### ISSUE TITLE
Did you really just copy Ping-Pong modules as your own?

### ISSUE THREAD

**Issue by Semmu** [nWidart/laravel-modules#1]
It really seems so...

https://github.com/pingpong-labs/modules

**Comment by nWidart** [comment]
As you could read in the readme yes, with the reasons.

**Comment by Semmu** [comment]
You should have forked it to give credit.

**Comment by nWidart** [comment]
If you're not aware, that's what I did for over a year. AsgardCMS used a fork for that long. I've tried to contact the author to have access to help maintain his package, never got a response.

Credit is given in the readme.

**Comment by adelowo** [comment]
Credit was also given to `ping-pong` in the License File

**Comment by pelmered** [comment]
Great that you started to maintain this module!

However, you probably should have kept all the commits from the original repository to keep the history intact and give credit for the previous contributions in the git history.
