### ISSUE TITLE
api urls in nWidart Modules is not working but outside api route is working

### ISSUE THREAD

**Issue by Rajath-Rexav** [nWidart/laravel-modules#1000]
![moduleroute](https://user-images.githubusercontent.com/66107430/84532211-705ef580-ad03-11ea-9aef-af95ae269ed4.png)

its in the route list but not working

**Comment by nWidart** [comment]
Hi,

Api routes are normal routes in laravel. All routes work in modules.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
