### ISSUE TITLE
How to Create, Register and Use middleware with modules?

### ISSUE THREAD

**Issue by chintanBeladiya** [nWidart/laravel-modules#1005]
I have created one search module with my laravel project Now i need to allow only authenticated user to visit URLs on this search module

If i use Main project midlleware with this Search module then it working fine
But how can i define and use midlleware with that Search Module

I haven't found much document on this thing so can any one plz guide me

**Comment by nWidart** [comment]
You can register middleware using `$this->middleware()` function inside your service provider.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by gfernandez-me** [comment]
> You can register middleware using `$this->middleware()` function inside your service provider.

Can you make an example? For me isn't working
