### ISSUE TITLE
How to specify ‘locations (config/modules.php )’ to create a module?

### ISSUE THREAD

**Issue by FrankDiao** [nWidart/laravel-modules#1006]
**I want to generate modules in the Examples directory.**
**what should I do?**

#### `config/modules.php`
```
    'locations' => [
        'app' => [
            'driver'    => 'local',
            'path'      => app_path('Modules'),
            'namespace' => 'App\\Modules\\',
            ......
            ],
        ],

        'examples' => [
            'driver'    => 'local',
            'path'      => app_path('Examples'),
            'namespace' => 'App\\Examples\\',
            ......
        ],
    ],
```

#### `Folder structure`
```
app/
bootstrap/
vendor/
Modules/
Examples/
```

#### `composer.json`
```
 "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Modules\\": "Modules/",
            "Examples\\": "Examples/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
```

**Comment by nWidart** [comment]
You change the module path config: https://github.com/nWidart/laravel-modules/blob/master/config/config.php#L73

**Comment by FrankDiao** [comment]
> You change the module path config: https://github.com/nWidart/laravel-modules/blob/master/config/config.php#L73

<br>

thank you for your reply.

I modified the `config.php` file according to your reply and it will work, 
but when I access the module that exists in the `Modules` directory, laravel will prompt me with a 404 error, I guess the routing file is not loaded .
What should I do?

`This is my modification to config.php`
```
[
   'namespace' => 'Examples',
   'paths' => [
      'modules' => base_path('Examples'),
      'assets' => public_path('examples'),
    ]
]
```

**Comment by nWidart** [comment]
That looks good, did you run a `composer dump-autoload` ?

**Comment by FrankDiao** [comment]
> That looks good, did you run a `composer dump-autoload` ?

Yes, I ran it, but it didn’t work

**Comment by nWidart** [comment]
Maybe clear your cache(s) etc. I'm able to have this work locally so I can only see caching issues as other people have had this already before.
