### ISSUE TITLE
lumen issue

### ISSUE THREAD

**Issue by fayroz** [nWidart/laravel-modules#1007]
Hi,
how can i fix this issue with lumen 7 
Class 'Illuminate\Foundation\Support\Providers\RouteServiceProvider' not found

**Comment by nWidart** [comment]
Hi,

Sorry, Lumen is not officially supported. 
You'll have to make it work on your own, or if somebody else can point you in the right direction.

**Comment by fayroz** [comment]
@nWidart  thanks

**Comment by arturmamedov** [comment]
> @nWidart  Are you mean that we not can create modules in lumen? 

You can if you can deal with this by your self, but the package laravel-modules don't do this officially
