### ISSUE TITLE
route:list is not working

### ISSUE THREAD

**Issue by corexz** [nWidart/laravel-modules#1008]
I am using version 5 on laravel 5.8 for an old project

I tried to check some routes with `route:list` artisan command ,it displays nothing.

After I removed `parent::boot()` from `RouteServiceProvider.php` in `app/Providers `
the commands `route:list` work again.

I tried to list all routes using `Route::getRoutes()` and this works fine.

**Comment by nWidart** [comment]
Hi,

That version is not supported anymore.
Not sure what's happening on your app, but you can debug it and see what the parent does, why does it affect module loading etc.
