### ISSUE TITLE
Read config value in view.

### ISSUE THREAD

**Issue by ivarledgis** [nWidart/laravel-modules#1009]
I have a Blog module and i have a config file in it . i want to display the value of config on the view . but i am not able to do it ..
i tired  .. {{ config('blog::config.name') }}
	{{ Config::get('blog::config.name') }}
didnt work. pls can anyone help me with this ?

**Comment by narik41** [comment]
Make sure your module service provider publishes and merges the config file with a Laravel. For this,

Publish the config file using in your module service provider under registerConfig method: 

 ```$this->publishes([
            module_path($this->moduleName, 'Config/name.php') => config_path('name.php'),
        ], 'config');```

And merge the config file using : 
```$this->mergeConfigFrom(
            module_path($this->moduleName, 'Config/name.php'), 'name'
        );```

Now, you can access the config file by:
``` config("name.key") ```
