### ISSUE TITLE
Extending from master layout(view)

### ISSUE THREAD

**Issue by abiodunjames** [nWidart/laravel-modules#101]
I just discovered this package. It's awesome but how can I extend a layout view from a child view. Since each module has its own views folder, I would like to have a master layout that can be extended by all other views in each module. How is this possible?

**Comment by mikemand** [comment]
If you put a view into Laravel's original `resources/views` directory, you can still access it from anywhere like normal. Just omit the namespace part. (E.g. the part before `::`, as well as the double colon.)

**Comment by adelowo** [comment]
Hey @abiodunjames You can create a `Core` module. Then add the views to the `core` module. Then have your view files in other modules extend it. `@extends("core::layout.main")`

**Comment by abiodunjames** [comment]
@mikemand Nice one. I did that it worked. @adelowo  Thanks

**Comment by J4si3k** [comment]
Is there any way to extend the view from laravel root views directory? I don't really like the "core module" approach

**Comment by nWidart** [comment]
I belive you can just use `@extends("layout.main")` in that case.

**Comment by fadilmalik** [comment]
I tried to take from the root view but an error appeared with 'View [layouts.main] not found.'

**Comment by efronpaduansi** [comment]
Thanks for all.
