### ISSUE TITLE
Route not found after optimize

### ISSUE THREAD

**Issue by folkevil** [nWidart/laravel-modules#1013]
Hi, 
I'm using laravel-modules for my project, everything is ok unless I'm using 

`php artisan optimize`

or I run Laravel project with Swoole server, and it showed "'home' route is not found" while it still exists. If I run:

`php artisan route:clear`

everything is normal. Does any suggestion please?

**Comment by nWidart** [comment]
Hi,

I haven't used swoole at all so I don't know what exactly could happen here. 
Probably best to debug this on your side with laravel, and see where/why the routes go missing after the optimize.

**Comment by folkevil** [comment]
> Hi,
> 
> I haven't used swoole at all so I don't know what exactly could happen here.
> Probably best to debug this on your side with laravel, and see where/why the routes go missing after the optimize.

Hi,

I got this problem not only with Swoole, even with a normal Laravel project + laravel-modules, everything work fine if I run without route cache, only get that problem if run "php artisan optimize/php artisan route:cache".

When I run "php artisan route:cache", then run "php artisan route:list", routes in modules didn't been registered.

**Comment by irfanyy** [comment]
Hi,
You can try this;
CACHE_DRIVER=file to change => CACHE_DRIVER=array
I hope it works.

**Comment by irfanyy** [comment]
Hi,
You can try this;
CACHE_DRIVER=file to change => CACHE_DRIVER=array
After, you should clear to folder "bootstrap / cache"
I hope it works.

**Comment by hsynnt** [comment]
> > Hi,
> > I haven't used swoole at all so I don't know what exactly could happen here.
> > Probably best to debug this on your side with laravel, and see where/why the routes go missing after the optimize.
> 
> Hi,
> 
> I got this problem not only with Swoole, even with a normal Laravel project + laravel-modules, everything work fine if I run without route cache, only get that problem if run "php artisan optimize/php artisan route:cache".
> 
> When I run "php artisan route:cache", then run "php artisan route:list", routes in modules didn't been registered.

Could you resolve this problem ? I tried to fix, but I dont

**Comment by emreakay** [comment]
i got similar problem

**Comment by EslamTeleb1** [comment]
Also me got the sanme problem in pure laravel project

**Comment by ithuis** [comment]
had this problem.. turns out the cached routes are loaded  in   "booted". 
i was using routes in the modules "boot" function. 

wrapping code works

```
  $this->app->booted(
            function () {
               // use routes
           }
);
```
