### ISSUE TITLE
Make listener CLI with --event flag wrong namespace

### ISSUE THREAD

**Issue by Norgul** [nWidart/laravel-modules#1017]
Using the following:

    php artisan module:make-listener SendsEmails Email --event=EmailInitialized --queued

produces the right class, however it is referencing:

    use Modules\Email\Listeners\Events\EmailInitialized;

instead of 

    use Modules\Email\Events\EmailInitialized;

**Comment by nWidart** [comment]
Thanks, this has been fixed in the linked PR. 👍
