### ISSUE TITLE
Laravel Mix issues 

### ISSUE THREAD

**Issue by virgiltu** [nWidart/laravel-modules#1019]
I am trying to run laravel mix, however I am a bit confused on this. 

I guess we have to run npm install for all modules individually am I correct? Sadly this would make add 130mb just for one module to the project, If I have multiple modules it will get to 500mb only for a few of them. 

Maybe I am understanding this wrong but I just want to make sure I understood this correct.

**Comment by livevasiliy** [comment]
@virgiltu Yes, you correct to understand. I do in my project in each **ENABLED** modules to make ```npm install``` or ``` yarn```

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
