### ISSUE TITLE
[Feature Request] Can you add livewire stubs and livewire command support?

### ISSUE THREAD

**Issue by kevyworks** [nWidart/laravel-modules#1021]

**Comment by nWidart** [comment]
Hi,

Hmm I don't know about this, not a fan of adding 3rd party stubs to this package.
Maybe an idea would be to create a new package that adds this functionality.

An easier way if you want this fast, you can wrap the module generation and add any custom files and templates on your side. This is what I did in AsgardCMS.

**Comment by kevyworks** [comment]
@nWidart Hi, thanks! right now its exactly what Im doing, adding those components manually. Some did express the ability to customize the path for livewire as how ever I do, it adds `app/` to the path.. because if that is possible, anyone extending could have no problem. I guess i'll push this to livewire instead.

**Comment by nWidart** [comment]
Hm indeed if livewire hardcode `app/` on their end it will have to be configurable on their side to make it easier.

**Comment by kevyworks** [comment]
@nWidart Hi, do you have any suggestion if we can create our own stubs and make custom commands, I tried to post a working example at liveware discussions (https://github.com/livewire/livewire/discussions/1267) but seems ignored.

My initial view was its fine to manually create this, or if I create my own command like a central `UiComponent` Module but this negates the modularity concept. 

And if I do just that above as the project grows, it would be better if modules could have there own components which other modules may wish to use.

Any thoughts?

**Comment by xkiller838** [comment]
mmm no me parece q deberias agregar livewire por defecto seria mejor q dejaras libre de si desea trabajar con livewire o vuejs o  los demas me gusta mucho este paquete aunq al comienzo no entendi como poder hacer q se ejecute la documentación no es muy clara si pudieras hacer un video de youtube almenos con el crud de laravel o login y registro usando el paquete ayudaria muchoo
