### ISSUE TITLE
unable to use other package command inside module

### ISSUE THREAD

**Issue by kathmandu1** [nWidart/laravel-modules#1025]
sir, i want to use command of matwebsite\excel comman like make:export class_name --model=targrt_modal 
 i want to use like php artisan module:make-export Claas_name --model=target-model  target_module_name

when i hit above command it should generate Expot folder and Export class name, if i was not wrong please tell me way to generate  this kind of folder inside module, thanks  in advance

**Comment by nWidart** [comment]
Hi, other package won't knnow to generate the file in a module. You will have to move the file to the module after generating it.
