### ISSUE TITLE
how to make model entity from command line

### ISSUE THREAD

**Issue by webafra** [nWidart/laravel-modules#1027]
hello.

i want make model form a module but run this command , i get error :
php artisan module:make-model User

befor make-model command , i run this command to make User module:
php artisan module:model User

![image](https://user-images.githubusercontent.com/8689072/88197972-6dd3b200-cc58-11ea-8055-3cdaffa3e935.png)

User Module folders: 
![image](https://user-images.githubusercontent.com/8689072/88198223-be4b0f80-cc58-11ea-8fa5-230521ee96e6.png)

please help me to make User model on User module .

**Comment by nWidart** [comment]
Hi, you need to use `php artisan module:make model User User`

Running `php artisan module:make model --help` would have helped you.
The documentation would have helped you too: https://nwidart.com/laravel-modules/v6/advanced-tools/artisan-commands#modulemake-model

**Comment by admiral9200** [comment]
Thank you very much
