### ISSUE TITLE
Auth Views not found

### ISSUE THREAD

**Issue by abiodunjames** [nWidart/laravel-modules#103]
By default, laravel creates authentication for you which is fine so I decided to create a module named 'Authentication' and moved laravel 'User' model to Authentication module's Entitities  and 'AuthController'  to Controllers' 

and  were properly namespaced . Auth views, I generated by running `php artisan make:auth`  were moved to views' folder in the module.
I get this error when I try to access it. Is like laravel is still going to default view folder. How I can I tackle this error?

![error](https://cloud.githubusercontent.com/assets/14722744/21100747/01882a00-c076-11e6-9a06-dab23918c3f7.PNG)
![arrangemnt](https://cloud.githubusercontent.com/assets/14722744/21100872/96690e64-c076-11e6-9230-fd884975508a.PNG)
![arrangement2](https://cloud.githubusercontent.com/assets/14722744/21100887/a955cb84-c076-11e6-9c2b-4a794f276eb3.PNG)

**Comment by adelowo** [comment]
What does your controller look like ? 

it should be something like `return view("module::auth.login")` not `return view('auth.login')`

**Comment by abiodunjames** [comment]
@adelowo Great. I figured
