### ISSUE TITLE
get database connection from config() when --database option is not present in module:migrate & module:seed commands

### ISSUE THREAD

**Issue by wakjoko** [nWidart/laravel-modules#1035]
Hi @nWidart ,

I found that you will only set the database when the --database option is present in the command.

You already have the `Config/config.php` of each module being loaded into `config()` which can be used to set the database connection there.

I'm suggesting that we add a fallback if the --database option is not provided, we should get the database connection from the `config('$module')`.

Most of large projects usually will have multiple database connections defined in `app/config/database.php` and in your modular architecture, I found that we can define it in `Config/config.php` of each module.

And that was awesome that I can have dedicated database per module, thanks to your great package.. thumbs up!

My modules is more laravel friendly as I have few files in `Config` directory like `database.php` for example.
Then I can get the database connection with `config('$module.database.default')` and I have `.env` in each modules to store the actual database connection.

I would like to hear your thoughts before going further.

Thanks.

**Comment by nWidart** [comment]
Hi,

This option should not be needed by default. It's only needed if you have multiple connections.
