### ISSUE TITLE
What is different between $module->enable() and $module->setActive()

### ISSUE THREAD

**Issue by phuclh** [nWidart/laravel-modules#1036]
I just found this great package yesterday and I really like this. Thank you for making this great package.

I have a question about what is different between `$module->enable()` and `$module->setActive()`?

I tried to run `$module->isEnabled()` after run `$module->enable()` or `$module->setActive()`. Both of cases return `true`. Is `$module->enable()` an alias of `$module->setActive()` or they have some different points that I missed?

**Comment by rcbgalido** [comment]
With ```setActive```, you should pass a boolean that indicates the active state to be set for the module. Basically, ```$module->enable()``` is equivalent to ```$module->setActive(true)``` and ```$module->disable()``` is equivalent to ```$module->setActive(false)```.
