### ISSUE TITLE
The Mix manifest does not exist, in production environment

### ISSUE THREAD

**Issue by parth391** [nWidart/laravel-modules#1038]
Hello,

I am trying to deploy my app on heroku, in production mode.

I did run following commends.

`composer install --optimize-autoloader --no-dev`
`npm install && npm run production`
`composer dump-autoload`

I am getting bellow error.
![Screenshot](https://user-images.githubusercontent.com/4966579/90285531-bebe7b00-de91-11ea-915b-9318c759b478.png)

**Comment by nWidart** [comment]
This sounds more related to laravel itself.
