### ISSUE TITLE
[QUESTION] [Migrations] migrate only default migrations

### ISSUE THREAD

**Issue by gfernandez-me** [nWidart/laravel-modules#1039]
Him

Do you have any option of running only standard migrations and not running migration modules? The only way is to disable all modules to run the migration and activate it again?

Thank you

**Comment by nWidart** [comment]
Hi,

There is no such feature out of the box no.
Maybe if you run `php artisan migrate` it wont see the module migrations.
Otherwise you can specify a folder to this command if I'm not mistaken.
