### ISSUE TITLE
Do modules prevent non-used module code from running to increase app performance?

### ISSUE THREAD

**Issue by jasondavis** [nWidart/laravel-modules#104]
I am building a l large scale PHP Laravel App. 
It is an app for Developers which consists of many sub-apps/modules.

For example a 

- **Bookmarks app** similar to **PinBoard**
- **Notebook app** similar to **Evernote**,
- **Code Snippets app**,
-  **RSS Feed Reader**
- about **30 more sub-app/modules** all in 1 large Laravel Web Developer App.

My question is about performance of using this Module package.

As generally only 1 module is used at a time by the user, does this system prevent all the other modules code from initiating and running so only the active module code is ran or does it run everything?

**Comment by nWidart** [comment]
Hello,

It will boot all the modules. However this isn't an issue. I've seen reports from users using many modules as well and still have an app load below <100ms.
