### ISSUE TITLE
Remove "Str::studly" name transformation from module:seed

### ISSUE THREAD

**Issue by vladamir** [nWidart/laravel-modules#1040]
I have problem when I call `module:seed my_module`. I have underscore in my module name and it can't be found.  

Is it possible to remove this line `$name = Str::studly($name);`?
https://github.com/nWidart/laravel-modules/blob/master/src/Commands/SeedCommand.php#L42

**Comment by nWidart** [comment]
Hi,

In general I would avoid using underscored in module names, prefer `camelCase` or `PascalCase` if possible.
