### ISSUE TITLE
Route not found after run optimize

### ISSUE THREAD

**Issue by folkevil** [nWidart/laravel-modules#1041]
Hi,

Sorry for re-open this issue, but with a normal Laravel project + laravel-modules, everything work fine if I run without route cache, but if I run 

`php artisan optimize`

or

`php artisan route:cache`

routes in modules not found. I tried to resolve but still don't know why. Everything back to normal if I clear route cache (I guess problem at route:cache command ?).

One more thing, I got a similar problem with "tightenco/ziggy", if I run command:

`php artisan ziggy:generate `
 
In Zyggy's generated file, it didn't contains routes of modules, I think it's same problem. In some ways, routes didn't been registered.

**Comment by nWidart** [comment]
Hi,

The caching this is weird, I've seen it work before. 
I've used the Ziggy routes project and if I remember correctly it did see the module routes.

A thing to check for both issues, is loading order. Maybe the routes in modules are loaded to late vs when those methods are called.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by ctf0** [comment]
am also seeing the same issue, it even give error when trying `config:cache`, any way to debug the reason ?

**Comment by ossycodes** [comment]
@nWidart please I am currently facing this issue

**Comment by alvarez25leo** [comment]
@nWidart please I am currently facing this issue
