### ISSUE TITLE
Event Broadcasting not working

### ISSUE THREAD

**Issue by dev-developer987** [nWidart/laravel-modules#1042]
hi 
I am working on a chat application and creating an event in module/events directory to broadcast when there is a new message, and receiving that using laravel echo, but unfortunately laravel echo listen event is not triggered after broadcast. i have verified my code by creating another broadcast event in root (App/Events) and its working fine there. could you please help me for this.
thanks

**Comment by nWidart** [comment]
Hi,
I've done event broadcasting with laravel echo in modules before so I'm sure it's possible.
I'm guessing there's a config / API to register events from within modules.

**Comment by omar-lk** [comment]
> Hi,
> I've done event broadcasting with laravel echo in modules before so I'm sure it's possible.
> I'm guessing there's a config / API to register events from within modules.

sure i have the some problem can you be more specific please
