### ISSUE TITLE
Laravel vue spa app

### ISSUE THREAD

**Issue by hkmsadek** [nWidart/laravel-modules#1046]
I am curious if its possible to add vue.js project inside the modules. I see I can do that individually, but I have to keep running the module npm run watch. the problem is, if you work with more than few modules at a time, then you have to run all the modules in separate terminal. Another problem is, they compile js in their own folder. How can we combine them together in a big js file?

**Comment by nWidart** [comment]
Hi,

Yes it's possible, you can look at the code in [AsgardCMS](https://github.com/AsgardCms/Platform). If I remember correctly, the modules publish their assets, and the JS watcher watches the published directory to compile it there.

**Comment by nafeeur10** [comment]
Hello @nWidart,
Like @AsgardCMS how can I make a Module like Theme in my Root directory?
Is it possible to create a Module in Root Directory?

Thanks
Nafeeur

**Comment by nWidart** [comment]
You can look at how I do it in asgardcms. It's not using modules
