### ISSUE TITLE
Assets sub folders

### ISSUE THREAD

**Issue by nhg2016** [nWidart/laravel-modules#105]
Hi,

This is possible out of scope, but would it be possible to created Assets sub folders when generating modules (e.g. css, js, img)?  Perhaps adding it as a option  when generating a new module?

Any thoughts on this?

Thanks

Nhg

**Comment by lchoate** [comment]
I'm not in favor of that idea considering most of my modules don't actually need additional assets, so I'd be creating a slew of empty directories. You can already put your subfolders in the modules/*module*/Assets directory and when you do:

    php artisan module:publish module

It will place all your extra assets in the public/modules/*module*/ directory.
