### ISSUE TITLE
Error after creating a module

### ISSUE THREAD

**Issue by juanklayd** [nWidart/laravel-modules#1051]
Everytime I finished creating a module, I can't do composer dump-autoload or any artisan commands
![1 code](https://user-images.githubusercontent.com/37618145/92635072-d7db1000-f307-11ea-8def-aa936c9ee7ce.JPG)

**Comment by midhunmonachan** [comment]
I changed line 6 of `{ModuleName}\Providers\{ModuleName}ServiceProvider.php` file from

`use Illuminate\Database\Eloquent\Factory;` to 
`use Illuminate\Database\Eloquent\Factories\Factory;`

**Comment by juanklayd** [comment]
I also changed it but this is what it says after
[image: image.png]

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by juanklayd** [comment]
I also changed it but this is what it says after
![Capture](https://user-images.githubusercontent.com/37618145/92673528-e64c1a80-f34d-11ea-8abc-8728adb332d8.JPG)

**Comment by nWidart** [comment]
Are you using laravel 8? Support has not been made yet for it.

**Comment by juanklayd** [comment]
Oh okay. Yes, I'm using Laravel 8. Will use an older version then. Looking forward for the update. Thank you!
