### ISSUE TITLE
Is it possible to create module in two different folder?

### ISSUE THREAD

**Issue by shankhadevpadam** [nWidart/laravel-modules#1053]
I want to create a module in two different folders one in default Modules folder and another in theme folder.

**Comment by di1606** [comment]
why? what's the point?

**Comment by shankhadevpadam** [comment]
I want to create theme module outside of module folder.

**Comment by backstageel** [comment]
I dont think that is possible right now

**Comment by nWidart** [comment]
It isn't indeed, and doubt it would be something worth support at this time.
