### ISSUE TITLE
Question: Bind modules to userroles ?

### ISSUE THREAD

**Issue by m-behr** [nWidart/laravel-modules#106]
Hi there,
before I start further investigations in that topic, I would like to ask if the following is basically possible. 

The goal is to assign modules to a userrole. If a user with a specified role signs in, all modules which are available to that role getting accessible to the user, others not. 
The role-module relation is stored in the database.

Thanks in advance!

Greetings
Michael

**Comment by nWidart** [comment]
This isn't possible by default. However you can customise it so that it works as you wish. For instance by only displaying certain modules depending on the role & permission.
