### ISSUE TITLE
Config::get() returns always null

### ISSUE THREAD

**Issue by nessor** [nWidart/laravel-modules#1062]
Hello everyone,

i'm not quite sure if this is a bug or if i'm doing something wrong. 
I have a module called ProtIT. Now I want to access the name of the module from the config in a module class.

The config looks like this:
```php
<?php

return [
    'name' => 'ProtIT',
];
```

However, no matter how I try to access the name, I always get `null` back
```php
Config::get('protit.name');
Config::get('ProtIT.name');
Config::get('protit::name');
Config::get('ProtIT::name');
```

Does anyone have an idea what this might be due to?

**Comment by nWidart** [comment]
Hi,

You need to check how you defined your config namespace in your module service provider. You should see there how it's called, and thus how you can reference it.
