### ISSUE TITLE
use trans in nWdart 

### ISSUE THREAD

**Issue by rezasrk** [nWidart/laravel-modules#1063]
hi 
I want use localization in module user
 
I have User Module 

my Resource directory exists this file   : 
auth.php

I use  
```php 
trans('user::auth.message-login')
```
but not working

**Comment by remzikocak** [comment]
Localization is supported and will load your language files. Make sure you put them in active local's folder e.g "Resources/lang/en/auth.php"

**Comment by rezasrk** [comment]
> Localization is supported and will load your language files. Make sure you put them in active local's folder e.g "Resources/lang/en/auth.php"

Thanks
I am forgot created en directoryy
