### ISSUE TITLE
Is Laravel 8 supported?

### ISSUE THREAD

**Issue by FoksVHox** [nWidart/laravel-modules#1065]
Title says everything

**Comment by roldandvg** [comment]
@nWidart waiting for laravel 8 support. Is there an estimated date for the update? Thank you

**Comment by zofe** [comment]
as workaround:  just comment public **registerFactories()** inside "ModuleName"ServiceProvider.php

**Comment by FoksVHox** [comment]
> as workaround: just comment **registerFactories()** inside "ModuleName"ServiceProvider.php

Haven't worked with Laravel Modules, but I'd like to know if Laravel 8 is supported as my application are a Laravel 8 application

**Comment by jay-gadhvi** [comment]
https://github.com/nWidart/laravel-modules/issues/1052#issue-698868960
can anyone help me with this?

**Comment by ckissi** [comment]
Nothing new regarding this?

**Comment by WS243593** [comment]
My upgrade process fails with this component, it would be nice to at least hear back from Nicolas.

**Comment by pktharindu** [comment]
Ping @nWidart 😄

**Comment by nWidart** [comment]
it's coming, sorry guys 😅

**Comment by FoksVHox** [comment]
> it's coming, sorry guys 😅

Got a timeline/deadline?

**Comment by ufhy** [comment]
still waiting... <g-emoji class="g-emoji" alias="sweat_smile" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f605.png">😅</g-emoji>

**Comment by nWidart** [comment]
[8.0](https://github.com/nWidart/laravel-modules/releases/tag/8.0.0) has been tagged.
