### ISSUE TITLE
 Target class [Illuminate\Database\Eloquent\Factory] does not exist.

### ISSUE THREAD

**Issue by cyberbaseza** [nWidart/laravel-modules#1066]
Hi Guys

Looking for assistance, am currently learning nWidart/laravel-modules to structure my application. Issues arise after creating Module and running the publish command.

I am getting the following exception

C:\~\Projects\LaravelModule\modularapp>php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"

   Illuminate\Contracts\Container\BindingResolutionException

  Target class [Illuminate\Database\Eloquent\Factory] does not exist.

  at C:\~\Projects\LaravelModule\modularapp\vendor\laravel\framework\src\Illuminate\Container\Container.php:812
    808▕
    809▕         try {
    810▕             $reflector = new ReflectionClass($concrete);
    811▕         } catch (ReflectionException $e) {
  ➜ 812▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    813▕         }
    814▕
    815▕         // If the type is not instantiable, the developer is attempting to resolve
    816▕         // an abstract type such as an Interface or Abstract Class and there is

  1   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Modules\Account\Providers\AccountServiceProvider))

  2   C:\~\Projects\LaravelModule\modularapp\vendor\laravel\framework\src\Illuminate\Container\Container.php:810
      ReflectionException::("Class Illuminate\Database\Eloquent\Factory does not exist")

**Comment by bojcheski** [comment]
Just install the `laravel/legacy-factories` package if you are using Factories, or simply comment the `$this->registerFactories();` inside `boot` method in each of your ModuleServiceProviders.

**Comment by jurnisa** [comment]
Thanks bojcheski

I will try both methods, i also searched on previous threads and found a fix, not sure if its best practice but it works. see the snipet below.

    public function registerFactories()
    {
        if (! app()->environment('production') && $this->app->runningInConsole()) {
            $this->loadFactoriesFrom(module_path($this->moduleName, '$FACTORIES_PATH$'));
        }
    }
this works and my only concern is its not done on the module creation as you have to manually update the Providers in the module. 

THanks

**Comment by truesteps** [comment]
https://github.com/nWidart/laravel-modules/issues/1050#issuecomment-700700957 Maybe a less hacky way to fix this issue :)

**Comment by nWidart** [comment]
Fixed in 8.0, supporting laravel 8.

**Comment by garbinmarcelo** [comment]
Hello, I'm upgrading Laravel from 7 to 8? are there any upgrade guidance documentation for Laravel Modules? Thanks

**Comment by AshutoshJha15** [comment]
If you are upgrading from laravel 7 to laravel 8 .
Use this composer require laravel/legacy-factories

**Comment by magic-thomas** [comment]
I upgraded from laravel 6 to laravel 10 .

` composer require laravel/legacy-factories` worked for me.

**Comment by lebresilien** [comment]
I facing same problem try to install poing/earmak. i don' know how to resolve it
