### ISSUE TITLE
Creating new variables from the RouteServiceProvider stub

### ISSUE THREAD

**Issue by seriousjelly** [nWidart/laravel-modules#1067]
Hi

What I am aiming to achieve is that for each `php artisan module:make` command, an 'admin' route group is created as well as the web and api groups. 

I have updated the `stubs.files` array to include my new routes file:
```
'stubs' => [
        'enabled' => false,
        'path' => base_path() . '/stubs/modules',
        'files' => [
            'routes/web' => 'Routes/web.php',
            'routes/api' => 'Routes/api.php',
            'routes/admin' => 'Routes/admin.php',
            'views/index' => 'Resources/views/index.blade.php',
        ...],
];
```

and begun modifying the `route-provider.stub` file, however, there are some variables being replaced here, and it looks like they are being built up in the `Nwidart\Modules\Commands\RouteProviderMakeCommand`:

```
    /**
     * Get template contents.
     *
     * @return string
     */
    protected function getTemplateContents()
    {
        $module = $this->laravel['modules']->findOrFail($this->getModuleName());

        return (new Stub('/route-provider.stub', [
            'NAMESPACE'            => $this->getClassNamespace($module),
            'CLASS'                => $this->getFileName(),
            'MODULE_NAMESPACE'     => $this->laravel['modules']->config('namespace'),
            'MODULE'               => $this->getModuleName(),
            'CONTROLLER_NAMESPACE' => $this->getControllerNameSpace(),
            'WEB_ROUTES_PATH'      => $this->getWebRoutesPath(),
            'API_ROUTES_PATH'      => $this->getApiRoutesPath(),
            'LOWER_NAME'           => $module->getLowerName(),
        ]))->render();
    }
```

Essentially, what I am looking to do is add a new one `ADMIN_ROUTES_PATH => $this->getAdminRoutesPath()`. 

Is there a way built in to handle this, or do I need to try to extend this class within my app (the issue there is that `$this->getControllerNamespace()` is private, so I can't override it? 

Any ideas or suggestions?

**Comment by nWidart** [comment]
Hi,

I did this in AsgardCMS by wrapping the module make command, by another command adding extra features like the one you're mentioning.

**Comment by lindo-llc** [comment]
I did that before. Nothing fancy here. 

All you need to do is to make a new command, with the same name, eg: `module:make` and register it so that Laravel would use it. Essentially what this will do is override the package command with your own. In there, just extend the base command class and override the `getTemplateContents()` function, essentially copy & paste the original code (because you can't really tap into the `Stub` array) + you desired extensions, such as `ADMIN_ROUTES_PATH`. 

This is how I had done before if I recall correctly

**Comment by seriousjelly** [comment]
Ah I got you, I didn't realise you could create a new command with the same name and it would overwrite the original! Great stuff. Thanks :)
