### ISSUE TITLE
Vendor Publish command copies all admin views to parent views.

### ISSUE THREAD

**Issue by jackkitley** [nWidart/laravel-modules#107]
Hello.

I ran php artisan vendor:publish and it did the following copy?

Copied Directory [/Modules/Admin/Resources/views] To [/resources/views/modules/admin]

TIA

**Comment by rhazen35** [comment]
Had the same, so that is what vendor:publish does apparently:)

**Comment by nWidart** [comment]
Indeed, that is the intended behaviour of _laravel_.
