### ISSUE TITLE
A way to disable/hide commands

### ISSUE THREAD

**Issue by lindo-llc** [nWidart/laravel-modules#1079]
Title.

Use case:
I am rewriting the whole application and integrating this package as core functionality. Therefore I am replacing all commands to use original names, such as: `module:make-model` to -> `make: model`. Therefore commands under the namespace `module` just makes a clutter

**Comment by nWidart** [comment]
This doesn't look like an issue for this package, but laravel instead. I don't think laravel allows this.

**Comment by lindo-llc** [comment]
`ConsoleServiceProvider.php`:
```
    /**
     * Register the commands.
     */
    public function register()
    {
          if(config('modules.use_commands')) {
               $this->commands($this->commands);
          }
    }
```

**Comment by nWidart** [comment]
We could indeed do that, you can open a PR for it if you want. 👍
