### ISSUE TITLE
Latest version can't support multiple routes in one module

### ISSUE THREAD

**Issue by ridwanskaterock** [nWidart/laravel-modules#108]
cant't support multiple routes in one module, 

i have module "Blog" 
and i have Http directory structure 
|-Http
|----Controllers
|----Middleware
|----Request
|----routes.php

i can make multiple routes in Blog module like webRoute.php, apiRoutes.php, 
and i have structure my blog module like this 
|-Http
|----Controllers
|----Middleware
|----Request
|----webRoutes.php
|----apiRoutes.php
|----moreRoutes.php

in current version this feature not avaiable

**Comment by adelowo** [comment]
I don't get this.. Route loading - especially with multiple files - isn't specific to this package... 

With that said, only a single route file is loaded by default -  `routes.php`.. And from what I can see, you don't have that file in your HTTP directory.. You would have to `require` your custom route files - webRoutes.php, fooroute.php, barroute.php - in the `map` method of your `RouteServiceProvider`.

**Comment by adelowo** [comment]
You can also require the other route files from `routes.php`

**Comment by nWidart** [comment]
As @adelowo said, this is specific to this package. You can setup mulitple route files using this package, I do this in AsgardCMS.

**Comment by ridwanskaterock** [comment]
yes could probably outsmart some of the code, but it is better if it is already available automatically on this repo.
so that each create a new module does not need to add code to set multiple route

**Comment by adelowo** [comment]
What I suggested would be the same thing you'd do in a plain Laravel installation -  one that doesn't use this package. This isn't a hack or something. 
Laravel's convention is to use a single route file, if you want something else, you'd have to make some edits.. 

I honestly think this is outside the scope of this package

**Comment by nWidart** [comment]
You can, with this repo, setup multiple routes files. In the `files` key of the `module.json` file.

**Comment by adelowo** [comment]
Oh @nWidart that didn't even come to my mind... That's another viable option

**Comment by ridwanskaterock** [comment]
okay i am append routes loader in module.json

like this, and it's working
"files": [
        "start.php",
        "Http/apiRoutes.php"
    ]

but it may be taken into consideration to add 3 route that is loaded by default
when making a module

with the route as follows

|--Routes
|----Api.php
|----Console.php
|----Web.php

because the final version is already installed by default laravel third route as above

**Comment by nWidart** [comment]
You can do this too.

I'll close this issue for now as this is possible.

**Comment by ercanertan** [comment]
You can do this request with my fork
[Check here](https://github.com/ercanertan/laravel-modules)

**Comment by nWidart** [comment]
Or natively with this package.
