### ISSUE TITLE
laravel optimize generates Symfony\Component\Finder\Exception\DirectoryNotFoundException

### ISSUE THREAD

**Issue by paulcocis** [nWidart/laravel-modules#1083]
The "/home/vagrant/code/dsw.local/resources/views/modules/dsw" directory does not exist.

 This is generated on php artisan optimize 
 
  Laravel 8, latest version of modules (8).

 This is generated by registerViews() from the Service Provider, any solutions for this?

**Comment by thursdaydan** [comment]
I'm having the same problem!
