### ISSUE TITLE
Add a module:make-component

### ISSUE THREAD

**Issue by FoksVHox** [nWidart/laravel-modules#1086]
Laravel has a component command, which is really awesome, and I think that people would like to see the same functionality in this package. 

My use case is that I'm making a Laravel vapor-like site, and I'd like to use the newly added dynamic-component in one of my modules.

**Comment by magic-thomas** [comment]
+1

**Comment by FoksVHox** [comment]
#1110 Fixes this issue

**Comment by FoksVHox** [comment]
Closed in 850931b
