### ISSUE TITLE
QUESTION - Database design with modules

### ISSUE THREAD

**Issue by albertatnerdbrain** [nWidart/laravel-modules#1092]
Hello,

thats not an that new problem. I read about it in other issues. But without propper solutions.

we want to use your library in our greenfield project. We have meanwhile relational database model. Now, we sepperated this tables logically (User, Product, ...) and made up 7 modules. But there are a lot of dependencies (constraints, crosstables, referential integrity) between these modules in the database. Now we are wondering how to make a migration without ordering the modules. We think this is also a DB design question. 

Our ideas on how to solve this problem, without changing the database model was to extract all constraints to one file and give them the ordernumber 10000. But this is not the ideal way we think. 

Is there a way to uncouple the relations between these modules but handle them carefully either? Our aim is to make migrations on one module without bothering of the others. Is this designable? If so, please share your sight of view to this problem.

We would be very happy.

**Comment by albertatnerdbrain** [comment]
Hello again. 

Another idea is (we are using eloquent), just to implement the relations in eloquent without foreign-keys and set events on the relations. So if eloquent determines an relation. An event will be sent. And every participent will update its relation. This idea came up to me a few seconds ago. And I will trace it... 

Does this sound like a solution? Please let's discuss this issue.

**Comment by nWidart** [comment]
Hi @albertatnerdbrain ,

I don't believe there should be any foreign keys between modules at all. One exception would be a user module for example.

If you have these foreign keys I would move these models in one single module. Group everything that belongs together.
