### ISSUE TITLE
composer install --no-dev error

### ISSUE THREAD

**Issue by stephenjason89** [nWidart/laravel-modules#1093]
im using
            "version": "7.2.0"

Everytime i try to instal composer install --no-dev i get
```
In DatabaseServiceProvider.php line 88:

  Class 'Faker\Factory' not found


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

if i remove Module folder then everything works as expected.
I don't know when it started but before it was working okay.

**Comment by nWidart** [comment]
Hi,

Looks like it's telling you to install faker.
