### ISSUE TITLE
Factory issues in Laravel 8

### ISSUE THREAD

**Issue by mauriciovillam** [nWidart/laravel-modules#1094]
Hey there! I might be wrong but I think the factory stub should be updated with the [new class format](https://laravel.com/docs/8.x/database-testing#writing-factories) introduced in Laravel 8.0?

If this is correct, I will gladly submit a PR.

**Comment by mauriciovillam** [comment]
On another hand, there is also an issue related with the new factory changes. The models should implement the [HasFactory](https://laravel.com/docs/8.x/database-testing#creating-models) trait and then Laravel will try to find the factory magically, based on the App namespace. 

Is it good practice to override that magic method and add support for modules namespace? Or are we forced to use the newFactory method on every model? Sounds kinda counter intuitive.

**Comment by Rezrazi** [comment]
I can confirm that Factory has issues on the current `8.0.0` build, even with both the classic definition and the new class format introduced in Laravel 8, seeding a module does not work anymore.

the new format for seeding an entity :
```php
\App\Models\User::factory(10)->create();
```

Adding the `HasFactory` trait to a module entity and trying to seed with the global `DatabaseSeeder` 
```php
class Author extends Model {
    use HasFactory;
    ...
}
```

```php
class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        \Modules\Author\Entities::factory(10)->create();
    }
}
```

Running `php artisan db:seed` Trace
```
   Error

  Class 'Database\Factories\Modules\Author\Entities\AuthorFactory' not found

  at \vendor\laravel\framework\src\Illuminate\Database\Eloquent\Factories\Factory.php:656
    652▕     public static function factoryForModel(string $modelName)
    653▕     {
    654▕         $factory = static::resolveFactoryName($modelName);
    655▕
  ➜ 656▕         return $factory::new();
    657▕     }
    658▕
    659▕     /**
    660▕      * Specify the callback that should be invoked to guess factory names based on dynamic relationship names.

  1   \vendor\laravel\framework\src\Illuminate\Database\Eloquent\Factories\HasFactory.php:15
      Illuminate\Database\Eloquent\Factories\Factory::factoryForModel()

  2   \database\seeders\DatabaseSeeder.php:17
      Modules\Manager\Entities\Manager::factory()
```

**Comment by mauriciovillam** [comment]
Yeah, that happens because this is how Laravel resolves the factory namespace by default:

```
    /**
     * Get the factory name for the given model name.
     *
     * @param  string  $modelName
     * @return string
     */
    public static function resolveFactoryName(string $modelName)
    {
        $resolver = static::$factoryNameResolver ?: function (string $modelName) {
            $modelName = Str::startsWith($modelName, 'App\\Models\\')
                ? Str::after($modelName, 'App\\Models\\')
                : Str::after($modelName, 'App\\');

            return static::$namespace.$modelName.'Factory';
        };

        return $resolver($modelName);
    }
```

So, in order to support the `Modules\{Module}` namespace you need to put this in your model:

```
    /**
     * Create a new factory instance for the model.
     *
     * @return \Illuminate\Database\Eloquent\Factories\Factory
     */
    protected static function newFactory()
    {
        return \Modules\Module\Database\Factories\ModelFactory::new();
    }
```

However, if this package doesn't supply this by default (which currently doesn't), we need to add that in every model that has a factory, which sounds like an annoying boilerplate.

**Comment by nWidart** [comment]
It could indeed be a could idea to add this to the generated model classes by default.

**Comment by renepardon** [comment]
I added the corresponding method to my model Tenant, which also contains the HasFactory namespace:

```
use HasFactory;
// ...
protected static function newFactory()
{
    return TenantFactory::new();
}
```

And inside the factory the model is referenced too. But I still receive errors like this when running my tests:

`InvalidArgumentException: Unable to locate factory for [Modules\Tenant\Entities\Tenant].`

I'm using laravel-modules v 8.2.0 with laravel framework 8.34.0

**Comment by Rezrazi** [comment]
> I added the corresponding method to my model Tenant, which also contains the HasFactory namespace:
> 
> ```
> use HasFactory;
> // ...
> protected static function newFactory()
> {
>     return TenantFactory::new();
> }
> ```
> 
> And inside the factory the model is referenced too. But I still receive errors like this when running my tests:
> 
> `InvalidArgumentException: Unable to locate factory for [Modules\Tenant\Entities\Tenant].`
> 
> I'm using laravel-modules v 8.2.0 with laravel framework 8.34.0

Make sure you import your `TenantFactory` class in your Model, and your Model in your `TenantFactory`

**Comment by mauriciovillam** [comment]
Maybe we can use something like this:

https://laravel.com/api/8.x/Illuminate/Database/Eloquent/Factories/Factory.html#method_guessFactoryNamesUsing

**Comment by renepardon** [comment]
> > I added the corresponding method to my model Tenant, which also contains the HasFactory namespace:
> > ```
> > use HasFactory;
> > // ...
> > protected static function newFactory()
> > {
> >     return TenantFactory::new();
> > }
> > ```
> > 
> > 
> > And inside the factory the model is referenced too. But I still receive errors like this when running my tests:
> > `InvalidArgumentException: Unable to locate factory for [Modules\Tenant\Entities\Tenant].`
> > I'm using laravel-modules v 8.2.0 with laravel framework 8.34.0
> 
> Make sure you import your `TenantFactory` class in your Model, and your Model in your `TenantFactory`

Did that. Unfortunately this is not the mistake :/

**Comment by MianSaleem** [comment]
You can try following in your ModuleServiceProvider's `boot` method

```php
use Illuminate\Database\Eloquent\Factories\Factory;

Factory::guessFactoryNamesUsing(function (string $modelName) {
    return 'Modules\\Module\\Database\\Factories\\' . class_basename($modelName) . 'Factory';
});
```

**Comment by raulpacheco2k** [comment]
> Yeah, that happens because this is how Laravel resolves the factory namespace by default:
> 
> ```
>     /**
>      * Get the factory name for the given model name.
>      *
>      * @param  string  $modelName
>      * @return string
>      */
>     public static function resolveFactoryName(string $modelName)
>     {
>         $resolver = static::$factoryNameResolver ?: function (string $modelName) {
>             $modelName = Str::startsWith($modelName, 'App\\Models\\')
>                 ? Str::after($modelName, 'App\\Models\\')
>                 : Str::after($modelName, 'App\\');
> 
>             return static::$namespace.$modelName.'Factory';
>         };
> 
>         return $resolver($modelName);
>     }
> ```
> 
> So, in order to support the `Modules\{Module}` namespace you need to put this in your model:
> 
> ```
>     /**
>      * Create a new factory instance for the model.
>      *
>      * @return \Illuminate\Database\Eloquent\Factories\Factory
>      */
>     protected static function newFactory()
>     {
>         return \Modules\Module\Database\Factories\ModelFactory::new();
>     }
> ```
> 
> However, if this package doesn't supply this by default (which currently doesn't), we need to add that in every model that has a factory, which sounds like an annoying boilerplate.

It worked like magic

**Comment by san4io** [comment]
Or you can try:
```
Factory::guessFactoryNamesUsing(function (string $modelName) {
      $moduleNamespace = Str::before($modelName,  '\\Entities');

      return sprintf("%s\\Database\\factories\\%sFactory", $moduleNamespace, class_basename($modelName));
});
```

**Comment by ahmadrio** [comment]
> You can try following in your ModuleServiceProvider's `boot` method
> 
> ```
> use Illuminate\Database\Eloquent\Factories\Factory;
> 
> Factory::guessFactoryNamesUsing(function (string $modelName) {
>     return 'Modules\\Module\\Database\\Factories\\' . class_basename($modelName) . 'Factory';
> });
> ```

thanks. it works & clean

**Comment by OsmairCoelhoGY** [comment]
> > Yeah, that happens because this is how Laravel resolves the factory namespace by default:
> > ```
> >     /**
> >      * Get the factory name for the given model name.
> >      *
> >      * @param  string  $modelName
> >      * @return string
> >      */
> >     public static function resolveFactoryName(string $modelName)
> >     {
> >         $resolver = static::$factoryNameResolver ?: function (string $modelName) {
> >             $modelName = Str::startsWith($modelName, 'App\\Models\\')
> >                 ? Str::after($modelName, 'App\\Models\\')
> >                 : Str::after($modelName, 'App\\');
> > 
> >             return static::$namespace.$modelName.'Factory';
> >         };
> > 
> >         return $resolver($modelName);
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So, in order to support the `Modules\{Module}` namespace you need to put this in your model:
> > ```
> >     /**
> >      * Create a new factory instance for the model.
> >      *
> >      * @return \Illuminate\Database\Eloquent\Factories\Factory
> >      */
> >     protected static function newFactory()
> >     {
> >         return \Modules\Module\Database\Factories\ModelFactory::new();
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, if this package doesn't supply this by default (which currently doesn't), we need to add that in every model that has a factory, which sounds like an annoying boilerplate.
> 
> It worked like magic

tranks @raulpacheco2k  I wrote my experience in https://github.com/nWidart/laravel-modules/issues/270#issuecomment-1570360657

**Comment by aon4o** [comment]
I think I found another solution to this problem.

Right now I am building a big system using Laravel Modules.
It has models in the `app/Models` dir, and in `modules/<Module>/Entities` directories in every module.
I didn't like the solution where I had to put a `newFactory()` method in each model, so I came up with this solution:
```php
<?php

declare(strict_types=1);

namespace App\Providers;

use Exception;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Str;
use Spatie\Translatable\Facades\Translatable;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        Translatable::fallback('en', true);
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        Paginator::defaultView('components/pagination');

        $this->registerFactories();
    }

    /**
     * Register Factories.
     */
    public function registerFactories(): void
    {
        Factory::guessFactoryNamesUsing(function (string $model) {
            $model_name = Str::afterLast($model, '\\');

            if (Str::startsWith($model, 'App\\Models')) {
                return "Database\\Factories\\{$model_name}Factory";
            }

            $modules_namespace = config('modules.namespace');

            if (Str::startsWith($model, "$modules_namespace\\")) {
                $entities_namespace = config('modules.paths.generator.model.path');
                $module_namespace = Str::before($model, "\\$entities_namespace\\$model_name");
                $factories_namespace = str_replace('/', '\\', config('modules.paths.generator.factory.path'));

                return "$module_namespace\\$factories_namespace\\{$model_name}Factory";
            }

            throw new Exception("Unable to locate factory for model: $model");
        });
    }
}
```

If a model comes from the default models dir, it searches a factory in the default dir for that.
If it comes from a module, it tries to find the corresponding factory dynamically by reading your custom modules config file.
And lastly, if there is no factory found it throws an exception.
