### ISSUE TITLE
How to add TailwindCSS in Each Module?

### ISSUE THREAD

**Issue by lavecart** [nWidart/laravel-modules#1096]
Hello,
Is it possible to use same `laravel-mix` for all Modules? I am using TailwindCSS for my Web App. For each Module will I have to use separate mix? 

Giving me an exception:
**Exception
Unable to locate Mix file: /css/category.css. (View: E:\xampp\htdocs\lavecart\Modules\Category\Resources\views\layouts\master.blade.php)**

I have created a public folder. Inside that folder I have created js and css folder.

```
const dotenvExpand = require('dotenv-expand');
dotenvExpand(require('dotenv').config({ path: '../../.env'/*, debug: true*/}));

const mix = require('laravel-mix');
require('laravel-mix-merge-manifest');

mix.setPublicPath('../../public').mergeManifest();

mix.js(__dirname + '/Resources/assets/js/app.js', 'js/category.js')
    .postCss('resources/css/app.css', 'css/category.css', [
        require('postcss-import'),
        require('tailwindcss')
    ]);

if (mix.inProduction()) {
    mix.version();
}
```

**Comment by nWidart** [comment]
I haven't used tailwind much so I could really tell you. 
I would assume just like any application though, I don't see why it wouldn't work.

**Comment by virgiltu** [comment]
> Hello, Is it possible to use same `laravel-mix` for all Modules? I am using TailwindCSS for my Web App. For each Module will I have to use separate mix?
> 
> Giving me an exception: **Exception Unable to locate Mix file: /css/category.css. (View: E:\xampp\htdocs\lavecart\Modules\Category\Resources\views\layouts\master.blade.php)**
> 
> I have created a public folder. Inside that folder I have created js and css folder.
> 
> ```
> const dotenvExpand = require('dotenv-expand');
> dotenvExpand(require('dotenv').config({ path: '../../.env'/*, debug: true*/}));
> 
> const mix = require('laravel-mix');
> require('laravel-mix-merge-manifest');
> 
> mix.setPublicPath('../../public').mergeManifest();
> 
> mix.js(__dirname + '/Resources/assets/js/app.js', 'js/category.js')
>     .postCss('resources/css/app.css', 'css/category.css', [
>         require('postcss-import'),
>         require('tailwindcss')
>     ]);
> 
> if (mix.inProduction()) {
>     mix.version();
> }
> ```

Did you figured this out? I can get Tailwind to see all the folder but not the Modules

**Comment by virgiltu** [comment]
For anybody that is looking for this just add this to your mail config.js 

`module.exports = {
  mode: 'jit',
  purge: [
    './Modules/**/*.blade.php',
    './resources/views/**/*.blade.php',
    './resources/css/**/*.css',
  ],
  theme: {
    extend: {}
  },
  variants: {},
  plugins: [
    require('@tailwindcss/ui'),
    require('@tailwindcss/jit'),
  ]
}`

**Comment by cschra** [comment]
with tailwind v.3 the syntax changed a bit:
base tailwind.config.js file would look like this now:
```js 
module.exports = {
    content: [
      "./resources/**/*.blade.php",
      "./resources/**/*.js",
      "./resources/**/*.vue",
      './modules/**/*.blade.php', // this is the important line
    ],
    theme: {
      extend: {
        //
      }
    },
    plugins: [],
  }
```
