### ISSUE TITLE
mcamara/laravel-localization

### ISSUE THREAD

**Issue by mrmarchone** [nWidart/laravel-modules#1097]
Need help ! My Module Route Can't working with mcamara

**Comment by FoksVHox** [comment]
Please provide more information, we can't solve your issue from what you wrote so far.

**Comment by mrmarchone** [comment]
mcamara working only default laravel web.php but in Route/web.php Not Working , is that clear ?

**Comment by mrmarchone** [comment]
Error happen when i add prefix() in RouteServiceProvidder in Module . it's working now Thank u 👍
