### ISSUE TITLE
QUESTION - How do I export mail module for customisation?

### ISSUE THREAD

**Issue by WS243593** [nWidart/laravel-modules#1098]
Essentially I want to do what is already available in standard Laravel: 
> Customizing The Components
You may export all of the Markdown mail components to your own application for customization. To export the components, use the vendor:publish Artisan command to publish the laravel-mail asset tag:

> php artisan vendor:publish --tag=laravel-mail
This command will publish the Markdown mail components to the resources/views/vendor/mail directory. The mail directory will contain an html and a text directory, each containing their respective representations of every available component. You are free to customize these components however you like.

Is there a native way of doing this in modules or is there another way I can add css to the mail template? 

I do apologise if I overlooked something in the exiting docs or just being plain stupid.

**Comment by nWidart** [comment]
You can just use regular templates for mails in modules if you wish. Or use the ones published by laravel in your modules, too.
You could publish them, and move them over to the module.

**Comment by WS243593** [comment]
@nWidart Thank you, that makes sense!
