### ISSUE TITLE
Will a modular app still work with packages like Passport and others....

### ISSUE THREAD

**Issue by jasondavis** [nWidart/laravel-modules#111]
Will an app that uses libraries like Socialite and Passport OAuth API break by installing and using this modular package?

I guess the real question would be, does the existing default Laravel folder structure still work in addition to the new Modular folder structure for new modules?

I am building what I believe is a game changer dream app for web developers that will consist of 30-40 web dev related modules.

So right now the path I am on will have hundreds of files in my Laravel folder structure so I really need a modular setup like this package.

Each of my modules has 5-10 files and I want other developers to be able to build there own modules in my app and share them too so being able to have all of a modules files under the same folder for each module is really what I need!

I am just afraid of breaking what I have so far with my Passport API with OAuth authentication and Socialite integration for social accounts registering my my laravel accounts as well as other packages like a Teams and Friendship package.

**Comment by armababy** [comment]
Nothing will break, modules have seperate namespace. You can use whatever packages you want inside modules and outside modules.
