### ISSUE TITLE
Multi tenancy

### ISSUE THREAD

**Issue by wyklif** [nWidart/laravel-modules#1111]
Hello, Thanks for the brilliant module, How do I achieve multi-tenancy with this package and have different databases for each module.

Thanks

**Comment by nWidart** [comment]
Hi,

I had to do this on a project in the past, you will have to develop the logic to have multiple db connections and be able to switch them on the fly.
It's not on the package level that this happens but your application level.

**Comment by wyklif** [comment]
Hi thanks for the swift reply, can i use somethinhg like https://github.com/spatie/laravel-multitenancy to achieve this? in conjunction with your package
