### ISSUE TITLE
error with factory in Laravel 8.x

### ISSUE THREAD

**Issue by di1606** [nWidart/laravel-modules#1112]
I am currently updating the version of Laravel and the Laravel-module package. I noticed when I launch the command `php artisan module:make-factory FactoryName Blog` it doesn't produce a class like the official Laravel documentation. Moreover, the documentation of the command `php artisan module:make-factory FactoryName Blog` doesn't follow the Laravel convention, it should rather be `...NameFactory...` .

These remarks I made, is it normal for the moment?

**Comment by TheGlenn88** [comment]
Laravel have provided a package to help with the upgrade. 

If do

`composer require laravel/legacy-factories`

That should fix your issue.

**Comment by nWidart** [comment]
Hi,
This has been tagged as 8.1
