### ISSUE TITLE
Tags for 7.0 are not up2date with code from branch 7.0

### ISSUE THREAD

**Issue by tomhatzer** [nWidart/laravel-modules#1113]
Hi!

I just saw that there are changes in branch 7.0 that have no tag yet, including at least one bug fix.

Would it be possible to tag a new release for 7.0 with the latest code from 7.0 branch?

Thank you very much and have a great day!

Best wishes
Tom

**Comment by nWidart** [comment]
Hi,

Thanks for reporting this, I've tagged 7.3: https://github.com/nWidart/laravel-modules/releases/tag/7.3.0
