### ISSUE TITLE
Enabling Modules create in previous version for Laravel 7, getting error

### ISSUE THREAD

**Issue by desyashasyi** [nWidart/laravel-modules#1115]
I have a module created in previous version of Laravel-Modules for Laravel 7. However, when i moved to Laravel 8 with this command _php artisan module:enable ModuleName_, i am getting this error.

![image](https://user-images.githubusercontent.com/48233515/97974186-d30f7580-1df9-11eb-8e42-723f358bad70.png)

How to solve the error?

**Comment by di1606** [comment]
Recently I did the update and I had the same error as you.

I have not installed the `laravel/legacy-factories` package proposed by Laravel to continue using the factories. I have changed my factories into classes. I have commented this code `$this->registerFactories()` which inside of the class `YourModuleServiceProvider`

**Comment by desyashasyi** [comment]
@di1606 Thank you very much. I will try your solution.
