### ISSUE TITLE
Laravel 8 Route::apiResource does not resolve if use statement is present

### ISSUE THREAD

**Issue by jtomek** [nWidart/laravel-modules#1116]
Hello,

Route::apiResource does not resolve its routes correctly under Laravel 8 if the use statement is present.

If I change the old 

```Route::apiResource('data-types', 'DataTypeController');``` into the new

```
<?php
use Modules\Data\Http\Controllers\DataTypeController;
... 
Route::apiResource('data-types', DataTypeController::class);
``` 

It throws the following error: 
```Target class [Modules\Data\Http\Controllers\Modules\Data\Http\Controllers\DataTypeController] does not exist```

This works:

```
<?php
// use Modules\Data\Http\Controllers\DataTypeController;
... 
Route::apiResource('data-types', DataTypeController::class);
``` 

And this works too:

```
<?php 
use Modules\Data\Http\Controllers\DataTypeController;
..
Route::get('data-types', [DataTypeController::class, 'index']);
```

Edit: Correction last example.

**Comment by exceedweb-taggers** [comment]
me too bro. What happened in 8.X??

**Comment by softrain73** [comment]
me too bro. What happened in 8.X now??

**Comment by nWidart** [comment]
check the route service provider, if you have a namespace there, you don't need to use anything.

**Comment by exceedweb-taggers** [comment]
> check the route service provider, if you have a namespace there, you don't need to use anything.
> 
> But indeed it's strange that it works some times, but not all the time. This seems to be laravel related though.

I resolved it with removing 'namespace' in Route::group . Hope This help you bro

**Comment by jtomek** [comment]
I had to remove all the namespaces everywhere (incl. the service providers), but please don't follow this "fix" blindly.

It works in my uses case, as I've been slowly transforming my app into an API and moving all of my views and assets to Angular. You may rely on blade views etc. so please be careful.
