### ISSUE TITLE
Improving Module Resources docs page

### ISSUE THREAD

**Issue by Phu1237** [nWidart/laravel-modules#1118]
Hi! Today i tried your package with using factory.

But this code didn't work in laravel 7.29.3.
![image](https://user-images.githubusercontent.com/9032235/98546884-f6d72d80-22c9-11eb-84ea-0dac04c2db93.png)

When i try adding it to Modules\<Module>\Providers\<Module>ServiceProvider.php in the boot function like this
![image](https://user-images.githubusercontent.com/9032235/98547330-95fc2500-22ca-11eb-9073-5cc1bd8320b2.png)

It will return error (after seed command)
![image](https://user-images.githubusercontent.com/9032235/98547552-effcea80-22ca-11eb-946c-e24e9a6b1039.png)

Because the right way to do it is
>$this->app->singleton(Factory::class, function () {
return Factory::construct(**new \Faker\Generator**, module_path($this->moduleName, '/Database/factories'));
});

But with the above code, i meet another error that can't use $faker in factory
![image](https://user-images.githubusercontent.com/9032235/98547734-33575900-22cb-11eb-982d-33c03deb5b69.png)

So i find another way to do it is to put this code in the boot function
>$this->app->make(Factory::class)->load(module_path($this->moduleName, '/Database/factories'));

Can you fix the docs page (the current docs don't tell us to put the code in module provider and in what function) or put this code in the provider file after created module and comment it (so everyone can uncomment it if they want)? Tks!
_Like this_
![image](https://user-images.githubusercontent.com/9032235/98549161-0015c980-22cd-11eb-9042-951b6fb30dc2.png)

**Comment by xtfer** [comment]
I agree with this suggestion. This was confusing for me.

**Comment by Phu1237** [comment]
But seem that the author don't mind this. Hope he will check this in the future.

**Comment by FoksVHox** [comment]
@nWidart Any updates on this?
