### ISSUE TITLE
Question: how to register middleware of any module without editing kernel.php

### ISSUE THREAD

**Issue by webreinvent** [nWidart/laravel-modules#112]
Can we register middleware of any module via its service provider?

**Comment by Gkiokan** [comment]
Yes, this is possible. I've done this in my modules.
You have to Import the Route and use the middleware method to add a middleware.

Here is my boot method which includes adding aliases to the Kernel, too.

`    public function boot(Router $router)
    {
        $this->registerTranslations();
        $this->registerConfig();
        $this->registerViews();

        $router->middleware('IsMyOwnProfile', \Gkiokan\Profile\Http\Middleware\IsOwnProfile::class);
        // app()->singleton('profile.callme', '\Gkiokan\Profile\Helpers\CallMe');
        $this->app->singleton('profile.callme', '\Gkiokan\Profile\Helpers\CallMe');
        $this->app->singleton('profile.magic', '\Gkiokan\Profile\Profile');
    }`

**Comment by vahidalvandi** [comment]
`use Illuminate\Routing\Router;
`
`    public function boot(Router $router)
    {
		
		Gate::define('user-invoice-check', 'Modules\Vproducts\Policies\UserPolicy@invoice');

        $this->registerTranslations();
        $this->registerConfig();
        $this->registerViews();
        $this->registerFactories();
        $this->loadMigrationsFrom(__DIR__ . '/../Database/Migrations');
	

		// Add your middleware 
		$router->middleware('CanReadInvoiceMiddleware', \Modules\Vproducts\Http\Middleware\CanReadInvoiceMiddleware::class);
		
	
	}`
