### ISSUE TITLE
Target class [Nwidart\Modules\Commands\] does not exist.

### ISSUE THREAD

**Issue by opeyemijj** [nWidart/laravel-modules#1121]
I just setup Laravel 8 and Nwidart Laravel Modules. I an running on php 7.3.8. everything works fine until i ran php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider". after this any command i run gives this error Target class [Nwidart\Modules\Commands\] does not exist.

VSTs-MacBook-Pro:endsars jawad$ php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"
Copied File [/vendor/nwidart/laravel-modules/config/config.php] To [/config/modules.php]
Publishing complete.
VSTs-MacBook-Pro:endsars jawad$ composer dump-autoload
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Illuminate\Contracts\Container\BindingResolutionException 

  Target class [Nwidart\Modules\Commands\] does not exist.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:811
    807▕ 
    808▕         try {
    809▕             $reflector = new ReflectionClass($concrete);
    810▕         } catch (ReflectionException $e) {
  ➜ 811▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    812▕         }
    813▕ 
    814▕         // If the type is not instantiable, the developer is attempting to resolve
    815▕         // an abstract type such as an Interface or Abstract Class and there is

      +13 vendor frames 
  14  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by nWidart** [comment]
Fixed in https://github.com/nWidart/laravel-modules/releases/tag/8.2.0

**Comment by opeyemijj** [comment]
confirmed. now fixed. thanks
