### ISSUE TITLE
After upgrade from 8.0 to 8.2, make-component command still not working.

### ISSUE THREAD

**Issue by davidkai147** [nWidart/laravel-modules#1122]
Hi Nicholas,
Thank you for your hard working on upgrade package version.

I've upgraded to version 8.2, but in modules.php (config), there is no 'component-class' or 'component-view'.
On the other hand, when I run command: 
`php artisan module:make-component _component_name_ _module_name_`

`Command "module:make-component" is not defined. `message appeared on the terminal.

I tried to delete vendor folder and reinstall packages, but there was no hope.
Best regards.

**Comment by lhoucinecherif** [comment]
I have the same  issue , also component inside module not resolved yet.
"Unable to locate a class or view for component ... ".

**Comment by iamine** [comment]
you can resolve them by using this syntax:

<x-module::component />

for example, if you have  a Blog  Module and you create a component in  Blog/Resources/views/components/sidebar.blade.php

you can resolve it like  that

<x-blog::sidebar />

as it explained here:
[https://laravel.com/docs/8.x/packages#anonymous-components](url)

**Comment by tuyenlaptrinh** [comment]
Up vote.
Please update this function.

**Comment by tuyenlaptrinh** [comment]
You can change config in modules.php

`ComponentClassMakeCommand::class,
 ComponentViewMakeCommand::class,`

add this classes to commands so your issue resolved

**Comment by FoksVHox** [comment]
@davidkai147 I've create PR #1148

**Comment by FoksVHox** [comment]
@nWidart This can be closed as you've merged #1148

**Comment by jimoheokoh** [comment]
> you can resolve them by using this syntax:
> 
> <x-module::component />
> 
> for example, if you have a Blog Module and you create a component in Blog/Resources/views/components/sidebar.blade.php
> 
> you can resolve it like that
> 
> <x-blog::sidebar />
> 
> as it explained here:
> [https://laravel.com/docs/8.x/packages#anonymous-components](url)

Thanks for this. The documentation page need to be updated. @nWidart

**Comment by FoksVHox** [comment]
> > you can resolve them by using this syntax:
> > <x-module::component />
> > for example, if you have a Blog Module and you create a component in Blog/Resources/views/components/sidebar.blade.php
> > you can resolve it like that
> > <x-blog::sidebar />
> > as it explained here:
> > [https://laravel.com/docs/8.x/packages#anonymous-components](url)
> 
> Thanks for this. The documentation page need to be updated. @nWidart

Make a PR to it
