### ISSUE TITLE
Use laravel ui package in module

### ISSUE THREAD

**Issue by theshendeveloper** [nWidart/laravel-modules#1126]
I want to install and use laravel ui in my new module but `Auth::routes()` in route file and `php artisan ui` command isn't working.
is there any way to use this package in module?

**Comment by wikigods** [comment]
I am new to using Modules, but if you mean using composer require laravel/ui.
1st If possible you should just create a User or Auth Module, move, rename routes ("Auth::routes()") , controllers, views to your module, then edit the config/auth file. php, line in laravel 8 ('model' => App\Models\User::class,) if you use old versions the line would be like this, ('model' => App\User::class,) [ replace the line "example Modules\User\Entities\User::class" ], lastly "composer dump-autoload", everything would be working.

2ª Although I recommend that you use the new package composer require laravel/breeze --dev , which is the same with the advantages that you can uninstall it, once executed and uses tailwindcss, if you want to use it with a Module just repeat the steps that I said at the beginning, excuse my English is not very good.
I forgot to tell you if you are working on old project make a backup and documentation, let me know if you have any problem
