### ISSUE TITLE
Livewire Components

### ISSUE THREAD

**Issue by zcwilt** [nWidart/laravel-modules#1127]
If I want to add a livewire component at the moment, there isn't a simple way to do this and have those components exist within the `modules` structure

For example.

I'm using the [Data Tables]( https://livewire-datatables.com/) package

I want components for this to exist in `[ModuleName]/Http/Livewire/`

However because of the way Livewire searches for components this isn't possible

Now I can fix this by registering the components in my `Modules/[modulename]/Provider/ServiceProvider`

and add something like 

`        Livewire::component('product-datatable', ProductDatatable::class);`

but this is a lot of work if I have lots of components to add.

What would be better is if we inspected the  `[ModuleName]/Http/Livewire/`
directory and automatically registered components.

The registration could first just convert the class name from camel case to kebab case
or we could look for a static `componentName` method

I'm willing to provide a PR for this.

**Comment by tibormarias** [comment]
I think it would be easier to add it as a command like this one:
`php artisan module:make-livewire [component_name] [module_name]`

**Comment by mhmiton** [comment]
@zcwilt I'm using a custom service provider for livewire components registration. It's working for me. You can try this. 

Example:

Livewire Component Class - Modules\Contact\Http\Livewire\Frontend\Components\ContactForm

Use this component in the blade file like this - `<livewire:contact::frontend.components.contact-form /> `

Register custom livewire service provider in the core modules service provider - 

```
/**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->app->register(RouteServiceProvider::class);
        $this->app->register(CustomLivewireServiceProvider::class); // Add this line
    }
```

Custom Livewire Service Provider Class - Modules\Core\Providers\CustomLivewireServiceProvider

```
<?php

namespace Modules\Core\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Filesystem\Filesystem;

class CustomLivewireServiceProvider extends ServiceProvider
{
    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->loadComponents();
    }

    /**
     * Get the services provided by the provider.
     *
     * @return array
     */
    public function provides()
    {
        return [];
    }

    protected function loadComponents()
    {
        $modules = \Module::toCollection();

        $filesystem = new Filesystem();

        $modules->map(function ($module) use ($filesystem) {
            $modulePath = $module->getPath();

            $moduleName = $module->getName();

            $path = $modulePath.'/Http/Livewire';

            $files = collect( $filesystem->isDirectory($path) ? $filesystem->allFiles($path) : [] );

            $files->map(function ($file) use ($moduleName, $path) {
                $componentPath = \Str::after($file->getPathname(), $path.'/');

                $componentClassPath = strtr( $componentPath , ['/' => '\\', '.php' => '']);
        
                $componentName = $this->getComponentName($componentClassPath, $moduleName);

                $componentClassStr = "\\Modules\\{$moduleName}\\Http\\Livewire\\".$componentClassPath;
                
                $componentClass = get_class(new $componentClassStr);

                $loadComponent = \Livewire::component($componentName, $componentClass);
            });
        });
    }

    protected function getComponentName($componentClassPath, $moduleName = null)
    {
        $dirs = explode('\\', $componentClassPath);
        
        $componentName = '';

        foreach ($dirs as $dir) {
            $componentName .= \Str::kebab( lcfirst($dir) ).'.';
        }

        $moduleNamePrefix = ($moduleName) ? \Str::lower($moduleName).'::' : null;

       return \Str::substr($moduleNamePrefix.$componentName, 0, -1);
    }
}
```

**Comment by FoksVHox** [comment]
> m Livewire Service Provider Class - Modules\Core\Providers\CustomLivewireService

Would you be able to PR it? I would love to see this in a future version of Laravel Modules

**Comment by mhmiton** [comment]
@FoksVHox Sure, I will provide PR for this very soon.

**Comment by mhmiton** [comment]
@FoksVHox I submitted a PR for Livewire Support. #1150

**Comment by aishwaryakumar-hub** [comment]
Modules\Channel\Providers\LivewireServiceProvider not found

**Comment by aishwaryakumar-hub** [comment]
> @zcwilt I'm using a custom service provider for livewire components registration. So, no need to register manually every time. It's working for me. You can try this.
> 
> Example:
> 
> Livewire Component Class - Modules\Contact\Http\Livewire\Frontend\Components\ContactForm
> 
> Use this component in the blade file like this - `<livewire:contact::frontend.components.contact-form /> `
> 
> Register custom livewire service provider in the core modules service provider -
> 
> ```
> /**
>      * Register the service provider.
>      *
>      * @return void
>      */
>     public function register()
>     {
>         $this->app->register(RouteServiceProvider::class);
>         $this->app->register(CustomLivewireServiceProvider::class); // Add this line
>     }
> ```
> 
> Custom Livewire Service Provider Class - Modules\Core\Providers\CustomLivewireServiceProvider
> 
> ```
> <?php
> 
> namespace Modules\Core\Providers;
> 
> use Illuminate\Support\ServiceProvider;
> use Illuminate\Filesystem\Filesystem;
> 
> class CustomLivewireServiceProvider extends ServiceProvider
> {
>     /**
>      * Register the service provider.
>      *
>      * @return void
>      */
>     public function register()
>     {
>         $this->loadComponents();
>     }
> 
>     /**
>      * Get the services provided by the provider.
>      *
>      * @return array
>      */
>     public function provides()
>     {
>         return [];
>     }
> 
>     protected function loadComponents()
>     {
>         $modules = \Module::toCollection();
> 
>         $filesystem = new Filesystem();
> 
>         $modules->map(function ($module) use ($filesystem) {
>             $modulePath = $module->getPath();
> 
>             $moduleName = $module->getName();
> 
>             $path = $modulePath.'/Http/Livewire';
> 
>             $files = collect( $filesystem->isDirectory($path) ? $filesystem->allFiles($path) : [] );
> 
>             $files->map(function ($file) use ($moduleName, $path) {
>                 $componentPath = \Str::after($file->getPathname(), $path.'/');
> 
>                 $componentClassPath = strtr( $componentPath , ['/' => '\\', '.php' => '']);
>         
>                 $componentName = $this->getComponentName($componentClassPath, $moduleName);
> 
>                 $componentClassStr = "\\Modules\\{$moduleName}\\Http\\Livewire\\".$componentClassPath;
>                 
>                 $componentClass = get_class(new $componentClassStr);
> 
>                 $loadComponent = \Livewire::component($componentName, $componentClass);
>             });
>         });
>     }
> 
>     protected function getComponentName($componentClassPath, $moduleName = null)
>     {
>         $dirs = explode('\\', $componentClassPath);
>         
>         $componentName = '';
> 
>         foreach ($dirs as $dir) {
>             $componentName .= \Str::kebab( lcfirst($dir) ).'.';
>         }
> 
>         $moduleNamePrefix = ($moduleName) ? \Str::lower($moduleName).'::' : null;
> 
>        return \Str::substr($moduleNamePrefix.$componentName, 0, -1);
>     }
> }
> ```

I am getting error class of provider not found

**Comment by aishwaryakumar-hub** [comment]
> @zcwilt I'm using a custom service provider for livewire components registration. So, no need to register manually every time. It's working for me. You can try this.
> 
> Example:
> 
> Livewire Component Class - Modules\Contact\Http\Livewire\Frontend\Components\ContactForm
> 
> Use this component in the blade file like this - `<livewire:contact::frontend.components.contact-form /> `
> 
> Register custom livewire service provider in the core modules service provider -
> 
> ```
> /**
>      * Register the service provider.
>      *
>      * @return void
>      */
>     public function register()
>     {
>         $this->app->register(RouteServiceProvider::class);
>         $this->app->register(CustomLivewireServiceProvider::class); // Add this line
>     }
> ```
> 
> Custom Livewire Service Provider Class - Modules\Core\Providers\CustomLivewireServiceProvider
> 
> ```
> <?php
> 
> namespace Modules\Core\Providers;
> 
> use Illuminate\Support\ServiceProvider;
> use Illuminate\Filesystem\Filesystem;
> 
> class CustomLivewireServiceProvider extends ServiceProvider
> {
>     /**
>      * Register the service provider.
>      *
>      * @return void
>      */
>     public function register()
>     {
>         $this->loadComponents();
>     }
> 
>     /**
>      * Get the services provided by the provider.
>      *
>      * @return array
>      */
>     public function provides()
>     {
>         return [];
>     }
> 
>     protected function loadComponents()
>     {
>         $modules = \Module::toCollection();
> 
>         $filesystem = new Filesystem();
> 
>         $modules->map(function ($module) use ($filesystem) {
>             $modulePath = $module->getPath();
> 
>             $moduleName = $module->getName();
> 
>             $path = $modulePath.'/Http/Livewire';
> 
>             $files = collect( $filesystem->isDirectory($path) ? $filesystem->allFiles($path) : [] );
> 
>             $files->map(function ($file) use ($moduleName, $path) {
>                 $componentPath = \Str::after($file->getPathname(), $path.'/');
> 
>                 $componentClassPath = strtr( $componentPath , ['/' => '\\', '.php' => '']);
>         
>                 $componentName = $this->getComponentName($componentClassPath, $moduleName);
> 
>                 $componentClassStr = "\\Modules\\{$moduleName}\\Http\\Livewire\\".$componentClassPath;
>                 
>                 $componentClass = get_class(new $componentClassStr);
> 
>                 $loadComponent = \Livewire::component($componentName, $componentClass);
>             });
>         });
>     }
> 
>     protected function getComponentName($componentClassPath, $moduleName = null)
>     {
>         $dirs = explode('\\', $componentClassPath);
>         
>         $componentName = '';
> 
>         foreach ($dirs as $dir) {
>             $componentName .= \Str::kebab( lcfirst($dir) ).'.';
>         }
> 
>         $moduleNamePrefix = ($moduleName) ? \Str::lower($moduleName).'::' : null;
> 
>        return \Str::substr($moduleNamePrefix.$componentName, 0, -1);
>     }
> }
> ```

<?php

namespace Modules\Channel\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Database\Eloquent\Factory;

class ChannelServiceProvider extends ServiceProvider
{
    /**
     * @var string $moduleName
     */
    protected $moduleName = 'Channel';

    /**
     * @var string $moduleNameLower
     */
    protected $moduleNameLower = 'channel';

    /**
     * Boot the application events.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerTranslations();
        $this->registerConfig();
        $this->registerViews();
        $this->loadMigrationsFrom(module_path($this->moduleName, 'Database/Migrations'));
    }

    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->app->register(RouteServiceProvider::class);
        $this->app->register(LivewireServiceProvider::class);
    }

    /**
     * Register config.
     *
     * @return void
     */
    protected function registerConfig()
    {
        $this->publishes([
            module_path($this->moduleName, 'Config/config.php') => config_path($this->moduleNameLower . '.php'),
        ], 'config');
        $this->mergeConfigFrom(
            module_path($this->moduleName, 'Config/config.php'), $this->moduleNameLower
        );
    }

    /**
     * Register views.
     *
     * @return void
     */
    public function registerViews()
    {
        $viewPath = resource_path('views/modules/' . $this->moduleNameLower);

        $sourcePath = module_path($this->moduleName, 'Resources/views');

        $this->publishes([
            $sourcePath => $viewPath
        ], ['views', $this->moduleNameLower . '-module-views']);

        $this->loadViewsFrom(array_merge($this->getPublishableViewPaths(), [$sourcePath]), $this->moduleNameLower);
    }

    /**
     * Register translations.
     *
     * @return void
     */
    public function registerTranslations()
    {
        $langPath = resource_path('lang/modules/' . $this->moduleNameLower);

        if (is_dir($langPath)) {
            $this->loadTranslationsFrom($langPath, $this->moduleNameLower);
        } else {
            $this->loadTranslationsFrom(module_path($this->moduleName, 'Resources/lang'), $this->moduleNameLower);
        }
    }

    /**
     * Get the services provided by the provider.
     *
     * @return array
     */
    public function provides()
    {
        return [];
    }

    private function getPublishableViewPaths(): array
    {
        $paths = [];
        foreach (\Config::get('view.paths') as $path) {
            if (is_dir($path . '/modules/' . $this->moduleNameLower)) {
                $paths[] = $path . '/modules/' . $this->moduleNameLower;
            }
        }
        return $paths;
    }
}

**Comment by josetiagobispo** [comment]
existe esse pacote: https://packagist.org/packages/mhmiton/laravel-modules-livewire

**Comment by aishwaryakumar-hub** [comment]
Class '\Modules\Channel\Http\Livewire\C:\xampp\htdocs\boilerplate\Modules\Channel\Http\Livewire\Rule\FormComponent' not found

**Comment by mhmiton** [comment]
@aishwaryakumar-hub Did you face this error from this package?

https://github.com/mhmiton/laravel-modules-livewire

**Comment by aishwaryakumar-hub** [comment]
I solved finally
