### ISSUE TITLE
How use mail "vendor" in modules?

### ISSUE THREAD

**Issue by atach** [nWidart/laravel-modules#1130]
Now all emails are displayed according to a single template (which is located: /resources/views/vendor/mail/html/).
How to make this template taken from the module folder?
I tried to move it to my module (Modules/ModuleName/resources/views/vendor/mail/html/), but nothing worked!

Same with error pages.

**Comment by andersonpem** [comment]
Watching.

**Comment by e-lyder** [comment]
Olá @atach e @andersonpem.

Se o template estiver em "Modules/ModuleName/resources/views/vendor/mail/html/"  chame o template assim...
```
@extends('ModuleName::vendor.mail.html.ViewMailName')
@section('content')
     <div class="container">
          <h1>My e-mail</h1>
     </div>
@endsection
```
Tente apontar o blade de email assim...
```
...your uses...

class SendMyMail extends Mailable
{
     ...
     public function build()
     {
          return $this->view('ModuleName::vendor.mail.html.ViewMailName');
     }
}
```
Já com os erros você pode mudar isso de maneiras diferentes:
1.) em seu `config/view.php` você tem um array `paths` -se você adicionar uma nova pasta aqui, então o Laravel irá pesquisar todos os caminhos (com `/errors` no final) até encontrar a página de erro correta. (Você deve excluir a pasta `errors` em  `resources/views`, caso contrário, ela irá pegá-los).
```
    'paths' => [
        realpath(base_path('resources/views')),
        realpath(module_path('ModuleName', 'resources/views/errors')),
    ],
```
Agora seus modelos de erro estão em `resources/views/errors`.

2.) você pode substituir o `renderHttpException()` -método da estrutura se adicionar um método com exatamente o mesmo nome em seu `app/Exception/Handler.php`.
algo como este exemplo:
```
    protected function renderHttpException(HttpException $e)
    {
        $status = $e->getStatusCode();

        $paths = collect(config('view.paths'));

        view()->replaceNamespace('errors', [resource_path('views/foo/bar'), 
             module_path('ModuleName', 'resources/views')',

        if (view()->exists($view = "errors::{$status}")) {
            return response()->view($view, ['exception' => $e], $status, $e->getHeaders());
        }

        return $this->convertExceptionToResponse($e);
    }
```
Agora seus modelos de erro estão em `Modules/ModuleName/resources/views/foo/bar` (sem `/errors` no final).
Acredito que pode ser isso...

Referência -> [Laracasts.com](https://laracasts.com/discuss/channels/laravel/i-want-to-change-the-directory-of-errors-blade-files?page=0)
