### ISSUE TITLE
Exception: Trait 'Illuminate\Database\Eloquent\Factories\HasFactory' not found

### ISSUE THREAD

**Issue by 4n70w4** [nWidart/laravel-modules#1132]
Hi! I use Laravel 7 and run `composer install nwidart/laravel-modules` and get 8.2.0 version.
Next I run model generation `php artisan module:make-model -m Recipe Scoring` and model generated with:

```php
    protected static function newFactory()
    {
        return \Modules\Scoring\Database\factories\FeatureFactory::new();
    }
```

But I get error:

```
Trait 'Illuminate\Database\Eloquent\Factories\HasFactory' not found
```

The composer package management tool provides the ability to specify compatible versions of dependent libraries.

Composer file does not currently contain such restrictions:

![image](https://user-images.githubusercontent.com/38257723/100020659-3be28000-2df1-11eb-8e78-dfd584a24d6f.png)

You are not using a version constraint for the laravel framework in `require`. Specifying `require-dev` does not work with installation.

**Comment by e-lyder** [comment]
[Issue 1112](https://github.com/nWidart/laravel-modules/issues/1112)

![](https://user-images.githubusercontent.com/38257723/100020659-3be28000-2df1-11eb-8e78-dfd584a24d6f.png)
In Laravel 7, run...

`composer require nwidart/laravel-modules "7.0"`

**Comment by nWidart** [comment]
You should require the correct version during the composer require command.

**Comment by 4n70w4** [comment]
@nWidart I agree. And you should specify the correct compatible versions in the `composer.json` file. =)

**Comment by MrNoBody619** [comment]
@4n70w4 Bro, have you found a way to fix the error issue?

**Comment by 4n70w4** [comment]
@MrNoBody619 see answer from e-lyde
