### ISSUE TITLE
issue when am typing php artisan seve

### ISSUE THREAD

**Issue by JulienMupenzi** [nWidart/laravel-modules#1133]
Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'BotMan\BotMan\Drivers\DriverManager' not found

  at C:\xampp\htdocs\House_Renting\app\Providers\BotMan\DriverServiceProvider.php:35
    31|      */
    32|     public function boot()
    33|     {
    34|         foreach ($this->drivers as $driver) {
  > 35|             DriverManager::loadDriver($driver);
    36|         }
    37|     }
    38|     /**
    39|      * Auto-discover BotMan drivers and load them.

  Exception trace:

  1   App\Providers\BotMan\DriverServiceProvider::boot()
      C:\xampp\htdocs\House_Renting\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36

  2   Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      C:\xampp\htdocs\House_Renting\vendor\laravel\framework\src\Illuminate\Container\Util.php:37

  Please use the argument -v to see more details.
PS C:\xampp\htdocs\House_Renting>

**Comment by nWidart** [comment]
Why are you creating the issue here? I looks to be a BotMan issue from the error you posted.

**Comment by JulienMupenzi** [comment]
please help me, that's the issue i got when i was creating my laravel projet with a Botman within it
