### ISSUE TITLE
Target class [Modules\{module}\Http\Middleware\{middleware}] does not exist

### ISSUE THREAD

**Issue by parsagholipour** [nWidart/laravel-modules#1140]
I'm trying to define a middleware in a module and use that for the web middleware group but I get this error:
Illuminate\Contracts\Container\BindingResolutionException: Target class [Modules\{module}\Http\Middleware\{middleware}] does not exist

The service provider of the module is being registered and booted and the module is enabled. I just can't use this middleware in kernel.

**Comment by maxcelos** [comment]
I have middlewares from module working. It might not be an error related to this package.

I've got similar errors and the cause was composer cache. Hope you got it solved by now.

**Comment by parsagholipour** [comment]
@maxcelos I don't know about before but now I tried and it works. Maybe a composer problem.
