### ISSUE TITLE
There is no way to clear the cached *_module.php files

### ISSUE THREAD

**Issue by jpswade** [nWidart/laravel-modules#1141]
It seems that it registers those files, but once they are registered, nothing will clean them out.

This has been mentioned in the past but nothing was done about it:

https://github.com/nWidart/laravel-modules/issues/494

**Comment by ctf0** [comment]
https://github.com/nWidart/laravel-modules/issues/494#issuecomment-750462672

**Comment by jpswade** [comment]
> [#494 (comment)](https://github.com/nWidart/laravel-modules/issues/494#issuecomment-750462672)

Thanks, I'll update accordingly.
