### ISSUE TITLE
Large scale project in github using Laravel modules 

### ISSUE THREAD

**Issue by foxmedo** [nWidart/laravel-modules#1144]
Hello, 

Looking for Large scale project in github using Laravel modules  to inspire the structure 

Also if there is project using Metronic theme with Laravel Modules 

Waiting for your answers

**Comment by n3m3s7s** [comment]
Maybe I am wrong but https://github.com/bagisto/bagisto it seems to use a tweaked version for "modules" (packages).
Each package has a structure almost identical to the one provided with "laravel-modules"
