### ISSUE TITLE
Refactoring Command 🎉 ( Change Laravel to Modules structure )

### ISSUE THREAD

**Issue by bluemmb** [nWidart/laravel-modules#1146]
We at [AsanSeminar](https://asanseminar.ir) recently attempted to refactor our production code to use modules and we chose this awesome library to do the job.

Since there was a lot of classes to move, we decided to automate the refactoring process and we created a Laravel command to accomplish it. The deadline for the task was tight but I think this was way better than doing it manually.

You can find the modified version of code in here *(it's stripped away from things that would expose the project details)*
[https://github.com/asanseminar/laravel-modules-refactor](https://github.com/asanseminar/laravel-modules-refactor)

We have tested our version and it works perfect, we hope it can help you too.

**Note: We are not using the refactored version of our code in production because we experienced some performance problems. I will create a new issue on that to get help.**

**Comment by FoksVHox** [comment]
@bluemmb would you be able to create a PR for this?

**Comment by bluemmb** [comment]
@FoksVHox For creating a PR I need to put more time on it to make it almost automatic and clean up the code, it's really a mess right now. I will try to do that in future. 
Thanks

**Comment by allanlaal** [comment]
unstale
