### ISSUE TITLE
Route caching problem

### ISSUE THREAD

**Issue by webmake** [nWidart/laravel-modules#115]
After some debugging and some measurements, I found such bug in module:
when routes are not cached, everything works good. But when cache file is generated (`bootstrap/cache/routes.php`), routes are included twice, from [RouteServiceProvider](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php#L27) and from each module with require line call from `start.php` file.

_My approach was different to include routes, but still, here those timing results:
Without cache  0.05-0.07s,
with cache 0.09-0.12s,
with fix 0.03-0.05s_

So my suggestion would be to change in
[start.stub](https://github.com/nWidart/laravel-modules/blob/1.14.0/src/Commands/stubs/start.stub)
by adding additional checking, to not include twice
```
if (!app()->routesAreCached()) {
    require __DIR__ . '/Http/routes.php';
}
```
for [route-provider.stub](https://github.com/nWidart/laravel-modules/blob/1.14.0/src/Commands/stubs/route-provider.stub) also same suggestion.

**Comment by nWidart** [comment]
Hello & thanks for the suggestion.

This is now on dev-master, feel free to test it out.

**Comment by webmake** [comment]
I have noticed,that path has changed:
https://github.com/nWidart/laravel-modules/commit/628f72a03fa94a152269141682983fccf3a32c19#diff-6a8f4f00dae32987c08a4083bfdca21aR38
missing `/..`

**Comment by nWidart** [comment]
This was fixed on latest release. 👍

**Comment by kevmt** [comment]
This seems not carried over to latest lumen, was this removed? lumen-framework v5.6.4, this triggers errors to @nWidart package.

**Comment by andresilva96** [comment]
I know the post is old, but I'm using this package now and I had a solution, in the `App\Providers\RouteServiceProvider` I put it on `boot` function:
```
    public function boot()
    {
        $this->configureRateLimiting();

        $this->routes(function () {
            Route::prefix('api')
                ->middleware('api')
                ->namespace($this->namespace)
                ->group(base_path('routes/api.php'));

            Route::middleware('web')
                ->namespace($this->namespace)
                ->group(base_path('routes/web.php'));

            foreach (Module::getByStatus(1) as $module) {
                $namespace = "Modules\{$module->name}\Http\Controllers";

                Route::middleware('web')
                    ->namespace($namespace)
                    ->group(module_path($module->name, '/Routes/web.php'));

                $path = module_path($module->name, '/Routes/api.php');

                if (file_exists($path)) {
                    Route::prefix('api')
                        ->middleware('api')
                        ->namespace($namespace)
                        ->group($path);
                }
            }
        });
    }
```

This worked to me, even though I created a global ModuleServiceProvider, so my Modules doesnt need any Services Providers.
