### ISSUE TITLE
How to change the Modules "Modules" folder name?

### ISSUE THREAD

**Issue by lavecart** [nWidart/laravel-modules#1154]
Is there any way to change the name of `Modules` folder name?

`Admin\Category`

Means my Modules folder name will be Admin

```
"autoload": {
        "psr-4": {
            "App\": "app/",
            "Modules\": "Admin/",
            "Database\Factories\": "database/factories/",
            "Database\Seeders\": "database/seeders/"
        }
    },
```
I tried with this but not working!

Thanks

**Comment by di1606** [comment]
what is the point of changing the name of the Module folder?  you can create an Admin module for example

**Comment by lavecart** [comment]
> what is the point of changing the name of the Module folder? you can create an Admin module for example

Because I want to create two `Modules` one is `Admin and another is `Store`

Is it possible?

**Comment by di1606** [comment]
Yes, it's is. You run this command 

`php artisan module:make Admin Store`

I encourage you to consult the documentation of this package, here is the link : https://nwidart.com/laravel-modules/v6/introduction
