### ISSUE TITLE
Routes from higher order modules overridden by lower order modules 

### ISSUE THREAD

**Issue by gokulkhatiwada** [nWidart/laravel-modules#1155]
"laravel/framework": "^8.0",
"nwidart/laravel-modules": "^8.0",

`{
    "name": "User",
    "alias": "user",
    "description": "User system",
    "keywords": [],
    "order": 0,
    "providers": [
        "Modules\\User\\Providers\\UserServiceProvider"
    ],
    "aliases": {},
    "files": [],
    "requires": []
}`

user module routes

`Auth::routes(['verify'=>true]);
 Route::get('login/{provider}','Auth\LoginController@redirectToProvider');
Route::get('callback/{facebook}','Auth\LoginController@handleProviderCallback');
Route::middleware('auth')->group(function(){
    Route::get('/update-password', 'UserController@changePassword')
        ->name('change.password');
    Route::post('/update-password','UserController@updatePassword')
        ->name('update.password');
});`
CMS module
`{
    "name": "CMS",
    "alias": "cms",
    "description": "Content Management for system",
    "keywords": [],
    "order": 4,
    "providers": [
        "Modules\\CMS\\Providers\\CMSServiceProvider"
    ],
    "aliases": {},
    "files": [],
    "requires": []
}`

cms routes

`Route::prefix('')->group(function() {
    Route::get('/{slug}', 'CMSController@viewPage')->name('view.page');
});`

now I can't access auth routes I get 404 and no any error on laravel.log

**Comment by wikigods** [comment]
Add in Module.json 
"priority": 0, ; take into account an order, it is something similar to "order": 0,
