### ISSUE TITLE
Not able to access Auth::user() in models after installing "nwidart/laravel-modules": "^8.2"

### ISSUE THREAD

**Issue by RadhaGupta91** [nWidart/laravel-modules#1156]
I have used "nwidart/laravel-modules": "^8.2" to implement modular approach.
but I am not able to access Auth::user() in models whereas I am able to access it in the controller.
Can you provide me a solution asap?

**Comment by FoksVHox** [comment]
> I have used "nwidart/laravel-modules": "^8.2" to implement modular approach.
> but I am not able to access Auth::user() in models whereas I am able to access it in the controller.
> Can you provide me a solution asap?

So you are not able to access `Auth::user()` in a module or a model inside a module?
