### ISSUE TITLE
Possible performance issue (measured by blackfire)

### ISSUE THREAD

**Issue by bluemmb** [nWidart/laravel-modules#1157]
Hi. Happy Christmas.

We are on production and decided to refactor our code to modules. So we created a command to make the refactoring easy and automatic as I have stated in #1146. I mentioned there that after putting the new code on production we experienced a big impact on performance, even behind opcache and cdn. So we had to rollback to previous code.

This week I got time to get back on this again since we are in need to do refactoring before adding more features. Today I was able to create a small benchmark from 4 different versions of our code and it's described below.

### 4 different versions:
- **original**: Our code on production

- **laravel-modules**: Refactoed code to this package's structure (only app folder, didn't touch database, routes, resources, ...) (31 modules)

- **laravel-modules-noproviders**: Previous version with all but not functional providers (31 modules)

- **simple modules**: We twisted our command a bit to just create an empty folder for each module and simply moved the same files from app folder to those folders with no extra providers, configs, ... files (almost the same files were moved as previous ones)

##### `php artisan optimize` and `php artisan view:cache` is used before serving on local computer and I have used [blackfire](https://blackfire.io) for profiling

Version | Page1 | Page2
------------ | ------------- | ------------- 
**original** | 32.7ms (1x mb) | 113ms (1x mb)
**laravel-modules** | 542ms  (1.25x mb) | 619ms (1.18x mb)
**laravel-modules-noproviders** | 56.6ms (1.08x mb) | 135ms (1.06x mb)
**simple modules** | 34.5ms (1.02x mb) | 110ms (1.01x mb)

Of course I ran each one multiple times but the average response results were just about the same.

By the way the package is awesome and I'm not sure if my profiling was sane and I am looking for a solution. thanks

**Comment by xtfer** [comment]
@bluemmb Did you get to the bottom of this?

**Comment by bluemmb** [comment]
@xtfer As we concluded for our source code, having many providers (we had 31) which load their own routes and etc causes the bad performance. Since time was tight we decided to use another approach.
But we should wait and see what the main contributors are going to say.
