### ISSUE TITLE
Unable to overriding package views from Module

### ISSUE THREAD

**Issue by abhishek-pokhriyal** [nWidart/laravel-modules#1158]
In the package we are using there is the following line in the `register` method of `PackageServiceProvider`
```php
$this->loadViewsFrom(__DIR__ . '/../resources/views', 'package');
```

**I'd like to know if it's possible to override this package from the `Modules/MyModule/Resources/views/`?**

I'm able to do it from the root application by creating a view file at `resources/views/vendor/package/view-name.blade.php` but not when I do the same from inside the module. That is, it's not overriding when I put the view in `Modules/MyModule/Resources/views/view-name.blade.php`.

Thanks

**Comment by SocolaDaiCa** [comment]
```php
$this->loadViewsFrom(__DIR__ . '/../resources/views', 'package');
```
Modules/MyModule/Resources/views/view-name.blade.php

'Resource' and 'resource' is difference

**Comment by abhishek-pokhriyal** [comment]
> 'Resource' and 'resource' is difference

@SocolaDaiCa I've tried this by renaming `Resources` to 'resources' but still no luck.

Also, I came across [this comment](https://github.com/nWidart/laravel-modules/issues/794#issuecomment-513263834) from Nicolas. The good thing is that I own the package in this case. Do you have any idea what changes I can make in the package to make this to work?

**Comment by SocolaDaiCa** [comment]
Do you want to load the file view-name.blade.php 
from resources / views / vendor / package / view-name.blade.php 
instead of Modules / MyModule / Resources / views / view-name.blade.php ?

**Comment by abhishek-pokhriyal** [comment]
There is a view in the package: `PROJECT_ROOT/vendor/author/package/resources/views/view-name.blade.php`
I want to override this view from `PROJECT_ROOT/Modules/MyModule/resources/views/view-name.blade.php`

**Comment by SocolaDaiCa** [comment]
it impossible
if you create a file 
`ROJECT_ROOT/resources/views/vendor/package/view-name.blade.php`, you can overwrite `ROJECT_ROOT/vendor/author/package/resources/views/view-name.blade.php`

you can create a command to copy file from `PROJECT_ROOT/Modules/MyModule/resources/views/vendor/package/view-name.blade.php` to `ROJECT_ROOT/resources/views/vendor/package/view-name.blade.php`

**Comment by abhishek-pokhriyal** [comment]
> if you create a file
ROJECT_ROOT/resources/views/vendor/package/view-name.blade.php, you can overwrite ROJECT_ROOT/vendor/author/package/resources/views/view-name.blade.php

Yes, I'm aware of that and I can do that. But, is there no way to do it from inside the module?

**Comment by SocolaDaiCa** [comment]
> Yes, I'm aware of that and I can do that. But, is there no way to do it from inside the module?

It possible if your module load view before package, like that in MyModuleProvider
```php
View::prependNamespace('package', __DIR__ . '/../resources/views');
```

**Comment by abhishek-pokhriyal** [comment]
@SocolaDaiCa I was not able to make this work. However, I did something else which worked for me but I'm not sure if there can be any side-effects.

In my `config/view.php`:

```php
'paths' => [
    resource_path('views'),
    base_path('Modules/MyModule/Resources/Views'),
]
```

Now it is overriding the package view from the view defined in MyModule. What do you think about this?

**Comment by SocolaDaiCa** [comment]
> ```
> 'paths' => [
>     resource_path('views'),
>     base_path('Modules/MyModule/Resources/Views'),
> ]
> ```
when user public view of package to `ROJECT_ROOT/resources/views/vendor/package, It so confuse
