### ISSUE TITLE
Undefined property Module::$alias

### ISSUE THREAD

**Issue by jesusave** [nWidart/laravel-modules#1159]
Undefined property: Nwidart\Modules\Laravel\Module::$alias.

I was using version 5.* and there were no problems but I decided to upgrade to version 8.* and it stopped working when I did foreach.

In my Controller:

```
public function index()
{
    $modules = Module::all();
    return view('addons.index', compact('modules'));
}
```
In my View:
```
@foreach($modules as $module)
    {{ $module->alias }}
    {{ $module->name }}
    {{ $module->description }}
@endforeach
```

Am I doing something wrong?

**Comment by sammyukavi** [comment]
Try
`$module->get('alias');`
OR
`$module->getAlias()`
