### ISSUE TITLE
How to load Vue Component with InertiaJS in Laravel 8 Modules

### ISSUE THREAD

**Issue by lavecart** [nWidart/laravel-modules#1162]
In Laravel 8 we can load Component with Inertiajs

We initialize Inertia in `app.blade.php` with this `@inertia`

After that in `app.js` file, we can initialize it like this:
```
const app = document.getElementById('app');

new Vue({
    render: (h) =>
        h(InertiaApp, {
            props: {
                initialPage: JSON.parse(app.dataset.page),
                resolveComponent: (name) => require(`./Pages/${name}`).default,
            },
        }),
}).$mount(app);
```

Then all components will load from the Pages folder.

Now, my question is:

How can I achieve it in a Module? I want to load Vuejs Components using Inertiajs. In module, this Resources/assets/js/app.js file is empty. If I put the above code in it and create a Pages folder but it's giving me error!
```
import { createApp, h } from 'vue'
import { App, plugin } from '@inertiajs/inertia-vue3'

const el = document.getElementById('app')

createApp({
  render: () => h(App, {
    initialPage: JSON.parse(el.dataset.page),
    resolveComponent: name => require(`./Pages/${name}`).default,
  })
}).use(plugin).mount(el)
```

In Core ( I made this ) module `master.blade.php`

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Module Core</title>
       <link rel="stylesheet" href="{{ mix('css/core.css') }}">

    </head>
    <body>
        @inertia
        <script src="{{ mix('js/core.js') }}"></script>
    </body>
</html>
```

CoreController:

```
use Inertia\Inertia;

class CoreController extends Controller
{
    public function index()
    {
        return Inertia::render('Admin/Index');
    }
}
```
I have a Page in assets/js/Pages/Admin/Index.vue

I want to load this. But giving me error:

**[Vue warn]: Error in created hook: "Error: Cannot find module './Admin/Index'"**

**Comment by yashiroiori** [comment]
Can try with this

![image](https://user-images.githubusercontent.com/17031855/104405715-42ed5b00-5523-11eb-8d5a-1c8c2b82fc86.png)

And into controller to load Module vue component
The sintax use is: Module/{ModuleName}/{ComponentName} and this search with path Modules/ModuleName/Resources/assets/js/Pages/ComponentName
![image](https://user-images.githubusercontent.com/17031855/104405764-5e586600-5523-11eb-83fd-8225acd5c1cf.png)

**Comment by yashiroiori** [comment]
Can make work??

**Comment by enextiarg** [comment]
I did some similar, using widart nomenclature in modules

Resolve function in app.js
```
resolveComponent: (name) => {
                let parts = name.split('::')
                let type = false
                console.log(parts.length)
                if (parts.length > 1) { 
                    type = parts[0]
                    parts.splice(0,1)
                }
                if(type) return require(`../../Modules/${type}/Resources/assets/js/${parts[0]}`).default
                return require(`./Pages/${name}`).default
            }
````

And returning inertia view in controller 

```
return Inertia::render('Test::Dashboard');
````

So you can use some folder structure of your module eg.

```
return Inertia::render('MyModule::Clients/Index');
```

**Comment by makusdouglas** [comment]
@enextiarg i have try it but getting the same error.
This Error is originated by Mix when running 'npm run dev':

![image](https://user-images.githubusercontent.com/56944784/115113645-adb69400-9f61-11eb-8c91-220e2f15ea2b.png)

Mix is trying to compile .php files.
How can i solve this?

sorry my bad english ;)

**Comment by enextiarg** [comment]
Could you share your webpack.mix.js and config?

**Comment by makusdouglas** [comment]
@enextiarg, this is my config.
I started working with Laravel recently, I'm probably doing something wrong 😄
In **resources/js/app.js** : 
![image](https://user-images.githubusercontent.com/56944784/115281510-77bf0e80-a11f-11eb-890b-66ca0cc271bf.png)
![image](https://user-images.githubusercontent.com/56944784/115281554-873e5780-a11f-11eb-8fa7-0efa53253c13.png)

In **webpack.mix.js** : 
![image](https://user-images.githubusercontent.com/56944784/115281759-bb197d00-a11f-11eb-8e6d-57d169d4da4f.png)
In **webpack.config.js** (file generated by [Jestream Inertia](https://jetstream.laravel.com/1.x/stacks/inertia.html)
![image](https://user-images.githubusercontent.com/56944784/115282171-43981d80-a120-11eb-96ec-049a4eac06db.png)

When run yarn *dev* or *watch*:
![image](https://user-images.githubusercontent.com/56944784/115283347-9e7e4480-a121-11eb-9574-b248807dcb4c.png)

**Comment by enextiarg** [comment]
Please check there are missing dependencies, please do  

`npm i laravel-mix-merge-manifest ignore-loader`

**Comment by SonnySha** [comment]
Hello,
I finded the solutions



`
render: () =>
        h(InertiaApp, {
            initialPage: JSON.parse(el.dataset.page),
            resolveComponent: (name) => {
                let parts = name.split('::')
                let type = false
                if (parts.length > 1) type = parts[0]
                if(type) {
                    let nameVue = parts[1].split('.')[0]
                    return require("../../Modules/" + parts[0] + "/Resources/js/Pages/" + nameVue + ".vue").default
                }else {
                    return require(`./Pages/${name}`).default
                }
            },
        }),
})
`

**Comment by SonnySha** [comment]
Hello,

I finded the solution,

``

```
render: () =>
        h(InertiaApp, {
            initialPage: JSON.parse(el.dataset.page),
            resolveComponent: (name) => {
                let parts = name.split('::')
                let type = false
                if (parts.length > 1) type = parts[0]
                if(type) {
                    let nameVue = parts[1].split('.')[0]
                    return require("../../Modules/" + parts[0] + "/Resources/js/Pages/" + nameVue + ".vue").default
                }else {
                    return require(`./Pages/${name}`).default
                }
            },
        }),
    })
````

Hope to help you

**Comment by adam-devapp** [comment]
> Hello,
> 
> I finded the solution,
> 
> ``
> 
> ```
> render: () =>
>         h(InertiaApp, {
>             initialPage: JSON.parse(el.dataset.page),
>             resolveComponent: (name) => {
>                 let parts = name.split('::')
>                 let type = false
>                 if (parts.length > 1) type = parts[0]
>                 if(type) {
>                     let nameVue = parts[1].split('.')[0]
>                     return require("../../Modules/" + parts[0] + "/Resources/js/Pages/" + nameVue + ".vue").default
>                 }else {
>                     return require(`./Pages/${name}`).default
>                 }
>             },
>         }),
>     })
> ```
> 
> Hope to help you

Can you paste your whole app.js?

**Comment by adam-devapp** [comment]
This is my working version.

```
require('./bootstrap');

import { createApp, h } from 'vue';
import { createInertiaApp } from '@inertiajs/inertia-vue3';
import { InertiaProgress } from '@inertiajs/progress';

const appName = window.document.getElementsByTagName('title')[0]?.innerText || 'Laravel';

createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name => {
        let parts = name.split('::')
        let type = false
        if (parts.length > 1) {
            type = parts[0]
        }
        if (type) {
            let nameVue = parts[1].split('.')[0]
            return import("../../Modules/" + parts[0] + "/Resources/assets/js/" + nameVue + ".vue")
        }else {
            return import(`./Pages/${name}`)
        }
    }),
    setup({ el, app, props, plugin }) {
        return createApp({ render: () => h(app, props) })
            .use(plugin)
            .mixin({ methods: { route } })
            .mount(el);
    },
});

InertiaProgress.init({ color: '#4B5563' });

```

**Comment by hesammoosapour** [comment]
I just commented `import { InertiaApp } from '@inertiajs/inertia-vue'` and the error went away.

**Comment by garbinmarcelo** [comment]
Hi, I'm starting with Inertia now. 

How is the integration of Laravel Modules with Inertia? Any difficulties?

Thanks

**Comment by maxonfjvipon** [comment]
Hey everyone. If you stuck with dynamic import/require problem using modules and Inertia, check [this](https://github.com/inertiajs/inertia/issues/957#issuecomment-969384686) out. 
Works perfectly.

**Comment by wadday** [comment]
hello everyone. My approach to solving this issue is a bit different. (Inertia with modules)

in my base app.js remains the same (note: I have used dynamic import)
![image](https://user-images.githubusercontent.com/194339/160081817-a5a30f19-adb8-4880-9466-369253028bb0.png)

Structure arrangements I follow the same as the base structure 

base structure
![image](https://user-images.githubusercontent.com/194339/160082429-0b7cda7e-3540-401d-a760-2af2c2f2ec6d.png)

Modules/Expenses structure
![image](https://user-images.githubusercontent.com/194339/160082706-069c8e8c-66bd-4102-85c0-fbd5fb466f99.png)

In base app controller (resources/js/Pages/Welcome.vue)
![image](https://user-images.githubusercontent.com/194339/160083309-1c0276a8-f514-4c7b-8102-45aa8e46dc62.png)

in module controller (Expenses/Pages/ExpensesIndex.vue => resources/js/Pages/Expenses/Pages/ExpensesIndex.vue)
![image](https://user-images.githubusercontent.com/194339/160083578-1bec9e59-7278-4ffd-b9d7-2fc52cc4b589.png)

I have created a command to link Modules.
![image](https://user-images.githubusercontent.com/194339/160084811-564d462e-bcb3-4418-b4f6-da5a22061511.png)

and finally how the base structure looks like
![image](https://user-images.githubusercontent.com/194339/160084573-f109f269-3e68-4460-9f2f-a455ef69eb34.png)

### Sharing data between module to base app. (ExpensesServiceProvider)
![image](https://user-images.githubusercontent.com/194339/160085665-bb7a253c-71d7-4553-b9c8-33c385d827f3.png)

base app Middleware (HandleInertiaRequests extends \Inertia\Middleware)
![image](https://user-images.githubusercontent.com/194339/160086141-2554ec6d-e403-444b-a661-4c274098f940.png)

note: the config loads the enabled modules so the main app has only access to enabled modules. (custom config)

Modules/Expenses middleware (ShareDataMiddleware extends \Inertia\Middleware)
![image](https://user-images.githubusercontent.com/194339/160085787-92a7a4cb-6753-4cdc-b8cd-6e38ee257426.png)

### Result
base app
![image](https://user-images.githubusercontent.com/194339/160086823-54babb5b-ecb3-4f0f-8baa-20021a69b096.png)

module (expenses)
![image](https://user-images.githubusercontent.com/194339/160086958-152b2ccb-e026-49a8-8bdc-773cbf132d3d.png)

in my demonstration, I have shared expenses (empty array) from module share data middleware. (highlighter)
![image](https://user-images.githubusercontent.com/194339/160087231-2459bac3-4ba5-45bf-9a32-6581a89192f3.png)


The idea for this approach is later I want to extract the module as a separate package it will be an easy workflow to integrate into a new project.

hope this is useful.

**Comment by enextiarg** [comment]
I like your idea!

**Comment by diorz38** [comment]
> hello everyone. My approach to solving this issue is a bit different. (Inertia with modules)
> 
> in my base app.js remains the same (note: I have used dynamic import) ![image](https://user-images.githubusercontent.com/194339/160081817-a5a30f19-adb8-4880-9466-369253028bb0.png)
> 
> Structure arrangements I follow the same as the base structure
> 
> base structure ![image](https://user-images.githubusercontent.com/194339/160082429-0b7cda7e-3540-401d-a760-2af2c2f2ec6d.png)
> 
> Modules/Expenses structure ![image](https://user-images.githubusercontent.com/194339/160082706-069c8e8c-66bd-4102-85c0-fbd5fb466f99.png)
> 
> In base app controller (resources/js/Pages/Welcome.vue) ![image](https://user-images.githubusercontent.com/194339/160083309-1c0276a8-f514-4c7b-8102-45aa8e46dc62.png)
> 
> in module controller (Expenses/Pages/ExpensesIndex.vue => resources/js/Pages/Expenses/Pages/ExpensesIndex.vue) ![image](https://user-images.githubusercontent.com/194339/160089957-e6b3a7f7-5816-49dd-bb9d-1090ed5f6d8d.png)
> 
> I have created a command to link Modules. ![image](https://user-images.githubusercontent.com/194339/160084811-564d462e-bcb3-4418-b4f6-da5a22061511.png)
> 
> and finally how the base structure looks like ![image](https://user-images.githubusercontent.com/194339/160084573-f109f269-3e68-4460-9f2f-a455ef69eb34.png)
> 
> ### Sharing data between module to base app. (ExpensesServiceProvider)
> ![image](https://user-images.githubusercontent.com/194339/160085665-bb7a253c-71d7-4553-b9c8-33c385d827f3.png)
> 
> base app Middleware (HandleInertiaRequests extends \Inertia\Middleware) ![image](https://user-images.githubusercontent.com/194339/160086141-2554ec6d-e403-444b-a661-4c274098f940.png)
> 
> note: the config loads the enabled modules so the main app has only access to enabled modules. (custom config)
> 
> Modules/Expenses middleware (ShareDataMiddleware extends \Inertia\Middleware) ![image](https://user-images.githubusercontent.com/194339/160085787-92a7a4cb-6753-4cdc-b8cd-6e38ee257426.png)
> 
> ### Result
> base app ![image](https://user-images.githubusercontent.com/194339/160086823-54babb5b-ecb3-4f0f-8baa-20021a69b096.png)
> 
> module (expenses) ![image](https://user-images.githubusercontent.com/194339/160086958-152b2ccb-e026-49a8-8bdc-773cbf132d3d.png)
> 
> in my demonstration, I have shared expenses (empty array) from module share data middleware. (highlighted) ![image](https://user-images.githubusercontent.com/194339/160087231-2459bac3-4ba5-45bf-9a32-6581a89192f3.png)
> 
> and finally module components are loaded from Modules. ![image](https://user-images.githubusercontent.com/194339/160090631-f57d0fdf-54a5-435d-adcf-6663c8571910.png)
> 
> The idea for this approach is later I want to extract the module as a separate package it will be an easy workflow to integrate into a new project.
> 
> hope this is useful.

can you make some example app with your approach?

**Comment by AxelGanter** [comment]
Hello everyone,
am a little desperate right now. 
i want to have my inertia pages delivered from the module.

![photo_2022-05-28_11-03-31](https://user-images.githubusercontent.com/2836270/170818705-f0c93fe8-4558-400e-9f08-f062a4dd0e00.jpg)
![photo_2022-05-28_11-03-22](https://user-images.githubusercontent.com/2836270/170818706-00f87f54-5ade-4f2e-ad44-35ac5c7093f5.jpg)

both methods work, but my webpack is unhappy and i can't tell why.

I dont want to have 365 errors when using the dynamic approach, but I need to have my module flexible

can one of you help me?

**Comment by AxelGanter** [comment]
seems like Webpack is going right into my Modules-Folder and trying to work on each file

[crashlog.txt](https://github.com/nWidart/laravel-modules/files/8790877/crashlog.txt)

**Comment by AxelGanter** [comment]
![image](https://user-images.githubusercontent.com/2836270/170820089-0d0eec72-8467-4e05-a07c-78a20634d2f2.png)

this was my solution for now. but still curious, how webpack is working (?)

remember to also add your module Resources (with capital "R") to your tailwind.config.js

![image](https://user-images.githubusercontent.com/2836270/170820157-e3a9e805-1814-4a86-aa12-f36cc820865a.png)

**Comment by irvine48** [comment]
**package.json**

```
{
    "private": true,
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "devDependencies": {
        "@tailwindcss/forms": "^0.5.2",
        "autoprefixer": "^10.4.2",
        "axios": "^0.27",
        "laravel-vite-plugin": "^0.5.0",
        "lodash": "^4.17.19",
        "postcss": "^8.4.6",
        "tailwindcss": "^3.1.0",
        "vite": "^3.0.0",
        "vite-plugin-windicss": "^1.8.7"
    },
    "dependencies": {
        "@inertiajs/inertia": "^0.11.0",
        "@inertiajs/inertia-vue3": "^0.6.0",
        "@vitejs/plugin-vue": "^3.0.3",
        "vue": "^3.2.36",
        "vue-loader": "^17.0.0"
    }
}
```


**vite.config.js**

```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';

export default defineConfig({
    plugins: [
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false,
                },
            },
        }),
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
                'resources/**/*.vue',
                'resources/**/**/*.vue',
                './Modules/**/Resources/**/*.vue',
            ],
            refresh: true,
        }),
    ],
});
```


**Laravel Controller**

```
return Inertia::render('Admin::Admin/Index', [
            'title' => 'Demo From Admin Controller',
            'object' => [
                'foo' => 'foofoo',
                'bar' => 'barbar',
            ],
]);
```

**app.js**

```
import { createApp, h } from 'vue'
import { createInertiaApp } from '@inertiajs/inertia-vue3'
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';

createInertiaApp({
    resolve: (name => {
        let parts = name.split('::')
        let type = false
        if (parts.length > 1) {
            type = parts[0]
        }
        if (type) {
            let nameVue = parts[1].split('.')[0];
            return resolvePageComponent(`../../Modules/${parts[0]}/Resources/Pages/${nameVue}.vue`, import.meta.glob([
                `../../Modules/**/Resources/Pages/**/*.vue`,
            ]));
        }else {
            return resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob([
                './Pages/**/*.vue',
            ]));
        }
    }),
    setup({ el, app, props, plugin }) {
        return createApp({ render: () => h(app, props) })
            .use(plugin)
            .mount(el);
    },
});
```

combine code from Laravel 9.16+ & Vite and some code here.
hope this help someone.

**Comment by jobasc0** [comment]
@irvine48 I am having this error, Uncaught (in promise) Error: Page not found: ./Pages/core::index.vue
    at aF (app.9d94ba7e.js:111:98)
    at resolve (app.9d94ba7e.js:111:17733)
    at m (app.9d94ba7e.js:39:954)
    at r0 (app.9d94ba7e.js:39:1028)
    at app.9d94ba7e.js:111:17694 
after following your tutorial, what should i do?

**Comment by wadday** [comment]
> @irvine48 I am having this error, Uncaught (in promise) Error: Page not found: ./Pages/core::index.vue at aF (app.9d94ba7e.js:111:98) at resolve (app.9d94ba7e.js:111:17733) at m (app.9d94ba7e.js:39:954) at r0 (app.9d94ba7e.js:39:1028) at app.9d94ba7e.js:111:17694 after following your tutorial, what should i do?

Check this repo. 
https://github.com/wadday/laravel-modules-inertia/tree/vite

**Comment by wadday** [comment]
my new implementation main app.js resolve like this.
![image](https://user-images.githubusercontent.com/194339/188733552-fcdfedbb-9090-45d0-8ec4-340f0ca9fa96.png)

base app controller
![image](https://user-images.githubusercontent.com/194339/188733722-292b01ea-ddac-43c3-8d05-37b0b1236077.png)

in the module controller reference as ModuleName::directory.Filename
![image](https://user-images.githubusercontent.com/194339/188733803-a2914d99-7ae0-41b5-9676-5e32d6c74b53.png)

This is vite setup. 

also, note that my module resource structure is same as base app resource structure. i

**Comment by wadday** [comment]
> > @irvine48 I am having this error, Uncaught (in promise) Error: Page not found: ./Pages/core::index.vue
> > at aF (app.9d94ba7e.js:111:98)
> > at resolve (app.9d94ba7e.js:111:17733)
> > at m (app.9d94ba7e.js:39:954)
> > at r0 (app.9d94ba7e.js:39:1028)
> > at app.9d94ba7e.js:111:17694
> > after following your tutorial, what should i do?
> 
> Your core:: not being process? Double check that first.

Which example have you tried? I have given 2 options. first link to a repo. and second screenshots. 

Error: Page not found: ./Pages/core::index.vue
make sure you are giving the correct path from the controller.

**Comment by jobasc0** [comment]
Hi, thanks a lot for your help, my setup is such a way that my index is directed to my core module so in my main app web routes i have 
Route::get('/', 'Modules\Core\Http\Controllers\CoreController@index')->name('index');
to direct tracfic to my Modules/Core/index.vue
and Modules is using the default Nwidart laravel-modules Resources so i have created a Pages folder in assets/js and placed my index.vue file there so don't know if that setup is the problem

**Comment by jobasc0** [comment]
@wadday Can you please paste your code? i can't read the screen shot i am having some display problems with my machine.

**Comment by jobasc0** [comment]
@wadday can you please post your whole app.js file? it seems there's a mistake some where.

**Comment by wadday** [comment]
@jobasc0 problem I noticed is how you referring to the component path in the controller.

referring to the resolve portion of the screenshot I've shared.

### in this example, I will use your core module.
1. Splitting the name (component path) using (::) in the resolve method
`let pages = name.split('::');`
this could expect an array of 2 elements in pages variable.

therefore, I am checking 
```
if (pages.length > 1) {
//if pages greater than 1 which means it returns more than 1 item in the pages array in
//your case Core as 1st element and Pages/Index as 2nd element.

//below line extracting 1st element as module (in your case core) and 2nd element as component path (Pages/Index)
const [module, paths] = pages

//here I am splitting the paths using dot (.) and joining forward slash (/).
// meaning in your controller you should define inertia('Core::Index) if the component is within a directory inside Pages //directory you should use dot (.) to separate example: inertia('Core::FolderName.Filename')
//if the file is directly in the Pages folder. inertia('Core::Index')
const moduleFileName = paths.split('.').join('/');

return resolvePageComponent(
                `../../Modules/${module}/Resources/js/Pages/${moduleFileName}.vue`,
                import.meta.glob('../../Modules/*/*/js/Pages/**/*.vue')
            )
} else {
//this is to handle none module pages usually laravel base resource/js/Pages
return resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue'));
}
```

Note that in the module controller when you give a component name to the inertia method you don't need to define the Pages folder. that part is been handled by the above logic to build the path.

along with the resolve screenshot I have also mentioned this.
**note that my module resource structure is the same as the base app resource structure.**

also, make sure that your folder naming convention is applied when you pass the name from the controller. if the folder name is lower case or upper case or Capitalize or not.

**Comment by jobasc0** [comment]
@wadday Thanks a lot for your help, your code in the screen shot is not working, here is the error code from my site, 
[plugin:vite:import-glob] Unexpected token (13:99)
C:/wamp64/www/laravel/resources/js/app.js:13:99
11 |  if (pages.length > 1) {
12 |  const [module, paths] = pages const moduleFileName = paths.split(':').join('/'); page = resolvePageComponent(
13 |  path: '../../Modules/${module}/Resources/js/Pages/${moduleFileName}.vue', import.meta.glob( pattern: '../../Modules/*/*/js/Pages/**/*.vue'),
   |                                                                                                     ^
14 |  .then(page = {
15 |  page.default.layout = name.startsWith('Auth/') ? undefined : defaultLayout
And this is also from online js validator:
2:1 error Parsing error: Unexpected reserved word 'let' 1 | resolve: (name) = { > 2 | let page; let pages = name.split('::'); | ^ 3 | if (pages.length > 1) { 4 | const [module, paths] = pages const moduleFileName = paths.split(':').join('/'); page = resolvePageComponent( 5 | path: '../../Modules/${module}/Resources/js/Pages/${moduleFileName}.vue', import.meta.glob( pattern: '../../Modules/*/*/js/Pages/**/*.vue'),

**Comment by wadday** [comment]
@jobasc0 share your repository than only i will be able to help you.

**Comment by jobasc0** [comment]
@irvine48  Your code is working but it's showing module first name in small letter, what i mean is my module name is Core but the it's been rendered as core thats why it was working at first unless i manualy changed ${parts[0]} to my module name (Core) is there a work arround for this?

**Comment by wadday** [comment]
@jobasc0 DM me in Twitter @wadday

**Comment by jobasc0** [comment]
> @jobasc0 DM me in Twitter @wadday

Thanks

**Comment by jobasc0** [comment]
> @jobasc0 DM me in Twitter @wadday

Sorry, i just find out that my twitter account has been suspended

**Comment by wadday** [comment]
> 

https://www.facebook.com/iwadday

**Comment by jobasc0** [comment]
> > 
> 
> https://www.facebook.com/iwadday

That will do

**Comment by gabrieloureiro** [comment]
Is there any command to refresh the routes? In my case there are 2 components that are returning 404 even with the others working. I've used `php artisan route:clear`, but still not working.

![Screen Shot 2023-02-01 at 14 35 12](https://user-images.githubusercontent.com/39869298/216119454-133efddd-90e0-4a42-b1d1-382f6780f2a6.png)

**Comment by ZSSoftwareStudio** [comment]
> **package.json**
> 
> ```
> {
>     "private": true,
>     "scripts": {
>         "dev": "vite",
>         "build": "vite build"
>     },
>     "devDependencies": {
>         "@tailwindcss/forms": "^0.5.2",
>         "autoprefixer": "^10.4.2",
>         "axios": "^0.27",
>         "laravel-vite-plugin": "^0.5.0",
>         "lodash": "^4.17.19",
>         "postcss": "^8.4.6",
>         "tailwindcss": "^3.1.0",
>         "vite": "^3.0.0",
>         "vite-plugin-windicss": "^1.8.7"
>     },
>     "dependencies": {
>         "@inertiajs/inertia": "^0.11.0",
>         "@inertiajs/inertia-vue3": "^0.6.0",
>         "@vitejs/plugin-vue": "^3.0.3",
>         "vue": "^3.2.36",
>         "vue-loader": "^17.0.0"
>     }
> }
> ```
> 
> **vite.config.js**
> 
> ```
> import { defineConfig } from 'vite';
> import laravel from 'laravel-vite-plugin';
> import vue from '@vitejs/plugin-vue';
> 
> export default defineConfig({
>     plugins: [
>         vue({
>             template: {
>                 transformAssetUrls: {
>                     base: null,
>                     includeAbsolute: false,
>                 },
>             },
>         }),
>         laravel({
>             input: [
>                 'resources/css/app.css',
>                 'resources/js/app.js',
>                 'resources/**/*.vue',
>                 'resources/**/**/*.vue',
>                 './Modules/**/Resources/**/*.vue',
>             ],
>             refresh: true,
>         }),
>     ],
> });
> ```
> 
> **Laravel Controller**
> 
> ```
> return Inertia::render('Admin::Admin/Index', [
>             'title' => 'Demo From Admin Controller',
>             'object' => [
>                 'foo' => 'foofoo',
>                 'bar' => 'barbar',
>             ],
> ]);
> ```
> 
> **app.js**
> 
> ```
> import { createApp, h } from 'vue'
> import { createInertiaApp } from '@inertiajs/inertia-vue3'
> import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';
> 
> createInertiaApp({
>     resolve: (name => {
>         let parts = name.split('::')
>         let type = false
>         if (parts.length > 1) {
>             type = parts[0]
>         }
>         if (type) {
>             let nameVue = parts[1].split('.')[0];
>             return resolvePageComponent(`../../Modules/${parts[0]}/Resources/Pages/${nameVue}.vue`, import.meta.glob([
>                 `../../Modules/**/Resources/Pages/**/*.vue`,
>             ]));
>         }else {
>             return resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob([
>                 './Pages/**/*.vue',
>             ]));
>         }
>     }),
>     setup({ el, app, props, plugin }) {
>         return createApp({ render: () => h(app, props) })
>             .use(plugin)
>             .mount(el);
>     },
> });
> ```
> 
> combine code from Laravel 9.16+ & Vite and some code here. hope this help someone.

Hey, I can't run the build command with this vite config file.

**Comment by wadday** [comment]
Try this on app.js
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/194339/217052253-676b2dcc-ac56-4bae-bb02-03528a65652c.png">

```
 resolve: (name) => {
        let page;
        let pages = name.split('::');

        if (pages.length > 1) {
            const [module, paths] = pages
            const moduleFileName = paths.split('.').join('/');
            page = resolvePageComponent(
                `../../Modules/${module}/Resources/js/Pages/${moduleFileName}.vue`,
                import.meta.glob('../../Modules/*/*/js/Pages/**/*.vue')
            )
        } else {
            page = resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue'))
        }

        return page
    },
```

**Comment by jobasc0** [comment]
HI, I have been absent for some time now and i am trying to start a new project but my site is displaying a blank page.
My setup is like this.
(app.js)
import './bootstrap';
import '../css/app.css';

import { createApp, h } from 'vue';
import { createInertiaApp } from '@inertiajs/vue3';
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';
import { ZiggyVue } from '../../vendor/tightenco/ziggy/dist/vue.m';

const appName = import.meta.env.VITE_APP_NAME || 'Laravel';

createInertiaApp({
    title: (title) => `${title} - ${appName}`,

    resolve: (name) => {
        let page;
        let pages = name.split('::');

        if (pages.length > 1) {
            const [module, paths] = pages
            const moduleFileName = paths.split('.').join('/');
            page = resolvePageComponent(
                `../../Modules/${module}/Resources/views/Pages/${moduleFileName}.vue`,
                import.meta.glob('../../Modules/*/*/views/Pages/**/*.vue')
            )
        } else {
            page = resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue'))
        }

        return page
    },
    setup({el, app, props, plugin}) {
        const vueApp = createApp({render: () => h(app, props)}).use(plugin)
        vueApp.mount(el)
        return vueApp
    },
})

**Web Routes**
use Modules\Core\http\Controllers\CoreController;

Route::get('/', [CoreController::class,'index'], ['canLogin' => Route::has('login'),
        'canRegister' => Route::has('register'),])->name('index');

**Core Module Controller**
use Inertia\Inertia;

class CoreController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        return Inertia::render('Core::Pages.index');
    }

**Comment by hbend1li** [comment]
> Try this on app.js (intended for inertiajs earlier than v1.0) <img alt="image" width="1070" src="https://user-images.githubusercontent.com/194339/217052253-676b2dcc-ac56-4bae-bb02-03528a65652c.png">
> 
> ```
>  resolve: (name) => {
>         let page;
>         let pages = name.split('::');
> 
>         if (pages.length > 1) {
>            //for module path
>             const [module, paths] = pages
>             const moduleFileName = paths.split('.').join('/');
>             page = resolvePageComponent(
>                 `../../Modules/${module}/Resources/js/Pages/${moduleFileName}.vue`,
>                 import.meta.glob('../../Modules/*/*/js/Pages/**/*.vue')
>             )
>         } else {
>            //for none module
>             page = resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue'))
>         }
> 
>         return page
>     },
> ```
> 
> in module controller define component path like this. Notice the Module name is seperated with (::) and (.) dot instead of slash.
> 
> <img alt="image" width="602" src="https://user-images.githubusercontent.com/194339/217053156-67482a15-8fd0-4538-870d-69e718169069.png">
> 
> vite.config.js
> 
> ```
> plugins: [
>      laravel({
>          input: 'resources/js/app.js',
>      }),
>      vue({
>          template: {
>              transformAssetUrls: {
>                  base: null,
>                  includeAbsolute: false,
>              },
>          },
>      }),
>  ],
>  resolve: {
>      alias: {
>          '@': '/resources/js'
>      }
>  },
> ```

what work for me.
jast replace upper (R) of Ressource by Lower (r).
>`../../Modules/${module}/resources/views/Pages/${moduleFileName}.vue`,
