### ISSUE TITLE
Register/load module files only for admin not for user.

### ISSUE THREAD

**Issue by naeemhostingshouse** [nWidart/laravel-modules#1173]
@nWidart is it possible to register/load module files only for admin but not for user ?
For example How can I replace this function in module.php file?
![image](https://user-images.githubusercontent.com/61738451/106137353-6a336180-618c-11eb-88a2-65fa54a1ccb2.png)

**Comment by yashiroiori** [comment]
I use a database to register all modules and with spatie/permission verify have access to BREAD to build user menu and into controllers use Policy

**Comment by alibaba258** [comment]
> I use a database to register all modules and with spatie/permission verify have access to BREAD to build user menu and into controllers use Policy

@yashiroiori Could you give me a short explanation on how to achieve this?
