### ISSUE TITLE
Middleware auth:sanctum not working in Module route

### ISSUE THREAD

**Issue by Binay7587** [nWidart/laravel-modules#1177]
I installed 'Laravel/sanctum' through composer and published the vendor and migrated migrations and used Laravel\Sanctum\HasApiTokens on Entitites/User. 
There is an api route file on user module and 'auth:sanctum' middleware is used on '/api/me' route. It should send Unauthenticated JSON response when there is no token, but when i hit this api without token, its showing login page even if i had used Accept: application/json as header.

Also im not able to hit this api even if i have sent the current token.

This is my api route file:

`Route::post('/login', 'AuthController@login')->name('api.login');
Route::group(['middleware' => ['auth:sanctum']], function () {
    Route::get('/me', 'AuthController@getLoggedUser')->name('api.me');
});
`
![2021-02-01 15_07_14](https://user-images.githubusercontent.com/46816702/106438962-45e2c800-649f-11eb-8f15-c8f6397fad73.png)

This is the response i'm getting when I hit on postman.
![Response Image](https://user-images.githubusercontent.com/46816702/106455016-b4ca1c00-64b3-11eb-9d06-28170deb0a77.png)

Is there something I need to do to be able to use the middleware in the module?

**Comment by p0werage2k** [comment]
@Binay7587  I have the same issue, did you find a solution to the problem?

**Comment by Binay7587** [comment]
@p0werage2k  No, then I used tymon/jwt-auth package.

**Comment by rw4lll** [comment]
Faced with the same problem. After some investigation it seems the problem happens there: https://github.com/laravel/sanctum/commit/f5695aecc547138c76bc66aaede73ba549dabdc5

During the refactoring they forgot to include default guard definition.

Just add this at the end of config/sanctum.php for api guard:

'guard' =>  'api'

**Comment by M-Abdullahi** [comment]
I'm having the same problem. I've correctly setup sanctum and fortify and managed to login. However, subsequent requests to routes protected with auth:sanctum middleware throws authorization error.
![Screenshot from 2021-04-14 13-14-51](https://user-images.githubusercontent.com/14330689/114698136-693fb400-9d27-11eb-955a-b8c5a44e4e8f.png)
![Screenshot from 2021-04-14 13-14-28](https://user-images.githubusercontent.com/14330689/114698168-72308580-9d27-11eb-9e46-a26493aefc11.png)

**Comment by devlamine** [comment]
I have same error , not yet resolved ?

**Comment by M-Abdullahi** [comment]
Ended up using Laravel passport. It's an overkill, for now

**Comment by KamalEssam** [comment]
i face them Issue but i solved it by Add to headers **_Accept_**   with value _**application/json**_

that's the best solution i found maybe others have another solution.

<img width="853" alt="Screen Shot 2021-08-12 at 2 41 37 PM" src="https://user-images.githubusercontent.com/52505488/129198841-db17ce6f-5e71-41a0-9487-232e6e790d5f.png">

**Comment by Branimir** [comment]
![image](https://user-images.githubusercontent.com/1248309/131254931-29a7735d-8cca-492f-aa14-a16e6927e7bf.png)

It seems that this still doesn't work no matter what I do... When I hit a guarded endpoint with Insomnia or Postman (without valid token) I get 401 (which is expected), but my frontend Vue app (using axios) doesn't complain at all when hitting the same endpoint (it gets 200).
 
 Any hope this will be fixed any time soon?

**Comment by arnoldatse** [comment]
I was had the same problem, i have found the solution, it seems to me that is because you use a old version of laravel, you must to create a new laravel 8 version project and transfer all your files projects into.
After that, integrate and config laravel-sanctum

**Comment by wagaana** [comment]
Am new to laravel and I had the same problem, but I solved it by changing the gurds in the file **config/auth.php** to `

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],`

And changed the **routes/api.php** groups to `

Route::group(['middleware' => 'auth:api'], function () {
    Route::get('articles', [MyController::class, 'index']);
});`

**GOOD LUCK**

**Comment by cptiwari20** [comment]
The issue still exists. I am using laravel 7 and wanted to add a few APIs, `auth:sanctum` middleware seems not working.
Anyone can suggest it??

**Comment by amaraa019** [comment]
In my case cpanel apache denied Authorization header even i configured on htaccess file. So i created XauthorizationMiddleware then my problem solved...

**Comment by amaraa019** [comment]
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;

class XAuthorizationHeader
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next) {

        // check if we have an X-Authorization header present
        if($auth = $request->header('X-Authorization')) {
            $request->headers->set('Authorization', $auth);
        }

        return $next($request);
    }
}

**Comment by amaraa019** [comment]
`<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;

class XAuthorizationHeader
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next) {

        // check if we have an X-Authorization header present
        if($auth = $request->header('X-Authorization')) {
            $request->headers->set('Authorization', $auth);
        }

        return $next($request);
    }
}
`

**Comment by amaraa019** [comment]
`
   public function handle($request, Closure $next) {
        // check if we have an X-Authorization header present
        if($auth = $request->header('X-Authorization')) {
            $request->headers->set('Authorization', $auth);
        }
        return $next($request);
    }
`

**Comment by amaraa019** [comment]
public function handle($request, Closure $next) {

        // check if we have an X-Authorization header present
        if($auth = $request->header('X-Authorization')) {
            $request->headers->set('Authorization', $auth);
        }

        return $next($request);
    }

**Comment by amaraa019** [comment]
then you must have include line below on Kernel.php
`\App\Http\Middleware\XAuthorizationHeader::class,`

**Comment by andypapmedialight** [comment]
> In my case cpanel apache denied Authorization header even i configured on htaccess file. So i created XauthorizationHeader middleware then my problem solved...

@amaraa019 YES! thankyou, after hours of searching this was indeed the problem for me cpanel/apache strips certain header values by default for security reasons. Your solution worked for me.

**Comment by hbakouane** [comment]
I think your AuthController contains a __construct() method, that was the case for me, I removed and the middleware got applied on the request, I think that the reason is the __construct() method clears the middlewares array, so make sure you don't have one on your controller. Hope it works for you!

**Comment by Jaylton** [comment]
> In my case cpanel apache denied Authorization header even i configured on htaccess file. So i created XauthorizationHeader middleware then my problem solved...

Perfect
