### ISSUE TITLE
On Web Module not found

### ISSUE THREAD

**Issue by macikgoz25** [nWidart/laravel-modules#118]
Hi I develop a gallery module it does work on local web server no problem. When I try my hosting Module does not working Why ? 

I use list modules this code 

$modules = Module::toCollection();

empty result returning on web.

**Comment by adelowo** [comment]
This sounds weird. 

What errors are you getting when trying to use that module (say the routes)...

**Comment by macikgoz25** [comment]
I get error 404. I solved this problem. In Config/Module.php     

'scan' => [
        'enabled' => true,
        'paths' => [
            base_path('vendor/*/*'),
        ],
],

to

'scan' => [
        'enabled' => true,
        'paths' => [
            base_path('modules/*'),
        ],
    ],

now It is working.

**Comment by adelowo** [comment]
Oh great then... You should close this issue though
