### ISSUE TITLE
Serviceprovider class not found .

### ISSUE THREAD

**Issue by aishwaryakumar-hub** [nWidart/laravel-modules#1181]
I am creating a custom serviceprovider and adding it in register function like : 
 public function register()
    {
        $this->app->register(RouteServiceProvider::class);
        $this->app->register(LivewireServiceProvider::class); // Add this line
    }
But , I am getting error as Class 'Modules\Channel\Providers\LivewireServiceProvider' not found

**Comment by tnaffh** [comment]
Same issue over here also

**Comment by tnaffh** [comment]
Oh I forgot to autoload my modules:

```
{
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Modules\\": "Modules/"
    }
  }
}
```
For more info: https://nwidart.com/laravel-modules/v6/installation-and-setup

**Comment by aishwaryakumar-hub** [comment]
I asked about custom livewire service provider class.
