### ISSUE TITLE
 Command "module:make-component" is not defined.  

### ISSUE THREAD

**Issue by quentingosset** [nWidart/laravel-modules#1188]
When I try to create a component with the command "php artisan module:make-component Test" I get the error that the command is not defined. Is this normal?

**Comment by tamasori** [comment]
No, but yes. Its a bug in the package, if you publish the config file, you should find a part where all the command classes are listed. The two component related classes are missing. The commands keys value should look something like this:

'commands' => [
        CommandMakeCommand::class,
        ControllerMakeCommand::class,
        DisableCommand::class,
        DumpCommand::class,
        EnableCommand::class,
        EventMakeCommand::class,
        JobMakeCommand::class,
        ListenerMakeCommand::class,
        MailMakeCommand::class,
        MiddlewareMakeCommand::class,
        NotificationMakeCommand::class,
        ProviderMakeCommand::class,
        RouteProviderMakeCommand::class,
        InstallCommand::class,
        ListCommand::class,
        ComponentClassMakeCommand::class,
        ComponentViewMakeCommand::class,
        ModuleDeleteCommand::class,
        ModuleMakeCommand::class,
        FactoryMakeCommand::class,
        PolicyMakeCommand::class,
        RequestMakeCommand::class,
        RuleMakeCommand::class,
        MigrateCommand::class,
        MigrateRefreshCommand::class,
        MigrateResetCommand::class,
        MigrateRollbackCommand::class,
        MigrateStatusCommand::class,
        MigrationMakeCommand::class,
        ModelMakeCommand::class,
        PublishCommand::class,
        PublishConfigurationCommand::class,
        PublishMigrationCommand::class,
        PublishTranslationCommand::class,
        SeedCommand::class,
        SeedMakeCommand::class,
        SetupCommand::class,
        UnUseCommand::class,
        UpdateCommand::class,
        UseCommand::class,
        ResourceMakeCommand::class,
        TestMakeCommand::class,
        LaravelModulesV6Migrator::class,
    ],
    
    The two missing classes are:
        ComponentClassMakeCommand::class
        ComponentViewMakeCommand::class

**Comment by quentingosset** [comment]
However, I have the last updated package with the 2 commands added in the ConsoleServiceProvider :/ 

![image](https://user-images.githubusercontent.com/6824137/108403554-237ed780-721f-11eb-8590-83df47c73ad9.png)

**Comment by vishalscrimatec** [comment]
I am facing the same issue. but on windows  Command "make:component" is not defined.

  Did you mean one of these?
      make:auth
      make:command
      make:controller
      make:event
      make:job
      make:listener
      make:mail
      make:middleware
      make:migration
      make:model
      make:notification
      make:policy
      make:provider
      make:request
      make:seeder
      make:test

what should i do?

**Comment by vishalscrimatec** [comment]
![error](https://user-images.githubusercontent.com/79529605/111929814-73caad00-8add-11eb-8aa7-f564c9b11a71.png)

**Comment by virgiltu** [comment]
> No, but yes. Its a bug in the package, if you publish the config file, you should find a part where all the command classes are listed. The two component related classes are missing. The commands keys value should look something like this:
> 
> 'commands' => [
> CommandMakeCommand::class,
> ControllerMakeCommand::class,
> DisableCommand::class,
> DumpCommand::class,
> EnableCommand::class,
> EventMakeCommand::class,
> JobMakeCommand::class,
> ListenerMakeCommand::class,
> MailMakeCommand::class,
> MiddlewareMakeCommand::class,
> NotificationMakeCommand::class,
> ProviderMakeCommand::class,
> RouteProviderMakeCommand::class,
> InstallCommand::class,
> ListCommand::class,
> ComponentClassMakeCommand::class,
> ComponentViewMakeCommand::class,
> ModuleDeleteCommand::class,
> ModuleMakeCommand::class,
> FactoryMakeCommand::class,
> PolicyMakeCommand::class,
> RequestMakeCommand::class,
> RuleMakeCommand::class,
> MigrateCommand::class,
> MigrateRefreshCommand::class,
> MigrateResetCommand::class,
> MigrateRollbackCommand::class,
> MigrateStatusCommand::class,
> MigrationMakeCommand::class,
> ModelMakeCommand::class,
> PublishCommand::class,
> PublishConfigurationCommand::class,
> PublishMigrationCommand::class,
> PublishTranslationCommand::class,
> SeedCommand::class,
> SeedMakeCommand::class,
> SetupCommand::class,
> UnUseCommand::class,
> UpdateCommand::class,
> UseCommand::class,
> ResourceMakeCommand::class,
> TestMakeCommand::class,
> LaravelModulesV6Migrator::class,
> ],
> 
> ```
> The two missing classes are:
>     ComponentClassMakeCommand::class
>     ComponentViewMakeCommand::class
> ```

do you have to run a comment after adding this? It still does not work.

**Comment by unclesam1991** [comment]
am facing the same issue. but on windows Command "make:component" is not defined.
 how to fix this issue. i'm get issue when install nwidart

**Comment by SocolaDaiCa** [comment]
@unclesam1991 You can try https://packagist.org/packages/socoladaica/laravel-modules-command
