### ISSUE TITLE
error 404 in apache

### ISSUE THREAD

**Issue by mahdi29sh** [nWidart/laravel-modules#1189]
Hello dear Nicholas
We encountered a 404 error when deploying the project in Apache. And after much research, we found that only the routes and structure of this package give a 404 error.
Please help us
------------------------------------------------

my laravel version is 7.28
package version is 7.3
and apache 2
php 7.4

**Comment by Hodel1** [comment]
Configure your composer.
It seems you dont had whitelisted that Module main namespace
