### ISSUE TITLE
Calling module_path() causes ErrorException while my module ServiceProvider is booting

### ISSUE THREAD

**Issue by aachekalov** [nWidart/laravel-modules#1191]
Hello!

I've been trying to use my module in my another project via https://github.com/joshbrw/laravel-module-installer

When I call `module_path()` inside `boot()` of my module ServiceProvider I got:
```
   ErrorException 

  Trying to access array offset on value of type null

  at vendor/nwidart/laravel-modules/src/LaravelModulesServiceProvider.php:59
     55▕             return new Laravel\LaravelFileRepository($app, $path);
     56▕         });
     57▕         $this->app->singleton(Contracts\ActivatorInterface::class, function ($app) {
     58▕             $activator = $app['config']->get('modules.activator');
  ➜  59▕             $class = $app['config']->get('modules.activators.' . $activator)['class'];
     60▕ 
     61▕             if ($class === null) {
     62▕                 throw InvalidActivatorClass::missingConfig();
     63▕             }
```

After I published the package's configuration file (readme says it is _optionally_):
`php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"`
everything works fine.

I think that's because you call `$this->mergeConfigFrom()` from `boot()` instead of `register()` in your `LaravelModulesServiceProvider`
See https://laravel.com/docs/8.x/packages#default-package-configuration

I suggest call `$this->mergeConfigFrom()` from `register()` but call `$this->publishes()` from `boot()`
See https://laravel.com/docs/8.x/packages#configuration

Thank you

**Comment by turbo124** [comment]
Came here to plus one this. @aachekalov were you able to resolve this?

**Comment by maxcelos** [comment]
I've replaced  `module_path()` by `__DIR__...` in a few cases. If your suggestion solves this problem please submit a PR.
