### ISSUE TITLE
Install the jwt package inside the module itself

### ISSUE THREAD

**Issue by BehroozBvk** [nWidart/laravel-modules#1194]
Hi,
I want to create an **Auth** module using Lumen that can be implemented by **JWT**, and I want to install the **JWT** package inside the **Auth** module itself, not inside the project root. Is this possible? . How?

**Comment by BehroozBvk** [comment]
@nWidart Do you have any comments?

**Comment by SocolaDaiCa** [comment]
You can do that, install jwt in your module and install your module on your project
