### ISSUE TITLE
Is it possible to add custom methods to Module instance? [question]

### ISSUE THREAD

**Issue by vrerabek** [nWidart/laravel-modules#1196]
Hi
As documentation states, there are multiple methods on $module instance, is there a possibility, to extend this and add custom methods?
For example if I want module to have method `$module->returnSomething(); `?

Thanks in advance!

**Comment by AlexSabur** [comment]
Use  macro
```php
    public function boot()
    {
        \Nwidart\Modules\Module::macro('returnSomething', function () {
            /** @var \Nwidart\Modules\Module $this */
            return $this->getName();
        });
    }
 ```

**Comment by vrerabek** [comment]
> 
> 
> Use macro
> 
> ```
>     public function boot()
>     {
>         \Nwidart\Modules\Module::macro('returnSomething', function () {
>             /** @var \Nwidart\Modules\Module $this */
>             return $this->getName();
>         });
>     }
> ```

Thanks for the reply, that's almost what I'm looking for! I would want to do this, but specific for each module. Let's say I have module `Contacts` and I want the method `returnSomething()` be different than on module `Dashboard`.
Is that possible?

**Comment by AlexSabur** [comment]
emm... ?
```php
public function boot()
{
    \Nwidart\Modules\Module::macro('returnSomething', function () {
        /** @var \Nwidart\Modules\Module $this */
        switch ($this->getName()) {
            case 'Contacts':
                return 'its contact';
            case 'Dashboard':
                return 'its Dashboard';
            default:
                throw new \Exception("its an unknown module");
        }
    });
}
```
