### ISSUE TITLE
does not load module paths when I use spa wildcard in main web.php

### ISSUE THREAD

**Issue by romeldev** [nWidart/laravel-modules#1197]
Modules web.php and api.php paths don't work when I add:
`Route::view('{any}', 'spa')->where('any', '.*');`
in the main web.php

Notes:
- I have no more paths in the main file.
- si remuevo la  spa funcionan las rutas de los modulos

**Comment by AlexSabur** [comment]
try `Route::fallback(fn () => view('spa'));`
