### ISSUE TITLE
Question: what is different in v8 compared to v6

### ISSUE THREAD

**Issue by rabol** [nWidart/laravel-modules#1198]
Hi

The documentation - https://nwidart.com/laravel-modules/v6/introduction - is not mentioning v8.

What are the changes and what to watch out for ?

**Comment by rogatty** [comment]
Check out the changelog: https://github.com/nWidart/laravel-modules/blob/8.2.0/CHANGELOG.md

**Comment by rabol** [comment]
I did look at the change log, but... there are a few things 'missing' :)

e.g. what is php artisan module:publish doing?
what command do I use to publish the views of a Module so I can override them.

Sure, I know I can look into the code, but it would be nice with documentation

**Comment by rabol** [comment]
Not sure if this is a good example, but:

```
protected $description = 'Publish a module\'s assets to the application';

/**
     * Publish assets from all modules.
     */
    public function publishAll()
    {
        foreach ($this->laravel['modules']->allEnabled() as $module) {
            $this->publish($module);
        }
    }

```

The comment say that it will publish assets for all modules, whereas I would have expected it to publish all assets for the module specified e.g.

```
php artisan module:publish Blog
```
