### ISSUE TITLE
Can i active all module or in list module specific by cli

### ISSUE THREAD

**Issue by ducvu91** [nWidart/laravel-modules#1202]
Hi all, i have issue in CI/CD, when deploy finish, i run a litte command php artisan cache:clear, php artisan config:clear.
After that it auto disable some module and it make error. Now, when every deploy, i must active module by manual :(

So how can a command to active all module in project or some list module was defined ?

Thanks a lot and have nice weekend.

**Comment by dcblogdev** [comment]
to activate all modules you can use 

```
php artisan module:enable
```

don't provide a module and all module will be enabled.

Also, there is modules_statuses.json inside the project root that contains a boolean for each module, which could also be used to enable, disable modules.
