### ISSUE TITLE
Global Provider

### ISSUE THREAD

**Issue by andresilva96** [nWidart/laravel-modules#1204]
Hello, I'm using the skeleton of the modules in a peculiar way, example:

- Modules
  - Module 1
    - Resources
    - Routes
  - Module 2
    - Resources
    - Routes
 
So I created a global `ModuleServiceProvider` that each `module.json` sees in the same Provider, to load faster (I believe) and use less unused folders / files etc ...

I'm trying to define the module used with `Module::setUsedNow()`, so I loaded the last modules.

Is there any way to stop loading all modules when I match the selected module? I wanted to use less files in my modules, but I accept tips.

**Comment by maxcelos** [comment]
For me the all point in the modular approach is to separate everything in its specific module/domain and make then not dependent each other. Not gluing then with a super-module.

If you want to centralize some common logic, create a base class and extend it inside the modules.

There is no point on place modules in a subdirectory, Your "Global Provider" could be placed in the Laravel's native "Providers" folder or in a specific module, to be extended by the others.

If you need to discuss this further, use the "Discussions" tab. This is not an issue.
