### ISSUE TITLE
Issue in loading blade view component class

### ISSUE THREAD

**Issue by iamine** [nWidart/laravel-modules#1206]
There is an issue on loading blade view component class

steps to reproduce

create a fresh laravel project and require laravel-modules

make a module

```console
php artisan module:make Example
```

then make a component

```console
php artisan module:make-component Example Example
```

after that on Modules/Resources/views/index.blade.php load that component

```blade
<x-example::example />
```

this will load the component blade file, and ignore the component class located here

Modules/Example/View/Component/Example.php

Fix:

is to register component name space on the module service provider

```php
Blade::componentNamespace(\Config::get('modules.namespace')."\\".$this->moduleName."\\View\\Component", $this->moduleNameLower);
```

**Comment by iamine** [comment]
if you find mark this as an issue i will make a pull request to fix it

**Comment by SocolaDaiCa** [comment]
It is not a issue, https://laravel.com/docs/8.x/blade#manually-registering-package-components

you can use
```php
Blade::component('package-alert', Alert::class);
<x-package-alert/>
```
or
```php
Blade::componentNamespace('Nightshade\\Views\\Components', 'nightshade');

<x-nightshade::calendar />
<x-nightshade::color-picker />
```

**Comment by iamine** [comment]
Components Namespace must be loaded automatically? no?

so you don't need to register the component namespace on each module.

**Comment by SocolaDaiCa** [comment]
@iamine Components Namespace is not loaded automatically
you need to register the component namespace on each module
