### ISSUE TITLE
laravel boot the modules in Ascending order ignoring the priority value for each module

### ISSUE THREAD

**Issue by samerzaki** [nWidart/laravel-modules#1208]
hello, my problem was mentioned before in this issue
https://github.com/nWidart/laravel-modules/issues/994

I want to boot the modules by the order(priority) I determined in module.json
but laravel overriding that and boot the service provider for each module instead of letting that task to (nWidart/laravel-modules)

1-for each module, I tried to delete from its composer.json the service provider name, but it didn't work
2-in main app composer.json, tried to use (dont-discover) feature, it worked successfully but means I needs to disable auto-discover for each module manually

so, any solution to boot each module service provider by the priority I want ?

**Comment by SocolaDaiCa** [comment]
you can edit file module.json in each package

**Comment by samerzaki** [comment]
i found out the solution to the problem, to simplify it for example:
if we have 3 modules
moduleX( priority:2 )
moduleY( priority:1 )
moduleZ( priority0 )

in normal situation, modules ordering will be (Z > Y > X)
but if **moduleZ** depends on **moduleX** (in composer.json)
then the laravel will ignore modules priority and boot first **moduleX**, then **moduleZ**, finally **moduleY**

**Comment by SocolaDaiCa** [comment]
Mean It is normal case
