### ISSUE TITLE
Laravel Modules Command

### ISSUE THREAD

**Issue by SocolaDaiCa** [nWidart/laravel-modules#1210]
I see MakeCommand of "laravel-modules" is not same with MakeCommand of Laravel. I create new command package base on MakeCommand of Laravel. I think someone need It.

https://github.com/SocolaDaiCa/Laravel-Modules-Command

**Comment by maxcelos** [comment]
Nice initiative. It can be useful for someone.

Just like to recommend move it to "Discussions". It's not an issue.

**Comment by SocolaDaiCa** [comment]
@maxcelos Ok, done
