### ISSUE TITLE
Generate Multiple Controllers

### ISSUE THREAD

**Issue by nasirkhan** [nWidart/laravel-modules#1212]
I need to generate two controllers for one single module. The namespace will be different for the controllers. I also need to change the Class name and other values. how can i do that ?

**Comment by SocolaDaiCa** [comment]
why 2 controller in same module has differrence namespace?
Please demo

**Comment by nasirkhan** [comment]
I want to use two controllers for backend and frontend functionalities separately. 

I also want to use the Controller names as plural.

**Comment by SocolaDaiCa** [comment]
```bash
php artisan module:make-controller Backend/PostsController Blog
php artisan module:make-controller Frontend/PostsController Blog
```

You mean like this, don't you?

**Comment by nasirkhan** [comment]
actually no. I know I can create these by using separate commands. But I
want the following command to create both files.

`php artisan module:make Blog`

**Comment by SocolaDaiCa** [comment]
It is not normal case, I think you need create a command, It call 2 command make controller, 1 for backend, 1 for frontend
