### ISSUE TITLE
I have an issue similar to this. When working with about 10 - 15 modules, everything loads quite fast. But with about 30+ modules, it becomes terribly slow. I am working on a project that has about 100+ modules and the load speed is unbearable. I think performance degrades significantly with increasing number of modules.

### ISSUE THREAD

**Issue by Devsotf** [nWidart/laravel-modules#1213]
I have an issue similar to this. When working with about 10 - 15 modules, everything loads quite fast. But with about 30+ modules, it becomes terribly slow. I am working on a project that has about 100+ modules and the load speed is unbearable. I think performance degrades significantly with increasing number of modules.

_Originally posted by @Alyka in https://github.com/nWidart/laravel-modules/issues/971#issuecomment-702784733_

**Comment by SocolaDaiCa** [comment]
because cache is off, You can config modules
```php
    'cache' => [
        'enabled' => false, // it should be true
        'key' => 'laravel-modules',
        'lifetime' => 60, // config cache time you want
    ],
```

**Comment by MrJmpl3** [comment]
@SocolaDaiCa Why exists the cache in this package? In other word, what function of this package need the cache?

**Comment by Alyka** [comment]
> because cache is off, You can config modules
> 
> ```
>     'cache' => [
>         'enabled' => false, // it should be true
>         'key' => 'laravel-modules',
>         'lifetime' => 60, // config cache time you want
>     ],
> ```

I turn on caching and ran `php artisan optimize` still the same.

**Comment by SocolaDaiCa** [comment]
@MrJmpl3 every time web load, laravel-modules will scan all module to get module.json of all module, cache help it only scan per 60 minutes *(if cache.lifetime equal 60)

**Comment by SocolaDaiCa** [comment]
> I turn on caching and ran `php artisan optimize` still the same.

@Alyka maybe 60 minutes not enough for you, try increment lifetime
