### ISSUE TITLE
altering the table using this package command

### ISSUE THREAD

**Issue by makobongo** [nWidart/laravel-modules#1216]
Hello am trying to alter my table and run this command php artisan module:make-migration add_is_pending_to_finance_payments_cash finance --table='finance_payments_cash';
but am getting an error The "--table" option does not exist.  So my question is how can alter my table. thanks!
![table_altering_issue](https://user-images.githubusercontent.com/25367341/114850650-ac625b80-9de9-11eb-97c3-a840309b5c00.png)

**Comment by SocolaDaiCa** [comment]
You can try my package, It look like make:migration of laravel
https://packagist.org/packages/socoladaica/laravel-modules-command
