### ISSUE TITLE
Config data of the disabled module

### ISSUE THREAD

**Issue by safakocamanoglu** [nWidart/laravel-modules#1218]
Hello,
I have a plugins page where I list all modules. I keep data such as module name, description, author and version in config.php.
If the module is disabled, I cannot access the config data. I want to keep the information about the module in the json or config.php file. How can I access this in the most practical way.
Thank you for your suggestions

Sample configuration file:
```
<?php
return [
    'name'        => 'GoogleAnalytics',
    'description' => 'Google Analistik ile web sitenizdeki trafiği anlık olarak takip edin.',
    'author'      => 'Safa K.',
    'doc_url'     => null,
    'version'     => "1.2",

];
```

**Comment by SocolaDaiCa** [comment]
You can modify file module.json in per module,
```php
$module = Module::find('GoogleAnalytics');
$moduleInfo = $module->get();

echo $moduleInfo->doc_url
```

**Comment by safakocamanoglu** [comment]
Thank you so much. The result I needed was with this method. :)
