### ISSUE TITLE
How to link to assets in custom module?

### ISSUE THREAD

**Issue by hahyes** [nWidart/laravel-modules#1219]
Hi there,

first of all, really nice job are you doing here.
I'm trying to use css and js files in custom module only. Problem is, I can't find it by any location I'm typing. How I should link to these css files, assuming my path to them is `module_name/resources/assets/css` for example? Using custom namespace seems to not working or I'm doing it wrong way.

Cheers.

**Comment by SocolaDaiCa** [comment]
run 
```php
php  module:publish module_name
```
css will put in public/modules/module_name/css

and use
```php
{{ Module::asset('module_name:css/app.js') }}
```
in blade to access to css file

**Comment by hahyes** [comment]
> run
> 
> ```
> php  module:publish module_name
> ```
> 
> css will put in public/modules/module_name/css
> 
> and use
> 
> ```
> {{ Module::asset('module_name:css/app.js') }}
> ```
> 
> in blade to access to css file

This is too way, but I didn't want to modify public directory (I'm using custom modules in Invoice Ninja so I want to stay separated). 

You can achieve my goal by pasting content from files you want to use, like this:

```php
<style>
   {!! file_get_contents(Module::find('blog')->getPath() . '/Assets/blog.css'); !!}
</style>
```

**Comment by SocolaDaiCa** [comment]
@hahyes I think It have a performance problem.
I use laravel mix watch when dev and `php  module:publish module_name` in product. It better

**Comment by hahyes** [comment]
> @hahyes I think It have a performance problem.
> I use laravel mix watch when dev and `php module:publish module_name` in product. It better

As I said, laravel mix is not meeting with my goals. I'm adding module to someone project and I want to keep module only assets in module directory. When I will move module to another instance, I will have no problem with integration of module. I don't need to use Laravel Mix to making assets working. Performance problem will not occure with minified Bootstrap files anyway.

**Comment by SocolaDaiCa** [comment]
I see
