### ISSUE TITLE
Multiple Seeding Problem in Single Module

### ISSUE THREAD

**Issue by ercanertan** [nWidart/laravel-modules#122]
Hi,
I have Module call "MyModule" and I want to create another seed class next to default one.

After creating seed class with `module:make-seed MySecondSeed mymodule` ,
How to call MySecondSeed?

because following only call default seed class.
`module:seed mymodule`

Thanks

**Comment by armababy** [comment]
You would add another call to seeder in main seeder class `Database\Seeders\ModuleSeeder`.
`$this->call(MyOtherSeeder::class);`

**Comment by ercanertan** [comment]
Aww, 
I absolutely forgot that commented out line.

Thank you
