### ISSUE TITLE
How to include models in my controller

### ISSUE THREAD

**Issue by harshalone** [nWidart/laravel-modules#1220]
Hi I have created a controller and I want to use my model inside it.

I am trying to use it like this:

use Modules\User\Entities\User;

but it's throwing me an error

```
Error
Class "Modules\User\Entities\User" not found
http://127.0.0.1:8000/auth/test
```

**Comment by wikigods** [comment]
check if you added all files that require User model, then composer dump-autoload, I use laravel/ui or laravel breeze with Modules and it works fine after making those changes.

**Comment by harshalone** [comment]
I simply created a model inside my module user.
Why do I have to do a composer dump-autoload
Its a simple inclusion isn't it?

**Comment by harshalone** [comment]
This is how my model looks:
```

<?php

namespace Modules\User\Models;

use Illuminate\Database\Eloquent\Model; 

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'users';


    public function create(){

    }
}

```

**Comment by harshalone** [comment]
This is how my controller looks:
```

<?php

namespace Modules\Auth\Http\Controllers;
//use App\Models\User;
use Modules\User\Entities\User;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Socialite;
use Hash;
use Str;

class AuthController extends Controller
{

}
```

**Comment by wikigods** [comment]
i am using laravel/ui in this package 
<?php

namespace Modules\User\Entities;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Modules\Blog\Entities\Post;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

}

**Comment by wikigods** [comment]
because you extend to test model 
class User extends Authenticatable

**Comment by wikigods** [comment]
si te sigue dando error  edita config/auth.php
`'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => User::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],`
because composer dump-autoload is to update the changes properly

**Comment by o2b3k** [comment]
> This is how my controller looks:
> 
> ```
> 
> <?php
> 
> namespace Modules\Auth\Http\Controllers;
> //use App\Models\User;
> use Modules\User\Entities\User;
> use Illuminate\Contracts\Support\Renderable;
> use Illuminate\Http\Request;
> use Illuminate\Routing\Controller;
> use Socialite;
> use Hash;
> use Str;
> 
> class AuthController extends Controller
> {
> 
> }
> ```

Namespace is not correct.
change use Modules\User\Entities\User;
to use Modules\User\Models\User;

**Comment by harshalone** [comment]
@o2b3k you are wrong it is Entities

` use Modules\User\Entities\User;`

**Comment by wikigods** [comment]
good luck in your project

**Comment by Lezhni** [comment]
@harshalone can you please close this issue, if solution was finded?
