### ISSUE TITLE
Bugs In 8.12

### ISSUE THREAD

**Issue by thegr8dev** [nWidart/laravel-modules#1221]
Hello,

The bugs I noticed in version 8.2 of this package is 

1. I installed laravel 8.12 and this package version 8.2 and after set it up I created a new Module Faq but it does not generate Model file in Entities folder. (I did not modified any path in config/modules.php). I think previously it's generate  Model in Entities folder.

2. Now I modified **config/modules.php** according to my need and I disabled config, and assets to false for rest it's disable is working fine when creating a new Module but for these two still it's creating config and assets file under the Module/ModuleName folder even I disable it from config/modules.php

**Comment by SocolaDaiCa** [comment]
It is normal, It's not auto create FAQ model under Entities folder FAQ.

**Comment by thegr8dev** [comment]
> It is normal, It's not auto create FAQ model under Entities folder FAQ.

It's create I tested in one of my other project and it creates a model too.
