### ISSUE TITLE
Assets not working

### ISSUE THREAD

**Issue by thegr8dev** [nWidart/laravel-modules#1222]
Hello,

I Created a module and in module I created a folder call assets and put a logo.png in it and my module name is faq.

Now in my main laravel view ex. in welcome.blade.php I attach using <img src="{{  Module::asset('faq:logo.png')  }}"/>

but it's work 

even I run this command call php artisan module:publish but nothing happen ! 

Can any buddy help me where I am doing wrong ?

**Comment by SocolaDaiCa** [comment]
Did you enable your module?
Try `php artisan module:list`

**Comment by thegr8dev** [comment]
> Did you enable your module?
> Try `php artisan module:list`
> 
> `php artisan module:publish` only work with enable module

Yes Module is enable I can check status under module status.json file

**Comment by thegr8dev** [comment]
Hello
Actuallyy mistake i need to put img in resources folder then it will publish else it not publishing.

**Comment by SocolaDaiCa** [comment]
@ok, Please close issue
