### ISSUE TITLE
Set default string length on modules

### ISSUE THREAD

**Issue by matsn0w** [nWidart/laravel-modules#1226]
Hey there,

I was having an issue with my migrations: I'm getting
```
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```
This is quite a familiar issue. I fixed it by setting the default string length to 191 in my main app's AppServiceProvider like so:
```php
Schema::defaultStringLength(191);
```

This works like a charm, but it isn't picked up by the modules. When I run the migrations it still fails. I tried setting it in the module's ServiceProvider but that doesn't seem to work. 

Any ideas?

Thanks in advance!

**Comment by SocolaDaiCa** [comment]
@matsn0w Are you try put It in boot or register method? and enable that module?

**Comment by matsn0w** [comment]
Hi @SocolaDaiCa,

I've put it in the boot() method. The module is enabled. (In fact I have two modules, but that doesn't matter, tried it on both).
