### ISSUE TITLE
Error : 404 Not Found

### ISSUE THREAD

**Issue by AEK-BKF** [nWidart/laravel-modules#1227]
Hi,

After updating Laravel 8 to the latest version v8.42.0, I get this Error :
404 Not Found if I want to access to any module index page.

Thanks

**Comment by imzeeshan** [comment]
Same here.

**Comment by AEK-BKF** [comment]
Also : php artisan route:list doesn't show any modules routes

**Comment by imzeeshan** [comment]
@AEK-BKF Downgrading to 8.41.0 worked.

`"laravel/framework": "8.41.0"` 

Delete composer.lock and run composer install, worked for me.  Phew !!

**Comment by SocolaDaiCa** [comment]
Are you enable your module?
try `php artisan module:list`

**Comment by andrewbroberg** [comment]
Looks like this has been caused by the following MR

https://github.com/laravel/framework/pull/37392#issuecomment-843609250

**Comment by andrewbroberg** [comment]
There is an MR up to revert the change https://github.com/laravel/framework/pull/37405

**Comment by AEK-BKF** [comment]
The issue is fixed here [laravel#37405](https://github.com/laravel/framework/pull/37405)
Just update Laravel to 8.42.1

**Comment by shubham6988** [comment]
thanku so much solved my problem
