### ISSUE TITLE
Are there any module specific contitionals we can use. 

### ISSUE THREAD

**Issue by ap-coder** [nWidart/laravel-modules#1231]
I have module i have added to my project but i need to integrate it into the parent now. Are there any conditionals available for use such as any of the following:

- if module exists
- if exists and is published
- if module exists and has **

you can what i am getting at. 

I am also wondering if you have a way to specify the order seeders are run. 
example:

Main project seeders  have 

- permissions table seeder
- permissionsRole seeder

module project has 
- permissions seeder also. 

I need to be able to run both seeders before the permRole seeder so it has all available permissions before it tried to connect the  role to the permissions or the roles will not have module permissions assigned.

**Comment by wikigods** [comment]
Hello, my English is not very good,
if module exists
if exists and is published
if module exists and has **
1º You can use the helpers (" module_path('Blog') ") replace it with what module you are going to use.
Fun fact, to customize the helpers, first create helpers.php file in Main module and edit module.json. 
load the helpers.php file, then add in helpers.php file this code that says "custom_code".
Now you can use your custom helpers like this (" custom_code('Blog') "). 

![Screenshot_51](https://user-images.githubusercontent.com/71094046/119249347-72f5dc00-bb5d-11eb-96c8-1e04416ebd71.png)

![Screenshot_52](https://user-images.githubusercontent.com/71094046/119249359-7d17da80-bb5d-11eb-948b-f16101882411.png)

 Main project seeders have

2º There are several ways to do it the simplest is to add it in DatabaseSeeder and put it in order that you like, detail is not necessary that it is PermissionDatabaseSeeder you can simply use it like this PermissionTableSeeder, I hope this helps you.

![Screenshot_53](https://user-images.githubusercontent.com/71094046/119249361-86a14280-bb5d-11eb-8dca-05d8e8264666.png)


if you have any problem don't hesitate to contact me, sorry my english is not very good, good luck in your project.
