### ISSUE TITLE
Module Core User Management Roles and Permissions

### ISSUE THREAD

**Issue by Kodok-Jr** [nWidart/laravel-modules#1237]
is there a module package for user roles and permissions management,

**Comment by wikigods** [comment]
You don't have to create them, but it is easy to do it
you can use any of these 2 packages
composer require spatie/laravel-permission
work with laravel's authentication packages or you can make your own
o 
composer require cartalyst/sentinel requires login and register if you don't know how it works you can guide you from asgard
https://github.com/AsgardCms/Platform/tree/master/Modules/User, keep in mind that you can use it as a reference, don't copy and paste (not recommended).

Good luck in your project
