### ISSUE TITLE
SaaS

### ISSUE THREAD

**Issue by zoxed** [nWidart/laravel-modules#1238]
### **features like multi-tenant are they still not featured in your project ?** 

Hello, I am planning on creating the SaaS system to offer software that the company developed (e-commerce).

first of all I'm not planning on using the packages that are available but i want to do it manually.

this project is mainly using your package as the architecture..i don't know how to achieve what I'm asked to do 

I want to create subscription module to allow tenants to create their own sub-domain

This is the sticking point.....

I want my users to be able to also manage their own members.

So top level my saas service I would subscribe customers to use my software, They become a member and generate their own sub-domains

I hope this makes sense and please feel free to ask me to explain further if needed. (new in Laravel)

**Comment by zoxed** [comment]
if there is any example of a modular application which are presenting a SAAS feature, so i could have a small vision about it

**Comment by wikigods** [comment]
Good first you should make a system of roles and permissions and limit action inside and outside the web, then use a package that allows to support several sites at once or do it yourself, then make 3 modules, one where all clients are, then one Base (System), and another Shared, with different User Models, then all the logic that is required.
You can use this package https://github.com/tenancy/multi-tenant. Sorry my English is not very good :(, good luck in your project.
