### ISSUE TITLE
laravel php  visual studio code 

### ISSUE THREAD

**Issue by praveen381** [nWidart/laravel-modules#1239]
![Capture](https://user-images.githubusercontent.com/85359092/120827879-894a6180-c579-11eb-97de-55c5fa494d49.PNG)

application.php line 735:
class "Laravel\ui\uiserviceprovider"not found 

anyone know how to fix.

**Comment by wikigods** [comment]
What version of laravel are you using.
You are using the package composer require laravel/ui

**Comment by moforsharon** [comment]
> ![Capture](https://user-images.githubusercontent.com/85359092/120827879-894a6180-c579-11eb-97de-55c5fa494d49.PNG)
> 
> application.php line 735: class "Laravel\ui\uiserviceprovider"not found
> 
> anyone know how to fix.

Did you finally resolve the issue? i just ran into the same problem

**Comment by oumayma1112** [comment]
> > ![Capture](https://user-images.githubusercontent.com/85359092/120827879-894a6180-c579-11eb-97de-55c5fa494d49.PNG)
> > application.php line 735: class "Laravel\ui\uiserviceprovider"not found
> > anyone know how to fix.
> 
> Did you finally resolve the issue? i just ran into the same problem

did you resolved it ?
