### ISSUE TITLE
Message Translation

### ISSUE THREAD

**Issue by ruverd** [nWidart/laravel-modules#124]
How can I get the message for validation on path resources/lang/myLang?
The only way that I could make works was creating a method message in my Request file but I don't want make that in each module.
Could you help me?

**Comment by nWidart** [comment]
Hello you can use the following:

```
trans('yourmodule::file.key')
```

**Comment by mikemand** [comment]
@nWidart That should be `@lang()` instead of `@trans()`. (I made the same mistake the other day too. D:)
