### ISSUE TITLE
How to use config ?

### ISSUE THREAD

**Issue by weileong17** [nWidart/laravel-modules#1244]
Modules/ProviderGameList/Config/config.php
```
<?php

return [
    'name' => 'ProviderGameList',
];

```

I've tried
```
Config::get('module::key')
Config::get('ProviderGameList::name')
```

it does not work.

**Comment by wikigods** [comment]
you have to use Name of the created module in lowercase, in my case User = user
![Screenshot_113](https://user-images.githubusercontent.com/71094046/122047884-4329a500-cda6-11eb-8f35-9844234135e8.png)
![Screenshot_114](https://user-images.githubusercontent.com/71094046/122047888-43c23b80-cda6-11eb-9f51-6308e0a5bf07.png)

**Comment by weileong17** [comment]
@wikigods It works! Thanks you!
