### ISSUE TITLE
Error with the routes ( apiResource and Resource ) of laravel 8

### ISSUE THREAD

**Issue by Rasool-deldar** [nWidart/laravel-modules#1245]
Hi, I noticed that the package has a problem. When I want to use the new method of root (Laravel 8), it has a problem with apiResource and resource and gives the following error (the path of the file controller repeats twice). Please fix this problem.

![image](https://user-images.githubusercontent.com/58503211/122161757-83ad1f80-ce87-11eb-934a-8ab37262ce87.png)

![image](https://user-images.githubusercontent.com/58503211/122161826-a6d7cf00-ce87-11eb-8d47-f4c492f1aefe.png)

**Comment by wikigods** [comment]
A workaround would be to comment out a few lines in your RouteServiceProvider for each Module.
![Screenshot_116](https://user-images.githubusercontent.com/71094046/122179058-c8679500-ce4c-11eb-910a-34062a072f78.png)
![Screenshot_117](https://user-images.githubusercontent.com/71094046/122179063-c9002b80-ce4c-11eb-9d46-c123cebda510.png)
![Screenshot_118](https://user-images.githubusercontent.com/71094046/122179064-c9002b80-ce4c-11eb-9565-66da9336f553.png)

**Comment by Rasool-deldar** [comment]
Thank you very much for your help.
