### ISSUE TITLE
Register Middleware

### ISSUE THREAD

**Issue by Rasool-deldar** [nWidart/laravel-modules#1246]
Hi, I made a middleware. Now how do I register a middleware in the module and use it?

**Comment by wikigods** [comment]
Good first create a Module or if you already have add this, let's make 2 examples:
The First Mode
php artisan module:make Example 

Then open ExampleServiceProvider and add

![Screenshot_120](https://user-images.githubusercontent.com/71094046/122480912-61a0c380-cf93-11eb-9c57-3be2a745b85d.png)

![Screenshot_121](https://user-images.githubusercontent.com/71094046/122480947-741afd00-cf93-11eb-9421-3e9fd867aaff.png)



The second mode is more professional


we repeat the first step,
![Screenshot_120](https://user-images.githubusercontent.com/71094046/122480912-61a0c380-cf93-11eb-9c57-3be2a745b85d.png)

then in boot we add "$this->registerMiddleware();",
![Screenshot_122](https://user-images.githubusercontent.com/71094046/122481062-a2004180-cf93-11eb-9e7f-13e43827116c.png)

finally at the end we add private "private function registerMiddleware()".

![Screenshot_123](https://user-images.githubusercontent.com/71094046/122481072-a9bfe600-cf93-11eb-947d-958915c42983.png)
