### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by klaravel** [nWidart/laravel-modules#125]
Can you please add support 5.4 laravel?

also one more thing I found that there no use for "laravelcollective/html": "5.1.*|5.2.*|5.3.*" or I am not sure if there is require to use this module.

**Comment by nWidart** [comment]
Hello,

5.4 support will be added soon.

**Comment by parweb** [comment]
Nice

**Comment by nWidart** [comment]
This is now on master branch.

**Comment by dieterdd** [comment]
If I composer require nwidart / laravel-modules execution comes the error

Problem 1

    Installation request for nwidart/laravel-modules ^1.15 -> satisfiable by nwidart/laravel-modules[1.15.0].
    nwidart/laravel-modules 1.15.0 requires laravel/framework 5.1.|5.2.|5.3.* -> satisfiable by laravel/framework[5.1.x-dev, 5.2.41, 5.2.x-dev, 5.3.x-dev, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.20
    v5.1.21, v5.1.22, v5.1.23, v5.1.24, v5.1.25, v5.1.26, v5.1.27, v5.1.28, v5.1.29, v5.1.3, v5.1.30, v5.1.31, v5.1.32, v5.1.33, v5.1.34, v5.1.35, v5.1.36, v5.1.37, v5.1.38, v5.1.39, v5.1.4, v5.1.40, v5.1.41, v5.1.42, v5.1.43, v5.1.44, v5.1.45, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.
    v5.2.0, v5.2.0-beta1, v5.2.1, v5.2.10, v5.2.11, v5.2.12, v5.2.13, v5.2.14, v5.2.15, v5.2.16, v5.2.17, v5.2.18, v5.2.19, v5.2.2, v5.2.20, v5.2.21, v5.2.22, v5.2.23, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.29, v5.2.3, v5.2.30, v5.2.31, v5.2.32, v5.2.33, v5.2.34, v5.2.3
    v5.2.36, v5.2.37, v5.2.38, v5.2.39, v5.2.4, v5.2.40, v5.2.42, v5.2.43, v5.2.44, v5.2.45, v5.2.5, v5.2.6, v5.2.7, v5.2.8, v5.2.9, v5.3.0, v5.3.0-RC1, v5.3.1, v5.3.10, v5.3.11, v5.3.12, v5.3.13, v5.3.14, v5.3.15, v5.3.16, v5.3.17, v5.3.18, v5.3.19, v5.3.2, v5.3.20, v5.3.21, v5.3
    2, v5.3.23, v5.3.24, v5.3.25, v5.3.26, v5.3.27, v5.3.28, v5.3.29, v5.3.3, v5.3.4, v5.3.5, v5.3.6, v5.3.7, v5.3.8, v5.3.9] but these conflict with your requirements or minimum-stability.

Have already used the Branch: Master with nWidart Preparing 1.16.0
With the new composer.json file

I have Laravel 5.4 in use and work with Homestead and PHP 7.1.x


You write great code, congratulations
best regards
Dieter

**Comment by laracoder** [comment]
Until Version 1.16 of laravel-modules is released just get the package by entering 
` composer require nwidart/laravel-modules dev-master`

**Comment by dieterdd** [comment]
Laracoder, now it goes, many thanks for the help. Also thanks again to nWidart for his great software

**Comment by sebastiaanluca** [comment]
Thanks for the update! Using this in all my projects, so eagerly anticipating the release for Laravel 5.4 :+1:

**Comment by nWidart** [comment]
I just tagged it as [1.16.0](https://github.com/nWidart/laravel-modules/releases/tag/1.16.0) 🎉

**Comment by Dsantacruz** [comment]
it can be used laravel 5.4??
