### ISSUE TITLE
Request the adding of a command of migration between spatie/multi-tenancy and your package 

### ISSUE THREAD

**Issue by zoxed** [nWidart/laravel-modules#1250]
i wanna be able to migrate all the tables that i have in my modules in each tenant that is gonna be created, i'm kinda stuck here so if anyone has an idea please feel free to answer, thank you

asking for @wikigods @nWidart

**Comment by wikigods** [comment]
I don't know if this is what you are looking for, php artisan module:migrate

**Comment by zoxed** [comment]
either way thanks i have been able to add a custom command on my own 
I'm gonna close this issue

**Comment by abbasmashaddy72** [comment]
Hi @zoxed Can you Let me know how did you implemented it in tenancy package and is it working fine
