### ISSUE TITLE
How to enable/disable module by user config ? 

### ISSUE THREAD

**Issue by zmap95** [nWidart/laravel-modules#1251]
Each module is a feature so how I can enable/disable which modules user can access ? 
Thank you !

**Comment by SocolaDaiCa** [comment]
You can use: 

## module:enable
Enable the given module.

```bash
php artisan module:enable Blog
```

## module:disable
Disable the given module.
```bash
php artisan module:disable Blog
```

https://nwidart.com/laravel-modules/v6/advanced-tools/artisan-commands

**Comment by wikigods** [comment]
There are several ways you can implement roles and permissions or use access policies.

You can make your own roles and permissions, you can use packages that facilitate the work such as 
spatie/laravel-permission or cartalyst/sentinel or the one of your choice and last but not least would be to use access policies.

 asgard in a good reference project 

https://github.com/AsgardCms/Platform
