### ISSUE TITLE
plugin architecture

### ISSUE THREAD

**Issue by Ayman-Nageeb** [nWidart/laravel-modules#1253]
Hello, I need help

I am planning to build an extensible system (via plugins) using laravel 

it for my project in the university ( I am a student ) 

the issue is that i don't know how to implement a plugins architecture in laravel

but you did it

i need to know how

so please give me any guide to start with

**Comment by maxcelos** [comment]
The start point is Domain Driven Design pattern.
https://en.wikipedia.org/wiki/Domain-driven_design
https://www.amazon.com.br/Domain-Driven-Design-Tackling-Complexity-Software-ebook/dp/B00794TAUG

Then check out the Package Development doc in Laravel docs.
https://laravel.com/docs/8.x/packages

Don't forget to read about how Composer works.
https://getcomposer.org/doc/

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
