### ISSUE TITLE
Explicit and implicit binding in routes, I get an empty array instead of a model.

### ISSUE THREAD

**Issue by ShevtsovTN** [nWidart/laravel-modules#1266]
Good Day.
The "show" method in my controller:
`
    public function show(OrderRefund $refund): OrderRefundResource
    {
        dd($refund);
        ...
    }
`
Code from RouteServiceProvider:
`
...
Route::as('.order.refund')->group(function() {
    ...
    Route::get('api/v2/order/refund/{refund}', [OrderRefundController::class, 'show'])->name('.show');
});
...
`
As a result, the model passed to the method is empty.
If you pass "int $ id" to the method, then the number is passed correctly.

**Comment by charindu77** [comment]
this is happening again and I'm using v10
