### ISSUE TITLE
Dont work Laravel New Routes

### ISSUE THREAD

**Issue by juniorsantos** [nWidart/laravel-modules#1271]
Do Not work Laravel New Routes!

```
use Modules\Foo\Http\Controllers\FooController;
Route::resource('/', FooController::class); 
```

**Comment by maxcelos** [comment]
I guess you should use only the controller name, not entire class ("FooController::class"), because the namespace is defined in your modules "RouteServiceProvider".

Check the namespace with `artisan route:list` command. It possible is duplicating the class namespace
