### ISSUE TITLE
Project Status and Development (Issues and Pull request Becoming Stale)

### ISSUE THREAD

**Issue by alphaolomi** [nWidart/laravel-modules#1272]
Hello @nWidart 

Great work with the project, Thank you for your time and effort

At the moment issues and pull request are not worked and thus coming stale and the stale bot closes

I have see some genuine issue with no response until the get closed by the stale bot

Am looking forward on using this package on an upcoming project, ATM i can't support financially but am willing to devote some time development and code reviews.

Thanks

**Comment by maxcelos** [comment]
I agree that there some lack of attention to issues and PR's, but I see almost all issues opened are not really related to this package but misunderstand of Laravel architecture.

I'm using it in production over one year, including exported packages in Packagist, and had none of issues reported.
