### ISSUE TITLE
Migration Status of modules doesn't show up in migrate:status

### ISSUE THREAD

**Issue by Gkiokan** [nWidart/laravel-modules#128]
Hey folks,

while I am developing each module I'd like to see the migration status of each module seperatly. But they doesn't even show up in the default migration:status command without publishing it.
This makes handling the migration hard if you need to rollback and migrate again and have a couple modules to have all in mind. 
 
 
Is this the way it should work or is there an easy way to show all of the migration in one place?
Sofar the migration Table in the DB have all records, but only the avaible migration files in the default /database/migrations folder are shown up.

**Comment by nWidart** [comment]
Hello,

This is not possible currently. However it sounds like a nice feature and would accept a PR to show statuses for each module /  or all.

**Comment by marcelogarbin** [comment]
Any updates on migrate:status?

**Comment by nWidart** [comment]
No.

**Comment by Gkiokan** [comment]
If someone would like to start this I'd like to mention that we can just look for the way how laravel is doing the Migration Table on the cmd, so we can find the error or even build a seperate command like php artisan module:migration

If you follow the orginal Command along you will find this method for getting 
the Migration paths. 
 https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Console/Migrations/BaseCommand.php#L14

I belive this is the missing part where Module Migrations wouldn't been found and they will not display as a result. As you can look up here
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Console/Migrations/StatusCommand.php#L90

**Comment by nWidart** [comment]
Interesting. Furthermore, this is the Migrator class used on this package for migrating modules. https://github.com/nWidart/laravel-modules/blob/master/src/Migrations/Migrator.php

**Comment by Gkiokan** [comment]
@nWidart I've got it working with a hacky solution for now. (static array merge).
Next step would be to get Module::paths() (??) and then loop though all modules.

Here my Example hacky code on the BaseCommand:

```php
    protected function getMigrationPaths()
     {
        if ($this->input->hasOption('path') && $this->option('path')) {
            return collect($this->option('path'))->map(function ($path) {
                return $this->laravel->basePath().'/'.$path;
            })->all();
        }

       // Magic is a example Module created with php artisan module:make Magic
        $modules = [
            $this->laravel->basePath() . '/Modules/Magic/Database/Migrations'
        ];

        return array_merge(
            [$this->getMigrationPath()], $this->migrator->paths(), $modules
        );
    }```

Here is an Screenshot of each array testing itself and within merged
![php artisan migrate-status forced with module paths](https://user-images.githubusercontent.com/7249224/27051488-9add7c26-4fb6-11e7-935d-bba9ea993d1d.png)

**Comment by nWidart** [comment]
Hello,

Very late reply here, but this sounds interesting.
I'd be happy to accept a PR with the migrate-status command.
