### ISSUE TITLE
Class 'Modules\Blog\Providers\BlogServiceProvider' not found

### ISSUE THREAD

**Issue by arif98741** [nWidart/laravel-modules#1283]
Every time I create a new module I get error that Provider is not found
![435325 ](https://user-images.githubusercontent.com/17213478/134113487-0ae6215a-2042-490f-bd49-b3738dd7999c.png)
nd
![43543](https://user-images.githubusercontent.com/17213478/134113784-69e66840-2301-418d-ad2d-e62e0751c45b.png)

**Comment by maxcelos** [comment]
Run `composer dumpautoload`

**Comment by arif98741** [comment]
> 

what is your laravel version?

**Comment by abanghendri** [comment]
I use laravel 8

**Comment by joshuacadman01** [comment]
I had this issue and it was due to me not adding the below code in the composer.json file.
`{
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Modules\\": "Modules/",
      "Database\\Factories\\": "database/factories/",
      "Database\\Seeders\\": "database/seeders/"
    }
  }
}`.

After running `composer dump-autoload`, the issue went away.

**Comment by hqms** [comment]
I'm using Laravel 12, and try implement this. Basically the generated module skeleton is not comply with the PSR-4 standart, so after I've moved some of the directory the dump-autoload just working fine, here's my current module directory structure 

`modules
└── Blog
    ├── App
    ├── Database
    │   ├── Seeders
    │   │   ├── .gitkeep
    │   │   └── BlogDatabaseSeeder.php
    │   ├── factories
    │   │   └── .gitkeep
    │   └── migrations
    │       └── .gitkeep
    ├── Http
    │   └── Controllers
    │       ├── .gitkeep
    │       └── BlogController.php
    ├── Providers
    │   ├── .gitkeep
    │   ├── BlogServiceProvider.php
    │   ├── EventServiceProvider.php
    │   └── RouteServiceProvider.php
    ├── composer.json
    ├── config
    │   ├── .gitkeep
    │   └── config.php
    ├── module.json
    ├── package.json
    ├── resources
    │   ├── assets
    │   │   ├── .gitkeep
    │   │   ├── js
    │   │   │   └── app.js
    │   │   └── sass
    │   │       └── app.scss
    │   └── views
    │       ├── .gitkeep
    │       ├── index.blade.php
    │       └── layouts
    │           └── master.blade.php
    ├── routes
    │   ├── .gitkeep
    │   ├── api.php
    │   └── web.php
    ├── tests
    │   ├── Feature
    │   │   └── .gitkeep
    │   └── Unit
    │       └── .gitkeep
    └── vite.config.js`

**Comment by tahsin352** [comment]
Move `Providers` folder out of `App` folder into your modules.
