### ISSUE TITLE
Enhancement: Module Manager Interface

### ISSUE THREAD

**Issue by sarfraznawaz2005** [nWidart/laravel-modules#129]
It would be great if there is module manager GUI interface out of the box. I have created one from my understanding with its screenshots as well as code.

![mmc](https://cloud.githubusercontent.com/assets/201788/22262043/25271dda-e291-11e6-8881-7fb9ef803722.jpg)
![mm](https://cloud.githubusercontent.com/assets/201788/22262044/2530b4d0-e291-11e6-933a-5190af0386db.jpg)
![mmd](https://cloud.githubusercontent.com/assets/201788/22262045/2533100e-e291-11e6-8c62-3d96060d71eb.jpg)

The Crud.docx should be renamed to Crud.zip cause GH didn't allow me to upload zip file.

[Crud.docx](https://github.com/nWidart/laravel-modules/files/727694/Crud.docx)

**Comment by armababy** [comment]
Very sweet job, great to see handy ui stuff.
