### ISSUE TITLE
Npm install from root does not automatically install all modules

### ISSUE THREAD

**Issue by jstam89** [nWidart/laravel-modules#1295]
Is it possible to run npm install automatically trough all published modules?
We currently have 20+ modules and it takes way to long to run `npm install` and `npm run dev` in all modules.
Anyone having the same problem and is there a solution? I can't seem to fix this.

**Comment by AbdullahFaqeir** [comment]
I'll be working on a fix for this.

**Comment by amidesfahani** [comment]
any ideas for vite?
