### ISSUE TITLE
Very slow, Almost 1 minute per  route in module

### ISSUE THREAD

**Issue by eiko03** [nWidart/laravel-modules#1309]
everytime i hit this in the module it becomes very slow, take 1 min per route

**Comment by maxcelos** [comment]
This is obviously a problem on you infrastructure or implementation. 

No way this package still exist if was causing 1 minute response time by itself. Don't you think?

**Comment by dilipvaghasiya** [comment]
I have the same issue

> everytime i hit this in the module it becomes very slow, take 1 min per route

Can please help to resolve the issue, facing the same
