### ISSUE TITLE
migrate:rollback with --path    is not possible, there is no command for migrate:rollback with modules

### ISSUE THREAD

**Issue by dieterdd** [nWidart/laravel-modules#131]
Is there perhaps a guide how this works exactly. There is no command for modules
Best regards
Dieter

**Comment by Gkiokan** [comment]
If you want to rollback a migration from your module you can do this like this:
`php artisan module:migrate-rollback YourModuleName`

The one Problem with that is, you don't get a status list like on `php artisan module:status`.
I've quested that before, someone should implement that feature #128 .
