### ISSUE TITLE
View [layouts.main] not found.

### ISSUE THREAD

**Issue by fadilmalik** [nWidart/laravel-modules#1318]
I tried to take from the root view but an error appeared with 'View [layouts.main] not found.'

**Comment by maxcelos** [comment]
It is probably a cache issue. But create a public repository recreating the but so we can try to help.

**Comment by fadilmalik** [comment]
> It is probably a cache issue. But create a public repository recreating the but so we can try to help.

checkout my new repo name laravel-module

**Comment by maxcelos** [comment]
Layouts folders must be inside "views".

Do:
```
mv resources/layouts resources/views/layouts
```

After that you can use this in your login.blade.php for example like `@extends('layouts.main')`

**Comment by fadilmalik** [comment]
oh i see. thank u sir, it works
