### ISSUE TITLE
How to move the Modules folder under App?

### ISSUE THREAD

**Issue by perffy** [nWidart/laravel-modules#1323]
Hi guys,

I am using Laravel 8.49.2 version. My goal is to have all Modules under App folder.

Here it is how my composer.json looks like:

```
    "autoload": {
        "psr-4": {
            "App\\": "app/",
			"Modules\\": "app/Modules/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
```

and here is some part of the config/modules.php:

```
'namespace' => 'App\Modules',
'paths' => [
        'modules' => 'app/Modules',
        ....
]
```

By calling artisan it works fine, unfortunately, the routes and the views don't work. I have placed the route in the default web.php and then I can open the URL, but then it cannot find the view. It comes to the following error:

`No hint path defined for [publication].`

What I am doing wrong?

**Comment by luckyboy1001** [comment]
Maybe your problem is with service provider of module
add module service provider to the main list maybe it work!

**Comment by perffy** [comment]
> Maybe your problem is with service provider of module add module service provider to the main list maybe it work!

Do you mean to include my module service provider in the config/app.php? I did that, but then i got this error: "Call to a member function getPath() on null"

**Comment by luckyboy1001** [comment]
Maybe laravel can't find or load those classes
I suggest check your autoload and try to run 
`composer dump-autoload`
it is hard to figure out the problem without source code and more details!

**Comment by luckyboy1001** [comment]
Actually there is an easy way to do that just public configuration of the package(Laravel-modular) and 
in my case it is in line 73 
`modules' => base_path('Modules')`
as you can see this is the path you can edit and customize it.

**Comment by perffy** [comment]
Thank you @luckyboy1001 it was the base_path()

I dont know why i have removed it, but that was causing the problem :)
