### ISSUE TITLE
Migration script reference across modules, this might be a feature

### ISSUE THREAD

**Issue by Thavarajan** [nWidart/laravel-modules#1326]
`php artisan module:migrate `

it was run in alphabetical order, so some dependent tables created across moudles will not execute properly, and throw errors, how could we resolve this?

or is there any other way to denote that one migration script depends on some other modules migration script

**Comment by Thavarajan** [comment]
IMHO then the concept of migrations inside modules was not useful. any other alternatives

**Comment by dcblogdev** [comment]
have you tried setting the priority levels in module.json in each module?
