### ISSUE TITLE
Not able to edit the modules views (blade)

### ISSUE THREAD

**Issue by Hamza160** [nWidart/laravel-modules#1329]
Hi there!
       Mr. nWidart firstly i really appreciate your efforts which you have made for laravel and for us. i'm facing the problem i have developed a large scale application using laravel-modules but the issue is that suddenly the modules views becomes statics i can't change the views i have tried a lot of things but failed. please help me to solve this issues thanks.

**Comment by dcblogdev** [comment]
could be a caching issue have you tried clearing your cache?

you could try clearing the view cache

```
php artisan view:clear 
```

or to clear everything

```
php artisan optimize:clear
```

**Comment by Hamza160** [comment]
Yes i have tried everything but nor working
php artisan config:cache
php artisan cache:clear
php artisan view:clear
php artisan route:clear
php artisan optimize
