### ISSUE TITLE
Hardcoded replacements extend

### ISSUE THREAD

**Issue by webmake** [nWidart/laravel-modules#133]
Seems that only `module:make` command has dynamic [replacements](https://github.com/nWidart/laravel-modules/blob/master/src/Generators/ModuleGenerator.php#L344) from configs [option](https://github.com/nWidart/laravel-modules/blob/master/config/config.php#L37), other uses hardcoded values like [middleware](https://github.com/nWidart/laravel-modules/blob/master/src/Commands/GenerateMiddlewareCommand.php#L55).

Is there any possibility to add custom replacements such as copyright, etc?

**Comment by nWidart** [comment]
Sorry for late reply, feel free to send a PR.
