### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by dcblogdev** [nWidart/laravel-modules#1330]
Hi @nWidart,

Could you do a new release, there's a merged PR that puts back in the make-component commands it's in master but not in the 8.2 release.

This was added in the PR Command "module:make-component" is not defined #1190

**Comment by dcblogdev** [comment]
Would be nice if issues were responded to.

**Comment by dcblogdev** [comment]
....

**Comment by EdgarSedov** [comment]
@nWidart Hey man are you alive or should we consider this repo as stale? Im looking for modules package for my new project, should i really choose this one or you plan to abandon its support?

**Comment by dcblogdev** [comment]
I find this package very stable, @nWidart does releases for each major release of Laravel, I've no reason to think this won't be the case again.

I do which the auto closing of issues was turned off tho it currently looks like issues are getting resolved but often that's not the case.

**Comment by dcblogdev** [comment]
@EdgarSedov I'm now helping Nicolas to support this package, feel free to raise any issues. 👍

I'll be creating a new release over the weekend as per the original message above.

**Comment by dcblogdev** [comment]
I've just released 8.3
