### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by GekkeGlenn-Dev** [nWidart/laravel-modules#1333]
Hay Contributers, I love your modules, but i missing documentation for the modules version 8. I only see the documentatino for the version v6 or lower, Where can i find the documentation for v7 and v8? Or is v8 almost simular as v6?

**Comment by dcblogdev** [comment]
There are no docs for 7 or 8 that I can find, I've written the docs for v8 as part of a book I'm releasing soon https://modularlaravel.com/

The docs for v6 should be fine for your needs, it covers most apects.

**Comment by arnonm** [comment]
At the very least update the docs to reflect that it works and has been tested with Laravel v8

**Comment by dcblogdev** [comment]
Thanks for raising this the docs will be worked on shortly, I can confirm it works perfectly with Laravel 8 and PHP 8.1 I'm running this version myself.

**Comment by dcblogdev** [comment]
I'm in the process of updating the docs now for v8 and v9.

**Comment by dcblogdev** [comment]
I've released the docs on a new domain https://docs.laravelmodules.com/

I will continue to update v8 and v9 docs.

**Comment by bradsi** [comment]
@dcblogdev The About section of this repo still has a link to the old documentation, please can you update it? I had no idea about docs for > v6 until reading your book just now and looking through closed issues
