### ISSUE TITLE
How to use @lang in modules?

### ISSUE THREAD

**Issue by lucasantoniooficial** [nWidart/laravel-modules#1334]
I have all the translations inside resources/lang but when I use @lang('Text') it doesn't understand the translation inside the modules.

**Comment by dcblogdev** [comment]
In order to load the translations you need to provide the module prefix then the local path ie:

```php
{{ __('contacts::messages.hello') }}
```
This relates to a module called Contacts with a file messages.php and a key of hello the file contains:

```php
<?php
return [
    'hello' => 'Hello English'
];
```
