### ISSUE TITLE
Custom blade components within modules directory

### ISSUE THREAD

**Issue by svenhaack** [nWidart/laravel-modules#1337]
I'm using Laravel Modules in in most of my projects nowadays. In order to avoid duplicate codes I've added some reusable custom blade components, e.g. an admin section as an example:

/resources/views/components/admin.admin-section.blade.php:
![grafik](https://user-images.githubusercontent.com/97032150/147931842-a7172fc1-b9e5-49f1-97e6-e8e2fa0a1a9f.png)

Called within a blade template as follows:
![grafik](https://user-images.githubusercontent.com/97032150/147931957-eff3f651-bf5a-483f-b70f-bf89bd703e2e.png)

Now I would love to move the admin blade components to Modules/Admin/Resources/views/components, because logically they belong to the admin module and I would like to have them there too.

Unfortunately this doesn't seem to work, is there anyone who has had this problem and can help with a solution?

Regards,
Sven

**Comment by walirazzaq** [comment]
Haven't used this package yet as I am planning to use it and from docs what I got, I think you can register `namespaced` blade components. From the docs of this package, it says when we create a new module it registers namespaces as well and from laravel docs, we can register components like so 
```php
   Blade::componentNamespace('Modules\\Admin\\Views\\Components', 'admin');
```

[Blade Components](https://laravel.com/docs/8.x/blade#manually-registering-components)

You might have to move from anonymous components to class components as well and from the `render` method of the component class, you will return `view('admin::path-to-view')`
As I said I haven't tried it myself and I am yet going through the docs, Do post the update as well
Thanks

**Comment by dcblogdev** [comment]
All you need to do is reference the module as a prefix <x-Module:: for example:

```php
<x-app::auth-card>
```

This loads from an `App` module.

the file is located at `Modules\App\Resources\views\components\auth-card.blade.php`

If you're using PHPStorm then I highly recommend getting https://laravel-idea.com/ provides auto-completion that's compatible with this package.

**Comment by sfaessler** [comment]
AWESOME! + 10000 points, exactly what I've been looking for! Thank you very much!
