### ISSUE TITLE
Issue in Laravel 5.4

### ISSUE THREAD

**Issue by eullercristian** [nWidart/laravel-modules#134]
Dears, 

I installed the package and created the module Site. When i did run the project i have the error:

FatalErrorException in Application.php line 606:
Class 'Modules\Site\Providers\SiteServiceProvider' not found

Can you help me?

Thanks

**Comment by brecky** [comment]
I have this problem
Laravel 5.4.9

**Comment by hufeng903** [comment]
i face the same question .  i run composer dump-autoload.  nothing changed ? my laravel version is 5.2

**Comment by nWidart** [comment]
This isn't related to laravel 5.4. There are numerous other issues about this. Please make sure your classes are autoloaded correctly.

**Comment by longvireak** [comment]
i face this problem too

**Comment by gmox** [comment]
Did you make sure to add `"Modules\\": "modules/",` to your PSR-4 autoloading?

**Comment by longvireak** [comment]
@gmox yes , but not working.

**Comment by longvireak** [comment]
after installation. 
use composer update . everything will be ok :)

**Comment by hufeng903** [comment]
i run composer update . error:
[Symfony\Component\Debug\Exception\FatalErrorException]
Class 'Modules\Api\Providers\ApiServiceProvider' not found

why? not the same resaon?

**Comment by hufeng903** [comment]
after installation. i use php artisan module:make api .
this is composer.json in api
{
    "name": "nwidart/api",
    "description": "",
    "authors": [
        {
            "name": "Nicolas Widart",
            "email": "n.widart@gmail.com"
        }
    ],
    "autoload": {
        "psr-4": {
            "Modules\\Api\\": ""
        }
    }
}

**Comment by longvireak** [comment]
@hufeng903  follow this-> https://nwidart.com/laravel-modules/v1/installation-and-setup

*note add "Modules\\": "Modules/" to autoload psr-4 in composer.json.

then run command composer update :)

**Comment by hufeng903** [comment]
@longvireak modify the composer.json like you say .  but nothing changed.  
i want to know how to test this class are autoloaded correctly?

**Comment by longvireak** [comment]
@hufeng903  did u follow the installation guide.

**Comment by hufeng903** [comment]
i am not sure this compose.json is right.  my composer.json is like 
{
    "name": "nwidart/api",
    "description": "",
    "authors": [
        {
            "name": "Nicolas Widart",
            "email": "n.widart@gmail.com"
        }
    ],
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Modules\\": "Modules/",
            "Modules\\Api\\": ""
        }
    }
}

**Comment by longvireak** [comment]
@hufeng903  not that composer.json on your module.  composer.json on your project 


 "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "nwidart/laravel-modules": "^1.16",
    },   
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/",
            "Modules\\": "Modules/"
        }
    },

**Comment by hufeng903** [comment]
@longvireak   i see . thank you !
