### ISSUE TITLE
Using with Jetstream

### ISSUE THREAD

**Issue by homeoftheunits** [nWidart/laravel-modules#1343]
Hi guys,

i have to questions, maybe there is an solution :)

First, is it possible to use modules with Jetstream and inertia? For Example, in my Jetstream App i want to use the cart module. Know the website shows me an cart icon and the Vue Pages are included in my Vue App.

And the second question is, can i make some dependency between modules? For Example, when i use the cart module, i must use the product module too

Cheers
Ralf

**Comment by garbinmarcelo** [comment]
Hi @homeoftheunits (sorry to answer this so late), have you progressed your project with Laravel Modules and Jetstream? I also have doubts about the use of these 2 packages together.

**Comment by homeoftheunits** [comment]
Hi @garbinmarcelo, we don't use Laravel Modules, because we didn't found an solution
