### ISSUE TITLE
lack of {module}ServiceProvider in config file.

### ISSUE THREAD

**Issue by OoBook** [nWidart/laravel-modules#1346]
After created a module, any command related to module not working. however you removed creating of Providers/{module}ServiceProvider.php class from your config.php file. If you look your last commit, will see 'stubs.files.provider' key removed. Hence, service provider of module not created, I can fix this error, but I can guess that problem will give more errors if I move on.

that's why it's occuring following issue:
at vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:208
    204▕      * @return \Illuminate\Support\ServiceProvider
    205▕      */
    206▕     public function createProvider($provider)
    207▕     {
  ➜ 208▕         return new $provider($this->app);
    209▕     }
    210▕ }

**Comment by dcblogdev** [comment]
I'm having trouble replicating this, on a fresh install generating new modules works fine for me. The service providers are being generated. Are you still having this problem? have you checked your on the latest version?
