### ISSUE TITLE
could the documentation elaborate on how to publish modules?

### ISSUE THREAD

**Issue by Fredericld** [nWidart/laravel-modules#1349]
Hi,

Can someone help me understand how to publish to GIT a nWidart module

I have followed the first basic steps https://nwidart.com/laravel-modules/v6/advanced-tools/publishing-modules

1- I created a module

2- I set the type of the module to "laravel-module" in composer.json

3- I am not sure what to do in this step. So far, I have a laravel application already connected to GIT repository. Now, how do I push the new module to its own repo? I have already created a blank repo in my GITHub account. I just need to know how to push the module to it.

**Comment by dcblogdev** [comment]
You will need to extract the module into its own git repo the easiest way to do this is to move the module into its own folder on your machine and then set up a new git repo for that module, from there you can push up your code to GitHub.

**Comment by Fredericld** [comment]
Assuming I have a module in my GIT reposotory, how do I import the module into the project?
If I do 
```
composer require "mymodule"
```
It is going to be installed in the vendor folder, and not in the "Modules" folder. 
I am a confused with this.

**Comment by dcblogdev** [comment]
you need another package installed:

```
composer require joshbrw/laravel-module-installer
```

This will move the module files automatically into the Modules folder. If you need to install the modules other than the Modules directory then add the following in your module composer.json.

```
"extra": {
    "module-dir": "Custom"
}
```
