### ISSUE TITLE
Vendor Scan

### ISSUE THREAD

**Issue by rehavvk** [nWidart/laravel-modules#135]
Hey,

i tried to put one of my modules into the vendor folder and set `scan.vendor.enabled` to true.

But if i run `php artisan module:list` the module couldn't be found.

Please help me. :)

**Comment by re-hawk** [comment]
Sure, the output is the normal module table without any module loaded. :/

**Comment by rehavvk** [comment]
NVM I solved it myself. Nor error occurred.
