### ISSUE TITLE
Application boot time takes too much time after increasing number of modules in laravel app

### ISSUE THREAD

**Issue by santosh-ghimire-cogenthealth** [nWidart/laravel-modules#1352]
i have been using nwidart module since 3 years, i was enjoying to developed  modular app using nwidart module package .recently in my big project having module more that 60  module . Now my app became too slow . I have optimize , cache config and routes but nothing work . after removing   50 module my app boot time down to between 1-2 second , if use all module my app boot time becomes 10-12 seconds

**Comment by dcblogdev** [comment]
Sorry, I don't think there's anything that can be done for that many modules.
