### ISSUE TITLE
Error using resource routes.

### ISSUE THREAD

**Issue by MarkAusten** [nWidart/laravel-modules#1353]
The package as-is does not work with resource routes. This can be rectified by setting moduleNamespace to '' in the module service provider but doing so prevents non-resource routes from working. That is:

```
// This works
Route::resource('post', PostController::class);

// This does not.
Route::get('/post','PostController@index');

// This does work
Route::get('/post','Modules\Blog\Http\Controllers\PostController@index');

```

There does not seem to be a way to emulate the Laravel 8/9 routing using this package. You must use one method or the other button both.

**Comment by dcblogdev** [comment]
Yes, due to the routing namespace change its a case of picking your style, personally I prefer to remove the prefix from the route service provider and use the newer class syntax



```php

use Modules\Contacts\Http\Controllers\ContactsController;

Route::get('/', [ContactsController::class, 'index']);
