### ISSUE TITLE
Target class [CommandMakeCommand] does not exist.

### ISSUE THREAD

**Issue by tomosia-hoanguyen** [nWidart/laravel-modules#1355]
Hi! I had issue with version 8.3.0, install with **laravel 8.4**. When run `composer install`, i received an error: 
`Illuminate\Contracts\Container\BindingResolutionException 

  Target class [CommandMakeCommand] does not exist.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:835
    831▕ 
    832▕         try {
    833▕             $reflector = new ReflectionClass($concrete);
    834▕         } catch (ReflectionException $e) {
  ➜ 835▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    836▕         }
    837▕ 
    838▕         // If the type is not instantiable, the developer is attempting to resolve
    839▕         // an abstract type such as an Interface or Abstract Class and there is

      +13 vendor frames 
  14  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

I hard code to back version 8.2.0 and every is OK. Please help me check this issue!

**Comment by chkm8** [comment]
We also encountered the same error, we specifically pointed the version to 8.2 in the composer until latest version is fixed.

`"nwidart/laravel-modules": "8.2.0",`

**Comment by dcblogdev** [comment]
sorry I'm not sure how I missed this I've had to handle all PR's since November 2020 in a single release I thought I'd caught everything.

In the config there's a breaking change for existing config files (fresh configs are okay)

To manually fix this import the commands class:

```php
use Nwidart\Modules\Commands;
```

then update the commands array to prefix the command:

```php
'commands' => [
        Commands\CommandMakeCommand::class,
        Commands\ComponentClassMakeCommand::class,
        Commands\ComponentViewMakeCommand::class,
        Commands\ControllerMakeCommand::class,
        Commands\DisableCommand::class,
        Commands\DumpCommand::class,
        Commands\EnableCommand::class,
        Commands\EventMakeCommand::class,
        Commands\JobMakeCommand::class,
        Commands\ListenerMakeCommand::class,
        Commands\MailMakeCommand::class,
        Commands\MiddlewareMakeCommand::class,
        Commands\NotificationMakeCommand::class,
        Commands\ProviderMakeCommand::class,
        Commands\RouteProviderMakeCommand::class,
        Commands\InstallCommand::class,
        Commands\ListCommand::class,
        Commands\ModuleDeleteCommand::class,
        Commands\ModuleMakeCommand::class,
        Commands\FactoryMakeCommand::class,
        Commands\PolicyMakeCommand::class,
        Commands\RequestMakeCommand::class,
        Commands\RuleMakeCommand::class,
        Commands\MigrateCommand::class,
        Commands\MigrateRefreshCommand::class,
        Commands\MigrateResetCommand::class,
        Commands\MigrateRollbackCommand::class,
        Commands\MigrateStatusCommand::class,
        Commands\MigrationMakeCommand::class,
        Commands\ModelMakeCommand::class,
        Commands\PublishCommand::class,
        Commands\PublishConfigurationCommand::class,
        Commands\PublishMigrationCommand::class,
        Commands\PublishTranslationCommand::class,
        Commands\SeedCommand::class,
        Commands\SeedMakeCommand::class,
        Commands\SetupCommand::class,
        Commands\UnUseCommand::class,
        Commands\UpdateCommand::class,
        Commands\UseCommand::class,
        Commands\ResourceMakeCommand::class,
        Commands\TestMakeCommand::class,
        Commands\LaravelModulesV6Migrator::class,
 ],
```

**Comment by mohamedsharaf** [comment]
to fix simply

`composer remove nwidart/laravel-modules 
`
then remove config/modules.php or backup your config

`composer require nwidart/laravel-modules
`
then reconfigure your changes 

hope it helps :)

**Comment by reidsneo** [comment]
> to fix simply
> 
> `composer remove nwidart/laravel-modules ` then remove config/modules.php or backup your config
> 
> `composer require nwidart/laravel-modules ` then reconfigure your changes
> 
> hope it helps :)

it's not working problem still exists
