### ISSUE TITLE
How To?

### ISSUE THREAD

**Issue by KatiaSishost** [nWidart/laravel-modules#1360]
How to implement a "IF" condition with status module in controller?

for example

if -> module('notifications' => active)
{ callAction;
}

**Comment by dcblogdev** [comment]
You can use the module helper:

```php
$module = Module::find('notifications');
```

Then check if enabled:
```php
$module->isEnabled();
```

Then check if disabled:
```php
$module->isDisabled);
```

You can also do a call in one go:

```php
Module::find('notifications')->isEnabled()
```

Only run the one liner if you've first checked the module exists otherwise you will get an error.
