### ISSUE TITLE
Advanced L9 Support

### ISSUE THREAD

**Issue by MarkAusten** [nWidart/laravel-modules#1361]
How far along the L9 "complaint" route are you going to go with laravel-modues? For example, promotion of the Lang folder, remaining the module namespace property in route ServiceProvider and such like?

Thanks.

**Comment by dcblogdev** [comment]
Open to the idea of matching the defaults, I'm in the process of getting the docs updated, once complete I'll look at this further.

Right now the docs for recent versions are the same as the v6 docs, there's changes in the code base not yet documented, so keen on addressing this first.

**Comment by MarkAusten** [comment]
Thanks for the update.
