### ISSUE TITLE
Undefined variable: $translations in component, php artisan module:make-component 

### ISSUE THREAD

**Issue by limsocheat** [nWidart/laravel-modules#1362]
I generated Laravel component using command: 

> php artisan module:make-component Translations Reservation 

It created two files: 

> /modules/Reservation/view/Component/Translations.php

```
public function render()
    {
        $translations = [];

        return view('reservation::components.translations', [
            'translations' => $translations,
        ]);
    }
```

> /modules/Reservation/resources/views/components/translations.blade.php

```
<script>
    window._translations = @json($translations);
</script>
```

As you can see, I pass $translations variable to view already. 
but I got error: 

> Undefined variable: translations (View: /modules/Reservation/resources/views/components/translations.blade.php)

<img width="1291" alt="Screen Shot 2022-02-18 at 10 25 14 AM" src="https://user-images.githubusercontent.com/6656644/154611743-64c142bb-4e70-4758-8deb-ad2c9e4d9c66.png">

**Comment by dcblogdev** [comment]
load your component:

```php
<x-reservations::translations />
```

In your service provider boot add:

import Blade:
```php
use Illuminate\Support\Facades\Blade;
```

Register component:

```php
Blade::component('reservations::translations', Translations::class);
```

You may need to clear your cache for views:

```php
php artisan view:clear
```

**Comment by dcblogdev** [comment]
With `Blade::component` you can call it anything you like.

```php
Blade::component('crazy-example', Translations::class);
```

to render:

```php
<x-crazy-example />
```

Just remember to clear your view cache.
