### ISSUE TITLE
Laravel Modules, Status in DB OK ... but

### ISSUE THREAD

**Issue by KatiaSishost** [nWidart/laravel-modules#1365]
I have the modus system with the option of the state in the database, the problem I have is that if I install tenancyforlaravel it keeps reading the modules database from the central one and not from the tenant database, could someone help me to change this please?

**Comment by apydevs** [comment]
> I have the modus system with the option of the state in the database, the problem I have is that if I install tenancyforlaravel it keeps reading the modules database from the central one and not from the tenant database, could someone help me to change this please?

I think this is more of an issue with tenancy then laravel modules, but he's how i would troubleshoot it 

This will give you the current database laravel is connecting to.
` dd(DB::connection()->getDatabaseName());` 

 if this the central DB  you need to get the modules like this.
 `$tenant->run(function () {
    Module::get();
});`



https://tenancyforlaravel.com/docs/v3/tenants
Running commands in the tenant context
