### ISSUE TITLE
Get list of modules who can "do" something (using keywords ?)

### ISSUE THREAD

**Issue by rycks** [nWidart/laravel-modules#1368]
Hello all,
first of all, **thanks** a lot for this fantastic project ! i really like it.

Now, i would like to get all of modules who can "do" something, for example if there is 3 modules who can "export data" (one in zip file with all user data, one in one pdf file, one make a doc ...) how can filter them ?

I'm looking for something like that

`$listOfModules = Module::can('export');`

And it could be based on "keywords" fields from module.json no ?

For the moment i do an event "exportData" then modules who can do the job handle the event but it could be more easy sometimes to make with a Facade method.

**Comment by dcblogdev** [comment]
There is nothing that I can see that allows you to do this easily but at a first stab how about something like this:

```php
$searchKeywords = ['export'];
$modules = Module::getOrdered();
$moduleNames = [];
foreach($modules as $module) {
    $keywords = $module->get('keywords');

    foreach($searchKeywords as $match) {
        if (in_array($match, $keywords)) {
            $moduleNames[] = $module->get('name');
        }
    }
}
```

Then loop over the array of module name:

```php
foreach($moduleNames as $moduleName) {
    $module = Module::find($moduleName);
    //use module
}
```

**Comment by rycks** [comment]
Nice idea, i will do something like that (+ laravel-settings from spatie) ! Thanks one more :-)
