### ISSUE TITLE
Declaration of Modules\Core\Providers\RoutingServiceProvider::boot(Illuminate\Support\Facades\Route $router) should be compatible with Illuminate\Foundation\Suppor   t\Providers\RouteServiceProvider::boot()

### ISSUE THREAD

**Issue by mahfuzphp** [nWidart/laravel-modules#137]
I am using this module package. very nice package. 
I am trying to do is : Load route from 3 different file like web, api and back-end.
 I have two Module core and post. I have generate those module by php artisan command.
In core I didnot change anything. 

I understand how the service provider works. it is loading .. why the  RoutingServiceProvider is not loading I don't know.
In post module  
so i put  /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {

        $this->app->register(RoutingServiceProvider::class);

    }

I have 2 module core and post.
In Post Module extends from  CoreRoutingServiceProvider

class RouteServiceProvider extends CoreRoutingServiceProvider

I am getting above error. Any Idea what I am doing  wrong. Thanks

i am getting a error  [ErrorException]
  Declaration of Modules\Core\Providers\RoutingServiceProvider::boot(Illuminate\Support\Facades\Route $router) should be compatible with Illuminate\Foundation\Suppor
  t\Providers\RouteServiceProvider::boot()

i wanted to load api ,web and back end  route files for each module. but i am getting this error? can you help me .

**Comment by adelowo** [comment]
This is not a problem with this package. Rather your code. Did you just upgrade to `5.3` or 5.4`.

My best bet is from  https://laravel.com/docs/5.3/upgrade

> You may remove the arguments from the boot method on the EventServiceProvider, RouteServiceProvider, and AuthServiceProvider classes. Any calls to the given arguments may be converted to use the equivalent facade instead. So, for example, instead of calling methods on the $dispatcher argument, you may simply call the Event facade. Likewise, instead of making method calls to the $router argument, you may make calls to the Route facade, and instead of making method calls to the $gate argument, you may make calls to the Gate facade.

If this didn't work, you should review the upgrade guide and find out what went wrong

**Comment by ercanertan** [comment]
Check my fork maybe helps
https://github.com/ercanertan/laravel-modules

**Comment by nWidart** [comment]
I'll close this for now as it's an issue with autoloading your classes.
