### ISSUE TITLE
Route  Resource config  Controllers Class does not exist.

### ISSUE THREAD

**Issue by githublirui** [nWidart/laravel-modules#1376]
Route config

Route::resource('product', \Modules\Admin\Http\Controllers\ProductController::class);

Illuminate\Contracts\Container\BindingResolutionException
Target class [Modules\Admin\Http\Controllers\Modules\Admin\Http\Controllers\ProductController] does not exist.

**Comment by asule90** [comment]
@githublirui how did you solve it?
