### ISSUE TITLE
Is it possible to autoload resource vies in to core views...

### ISSUE THREAD

**Issue by filtration** [nWidart/laravel-modules#138]
For example, I have modules like so: polls, albums (pictures), now on my timeline I have hardcoded icons and javascript in my timeline:

<img src="https://i.gyazo.com/447094e2811283dbeb3c2757b7fb8a67.png">

I plan on creating modules for my scripts, so those modules won't be installed by default, I can manually install the module via adding the views in the main layouts, but when I release my script, people won't know how to do it,

I've looked through laravel documentation to achieve this, but haven't found anything

For example, this is my status partials in a timeline modules:

    <div class="box profile-info n-border-top">
        <form action="{{ route('CreateStatus') }}" method="post">
            {{csrf_field()}}
            <textarea class="form-control input-lg p-text-area" name="status" rows="2" placeholder="Whats in your mind today?"></textarea>
            <div class="box-footer box-form">
                <input type="submit" value="submit" class="btn btn-azure pull-right">
                <ul class="nav nav-pills">
                    <li><a href="#"><i class="fa fa-map-marker"></i></a></li>
                    <li><a href="#"><i class="fa fa-camera"></i></a></li>
                    <li><a href="#"><i class=" fa fa-film"></i></a></li>
                    <li><a href="#"><i class="fa fa-microphone"></i></a></li>
                </ul>
            </div>
        </form>
    </div>

So, is there a way with this package to add partials from another module to another module automatically?

**Comment by nWidart** [comment]
Not automatically. But you can just call your partials between modules.
