### ISSUE TITLE
Hello everyone. My approach to solving (Inertia with modules)

### ISSUE THREAD

**Issue by wadday** [nWidart/laravel-modules#1381]
Follow the [Repository LInk](https://github.com/wadday/laravel-modules-inertia)
> hello everyone. My approach to solving this issue is a bit different. (Inertia with modules)
> 
> in my base app.js remains the same (note: I have used dynamic import) ![image](https://user-images.githubusercontent.com/194339/160081817-a5a30f19-adb8-4880-9466-369253028bb0.png)
> 
> Structure arrangements I follow the same as the base structure
> 
> base structure ![image](https://user-images.githubusercontent.com/194339/160082429-0b7cda7e-3540-401d-a760-2af2c2f2ec6d.png)
> 
> Modules/Expenses structure ![image](https://user-images.githubusercontent.com/194339/160082706-069c8e8c-66bd-4102-85c0-fbd5fb466f99.png)
> 
> In base app controller (resources/js/Pages/Welcome.vue) ![image](https://user-images.githubusercontent.com/194339/160083309-1c0276a8-f514-4c7b-8102-45aa8e46dc62.png)
> 
> in module controller (Expenses/Pages/ExpensesIndex.vue => resources/js/Pages/Expenses/Pages/ExpensesIndex.vue) ![image](https://user-images.githubusercontent.com/194339/160089957-e6b3a7f7-5816-49dd-bb9d-1090ed5f6d8d.png)
> 
> I have created a command to link Modules. ![image](https://user-images.githubusercontent.com/194339/160084811-564d462e-bcb3-4418-b4f6-da5a22061511.png)
> 
> and finally how the base structure looks like ![image](https://user-images.githubusercontent.com/194339/160084573-f109f269-3e68-4460-9f2f-a455ef69eb34.png)
> 
> ### Sharing data between module to base app. (ExpensesServiceProvider)
> ![image](https://user-images.githubusercontent.com/194339/160085665-bb7a253c-71d7-4553-b9c8-33c385d827f3.png)
> 
> base app Middleware (HandleInertiaRequests extends \Inertia\Middleware) ![image](https://user-images.githubusercontent.com/194339/160086141-2554ec6d-e403-444b-a661-4c274098f940.png)
> 
> note: the config loads the enabled modules so the main app has only access to enabled modules. (custom config)
> 
> Modules/Expenses middleware (ShareDataMiddleware extends \Inertia\Middleware) ![image](https://user-images.githubusercontent.com/194339/160085787-92a7a4cb-6753-4cdc-b8cd-6e38ee257426.png)
> 
> ### Result
> base app ![image](https://user-images.githubusercontent.com/194339/160086823-54babb5b-ecb3-4f0f-8baa-20021a69b096.png)
> 
> module (expenses) ![image](https://user-images.githubusercontent.com/194339/160086958-152b2ccb-e026-49a8-8bdc-773cbf132d3d.png)
> 
> in my demonstration, I have shared expenses (empty array) from module share data middleware. (highlighted) ![image](https://user-images.githubusercontent.com/194339/160087231-2459bac3-4ba5-45bf-9a32-6581a89192f3.png)
> 
> and finally module components are loaded from Modules. ![image](https://user-images.githubusercontent.com/194339/160090631-f57d0fdf-54a5-435d-adcf-6663c8571910.png)
> 
> The idea for this approach is later I want to extract the module as a separate package it will be an easy workflow to integrate into a new project.
> 
> hope this is useful.

can you make some example app with your approach?

_Originally posted by @diorz38 in https://github.com/nWidart/laravel-modules/issues/1162#issuecomment-1081359543_

**Comment by wadday** [comment]
Repo link
[Repository](https://github.com/wadday/laravel-modules-inertia)

**Comment by diorz38** [comment]
@wadday its working in dwv mode, but when i run for production, i got error:
```
> production
> mix --production


● Mix █████████████████████████ building (11%) 0/2 entries 364/368 dependencies 153/165 modules 12 active
 ignored|D:\laragon415\laravel_demos\laravel-modules-inertia\node_modules\object-inspect|.\util.inspect

D:\laragon415\laravel_demos\laravel-modules-inertia\node_modules\webpack\lib\util\hash\wasm-hash.js:108
                const length = data.length;
                                    ^
```

**Comment by wadday** [comment]
@diorz38 have you found any solution yet?? 

I dig a bit on this issue and found that webpack when building for production uses the hash which is not working as we expected using a symbolic link. 

however, made a little tweak using previous topic ideas shared by other users.

app.js
![image](https://user-images.githubusercontent.com/194339/161604792-f4abee11-2272-4a70-9f3a-823c123850c1.png)

webpack.config.js
![image](https://user-images.githubusercontent.com/194339/161604904-4abe8ef6-741e-46f8-afc8-b8fef8d4191c.png)

Module Controller
![image](https://user-images.githubusercontent.com/194339/161604968-13deef67-4af6-4529-ba61-746dfa9eaa81.png)

None module controller
![image](https://user-images.githubusercontent.com/194339/161605029-acb41ab3-efd6-4dbe-a8f1-2b6b5d3255a4.png)

this is working for development and production as well. 

remember to remove/delete the created symbolic links between module to root.

**Comment by wadday** [comment]
also check this [resolvesymlinks](https://webpack.js.org/configuration/resolve/#resolvesymlinks)

**Comment by diorz38** [comment]
@wadday  for now i replace tailwind to bootstrap 5, and the problem was gone. i'll try your approach regarding of webpack setting and in app.js

**Comment by wadday** [comment]
> 

Do you mean you are still using the symbolic link approach?

**Comment by rizkhal** [comment]
how about register custom plugins from modules?

**Comment by diorz38** [comment]
> @diorz38 Do you mean you are still using the symbolic link approach?

yes, you can check it in my repo [inertiaTabler](https://github.com/diorz38/inertiaTabler) if you want.
in there you can find another branch with your new approach, but it doesn't work.

**Comment by rizkhal** [comment]
how about this [titen](gtihub.com/codegoen/titen)?
