### ISSUE TITLE
js and css not found from resource/assets

### ISSUE THREAD

**Issue by richest** [nWidart/laravel-modules#1384]
Hii nWidart I created a module frontend
php artisan module:make frontend

and add some js and css  files to resource/assets/js and css 

I'm calling by this method on blade file
Module::asset('frontend/main.js');

but it says not found on this path.

**Comment by arsangamal** [comment]
Could you please check these two pages ?

https://nwidart.com/laravel-modules/v6/basic-usage/compiling-assets
https://nwidart.com/laravel-modules/v6/advanced-tools/publishing-modules

I hope you find the solution there, in case you didn't, Please attach a screenshots to provide further information of you project structure and code
