### ISSUE TITLE
Laravel Modular Structure .... Array to string conversion error

### ISSUE THREAD

**Issue by MuzammilNaveed** [nWidart/laravel-modules#1388]
i need help to solve the issue. Please help me..
i'm using laravel modular structure and call modular entities into laravel main controller ....
for reference i'll attach the screenshot for your perusal

![image](https://user-images.githubusercontent.com/62797875/164954476-41ac7a41-45f3-4c19-a6aa-530d22d4daae.png)

The above image showing me the Error... 
Following are my vscode scrrenshot.

![image](https://user-images.githubusercontent.com/62797875/164954640-4e93bd39-9e06-4747-83e6-2f8d45d569d6.PNG)

**Comment by arsangamal** [comment]
Could you please attach an image of the Category.php Model code @MuzammilNaveed ?
