### ISSUE TITLE
Class name formation error (data seeding)

### ISSUE THREAD

**Issue by atach** [nWidart/laravel-modules#1394]
- Laravel v9.12.2
- Laravel-modules 9.0.1
- PHP 8.1.5

When trying to call the command:
```bash
php artisan module:make-seed MyFolder/SeedName MyModule
``` 
Invalid name is generated class **```MyFolder/SeedNameTableSeeder```**

```php
<?php
namespace Modules\MyModule\Database\Seeders\MyFolder;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class MyFolder/SeedNameTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        // $this->call("OthersTableSeeder");
    }
}
```

**Comment by wikigods** [comment]
I think the right thing to do would be  "php artisan module:make-seed SeedName MyModule".
But if you want it subfolder the correct thing would be
![Screenshot_30](https://user-images.githubusercontent.com/71094046/169141310-abf468ef-dde3-4d6a-a564-7220bf12edee.png)

**Comment by haithamRD** [comment]
@atach 
if you need to create a SeedName module in subforlder 
i think you should use this command :
`php artisan module:make-seed MyFolder\\SeedName MyModule`

**Comment by dcblogdev** [comment]
> @atach if you need to create a SeedName module in subforlder i think you should use this command : `php artisan module:make-seed MyFolder\\SeedName MyModule`

Confirmed, this will create the seeder in a subfolder.
