### ISSUE TITLE
Do not load module configurations

### ISSUE THREAD

**Issue by pabbec** [nWidart/laravel-modules#1398]
Hi. 

I created a new module from console called Admin.

In the Config folder of this module I created a new config file called sections.php with an array (Modules/Admin/Config/sections.php).

From the AdminController (Modules/Admin/Http/Controllers/AdminController.php) I try to load it because I need the values of these config file with Config::get('admin.sections') but I get only null.

I tried with:

Config::get('admin::sections'); 
Config::get('Admin.sections') ;
Config::get('Admin::sections');

But nothing works.

I'm using Laravel 9.15.0 and Laravel Modules 9.0.1

Could you help me?

**Comment by onemoreahmad** [comment]
Copy this line in your module server provider `$this->registerConfig();` from the `boot method` to the `register method`, and then this `Config::get('admin.sections');` should work.

<img width="451" alt="Screen Shot 2022-06-03 at 5 53 40 AM" src="https://user-images.githubusercontent.com/1885785/171777460-4bb7b347-048e-4046-890d-a96167284223.png">
