### ISSUE TITLE
Model names with upper cases

### ISSUE THREAD

**Issue by unxp** [nWidart/laravel-modules#14]
If you for example run this code: `php artisan module:make NewModule`. It generates all the files correctly except for the namespaces. It probably runs module name through an ucfirst() or something.

So after generating such module all three generated classes will be under namespace **Modules\Newmodule**. However, it should be under **Modules\NewModule**.

**Comment by nWidart** [comment]
Hello,

Thank you for reporting the issue.

This has been fixed in version `0.8`, please give it a try.

https://github.com/nWidart/laravel-modules/releases/tag/0.8

**Comment by unxp** [comment]
Great. Thanks for a quick response!
