### ISSUE TITLE
How to call module in browser

### ISSUE THREAD

**Issue by msaashish** [nWidart/laravel-modules#140]
Hi,

I created a module department when i try like this its saying object not found http://localhost:81/schoolmanagementnew/school/Department/

**Comment by gmox** [comment]
You still have to register routes like any other Laravel application.

**Comment by msaashish** [comment]
Its calling from http://localhost:81/schoolmanagementnew/school/public/Department/

**Comment by gmox** [comment]
So you registered a route like:

`Route::get('/school/public/Department', function() { ... });`

**Comment by aliforever** [comment]
having the same problem, this is the first time I'm trying to make a modular app with laravel.
Modules have a routes.php themselves, and there's a web.php route in laravel.
How is it done? how can we redirect all urls starting with a module's name to that module's route in  web.php?

**Comment by sarfraznawaz2005** [comment]
I think first letter should be lowercase so intead of `Department`, it should be `department` when you type in the url.
