### ISSUE TITLE
module:make command doesn't create a Model / Entity

### ISSUE THREAD

**Issue by StanMenten-bp** [nWidart/laravel-modules#1400]
Hi,

While running the `php artisan module:make Blog` command for example, it doesn't create a model / entity.
Tried it with a fresh Laravel 9 installation.

Am I missing something?

I've published all stubs but haven't changed anything.

**Comment by StanMenten-bp** [comment]
Currently solved this by using `php artisan module:make-model...` command.

**Comment by MelchiorKokernoot** [comment]
I believe this is intended behaviour. A module does not necessarily relate to a model on a 1:1 relationship.

**Comment by dcblogdev** [comment]
yes @MelchiorKokernoot is correct, a model/entity is not created by default, folders specified in the config are created by default but not model classes.

if you want to generate a module with specific files I recommend creating a default structure then using a package to take a copy of that template module. I made a package for this purpose https://github.com/dcblogdev/laravel-module-generator
