### ISSUE TITLE
Delete all related views folder

### ISSUE THREAD

**Issue by serlopDev** [nWidart/laravel-modules#1402]
Is it possible to create modules for only rest api project?, I mean, if it's possible to create through commands a module without webpack and folder views. On the contrary, can I delete this folder without affecting the behavior of the library?

**Comment by MelchiorKokernoot** [comment]
You can delete the Resources directory for sure! Just make sure you are not referencing it anywhere. You can also generate a module with the API template like so: 
`php artisan module:make Blog --api`
