### ISSUE TITLE
Publishing Module to Packagist from inside /Modules

### ISSUE THREAD

**Issue by ShemarBrandonAustin** [nWidart/laravel-modules#1404]
I have created a few modules inside of the main Modules folder but i want them to be reused across all my applications. Submitting to packagist using the normal methods requires me to have that module alone in a repo but im sure there was a way to publish withing the Modules using the terminal. Can anyone help here

**Comment by MelchiorKokernoot** [comment]
I have not tried this myself, but I do think it should be possible to link to a module using a composer repository with a local path: https://getcomposer.org/doc/05-repositories.md#path

Let me know if that works!

**Comment by dcblogdev** [comment]
I don't think there is a way to do this, I always copy the modules into their own repo and release from there.
