### ISSUE TITLE
QUESTION: GUI for Modules Management

### ISSUE THREAD

**Issue by mgip** [nWidart/laravel-modules#1405]
Hello 

Someone know if exist a component to manage all modules, like, add, disactivate, activate, etc etc with crud included.

Thanks

**Comment by MelchiorKokernoot** [comment]
I do not believe this exists. Could be a nice standalone package I think. Let me know if you're going to implement something like this!

**Comment by mgip** [comment]
> I do not believe this exists. Could be a nice standalone package I think. Let me know if you're going to implement something like this!

Check This, https://laraadmin.com/docs/1.0/module_manager, but  i think that is not support any longer.

I will to check that project and i try to adapt to laravel v8 only the module manager system.

see you soon.

**Comment by dcblogdev** [comment]
btw this would have been better on the discussion page https://github.com/nWidart/laravel-modules/discussions
