### ISSUE TITLE
Why not managing the controller and the seeder files in the config like the other files? 

### ISSUE THREAD

**Issue by mshamaseen** [nWidart/laravel-modules#1406]
I'm planning to make a PR for that, just want to make sure you don't have any concerns about it.
I'm trying to create a module, and I **don't** want to use `plain` as I want to generate some files controlled in the config, but I don't want a Controller or a seeder, I'm wondering why these are not added in the `files` section in the config like the other files?

**Comment by dcblogdev** [comment]
All you need to do it change the folder creation to false in the config 

```
'seeder' => ['path' => 'Database/Seeders', 'generate' => false],
'controller' => ['path' => 'Http/Controllers', 'generate' => false],
```

This will stop the folders and contents be generated.

You can then generate a controller when needed and a controllers folder will be created automatically.
