### ISSUE TITLE
Module Management System, Add/Activate/Remove Hot Swappable Modules from GUI just Like Wordpress does it.

### ISSUE THREAD

**Issue by imlolman** [nWidart/laravel-modules#1407]
Hi People,

I am curious to know, is there a module management system available so that admins can add/activate/remove modules just like the plugin system in wordpress?

If there is no plugin system, is it possible to make a module that will help in add/activate/remove custom modules? Basically, are these modules hot swappable and if one of the modules break (bad code/ bug), will they break entire application? Is there a way we can prevent this.

I am looking forward to make such a module (that will help in add/activate/remove custom modules) so that applications can be launched/delivered with the basic functionality and features can be added/removed by using swappable modules (specifically designed for the same application).

I have many more basic questions which I will ask once I get the answers of above questions.

Thanks for working on this repository, Kudos to Open Source Community 👍

**Comment by dcblogdev** [comment]
Hi, there isn't the reason there's no enforcement on what front end is used. Some may use Bootstrap while others could be using Tailwindcss it's very project-specific.

There is a modules_statuses.json which activates/deactivates modules, for example this is from one of my projects:

<img width="255" alt="CleanShot 2022-07-11 at 19 41 23@2x" src="https://user-images.githubusercontent.com/1018170/178335262-e796f135-ad36-4d35-838d-1c55244c09e3.png">

The default is file-based activation like this if you do want a database-driven apprach then you could need to modify your config and prove a database interface into:

```php
/*
    |--------------------------------------------------------------------------
    | Activators
    |--------------------------------------------------------------------------
    |
    | You can define new types of activators here, file, database etc. The only
    | required parameter is 'class'.
    | The file activator will store the activation status in storage/installed_modules
    */
    'activators'      => [
        'file' => [
            'class'          => FileActivator::class,
            'statuses-file'  => base_path('modules_statuses.json'),
            'cache-key'      => 'activator.installed',
            'cache-lifetime' => 604800,
        ],
    ],

    'activator' => 'file',
```
