### ISSUE TITLE
UPPERCASE_NAME replacement in stubs

### ISSUE THREAD

**Issue by madboy-hardik** [nWidart/laravel-modules#1408]
I'm using custom stubs for module generation and in there I need UPPERCASE_NAME replacement. In simple worlds, I need to replace uppercase version of module name in stubs file. How I can do it. I've searched files but It seems there is no replacement function for it in src/Generators/ModuleGenerator.php file.

**Please help me!**

**Comment by dcblogdev** [comment]
I've built a package for generating modules from a template this may be better for your needs https://github.com/dcblogdev/laravel-module-generator
