### ISSUE TITLE
add module:make-request

### ISSUE THREAD

**Issue by hamrahpay** [nWidart/laravel-modules#141]
hello dear
it's better to add module:make-request to project :)
thank you

**Comment by nWidart** [comment]
Hello,

Good idea, pull request welcome.

**Comment by hamrahpay** [comment]
thank you , but "create pull request" button is disabled for me

**Comment by JoseCage** [comment]
@hamrahpay you are doing the right way.?

> thank you , but "create pull request" button is disabled for me

You have forked the repo?

Refs: [Creating a pull request](https://help.github.com/articles/creating-a-pull-request/) and [Creating a pull request from a fork](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)

**Comment by MineSQL** [comment]
You can probably close this ticket @nWidart as the functionality exists.

**Comment by nWidart** [comment]
Indeed!, thanks for bringing this up. 👍
