### ISSUE TITLE
Using "Models" instead of "Entities"

### ISSUE THREAD

**Issue by binaryfire** [nWidart/laravel-modules#1411]
Hello

We'd like to generate new modules with a "Models" folder rather than "Entities". Is there an easy way to make this change?

Thanks!

**Comment by dcblogdev** [comment]
yes, you can change this in the config.

Change:
```
'model' => ['path' => 'Entities', 'generate' => true],
```

To:
```
'model' => ['path' => 'Models', 'generate' => true],
```

**Comment by binaryfire** [comment]
@dcblogdev Thanks David. Actually I just discovered your generator package - nice work!
