### ISSUE TITLE
ModuleJson is not showing 

### ISSUE THREAD

**Issue by sanjayaharshana** [nWidart/laravel-modules#1412]
![image](https://user-images.githubusercontent.com/17973608/178510356-3312881f-5f93-4dbf-b42a-bccb1f57e3e1.png)

**Comment by dcblogdev** [comment]
if you want to read the module.json file you instead call ->json():

```php
$module = Module::find('blog');
dd($module->json('module.json'));
```

<img width="600" alt="CleanShot 2022-07-12 at 16 53 46@2x" src="https://user-images.githubusercontent.com/1018170/178536059-e15e2f34-88dc-4fda-b4d1-e82b47a45b21.png">

**Comment by sanjayaharshana** [comment]
Cool... Thank you guys
