### ISSUE TITLE
How can I create module in the different directories

### ISSUE THREAD

**Issue by hadi-mansoori** [nWidart/laravel-modules#1414]
Hi , I want create api using laravel module but I can't version them and place them in different directories at the same time
Modules/Api/V1/Notification
Modules/Api/V2/Notification

**Comment by dcblogdev** [comment]
I'm not sure what you mean, you can have multiple version in the same module what I do it create a v1 folder and place the files in there and load them via the routeserviceprovider

```
protected function mapApiRoutes()
{
    Route::prefix('api/v1')
        ->middleware('api')
        ->namespace($this->moduleNamespace)
        ->group(module_path('Products', '/Routes/V1/api.php'));
}
```

![CleanShot 2022-07-19 at 08 00 00](https://user-images.githubusercontent.com/1018170/179686581-2a69dc2e-0fda-4799-854b-2b0b38dc88cc.png)

**Comment by hadi-mansoori** [comment]
Thank you very much, you solved my problem
