### ISSUE TITLE
The environment file is invalid!

### ISSUE THREAD

**Issue by mjubouri** [nWidart/laravel-modules#1415]
The environment file is invalid!
Failed to parse dotenv file. Encountered an invalid name at [php artisan module:migrate-refresh Website --seed].

**Comment by dcblogdev** [comment]
I've ran this and its working fine.

```
dave@dcblog submodules % php artisan module:migrate-refresh products --seed
Nothing to rollback.
Migration table created successfully.
Nothing to migrate.
Database seeding completed successfully.
Module [Products] seeded.
```

can you give more details?
