### ISSUE TITLE
Vendor Module Namespace not found

### ISSUE THREAD

**Issue by rehavvk** [nWidart/laravel-modules#142]
Hey guys,

I created a module to puplish it.

So I try it by one of my own projects. Enabled vendor scan and modified the modules namespace.

But when I try to start the server via `php artisan serve`, I get an exception:

**Class 'Invitel\Common\LaravelADAuth\Providers\ADAuthServiceProvider' not found**

My module.json
{
    "name": "ADAuth",
    "alias": "adauth",
    "description": "",
    "keywords": [],
    "active": 1,
    "order": 0,
    "providers": [
        "Invitel\\Common\\LaravelADAuth\\Providers\\ADAuthServiceProvider",
        "Adldap\\Laravel\\AdldapServiceProvider",
        "Adldap\\Laravel\\AdldapAuthServiceProvider"
    ],
    "aliases": {
        "Adldap": "Adldap\\Laravel\\Facades\\Adldap"
    },
    "files": [
        "start.php"
    ],
    "requires": []
}

The namespace of the provider:

**Invitel\Common\LaravelADAuth\Providers**

Please help me. :)

**Comment by mikemand** [comment]
I think you might need to escape the slashes, like so:

```json
{
    "name": "ADAuth",
    "alias": "adauth",
    "description": "",
    "keywords": [],
    "active": 1,
    "order": 0,
    "providers": [
        "Invitel\\Common\\LaravelADAuth\\Providers\\ADAuthServiceProvider",
        "Adldap\\Laravel\\AdldapServiceProvider",
        "Adldap\\Laravel\\AdldapAuthServiceProvider"
    ],
    "aliases": {
        "Adldap": "Adldap\\Laravel\\Facades\\Adldap"
    },
    "files": [
        "start.php"
    ],
    "requires": []
}
```

**Comment by rehavvk** [comment]
I do not know why it is not in my post.

But in my code I did that. Thanks anyway. :)

Any other suggestions?

**Comment by mario-hoyvoy** [comment]
Check the file and class name and make sure the namespace is the folder ubication and you have it writted well.

**Comment by rehavvk** [comment]
Hey mario-hoyvoy,

thanks for your reply, i found the problem by my own and fixed it. :)
