### ISSUE TITLE
[Major] Boot performance

### ISSUE THREAD

**Issue by Sophist-UK** [nWidart/laravel-modules#1420]
I am just starting a new Laravel project.

I had a false start without using Laravel Modules, and that would give a response in 1s-2s or even faster on my dev environment.

I then decided that I would use Laravel Modules and started with a fresh Laravel environment.

Now, without changing Apache or php, the boot time is c. 5s. (This is true from the command line as well as from a browser.)

Removing Laravel Modules makes it fast, adding it again makes it slow. I have no idea what the cause is yet. I will take a look and see if I can work out what is causing this and how to fix it, but I am not confident I can work this out.

**Comment by Sophist-UK** [comment]
Ok - I have found several potential causes in `/src/FileRepository.php`:

1.  The `scan` function is called several (13) times to find `module.json` when I run `php artisan` with no parameters, and each time it recurses the same directories. Note: This is only recursing my modules directory and not the vendor tree - if I had `scan.enabled` in `config/modules.php` this would be far far worse.

  IMO, the `scan` function should cache the results of the first scan in a class variable and reuse that result.

2. The `scan.exclude` config value that is coded in this class is not documented, but the code suggests that you can only exclude specific filenames and not paths. It would be better IMO for the exclude functionality to use  `glob` style path/name matching patterns for exclusion.

3. Assuming that both `recursiveSearch`  and `exclude` use specific filenames, we do not check once at the beginning of the function if the file we are searching for is in the exclude list and return immediately - instead we recurse all directories and filter out such files which seems to me to be a waste of time. (If we use `glob` style filters, then it would still need to be done in the `RecursiveCallbackFilterIterator`.)

4. The callback gets the `scan.exclude` array on every iteration rather than once when the function is called. 

5. The `recursiveSearch` function is looping through every directory and then every file and getting the filename and comparing it to the wanted filename. It would be much better to iterate through the directories and use an improved `RecursiveCallbackFilterIterator` callback function to check that the filename is correct or indeed only iterate the directories and for each directory check whether the specific file exists.

I will try and see if I can address these issues and create a PR tomorrow as it is time for bed here in PT.

**Comment by codeanddeploy** [comment]
Up for this, I hope it gets fixed.

**Comment by mshamaseen** [comment]
@Sophist-UK There is a caching feature that you can enable in the config file.

I like point 5 of your comment. Can you make a PR for it?

Does enabling the cache in the config file fix it for you? How many folders do you have in your modules folder?

**Comment by Sophist-UK** [comment]
I have been (and am still) busy with other things, but I am intending to raisea PR for points 1, 3, 4, and 5 which will leave the functionality exactly the same and just improve performance.

Point 2. is an enhancement to an undoumented feature, so I am unsure about the need for it. 

I don't want to implement point 6 unless I am certain that it will not have unintended consequences, so I need someone more knowledgeable to comment on whether it would have such consequences or not. (Essentially the question is whether the modules/ vendor directories can have modules embedded in packages or other modules - and I do not have anywhere near sufficient experience to know. But I should be able to improve performance substantially.)

**Comment by mshamaseen** [comment]
@Sophist-UK  Just be aware of the following before spending time on making PRs:
1. the package iterate throw each subfolder to search for submodules; refer to https://github.com/nWidart/laravel-modules/pull/1409 for more details about sub module feature.
2. you can enable the caching feature from the config, I'm not sure what exactly this does but I assume it caches the modules in order not to search for them each time.

**Comment by Sophist-UK** [comment]
@mshamaseen

1. Thanks. That tells me that we still need to iterate all directories.

2. Caching is not a benefit during development when things are frequently changing. I will, however, take a look at that when I create the PR.

**Comment by Sophist-UK** [comment]
Points 3, 4 and 5 have been addressed in #1421.

Point 1 has not been addressed because the class itself is instantiated 13 times rather than scan being called 13 times within a single instantiation. I haven't tracked this down, but it does not seem to be a performance problem with the new code.

Point 2. has not been addressed because there is no use case.

Point 6. has not been addressed due to #1409.
