### ISSUE TITLE
Looking for command to rollback specific table and migrate that table again

### ISSUE THREAD

**Issue by JaberWiki** [nWidart/laravel-modules#1423]
### Discussed in https://github.com/nWidart/laravel-modules/discussions/1422

<div type='discussions-op-text'>

<sup>Originally posted by **JaberWiki** July 27, 2022</sup>
How to rollback migration with step  or --path like default Laravel rollback commands on Laravel modules?
I've tried this command

`php artisan migrate:rollback --path=/Modules/ModuleName/Database/Migrations/table_name.php`

**or**

`php artisan module:migrate-rollback --path=/Modules/ModuleName/Database/Migrations/table_name.php Blog`

But it's not working.
Is there any command to migrate or rollback specific table?</div>

**Comment by moxerox** [comment]
Well, the path option is only to indicate the directory, not the file

**Comment by Mello21century** [comment]
It should be like that
```bash
php artisan module:migrate-rollback Product
```

While Product is the module name you wish to rollback current migrations

**Comment by JaberWiki** [comment]
> It should be like that
> 
> ```shell
> php artisan module:migrate-rollback Product
> ```
> 
> While Product is the module name you wish to rollback current migrations

Yeah, It’s also described in documentation. But I want to rollback an specific migration.

**Comment by dcblogdev** [comment]
I've looked into the inner workings into migrator there's no support for this as far as I can see.
