### ISSUE TITLE
Performance issues in 9.0.3

### ISSUE THREAD

**Issue by mike-healy** [nWidart/laravel-modules#1425]
After running a composer update to get a new version of Laravel we started to have big performance issues, especially running the test suite.
Following [this thread](https://twitter.com/aammmaann20/status/1552302380393418752?s=20&t=wFhU2N95KAS37pLRnu5Duw) and the problem seems to be the latest version of Laravel Modules.

Reverting Modules to 9.0.1 with the latest Laravel (9.22) resolved the perf problems.

**Comment by webty-mizusawa** [comment]
v9.0.2 | v9.0.3 have performance issues due to the addition of submodule functionality.
 
https://github.com/nWidart/laravel-modules/pull/1409

**Comment by dcblogdev** [comment]
I've reverted the recent changes back now, if you do a composer update to get 9.0.4
