### ISSUE TITLE
Examples for enable/disable database modules for tenants

### ISSUE THREAD

**Issue by bipin-nepular** [nWidart/laravel-modules#1436]
Hi there, As it looks like we can enable or disable specific modules based on database modules table.  Can you plz help me with documentation or examples related to enabling or disabling tenants specific modules. Would be really grateful !! 
I am using "tenancyforlaravel" package for managing my tenants...

**Comment by Mello21century** [comment]
It's doable as I can see in the code. 

I never tried it but I can see there is a config array
```php
'activators' => [
        'file' => [
            'class' => FileActivator::class,
            'statuses-file' => base_path('modules_statuses.json'),
            'cache-key' => 'activator.installed',
            'cache-lifetime' => 604800,
        ],
    ],
```

As I can see 
https://github.com/nWidart/laravel-modules/blob/6eb80e2d9074c579e13bd0601f7b0a357b5a876a/src/Activators/FileActivator.php
This file is used to the determinate which modules is enabled

You need first to publish the configuration of the package using
```bash
php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"
```
Then: You can create a similar class in your laravel app or in a core module or something. 
Make sure to: Replicate the same methods. But querying database instead based on current tenant. retrieving the modules enabled 

Modify the configuration file app/config/modules.php

Change activators > file > class: to your created class. with namespace prefix.
 
And hope this would work with you

**Comment by yashiroiori** [comment]
In this case, each tenant may have module list in own database, each module have field status or active or any name, then create menu dynamic per user depending permission and only get active modules

I use like this code in both ways, normal Laravel app and multi tenant app

https://github.com/yashiroiori/erp-tabler/blob/b2d6530bf00666f8ad665ed86e46069e2e26ebf1/app/Traits/UserMenuTrait.php#L25
