### ISSUE TITLE
Filament issue with Module

### ISSUE THREAD

**Issue by Mello21century** [nWidart/laravel-modules#1437]
Hello,

I've used laravel modules package to separate the projects into different modules each should have his own logic and related models
I've used the filament package for admin interface

This is a public rebo:
https://github.com/sz4h/filament-base
As you can see in "Modules/Product" I've added filament resources as described 
https://filamentphp.com/docs/2.x/admin/plugins#registering-plugins

I've added an example resources
But it doesn't loaded in admin panel

I've checked the code behind of both filament package and laravel-modules packages. Didn't notice the problem. I'm willing to pull request the problem and solve myself. Just need some kind of hint

As far as I see. There is another package I've installed that implement spatie roles & permissions into the filament admin
It uses the same concept that I'm tryin to achieve. But it's a Package not a Module.

I've tried to dump the service provider of the package and filament. I could see that filament package comes after spatie-filament package in order of Laravel registration. While the module service provider comes later. (May be that's the problem)

Please advice anything

**Comment by Mello21century** [comment]
I've fixed it by
I've added those lines to main composer.json
```json
{
"extra": {
    "laravel": {
      "dont-discover": [
        "filament/filament"
      ]
    }
  }
}
```
Then inside my module service provider I've added

```php
	public function register()
	{
		// These couple of lines
		if (class_exists('Filament\FilamentServiceProvider')) {
			$this->app->register(\Filament\FilamentServiceProvider::class);
		}

	}
```

Now I can see the resources in the admin panel and working fine

Thanks anyway

**Comment by dcblogdev** [comment]
thanks for documenting your solution 👍
