### ISSUE TITLE
Webpack mergemanifest not compiling if changed modules folder

### ISSUE THREAD

**Issue by OtiZ2** [nWidart/laravel-modules#1439]
I changed structure to app\Modules
i install merge manifest
https://nwidart.com/laravel-modules/v6/basic-usage/compiling-assets
and edited webpack.mix.js 

but modules assets are not processed.

![image](https://user-images.githubusercontent.com/11439000/184812793-84dde1eb-33f7-4623-81be-2108fecdb612.png)

**Comment by dcblogdev** [comment]
can you share any code to help investigate.
