### ISSUE TITLE
API is working after Disabling a Module

### ISSUE THREAD

**Issue by aliabaws** [nWidart/laravel-modules#1440]
Hi, I have started working with laravel modules recently. I wrote an API call, abc, in a module, Post, and bound it in the laravel RouteServiceProvider. 
Even after disabling the module i was able to call the abc API. I also cleared the cache after disabling the module..
need help in working with modules. 
I have gone through the documentation but found nothing helpful regarding API management

**Comment by Mello21century** [comment]
Please share the code on github or provide an examples of your setup so anyone can help
