### ISSUE TITLE
how can i add css,js for root laravel views from inner module

### ISSUE THREAD

**Issue by vakora** [nWidart/laravel-modules#1441]
hi, I created a module for my project, in the project when the user installs my module I want to add some CSS, js to the whole laravel view blades header, how can I edit the laravel layout from my module

**Comment by Mello21century** [comment]
Hi,

If I understand you right. The layout of your UI is rested inside resources/views/ base folder

You can add  @stack or @yield to it
and inside your module views. You may extends certain layout and use @push or @section  directive to inject some snippets into the layout

Example:
resources/views/layouts/main.blade.php
```php
<html>
<head>
...
@stack('css')
</head>
...
@stack('js')
</html
```

Inside your Modules/MyModule/Resources/views/page.blade.php
```php
@extends('layouts.main')

@push('css')
<link rel="stylesheet" href="SOMEURLS">
@endpush

@section('content')
Content Goes Here
@endsection

@push('js')
<script src="SOMEURLS"></script>
@endpush
```

Hope it helps. If that what you means

**Comment by vakora** [comment]
> Hi,
> 
> If I understand you right. The layout of your UI is rested inside resources/views/ base folder
> 
> You can add @stack or @yield to it and inside your module views. You may extends certain layout and use @Push or @section directive to inject some snippets into the layout
> 
> Example: resources/views/layouts/main.blade.php
> 
> ```
> <html>
> <head>
> ...
> @stack('css')
> </head>
> ...
> @stack('js')
> </html
> ```
> 
> Inside your Modules/MyModule/Resources/views/page.blade.php
> 
> ```
> @extends('layouts.main')
> 
> @push('css')
> <link rel="stylesheet" href="SOMEURLS">
> @endpush
> 
> @section('content')
> Content Goes Here
> @endsection
> 
> @push('js')
> <script src="SOMEURLS"></script>
> @endpush
> ```
> 
> Hope it helps. If that is what you means

yes my question is about extending the base view from the module but in this way you said when I have some variable in the base view that passes view his controller m when I extends view I got some error about null  value, i want to know can i extends base view by another way?

**Comment by wadday** [comment]
try something like this along with @Mello21century suggestion

![image](https://user-images.githubusercontent.com/194339/187198175-5014be9c-bb55-4232-aafb-621b63f5f97a.png)

**Comment by Mello21century** [comment]
Thanks @wadday mention me help see his reply
I guess u mean that variables inside main base view like page title or some menu links or even auth user data are passed to the view through some controller method
And in your module these variables are not passed to the base view when u extend it

If the previous paragraph explain your problem. Then u might need to do it in one way of the following:

1- Using view composer
Docs: https://laravel.com/docs/9.x/views#:~:text=View%20composers%20are%20callbacks%20or,logic%20into%20a%20single%20location. 

2 - using view share
Docs: https://laravel.com/docs/9.x/views#sharing-data-with-all-views

Hope this helps u
If not please don't hesitate to reply me
Just mention me for faster respond

**Comment by wadday** [comment]
> Thanks @wadday mention me help see his reply I guess u mean that variables inside main base view like page title or some menu links or even auth user data are passed to the view through some controller method And in your module these variables are not passed to the base view when u extend it
> 
> If the previous paragraph explain your problem. Then u might need to do it in one way of the following:
> 
> 1- Using view composer Docs: https://laravel.com/docs/9.x/views#:~:text=View%20composers%20are%20callbacks%20or,logic%20into%20a%20single%20location.
> 
> 2 - using view share Docs: https://laravel.com/docs/9.x/views#sharing-data-with-all-views
> 
> Hope this helps u If not please don't hesitate to reply me Just mention me for faster respond

@vakora FYA
