### ISSUE TITLE
Upgrade webpack to vitejs

### ISSUE THREAD

**Issue by RezaMnk** [nWidart/laravel-modules#1442]
Due to laravel 9.19 release and replacement of Webpack by Vitejs, is there any update for Laravel modules?

And if there is any temporary solution I will be very grateful to check it out. Thanks

**Comment by razavistag** [comment]
Requesting to replace Webpack to Vite compiler #

**Comment by anantrp** [comment]
+1

**Comment by RezaMnk** [comment]
Well I know it, but laravel is migrating to vite and this is not a good idea to downgrading it

**Comment by dcblogdev** [comment]
see https://github.com/nWidart/laravel-modules/issues/1413#issuecomment-1208029864 The way it works I'm not sure if it can be loaded by modules directly.

**Comment by dcblogdev** [comment]
yeah, I'm not sure of the right course of action on this, personally, I don't use any front-end assets from modules. But if you do maybe sticking with webpack may be better.

I'm open to suggestions

**Comment by jjanampa** [comment]
example admin module with vite:

**vite.config.js:**
```

import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

const domain = 'mydomain.test';
export default defineConfig({
    envDir: '../../',
    build: {
        manifest: true,
        emptyOutDir: true,
        assetsDir:'',
    },
    server: {
        https: {
            key: "../../.docker/nginx/certs/app.key",
            cert: "../../.docker/nginx/certs/app.crt",
        },
        host: domain,
        hmr: {
            host: domain,
        },
    },
    plugins: [
        laravel({
            publicDirectory: '../../public',
            buildDirectory: "static/admin",
            input: [
                'Resources/assets/css/app.css',
                'Resources/assets/js/app.js',
            ],
            refresh: [
                'Resources/views/**/*.php',
            ],
        }),
    ],
});
```

**in AdminServiceProvider:**
```
    public function boot(Router $router)
    {
        ...
        Vite::useBuildDirectory('static/admin');

    }
```
**in view:**

```
    {{
        Vite::withEntryPoints(['Resources/assets/css/app.css', 'Resources/assets/js/app.js'])
    }}
```
`{{ Vite::asset('Resources/assets/images/logo.png') }}`

**Comment by anburocky3** [comment]
Closed without any solution? 🤕
