### ISSUE TITLE
artisan model:prune returns DirectoryNotFoundException

### ISSUE THREAD

**Issue by rowanfuchs** [nWidart/laravel-modules#1444]
When following the laravel docs on how to add pruning to models https://laravel.com/docs/9.x/eloquent#pruning-models and initializing the prune command, the following error returns:

```
Symfony\Component\Finder\Exception\DirectoryNotFoundException

  The "/var/www/app/Models" directory does not exist.

  at vendor/symfony/finder/Finder.php:592
    588▕             } elseif ($glob = glob($dir, (\defined('GLOB_BRACE') ? \GLOB_BRACE : 0) | \GLOB_ONLYDIR | \GLOB_NOSORT)) {
    589▕                 sort($glob);
    590▕                 $resolvedDirs[] = array_map([$this, 'normalizeDir'], $glob);
    591▕             } else {
  ➜ 592▕                 throw new DirectoryNotFoundException(sprintf('The "%s" directory does not exist.', $dir));
    593▕             }
    594▕         }
    595▕
    596▕         $this->dirs = array_merge($this->dirs, ...$resolvedDirs);

      +15 vendor frames
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Comment by dcblogdev** [comment]
This is a Laravel error, telling you the folder path `var/www/app/Models` cannot be found.

**Comment by rowanfuchs** [comment]
Thanks for the response, while I understand that it is a laravel error. The problem is that the Laravel modules package cannot handle prunable modules due to this. I couldn't provide a path to the Model or Entity as it could not be found, the Modules folder / namespace wasn't recognized. Looking at the code of Laravel this feels like an issue of the Laravel modules package not properly defining a models namespace.

Note line 122 of the PruneCommand file which uses the app_path of models:
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Console/PruneCommand.php#L122
