### ISSUE TITLE
"requires": [] in module.json

### ISSUE THREAD

**Issue by sprklinginfo** [nWidart/laravel-modules#1447]
Hi, can someone explain what `"requires": []` is for in the `module.json` file in a module directory? Thanks!

**Comment by Sandersm90** [comment]
#968

**Comment by sprklinginfo** [comment]
Thanks @Sandersm90  . It is auto-generated in the module.json file when creating a module. Do you mean it is acting like the 'require' array in the module's composer.json file? following the same syntax in the composer.json file?

**Comment by dcblogdev** [comment]
That used to be for requiring other packages, it's not used anymore now.

To require modules use the composer file.

I'll go through the stubs for module.json and remove any elements that are no longer used to avoid confusion.

**Comment by sprklinginfo** [comment]
thanks @dcblogdev. so if my Module A depends on a third-party package, do I just add it in the module's composer.json file, then run 'module:update' command? Is there a way that when the module is enabled, the required dependencies for the module will be auto-loaded?
