### ISSUE TITLE
Double loading of service providers

### ISSUE THREAD

**Issue by SpinyMan** [nWidart/laravel-modules#1448]
I tested my application and by chance I found one weird thing: all service providers started to load again.
After some researching I found that in file `src/LaravelModulesServiceProvider.php` in `boot` section there is the `$this->registerModules();` call that loads `BootstrapServiceProvider` class. This triggers Laravel to reload all Service providers again.
So, you should avoid to load any service providers in boot section!
But if you try to move `$this->registerModules();` in `register` you will get some errors that `cache` and `translator` target class not found. So, you should force load them before.

**Comment by dcblogdev** [comment]
how do you know all service providers are being called twice?

**Comment by SpinyMan** [comment]
> how do you know all service providers are being called twice?

Xdebug helped me to do this.
