### ISSUE TITLE
Markdown mails ?

### ISSUE THREAD

**Issue by BRKsDeadPool** [nWidart/laravel-modules#145]
How about an artisan option to the command "module:make-mail" to generate markdown mails ? like the original one "make:mail"

**Comment by nWidart** [comment]
What do markdown email classes need over the usual email classes ?

**Comment by nWidart** [comment]
From what I read in the docs it's as simple as using `markdown` instead of `view`

https://laravel.com/docs/5.4/mail#generating-markdown-mailables

**Comment by BRKsDeadPool** [comment]
Yeah you are right, i didn't saw that
