### ISSUE TITLE
Add functions from a module to a existing model

### ISSUE THREAD

**Issue by FrancissEscamez** [nWidart/laravel-modules#1452]
Hi, i had a project with a model of invoice, that had his relations and all.

Then, i had a module that create a entity of payment, and i want it to be related with invoice.

I can relate the payment with the invoice, but my question is, how can i relate the invoice with the paiment, without modifying the invoice model? so i can do $invoice->paiments

Or a more general idea, how can i add new functions to an existing model, via a module

**Comment by dcblogdev** [comment]
I don't think you can without adding a relationship on the invoice model. In theory, you could create a model class in your module that extends the invoice model and use that.

Personally, I would add the method to the model directly.

**Comment by twf-nikhila** [comment]
I used this approach and it worked.

Check screenshot - 

![image](https://github.com/nWidart/laravel-modules/assets/3498959/fcb361a2-39ef-4db2-9b8a-c238cb185c3c)
