### ISSUE TITLE
Error with updating modules when scripts are defined on the composer.json file

### ISSUE THREAD

**Issue by jaymeh** [nWidart/laravel-modules#1453]
Hi,

I've come across an issue when defining a custom script on one of my modules. Here is the composer.json file:

```
{
    "name": "creode/externalapiauthentication",
    "description": "",
    "authors": [
        {
            "name": "Creode",
            "email": "contact@creode.co.uk"
        }
    ],
    "extra": {
        "laravel": {
            "providers": [],
            "aliases": {

            }
        }
    },
    "autoload": {
        "psr-4": {
            "Modules\\ExternalApiAuthentication\\": ""
        }
    },
    "scripts": {
        "build-docs": "npx redoc-cli --output Docs/api/docs.html build Docs/api/document-retrieval-api.yml"
    }
}
```

Upon running the `php artisan module:update` command I get an error stating: `array_merge(): Argument #1 must be of type array, string given`.

This is when using PHP 8.0.21.

![CleanShot 2022-08-31 at 16 50 34](https://user-images.githubusercontent.com/18261676/187722761-5c3a2573-5144-4963-a465-76f3519f15af.png)

**Comment by dcblogdev** [comment]
just like in composer.json the scripts expect an array so yous can be changed to:

```
"scripts": {
        "build-docs": [
            "npx redoc-cli --output Docs/api/docs.html build Docs/api/document-retrieval-api.yml"
        ]
    }
```

This will then run the command

<img width="700" alt="CleanShot 2022-09-07 at 18 46 36@2x" src="https://user-images.githubusercontent.com/1018170/188944801-6c65b7f9-c85f-44aa-bfb7-5ae1743229f0.png">

**Comment by jaymeh** [comment]
Perfect, thank you for this. 👍
