### ISSUE TITLE
Method Nwidart\Modules\Laravel\LaravelFileRepository::object does not exist.

### ISSUE THREAD

**Issue by yanarowana123** [nWidart/laravel-modules#1458]
BadMethodCallException: Method Nwidart\Modules\Laravel\LaravelFileRepository::object does not exist. in file /var/www/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php on line 113

Module version v8.3.0
Framework version v8.*

When i try to make api request to a new route i just have added. Another routes of the same module works fine. 

<img width="876" alt="image" src="https://user-images.githubusercontent.com/43446950/188371827-62762547-d7e0-4722-98cd-11146fcaa798.png">

**Comment by zakipharaon** [comment]
use module V8.0 
it will work fine
