### ISSUE TITLE
Preferred way of registering facades in modules

### ISSUE THREAD

**Issue by gmox** [nWidart/laravel-modules#146]
Is there a preferred way to register a facade in modules? I don't see any references in the master branch to facade registering, so before I go and submit a PR, how does everyone register facades?

**Comment by sarfraznawaz2005** [comment]
Use the `aliases` section in module.json file of the module, example:

      "aliases": {
          "Flash": "Laracasts\\Flash\\Flash"
      },

**Comment by gmox** [comment]
Are you sure about that? The only references to alias I see are the same as saying "another name to call this."

https://github.com/nWidart/laravel-modules/search?utf8=%E2%9C%93&q=alias

Aliases also comes up with nothing, so if that was the way of doing it, it seems to be no longer the case.

**Comment by gmox** [comment]
Ah, it turns out I am mistaken and Github's search is just bad:

https://github.com/nWidart/laravel-modules/blob/master/src/Module.php#L246
