### ISSUE TITLE
Please Help Me to Fix it , I Use laravel-searchable Cant found route from Modules 

### ISSUE THREAD

**Issue by adibw99** [nWidart/laravel-modules#1466]
I have problem with Searchable with your libraries package. I use Laravel Modules from https://nwidart.com/laravel-modules/v6/introduction and I create Navigation menu with this . I try create Multi search with laravel-searchable library but I cant found this route . I try to create global route , and that can be found but to specification route it cant be found. 
![image](https://user-images.githubusercontent.com/50860243/192343439-a6373a9d-e26e-4b2a-9c8c-fa74c1ee0820.png)
How shoul I do to compare  laravel-searchable match with Laravel modules? Laravel modules have specification own models.

**Comment by dcblogdev** [comment]
It looks like you need to update the name route it appears it's named as only `detail` but you're referring to it as `career.detail`
