### ISSUE TITLE
 Class "Illuminate\Foundation\Console\ShowModelCommand" not found

### ISSUE THREAD

**Issue by sosupp** [nWidart/laravel-modules#1470]
A new installation of the package throws an error that ShowModelCommand not found. Any help on this will be useful. Thanks.

>  Class "Illuminate\Foundation\Console\ShowModelCommand" not found

  at C:\xampp\htdocs\picker\vendor\nwidart\laravel-modules\src\Commands\ModelShowCommand.php:7
      3▕ namespace Nwidart\Modules\Commands;
      4▕
      5▕ use Illuminate\Foundation\Console\ShowModelCommand;
      6▕
  ➜   7▕ class ModelShowCommand extends ShowModelCommand
      8▕ {

      9▕
     10▕
     11▕     /**

  1   C:\xampp\htdocs\picker\vendor\composer\ClassLoader.php:571
      include()

**Comment by mwillis72** [comment]
Am also facing the same problem on laravel 9 and php 8

**Comment by mwillis72** [comment]
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/Console/ShowModelCommand.php

The above file does not exist in your laravel installation try to check

**Comment by smartrahat** [comment]
It solved when I upgrade from 8 to 9
