### ISSUE TITLE
Problems with the translation system and loadJsonTranslationsFrom()

### ISSUE THREAD

**Issue by Rattone** [nWidart/laravel-modules#1476]
I'm having problems translating static texts of my modules (Laravel 8) and analyzing I found several inconsistencies, at least I think.

First, I noticed that this commit https://github.com/nWidart/laravel-modules/commit/3b1285084019d25eb08619d5bfb1f958d17c2a47 introduced JSON translations by default, great, but the function `loadJsonTranslationsFrom` require only one parameter and 2 are passed. 

- Laravel API Docs: https://laravel.com/api/9.x/Illuminate/Support/ServiceProvider.html#method_loadJsonTranslationsFrom

I also noticed that the package "publishes" the module translations under the `resources/lang/{$name}` folder, instead the stub points to the `'lang/modules/' . $this->moduleNameLower` folder.

- `module:publish-translation` command that call LangPublisher
https://github.com/nWidart/laravel-modules/blob/master/src/Commands/PublishTranslationCommand.php

- LangPublisher with /resources/lang/
https://github.com/nWidart/laravel-modules/blob/master/src/Publishing/LangPublisher.php#L25

- Stub with /resources/lang/module/
https://github.com/nWidart/laravel-modules/blob/master/src/Commands/stubs/scaffold/provider.stub#L83

The documentation is also very unclear about how translations work

**Comment by MirazMac** [comment]
Facing the same issue. Even overriding the registerTranslations() method doesn't work.

**Comment by Rattone** [comment]
> Facing the same issue. Even overriding the registerTranslations() method doesn't work.

With Laravel 8?
The problem doesn't seem to be present with Laravel 9, and the related version of this package, but I couldn't find the cause why it doesn't work with Laravel 8

**Comment by MirazMac** [comment]
> > Facing the same issue. Even overriding the registerTranslations() method doesn't work.
> 
> With Laravel 8? The problem doesn't seem to be present with Laravel 9, and the related version of this package, but I couldn't find the cause why it doesn't work with Laravel 8

No, I'm using Laravel 9. Can you tell me how you solved this in Laravel 9?

**Comment by Rattone** [comment]
> No, I'm using Laravel 9. Can you tell me how you solved this in Laravel 9?

I haven't "solved", I just tested with a fresh install in Laravel 9 (with Sail) and the translations from the modules work. The same operation with Laravel 8 did not bring the same result.
I couldn't test carefully, I did a quick test because currently I can't migrate to Laravel 9.

**Comment by dcblogdev** [comment]
Thanks for raising this I'll do some tests, from what I understand this problem happens only with Laravel 8?

I'll do some testing with 8 and 9

**Comment by Rattone** [comment]
> Thanks for raising this I'll do some tests, from what I understand this problem happens only with Laravel 8?
> 
> I'll do some testing with 8 and 9

Thanks to you! From what I could see from my (few) tests done 3 months ago with Laravel Sail, the problem was only in Laravel 8. Let us know ❤️

**Comment by MirazMac** [comment]
> the translations from the modules work

It works, however, published translations aren't being loaded. It always loads translation from the module's directory.

**Comment by dcblogdev** [comment]
okay in Laravel 8 there is no json call by default so adding `$this->loadJsonTranslationsFrom(module_path($this->moduleName, 'Resources/lang'));` into the `registerTranslations` from the module service provider is needed. 

```php
public function registerTranslations()
{
    $langPath = resource_path('lang/modules/' . $this->moduleNameLower);

    if (is_dir($langPath)) {
        $this->loadTranslationsFrom($langPath, $this->moduleNameLower);
        $this->loadJsonTranslationsFrom($langPath);
    } else {
        $this->loadTranslationsFrom(module_path($this->moduleName, 'Resources/lang'), $this->moduleNameLower);
        $this->loadJsonTranslationsFrom(module_path($this->moduleName, 'Resources/lang'));
    }
}
```

**Comment by dcblogdev** [comment]
Also with a bit of tinkering languages can be loaded from module/lang folder

```php
$langPath = resource_path('lang/modules/' . $this->moduleNameLower);
$rootLangPath = module_path($this->moduleName, 'lang');

if (is_dir($langPath)) {
    $this->loadTranslationsFrom($langPath, $this->moduleNameLower);
    $this->loadJsonTranslationsFrom($langPath);
} elseif (is_dir($rootLangPath)) {
    $this->loadTranslationsFrom($rootLangPath, $this->moduleNameLower);
    $this->loadJsonTranslationsFrom($rootLangPath);
} else {
    $this->loadTranslationsFrom(module_path($this->moduleName, 'Resources/lang'), $this->moduleNameLower);
    $this->loadJsonTranslationsFrom(module_path($this->moduleName, 'Resources/lang'));
}
```

needs a bit of cleanup and to see if this can be made more directly.

**Comment by Rattone** [comment]
@dcblogdev the correct $rootLangpath value should be with `Resources/lang` as second parameter!?

I try the code (and many variants) in my application and it doesn't load the module translations but the Laravel default ones

**Comment by dcblogdev** [comment]
okay for Laravel 8 this refactor will load the languages:

this can then load languages from

* resources/lang/module/*
* modules/module/Resources/lang/*
 

```php
public function registerTranslations()
{
    $langPath                                = resource_path('lang/modules/' . $this->moduleNameLower);
    $modulesResourceLangPath = module_path($this->moduleName, 'Resources/lang');

    is_dir($langPath) ? $this->loadTranslations($langPath) : $this->loadTranslations($modulesResourceLangPath);
}

protected function loadTranslations($path)
{
    $this->loadTranslationsFrom($path, $this->moduleNameLower);
    $this->loadJsonTranslationsFrom($path);
}
```

then for Laravel 9:

this can then load languages from

* resources/lang/module/*
* modules/module/Resources/lang/*
* modules/module/lang/* //support for the new path to match Laravel 9 structure

```php
public function registerTranslations()
{
    $langPath                                = resource_path('lang/modules/' . $this->moduleNameLower);
    $modulesLangPath                = module_path($this->moduleName, 'lang');
    $modulesResourceLangPath = module_path($this->moduleName, 'Resources/lang');

    if (is_dir($langPath)) {
        $this->loadTranslations($langPath);
    } elseif (is_dir($modulesLangPath)) {
        $this->loadTranslations($modulesLangPath);
    } else {
        $this->loadTranslations($modulesResourceLangPath);
    }
}

protected function loadTranslations($path)
{
    $this->loadTranslationsFrom($path, $this->moduleNameLower);
    $this->loadJsonTranslationsFrom($path);
}
```

**Comment by dcblogdev** [comment]
> @dcblogdev the correct $rootLangpath value should be with `Resources/lang` as second parameter!?
> 
> I try the code (and many variants) in my application and it doesn't load the module translations but the Laravel default ones

yes i try trying it out the a modified layout folder path but remember that was not changed until Laravel 9, 8 its located in Resources as you've mentioned

**Comment by dcblogdev** [comment]
This loads for me using Laravel 8 and Laravel Modules 8

<img width="291" alt="CleanShot 2022-12-27 at 13 39 45@2x" src="https://user-images.githubusercontent.com/1018170/209674928-efdc491c-24d5-49ee-939c-29a0d2487e02.png">

**Comment by Rattone** [comment]
I

> This loads for me using Laravel 8 and Laravel Modules 8
> 
> <img alt="CleanShot 2022-12-27 at 13 39 45@2x" width="291" src="https://user-images.githubusercontent.com/1018170/209674928-efdc491c-24d5-49ee-939c-29a0d2487e02.png">

So I've to try with a clean installation couse I modified the code as you suggested and moved the it.json file from /resources/lang to /Modules/Admin/Resources/lang but the file with my Italian translations is not read.

![image](https://user-images.githubusercontent.com/7362607/209675304-63926d96-f4bf-4163-9856-a207edf14573.png)

**Comment by dcblogdev** [comment]
do you have `/resources/lang/modules/admin` present still? if it's there then the module lang won't be loaded.

what if you have your method to look like this only:

```php
$modulesResourceLangPath = module_path($this->moduleName, 'Resources/lang');
$this->loadTranslations($modulesResourceLangPath);
```

so that it only looks for lang files inside your module

**Comment by Rattone** [comment]
> do you have `/resources/lang/modules/admin` present still? if it's there then the module lang won't be loaded.

I've never had any translations under resources/lang/modules/admin. Now I'm forced to have a single it.json file in resources/lang for all modules, with the obvious limitations.

> what if you have your method to look like this only:
> 
> ```
> $modulesResourceLangPath = module_path($this->moduleName, 'Resources/lang');
> $this->loadTranslations($modulesResourceLangPath);
> ```
> 
> so that it only looks for lang files inside your module

In the previous code, php "enters" in the right if so even with this suggestion the it.json file in /Modules/Admin/Resources/lang/ is not read to me

**Comment by dcblogdev** [comment]
I don't understand why it's not being read for you. I've uploaded my demo at https://github.com/dcblogdev/sample-laravel-modules-8/

If you go to /contacts you will see `{{ __('Hello World') }}` inside the index view file but when rendered it shows `Ciao mondo` since I've set the application use it `it` as the language

**Comment by Rattone** [comment]
> I don't understand why it's not being read for you. I've uploaded my demo at https://github.com/dcblogdev/sample-laravel-modules-8/
> 
> If you go to /contacts you will see `{{ __('Hello World') }}` inside the index view file but when rendered it shows `Ciao mondo` since I've set the application use it `it` as the language

As soon as I have time, I'll also try it with a fresh installation. I think to do it during these Christmas holidays.
Thank you for your time

**Comment by Rattone** [comment]
I did a clean install of Laravel 8 with Sail and the problem doesn't seem to occur, the Italian json file is read by the module.
So the problem is with my codebase but I can't figure out what it could be. The project is now big to move everything into an empty one. I will do other tests to understand, if you have any advice let me know :-)

**Comment by Rattone** [comment]
I found the cause of my problem. It's the rinvex/laravel-categories package that using translation functionality for some strange reason invalidates loadJsonTranslationsFrom. I'm trying to figure out why...
If I remove the package the translation is taken from the it.json file in the modules, as soon as I put it back in my composer dependencies it stops working

**Comment by dcblogdev** [comment]
Does it have the same language keys in use? I'm guessing it's a loading order issue in that which ever is loaded first is used.

**Comment by Rattone** [comment]
I don't know, I don't think so. If you require rinvex/laravel-categories in your project "sample-laravel-modules-8" the translation from the module stops working

**Comment by dcblogdev** [comment]
I'm out this evening but I'll see if I can understand the cause

**Comment by Rattone** [comment]
I did a quick test with a clean install of Laravel 9 + nWidart/laravel-modules + rinvex/laravel-categories = Same problem as with Laravel 8

**Comment by Rattone** [comment]
I have a small update, I found that the package that invalidates module translations is rinvex/laravel-support, a dependency of laravel-categories

**Comment by MirazMac** [comment]
> > > Facing the same issue. Even overriding the registerTranslations() method doesn't work.
> > 
> > 
> > With Laravel 8? The problem doesn't seem to be present with Laravel 9, and the related version of this package, but I couldn't find the cause why it doesn't work with Laravel 8
> 
> No, I'm using Laravel 9. Can you tell me how you solved this in Laravel 9?

My bad, I had `modules.register.translations` set to `true` which was overriding the loaded translations.
