### ISSUE TITLE
Same attribute name validation

### ISSUE THREAD

**Issue by serdarkok** [nWidart/laravel-modules#148]
Hi there;
Example, I created two modules at laravel 5.3 as groups and customers. groups and customers table have "name" fields both. Form validation is taking language and attributes array to "rootproject/resources/lang/[lang]/validation.php" but groups's name and customers's name is different attributes. I want to custom validation lang file for modules. How can i do this?

**Comment by nWidart** [comment]
Each module can have its own translation messages. Look at the laravel documentation they show how to namespace that. 

Example you can call `trans(yourmodule::key)`.

**Comment by tsunamilx** [comment]
Hi

In lang/[lang]/validation.php, Laravel has "attributes" to customize the display name of the attributes, if I define "attributes" in the module lang/[lang]/validation.php, it doesn't seem to work.

**Comment by fndmiranda** [comment]
I also need to do as @tsunamilx said, set the attribluto name in the lang file of the module but it is not working like that.
