### ISSUE TITLE
Having issue with pest and datasets: A dataset with the name `emails` does not exist.

### ISSUE THREAD

**Issue by kossa** [nWidart/laravel-modules#1480]
Hello,

I want to use shared datasets, I create `Datasets` under `Modules/Order/Tests/Datasets/Products.php`, when I add with('products') I got this error: `A dataset with the name `emails` does not exist.`

Modules/Order/Tests/Feature/OrderTest.php:
```
test('Just test', function ($email) {
    dump($email);
})->with('emails');
```

Modules/Order/Tests/Datasets/Emails.php:
```
<?php

dataset('emails', [
    'enunomaduro@gmail.com',
    'other@example.com'
]);

```

**Comment by dcblogdev** [comment]
This is due to pest not reading from namespaces, I think you may be able to get this to work using the uses method

something like `uses(Modules\Tests\Datasets\Emails::class);` but would require a namespace adding to the file. This is untested.

**Comment by kossa** [comment]
Thanks

**Comment by jackbaron** [comment]
it not working for me
