### ISSUE TITLE
Since symfony/console 6.1: Relying on the static property "$defaultName" for setting a command name is deprecated

### ISSUE THREAD

**Issue by kmizzi** [nWidart/laravel-modules#1482]
Full message:
Since symfony/console 6.1: Relying on the static property "$defaultName" for setting a command name is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "Nwidart\Modules\Commands\ModelShowCommand" class instead

**Comment by dcblogdev** [comment]
this would be a good PR if you would like to open one.

**Comment by max-kut** [comment]
Please copy this patch for v9. Or create 9.0 branch and i create pull-request
