### ISSUE TITLE
Class "Modules\Product\Providers\ProductServiceProvider" not found

### ISSUE THREAD

**Issue by imzainmalik** [nWidart/laravel-modules#1484]
Error while creating new module "Blog" first after installing module package i make Product module then i make another module with name of blog this error appears.

 at ~project-folder\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:208
    204▕      * @return \Illuminate\Support\ServiceProvider
    205▕      */
    206▕     public function createProvider($provider)
    207▕     {
  ➜ 208▕         return new $provider($this->app);
    209▕     }
    210▕ }
    211▕

  1   ~project-folder\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:144
      Illuminate\Foundation\ProviderRepository::createProvider("Modules\Product\Providers\ProductServiceProvider")

  2   ~project-folder\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:61
      Illuminate\Foundation\ProviderRepository::compileManifest()

**Comment by dcblogdev** [comment]
can you try doing a `composer update` and deleting the module you may need to remove it from `module_statuses.json` and re-generate the module.
