### ISSUE TITLE
Route and cache weird behaviour

### ISSUE THREAD

**Issue by Ashk2a** [nWidart/laravel-modules#1485]
**Versions :**
PHP : 8.1.10
Laravel : 9.30.1
Package : 9.0.5

Hello, my routes are not same between a `php artisan optimize:clear` and `php artisan optimize`

`php artisan route:list` (with clear)
- GET|HEAD : users/{user} users.show › Modules\User\Http\Controllers\UserController@show  
- PUT|PATCH : users/{user} users.update › Modules\User\Http\Controllers\UserController@update  
- GET|HEAD : api.abc.local/users/{user} users.show › Modules\User\Http\Controllers\UserController@show  
- PUT|PATCH : api.abc.local/users/{user} users.update › Modules\User\Http\Controllers\UserController@update  

`php artisan route:list` (without cache)
- GET|HEAD : api.abc.local/users/{user} users.show › Modules\User\Http\Controllers\UserController@show  
- PUT|PATCH : api.abc.local/users/{user} users.update › Modules\User\Http\Controllers\UserController@update

When I clear route cache all routes are declared several time like examples, is this issus known ? A possible solution ?

PS : this behaviour happen when `bootstrap/cache/routes-v7.php` is missing

Thank you a lot !

**Comment by adrien-zenchef** [comment]
Ok I found the problem.... It's not concern directly laravel modules !
I put wrong path in auto discovery with `spatie/laravel-settings` and it parsed all my modules directory and run all files...

This issue can be close
