### ISSUE TITLE
Class "Illuminate\Foundation\Console\ShowModelCommand" not found

### ISSUE THREAD

**Issue by tristanantazo** [nWidart/laravel-modules#1486]
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error 

  Class "Illuminate\Foundation\Console\ShowModelCommand" not found

  at vendor/nwidart/laravel-modules/src/Commands/ModelShowCommand.php:7
      3▕ namespace Nwidart\Modules\Commands;
      4▕ 
      5▕ use Illuminate\Foundation\Console\ShowModelCommand;
      6▕ 
  ➜   7▕ class ModelShowCommand extends ShowModelCommand
      8▕ {
      9▕ 
     10▕ 
     11▕     /**

      +2 vendor frames 
  3   [internal]:0
      Composer\Autoload\ClassLoader::loadClass("Nwidart\Modules\Commands\ModelShowCommand")

      +12 vendor frames 
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by adaptpatrick** [comment]
I'm getting this too 👀

**Comment by dcblogdev** [comment]
What version of Larave / Package are you using? I've tried installing Laravel 8 and 9  but haven't been able to replicate this.

**Comment by tristanantazo** [comment]
I'm using Laravel 8.75

**Comment by dcblogdev** [comment]
I'm not sure why `ModelShowCommand` is being triggered on my install of Laravel `8.83.25` the command doesn't exist since Laravel 9. Upgrading to Laravel 9 would solve this, in the meantime I wonder if republishing the config will correct the problem.

**Comment by tristanantazo** [comment]
It's already fixed now, I tried to reinstall the laravel modules using 8.0 version, maybe that the issue I use the laravel 8.75 and it is not compatible with the  laravel module 9.0

**Comment by TonnyORG** [comment]
This is still an on-going issue, it happens on Laravel 9.x apps
