### ISSUE TITLE
Vite support not documented well

### ISSUE THREAD

**Issue by Hussam92** [nWidart/laravel-modules#1487]
The support for vite is not documented (maybe even not implemented) well enough. I can't publish assets from Modules anymore. Also the version for Vite support is just a minor version??? It should be a major or intermediate new version. 9.1.0 maybe.

Thank you

**Comment by wikigods** [comment]
Good, what commands have you run vite, remember what files should be configured if you used bootstrap (sass) or tailwind, you should configure also if you use vue, react, etc. @Hussam92

**Comment by anburocky3** [comment]
Yes, having an switch like `webpack` and `vite` would be helpful. If the users are using vite, the documentation should hide the webpack stuffs and show only vite related stuffs. That would be cool.

**Comment by dcblogdev** [comment]
its not yet been documented at all, as soon as we've got a good solution I'll update the docs.

**Comment by anburocky3** [comment]
Its still not documented good. Why is this issue closed?
