### ISSUE TITLE
Feedback for new documentation

### ISSUE THREAD

**Issue by webreinvent** [nWidart/laravel-modules#149]
Guys,

Thanks for creating new documentations, but I really miss one thing from the previous documentation. There was complete line of code for every command like ```php artisan module:migrate blog```. It was very helpful in copy & paste, change one parameter and done. Very quick and easy.

Consider it if it makes sense. 

Thanks

**Comment by nWidart** [comment]
Hello,

Thanks for the feedback. I will add back a module name as an example argument asap.

**Comment by nWidart** [comment]
I added those back. https://nwidart.com/laravel-modules/v1/advanced-tools/artisan-commands

**Comment by webreinvent** [comment]
Made few changes https://github.com/nWidart/nwidart-docs/compare/master...webreinvent:patch-1

**Comment by nWidart** [comment]
Wasn't this what you requested ?

**Comment by webreinvent** [comment]
look at https://vgy.me/nPAEGg.png you'll get it

**Comment by nWidart** [comment]
Those are now here: https://nwidart.com/laravel-modules/v1/basic-usage/creating-a-module

**Comment by nWidart** [comment]
Feel free to send a pull request to the docs if I missed some 👍

**Comment by nWidart** [comment]
I added the `php artisan` suffix to all commands.
