### ISSUE TITLE
 file_get_contents(/Commands/stubs/webpack.stub): Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by MaticSulc** [nWidart/laravel-modules#1491]
After updating my existing project to the latest laravel modules version, this error keeps appearing.

` file_get_contents(*project path here*/../Commands/stubs/webpack.stub): Failed to open stream: No such file or directory`

I'm not sure what keeps referencing the old stub that was deleted - do you have any idea what I should look at @wikigods ?

**Comment by dcblogdev** [comment]
it will be in your config file

<img width="918" alt="CleanShot 2022-11-04 at 08 54 27@2x" src="https://user-images.githubusercontent.com/1018170/199932339-0accf5de-eee8-4a10-b8d8-6e2d82defd65.png">

deleting webpack from here will sort it.

**Comment by MaticSulc** [comment]
Thanks, this worked like a charm.
Another thing, I'm guessing I have to make some other changes for tailwind to work?
This is the generated layout in the module. In main app.js I just import tailwind from the app.css file.

`<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Module Worldline</title>

       {{-- Laravel Vite - CSS File --}}
       {{-- {{ module_vite('build-projectname', 'Resources/assets/sass/app.scss') }} --}}

    </head>
    <body>
        @yield('content')

        {{-- Laravel Vite - JS File --}}
        {{-- {{ module_vite('build-projectname', 'Resources/assets/js/app.js') }} --}}
    </body>
</html>
`

**Comment by MaticSulc** [comment]
Another issue appeared for me. It seems like tailwind generates only the CSS, which was used in the main components.
Fixed that by adding `'./Modules/**/Resources/Pages/*.vue',` to the tailwind.config.js file.
