### ISSUE TITLE
Is it possible to have different database for each module?

### ISSUE THREAD

**Issue by joandreiy** [nWidart/laravel-modules#1492]
I have 2 modules. **App1, App2**.

Is it possible to define the default connection for different databases in each module?

  - App1 module `'default' => env('DB_CONNECTION', 'App1')`
  - App2 module `'default' => env('DB_CONNECTION', 'App2')`

similar to how there is **config/database.php** so that when you run **module:migrate App1** only the migration in module App1 with the App1 database works?

There is a **Config/config.php** folder inside each module, is it possible to configure there? and How do you do?

**Comment by wikigods** [comment]
yes I think it could to some extent, try this if it is a solution to what you are looking for (I am not 100% sure),
1. Once configured in the Config/config.php folder of your module.
2. Publish it in laravel config, this is just an example of the possible path config/ModuloCustom/config.php.
3. Then add this in your migration (remember this is just an idea, don't forget to do the necessary configurations)
`Schema::connection(config('module.app1'))->create('users', function (Blueprint $table) {
    $table->id();
});`.

If you need help I can help you a little more by looking at the structure of your project, let me know if it worked for you.

**Comment by DeveloperOnCall** [comment]
I'd suggest using the connection setting in the module's Model.

Create the database connection(s) in the ```config/database.php``` file  or within the module's ```config.php``` file.

```php
'App1' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => false,
            'engine' => 'InnoDB',
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],
```

Then in each of the modules (Model/Entity) classes set the connection according to your requirements. 

```php

class MyModuleEntity extends Model
{

 protected $connection = 'App1';

}
```

**Comment by HashmatWaziri** [comment]
is this feature available ?
