### ISSUE TITLE
Customizing Stub not working

### ISSUE THREAD

**Issue by pkd2989** [nWidart/laravel-modules#1497]
Hi,
I have tried to customized the Stubs located here (generated after 'php artisan stub:publish')
![image](https://user-images.githubusercontent.com/68956997/201309703-aca083da-efd4-4569-8739-ef4f5dbc1b1f.png)

- model.stub
```php
<?php

namespace $NAMESPACE$;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Tags\HasTags;

class $CLASS$ extends Model
{
    use SoftDeletes;
    use HasTags;
    
    protected $guarded = ['status'];    

// For timestamp in Unix format
    public function getDateFormat()
    {
        return 'U';
    }

    protected $casts = [
        'updated_at' => 'datetime:U',
        'created_at' => 'datetime:U',
        'deleted_at' => 'datetime:U',
    ];

}
```

- But on creating a new model with `module:make-model Topic -mc` ,  I am still getting model class from default stub.

```php
<?php

namespace Modules\LMS\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Topic extends Model
{
    use HasFactory;

    protected $fillable = [];
    
    protected static function newFactory()
    {
        return \Modules\LMS\Database\factories\TopicFactory::new();
    }
}
```

> FYI: changing the stub of Laravel (not the modules) is still working fine for me. 

It will be helpful if you can have a check, or is it something to be done that I am missing.

Thanks.

**Comment by dcblogdev** [comment]
have you update the config path?

```
'stubs'    => [
        'enabled'      => false,
        'path'         => base_path().'/vendor/nwidart/laravel-modules/src/Commands/stubs',
```

By default it will use the stubs from the package.

**Comment by pkd2989** [comment]
Hi.
Can you please tell which config path is being referred here?

**Comment by pkd2989** [comment]
Hi.
Founder the vendor config file.

Even after modification something like this.
```php

    'stubs' => [
        'enabled' => true,
        'path' => base_path() . '/stubs/nwidart-stubs',
```
Still the default stubs are being used.

Thanks

**Comment by pkd2989** [comment]
Sorry to bother, it was already in the documentation
https://docs.laravelmodules.com/v9/custom-module-generator

Thanks.
