### ISSUE TITLE
How to publish package configuration files 如何发布包配置文件

### ISSUE THREAD

**Issue by liumenggit** [nWidart/laravel-modules#1499]
例如我在 User 模块下使用了 tymon/jwt-auth 包，需要发布配置，但我该如何发布 User 模块下安装的 jwt-auth 包的配置文件那？
For example, I use the tymon/jwt-auth package under the User module and need to publish the configuration, but how do I publish the configuration file of the jwt-auth package installed under the User module?
`php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\LaravelServiceProvider"`

**Comment by sitation-mike** [comment]
We have also run into this and curious if there is a solution other than manually moving files to the module.

**Comment by dcblogdev** [comment]
I don’t think you can. I think you’re better off leaving vendor published files in their published location
