### ISSUE TITLE
RESTful controllers

### ISSUE THREAD

**Issue by unxp** [nWidart/laravel-modules#15]
From `php artisan help module:make-controller`:

>  Generate new restful controller for the specified module.

Correct me if I'm wrong, but should'nt it generate a controller with full stack of methods (index, create, store, show, edit, update, destroy), like default Laravel generator does and not just one index() method?

Ofcourse, if it would generate all those methods, then additional views are required or some message could be displayed that views are not present. Moreover, generated get() route should be changed to a resource().

Anyway, I think it should either generate all methods (with option to generate plain one), or generator description should be changed.

**Comment by nWidart** [comment]
You are correct that it could generate all the resource route. 

However I won't use the `resource()` helper, as when I profiled it, it is slower than using the 'manual' routes.
You're free to use the resource helper after generation though of course.

Pull requests always welcome.

**Comment by unxp** [comment]
I see. So I think word _restful_ should be removed from the command description so it would not mislead anyone in the future :)

**Comment by nWidart** [comment]
This has been added to the [0.9 release](https://github.com/nWidart/laravel-modules/releases/tag/0.9).

Thank you for the suggestion. :)
