### ISSUE TITLE
webpack.stub, Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by majedqatousa** [nWidart/laravel-modules#1505]
hello ! 
im trying to create new module ,  
after run command its fail on /webpack.mix.js  
`php artisan module:make Course`

`
Generating file C:\Users\SmartWeb\Desktop\smart-edu\Modules/Course/module.json ............................... 2ms DONE
  Generating file C:\Users\SmartWeb\Desktop\smart-edu\Modules/Course/Routes/web.php ............................ 1ms DONE
  Generating file C:\Users\SmartWeb\Desktop\smart-edu\Modules/Course/Routes/api.php ............................ 3ms DONE  
  Generating file C:\Users\SmartWeb\Desktop\smart-edu\Modules/Course/Resources/views/index.blade.php ........... 1ms DONE
  Generating file C:\Users\SmartWeb\Desktop\smart-edu\Modules/Course/Resources/views/layouts/master.blade.php .. 6ms DONE
  Generating file C:\Users\SmartWeb\Desktop\smart-edu\Modules/Course/Config/config.php ......................... 1ms DONE
  Generating file C:\Users\SmartWeb\Desktop\smart-edu\Modules/Course/composer.json ............................. 2ms DONE
  Gener9ating file C:\Users\SmartWeb\Desktop\smart-edu\Modules/Course/Resources/assets/js/app.js ............... 20ms DONE
  Generating file C:\Users\SmartWeb\Desktop\smart-edu\Modules/Course/Resources/assets/sass/app.scss ............ 2ms DONE
  Generating file C:\Users\SmartWeb\Desktop\smart-edu\Modules/Course/webpack.mix.js ............................ 1ms FAIL  

   ErrorException 

  file_get_contents(C:\Users\SmartWeb\Desktop\smart-edu\vendor\nwidart\laravel-modules\src\Support/../Commands/stubs/webpack.stub): Failed to open stream: No such file or directory

  at C:\Users\SmartWeb\Desktop\smart-edu\vendor\nwidart\laravel-modules\src\Support\Stub.php:106
    102▕      * @return mixed|string
    103▕      */
    104▕     public function getContents()
    105▕     {
  ➜ 106▕         $contents = file_get_contents($this->getPath());
    107▕
    108▕         foreach ($this->replaces as $search => $replace) {
    109▕             $contents = str_replace('$' . strtoupper($search) . '$', $replace, $contents);
    110▕         }`

laravel  9 
php 8
 "nwidart/laravel-modules": "^9.0",

**Comment by majedqatousa** [comment]
i tried to do this : 
clear cache . 
`composer update ` 
`composer dump-autoload`
`npm i & npm run dev`

Nothing solved this issue

**Comment by majedqatousa** [comment]
config file 
nwidart/laravel-modules/config/config.php 


`
    'stubs' => [
        'enabled' => false,
        'path' => base_path('vendor/nwidart/laravel-modules/src/Commands/stubs'),
        'files' => [
            'routes/web' => 'Routes/web.php',
            'routes/api' => 'Routes/api.php',
            'views/index' => 'Resources/views/index.blade.php',
            'views/master' => 'Resources/views/layouts/master.blade.php',
            'scaffold/config' => 'Config/config.php',
            'composer' => 'composer.json',
            'assets/js/app' => 'Resources/assets/js/app.js',
            'assets/sass/app' => 'Resources/assets/sass/app.scss',
            'vite' => 'vite.config.js',
            'package' => 'package.json',
        ],
`

**Comment by parastooam** [comment]
I had this problem after updating the Laravel project, so I replaced
  'vite' => 'vite.config.js'
  instead of 
  'webpack' => 'webpack.mix.js'
  and it worked
