### ISSUE TITLE
I want to customize module folders like this

### ISSUE THREAD

**Issue by esameisa** [nWidart/laravel-modules#1506]
When i write `php artisan module:make Post` I want to customize module to be like this:
```
Http
- Controllers
- - Dashboard
- - - PostController.php
- - Api
- - - PostController.php
```

**how can i make it?**

**Comment by wikigods** [comment]
I think you should run it like this:
`php artisan module:make-controller Dashboard/PostController Post`
`php artisan module:make-controller Api/PostController Post`

**Comment by dcblogdev** [comment]
you may be better off using a generator https://github.com/dcblogdev/laravel-module-generator this allows you to create a base structure for your modules.
