### ISSUE TITLE
While using Laravel 9.5.1 Facing following errors

### ISSUE THREAD

**Issue by anupamsahoo** [nWidart/laravel-modules#1507]
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/1630888/208595343-0117b64d-2aff-4b14-88e0-1f3bdb476299.png">

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/1630888/208595455-c9a8ae0a-e7ca-4956-aee9-333ed4591057.png">

**Comment by alissn** [comment]
Hi @anupamsahoo ,

the showModelCommand added to Laravel  in version 9.21 in this PR: [[9.x] Artisan model:show command](https://github.com/laravel/framework/pull/43156) 

you should update your laravel version, or downgrade version nWidart/laravel-modules to [9.0.4](https://github.com/nWidart/laravel-modules/releases/tag/v9.0.4)
