### ISSUE TITLE
[Feature request] Nova support

### ISSUE THREAD

**Issue by JanKrb** [nWidart/laravel-modules#1509]
It would be great implementing a support for Laravel Nova.

**Comment by dcblogdev** [comment]
Can you elaborate I've never used Nova, what support are you looking for?

**Comment by shubhamchugh** [comment]
like creating resources for nova

Like this commands: 
php artisan nova:dashboard UserInsights
php artisan nova:card acme/analytics

**Comment by dcblogdev** [comment]
no, I think support for third-party packages would better come from dedicated packages that can be installed for anyone who uses those packages.
