### ISSUE TITLE
How to reference css / js files using this package

### ISSUE THREAD

**Issue by alishanvr** [nWidart/laravel-modules#151]
Hi,

I am trying to reference css/js files by using `Module::asset('blog:img/logo.img');` but it is giving me NotFoundException, Please elaborate how can I reference css / js files from Module.

Thank You,

**Comment by armababy** [comment]
Did you publish your assets before using them?

**Comment by alishanvr** [comment]
I read all documentation and did not found how I can publish assets ? Please guide.

thank you,

**Comment by armababy** [comment]
The new documentation seems to miss this one, but it's `php artisan module:publish Blog`, and you can see any other commands with `php artisan | grep module`

**Comment by alishanvr** [comment]
Thankyou. 
It solves my issue. 

Solution:

1) I put my css file in Modules/Users/Assets/test.css (Users is modules name)
2) I attached my css file by using  `<link rel="stylesheet" href="{{Module::asset('users:test.css')}}">`
Read More: [https://nwidart.com/laravel-modules/v1/advanced-tools/facade-methods] 
3) I use php `artisan module:publish Users ` command
4) Refresh Page.


Thank You @armababy
