### ISSUE TITLE
Multi tenant support 

### ISSUE THREAD

**Issue by satis-apex** [nWidart/laravel-modules#1511]
Is it possible to create a module.json for multiple tenant, so i can enable a module for one tenant and disable for other.

Modules enable/disable check from database might be one solution.

Please suggest.

**Comment by satis-apex** [comment]
modules_status.json file with following 
{
    "MenuLink": true,
    "User": true,
    "AppSetting": true,
    "UserRole": true,
    "DataTable": false,
    "Staff": true
} 

if i was unclear on the above comment. can we load this  from database 
or another solution might also be accessing it from session variable

**Comment by dcblogdev** [comment]
that's beyond the scope of what this package provides out of the box. But in theory yes you can load the module's statuses from a database instead of the file, have a search through the issues I think the database setup has been talked about a few times.

I'll see if I can get some examples later.

**Comment by satis-apex** [comment]
i found the branch in the repo which is quite old but with few changes i was able to work it out
