### ISSUE TITLE
One question why don't you update RouteServiceProvider modules? 

### ISSUE THREAD

**Issue by wikigods** [nWidart/laravel-modules#1512]
Hi been testing and this works.
1. `protected $moduleNamespace = 'Modules\Blog\Http\Controllers';` replace `//protected $namespace = 'Modules\Base\Http\Controllers';` (must be commented).
2.  Remove all previous code just leave boot function. (add the following code shown in the image)
![Screenshot_18](https://user-images.githubusercontent.com/71094046/209876741-29516b63-ee8d-4ee5-a773-4d9dcd96daa6.png)
 3. final result .
![Screenshot_19](https://user-images.githubusercontent.com/71094046/209876997-38a349eb-364a-471e-80ff-ed60225369ae.png)
@dcblogdev what do you think

**Comment by dcblogdev** [comment]
you know that saying if it ain't broke 🤣

Looks like it should be fine, do you want to submit a PR?

**Comment by wikigods** [comment]
I am going to work on it (PR), but I have some doubts I have been reviewing test are not working correctly instead of writing it down I am going to list it.
1. phpunit.xml.dist (I get obsolete notification) [Any suggestions]. 
2. Errors in test classes in example files with screenshots.
![Screenshot_20](https://user-images.githubusercontent.com/71094046/210012453-535e118d-fc16-4a5d-a97e-8f1d91a2cf3b.png)

4. There are some functions that are not covered with test.
5. This is a mistake on my part (I fixed it, but it's a big range, it would be good to include it in PR?)
[
Radical changes:
1. phpunit.xml.dist 9.5 (logging not support attached picture)
![Screenshot_21](https://user-images.githubusercontent.com/71094046/210012664-b64d65c3-9716-421d-a453-9873a7a710ff.png)

]
sorry my english is not very good. @dcblogdev

**Comment by dcblogdev** [comment]
sorry I haven't replied sooner, not sure if this is something you are working on?
