### ISSUE TITLE
How to use policies

### ISSUE THREAD

**Issue by MehrshadBaradaran** [nWidart/laravel-modules#1516]
Hello
I'm trying to write and use a policy inside a module controller($this->authorize() method)
no matter what I do it just doesn't work
I tried to register my policy in a different provider  (which extends from Illuminate\Foundation\Support\Providers\AuthServiceProvider )
but it doesn't work

please help me

thank you

**Comment by dcblogdev** [comment]
does this thread explain it for you?

https://github.com/nWidart/laravel-modules/issues/16

**Comment by ee12ee** [comment]
> Hello I'm trying to write and use a policy inside a module controller($this->authorize() method) no matter what I do it just doesn't work I tried to register my policy in a different provider (which extends from Illuminate\Foundation\Support\Providers\AuthServiceProvider ) but it doesn't work
> 
> please help me
> 
> thank you

same problem
