### ISSUE TITLE
The package used inside the module is loaded in the wrong order

### ISSUE THREAD

**Issue by pavelforever** [nWidart/laravel-modules#1519]
Hello! I'm trying to use my own package inside a module, but composer install things the way module is loaded first and then the package. Thus, I can't use the package inside the module.
How can I make it so that the package is loaded first and then the module?

What I did: being inside the module folder, I installed the package through the composer (`composer require me/myPackage:dev-master`). Then I went to root folder of the project and ran `php artisan module:update myModule`. 
When I tried to use a package inside a module, laravel would give an error that there was no such class. I changed the order in bootstrap/cache/services.php and bootstrap/cache/packages.php and then everything started working, but that's not the solution
It is also worth mentioning that laravel's facade is used inside the package, and since the resources of the package are not loaded when the module tries to use it, an error occurs.

**Comment by pavelforever** [comment]
It turned out that for me it is not critical which package is loaded first. The problem turned out to be that I was executing code in my custom function file, which was loaded in module.json via the 'files' section. This code is loaded when all packages are initialized, so that's not where I should have checked my code. Instead, I should have checked it anywhere in the normal thread (when all packages are already loaded) - in controllers, for example.

**Comment by nWidart** [comment]
Hello,

Indeed, maybe even in a service provider, depending on what your logic does it might not fit in a controller :)
