### ISSUE TITLE
function down() of migration not working when another connection

### ISSUE THREAD

**Issue by ejimenez123** [nWidart/laravel-modules#1520]
Hi Nicolas !!

I'm using  `laravel/framework: "^9.19"` and `nwidart/laravel-modules: "^9.0"`, then...

When I run the migrations, the `down()` function is not executed. In other words, it is completely ignored. I guess it has something to do with why I'm using another connection.

For example:

```
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateFoodsTable extends Migration
{

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::connection('pgsql_other_connection')->create('foods', function (Blueprint $table) {
            // omitted for brevity ...
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down() // THIS FUNCTION IS NOT EXECUTED WHEN I RUN THE MIGRATIONS
    {
        Schema::connection('pgsql_other_connection')->dropIfExists('foods');
    }
}
```
It gives me the error: `SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "foods" already exists`

I solved it like this, for now, in a not very elegant way and I hope I don't have problems in the future.

```
     // omitted for brevity ...
    public function up()
    {
        Schema::connection('pgsql_other_connection')->dropIfExists('foods');
        Schema::connection('pgsql_other_connection')->create('foods', function (Blueprint $table) {
           // omitted for brevity ...
        });
    }
    // omitted for brevity ...
```

As you see, I put everything in the `up()` function and it worked for me.

Please, I appreciate your comment...

Thanks !!

**Comment by lamtranb** [comment]
This issue is not related to this package.

In the down() function, I think you should replace **pgsql_common** with **pgsql_other_connection**

`Schema::connection('pgsql_other_connection')->dropIfExists('foods')`

**Comment by ejimenez123** [comment]
Sorry @lamtranb, I already made the correction in the issue above. I have it with `Schema::connection('pgsql_common')->dropIfExists('foods')` because that is what the connection is called in my code. I didn't realize it at the time of writing this issue.

But equally, it never enters the `down()` function. I even put a `dd()` to stop the process and it never goes through.

Before it worked for me when it was a single connection. But now that there are two, it only does the `up()`.

Thanks for answering !!

**Comment by dcblogdev** [comment]
Down is getting called for me.

I've created this migration:

```php
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('demo', function (Blueprint $table) {
            $table->id();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        dd('called');
        Schema::dropIfExists('demo');
    }
};

```

Calling `module:migrate-rollback Demo` I see `called`

**Comment by dcblogdev** [comment]
I think this is a Laravel issue rather then package directly. Running migrations will use the default connection. If you specify a connection that may work

```bash
php artisan module:migrate-rollback --database=test
```

**Comment by ejimenez123** [comment]
I repeat, Laravel migrations work fine for me, both with `up()` and `down()`. But I had never tried it before with different connections to the DB, except now that I am modularizing my application. It may be what you say, I should try it....

Thank !!
