### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by beeyev** [nWidart/laravel-modules#1521]
Firstly, thank you so much for the great package, I have been using it for quite a long, and it's absolutely great.

I have a question, since Laravel 10 will be released very soon, on February 7th. Will this package support the new Laravel version?

**Comment by dcblogdev** [comment]
Thanks for the support.

Yes, it will be updated for Laravel 10

**Comment by beeyev** [comment]
Up

**Comment by o2b3k** [comment]
up

**Comment by CallMeNegar** [comment]
up

**Comment by HamasakiBrain** [comment]
up
