### ISSUE TITLE
create config/app

### ISSUE THREAD

**Issue by aroon9002ahmed** [nWidart/laravel-modules#1522]
how i can create *ModulesName*/config/app.php to add my custom code for module?

i have custoum code in my main app.php

```
//Slider
    'SLIDER_IMAGES_SIZE_MSG'  =>  'Allowed files .jpg 1250x450 file size up to 5MB', //image size message
    'SLIDER_IMAGES_PATH'  =>  'sliders',
    'SLIDER_IMAGES_SIZE_WEIGHT'  =>  '1250', //image weight
    'SLIDER_IMAGES_SIZE_HEIGHT'  =>  '450', //image height
```

my question is simple way : how to access module config.php data in module controller?

**Comment by dcblogdev** [comment]
you can reference the config options of a module like:

```php
config('module.property')
```
