### ISSUE TITLE
Missed webpack.stub

### ISSUE THREAD

**Issue by Aido21** [nWidart/laravel-modules#1523]
`php artisan module:make generates an error:`

 Generating file Modules/AccountsPayable/webpack.mix.js .................... 4ms FAIL

In Stub.php line 106:
                                                                                                                                                  `file_get_contents(/Applications/MAMP/htdocs/myproject/vendor/nwidart/laravel-modules/src/Support/../Commands/stubs/webpack.stub): Failed to open stream: No such file or directory `

**Comment by OmarKadish** [comment]
I had the same problem, but when I deleted the webpack from config/modules.php file as suggested in this issue https://github.com/nWidart/laravel-modules/issues/1505  the problem was solved.

**Comment by Aido21** [comment]
With this solution, you disable the webpack installation. 
I am not so good in Laravel so I have a question will everything work correctly without webpack?

**Comment by wikigods** [comment]
do not change anything or delete anything just backup config/modules (keep it in a safe place, for reference) now run config/modules again to get the latest configuration changes;

**Comment by Aido21** [comment]
it does not help

**Comment by wikigods** [comment]
Yes, sorry, I made a little mistake, after doing your backup delete the modules file from config folder, regenerate it again with the above command. now new config file should be using vite "Remember the default vite environment comes empty" implement any one you like like like tailwind, bootstrap 5 or any other. [excuse my english]
