### ISSUE TITLE
Proposal how to manage the asset ['vite' or webpack].

### ISSUE THREAD

**Issue by wikigods** [nWidart/laravel-modules#1524]
Proposal 1
Add configuration modules  
`'compiler' => [
  'type' => vite o webpack,
  'laravel' => false,
]`
Proposal 2
Add comand 
`php artisan module:make-assets Blog webpack o vite [-w o -v] laravel [-l]`
I explain a little more command 
`php artisan module:make-assets Blog webpack laravel`
It generates webpack in Blog module if you pass laravel you indicate that you will use main compiler that brings laravel
If you do not want to write everything you can use short letters 
`[-w o -v] [-l]`

Now the most important thing for me would be if when you generate asset it is clean or if it comes preinstalled "but if we use that there would be debate if it comes tailwind or bootrsrap", I am more fan of bootstrap :) . but I would like it to come clean.
 
Changes or suggestions I would start working when laravel 10 version is released, as I am a little busy with work. (sorry for my English)

@dcblogdev

**Comment by dcblogdev** [comment]
I'm not sure I understand, can you try explaining these options?

**Comment by dcblogdev** [comment]
I'd like to have a solution in place before I do a v10 major release. Laravel 10 is due to be released tomorrow. 

I feat doing a release now will cause a lot of confusion for anyone needing a built system.
