### ISSUE TITLE
  Class "Modules\ModuleName\Providers\ModuleNameServiceProvider" not found

### ISSUE THREAD

**Issue by CookieMC337** [nWidart/laravel-modules#1527]
If there are already modules, I cannot create any more and I get this error. 
![Screenshot 2023-01-29 220734](https://user-images.githubusercontent.com/51511368/215355706-7ebcfc04-f530-4cbc-84d5-fe9cac4733a9.png)
![Screenshot 2023-01-29 220839](https://user-images.githubusercontent.com/51511368/215355747-8a90a1c9-44cc-4f4c-b1ce-0fc5f10241cf.png)

**Comment by Verstand** [comment]
![image](https://user-images.githubusercontent.com/3618249/215635404-e0550653-5405-4c9d-811c-1de763dc0869.png)

Add module loading to composer.json

**Comment by Verstand** [comment]
> If there are already modules, I cannot create any more and I get this error. ![Screenshot 2023-01-29 220734](https://user-images.githubusercontent.com/51511368/215355706-7ebcfc04-f530-4cbc-84d5-fe9cac4733a9.png) ![Screenshot 2023-01-29 220839](https://user-images.githubusercontent.com/51511368/215355747-8a90a1c9-44cc-4f4c-b1ce-0fc5f10241cf.png)
![image](https://user-images.githubusercontent.com/3618249/215635698-d12f356a-aa06-46b0-9d03-6847f041d009.png)

Add module loading to composer.json

**Comment by CookieMC337** [comment]
I have already done that. However, it does not find the files, which is why I can no longer add modules.

**Comment by LukasFreyCZ** [comment]
I have the same issue. A fresh installation of laravel with a fresh installation of laravel-modules. After you add the first module, the whole package seems to stop working as it for some reason can't find the service provider itself created.

**Comment by dcblogdev** [comment]
This appears to be an operating system issue, looking at these search results I see lots of issues about this that often is referring to 

https://www.google.com/search?q=openssl+is+already+loaded&rlz=1C5CHFA_enGB1034GB1034&sxsrf=AJOqlzVsbRVb23FImYBKhFVBg3kvZPpjjQ%3A1675637772119&ei=DDTgY_nyBpCG8gLu8b74BQ&ved=0ahUKEwj5qLeRvf_8AhUQg1wKHe64D18Q4dUDCBA&uact=5&oq=openssl+is+already+loaded&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIECCMQJzIGCAAQBRAeMgYIABAFEB4yBQgAEIYDMgUIABCGAzIFCAAQhgMyBQgAEIYDOgoIABBHENYEELADOgcIIxCwAhAnOggIABAFEAcQHkoECEEYAEoECEYYAFCuBFjgBWCnB2gBcAF4AIABSYgBhwGSAQEymAEAoAEByAEIwAEB&sclient=gws-wiz-serp

if you're using exampp this may apply:

You need to open Xammp folder/php/php.ini and Cntr+F and find extension=php_openssl.dll and uncomment it.

```
;extension=php_openssl.dll
```

I'm closing this as its not package caused.

**Comment by CookieMC337** [comment]
Hi, the OpenSSL error can be ignored. Below that the error comes from the module / Artisan. The first time I use it, I can create modules. However, as soon as modules are already present comes the error in which it is said that the ServiceProvider of the module can not be found.

**Comment by dcblogdev** [comment]
what version are you using, I've tried to replicate this using Laravel `9.50.2` and package `9.0.6` 

<img width="893" alt="CleanShot 2023-02-05 at 23 09 59@2x" src="https://user-images.githubusercontent.com/1018170/216851296-9acb4e40-f4a1-487e-a528-43969d356be3.png">

I've created 4 modules, without seeing errors.

Also listing them is working 

<img width="1360" alt="CleanShot 2023-02-05 at 23 10 50@2x" src="https://user-images.githubusercontent.com/1018170/216851328-f40e6e17-e32b-4d39-b91c-a7de2cd24188.png">

**Comment by CookieMC337** [comment]
@dcblogdev i´m using Laravel v9.48.0 (PHP v8.1.14) with Package version 9.0.6

**Comment by CookieMC337** [comment]
https://s3.eu-central-003.backblazeb2.com/cookiesharex/ShareX/2023/02/phpstorm64_xvWKJEYKEJ.gif

**Comment by LukasFreyCZ** [comment]
@CookieMC337 Did you run `composer dump-autoload` afterwards? That fixed the issue for me.

**Comment by CookieMC337** [comment]
@LukasFreyCZ cannot execute the command 

![phpstorm64_YmfEGu5hma](https://user-images.githubusercontent.com/51511368/216954713-5a32f07d-3df9-484c-bbc2-c2edc839a039.png)

**Comment by LukasFreyCZ** [comment]
> @LukasFreyCZ cannot execute the command
> 
> ![phpstorm64_YmfEGu5hma](https://user-images.githubusercontent.com/51511368/216954713-5a32f07d-3df9-484c-bbc2-c2edc839a039.png)

Can you run the command again and check your laravel.log file and paste it here?

**Comment by CookieMC337** [comment]
[laravel.log](https://github.com/nWidart/laravel-modules/files/10687617/laravel.log)
@LukasFreyCZ

**Comment by LukasFreyCZ** [comment]
> [laravel.log](https://github.com/nWidart/laravel-modules/files/10687617/laravel.log)
> @LukasFreyCZ

I've had issues with this too, I just don't remember how I fixed it. It was something small and stupid though.

Check your config/app.php whether you don't try to register a provider that doesn't exist or something.

**Comment by CookieMC337** [comment]
@LukasFreyCZ If this is a path problem in the sense it would make sense that it works under MacOS and Linux but not under Windows. I'll set up a Linux environment and test it again.
