### ISSUE TITLE
How i run a command that i have create with module:make-command TestCommand Test?

### ISSUE THREAD

**Issue by vise92** [nWidart/laravel-modules#1528]
I have create a command with the command:
php artisan module:make-command TestCommand Test
But when i wirte php artisan, the command that i have created before didn't exixts in the list of command.

How is possible?

**Comment by dcblogdev** [comment]
You'll need to register the command in the module service provider inside the boot method.

```php
$this->commands([
    \Modules\Test\Console\TestCommand::class,
]);
```

I like to create its own method

```php
public function boot()
{
 $this->registerCommands();
}
```

the method:

```php
protected function registerCommands()
{
    // Add your paths to the module commands like the example below
    $this->commands([
        \Modules\Test\Console\TestCommand::class
    ]);
}
```


If you need to run a schedule then inside the boot:

```php
$this->app->booted(function () {
    $schedule = $this->app->make(Schedule::class);
    $schedule->command('test:run-test')->everyMinute();
});
```

**Comment by dcblogdev** [comment]
I've updated the docs to make this clearer https://docs.laravelmodules.com/v9/module-console-commands
