### ISSUE TITLE
Target class [cache] does not exist.

### ISSUE THREAD

**Issue by LukasFreyCZ** [nWidart/laravel-modules#1529]
When installing the package `filament-modules` (https://github.com/savannabits/filament-modules)
inside that plugin's config for this line
`'path' => module_path($moduleName, "$contextPath/Pages"),`

it shows the following error:

```
   Illuminate\Contracts\Container\BindingResolutionException 

  Target class [cache] does not exist.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:891
    887▕ 
    888▕         try {
    889▕             $reflector = new ReflectionClass($concrete);
    890▕         } catch (ReflectionException $e) {
  ➜ 891▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    892▕         }
    893▕ 
    894▕         // If the type is not instantiable, the developer is attempting to resolve
    895▕         // an abstract type such as an Interface or Abstract Class and there is

  1   [internal]:0
      Nwidart\Modules\FileRepository::__construct(Object(Illuminate\Foundation\Application))

      +8 vendor frames 
  10  [internal]:0
      Nwidart\Modules\FileRepository::__construct(Object(Illuminate\Foundation\Application))
```

It seems like it's more of a laravel-modules issue than an error with the other package itself.

**Comment by javierhstr** [comment]
Hi, any solution to the problem?

**Comment by LukasFreyCZ** [comment]
> 

You can temporarily fix it by replacing all `module_path` calls with a `base_path` call. The error is somewhere inside the module_path function.

**Comment by javierhstr** [comment]
yes, I had already tried it, but I thought it could be something else. thanks!

**Comment by leek** [comment]
Would love to see a fix for this...

**Comment by RealMrHex** [comment]
Any solution?

**Comment by mstfkhazaal** [comment]
any solutions?

**Comment by hoangnamitc** [comment]
How to fix it?

<img width="478" alt="image" src="https://github.com/nWidart/laravel-modules/assets/7042462/2cbadd1d-b486-4276-b708-f98aa2722bdb">

**Comment by siadress** [comment]
any solutions?

**Comment by 27nisha** [comment]
Target class [cache] does not exist. while trying to implement the         "rap2hpoutre/laravel-log-viewer": "^2.5".

managed in config/app.php

![Image](https://github.com/user-attachments/assets/4c01af40-59a4-45f6-a7e5-ee1bb8fbda7d)

![Image](https://github.com/user-attachments/assets/0e0d0021-1751-49ba-bc86-051f9588a1cb)
