### ISSUE TITLE
[Enhacement]: Specify Subdirectories in migrate command

### ISSUE THREAD

**Issue by Fagl4** [nWidart/laravel-modules#153]
I am currently working in a multi database project, various databases can have different migrations from the same module, currently we store migrations in subdirectories, so we would like to be possible to specify subdirectories in the migrate command so only the migrations from that subdirectory are run

For example:
`php artisan module:migrate --subdir="test" Module`  run the migrations in `module/database/migrations/test` folder

**Comment by nWidart** [comment]
Hello,

Thank you for the suggestion, however this looks like a fairly custom requirement.
I'd suggest you to make a command custom to your project which allows this.

**Comment by nWidart** [comment]
I see you forked the repository making this work. It's simpler than what I thought it'd be, PR welcome. 👍

**Comment by Fagl4** [comment]
As soon as i have some free time i will send a PR, cheers
