### ISSUE TITLE
Support for laravel 8

### ISSUE THREAD

**Issue by imhayatunnabi** [nWidart/laravel-modules#1530]
Hello nWidart,
Myself a Laravel Developer who is going to work on a module-based project which will require your laravel-modules package installation. but the problem is your package does not have any support for laravel 8. when i am trying to install this package in laravel 8 project which is full stack then i get this sort of error from the image. will be able to solve this or bring support for laravel 8 ?
Laravel version : 8.75
Php version : 7.3|8.0
![Screenshot from 2023-02-06 13-21-45](https://user-images.githubusercontent.com/44812376/216926593-2dbad34b-6c90-4a7f-91e0-f3e6ebc18335.png)

**Comment by dcblogdev** [comment]
looks like you've installed version 9 of the package, you'll need to use version 8

```json
"nwidart/laravel-modules": "^8.3"
```

**Comment by imhayatunnabi** [comment]
Okay thank you
