### ISSUE TITLE
How to run Schedule with Stancl/tenancy

### ISSUE THREAD

**Issue by KatiaSishost** [nWidart/laravel-modules#1537]
I have a Mini ERP system that I am using with stancl/tenancy to have the same ERP for my 3 departments... now add a module that activates some "notes" a kind of internal blog...

The problem is the following:

How can I make them publish on a certain date?

I have the notes table with its fields and a column called publish_at and the status with an enum of published and unpublished

Can someone tell me how to make it work but with stancl/tenancy?

**Comment by dcblogdev** [comment]
I would publish it to the tenants as soon as you create the record but not display until the published_at is in the past

so in a model create a local scope:

```php
public function scopePublished($query)
{
    return $query->where('published_at', '<=', Carbon::now());
}
```

then in queries would could reference the scope:

```php
$notes = Note::published()->paginate();
```

Another way would be to have a command to run every minute and if the date matches then fire off the actions something like:

```php
$tenants = Tenant::all();
$tenants->each(function ($tenant) {
    tenancy()->initialize($tenant);
    //publish the note here
    tenancy()->end();
});
```
