### ISSUE TITLE
Module not correctly generated with custom namespace

### ISSUE THREAD

**Issue by jaumeavila** [nWidart/laravel-modules#154]
Hi!
After changing the namespace and creating a new module via:
php artisan module:make Reservation

The namespaces of the files are correctly set but the folders with the files are created in Modules instead of under the Namespace set.

Thanks!

**Comment by nWidart** [comment]
That's intended, the namespace doesn't set the folder. There is a folder config option for this.

**Comment by jaumeavila** [comment]
Thanks!
My bad.

And congrats! It is a great package!
