### ISSUE TITLE
Laravel-module 8.3 module.json server error

### ISSUE THREAD

**Issue by jessypentdragon** [nWidart/laravel-modules#1540]
When i remove the module.json file it routes to the url but doesnt show anything. when i add the module.json file to the generated module's root folder, I get 500 | server error. I updated to laravel 8. Please any help

**Comment by dcblogdev** [comment]
What error are you gettings?

**Comment by jessypentdragon** [comment]
500 | server error

**Comment by jessypentdragon** [comment]
But when I take the module.json out from the module rook directory my app loads fine

**Comment by jessypentdragon** [comment]
Ok am on it

**Comment by jessypentdragon** [comment]
[laravel-2023-02-25.log](https://github.com/nWidart/laravel-modules/files/10830874/laravel-2023-02-25.log)
That is my log can you give me a clue please

**Comment by dcblogdev** [comment]
You have multiple errors, going from the bottom of the log upwards:

```
[2023-02-25 16:04:49] live.ERROR: Uncaught Symfony\Component\Finder\Exception\DirectoryNotFoundException: The "C:\Ampps\www\hexupdate\custom_views" directory does not exist. in C:\Ampps\www\hexupdate\vendor\symfony\finder\Finder.php:592
```

This cannot find the path "C:\Ampps\www\hexupdate\custom_views"

```
[2023-02-25 16:04:27] live.ERROR: Uncaught ReflectionException: Class App\Policies\ModelPolicy does not exist
```

You must have some code that is looking for a ModelPolicy that it cannot find

```
[previous exception] [object] (Illuminate\\Routing\\Exceptions\\UrlGenerationException(code: 0): Missing required parameter for [Route: manage-modules.destroy] [URI: manage-modules/{manage_module}] [Missing parameter: manage_module]. at C:\\Ampps\\www\\hexupdate\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Exceptions\\UrlGenerationException.php:35)
[stacktrace]
```

You have a named route for manage-modules/destroy but a second param is not being passed to the route manage-modules.destroy

```
[2023-02-25 16:02:58] live.ERROR: Missing required parameter for [Route: manage-modules.destroy] [URI: manage-modules/{manage_module}] [Missing parameter: manage_module]. (View: C:\Ampps\www\hexupdate\resources\views\install\modules\index.blade.php) {"userId":1,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Missing required parameter for [Route: manage-modules.destroy] [URI: manage-modules/{manage_module}] [Missing parameter: manage_module]. (View: C:\\Ampps\\www\\hexupdate\\resources\\views\\install\\modules\\index.blade.php) at C:\\Ampps\\www\\hexupdate\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Exceptions\\UrlGenerationException.php:35)
```

same as above, you need to find where the route manage-modules.destroy is being used and pass a second param to the route call.

**Comment by jessypentdragon** [comment]
Thanks for the details let me try

**Comment by jessypentdragon** [comment]
`<form 
                            action="{{action('Install\ModulesController@destroy', ['module_name' => $module['name']])}}"
                                style="display: inline;" 
                                method="post"
                                onsubmit="return confirm('Do you really want to delete the module? Module code will be deleted but the data will not be deleted')"
                            >
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-danger rounded-5 btn-xs"
                                    @if($is_demo)
                                    disabled="disabled" 
                                    title="@lang('lang_v1.disabled_in_demo')"
                                    @endif
                                >
                                @lang('messages.delete')</button>
                            </form>`
That is the code for module detroy please

**Comment by jessypentdragon** [comment]
When I remove this code the app functions but that part of the app doesn't

**Comment by dcblogdev** [comment]
I recommend using a named route instead of calling a controller like that.

But in any case try this

```php
action="{{ action('Install\ModulesController@destroy', $module['name']) }}"
```

**Comment by jessypentdragon** [comment]
Ok Thanks, thanks that worked. Much appreciated

**Comment by jessypentdragon** [comment]
My name is Jessy Bright what of you

**Comment by dcblogdev** [comment]
Great 👍 

I'm David Carr, nice to meet you.

**Comment by jessypentdragon** [comment]
Same here please
Can we exchange contacts just incase. If you dont mind

**Comment by dcblogdev** [comment]
Sure I have all my socials linked on my website https://dcblog.dev

I'm also pretty active on Twitter https://twitter.com/dcblogdev

**Comment by jessypentdragon** [comment]
Thanks sir

**Comment by jessypentdragon** [comment]
Please @dcblogdev Can you help me with this also
`try {
                $modules[$module]['install_link'] = action('\Modules\\' . $details['name'] . '\Http\Controllers\InstallController@index');
            } catch (\Exception $e) {
                $modules[$module]['install_link'] = "#";
            }`

**Comment by dcblogdev** [comment]
honestly I highly recommend learning about named routes rather then littering actions in your code. 

try

```
action('\Modules\\' . $details['name'] . '\Http\Controllers\InstallController@index', $module['name']);
```

**Comment by jessypentdragon** [comment]
Ok thanks

**Comment by jessypentdragon** [comment]
It rather gives me the catch exeption link thus href="#"
