### ISSUE TITLE
what module:update exactly does?

### ISSUE THREAD

**Issue by giacomok** [nWidart/laravel-modules#1544]
Hi,  
I was wondering about `module:update` command.

I was not able to read in the documentation what this command does.

I added some voices to my `Module/Config.php` file, but after the deploy to another server, these new voices are empty.  
Do I have to execute `php artisan module:update` command?

**Comment by dcblogdev** [comment]
that command updates the module depenencies ie its composer.json 

What do you mean by voices? do you mean add array keys to the config file? in which case are you certain you commited them to GIT? assuming you're using GIT.

**Comment by giacomok** [comment]
Thanks for replay.

About the voices, yes, I was talking about array keys. The problem was I need to reference to the model in lower case.  
It should be added in the docs.

**Comment by dcblogdev** [comment]
okay thanks, I'll add a note in the docs.
