### ISSUE TITLE
Class "Illuminate\Database\Console\ShowModelCommand" not found

### ISSUE THREAD

**Issue by moharrum** [nWidart/laravel-modules#1548]
Hello,

Installing `laravel-modules` on `Laravel 9.52.4`, I get the following error:

```
$ composer require nwidart/laravel-modules
./composer.json has been updated
Running composer update nwidart/laravel-modules
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error 

  Class "Illuminate\Database\Console\ShowModelCommand" not found

  at vendor/nwidart/laravel-modules/src/Commands/ModelShowCommand.php:9
      5▕ use Illuminate\Database\Console\ShowModelCommand;
      6▕ use Symfony\Component\Console\Attribute\AsCommand;
      7▕ 
      8▕ #[AsCommand('module:model-show', 'Show information about an Eloquent model in modules')]
  ➜   9▕ class ModelShowCommand extends ShowModelCommand
     10▕ {
     11▕ 
     12▕ 
     13▕     /**

      +2 vendor frames 
  3   [internal]:0
      Composer\Autoload\ClassLoader::loadClass()

      +7 vendor frames 
  11  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

While inspecting th issue, I found that `\Nwidart\Modules\Commands\ModelShowCommand` uses `Illuminate\Database\Console\ShowModelCommand`, which is not there any more.

See:
https://laravel.com/api/9.x/Illuminate/Database/Console.html

EDIT:
I see now that for version Laravel 9 we should use laravel-modules 9 also, sorry about the mistake.

Best regards,
Khalid Muharam.

**Comment by mcagri33** [comment]
yes, i had same error but i didnt solve

**Comment by mcagri33** [comment]
https://github.com/nWidart/laravel-modules/pull/1545/files   i solved.

**Comment by moharrum** [comment]
I think `composer require "nwidart/laravel-modules":"9.*"` will do, depending on your Laravel version.

**Comment by andreamanini** [comment]
when will this be fixed ? I can't run composer update since using version 9 of this module

**Comment by moharrum** [comment]
Hello @andreamanini 

You need to edit your `composer.json` file, specify the package version compatible with you `Laravel` version.

```php
{
...
    "require": {
...
        "nwidart/laravel-modules": "9.*",
...
    }
...
}
```

**Comment by andreamanini** [comment]
> Hello @andreamanini
> 
> You need to edit your `composer.json` file, specify the package version compatible with your `Laravel` version.
> 
> ```
> {
> ...
>     "require": {
> ...
>         "nwidart/laravel-modules": "9.*",
> ...
>     }
> ...
> }
> ```

this doesn't solve the issue for me actually, I still get the same error regardless

**Comment by mcagri33** [comment]
> > Hello @andreamanini
> > You need to edit your `composer.json` file, specify the package version compatible with your `Laravel` version.
> > ```
> > {
> > ...
> >     "require": {
> > ...
> >         "nwidart/laravel-modules": "9.*",
> > ...
> >     }
> > ...
> > }
> > ```
> 
> this doesn't solve the issue for me actually, I still get the same error regardless

you should do it

https://github.com/nWidart/laravel-modules/pull/1545/files

**Comment by dcblogdev** [comment]
I cannot replicate this issue, when using Laravel 9 ensure you're using version 9 of the package:

```
"require": {
    "laravel/framework": "^9.19",
    "nwidart/laravel-modules": "^9.0"
},
```

For Laravel 10:

```
"require": {
    "laravel/framework": "^10.0",
    "nwidart/laravel-modules": "^10.0"
},
```

**Comment by dcblogdev** [comment]
> when will this be fixed ? I can't run composer update since using version 9 of this module

@andreamanini what versions do you have both the package and laravel in your composer.json file?

**Comment by andreamanini** [comment]
this is what I have in my composer file

`"laravel/framework": "^9.0",
  "nwidart/laravel-modules": "^9.0",`

and this is what I get when I try to run composer update/install

`Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error 

  Class "Illuminate\Database\Console\ShowCommand" not found

  at vendor/nwidart/laravel-modules/src/Commands/ModelShowCommand.php:9
      5▕     use Illuminate\Database\Console\ShowCommand;
      6▕     use Symfony\Component\Console\Attribute\AsCommand;
      7▕ 
      8▕     #[AsCommand('module:model-show', 'Show information about an Eloquent model in modules')]
  ➜   9▕     class ModelShowCommand extends ShowCommand
     10▕     {
     11▕ 
     12▕ 
     13▕         /**

      +2 vendor frames 
  3   [internal]:0
      Composer\Autoload\ClassLoader::loadClass("Nwidart\Modules\Commands\ModelShowCommand")

      +7 vendor frames 
  11  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
`

**Comment by dcblogdev** [comment]
okay can you try changing your version for a minimum of 9.19 `"laravel/framework": "^9.19"` its odd that I'm not getting this I can't replicate this myself

Maybe try deleting vendor and running `composer install`

**Comment by andreamanini** [comment]
> okay can you try changing your version for a minimum of 9.19 `"laravel/framework": "^9.19"` its odd that I'm not getting this I can't replicate this myself
> 
> Maybe try deleting vendor and running `composer install`

yes, I've done that also.. and I can see that composer is trying to download 

`Downloading nwidart/laravel-modules (v9.0.6)`

but that ends up in throwing the same exact error.. 

did you already fix the issue in all the versions of the repo?

**Comment by ctf0** [comment]
this happens on laravel 10 & installing a module that depends on `nwidart/laravel-modules` version 9 which has installed version of `v9.0.6`

so the fix is to update the module composer file to use `*` wild card version for `nwidart/laravel-modules` which will always get you the correct version according to your laravel version.

if u still want to constraint the version of laravel, you can add `"laravel/framework": "^9.0 || ^10.0",` to your module composer json file

**Comment by andreamanini** [comment]
> 

Hi, I'm not using laravel 10 right now, and as mentioned in previous comments I've also tried to add a specific laravel version, such as the 9.19 in the composer file but that did not help at all..

**Comment by coffeeyoghurt** [comment]
If you experience problems try running with the `--no-scripts` flag:

```
composer update --no-scripts
```

or 
```
composer install --no-scripts
```

**Comment by h00na** [comment]
I am using Laravel 10 and I switched manually the extend from ShowCommand to DbCommand
