### ISSUE TITLE
[Question] If You Have So Many Modules. How Do You Organize It?

### ISSUE THREAD

**Issue by johanessurya** [nWidart/laravel-modules#1549]
I have one big app that:

1. Have APIs group. Handle all API actions.
2. Have a regular web app. Handle all regular web actions.
3. Some of them(API and Web) use the same source code that I create.

Let's imagine that I have 100-200 modules in total(API, Web, and Library Modules).

1. Could you share how you organize your modules in this case?
2. If I want to group by actions like API, Web, and Library. So I have 3 big folder for modules API in folder `Api`, Web in folder `Web`, and Library in folder `Library`. Is it possible?

**Comment by dcblogdev** [comment]
You could define multiple module paths by turning on scan mode in the config and add multiple paths that can be scanned, you would have to update the namespaces for all files within those modules placed in the defined paths.

```
'scan' => [
        'enabled' => true,
        'paths' => [
            base_path('OtherModules/*'),
            base_path('vendor/*/*'),
        ],
    ],
```

I've done that in the past where I had a `Modules` and a `CMSModules` directly

**Comment by solomon-ochepa** [comment]
You can simply make each modules installable module packages and require them where needed!
For instance, I may have User-module, but requires Status-module to function fully.
