### ISSUE TITLE
how to know current active module

### ISSUE THREAD

**Issue by aiqbalsyah** [nWidart/laravel-modules#155]
Hello, 

I just want to know how to know current active module..

Thanks

**Comment by Fuhrmann** [comment]
Is there a way discover the current active module?

**Comment by nWidart** [comment]
For AsgardCMS I created this helper for instance: https://github.com/AsgardCms/Platform/blob/3.0/Modules/Core/helpers.php#L23-L28

**Comment by Fuhrmann** [comment]
Thanks @nWidart !
