### ISSUE TITLE
[Feature request] Optionally boot modules

### ISSUE THREAD

**Issue by swaner** [nWidart/laravel-modules#1552]
## Purpose
Currently this library is loading all enabled modules on each request. But a module might only have one or none dependencies to other modules.
To load only dependent modules would be great for both performance and module isolation (avoiding a bug in some other module). 

## Suggestion
My suggestion is to add an optional configuration file where you can specify dependencies to load for each module. This file should be optional so it's backwards compatible.

### Configuration file
Introduce a new file that file list all dependencies to load for each module:

modules_dependencies.json:
```json
{
    "APIModule": [
        "AccountModule",
        "InvoiceModule",
        "AuthModule"
    ],
    "InvoiceModule": [
        "AccountModule"
    ]
}
```

So when the InvoiceModule is called, then laravel-modules will load AccountModule and skip loading the other modules.
This file could perhaps be generated in some CI script that uses deptrac or similar tooling to figure out module dependencies? But that shouldn't be part of this project.

### Rules
* If modules_dependencies.json file doesn't exist, all modules will always be loaded
* If the calling module is missing in modules_dependencies then all modules will be loaded
* When there are nested dependencies all dependencies in that tree will be loaded
   * Circular dependencies must therefore be handled by the "module loader"

I think I can help out with the implementation but would like to know if you think it's a PR that would be merged?

**Comment by turkimud** [comment]
Also conceder adding facade method to PR
Module::allLoaded();

**Comment by solomon-ochepa** [comment]
I don't think this is necessary.

All the modules are booted, yes; but not all are loaded.

I'm using a nested modules architecture where a particular module may requires one or more other modules to function. In this case, all the modules are booted with Laravel (which is a normal behavior), but only the depending modules are loaded and some ever eagerly loaded (Eloquent) into another module.

Example: Property-module
Required: Category-module, Status-module, User-module, Attribute-module etc.

Hope you get my points?
