### ISSUE TITLE
Route Priority Issue

### ISSUE THREAD

**Issue by mprince2k18** [nWidart/laravel-modules#1555]
I want to give root web.php high priority rather than the modules route.

**Comment by solomon-ochepa** [comment]
Without routes conflict, I don't see any reason why this is necessary. And notwithstanding, routes conflict is actually a bug you'll need to fix in your codebase.

Routes conflicts is when you define more than one route for a given resources; either in the same file or multiple route files.

**Comment by mprince2k18** [comment]
I wanted to do something like when the module route web.php has an URL of '/home' and the root route web.php has '/home' it will give priority to the root route web.php, if the root route web.php do not have the '/home' URL it will get access of the module url.

**Comment by solomon-ochepa** [comment]
Alternatively, to achieve your goal you have to check if a route exist before declaring each routes in your modules.

Using this method, you are overriding the modules functionalities.

A module with store or update resources for instance will be overridden to root controller with different logics and validations. What do you expect in this case? Fatal error!
