### ISSUE TITLE
php artisan module:lang issue

### ISSUE THREAD

**Issue by SVANNER** [nWidart/laravel-modules#1559]
Hi, it seems the php artisan module:lang command is not working while there is a 'CheckLangCommand.php' in the Command folder. I tried to add 'Commands\CheckLangCommand::class,' in the config.php file, but it seems the command is still not found
![image](https://user-images.githubusercontent.com/3523354/228615212-a86851c3-93ec-4c4d-b4b3-21c4cacf35c8.png)

**Comment by alissn** [comment]
@SVANNER 

HI, Which version of laravel and package are you using?

**Comment by SVANNER** [comment]
Hi, i ran a composer update and it solved the problem for me.
Thanks a lot !
