### ISSUE TITLE
Communication between modules

### ISSUE THREAD

**Issue by Mohammed-Alama** [nWidart/laravel-modules#1560]
This questions freeze my mind 
What is the official way in this package to have a communication between modules
and to communicate you must have a single point to access, in the modular world we could have facades 
- Modules
  - Post
    - Http 
    - PostFacade
  - User
    - Http 
    - UserFacade  

Need your opinions here !!!

**Comment by Chemaclass** [comment]
I think [Gacela](https://github.com/gacela-project/gacela) can help you to work out the **communication between modules** exactly as you draw above ☝️

**Comment by Tito-Kati** [comment]
Yes, Gacela definitely could serve for this!
