### ISSUE TITLE
 Nwidart\Modules\Exceptions\ModuleNotFoundException     Module [] does not exist!

### ISSUE THREAD

**Issue by mprince2k18** [nWidart/laravel-modules#1561]
I tried php artisan module:make-model Language this command and getting 

 Nwidart\Modules\Exceptions\ModuleNotFoundException     Module [] does not exist! error
 
 
![image](https://user-images.githubusercontent.com/43857625/229491466-0497b8b5-ea16-40dd-a568-f667968a050b.png)

**Comment by mprince2k18** [comment]
problem solved

**Comment by Collinskem** [comment]
@mprince2k18 how did you solved this issue?

**Comment by hoangnamitc** [comment]
It is possible to make some misunderstandings from the documentation.
Instead of the correct structure

`php artisan module:make-model <model_name> <module_name>`

Maybe some people only pass 1 first parameter, because they think this is a command to create multiple models at the same time
