### ISSUE TITLE
Component class function not able to call inside the blade file module

### ISSUE THREAD

**Issue by mtkumar82** [nWidart/laravel-modules#1562]
Hi,
I am using Nwidart extension and created modules in my application which is working file. But now for some functionality I need to use component inside my module. I created the component inside my module and it created successfully, View file of component is also working fine with tag like
<code>
<x-amazonrepricer::amazon-repricer />

</code>
where amazonrepricer is my module name and amazon-repricer is blade file with Component class AmazonRepricer with function. like 

<code>
class AmazonRepricer extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
       
    }

    public function getShortTextByStatus($statusCode)
    {
       return 'TEST';
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        die("sadfasdf");
       return view('amazonrepricer::components.amazonrepricer');
    }
</code>

And calling the getShortTextByStatus in my blade file like 

<div>
    
 {{ $slot }}
 {{ $getShortTextByStatus('EDIT') }}
</div>

but its giving error Undefined variable $getShortTextByStatus. Please help me how to use the Component class function inside the component view blade file.

Thanks,
jarnail

**Comment by tiagoskaterock** [comment]
I am having the same problem. I created components inside the modules, when I call the component it renders well. BUT, the class responsable for renders the component which is inside View/Components inside the Modules NEVER runs for some reason.

**Comment by solomon-ochepa** [comment]
What is the solution for this issue please?

**Comment by tiagoskaterock** [comment]
Hello solomon!

I did a workaround here on Laravel 10

Since nothing inside Modules/Mymodule/app/View/Components looks to work for me and I am going crazy

I am passing the variables and they are available directly inside the view component.

---

Calling the component in my views index.blade.php
`<x-websitecupcakes::headerlink slug="#intro" title="Home" test="test1" /> `

The component in Modules/Mymodule/Resources/Components/headerlink.blade.php
```
@php 
  // the code that was inside the component class goes here now, the __construct and render methods
 // do this stuff
 // do that stuff
 // do more stuff
@endphp

<li>
  <a href='{{ $slug }}' >
    {{ $title }}
    {{ $test }}
  </a>  
</li>
```
I know it's not clean and pretty, but for now this is doing the job for me.

Any help from anyone would be really appreciated =)

Good coding!

**Comment by solomon-ochepa** [comment]
> Mymodule

Yeah, that is right. I'm using the same concept for now. It would be nice if the component class worked as expected.

**Comment by solomon-ochepa** [comment]
> Hello solomon!
> 
> I did a workaround here on Laravel 10
> 
> Since nothing inside Modules/Mymodule/app/View/Components looks to work for me and I am going crazy
> 
> I am passing the variables and they are available directly inside the view component.
> 
> Calling the component in my views index.blade.php `<x-websitecupcakes::headerlink slug="#intro" title="Home" test="test1" /> `
> 
> The component in Modules/Mymodule/Resources/Components/headerlink.blade.php
> 
> ```
> @php 
>   // the code that was inside the component class goes here now, the __construct and render methods
>  // do this stuff
>  // do that stuff
>  // do more stuff
> @endphp
> 
> <li>
>   <a href='{{ $slug }}' >
>     {{ $title }}
>     {{ $test }}
>   </a>  
> </li>
> ```
> 
> I know it's not clean and pretty, but for now this is doing the job for me.
> 
> Any help from anyone would be really appreciated =)
> 
> Good coding!

Yeah, that is right. I'm using the same concept for now. It would be nice if the component class worked as expected.
