### ISSUE TITLE
Routing with Slash Route Issue

### ISSUE THREAD

**Issue by omega925** [nWidart/laravel-modules#1564]
by default in create of module it create default route "/"
for example 

Route::prefix('mymodule')->group(function() {
    Route::get('/', 'MyModuleController@index');
});

and also the route shows if i use "php artisan route:list"
but if i use this route it go to page 404 

according to my debug i find this route doesn't work but i put any other route 
for example if i add something after slash it work will 
for example let suggest the generated route by module is 
 Route::get('/', 'MyModuleController@index'); 
it will not work 
but if add for example any latter or word after / it work will for example if i add index word after slash it will become 
 Route::get('/index', 'MyModuleController@index'); 

before last update to version 10 it was work well 
can you check it please 
thank you

**Comment by JaberWiki** [comment]
@omega925 I checked in Laravel 9 and 10. I haven't faced any issue.
