### ISSUE TITLE
rootUrlNamespace usage in RouteServiceProvider

### ISSUE THREAD

**Issue by webmake** [nWidart/laravel-modules#157]
I'm interested, why nobody noticed wrong variable usage:
`protected $rootUrlNamespace = '$MODULE_NAMESPACE$\$MODULE$\Http\Controllers';`
this place I always replace with namespace variable:
`protected $namespace = 'app\Modules\Sample\Http\Controllers';`

Is it version specific?
I use 5.4.13 laravel

**Comment by nWidart** [comment]
Can you provide a failing test for this ?
