### ISSUE TITLE
Problem create module in Laravel 5.4

### ISSUE THREAD

**Issue by FradaL** [nWidart/laravel-modules#158]
El the file start.php of module folder

holds this:

```
if (!app()->routesAreCached()) {
    require __DIR__ . '/../Http/routes.php';
}
```

i can solution the problem with next form:

```
if (!app()->routesAreCached()) {
    require __DIR__ . '/Http/routes.php';
}
```
i wait the information help you

**Comment by Phirames** [comment]
Same for me. Command `module:make ModuleName` genereates `start.php` which causes error. 
I have to manually remove '/..' to keep working with code every time I create module.

**Comment by online217** [comment]
The same to me and by removing '/..' it works.

**Comment by nWidart** [comment]
Hm, I originally changed due to this issue: https://github.com/nWidart/laravel-modules/issues/115

**Comment by online217** [comment]
I am using laravel v5.4.9.

**Comment by nWidart** [comment]
Fixed it latest version, thanks for reporting the issue. 👍 

https://github.com/nWidart/laravel-modules/releases/tag/1.17.1
