### ISSUE TITLE
Regarding module routing

### ISSUE THREAD

**Issue by AwesomeNishanTM** [nWidart/laravel-modules#1580]
I have created a controller having a index() method with public function index()
    {
        // return 'hello';
        $users=$this->user->list();
        return view('user.index',compact($users));
    }

and trying to access using routing but could not access it
always get 404 error but able to route from root web.php of root blade files

**Comment by JaberWiki** [comment]
**Use**
return view('module_name::user.index', compact($users));

**Comment by JaberWiki** [comment]
> **Use**
> return view('module_name::user.index', compact($users));

@AwesomeNishanTM
