### ISSUE TITLE
webpack.stub, Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by alagoroVigo** [nWidart/laravel-modules#1584]
$ php8 artisan module:make Diplomasacs

   INFO  Creating module: [Diplomasacs].  

  Generating file Modules/Diplomasacs/module.json ................... 0ms DONE
  Generating file Modules/Diplomasacs/Routes/web.php ................ 0ms DONE
  Generating file Modules/Diplomasacs/Routes/api.php ................ 0ms DONE
  Generating file Modules/Diplomasacs/Resources/views/index.blade.php  0ms DONE
  Generating file Modules/Diplomasacs/Resources/views/layouts/master.blade.php  0ms DONE
  Generating file Modules/Diplomasacs/Config/config.php ............. 0ms DONE
  Generating file Modules/Diplomasacs/composer.json ................. 0ms DONE
  Generating file Modules/Diplomasacs/Resources/assets/js/app.js .... 0ms DONE
  Generating file Modules/Diplomasacs/Resources/assets/sass/app.scss  0ms DONE
  Generating file Modules/Diplomasacs/webpack.mix.js ................ 0ms FAIL

   ErrorException 

  file_get_contents(/opt/svn/musicaldoslagol9/vendor/nwidart/laravel-modules/src/Support/../Commands/stubs/webpack.stub): Failed to open stream: No such file or directory

Ok. This is the same as #1505 but there is no file config/modules.php where to remove  webpack from.
So until there is another solution I created a file Commands/stubs/webpack.stub from an older version of nWidart/laravel-modules:

`const mix = require('laravel-mix');
require('laravel-mix-merge-manifest');

mix.setPublicPath('../../public').mergeManifest();

mix.js(__dirname + '/Resources/assets/js/app.js', 'js/$LOWER_NAME$.js')
    .sass( __dirname + '/Resources/assets/sass/app.scss', 'css/$LOWER_NAME$.css');

if (mix.inProduction()) {
    mix.version();
}`

and now it worked

**Comment by CodingGagan** [comment]
Hi @alissn 
I'm facing the same issue but with different file.

  Generating file Modules/Page/module.json ................................................................................................ 0ms DONE
  Generating file Modules/Page/routes/web.php ............................................................................................. 0ms DONE
  Generating file Modules/Page/routes/api.php ............................................................................................. 0ms DONE
  Generating file Modules/Page/resources/views/index.blade.php ............................................................................ 0ms DONE
  Generating file Modules/Page/resources/views/layouts/master.blade.php ................................................................... 0ms DONE
  Generating file Modules/Page/config/config.php .......................................................................................... 0ms DONE
  Generating file Modules/Page/composer.json .............................................................................................. 0ms DONE
  Generating file Modules/Page/resources/js/app.js ........................................................................................ 0ms FAIL

   ErrorException 

  file_get_contents(/opt/lampp/htdocs/thebrandconceptadmin/vendor/nwidart/laravel-modules/src/Support/../Commands/stubs/js/app.stub): Failed to open stream: No such file or directory

  at vendor/nwidart/laravel-modules/src/Support/Stub.php:106
    102▕      * @return mixed|string
    103▕      */
    104▕     public function getContents()
    105▕     {
  ➜ 106▕         $contents = file_get_contents($this->getPath());
    107▕ 
    108▕         foreach ($this->replaces as $search => $replace) {
    109▕             $contents = str_replace('$' . strtoupper($search) . '$', $replace, $contents);
    110▕         }

      +21 vendor frames 

  22  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()
      
      Can you please help me with this.

**Comment by CodingGagan** [comment]
Hi @alissn 
Can you please in the same. I'm facing this issue

`
  Generating file Modules/Page/module.json ................................................................................................ 0ms DONE
  Generating file Modules/Page/routes/web.php ............................................................................................. 0ms DONE
  Generating file Modules/Page/routes/api.php ............................................................................................. 0ms DONE
  Generating file Modules/Page/resources/views/index.blade.php ............................................................................ 0ms DONE
  Generating file Modules/Page/resources/views/layouts/master.blade.php ................................................................... 0ms DONE
  Generating file Modules/Page/config/config.php .......................................................................................... 0ms DONE
  Generating file Modules/Page/composer.json .............................................................................................. 0ms DONE
  Generating file Modules/Page/resources/js/app.js ........................................................................................ 0ms FAIL

   ErrorException 

  file_get_contents(/vendor/nwidart/laravel-modules/src/Support/../Commands/stubs/js/app.stub): Failed to open stream: No such file or directory

  at vendor/nwidart/laravel-modules/src/Support/Stub.php:106
    102▕      * @return mixed|string
    103▕      */
    104▕     public function getContents()
    105▕     {
  ➜ 106▕         $contents = file_get_contents($this->getPath());
    107▕ 
    108▕         foreach ($this->replaces as $search => $replace) {
    109▕             $contents = str_replace('$' . strtoupper($search) . '$', $replace, $contents);
    110▕         }

      +21 vendor frames 

  22  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()`

**Comment by CodingGagan** [comment]
```
"php": "^8.1",
        "barryvdh/laravel-debugbar": "^3.9",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.0",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "league/flysystem-aws-s3-v3": "^3.15",
        "nwidart/laravel-modules": "^11.0"`  
```  
     

   I just commented out these two files,


```
 'files' => [
            'routes/web' => 'routes/web.php',
            'routes/api' => 'routes/api.php',
            'views/index' => 'resources/views/index.blade.php',
            'views/master' => 'resources/views/layouts/master.blade.php',
            'scaffold/config' => 'config/config.php',
            'composer' => 'composer.json',
            // 'js/app' => 'resources/js/app.js',
            // 'sass/app' => 'resources/sass/app.scss',
            'vite' => 'vite.config.js',
            'package' => 'package.json',
        ],
```

        So I was trying to install a module using command => `php artisan module:make Page`
        
        and it giving me error of Fail on app.js and app.scss file. So commenting out those two line work for me.

**Comment by alissn** [comment]
It's not correct. You should use version 10 of the package for Laravel 10, or upgrade the Laravel version in your project.

Additionally, have you changed the `stubs.path` in your config? If so, please provide those details.
