### ISSUE TITLE
Laravel Passport

### ISSUE THREAD

**Issue by IgorSiqueira** [nWidart/laravel-modules#1586]
I have a working project where the api login is done using Laravel Passport.

I just added laravel-modules and created a new controller and route that must be protected by auth:api , but even if I send the token correctly I always get unauthenticated return.

**Comment by Escarter** [comment]
Hi @IgorSiqueira , take a look at this blog post might be helpful. 
https://medium.com/@santhoshj/how-to-use-passport-with-laravel-modules-nwidart-566deadf651b
