### ISSUE TITLE
Laravel-modules version 7 breaking existing translations

### ISSUE THREAD

**Issue by mrjokermr** [nWidart/laravel-modules#1587]
Whenever I create a module via the php artisan command: php artisan module:make [Name] , 
the trans() function that was functioning before breaks I have already searched where the break happens  but I can't find it also can't find what is exactly changed after this php artisan command. 

Even turning off the module via the artisan command won't fix trans() helper.

Anyone that knows a solution for this problem or knows which files I should also check where the bug is created?

**Comment by mrjokermr** [comment]
I think I need to know what files in the vendor directory are changed, these changes won't be highlighted by git status.

**Comment by mrjokermr** [comment]
I already removed the translation functionalities from the module, but this didn't fix it. Also tried to install another older version (v6) but this would also break the laravel trans() helper functionalities.

**Comment by mrjokermr** [comment]
Okay this module Translator is overwriting the base app translator (`$this->translator = $app['translator'];`), which shouldn't happen. How could I prevent this from happening? Because setting translations config settings to false won't do anything.

**Comment by mrjokermr** [comment]
No fix? Because turning off the translations boolean to false in the module configuration isn't changing anything for this translator to not be set.

**Comment by alissn** [comment]
hi @mrjokermr 

how use trans function? write your code here
