### ISSUE TITLE
How to include modules assets

### ISSUE THREAD

**Issue by Warchiefs** [nWidart/laravel-modules#159]
I have a .js file in my Modules\ModuleName\Assets folder. I want to use it in other module's views files. How i can to include it in html.

**Comment by mikemand** [comment]
Like so:

```blade
{{ Module::asset('blog:js/script.js') }}
```

This assumes your script is located at `/Modules/ModuleName/Assets/js`. If it is not in a folder, just omit the `js/` part in the `asset` call.

(Found [here](https://nwidart.com/laravel-modules/v1/advanced-tools/facade-methods).)

**Comment by MineSQL** [comment]
Using the `Module::asset('blog:js/script.js')` function just gives me a 404 error when attempting to link to the files. I'm running this on artisan serve.

**Comment by nWidart** [comment]
Did you publish your module assets ? (command in the docs as well)

**Comment by Warchiefs** [comment]
oh, thx a lot)

**Comment by t-prod** [comment]
Hi, how can we handle assets files ?
In fact I use Bower and would like to copy all assets from the bower_components directory instead of Assets directory.
Modules/OwlCarousel2
---bower.json
---Assets
---bower_components

It's more simple I think to update only the bower.json and call the publish command

Thanks for your help

**Comment by prayas-sapkota** [comment]
Please help me to publish module assets?

I tried Module::asset('blog:js/script.js') function just gives me a 404 error.

Thanks.

**Comment by nWidart** [comment]
Run `php artisan module:publish`.

**Comment by prayas-sapkota** [comment]
Hi nWidart,

Thank you for your help. I run the publish command, it says published but still it is not working.

**Comment by prayas-sapkota** [comment]
Thanks @nWidart for your quick while, I tried again and looks good now.

**Comment by kathmandu1** [comment]
prayas daai malai css ra js , image haru Module ko vitra raakhnu pareko kasari solve garnu vayo

**Comment by zahidhassanshaikot** [comment]
> Thanks @nWidart for your quick while, I tried again and looks good now.

how you solved it please help me

**Comment by Hasitha98** [comment]
@nWidart please can you tell me command to publish assets

**Comment by foxmedo** [comment]
Hello, 

How to use assets without publish on dev mode

it's not possible to run the publish commande after each js file update, any idea ?

waiting for your feedback

**Comment by SocolaDaiCa** [comment]
@foxmedo you can config laravel mix in your module. when run `npm run watch` It will compile and put code to public whenever file in assets change
