### ISSUE TITLE
Vite manifest not found

### ISSUE THREAD

**Issue by HelpsmannBjoern** [nWidart/laravel-modules#1593]
When I want to implement the {{ module_vite('build-modulename', 'Resources/assets/sass/app.scss') }} an error comes with "Vite manifest not found". npm run dev is working.

**Comment by CrazyTapok-bit** [comment]
In fact, this package has really terrible and outdated documentation. But you can try go to module directory `cd ./Modules/modulename/`, then do `npm install`, `npm run build`. At this point you should have a manifest file. And finally you can do `npm run dev`. Let me know the result
