### ISSUE TITLE
Folder to each tenant 

### ISSUE THREAD

**Issue by yashiroiori** [nWidart/laravel-modules#1600]
Hi, I have an ERP in Laravel 10, using of course modules with this package, inertiajs with react and stancl tenant package, all work perfect but some customers send email ask me if I can develop custom features with specify process or ask me if they can develop your own modules an upload in the system

The question is if exists to make custom folder with for example ID if the tenant and put the custom modules and after the module package read and work with them modules?? And another case overwrite de native module with the tenant module like Quotation and tenant make own Quotation module and use them instance?? 
Like Modules folder are a central modules and have a ModulsTenant folder to put the custom modules for each tenant

Folder example:
app
Modules/
    Auth/
    Quotation/
ModulesTenant/
     Tenant1/
            Shipment/
            Quotation/.   -> use this module instance Modules/Quotation

**Comment by dcblogdev** [comment]
nothing like this exists, modules are not tenant aware, and you'll need to use the module's service providers to place custom code in. I don't think there's anything baked into this package that will leverage what you need.
