### ISSUE TITLE
Is there any plan to using vite for laravel 10 version?

### ISSUE THREAD

**Issue by Jagdish-J-P** [nWidart/laravel-modules#1603]
Is there any plan to support vite asset bundler instead of webpack mix for Laravel 10? As I have used vite for my existing project and I couldn't find option here.

**Comment by Sicklou** [comment]
it already works.

You have to change your config/modules.php with the new one. [Here](https://github.com/nWidart/laravel-modules/blob/master/config/config.php)

See : https://github.com/nWidart/laravel-modules/issues/1588#issuecomment-1630815574
