### ISSUE TITLE
Issue while publishing a config file using php artisan module:publish-config

### ISSUE THREAD

**Issue by kjavaid** [nWidart/laravel-modules#1609]
The issue is my module name is "Services" and when it tried to run `php artisan module:publish-config` command it doesn't work, means it do not create a file on config directory of Laravel project.
Here is the reason I have identified so far Laravel project by default have services.php file inside the config directory and our Module name is Services so when we execute the command it doesn't do anything as excepted because there's already a file named services.php
So my question related to this problem is there any option so we can just add some sort of prefix or something like this so that config file of Services module get publish with some other name

**Comment by alissn** [comment]
Hi,

You can modify the `registerConfig` method in `Module/Services/Providers/ServicesServiceProvider` as shown below:

```php
protected function registerConfig()
{
    foreach (\File::glob(module_path($this->moduleName, 'Config/*.php')) as $file) {

        $this->publishes([
            $file => config_path(basename($file)),
        ], 'config');

        $this->mergeConfigFrom(
            $file, basename($file, '.php')
        );
    }
}
```

After making these changes, you will be able to create a configuration file with a custom name. This file will also be published with the same name into the root configuration.

Additionally, you can utilize the `php artisan module:publish-config -f` command to overwrite existing configuration files.

**Comment by kjavaid** [comment]
Thanks @alissn that helped a lot

**Comment by kjavaid** [comment]
Well, I modified the code so that only config file name will be changed as per need rest of the files will work the same

`protected function registerConfig()
{
    foreach (\File::glob(module_path($this->moduleName, 'Config/*.php')) as $file) {

        $this->publishes([
            $file => explode(".", basename($file))[0] == 'config'
                    ? config_path('services-module.php')
                    : config_path(basename($file)),
        ], 'config');

        $this->mergeConfigFrom(
            $file, basename($file, '.php')
        );
    }
}`

Maybe someone can get help from this as well
