### ISSUE TITLE
Module lang files are not loaded

### ISSUE THREAD

**Issue by jaumeavila** [nWidart/laravel-modules#161]
When I try to show a message stored in the module lang file it is not displayed.
But if I set the key in the Laravel Lang folder, it is.

Do I have to change anything manually to load de lang file from the module directory?

The module name is Carsharing. Here you have the info in module.json:
`{
    "name": "Carsharing",
    "alias": "carsharing",
    "description": "",
    "keywords": [],
    "active": 1,
    "order": 0,
    "providers": [
        "Ubeeqo\\Carsharing\\Providers\\ReservationServiceProvider"
    ],
    "aliases": {},
    "files": [
        "start.php"
    ],
    "requires": []
}`

I have tried as keys:
Carsharing::errors.invalid_vehicle_id
carsharing::errors.invalid_vehicle_id
Carsharing.errors.invalid_vehicle_id
carsharing.errors.invalid_vehicle_id
Carsharing:errors.invalid_vehicle_id
carsharing:errors.invalid_vehicle_id

And I have used Lang::get and trans

**Comment by jaumeavila** [comment]
Ok, I had a problem with the fallback locale.

My fault, sorry.

Great work!

**Comment by nWidart** [comment]
Oh awesome, thanks for letting us know! 👍
