### ISSUE TITLE
support laravel/octane

### ISSUE THREAD

**Issue by Kevin-Ben** [nWidart/laravel-modules#1617]
this is support laravel/octane?

**Comment by rupeshstha** [comment]
The compatibility of this package with Laravel Octane depends on how you structure your code. I have successfully developed an ecommerce project utilizing the capabilities of Laravel Octane in conjunction with this package. To ensure smooth operation, it is imperative to include 'Modules' in the watch configuration of your octane.php file.

In summary, yes, the package can be made compatible with Laravel Octane, as long as you configure it correctly as mentioned above.
