### ISSUE TITLE
module routes not found

### ISSUE THREAD

**Issue by AliYazdanifar** [nWidart/laravel-modules#1618]
When I was in the local environment, there was no problem, but when I brought it to the shared host,i get 404 error and the modules are not found and the routes are not registered.
htaccess : 
`RewriteEngine on
RewriteCond %{REQUEST_URI} !^public
RewriteRule ^(.*)$ public/$1 [L]`

**Comment by theodor-codrianu** [comment]
"when I brought it" what do you mean? if you just uploaded module to shared host (production that is) try enabling it (php artisan module:enable ModuleName) 
and, eventually, clear cache, views etc ...
