### ISSUE TITLE
composer update on the module

### ISSUE THREAD

**Issue by RichardTianke** [nWidart/laravel-modules#162]
Hi guy,
When I composer update on the Module.
It's done, but http fail. eg.http://www.test.com/xxx (xxx is module name).
The message is : 
```
Sorry, the page you are looking for could not be found.
NotFoundHttpException in RouteCollection.php line 161:
```

can you help me?

**Comment by RichardTianke** [comment]
Laravel version: 5.4
PHP version: 7.0
composer version: 1.3.2

**Comment by nWidart** [comment]
Is that route defined in your routes files ?

**Comment by RichardTianke** [comment]
The first thing I installed the module, named Test.
Then I can from the browser access to this module, eg. http://test.com/test
I went into the Test module directory
```shell
cd path/Modules/Test
```
```shell
composer update
```
Then I can't from the browser to visit, eg.http://test.com/test,It throws the exception.

Error the following:
```
Sorry, the page you are looking for could not be found.
NotFoundHttpException in RouteCollection.php line 161:
```
Is where I'm going to define some what things?

**Comment by nWidart** [comment]
I don't understand what you're trying to do.

To load your route you need to require it, just as in any laravel app / package.

**Comment by RichardTianke** [comment]
Ok, I'll look at how to deal with this problem
