### ISSUE TITLE
Do something when a module is enabling/disabling

### ISSUE THREAD

**Issue by almamund** [nWidart/laravel-modules#1627]
Hello,
Is there a way to perform an one-time action when a module is being enabled or disabled? For example, I may need to generate certain key or set config value. Could somebody pls give me a hint?

Regards

**Comment by dcblogdev** [comment]
Yes, there are events that fire that you can create a listener for.

When enabling a module these 2 events fire `enabling` and `enabled` once completed the same goes for disabling a module `disabling` and `disabled`
