### ISSUE TITLE
Module composer.json require-dev and scripts

### ISSUE THREAD

**Issue by BTeodor** [nWidart/laravel-modules#163]
I didn't found a way to add dev packages and scripts to the main composer.json from the module composer.json, isn't there the possibility yet?
Would you accept a PR with this? Something like [this](https://github.com/BTeodor/laravel-modules/blob/b136f59663a97dd37d8ef31279791b9462ae9b79/src/Process/Updater.php)

Thanks.

**Comment by nWidart** [comment]
Hello,

That looks decent indeed. One thing it doesn't do is add that packages to the main composer.json file as the `require` key does. That might be something good to have as well.

**Comment by nWidart** [comment]
I just added this on `dev-master`. Feel free to test it out. 👍

**Comment by nWidart** [comment]
This has now been tagged.

**Comment by BTeodor** [comment]
Thanks :)

What about the scripts?

    //scripts
    $scripts = $module->getComposerAttr('scripts', []);
    $composer = json_decode(file_get_contents(base_path('composer.json')), true);
    foreach ($scripts as $key => $script):
        $composer['scripts'][$key] = array_unique(array_merge($composer['scripts'][$key], $script));
    endforeach;
    file_put_contents(base_path('composer.json'), json_encode($composer, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));

I don't know if my approach is the best way to do this but it's working.

For example, i have a dev module where i add all dev packages that i need. When i install the dev module i want to install the dev packages and update the scripts from the main composer.

For example:

Update

    "scripts":{
    "post-update-cmd": [
        "Illuminate\\Foundation\\ComposerScripts::postUpdate",
        "php artisan optimize"
        ]
    },

With

    "scripts":{
    "post-update-cmd": [
        "Illuminate\\Foundation\\ComposerScripts::postUpdate",
        "php artisan ide-helper:generate",
        "php artisan ide-helper:meta",
        "php artisan optimize"
        ]
    },

**Comment by nWidart** [comment]
Oh, you're right, I missed that part. I'll try to implement this asap.

**Comment by nWidart** [comment]
This is now on `dev-master` as well. Has to change your code a bit so it'd work if the script title wasn't present in the main composer.json file.

**Comment by BTeodor** [comment]
Thanks :). Will test soon.
