### ISSUE TITLE
Making another model in an existing module

### ISSUE THREAD

**Issue by admiral9200** [nWidart/laravel-modules#1659]
I have a module named 'Contract' in my laravel project.

To make a model named 'Contract', I used this command:
_php artisan module:make-model Contract -ms_

Then I am going to make another model named 'ContractType' in existing 'Contract' module.
In this case, I used the php artisan cli like the above:
php artisan module:make-model ContractType -ms.
But in this case, "Module [ContractType] does not exist!" error ocurred.

Please let me know how to make another model in an existing module.

**Comment by dcblogdev** [comment]
you need the module name too

```
php artisan module:make-model ContractType Contract -ms.
```

**Comment by admiral9200** [comment]
Yeah, you are right. Thanks
