### ISSUE TITLE
Relation between models in diferent modules

### ISSUE THREAD

**Issue by alagoroChapela** [nWidart/laravel-modules#1668]
This is a topic already written about, but how about having modules deactivated, how can you make relations only if module is active?

Module 1 has clients
Module 2 has invoices

in model client

```php
namespace Modules\Module1\Entities;

use Modules\Module2\Entities\Invoice;

public function invoices(){

return $this->hasMany(Invoice::class)
}
```

in invoices model

```php
namespace Modules\Module2\Entities;

use Modules\Module1\Entities\Client;

public function client(){
return $this->belongsTo(Client::class)
}
```

(Please excuse me if there are any syntax errors, I had to build the example in my mind)

Now Module 2 is deactivated. How can I make method invoices available only if module 2 is active?

**Comment by dcblogdev** [comment]
you can use the `Module::isEnabled('ModuleName');` method ie

```php
use Nwidart\Modules\Facades\Module;

...

if (Module::isEnabled('Module2') {
 //do action 
}
```

**Comment by alagoroChapela** [comment]
> you can use the `Module::isEnabled('ModuleName');` method ie
> 
> ```
> use Nwidart\Modules\Facades\Module;
> 
> ...
> 
> if (Module::isEnabled('Module2')) {
>  //do action 
> }
> ```

But if Module is not enabled method referring that module should not be implemented in model as class could no exist.

**Comment by solomon-ochepa** [comment]
> But if Module is not enabled method referring that module should not be implemented in model as class could no exist.

When a module is disabled, it doesn't mean the code has been deleted. The full source code is still in place.

However, it's now your responsibility to always check for the necessary conditions to determine when and when not to implement a code block that depends on that module.

[dcblogdev](https://github.com/nWidart/laravel-modules/issues/1668#issuecomment-1784192350) is the perfect code to use.

**Comment by solomon-ochepa** [comment]
> you can use the `Module::isEnabled('ModuleName');` method ie
> 
> ```
> use Nwidart\Modules\Facades\Module;
> 
> ...
> 
> if (Module::isEnabled('Module2')) {
>  //do action 
> }
> ```

You can apply this solution as follows;

```php
namespace Modules\Module2\Entities;

use Modules\Module1\Entities\Client;
use Nwidart\Modules\Facades\Module;

...

public function client()
{
    if (Module::isEnabled('Module1')) {
        return $this->belongsTo(Client::class);
    } else {
        return null;
    }
}

...
```

**Comment by alagoroChapela** [comment]
OK. I don't know if this is an issue to be related here, so please redirect me to whereever..

The problem is I could be making a relation between module1 and module 2 but I could not be owner of the code in module1.

Is there any way to make code relating module1 and module2 making a kind of trait to include in module1 but belonging to module2 and only included if module2 is active?

Obviously I'm trying to make something "today" I can't do:

```
if (Module::isEnabled('Module1')) {
  use Modules\Module2\relationTrait
}

```

**Comment by solomon-ochepa** [comment]
> OK. I don't know if this is an issue to be related here, so please redirect me to whereever..
> 
> The problem is I could be making a relation between module1 and module 2 but I could not be owner of the code in module1.
> 
> Is there any way to make code relating module1 and module2 making a kind of trait to include in module1 but belonging to module2 and only included if module2 is active?
> 
> Obviously, I'm trying to make something "today" I can't do:
> 
> ```
> if (Module::isEnabled('Module2')) {
>   use Modules\Module2\relationTrait
> }
> ```

If I understand you clearly, you'd like to reuse a code (e.g. Trait) from another module within your app, but only when it's active.

If that is the case then your code sample is very correct!

**Comment by alagoroChapela** [comment]
Thank yo for all your answers.
