### ISSUE TITLE
These changes in main stubs are necessary  

### ISSUE THREAD

**Issue by wikigods** [nWidart/laravel-modules#1684]
Hello @dcblogdev, why there have been changes with stubs such as request, provider, web, controller, are they necessary, I think we should keep it in a standard way and having as a base how laravel is handling it so we don't have content commented unnecessarily. I know that we can publish stubs and modify them but it is faster to have it clean and make the modifications of the stubs.

Request 
![image](https://github.com/nWidart/laravel-modules/assets/71094046/f4d8c98f-9383-41ad-99ae-dcae19f24c8c)

Request (Laravel)  (previously we had it in only true)
![image](https://github.com/nWidart/laravel-modules/assets/71094046/d6e2b505-a1d4-4282-9f3c-2596a78d5b6c)

Controller
![image](https://github.com/nWidart/laravel-modules/assets/71094046/4e080f64-20b4-4a87-9f51-ec4698ee0190)
Controller (Laravel)
![image](https://github.com/nWidart/laravel-modules/assets/71094046/c5adcaf5-907d-4709-b8cf-ee5cc116cb21)

**Comment by solomon-ochepa** [comment]
Have you created a fresh app recently using Laravel 10.x?

Everything you pointed out are implemented or recommended based on the upgrade documentations.

The commented return value in request.stub is a recommendation. Instead of blindly returning true/false to a form request, it's recommended that you examine the capabilities (permissions) of the user/client making the request.

Since it's not mandatory, but a recommendation and standard, it's commented.

**Comment by wikigods** [comment]
Hello @solomon-ochepa, I don't understand your question if you are working with laravel 10.x (if I am working with 2 applications with modules).

On this "Everything you point out is implemented or recommended based on the upgrade documentation.", attach screenshots of laravel base stubs.

For conventional use if this well comment that happens when you use a third party package that is not spatie/permission, my recommendation to keep clean to not confuse new people with package may think it is mandatory to add permissions in a request, because in my case I am more to use access policies, in some cases if I do additional validation in request. 

Be aware of people new to using the package who do not know how to set up the package stubs.
 Best regards.

**Comment by solomon-ochepa** [comment]
> For conventional use if this well comment that happens when you use a third party package that is not spatie/permission, my recommendation to keep clean to not confuse new people with package may think it is mandatory to add permissions in a request, because in my case I am more to use access policies,

https://laravel.com/docs/10.x/authorization#authorizing-actions-using-policies

```php
<?php
 
namespace App\Http\Controllers;
 
use App\Http\Controllers\Controller;
use App\Models\Post;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
 
class PostController extends Controller
{
    /**
     * Update the given post.
     */
    public function update(Request $request, Post $post): RedirectResponse
    {
        if ($request->user()->cannot('update', $post)) {
            abort(403);
        }
 
        // Update the post...
 
        return redirect('/posts');
    }
}
```

Notice, that the `can()` and `cannot()` methods are reliant on the 3rd party package only.

Secondly, check the code sample copied from the official documentation (link attached above), you will notice the `: RedirectResponse,` being the standard return value format for both the `store()` and `update()` methods.

**Comment by solomon-ochepa** [comment]
![image](https://github.com/nWidart/laravel-modules/assets/110875083/d4483417-89b2-4f34-b1e6-946ad1cae410)

Source: https://laravel.com/docs/10.x/authorization#user-model-actions-that-dont-require-models

**Comment by wikigods** [comment]
Considering what you tell me about the example that would be when you use "redirect" that when you make json response attached image there was debate that same in laravel I think that's why stubs left that without :RedirectResponse or JsonResponse that was the most reasonable that's why I attached stubs base of laravel.

![image](https://github.com/nWidart/laravel-modules/assets/71094046/60bd4a75-696b-4183-a0d5-232af4b7493f)

thank you, sorry for the inconvenience caused by changes I appreciate the work of everyone in the community for maintaining a great package.   @solomon-ochepa

**Comment by dcblogdev** [comment]
yeah, its a tricky situation finding the right balance between stubs for new projects and best practice.

**Comment by solomon-ochepa** [comment]
> Considering what you tell me about the example that would be when you use "redirect" when you make a JSON response attached image. There was debate about that same in laravel. I think that's why stubs left that without RedirectResponse or JsonResponse which was the most reasonable, that's why I attached stubs based on laravel.
> 
> ![image](https://user-images.githubusercontent.com/71094046/280544745-60bd4a75-696b-4183-a0d5-232af4b7493f.png)
> 
> Thank you; sorry for the inconvenience caused by the changes. I appreciate the work of everyone in the community for maintaining a great package. @solomon-ochepa

It's always a good practice to separate API resources from the ordinary web. And for that reason, we have two routes and controller stubs to address that.

Mixing both resources will always come with a cost, and so comes the concept of separation of concerns!

Create two controllers, one for handling API requests and the other for web requests,

Thanks to everyone who has contributed immensely to the growth of this project and open source in general.

**Comment by wikigods** [comment]
I always separate them, that's why I said better to have clean stubs and use stubs base of laravel, an example of capture of really it would look with Api, now I'm doing some tests to make an update some projects that I have version 9 of laravel. (Well I will not make longer I will have to modify stubs and have them in zip, since I'm making config to keep the same structure)

laravel has it like this example 
![image](https://github.com/nWidart/laravel-modules/assets/71094046/9992731e-a2fa-4462-84c2-5349133c2883)

![image](https://github.com/nWidart/laravel-modules/assets/71094046/2d1574bd-48e6-45d9-93c9-5d1d4683991e)

**Comment by solomon-ochepa** [comment]
> I always separate them, that's why I said better to have clean stubs and use stubs base of laravel, an example of capture of really it would look with Api, now I'm doing some tests to make an update some projects that I have version 9 of laravel. (Well I will not make longer I will have to modify stubs and have them in zip, since I'm making config to keep the same structure)
> 
> laravel has it like this example ![image](https://user-images.githubusercontent.com/71094046/280585318-9992731e-a2fa-4462-84c2-5349133c2883.png)
> 
> ![image](https://user-images.githubusercontent.com/71094046/280585019-2d1574bd-48e6-45d9-93c9-5d1d4683991e.png)

Do you realize we have `controller.stub` and `controller-api.stub`?

**Comment by wikigods** [comment]
we had this command "php artisan module:make-model" It generated all the necessary to only made modification I extended the class to add functionality Policy optionally also to generate routes and 4 Api argument to host controller there but used as base controller.stub, no longer had problems to modify stubs, Well anyway thanks for all I will close
