### ISSUE TITLE
upgrade from version 9 to 10 with respect to the new structure 

### ISSUE THREAD

**Issue by wikigods** [nWidart/laravel-modules#1686]
Hi @dcblogdev, what would be the steps to upgrade to the version of structure from v9 to v10 or to keep the structure of version 9 as there are several modules with several files, (is there a way to keep the previous structure preferably v9). 

in documentation I have not found anything related  https://laravelmodules.com/docs/v10/introduction , 

v9 capture
![image](https://github.com/nWidart/laravel-modules/assets/71094046/45725fe7-d78e-44df-a651-fee4bba69eec)

v10 capture
![image](https://github.com/nWidart/laravel-modules/assets/71094046/bfb1bce6-a300-4458-8395-6b881ee44ebd)

or is it only possible by setting up the above configuration or is additional configuration required?
![image](https://github.com/nWidart/laravel-modules/assets/71094046/98e0a9b3-58f1-45f7-9a0e-38da3fb053c5)

I have 10 laravel applications using version 9 laravel-modules and I am interested in upgrading to version 10, 3 of them the clients are asking me to upgrade to laravel 10 and I also need to upgrade the modules package.

**Comment by dcblogdev** [comment]
you won't have to change the modules at all, just the composer version, possibly the config with recent changes. The config structure only applies for making new modules.

You're existing modules should work as is, the only caveat is if you're planning on using vite centrally then you would need to update the vite configs for each module.

You can move the folder structures around as needed, if you use an IDE like PhpStorm it will update namespaces for you if you move files into different directories, as I say its not needed to change

**Comment by solomon-ochepa** [comment]
@dcblogdev has said it all.

1. The changes will not affect your old modules, only newly created modules.

2. However, if you like the new structure, kindly move and rename the necessary files and folders, and remember to update the namespace accordingly!

You may want to delete the entire stubs and the `config/modules.php` and then run the `vendor:publish` command to publish the recent files after upgrading. Make sure to compare the changes (using `git` for instance).

**Comment by wikigods** [comment]
Thanks to the 2, but I prefer the previous structure is cleaner in concept of access, although the new one is not bad either. (Although now I will have to do a little more configurations config to maintain previous structure hehehe), "It would be good if you could put in documentation an update section on the new structure explaining how little you can keep the previous version for old projects."
