### ISSUE TITLE
Vite build error

### ISSUE THREAD

**Issue by jobasc0** [nWidart/laravel-modules#1688]
I did a fresh install today and followed the compiling tuturials like this:

Module layout css:
```
{{ module_vite('build-core', 'resources/assets/css/app.css') }}
```

Module vite.config.js file:

```js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    build: {
        outDir: '../../public/build-core',
        emptyOutDir: true,
        manifest: true,
    },
    plugins: [
        laravel({
            publicDirectory: '../../public',
            buildDirectory: 'build-core',
            input: [
                __dirname + '/resources/assets/css/app.css',
                __dirname + '/resources/assets/js/app.js'
            ],
            refresh: true,
        }),
    ],
});

export const paths = [
    'Modules/$STUDLY_NAME$/resources/assets/css/app.css',
    'Modules/$STUDLY_NAME$/resources/assets/js/app.js',
];
```

Default site vite.config.js file

```js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    build: {
        outDir: '../../public/build',
        emptyOutDir: true,
        manifest: true,
    },
    plugins: [
        laravel({
            publicDirectory: '../../public',
            buildDirectory: 'build',
            input: [
                __dirname + '/resources/assets/css/app.css',
                __dirname + '/resources/assets/js/app.js'
            ],
            refresh: true,
        }),
    ],
});
```

But i am getting this error:

(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.
node:internal/fs/sync:78
  return binding.openSync(
                 ^

Error: ENOENT: no such file or directory, open '../../public/hot'
    at Object.open (node:internal/fs/sync:78:18)
    at Object.openSync (node:fs:565:17)
    at Object.writeFileSync (node:fs:2288:35)
    at Server.<anonymous> (file:///home/myzegaden/public_html/laravel/node_modules/laravel-vite-plugin/dist/index.mjs:104:14)
    at Object.onceWrapper (node:events:628:28)
    at Server.emit (node:events:526:35)
    at emitListeningNT (node:net:1906:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '../../public/hot'
}
Please help,
Thanks in advance.

**Comment by jobasc0** [comment]
> Hi the docs have been updated recently: https://laravelmodules.com/docs/v10/compiling-assets
> 
> inside your module removed everyone and have an array only:
> 
> ```js
> export const paths = [
>     'Modules/ModuleName/resources/assets/css/app.css',
>     'Modules/ModuleName/resources/assets/js/app.js',
> ];
> ```
> 
> then in the root vite config:
> 
> ```js
> import {defineConfig} from 'vite';
> import laravel from 'laravel-vite-plugin';
> import collectModuleAssetsPaths from './vite-module-loader.js';
> 
> async function getConfig() {
>     const paths = [
>         'resources/css/app.css',
>         'resources/js/app.js',
>     ];
>     const allPaths = await collectModuleAssetsPaths(paths, 'Modules');
> 
>     return defineConfig({
>         plugins: [
>             laravel({
>                 input: allPaths,
>                 refresh: true,
>             })
>         ]
>     });
> }
> 
> export default getConfig();
> ```
> 
> For existing modules, you'll need to add `"type": "module"` to the modules `package.json` files

Hi, thanks for the quick response, i have followed your tutorial now the response is;
Vite manifest not found at: /home/myzegaden/public_html/laravel/public/build-core/manifest.json
Pleade help.

**Comment by dcblogdev** [comment]
if your loading all assets centrally then update your layout file to use:

```php
@vite(\Nwidart\Modules\Module::getAssets())
```

otherwise to load the asserts from a module then you may find this guide helpful https://laravelmodules.com/docs/v10/compiling-assets#vite-load-from-modules

the error you're getting is due to a missing manifest file from a module.

**Comment by jobasc0** [comment]
> ```js
> import collectModuleAssetsPaths from './vite-module-loader.js';
> ```

It's still not working, i want to load assets from modules.
This is my setup:

moduleLayout.blade.php
{{ module_vite('build-core', 'resources/assets/css/app.css') }}
{{ module_vite('build-core', 'resources/assets/js/app.js') }}

module vite.config.js
export const paths = [
    'Modules/Core/resources/assets/css/app.css',
    'Modules/Core/resources/assets/js/app.js',
];

site default vite.config.js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';


export default defineConfig({
    build: {
        outDir: '../../public/build',
        emptyOutDir: true,
        manifest: true,
    },
    plugins: [
        laravel({
            publicDirectory: '../../public',
            buildDirectory: 'build',
            input: [
                __dirname + '/resources/assets/css/app.css',
                __dirname + '/resources/assets/js/app.js'
            ],
            refresh: true,
        }),
    ],
});

Npm run build output this response;
Could not resolve entry module "resources/assets/js/app.js".
error during build:
RollupError: Could not resolve entry module "resources/assets/js/app.js".
    at error (file:///home/myzegaden/public_html/laravel/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at ModuleLoader.loadEntryModule (file:///home/myzegaden/public_html/laravel/node_modules/rollup/dist/es/shared/node-entry.js:24881:20)
    at async Promise.all (index 1)

Npm run dev outputs this response:
> dev
> vite

node:internal/fs/sync:78
  return binding.openSync(
                 ^

Error: ENOENT: no such file or directory, open '../../public/hot'
    at Object.open (node:internal/fs/sync:78:18)
    at Object.openSync (node:fs:565:17)
    at Object.writeFileSync (node:fs:2288:35)
    at Server.<anonymous> (file:///home/myzegaden/public_html/laravel/node_modules/laravel-vite-plugin/dist/index.mjs:104:14)
    at Object.onceWrapper (node:events:628:28)
    at Server.emit (node:events:526:35)
    at emitListeningNT (node:net:1906:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '../../public/hot'
}

Node.js v20.9.0

So what i am doing wrong?
Please help.

**Comment by dcblogdev** [comment]
to run vite within a module your module's vite.config file can contain:

```js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    build: {
        outDir: '../../public/build-pages',
        emptyOutDir: true,
        manifest: true,
    },
    plugins: [
        laravel({
            publicDirectory: '../../public',
            buildDirectory: 'build-pages',
            input: [
                __dirname + '/resources/assets/sass/app.scss',
                __dirname + '/resources/assets/js/app.js'
            ],
            refresh: true,
        }),
    ],
});
```

You will want to navigate to the module in my case using a module called Pages so in terminal:

```bash
cd Modules/Pages
```

for the first time install

```js
npm install 
```

run the build
```js
npm run built
```

this will vite the build manifest for the module. You don't care about the project vite.config.js since you're not using it.
