### ISSUE TITLE
Hardcoded Provider Path when Publishing Module Configuration

### ISSUE THREAD

**Issue by jaymeh** [nWidart/laravel-modules#1690]
Hey, I'm a big fan of the newer version of Laravel modules which restructures the filesystem and moves main classes into the app folder.

I have however encountered an issue when running the `php artisan module:publish-config <module-name>` command. This assumes that the provider exposing the configuration will sit inside the following namespace: `"$namespace\\$studlyName\\Providers\\{$studlyName}ServiceProvider"` when with the new folder structure it actually sits within: `"$namespace\\$studlyName\\app\\Providers\\{$studlyName}ServiceProvider"`.

This causes the command to return the attached error message: 
![CleanShot 2023-11-13 at 11 58 50](https://github.com/nWidart/laravel-modules/assets/18261676/4872651b-75c4-4795-b014-2169b1876d68)

Wondering if there is some kind of workaround or suggested route for this?

Thanks

**Comment by dcblogdev** [comment]
thanks for reporting this, I'll need to look into this, should be a case of updating them path and ensure its dynamic.

**Comment by dcblogdev** [comment]
confirmed and got it working with a dynamic path:

```php
$provider = $this->laravel['config']->get('modules.paths.generator.provider.path');
$provider = str_replace('/', '\\', $provider);

return "$namespace\\$studlyName\\$provider\\{$studlyName}ServiceProvider";
```

Checking for other locations that may need updating.

**Comment by dcblogdev** [comment]
I've pushed a new release now.
