### ISSUE TITLE
Config psr4 namespace into composer.json from Module

### ISSUE THREAD

**Issue by yashiroiori** [nWidart/laravel-modules#1691]
Hi, in new version of this package v10, have lower case folders, I set namespace uppercase into composer.json from module but not take this namespace, how do to take effect??

In this example set "namespace Modules\ProxmoxManager\App\Models;"

<img width="1325" alt="image" src="https://github.com/nWidart/laravel-modules/assets/17031855/a721f048-699a-417e-abc3-f5c457bd8e79">

**Comment by dcblogdev** [comment]
In your namespaces change `App` to `app` and also `database/seeders` and `database/factories`

These folders should be lowercase in namespaces:

* app
* database
* database/factories
* database/seeders
* tests

**Comment by solomon-ochepa** [comment]
I think I've found means to solve this issue.

We can leverage on the https://github.com/wikimedia/composer-merge-plugin.

I've tested it and it's working perfectly.

Though, we have about three (3) options.
1. Ask users to install the package manually and configure it - adding the paths.
2. Require the package in the `laravel-modules`' composer.json file and the user can simply add the path.
3. The package `laravel-modules-installer` uses a similar concept. but not utilizing the composer events feature. We can convince the contributor to require it to the package either temporarily while we work on adding all the necessary functions to the laravel-modules-installer or just leave it as a dependency. Users will be required to install the laravel-modules-installer and add the paths or we can simply add the laravel-modules-installer as dependency for laravel-modules.

Either way, once the package finds its way in, all you have to do is add the following code to the root composer.json file;
```bash
    "extra": {
        "merge-plugin": {
            "include": [
                "Modules/*/composer.json"
            ]
        }
    },
```

**Comment by solomon-ochepa** [comment]
In the config/modules.php file, what are the purposes of these two properties?
1. `scan` - is it scanning online for updates, or what exactly is it scanning for?
2. `composer.composer-output` - a detailed explanation, please.

Please, I recommend you reopen this issue and leave it open until it's fixed.

This is one of our challenges and should be given appropriate attention.

**Comment by dcblogdev** [comment]
@solomon-ochepa when you say
> I've tested it and it's working perfectly.

what do you mean exactly? I've installed the package into a demo app and configured the root composer 

created a module called Demo which not appears to have mixed both modules's composer with the root composer

```
Warning: Ambiguous class resolution, "Modules\Demo\database\seeders\DemoDatabaseSeeder" was found in both "/Users/dave/sites/wip/modulesdemo/Modules/Demo/database/seeders/DemoDatabaseSeeder.php" and "/Users/dave/sites/wip/modulesdemo/modules/Demo/database/seeders/DemoDatabaseSeeder.php", the first will be used.
Warning: Ambiguous class resolution, "Modules\Demo\app\Providers\RouteServiceProvider" was found in both "/Users/dave/sites/wip/modulesdemo/Modules/Demo/app/Providers/RouteServiceProvider.php" and "/Users/dave/sites/wip/modulesdemo/modules/Demo/app/Providers/RouteServiceProvider.php", the first will be used.
Warning: Ambiguous class resolution, "Modules\Demo\app\Providers\DemoServiceProvider" was found in both "/Users/dave/sites/wip/modulesdemo/Modules/Demo/app/Providers/DemoServiceProvider.php" and "/Users/dave/sites/wip/modulesdemo/modules/Demo/app/Providers/DemoServiceProvider.php", the first will be used.
Warning: Ambiguous class resolution, "Modules\Demo\app\Http\Controllers\DemoController" was found in both "/Users/dave/sites/wip/modulesdemo/Modules/Demo/app/Http/Controllers/DemoController.php" and "/Users/dave/sites/wip/modulesdemo/modules/Demo/app/Http/Controllers/DemoController.php", the first will be used.
```

**Comment by dcblogdev** [comment]
> In the config/modules.php file, what are the purposes of these two properties?
> 
> 1. `scan` - is it scanning online for updates, or what exactly is it scanning for?
> 2. `composer.composer-output` - a detailed explanation, please.
> 
> Please, I recommend you reopen this issue and leave it open until it's fixed.
> 
> This is one of our challenges and should be given appropriate attention.

What I'd like to understand what are you looking to accomlish with this? being able to have namespaces like: `Modules\Demo\App\Http\Controllers` ?

1) Scan when enabled will load modules from vendor and any other path provided, I've used this only once years ago to load modules from another local folder, where I have a ModulesCMS folder and a Modules folder.  

2) Looking into the source code this silences composer output by adding a `--quiet` flag

```php
/**
     * Check if composer should output anything.
     *
     * @return string
     */
    private function isComposerSilenced()
    {
        return config('modules.composer.composer-output') === false ? ' --quiet' : '';
    }
```

**Comment by yashiroiori** [comment]
> In the config/modules.php file, what are the purposes of these two properties?
> 
> 1. `scan` - is it scanning online for updates, or what exactly is it scanning for?
> 2. `composer.composer-output` - a detailed explanation, please.
> 
> Please, I recommend you reopen this issue and leave it open until it's fixed.
> 
> This is one of our challenges and should be given appropriate attention.

The problem are I have modules in version 9 and de namespace use camel case, but in new version make some changes to lower words into namespace and move models/controllers to app folder, ideal are maintain namespace to make minimun changes, I had to modify about 200 files namespace and routes for models and controllers

**Comment by dcblogdev** [comment]
@yashiroiori at first I thought your existing modules would not be affected but since the stubs have been updated it would effect commands for making new files, they would end up being created in the wrong place.

If you wanted to keep the older structure then keeping the generator paths the same as before would put generated files into the expected folders.

inside `config/modules.php`

```php
'generator' => [
    'config' => ['path' => 'Config', 'generate' => true],
    'command' => ['path' => 'Console', 'generate' => true],
    'channels' => ['path' => 'Broadcasting','generate' => false],
    'migration' => ['path' => 'Database/Migrations', 'generate' => true],
    'seeder' => ['path' => 'Database/Seeders', 'generate' => true],
    'factory' => ['path' => 'Database/factories', 'generate' => true],
    'model' => ['path' => 'Models', 'generate' => true],
    'observer' => ['path' => 'Observers', 'generate' => false],
    'routes' => ['path' => 'Routes', 'generate' => true],
    'controller' => ['path' => 'Http/Controllers', 'generate' => true],
    'filter' => ['path' => 'Http/Middleware', 'generate' => true],
    'request' => ['path' => 'Http/Requests', 'generate' => true],
    'provider' => ['path' => 'Providers', 'generate' => true],
    'assets' => ['path' => 'Resources/assets', 'generate' => true],
    'lang' => ['path' => 'Resources/lang', 'generate' => false],
    'views' => ['path' => 'Resources/views', 'generate' => true],
    'test' => ['path' => 'Tests/Unit', 'generate' => true],
    'test-feature' => ['path' => 'Tests/Feature', 'generate' => true],
    'repository' => ['path' => 'Repositories', 'generate' => false],
    'event' => ['path' => 'Events', 'generate' => false],
    'listener' => ['path' => 'Listeners', 'generate' => false],
    'policies' => ['path' => 'Policies', 'generate' => false],
    'rules' => ['path' => 'Rules', 'generate' => false],
    'jobs' => ['path' => 'Jobs', 'generate' => false],
    'emails' => ['path' => 'Emails', 'generate' => false],
    'notifications' => ['path' => 'Notifications', 'generate' => false],
    'resource' => ['path' => 'Transformers', 'generate' => false],
    'component-view' => ['path' => 'Resources/views/components', 'generate' => false],
    'component-class' => ['path' => 'View/Components', 'generate' => false],
],
```

I need to do a better job documenting this.

**Comment by solomon-ochepa** [comment]
> > In the config/modules.php file, what are the purposes of these two properties?
> > 
> > 1. `scan` - is it scanning online for updates, or what exactly is it scanning for?
> > 2. `composer.composer-output` - a detailed explanation, please.
> > 
> > Please, I recommend you reopen this issue and leave it open until it's fixed.
> > This is one of our challenges and should be given appropriate attention.
> 
> The problem are I have modules in version 9 and de namespace use camel case, but in new version make some changes to lower words into namespace and move models/controllers to app folder, ideal are maintain namespace to make minimun changes, I had to modify about 200 files namespace and routes for models and controllers

Hi, modifying existing/old modules is optional as the changes don't affect existing modules.

While developing a new module and moving forward, it's crucial to conform to Laravel's existing file structures and standards, thus necessitating these changes.

**Comment by solomon-ochepa** [comment]
> @solomon-ochepa when you say
> 
> > I've tested it and it's working perfectly.
> 
> What do you mean exactly? I've installed the package into a demo app and configured the root composer

Hi, what I mean is different.

I'm referring to the composer.json files.

Please, I'd like you to go back to the comment again - https://github.com/nWidart/laravel-modules/issues/1691#issuecomment-1817486565

> Either way, once the package finds its way in, all you have to do is add the following code to the root `composer.json` file;
>  ```json
>     "extra": {
>         "merge-plugin": {
>              "include": [
>                  "Modules/*/composer.json"
>              ]
>          }
>      },
>  ```
