### ISSUE TITLE
module:make creates "app" folder inside the module

### ISSUE THREAD

**Issue by Florian-Cullmann** [nWidart/laravel-modules#1698]
<img width="152" alt="image" src="https://github.com/nWidart/laravel-modules/assets/66006032/8438743c-35ca-4308-b21f-55211a49efdc">

According to the docs this is not normal behaviour... I just installed a fresh Laravel 10 with a simple docker setup (nginx, php8.2, mysql). After that I just installed laravel-modules and ran the command "php artisan module:make Auth"

composer.json autoload:

<img width="404" alt="image" src="https://github.com/nWidart/laravel-modules/assets/66006032/8e5383f0-15f2-413f-ad3b-3d839f8449e0">

(Even without adding "Modules" to psr-4 it's doing the same. I also did composer dump-autoload)

**Comment by Florian-Cullmann** [comment]
Apparently is this wanted behaviour in v10... 
Lucky me found configuration options in /config. (Create modules.php in there)

**Comment by solomon-ochepa** [comment]
> Author

You can change the behavior from configs.
However, it's a good practice to keep the file structure this way to comply with Laravel's standards.

**Comment by solomon-ochepa** [comment]
> Apparently is this wanted behaviour in v10... Lucky me found configuration options in /config. (Create modules.php in there)

You can change the behavior from configs.
However, it's a good practice to keep the file structure this way to comply with Laravel's standards.
