### ISSUE TITLE
Class 'Modules\App1\Http\Controllers\Module' not found

### ISSUE THREAD

**Issue by KSVQ** [nWidart/laravel-modules#170]
All went clean with install and creating modules (as we talked in the previous issue). I wanted to start exploring the methods and got this:

`Class 'Modules\App1\Http\Controllers\Module' not found`

All I did was this on App1Controller.php

```
    public function index()
    {
        $count = Module::count();
        return view('app1::index')->with('count', $count);
    }
```

I adjusted my composer file and ran the composer dump-autoload.

Is there a piece of documentation about the setup that I might be missing somewhere?

**Comment by nWidart** [comment]
Again this is not related to this package. You need to import the Module class/facade in your controller.
