### ISSUE TITLE
Proposed Version Functionality and Simplified Module Installation

### ISSUE THREAD

**Issue by imlolman** [nWidart/laravel-modules#1701]
I've been exploring nwidart-docs and have identified a couple of areas that could enhance the management of modules. 

### Suggestions

1. **Versioning with getVersion()**
   - Currently, the version details are not visible in `module.json`. 
   - **Proposal**: Incorporate version information in `module.json` and introduce a `getVersion()` function to facilitate easier tracking of module versions.

2. **Custom Metadata in `module.json`**
   - The module.json file may lack flexibility in defining custom metadata for modules.
   - **Proposal**: Expand the capabilities of `module.json` to include user-defined metadata, such as icons, images, or specific URLs (e.g., `upgradeUrl`). This addition would allow for richer and more descriptive module information, aiding in better module identification and management.

3. **Simplified Install/Uninstall Process**
   - The current system includes activate and deactivate functions, but updating or installing modules can be challenging for end user.
   - **Proposal**: Developers will Implement an upload functionality to streamline module updates. While For example, a method could be added like `Modules::install('modulepath.zip')`, where `modulepath` could be a URL or a local path, to simplify the installation process.

### Additional Notes
- I'm not sure if some of these features are already in development or exist, and I may have overlooked them. Please update me if that's the case.
- I am willing to contribute to the development of these features if they are not already planned.

Looking forward to the possibility of contributing to the nWidart project.

**Comment by imlolman** [comment]
I've checked, Custom Metadata and Versioning features already exist. 😅

I am still exploring for Installation and Upgradation process.

**Comment by solomon-ochepa** [comment]
> I've checked, Custom Metadata and Versioning features already exist. 😅
> 
> I am still exploring for Installation and Upgradation process.

Regarding the installation and upgrade, check https://github.com/joshbrw/laravel-module-installer
