### ISSUE TITLE
The Route Problem - Routes::resource()  instead Route::get() ??

### ISSUE THREAD

**Issue by manojdhrma** [nWidart/laravel-modules#1702]
> Laravel Framework 10.37.x
> Livewire v3.3.0
> nwidart laravel-Modules 10.0.4

When using this route, it is no longer works. 
`Route::get('sample', \Modules\Sample\app\Http\Controllers\HomeController::class)->name('sample');`

It gives an UnexpectedValueException as follows,
`Invalid route action: [Modules\Sample\app\Http\Controllers\HomeController]`

However, it was working correctly using the Route::get() before.

And now it seems only works for this route. 
`Route::resource('sample', \Modules\Sample\app\Http\Controllers\HomeController::class)->name('sample');`

Does this means, laravel-modules will only accept Route::resource() ?? 

Also, when creating a fresh laravel-module, the RouteServiceProvider added with hard coded url to `$moduleNamespace`.  For example,  ` protected string $moduleNamespace = 'Modules\Sample\Http\Controllers'`

Which gives the following exception
[Modules\Sample\Http\Controllers\Modules\Sample\app\Http\Controllers\HomeController] does not exist.

In order it to work, the `$moduleNamespace` must be set as empty string. Is this an issue ?

**Comment by dcblogdev** [comment]
when using the newer style of routing `([Classname::class, 'index'])` then it's best to change the namespace to null

```
protected $moduleNamespace = null;
```

It's only needed when using the old style routing Classname@method
