### ISSUE TITLE
Namespace generating issue

### ISSUE THREAD

**Issue by geass94** [nWidart/laravel-modules#1705]
When you generate something inside module, namespace has "app" in lowercase, that is not correct, it should be ucfirst "App"

**Comment by n1crack** [comment]
It was really better before. I really don't like the current directory even if simulates the laravel folder structure.

At least yes, It should be ucfirst.  It can't be assumed every module has a composer.json file.

**Comment by aliakbarazizi** [comment]
i publish the config file, and in the `config/modules.php` I fix name in all `generator`
for example
```
'factory' => ['path' => 'database/factories', 'namespace' => 'Database/Factories', 'generate' => true],
```

the real problem for me was the i didn't want to change folder to CamelCase and in the mean time I wanted CamelCase namespace,
since this library will make `composer.json` in each directory and it has all folder namespaces in it, I used composer repository like this
```
"repositories": [
        {
            "type": "path",
            "url": "Modules/*"
        }
    ],
```

Then I did require all module in composer
`composer require app/modulename`

you need to modify composer.json in each module, and also you need to add version or remove `minimum-stability` in the root composer

**Comment by solomon-ochepa** [comment]
> It was better before. I don't like the current directory, even though it simulates the laravel folder structure.
> 
> At least yes, It should be ucfirst. It can't be assumed every module has a composer.json file.

Yes, the goal of the new structure is to simulate the standard Laravel file structure.
And yes, every module requires the composer.json file.

However, you can configure every behavior from the module configure file.

**Comment by unbolt** [comment]
In my module composer.json I have the name spaces configured as so:

```
    "autoload": {
        "psr-4": {
            "Modules\\Driver\\": "",
            "Modules\\Driver\\App\\": "app/",
            "Modules\\Driver\\Database\\Factories\\": "database/factories/",
            "Modules\\Driver\\Database\\Seeders\\": "database/seeders/"
        }
    },
```

However, doing `composer dump-autoload` gives the following error:

```
Class Modules\Driver\Database\Factories\DriverFactory located in ./Modules/Driver/database/factories/DriverFactory.php does not comply with psr-4 autoloading standard. Skipping.
Class Modules\Driver\App\Models\Driver located in ./Modules/Driver/app/Models/Driver.php does not comply with psr-4 autoloading standard. Skipping.
Class Modules\Driver\App\Models\Vehicle located in ./Modules/Driver/app/Models/Vehicle.php does not comply with psr-4 autoloading standard. Skipping.
Class Modules\ExampleModule\App\Http\Controllers\ExampleModuleController located in ./Modules/ExampleModule/app/Http/Controllers/ExampleModuleController.php does not comply with psr-4 autoloading standard. Skipping.
```

How do I get the composer.json in the root to account for those in the modules? Should that be happening automatically for the namespacing to work?

**Comment by dcblogdev** [comment]
I recommend going back to use `App` and `Database` for the namespaces and folder names. It's far simpler, it can all be done by updating your config file for new modules. No core changes are required.

Anyone that wants to use lowercase or uppercase can freely update their configuration. See https://github.com/nWidart/laravel-modules/issues/1719 for an example.
