### ISSUE TITLE
Unable to Publish "beyondcode/laravel-ask-database" Package in AskQuestion Module

### ISSUE THREAD

**Issue by Rushita-Ginoya** [nWidart/laravel-modules#1706]
I'm encountering difficulties while attempting to integrate the "beyondcode/laravel-ask-database" package into my AskQuestion module. Here's a breakdown of the steps I've followed:

Updated the composer.json file in the AskQuestion module with the correct package name and verified versions.
Navigated to the module directory [/Module/AskQuestion] and executed "composer install" to install the package.
Went to the project directory [/Project] and ran the command "php artisan module:update AskQuestion" to ensure the module is updated.

However, I'm facing an issue when trying to publish the "laravel-ask-database" package within the AskQuestion module. Despite attempting manual registration of package providers, aliases, and configuration in the module's service provider file, the package doesn't seem to load in the module.

Even after manual registration steps, the package is not loaded within the AskQuestion module.

Any guidance or assistance in resolving this issue would be greatly appreciated.

**Comment by dcblogdev** [comment]
Could you provide a public repo so I can look into what you've tried.
