### ISSUE TITLE
Problem with WebSockets

### ISSUE THREAD

**Issue by KatiaSishost** [nWidart/laravel-modules#1707]
i have a ChatController, MessageController

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\User;
use App\Models\Chat;

class ChatController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function chat_with(User $user)
    {

        $user_a = auth()->user();

        $user_b = $user;

        $chat = $user_a->chats()->wherehas('users', function ($q) use ($user_b) {

            $q->where('chat_user.user_id', $user_b->id);
        })->first();

        if (!$chat) {

            $chat = Chat::create([]);

            $chat->users()->sync([$user_a->id, $user_b->id]);
        }

        return redirect()->route('chat.show', $chat);
    }

    public function show(Chat $chat)
    {

        abort_unless($chat->users->contains(auth()->id()), 403);

        return view('chat', [
            'chat' => $chat
        ]);
    }

    public function get_users(Chat $chat)
    {

        $users = $chat->users;

        return response()->json([
            'users' => $users
        ]);
    }

    public function get_messages(Chat $chat)
    {

        $messages = $chat->messages()->with('user')->get();

        return response()->json([
            'messages' => $messages
        ]);
    }
}

```

MessageController:

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Events\MessageSent;



class MessageController extends Controller
{
    public function __construct()
	{
		$this->middleware('auth');
	}


	public function sent(Request $request)
	{

		$message = auth()->user()->messages()->create([
			'content' => $request->message,
			'chat_id' => $request->chat_id
		])->load('user');

		broadcast(new MessageSent($message))->toOthers();

		return $message;

	}
}

```

This Models Chat.php

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Chat extends Model
{
    use HasFactory;

    public function users()
    {
    	return $this->belongsToMany('App\Models\User');
    }

    public function messages() 
    {
    	return $this->hasMany('App\Models\Message');
    }
}

```

Message.php

`<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    use HasFactory;

    protected $fillable = [
    	'content',
    	'chat_id',
    ];

    public function user()
    {
    	return $this->belongsTo('App\Models\User');
    }

    public function chat()
    {
    	return $this->belongsTo('App\Models\Chat');
    }
}
`

User.php

`<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function chats()
    {
        return $this->belongsToMany('App\Models\Chat');
    }

    public function messages()
    {
        return $this->hasMany('App\Models\Message');
    }
}
`

Event:

`<?php

namespace App\Events;

use Illuminate\Broadcasting\Channel;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

class MessageSent implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $message;

    /**
     * Create a new event instance.
     */
    public function __construct($message)
    {
        $this->message = $message;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return array<int, \Illuminate\Broadcasting\Channel>
     */
    public function broadcastOn()
    {
        return new PresenceChannel('chat.' . $this->message->chat_id);
    }
}
`

routes/Channels.php

```
Broadcast::channel('chat.{chat_id}', function ($user, $chat_id) {

	if($user->chats->contains($chat_id)){

		return $user;

	}

});
```

routes/web.php

`Route::get('auth/user', function () {

	if(auth()->check()){

		return response()->json([
			'authUser' => auth()->user()
		]);

		return null;

	}

});

Route::get('chat/{chat}', 'App\Http\Controllers\ChatController@show')->name('chat.show');

Route::get('chat/with/{user}', 'App\Http\Controllers\ChatController@chat_with')->name('chat.with');

Route::get('chat/{chat}/get_users', 'App\Http\Controllers\ChatController@get_users')->name('chat.get_users');

Route::get('chat/{chat}/get_messages', 'App\Http\Controllers\ChatController@get_messages')->name('chat.get_messages');

Route::post('message/sent', '\App\Http\Controllers\MessageController@sent')->name('message.sent');`

Without Modules, all work perfectly...

It's very strange, but when creating the controllers within the Modules, the models and the event and their routes...

I enter the chat, the room is created correctly, the event is sent, the event is executed... but the messages are not updated in real time... (only the sent ones)

I must update the website so that the received messages are shown...

It should be noted that without using Modules, everything works perfectly.

**Comment by KatiaSishost** [comment]
UPDATE:

The problem is when I place the MessageSent event with 

`php artisan module:make-event MessageSent ModuloChat`

but if I leave the MessageSent event in root/app/Events/MessageSent.php everything works correctly



my root/app/Events/MessageSent.php

`<?php

namespace App\Events;

use Illuminate\Broadcasting\Channel;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

class MessageSent implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $message;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($message)
    {
        $this->message = $message;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new PresenceChannel('chat.' . $this->message->chat_id);
    }
}
`


My Modules\Chat\app\Events\MessageSent.php

`<?php

namespace Modules\IncidentManager\app\Events;

use Illuminate\Broadcasting\Channel;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

class MessageSent implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $message;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($message)
    {
        $this->message = $message;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new PresenceChannel('chat.' . $this->message->chat_id);
    }
}
`

**Comment by KatiaSishost** [comment]
re open.

**Comment by dcblogdev** [comment]
I'll look into this, I'll do some testing with events.

**Comment by dcblogdev** [comment]
I don't see a section where you register the event in a module, ensure you register the event in an EventServiceProvider.

**Comment by KatiaSishost** [comment]
> I don't see a section where you register the event in a module, ensure you register the event in an EventServiceProvider.

can you send me an example of the next steps?

im confusing how to make this ^^...
