### ISSUE TITLE
Publishing a package issue

### ISSUE THREAD

**Issue by 66a066** [nWidart/laravel-modules#1708]
I have installed a package in a module named as PageBuilderModule. I have installed a package in its vendor folder by going into the directory of module..The problem now i am facing is i am unable to publish the package in my PageBuilderModule..Can you please guide me how can i successfully publish  that package files from the vendor directory of the module to the module itself? The package i want to publish is using is hansschouten/laravel-pagebuilder..

**Comment by dcblogdev** [comment]
sorry I'm not sure I understand, can you elaborate?

**Comment by 66a066** [comment]
Thanks for your reply..My question was regarding the package install via
composer ..I have an requirements in which i have to install a
package inside my module ..The package successfully installed by going into
the module composer but the problem i am facing is i cannot able to vendor
publish and get all the classes inside the module provider so i can use
them..Means Publishing a vendor  inside module is possible or not?

**Comment by dcblogdev** [comment]
Sorry no its not possible, composer will install package into the vendor, We use a third party package that allows modules when installed as packages to be moved into the modules folder but that's only for module packages.
