### ISSUE TITLE
Extract CSS out when getting assets from Modules

### ISSUE THREAD

**Issue by jaymeh** [nWidart/laravel-modules#1711]
I've been following the documentation for modules to utilise the new Vite features that allow modules to expose their code via the `vite.config.js` file on each module. Whilst it took a while to get to grips with and understand I like the way it is implemented and how easy it is to get setup once you understand the underlying process.

One of the issues I am currently looking into is that when a page loads because the`@vite(\Nwidart\Modules\Module::getAssets())` line is added towards the end of our layout file, the page flashes some unstyled elements before everything pops into place. This isn't the end of the world but it does feel a little strange when viewing our site.

I often would load our CSS at the top of the HTML files and the JS at the bottom but because Laravel modules is controlling this process and just adding everything at the bottom, I can't selectively pick what goes in the header and what goes in the footer. Currently, I can only move all CSS and JS to the header or leave it the way it is.

There are some workarounds I have found like hardcoding some of the CSS files to load in through vite in the header (the browser theoretically shouldn't load them twice) but I'm keen to hear some thoughts on any ways this experience can be improved. Perhaps some kind of whitelist/blacklist or additional optional configuration I can pass to split the assets differently and pull them into the layout file.

Thanks

**Comment by dcblogdev** [comment]
As you've mentioned the asserts are grouped together, I wonder if there is a way to identify CSS and JS independently then I could add a way to specify the type of build to load.

It's worth trying to see if there is a way for this.
