### ISSUE TITLE
[Docs] Broken link to explanation article

### ISSUE THREAD

**Issue by simonebogni** [nWidart/laravel-modules#1714]
Hi, I was reading the docs at https://laravelmodules.com/docs/v10/introduction and I noticed that the link to the article is broken.
When visiting "[Writing modular applications with laravel-modules](https://nicolaswidart.com/blog/writing-modular-applications-with-laravel-modules)", we can see the following error message:
<img width="985" alt="Screenshot 2024-01-14 at 17 19 56" src="https://github.com/nWidart/laravel-modules/assets/24236393/4a9cbc92-cabe-444e-a1eb-e90aef0c0a06">

**Comment by dcblogdev** [comment]
Unfortunately I can't fix that I only host laravelmodules.com @nWidart are you able to fix your site?

**Comment by dcblogdev** [comment]
I'll close this as there is nothing I can do.

**Comment by runofthemill** [comment]
Noting I just ran into this as well; I was able to find what I assume is another copy of the article at https://www.programmersought.com/article/18072634173/ - maybe the link could be updated to point there?
