### ISSUE TITLE
TailwindCSS not working in Modules

### ISSUE THREAD

**Issue by jobasc0** [nWidart/laravel-modules#1715]
Hi, i have noticed that taillwind css is not working in my modules recently, i have also make a fresh laravel install today but the problem is the same.
Here is my setup

tailwind.config.js;
```js
`import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './Modules/**/*.blade.php',
        "./node_modules/tw-elements/dist/js/**/*.js",
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [forms],
};
```

Module app.css file:

```css
`@import "tailwindcss/base";
@import "./style.css";
@import "./color.css";

@import "tailwindcss/components";
/* @import "./custom-components.css"; */

@import "tailwindcss/utilities";
/* @import "./custom-utilities.css"; */`
```

Module Layout master.blade.php file:

`{{ module_vite('build-core', 'resources/assets/css/app.css') }}`

Module vite.config.js file:

```js
`import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    build: {
        outDir: '../../public/build-core',
        emptyOutDir: true,
        manifest: true,
    },
    plugins: [
        laravel({
            publicDirectory: '../../public',
            buildDirectory: 'build-core',
            input: [
                __dirname + '/resources/assets/css/app.css',
                __dirname + '/resources/assets/js/app.js'
            ],
            refresh: true,
        }),
    ],
});

//export const paths = [
//    'Modules/$STUDLY_NAME$/resources/assets/sass/app.scss',
//    'Modules/$STUDLY_NAME$/resources/assets/js/app.js',
//];`
```

Please what am i doing wrong? 
Please help.

**Comment by dcblogdev** [comment]
I would install Tailwind into the main project then have your modules either use the classes in the normal way or have only the files passed to the global vite file:

```js
export const paths = [
    'Modules/$STUDLY_NAME$/resources/assets/sass/app.scss',
    'Modules/$STUDLY_NAME$/resources/assets/js/app.js',
];
```

You can do all the steps above but Tailwind does not update the generated build files, it may be possible by telling Tailwind where to look, but it's beyond the scope of what you get out the box.

**Comment by jobasc0** [comment]
> I would install Tailwind into the main project then have your modules either use the classes in the normal way or have only the files passed to the global vite file:
> 
> ```js
> export const paths = [
>     'Modules/$STUDLY_NAME$/resources/assets/sass/app.scss',
>     'Modules/$STUDLY_NAME$/resources/assets/js/app.js',
> ];
> ```
> 
> You can do all the steps above but Tailwind does not update the generated build files, it may be possible by telling Tailwind where to look, but it's beyond the scope of what you get out the box.

Runing npm build in inside module directory gives me this response.
`warn - The `content` option in your Tailwind CSS configuration is missing or empty.
warn - Configure your content sources or your generated CSS will be missing styles.
warn - https://tailwindcss.com/docs/content-configuration`
