### ISSUE TITLE
Can we duplicate a new module?

### ISSUE THREAD

**Issue by muhammadalifh** [nWidart/laravel-modules#1717]
Hello, I have just learned about Laravel modules, and I have created a module named "employee." My client has requested me to create a similar module to "employee." Is there a way I can save time, perhaps by cloning or copying the "employee" module with a different name?

**Comment by dcblogdev** [comment]
There are no copy or clone commands so you would have to copy the module and give it a new name. Then manually update the classes namespaces and update the modules composer file.

**Comment by dcblogdev** [comment]
You may find this package useful https://github.com/dcblogdev/laravel-module-generator it allows you to set a base module as a template.

**Comment by muhammadalifh** [comment]
@dcblogdev Thank you for your response, it seems like the package is useful, I'll give it a try.

**Comment by solomon-ochepa** [comment]
I have built commands for copying and moving modules. I'll share the code with the community now.
