### ISSUE TITLE
How to handle node_modules hell if dependencies are common?

### ISSUE THREAD

**Issue by veodko** [nWidart/laravel-modules#1718]
I'm starting to use laravel-modules and I'm liking it so far, though I noticed something that is kinda problematic IMO.

The fact that each module can have it's own nodejs dependencies is great, but I quickly figured out that it turns into a massive hell once you have common dependencies between the modules or the main app.

Let's say that 10 of your modules use axios, or vite or whatever. Your main app also uses axios/vite so it has it already in the main `node_modules` directory.
You can import axios in the module, and it will work well after `npm run build` because it's gonna take it from the top-level `node_modules` directory. Unless you use `npm i` in the module, then you start doubling everything and end up with 11 axios directories in the file tree and a project that will soon be X GB in size.

Not only that, the client-side JS bundles will also have doubled Axios (or whatever else you import) code. While `node_modules` size is not a big deal, this seems like something that is completely unacceptable in a real-world scenario. You'll end up with a crazy big, slow piece of garbage the more stuff you add. Matter of fact, it will happen anyway even if you just import modules from the top-level `node_modules`, they will end up being bundled multiple times instead of being shared (as a separate asset?)

How do you handle this in your projects? There must be some better way.. only thing I can think of atm is to import such stuff in the main app layout/view and expose it in `window`, but this is ugly and results in no intellisense when coding modules.

I found a similar closed issue here: https://github.com/nWidart/laravel-modules/issues/909 which kinda references this problem but has very little detailed information and no solution at all

**Comment by dcblogdev** [comment]
I don't use any assets from modules, I install them into the global package.json and composer.json files. To me it's not worth the hassle.

There is a merge composer package that can be installed but I don't know of anything like that for node.

**Comment by veodko** [comment]
> I don't use any assets from modules, I install them into the global package.json and composer.json files. To me it's not worth the hassle.
> 
> There is a merge composer package that can be installed but I don't know of anything like that for node.

What are you using for rendering module views? Plain blade or some JS framework that requires a build step?

**Comment by dcblogdev** [comment]
My modules use blade files that use a layout from the main `resources/views/layout/app`

That layout uses

```php
@vite(['resoursces/sass/app.scss', 'resources/js/app.js'])
```

My modules mostly Livewire based on the classes load a main layout using `->layout('layouts.front')`

When I make any style changes I run the `npm run build` to recompile or dev if I'm making a lot of changes.
