### ISSUE TITLE
module:migrate command returns 'The "--path" option does not exist.' error

### ISSUE THREAD

**Issue by giacomomasseron** [nWidart/laravel-modules#1722]
Hi,  
the command:

    php artisan module:migrate MyModule

returns the error:

> The "--path" option does not exist.

I am not able to figure out if it's a package error or my error.

**Comment by dcblogdev** [comment]
I think it may be something in your application, so there anything in the stack trace that may help identify the issue?

**Comment by giacomomasseron** [comment]
I do not have any other error message.

The only thing I'm thinking is that the module does not have new folder structure (inside "app" folder).

I created the module with prev version of package, so the module does have this structure:

```
ModuleName
    Config
    Console
    ...etc

```

**Comment by giacomomasseron** [comment]
The error starts from "MigrateCommand.php" file, line 73:

```
$this->call('migrate', [
            '--path' => $path,
            '--database' => $this->option('database'),
            '--pretend' => $this->option('pretend'),
            '--force' => $this->option('force'),
        ]);
```

**Comment by giacomomasseron** [comment]
10.0.4

**Comment by dcblogdev** [comment]
Does this happen on a fresh installation? I'm not sure what could be the cause, I have multiple projects but can't reproduce the error.

**Comment by giacomomasseron** [comment]
I tried these commands:

    composer create-project laravel/laravel example-app
    composer require nwidart/laravel-modules
    php artisan module:make Blog
    php artisan module:migrate Blog

I get this error:

> Class "Modules\Blog\App\Providers\BlogServiceProvider" not found

**Comment by dcblogdev** [comment]
ensure you've added the autoloading for modules to composer.json

```php
"autoload": {
    "psr-4": {
        "App\\": "app/",
        "Modules\\": "Modules/",
        "Database\\Factories\\": "database/factories/",
        "Database\\Seeders\\": "database/seeders/"
    }
},
```

**Comment by giacomomasseron** [comment]
You right. And it works from fresh installation :(

I'm still not able to understand why does not work in the other project.

**Comment by dcblogdev** [comment]
I'm not sure either, try copying over the modules and take it from there.

**Comment by dcblogdev** [comment]
nice, glad you got to the bottom of it.

**Comment by giacomomasseron** [comment]
My question now is:
how can I disable laravel `migrate` command and still use my command?

**Comment by dcblogdev** [comment]
this is actually a base Laravel issue, what you can do is in your custom command define the path option:

```php
protected $signature = 'app:migrate {--path= : The path to the migrations}';
```

Then if you do want to use the path you can do something like this inside the handle method

```php
$path = $this->option('path') ?: 'default_migration_path'; // Set your default migration path if --path is not provided
$this->comment("Running migrations from path: $path");

// Your custom logic here

// Example: Calling module:migrate with the specified path
$this->call('module:migrate', ['--path' => $path]);
```
