### ISSUE TITLE
An option shortcut cannot be empty.

### ISSUE THREAD

**Issue by Renato27** [nWidart/laravel-modules#1728]
I'm using "nwidart/laravel-modules": "^8.0" in my project laravel with PHP 7.4. 
The error "An option shortcut cannot be empty" It's started today. 
I saw that was fixed a similiar issue on v8.4, but It doesn't work to my project in PHP 7.4.

**Comment by dcblogdev** [comment]
this stems from an internal change in https://github.com/symfony/symfony/pull/53516 will get the branches updated, looking at v7+

**Comment by sagar-patona** [comment]
i am also getting the same issue.

i am using I'm using "nwidart/laravel-modules": "8.2"

![image](https://github.com/nWidart/laravel-modules/assets/142371178/2a24a26e-9afc-44c0-9d35-734f4d72fbdd)

**Comment by emyu01** [comment]
I am also getting same issue

**Comment by dzung1nguyen** [comment]
Same error in v8.3.0 with laravel 8 and php 8.1
if v8.4.0, i got error: 
![image](https://github.com/nWidart/laravel-modules/assets/14831468/07397eb1-60d6-45cf-a501-459623274165)

**Comment by suryakaritva** [comment]
Same error for me all of a sudden in laravel 7.2
 Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
                                      
  An option shortcut cannot be empty.                                      

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by dcblogdev** [comment]
waiting on https://github.com/symfony/symfony/pull/53711 this should resolve the issue.

**Comment by jayminsilicon** [comment]
@dcblogdev Symfony PR is merged now however release will happen in upcoming days as 5.4.35. Ref : https://github.com/symfony/symfony/pull/53711#issuecomment-1921340193
Meanwhile can we make release of last pr https://github.com/nWidart/laravel-modules/pull/1730  ?

Thanks

**Comment by dcblogdev** [comment]
for now for versions 7 & 8 the symfony update can be skipped by adding into composer.json

```bash
"conflict": {
    "symfony/console": "5.4.35"
  }
  ```
  
  For version 8 set the version specifically 
  ```bash
  "nwidart/laravel-modules": "8.3"
  ```
  
  https://stackoverflow.com/questions/77918736/laravel-composer-install-suddenly-returns-an-option-shortcut-cannot-be-empty/77920770#77920770

**Comment by aghoshsuraj555** [comment]
@dcblogdev is there any permanent solution for this.
I tried your above solution but it will not be help after deleting vendor file and composer.lock.
so is there permanent solution for this.

**Comment by azeiee1010** [comment]
I have tried a  solution.

1. Created a customTestMakeCommand and extends the TestMakeCommand.
2. Override the getOptions function
` protected function getOptions()
    {
        return [
            ['feature', null, InputOption::VALUE_NONE, 'Create a feature test.'],
        ];
    }`
 3. Bind it in AppServiceProvider
 > $this->app->bind(TestMakeCommand::class, CustomTestMakeCommand::class);

3. It worked locally for me. Now getting an issue on my deployment side. If that is fixed then it could be a solution.

**Comment by opusaha** [comment]
I am also getting same issue

@php artisan package:discover --ansi

**Comment by dcblogdev** [comment]
okay, I'll need to figure out how to do a release for 2 versions back. Every time I've tried to do a release manually its included the recent changes.

I was hoping Symfony was going to do an immediate release but looks like that's not going to happen for a few weeks.

**Comment by dcblogdev** [comment]
I've released 2 new versions please update:

V7 use https://github.com/nWidart/laravel-modules/releases/tag/7.4.0
v8 use https://github.com/nWidart/laravel-modules/releases/tag/8.6.0
