### ISSUE TITLE
Interface "Illuminate\Contracts\Console\PromptsForMissingInput" not found

### ISSUE THREAD

**Issue by Renato27** [nWidart/laravel-modules#1729]
![image](https://github.com/nWidart/laravel-modules/assets/54475563/799bc00f-244e-40d7-bba2-8ef9f4a7f13d)

Now I'm using PHP 8.1 for to use the release 8.4, but I'm receiving this error.

**Comment by dcblogdev** [comment]
there's something wrong with the 8.4 release it contains changes meant for recent versions, looking into it.

**Comment by jyxjjj** [comment]
https://github.com/nWidart/laravel-modules/pull/1730

**Comment by opuu** [comment]
Getting the same error on php 8.3

**Comment by RamilYanEh** [comment]
> there's something wrong with the 8.4 release it contains changes meant for recent versions, looking into it.

Yes I think some of the commits for 10.x is included into 8.x

**Comment by KevalPanchalSilicon** [comment]
@dcblogdev 
We also have the same error when we update the package 8.2 to 8.4. 
I used Laravel version 8.X and PHP version 8.1.*

**Comment by dcblogdev** [comment]
waiting on https://github.com/symfony/symfony/pull/53711 this should resolve the issue.

**Comment by dcblogdev** [comment]
Revert to 8.3 since 8.4 will break the application, once the PR on Symfony is released I think that will sort it.

**Comment by Renato27** [comment]
> Revert to 8.3 since 8.4 will break the application, once the PR on Symfony is released I think that will sort it.

I tried that, but the erro "An option shortcut cannot be empty." returned. In this case I used PHP 8.1.27, Laravel 8.83.27 and  nwidart/laravel-modules 8.3.0.

**Comment by dcblogdev** [comment]
Yes the symphony release is still open, it won't be fixed until that's been released

**Comment by filip-stojkovski-adeva** [comment]
@dcblogdev just a heads up: it's merged

**Comment by dcblogdev** [comment]
All good now?

**Comment by filip-stojkovski-adeva** [comment]
I tried updating the package, still get the same error on 8.5.0

**Comment by RamilYanEh** [comment]
I tried also updating the package nothing changes; still have the same error

**Comment by RamilYanEh** [comment]
Correct me if I am wrong ... Is this the issue ? i saw from the package's composer.json
![image](https://github.com/nWidart/laravel-modules/assets/97419690/a162c5d9-9075-4742-86bf-10515f1c9c76)

**Comment by dcblogdev** [comment]
See https://github.com/nWidart/laravel-modules/issues/1728#issuecomment-1921445620 I'll close this as its essentially the same thing as the other issue.

**Comment by sergeich5** [comment]
This helps:

in `composer.json` add

```
"conflict": {
  "symfony/console": "5.4.35"
},
```

and in `require` section use exactly 8.3 version
`"nwidart/laravel-modules": "8.3"`
