### ISSUE TITLE
Load original routes files?

### ISSUE THREAD

**Issue by jaumeavila** [nWidart/laravel-modules#173]
In the company where I work, we are creating the Laravel application with modules to be able to create microservices afterwards.
We use routes for each module (which works great), but we would like to get some routes in original /routes folder at the root level.

I have made some tests and if I put a post route there it does not get called, whereas inside a module it does.

Is there a way to load them or should I create like a common module?

Thanks!

**Comment by nWidart** [comment]
You can use the usual route indeed. Make sure they are loaded in the laravel service provider. https://github.com/laravel/laravel/blob/master/app/Providers/RouteServiceProvider.php

**Comment by jaumeavila** [comment]
Yes, I have it like this.
But nevertheless something seems wrong.
But I don't think it has anything to do with your package, so closing the issue.

Thanks!

Jaume

**Comment by nWidart** [comment]
Indeed, this doesn't interfere with the usual laravel way of loading routes. Feel free to let others know what the issue was/is when you figured it out. 👍
