### ISSUE TITLE
Failed to load module script for static assets such as images

### ISSUE THREAD

**Issue by reecehill** [nWidart/laravel-modules#1731]
Hey,

I currently have v10.0.5 of Laravel modules installed, alongside Vite v5, Vue v3 (with Typescript).

It works amazingly together, thank you!

### The problem 
However, with the default installation the browser console prints errors for any static asset, for example:

> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "image/**svg**+xml". Strict MIME type checking is enforced for module scripts per HTML spec.

> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "image/**jpeg**". Strict MIME type checking is enforced for module scripts per HTML spec.

> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "image/**png**". Strict MIME type checking is enforced for module scripts per HTML spec.

These errors are caused by Vite's insertion of the following into DOM:

> <script type="module" src="REDACTED.svg"></script>

### Solution

The issue lies in \Nwidart\Modules\Module::getAssets()
It returns **every** file as an entry point... is this intended? For my project, it doesn't make sense for static resources such as those above to be passed to Vite (and it only leads to a large bundle size!)

So, I've changed the function to be as follows:

```
    public static function getAssets(): array
    {
        $paths = [];

        if (file_exists('build/manifest.json')) {
            $files = json_decode(file_get_contents('build/manifest.json'), true);

            if (is_array($files)) {
                foreach ($files as $file) {

                    if (
                        isset($file['src'])
                       && (isset($file['isEntry']) || isset($file['isDynamicEntry]'])) // check if entry point!!
                    ) {
                        $paths[] = $file['src'];
                    }
                }
            }
        }

        return $paths;
    }
```

Hope this is helpful to some people!

**Comment by dcblogdev** [comment]
Glad to hear it's working apart from the images. I'm away for the next few days, can you raise a PR for this?
