### ISSUE TITLE
Composer template not updated after App and Database folder capitalisation change

### ISSUE THREAD

**Issue by jaymeh** [nWidart/laravel-modules#1734]
I've been using the new template from version 10.0.6, I can see that the App and Database folders have changed their capitalisation. Within the Composer file, I noticed that it still uses the old capitalisation whereas the files are in the new format. See the screenshots attached.

![CleanShot 2024-02-05 at 10 29 19](https://github.com/nWidart/laravel-modules/assets/18261676/bb1188ce-478a-46f6-83b5-813ec34d8550)
![CleanShot 2024-02-05 at 10 28 13](https://github.com/nWidart/laravel-modules/assets/18261676/9d178112-64c2-48ed-820b-fac3c51aeafc)

Thanks

**Comment by dcblogdev** [comment]
I don't think it really matters, seems to work in either case for me. You can change them in the stubs composer.json file for new modules and manually update on existing modules.
