### ISSUE TITLE
Config Module

### ISSUE THREAD

**Issue by LeonardoAthayde** [nWidart/laravel-modules#174]
How can I acsess the config values of specific module?

**Comment by mikemand** [comment]
```php
config('modulename::filename.key')
```

For example:

```php
config('blog::settings.disqus.api-secret')
```

**Comment by LeonardoAthayde** [comment]
Thanks a lot!!!

**Comment by LeonardoAthayde** [comment]
I published the config file, so I can access the value by config('base.name')

Is that a good way?

**Comment by mikemand** [comment]
It all depends on how you set up the config to be published in your service provider. I was also wrong earlier: Laravel does not namespace configs. So yes, `base.name` is correct if your published config is at `/config/base.php`

**Comment by LeonardoAthayde** [comment]
Yes I understand, one more thing, because I miss something.

It's about what you said previusly, "Make sure that your module's Service Provider "provides" the config.".

I am a newer on Laravel Framework, and I would like to know, what code I need to put on my module ServiceProvider to load the config files?

Thanks!

**Comment by mikemand** [comment]
From here: https://laravel.com/docs/5.4/packages#configuration

Make sure your Service Provider `publishes` the config, as well as `mergeConfigFrom` (so the config file doesn't *have* to be published, unless you need to change some setting).
