### ISSUE TITLE
migrate first module only

### ISSUE THREAD

**Issue by greatsami** [nWidart/laravel-modules#1743]
![Screenshot from 2024-02-14 17-33-14](https://github.com/nWidart/laravel-modules/assets/11071915/1887cba2-757f-4654-8334-87764f14d35a)

I'm facing strange something:
As you see in the image I moved users migrations to User module, also I removed the database and factories from composer.json from autoload part. 
when I run php artisan migrate:fresh --seed (amigfs in the image), 
It should not migrate the modules databases, Right?

- it migrate User Module tables.
- and migrate (failed_jobs, settings, media) from the Laravel migration folder
- skip the second module database tables.
after that it show error (Target class [DatabaseSeeder] does not exist)

I added to composer classmap to autoload part, It solved the above error.
```
"autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/",
            "Modules\\": "Modules/"
        },
...
}
```

but also not seeded the User module.

Note: if I run (php artisan module:migrate --seed User & php artisan module:migrate --seed Blog)  it works fine.

I need when I run (php artisan migrate:fresh --seed) that migrate (failed_jobs, settings, media) with thier seeds only.

**Comment by alissn** [comment]
Hi,

when you call `php artisan migrate:fresh --seed`, the seed data is generated using this section of the Laravel framework:

https://github.com/laravel/framework/blob/cf9513219e80608aded783e33a30f8e8d145f6c2/src/Illuminate/Database/Console/Migrations/FreshCommand.php#L91-L98

By default, when the `--seeder` option is not passed, the command uses the `Database\Seeders\DatabaseSeeder` class.

To use this with a modular system, you have two options:

1. Pass the seeder class when calling the command:
   ```sh
   php artisan migrate:fresh --seed --seeder="Modules\Base\Database\Seeders\DatabaseSeeder"
   ```

2. Or bind the `Database\Seeders\DatabaseSeeder` class to your target class. To do this, add the following line to the `BaseServiceProvider.php` file in the `register` method:
   ```php
   public function register()
   {
       $this->app->bind(
           'Database\\Seeders\\DatabaseSeeder', 
           \Modules\Base\Database\Seeders\BaseDatabaseSeeder::class
       );
   }
   ```
   Replace `\Modules\Base\Database\Seeders\BaseDatabaseSeeder::class` with your desired class. In this example, I used the Base Module.

**Comment by greatsami** [comment]
Thank you for reply.

In the first, 
I moved Users to User module and i set the priority 10000 in User/module.json.
I moved Setting to Setting module  and i set the priority 9999 in Setting/module.json.
I moved Blog to Blog module  and i set the priority 9998 in Blog/module.json.

Then I apply the second option you mentiond, its success in migration and UserDatabaseSeeder only.
How to resolve it to seed other modules?

**Comment by alissn** [comment]
@greatsami 
When binding seeders to the base, you need to locate the seeders from modules and call them. I've provided a sample code snippet below that utilizes the `glob` function to find seeders, converts them to namespaces, and then calls the seeders.

```php
$files = glob(base_path('Modules/*/Database/Seeders/*.php'));

$seeders = array_map(function ($item) {
    return str_replace(['/', '.php'], ['\\', ''], ltrim($item, base_path()));
}, $files);

$this->call($seeders);
```

**Comment by greatsami** [comment]
Thank you @alissn 
Its work :)
