### ISSUE TITLE
Performance issue after creating 100+ Module

### ISSUE THREAD

**Issue by alpeshrajodiya94** [nWidart/laravel-modules#1745]
Hello,

I wanted to express my gratitude for the outstanding package provided.

While utilizing it, we've developed over 100 modules. However, we've encountered speed/performance issues. Our investigation revealed that the package loads all modules on every page during Laravel's boot process. For instance, on pages like the Login page, not all modules are necessary to load. Is there a way to skip loading certain modules selectively? For example, on Module 1's webpage, Module 10 isn't required, so can we skip it during the boot method?

We welcome any suggestions or insights from those who may have encountered similar challenges.

Thank you.

**Comment by kjostling** [comment]
Could Laravel octane be a solution? That would only boot you app once at startup. But, with 100+ modules I guess it's hard to tell if the app comply to the "dos and donts". 

I usually remove stuff in the modules service provider that isnt needed for that specific module. For instance scanning for migrations in a folder is expensive, views aswell. 
  
Otherwise perhaps its time to split the monolith into smaller pieces. 100+ modules, thats impressive!

**Comment by xavi7th** [comment]
@dcblogdev when you say you enabled caching, can you please share some insights on the caching strategy you implemented?

I am having the same issues with load time also and I might benefit greatly from some insights you share.

Thanks in advance.

**Comment by CasonWebDev** [comment]
I'm planning to construct a large application here where i work using modules with this library in my laravel project, knowing the quantity of modules can cause lower performance, i'm thinking to up my application in kubernetes pods where i'll isolate deployments by concerns, and depending of the concern i can disable a set of modules i'll not use in that concern, in this way i believe i'll able to stay working with multiple modules but enabling that group i'll need in certain concern or not.
This architecture my make sense to you too. 

The command to disable modules is available in the library with php artisan module:disable <module>

**Comment by SneherAdor** [comment]
> I then enabled caching load time went down to around 800 miliseconds.

It also works for me by enabled cache on modules configuration files.

**Comment by kjostling** [comment]
I get the following stats roughly:
Clean install 0 modules: **75ms**
Created 150 modules: **11s**
Installed octane+swoole: **30ms**
Starting tinker: **11s**
Schedule run: **11s**

Running scheduler (and tinker) with swoole takes about the same time as loading a page without swoole, which indicate that it's executing register & boot. If a slow scheduler is a problem one could perhaps rely on ticks & intervals in swoole rather then externally executed crontasks. 

It's perhaps not a solution to the "make many modules fast" problem, rather a workaround.

**Comment by alpeshrajodiya94** [comment]
Thank you for your feedback/comments.

I'm considering if it's possible to skip loading modules based on the route. Instead of loading all modules during the boot method, we could determine which module loads on which URL or route.

For instance, we have modules named Google 2FA, Sales, Purchase, etc. Upon login, we can load Google 2FA. On the dashboard page, we can load all modules. On the Sales page route, we would load only the Sales module (skipping Google 2FA).

Any luck on this suggestion?

**Comment by solomon-ochepa** [comment]
> I'm planning to construct a large application here where i work using modules with this library in my laravel project, knowing the quantity of modules can cause lower performance, i'm thinking to up my application in kubernetes pods where i'll isolate deployments by concerns, and depending of the concern i can disable a set of modules i'll not use in that concern, in this way i believe i'll able to stay working with multiple modules but enabling that group i'll need in certain concern or not. This architecture my make sense to you too.
> 
> The command to disable modules is available in the library with php artisan module:disable

I'll recommend you try microservices! Every module is a potential microservice. If anyone needs help in breaking your app down to microservices, I and my team will be more than willing to help.

**Comment by solomon-ochepa** [comment]
> Hello,
> 
> I wanted to express my gratitude for the outstanding package provided.
> 
> While utilizing it, we've developed over 100 modules. However, we've encountered speed/performance issues. Our investigation revealed that the package loads all modules on every page during Laravel's boot process. For instance, on pages like the Login page, not all modules are necessary to load. Is there a way to skip loading certain modules selectively? For example, on Module 1's webpage, Module 10 isn't required, so can we skip it during the boot method?
> 
> We welcome any suggestions or insights from those who may have encountered similar challenges.
> 
> Thank you.

I'll definitely advise you to try microservices! Like I said earlier, every module is a potential microservice.

If you or anyone else need help to convert your app into microservices, I and my team will be more than willing to help.

**Comment by Wulfheart** [comment]
I can confirm this issue. I took a barebones repo and only added fifteen modules. This package took 150ms, around 80ms with cache, while internachi/modular has no measurable performance overhead whatsoever. To give you a baseline: On a bare Laravel application the booting process takes about 13ms. Yes, I could disable XDebug and all that stuff but I think it highlights the performance issue quite well.

**Comment by enterprime** [comment]
When looking at the file upload and the capabilities of the nwidart/modules package in Laravel, I can conclude that during the initial module creation and basic configuration, a plethora of processes are registered.

For instance, consider a package for an online store or an administrative module where migrations are created, followed by additional modules such as search, cart, personal account, and so forth.

During module initialization, the following processes are automatically registered:
```
// Command registration
$this->registerCommands();

// Command schedule registration
$this->registerCommandSchedules();

// Translation registration
$this->registerTranslations();

// Configuration registration
$this->registerConfig();

// View registration
$this->registerViews();

// Loading migrations from the specified path
$this->loadMigrationsFrom(module_path($this->moduleName, 'database/migrations'));
```

However, the extent to which these processes are utilized depends on the specific project requirements. For instance, if you have your own templating engine and configuration system, most of these functions may be disabled.

Additionally, it's worth noting the API route mapping process:
```
// API route mapping
$this->mapApiRoutes();
```

This process may be activated only in certain parts of the project, while route reading will always function.

Therefore, it's advisable to analyze each of these processes and enable only those that are necessary according to your project's requirements.

My opinion: **these examples should be commented out when the module is created.**

**Comment by dont-know-php** [comment]
hi there,

maybe someone will find it useful in Laravel modules optimization. 

I'm using versions `laravel: 8.75` and `laravel-modules: 8`. I had the same problem of slow Laravel initialization, although I have only 15 modules with a lot of settings in a service providers  (loading routes, migrations, templates, resources, etc..).

I profiled my application - the `module_path` helper function takes the most execution time (my code calls the function `~100` times and it takes `~180ms`) because every time the method is called, a `Module` class object is created

I replaced all method calls with a direct path to the files, for example:

```php
// before
$this->loadMigrationsFrom(module_path($this->moduleName, 'Database/Migrations'));

// after
$this->loadMigrationsFrom(__DIR__ . '/../Database/Migrations');
```

This way I saved `~180ms` on the Laravel initialization

**Comment by solomon-ochepa** [comment]
> hi there,
> 
> maybe someone will find it useful in Laravel modules optimization.
> 
> I'm using versions `laravel: 8.75` and `laravel-modules: 8`, the [modules cache is enabled ](https://nwidart.com/laravel-modules/v6/basic-usage/configuration#caching)
> 
> I had the same problem of slow Laravel initialization, although my project has only 15 modules with a lot of settings in a service providers (loading routes, migrations, templates, resources, etc..).
> 
> I profiled my application - the `module_path` helper function takes the most execution time (my code calls the function `~100` times and it takes `~180ms`) because every time the method is called, a `Module` class object is created
> 
> I replaced all method calls with a direct path to the files, for example:
> 
> ```
> // before
> $this->loadMigrationsFrom(module_path($this->moduleName, 'Database/Migrations'));
> 
> // after
> $this->loadMigrationsFrom(__DIR__ . '/../Database/Migrations');
> ```
> 
> This way I saved `~180ms` on the Laravel initialization

This is indeed a great solution. However, the concept behind the initial method is quiet different. What I'll recommend is to use a conditional statement to check if the name is the same as the module, then decide if to call the file directly or use the module object.

**Comment by solomon-ochepa** [comment]
The module object however loads too much.

**Comment by alissn** [comment]
Hi everyone,

I’ve just created a new pull request (#1921) that addresses the performance issue we've been discussing. The changes in the PR aim to significantly improve the loading speed of the modules.

It would be great if you could test it out and provide feedback. Any suggestions for further improvement are welcome. 

Thanks!

**Comment by alpeshrajodiya94** [comment]
@alissn  It's worked. I appreciate your support!!! 

We have made a demo on the local server and worked very well. Still, we will apply this fixing to the actual code (live server) and see how it goes.

**Comment by dcblogdev** [comment]
@alissn I've pulled down 11.1.0 I have 140 modules 

Boot time is high, still need to look at this I think.

![CleanShot 2024-09-14 at 14 57 37](https://github.com/user-attachments/assets/168ed326-3ef6-44d4-8666-dc6a1a14ad7c)

**Comment by barnicolly** [comment]
i have perfomance problem too

https://github.com/nWidart/laravel-modules/commit/d7f17015635d5dfa31ad4b61cf3747d361c06917 removed cache

**Comment by dcblogdev** [comment]
that cache was actually slower then @alissn implementation but I don't think he's finished with it as yet.

**Comment by alissn** [comment]
Hi @dcblogdev,

I checked the source again and tested performance by creating 400 modules in the `breeze-demo` project. The boot time was around 1 second, which seems good. I’ve attached some images below, showing that around 2,500 files were loaded.

<img width="1268" alt="image" src="https://github.com/user-attachments/assets/ea81d483-8aad-4aa0-af49-6a9e9d22d90c">
<img width="1269" alt="image" src="https://github.com/user-attachments/assets/2d9ff9a0-511f-47e1-bc8b-44b1471cbe74">

I need more information to investigate the issue further. For reference, my local setup is a Mac M1 2020, and I’m running the project with Herd.

**Comment by alissn** [comment]
Hi @barnicolly,

The cache has been deleted, and the scan method is now stored in a static property. This static property remains in memory until the cycle ends, which improves performance.

For testing purposes, this section is disabled, as tests typically create and delete 1 or 2 modules. 

You can see the reference here:
https://github.com/nWidart/laravel-modules/blob/f183d64e2abb06cb8e7ce50dbd480e6f9f91b76c/src/FileRepository.php#L143-L148

**Comment by dcblogdev** [comment]
ah turning on normal laravel caching really speeds things up.

In my Breeze demo with 140 mobiles after running `php artisan optimize` much quicker.

![CleanShot 2024-09-14 at 22 33 48@2x](https://github.com/user-attachments/assets/e89cb8b2-34b8-4287-ba5a-c3a0fbb61aab)

**Comment by dcblogdev** [comment]
this is with 500 modules!

no application needs this many modules. Just remember to run `php artisan optimize`

![CleanShot 2024-09-14 at 23 26 29@2x](https://github.com/user-attachments/assets/b7446a0c-3014-4caf-8ad3-88258ef3fe9f)

**Comment by Wulfheart** [comment]
> this is with 500 modules!
> 
> no application needs this many modules. Just remember to run `php artisan optimize`
> 
> ![CleanShot 2024-09-14 at 23 26 29@2x](https://private-user-images.githubusercontent.com/1018170/367546934-b7446a0c-3014-4caf-8ad3-88258ef3fe9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzOTIyNjMsIm5iZiI6MTcyNjM5MTk2MywicGF0aCI6Ii8xMDE4MTcwLzM2NzU0NjkzNC1iNzQ0NmEwYy0zMDE0LTRjYWYtOGFkMy04ODI1OGVmM2ZlOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTVUMDkxOTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ZjMzAwMmE1YzRiOGEyN2ZkZTM4NGRkNzRhNmYzNTllMjYwYWRjMjY1Yzk3YTc4NmYyNDUyNzVhM2VlODljMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vli0AzgD3XkMkULR4Tk1n8OcejMWXAJNMhSvN4Rkp8o)



> ah turning on normal laravel caching really speeds things up.
> 
> In my Breeze demo with 140 modules after running `php artisan optimize` much quicker.
> 
> ![CleanShot 2024-09-14 at 22 33 48@2x](https://private-user-images.githubusercontent.com/1018170/367545358-e89cb8b2-34b8-4287-ba5a-c3a0fbb61aab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzOTIyNjMsIm5iZiI6MTcyNjM5MTk2MywicGF0aCI6Ii8xMDE4MTcwLzM2NzU0NTM1OC1lODljYjhiMi0zNGI4LTQyODctYmE1YS1jM2EwZmJiNjFhYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTVUMDkxOTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmE1NjZlMjliMjlkZDY0MDEyZmIwMDNhYzhiYzZlY2QzMDZiMDEzY2RhOGRiOWUwMWUyZDg1YTZmYjVhYWMwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PstkUY5BZvoO-7lg07SUGllYCJjYmZyM5lP2w_Lr1eQ)


still too slow in my opinion. But may fit 99% of the use cases.
