### ISSUE TITLE
if --web and --api is specified only api controller is generated

### ISSUE THREAD

**Issue by rabol** [nWidart/laravel-modules#1747]
If you create a new module like this:

```
php artisan module:make Integrations --web --api
```

then no API controller generated and the controller that is generated, returns JSON (API)

**Comment by dcblogdev** [comment]
looked into this, web is done by default, the --api option essentially stops the web controller from generating.

Also if they did both generate there would be a clash as they would both attempt to generate the same controller name.

I suggest if you want both then generate a module as normal then generate an API controller

```
php artisan module:make-controller ApiController Blog --api
```

**Comment by solomon-ochepa** [comment]
> looked into this, web is done by default, the --api option essentially stops the web controller from generating.
> 
> Also if they did both generate there would be a clash as they would both attempt to generate the same controller name.
> 
> I suggest if you want both then generate a module as normal then generate an API controller
> 
> ```
> php artisan module:make-controller ApiController Blog --api
> ```

You are right about the default behavior, but I strongly believe this feature  the issue is aiming is a wonderful idea.

Nevertheless, `ApiController` is not a generic name. Consider using `BlogApiController` or `Api\\BlogController`

**Comment by dcblogdev** [comment]
I agree it would be good to have this, happy to accept a PR for this with tests. Over the coming weeks, I want to concentrate on the docs and guides.
