### ISSUE TITLE
Register Middleware

### ISSUE THREAD

**Issue by LeonardoAthayde** [nWidart/laravel-modules#175]
How is the best way to register some module middeware on the Laravel?

**Comment by nWidart** [comment]
In your service provider you can call the `middleware` method on the Router class (`$this->app['router']`)

**Comment by wPatrick** [comment]
Some changes came into Laravel 5.4. Use  `aliasMiddleware` method on $this->app['router'] and you are ready to go.

**Comment by LeonardoAthayde** [comment]
So I cant load middleware in my service provider module? 

The only solution is to mannualy register the middleware on kernel.php?

**Comment by LeonardoAthayde** [comment]
I Got, now its working thnks people!!!!

**Comment by praditha** [comment]
@LeonardoBAV 
Could you please give me the sample code?

**Comment by jjth** [comment]
@praditha 
For those still wondering, here is a sample code from @LeonardoBAV 's repositories:
https://github.com/LeonardoBAV/User/blob/9a4054ad8397f116d820c487d0812450250b178f/Providers/UserServiceProvider.php#L30

**Comment by enniosousa** [comment]
If you want add a Global Middleware, just instace Kernel Http Contract from Illumite and call ```pushMiddleware``` method

```php
public function boot(){
        $this->registerTranslations();
        $this->registerConfig();
        $this->registerViews();
        $this->registerFactories();
        $this->loadMigrationsFrom(__DIR__ . '/../Database/Migrations');
        
        // adding global middleware
        $kernel = $this->app->make('Illuminate\Contracts\Http\Kernel');
        $kernel->pushMiddleware('Modules\Frequencia\Http\Middleware\PeriodoMiddleware');
    }
```

**Comment by vahidalvandi** [comment]
`
    public function boot(Illuminate\Routing\Router $router)
    {
		
		Gate::define('user-invoice-check', 'Modules\Vproducts\Policies\UserPolicy@invoice');

        $this->registerTranslations();
        $this->registerConfig();
        $this->registerViews();
        $this->registerFactories();
        $this->loadMigrationsFrom(__DIR__ . '/../Database/Migrations');

         $router->aliasMiddleware('CanReadInvoiceMiddleware', \Modules\Vproducts\Http\Middleware\CanReadInvoiceMiddleware::class);

	}

`
