### ISSUE TITLE
Error reading module statuses or module configurations: ReferenceError: __dirname is not defined in ES module scope

### ISSUE THREAD

**Issue by eelco2k** [nWidart/laravel-modules#1751]
``
Error reading module statuses or module configurations: ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/phpproject/Modules/Core/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
``

node version: 10.2.4

**Comment by dcblogdev** [comment]
If you're running vite from a module directly then see https://laravelmodules.com/docs/v10/compiling-assets#vite-load-from-modules

Otherwise to load vite from the global vite config then each module vite file should contain only an array such as:

```
export const paths = [
   'Modules/Demo/resources/assets/sass/app.scss',
   'Modules/Demo/resources/assets/js/app.js',
];
```
