### ISSUE TITLE
Suport laravel 11 ?  

### ISSUE THREAD

**Issue by bijon059** [nWidart/laravel-modules#1760]
When the Laravel 11 support will be released?

**Comment by dcblogdev** [comment]
we're working on it, just as soon as https://github.com/nWidart/laravel-modules/pull/1758 is solved. We want to add a meaningful release.

**Comment by enterprime** [comment]
> we're working on it, just as soon as #1758 is solved. We want to add a meaningful release.

When can we expect the release of support for Laravel 11? Are we looking at around 1-2 weeks or a month? Our team is eagerly awaiting this moment.

**Comment by dcblogdev** [comment]
All being well, later today. Got a few more tests to perform.

**Comment by azamrizki** [comment]
Is there any good news about updates to support Laravel 11 ?

**Comment by dcblogdev** [comment]
I've just tagged v11 🎉

https://github.com/nWidart/laravel-modules/releases/tag/v11.0.0

Please see the upgrade guide at https://laravelmodules.com/docs/v11/upgrade

Thanks to everyone who's helped recently to get this over the line.
