### ISSUE TITLE
No hint path defined for [modulename]

### ISSUE THREAD

**Issue by wisnuaryadipa** [nWidart/laravel-modules#177]
I have problem with "No hint path defined for [modulename]

This problem happen when i copy my laravel project from my pc to my laptop, and run `php artisan serve`

I think my laravel project cant find where's the module path.
Then i try to create module `pa module:make testing` and the module generated in the different path i run on drive E but the module generated in drive D

can someone help me?

**Comment by wisnuaryadipa** [comment]
Problem solved
if you wanna move laravel to other server or path, you need to change all old path to new path u wanna to use at `laravel/bootstrap/cache/config.php`

**Comment by arslanramay** [comment]
I have the same problem with one of my Laravel Modules when I renamed a Module. I forgot to rename some config values in the ModuleServiceProvider i.e. protected $moduleNameLower = 'fitnessclass';

Once I updated the '$moduleNameLower' to a new value, I just did 'composer dump-autoload' and everything worked fine.
