### ISSUE TITLE
creating links to modules

### ISSUE THREAD

**Issue by designvoid** [nWidart/laravel-modules#178]
Hi there - just wondering, how do I go about creating links to modules? I am using:

 {{ action('AtozController@index') }}

But I am getting:

ErrorException in UrlGenerator.php line 337:
Action App\Http\Controllers\AtozController@index not defined. (View: /home/vagrant/Code/App/resources/views/home.blade.php)

**Comment by montyclt** [comment]
Same problem, I trien with action('Home::HomeController@index'), but now working.

**Comment by montyclt** [comment]
I think the best form for do it, its probably adding a method to module class and fecade, and get route of the action doing it:

`$module = Module::find('home');
$module->action('ControllerInModule@method');`

Or maybe directly with Fecade:

`Module::action('Home', 'ControllerInModule@method')`

@nWidart This weekend I'll study about how it's made the package and probably send a pull request with this feature.

**Comment by mikemand** [comment]
You probably need to use the fully qualified namespace for your module's controller:

```php
{{ action('\Modules\MyModule\Http\Controllers\AtozController@index') }}
```

I highly suggest [named routes](https://laravel.com/docs/5.4/routing#named-routes) instead. I've never understood why one would use `action` (or raw uris) when naming your routes is so much more backwards compatible.

**Comment by montyclt** [comment]
I was using action because I did not know the named routes.

Thanks for link in documentation, I'll use named routes now.

**Comment by designvoid** [comment]
I am using action as I have resource controllers

**Comment by mikemand** [comment]
Resource controllers (depending on the version of Laravel) create named routes (or you can manually create them). https://laravel.com/docs/5.4/controllers#resource-controllers

You can always check the route list if you're not sure:

```sh
php artistan route:list
```

**Comment by mikemand** [comment]
By "manually create", I mean `Route::resource()` has the option to name routes, just like you can `exclude` or only `include` certain resources.

**Comment by designvoid** [comment]
Well stone the crow! I never realised that!

Amazing what you miss! Thanks!!!

**Comment by mikemand** [comment]
No problem. :)

**Comment by nWidart** [comment]
I'll close this as it looks fixed 😄
