### ISSUE TITLE
Class "Modules\Posts\Providers\PostsServiceProvider" not found | laravel 11

### ISSUE THREAD

**Issue by pkfan** [nWidart/laravel-modules#1781]
I just installed **laravel 11 version** with **"jetstream"**

after that I **installed "laravel-modules"** package.

after that, run this command for demo module from docs
`php artisan module:make posts`

and then run laravel command
`php artisan serve`

-------------------------------

Got this provider error
```
 Error

  Class "Modules\Posts\Providers\PostsServiceProvider" not found

  at vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:206
    202▕      * @return \Illuminate\Support\ServiceProvider
    203▕      */
    204▕     public function createProvider($provider)
    205▕     {
  ➜ 206▕         return new $provider($this->app);
    207▕     }
    208▕ }
    209▕

  1   vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:142
      Illuminate\Foundation\ProviderRepository::createProvider("Modules\Posts\Providers\PostsServiceProvider")

  2   vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:61
      Illuminate\Foundation\ProviderRepository::compileManifest()
```

I just want to try this package but first try failed.

Please confirm, this is about package error or I am doing setup in wrong way.

**Comment by dcblogdev** [comment]
have you added/updated your composer.json file?

By default, the module classes are not loaded automatically. You can autoload your modules by adding merge-plugin to the extra section:

```
"extra": {
    "laravel": {
        "dont-discover": []
    },
    "merge-plugin": {
        "include": [
            "Modules/*/composer.json"
        ]
    }
},
```

don't forget to run composer dump-autoload afterwards.

**Comment by pkfan** [comment]
Dear [dcblogdev](https://github.com/dcblogdev),

I followed your instructions and updated my composer.json file accordingly. Adding the merge-plugin to autoload the modules was precisely what I needed, and it resolved my issue flawlessly.

thank you so much for your prompt and effective help. 

Warm regards,
