### ISSUE TITLE
Blueprint

### ISSUE THREAD

**Issue by dcblogdev** [nWidart/laravel-modules#1784]
Look into the possibility of https://github.com/laravel-shift/blueprint can be extended for modules.

https://blueprint.laravelshift.com/docs/extending-blueprint/

**Comment by solomon-ochepa** [comment]
I just went through the video demo, and this will be great. I'll try this package and recommend it to my tech team.

This can be used in place of stubs.

**Comment by dcblogdev** [comment]
Could be interesting, hoping to find some time next week to check it out.
