### ISSUE TITLE
  Class "Modules\Shop\Database\factories\CategoryFactory" not found in production

### ISSUE THREAD

**Issue by AHMED-GAMAL-AG** [nWidart/laravel-modules#1788]
i get in production `Class "Modules\Shop\Database\factories\CategoryFactory" not found` when `php artisan db:seed` runing  the code works fine in the local environment 

![image](https://github.com/nWidart/laravel-modules/assets/76778937/ca4b1f89-619a-4149-acce-c7c4dcdd0c24) 

the class exists in this path 

![image](https://github.com/nWidart/laravel-modules/assets/76778937/3e337e3e-402b-469c-8915-33c9bcb1b451)

the Shop module is active 

![image](https://github.com/nWidart/laravel-modules/assets/76778937/095a3a78-38b1-4344-af86-279d1d3d4cc9)

I ran `composer dump-autoload` but it didn't help 

what could be the problem?

**Comment by AHMED-GAMAL-AG** [comment]
Great it works fine now The problem was that the Category Model the Factory was imported as `use Modules\Shop\Database\factories\CategoryFactory;` changing to `use Modules\Shop\Database\Factories\CategoryFactory;` with Factoris with Upper Case F fixed it.

**Comment by AHMED-GAMAL-AG** [comment]
@dcblogdev by default, the **f** in the path is in lower case, which causes problem in the production environment. It need to be fixed, though  

![image](https://github.com/nWidart/laravel-modules/assets/76778937/804a4226-f52c-41f5-aa0a-5eb85626732d)

**Comment by dcblogdev** [comment]
thanks https://github.com/nWidart/laravel-modules/pull/1791 addresses this.
