### ISSUE TITLE
include view

### ISSUE THREAD

**Issue by srakl** [nWidart/laravel-modules#1793]
Hi,

In my `index.blade.php` file i want to inlcude another view `_index.blade.php`

I calling it like this `@include('ModuleName::_index')` but i'm getting this error `No hint path defined for [ModuleName].`

`_index.blade.php` is in the same folder / directory as `index.blade.php`. Any idea how to get this to work? Thank you

**Comment by enterprime** [comment]
Hi,
the module name must be in lower case
`@include('modulename::_index')`

**Comment by srakl** [comment]
thank you
