### ISSUE TITLE
 Nwidart\Modules\Exceptions\ModuleNotFoundException

### ISSUE THREAD

**Issue by T3mmyKay** [nWidart/laravel-modules#1795]
I am trying to create a module and I keep getting  Nwidart\Modules\Exceptions\ModuleNotFoundException

**Comment by enterprime** [comment]
Have you customized composer.json? 

If yes and it doesn't work, then run the command: 
`composer dump-autoload`
or
If yes and it doesn't work, then run the command: 
`composer update -o`
