### ISSUE TITLE
No such command for creating Observers 

### ISSUE THREAD

**Issue by Masumrahmanhasan** [nWidart/laravel-modules#1796]
so when i try to create a Observer for that particular Module i could not add that cause there is no command for creating that 

So how do i use Observer for that Modules

**Comment by enterprime** [comment]
Did you use the command or not? 

`php artisan module:make-observer PostObserver ModuleName`

**Comment by Masumrahmanhasan** [comment]
@enterprime  i already did and it shows the existing command list cause this command is not there

**Comment by enterprime** [comment]
what version of laravel and module packages are you using?

**Comment by alissn** [comment]
Hi, @Masumrahmanhasan 

I think you've published an outdated config file. In the old config file, commands were defined for your project. Please review PR #1720.

Update your config as follows:

```php
'commands' => \Nwidart\Modules\Providers\ConsoleServiceProvider::defaultCommands()
        ->merge([
            // New commands go here
        ])->toArray(),
```
