### ISSUE TITLE
Class "Modules\Hello\Providers\HelloServiceProvider" not found

### ISSUE THREAD

**Issue by RamiiYoussef** [nWidart/laravel-modules#1797]
Laravel V11.1

- Create module Hello: php artisan module:make Hello
Success Creation.

- When run any command like:
php artisan optimize:clear   
php artisan module:list
etc..

Getting this error:

```
  Class "Modules\Hello\Providers\HelloServiceProvider" not found

  at vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:206
    202▕      * @return \Illuminate\Support\ServiceProvider
    203▕      */
    204▕     public function createProvider($provider)
    205▕     {
  ➜ 206▕         return new $provider($this->app);
    207▕     }
    208▕ }
    209▕ 

```

**Update:**

It's not work even I add this in composer.json

```
"extra": {
    "laravel": {
        "dont-discover": []
    },
    "merge-plugin": {
        "include": [
            "Modules/*/composer.json"
        ]
    }
},
```

**Comment by enterprime** [comment]
After the composer.json file was edited, was the `composer update` command run?

**Comment by RamiiYoussef** [comment]
I fixed it.

I was forgot to add  "Modules\\": "Modules/" to psr-4

```
{
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Modules\\": "Modules/"
    }
  }
}
```

**Comment by alissn** [comment]
> I fixed it.
> 
> I was forgot to add "Modules\": "Modules/" to psr-4
> 
@RamiiYoussef

on version 11 no need add `"Modules\\": "Modules/"`

 module register with package [composer-merge-plugin](https://github.com/wikimedia/composer-merge-plugin)
 
 more info for update [here](https://laravelmodules.com/docs/v11/installation-and-setup#autoloading) and [here](https://laravelmodules.com/docs/v11/upgrade#composer-merge-plugin)
