### ISSUE TITLE
[Module] Service provider not found on production server

### ISSUE THREAD

**Issue by KyawNaingTun** [nWidart/laravel-modules#18]
I created Employee Module, but error message is appearing on production server like that

```
[Symfony\Component\Debug\Exception\FatalThrowableError]               
 Class 'Modules\Employee\Providers\EmployeeServiceProvider' not found
```
Development -> Mac
Production -> Ubuntu server 14.04, Nginx

I also run a `composer dump-autoload` and `php artisan clear-compiled` on production.

Application is running stable on development server.
I don't exactly know this error message. Please help me. Thanks

**Comment by nWidart** [comment]
Hello,

If you're having this on production and not locally it's quite possible it's a Case sensitive issue.

Double check what casings the files have.

**Comment by unxp** [comment]
As @nWidart pointed out: make sure that file location on production server is exactly `Modules\Employee\Providers\EmployeeServiceProvider.php` matching all lower and upper case letters.  It is a  common problem when people develop using Windows (which _ignore upper case in file name_), everything works fine and when they upload to production (which is usually unix based system that _**does not ignore** upper case in file name_) they see file not found errors.

**Comment by m-behr** [comment]
have a look at app/config/modules.php

in line ~65 , change `'modules' => base_path('Modules'),`
to `'modules' => base_path('modules'),`

this solved the problem for us ( coming from named routes not working)
I am not sure if the different naming is general bug, so if you run php artisan module: make test
it will create a 'Modues' dir, even if 'modules' is present

**Comment by KyawNaingTun** [comment]
I solved, thanks @m-behr 👍 
but error message is appearing like that` NotFoundHttpException in RouteCollection.php line 161:` 
I think, this package was not tested on Ubuntu/Linux OS. How can I fix Sir?

**Comment by armababy** [comment]
@KyawNaingTun i run several apps using this package on Ubuntu and i comply with PSR4 naming and had no issues. 
Folder name `Modules` namespace `Modules` and everything good.

**Comment by KyawNaingTun** [comment]
Thank you @armababy  for your comment. But I can't solve it :( . I added in autoload and then run `composer dump-autoload`. I don't exactly know that. What? Why? I can't continue development. My development process is stopping on live server. :(

**Comment by KyawNaingTun** [comment]
I solved all errors. :D Thank everybody
Solutions:
1. Main root module folder[`Modules`] to [`modules`]
2. please go to comment of @m-behr :D

**Comment by armababy** [comment]
But this still suggests me that it's not a legit fix. You just somewhere have lowercase modules in your namespace. The uppercase Modules is correct.

But i'm glad it worked out for you :)

**Comment by FaCuZ** [comment]
I fix it with `composer install`

**Comment by ederrafo** [comment]
Hello @KyawNaingTun @nWidart 
Thanks
Please, 
When I run this command: $ php artisan module:make MyModule
the Module folder is generated out of app folder.
Why? :S
My-project/
                 Modules/
                 app/
                 bootstrap/
                 .
                 .

I modified the modules.php file, this line:
  'modules' => base_path('app/Modules'),

That works, but  I run this command again: $ php artisan module:make OtherModule
I have this error:
[Symfony\Component\Debug\Exception\FatalThrowableError]               
  Class 'Modules\Frontend\Providers\MyModuleServiceProvider' not found  
  
:'(


any suggestions?
Thanks

**Comment by nWidart** [comment]
Hi,

You need to autoload your module with composer.

**Comment by KyawNaingTun** [comment]
Hello @ederrafo ,
Please have a look the following steps

**1. Folder structure-**
```
your-laravel-app/
├── app/
├── bootstrap/
├── vendor/
├── modules/
├── ├── YourModuleFolder/
```

**2. and then check in your composer.json**
```
{
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Modules\\": "modules/"
    }
  }
}
```
**3. run this command `composer dump-autoload`**

**Comment by m-behr** [comment]
Did you adjust the module - path in composer.json ? 

On 12. August 2016 18:04:45 MESZ, "Eder Rafo Jose Pariona Espiñal" <notifications@github.com> wrote:
>Hello @KyawNaingTun @nWidart 
>Thanks
>Please, 
>When I run this command: $ php artisan module:make MyModule
>the Module folder is generated out of app folder.
>Why? :S
>My-project/
>                 Modules/
>                 app/
>                 bootstrap/
>                 .
>                 .
>
>I modified the modules.php file, this line:
>  'modules' => base_path('app/Modules'),
>
>That works, but  I run this command again: $ php artisan module:make
>OtherModule
>I have this error:
>[Symfony\Component\Debug\Exception\FatalThrowableError]               
> Class 'Modules\Frontend\Providers\MyModuleServiceProvider' not found  
>  
>:'(
>
>
>any suggestions?
>Thanks
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nWidart/laravel-modules/issues/18#issuecomment-239487472

-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.

**Comment by ederrafo** [comment]
Hi
My composer.json:

 "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/",
            "Modules\\": "modules/"
        }
    }

I run : composer dump-autoload

same, 
I have the same error message.

$ php artisan module:make OtherModule
Class 'Modules\Frontend\Providers\MyOtherModuleServiceProvider' not found

:(

**Comment by armababy** [comment]
@ederrafo 
Do a full search on whole project and search for string `Modules\Frontend\Providers\MyOtherModuleServiceProvider` see where it is defined (autoloader, cache or somewhere else) tell us what it's linking to.

**Comment by assoft** [comment]
try it:

`artisan module:make YourModuleName`
`composer dumpa`

**Comment by ederrafo** [comment]
Hello guys, thanks for your answers
I solved the problem, when I generate, modules, with command **$ php artisan module:make user**, is generated into module User, this file **modules.json** in that file on line 9 : 
 "providers": [
        "Modules\\User\\Providers\\UserServiceProvider"
    ],
I changed:
"providers": [
        "Modules\User\Providers\UserServiceProvider"
    ],

Now, I generate othermodules :+1:  , but always I have to edit the file modules.json  :( 
The error is caused by: // , Why?
:O

**Comment by ederrafo** [comment]
Now, I run
$  composer install  //for autoload files
$ php artisan route:list

Other message, similar:
` [ReflectionException]                                                    
  Class Modules\User\Http\Controllers\UserController does not exist `

:'( I'm trying to solve this

**Comment by Sahandi81** [comment]
in `config/modules.php` sometimes work with :
```
        'modules' => base_path('modules'),

```
and sometimes work with:
```
        'modules' => base_path('Modules'),
```

**Comment by rerdsys** [comment]
Mine only works when I rename the modules folder to Modules

**Comment by elvisbomfim** [comment]
I had the same error, 
php artisan  module:list
+---------------+----------+----------+---------------------------------------------------+
| Name          | Status   | Priority | Path                                              |
+---------------+----------+----------+---------------------------------------------------+
| A 		| Enabled  | 0        | /var/www/projects/www/Modules/A
| B   		| Enabled  | 0        | /var/www/projects/www/Modules/B
| C	      	| Disabled | 0        | /var/www/projects/www/Modules/C

The I fixed it using:

php artisan module:enable C

**Comment by morpheusadam** [comment]
you most go to bootstrap cach ->modules
and remove the ModuleNameServiceprovider
