### ISSUE TITLE
Routes in module folder doesn't work

### ISSUE THREAD

**Issue by gillesgw** [nWidart/laravel-modules#180]
Hey,

Sorry if this is simple and stupid, but when my routes are in Modules/MyModule/Http/routes.php, I can see them with php artisan routes:list, but it shows me a 404 page. If I move theses routes in the app/Http/routes.php, it's working perfectly.

I followed the documentation, anything i'm not doing right ? I'm on laravel 5.2 and I use laravel built-in serve.

Thanks for your work !

**Comment by eness** [comment]
What do you have in your routes.php file from module's folder?

**Comment by gillesgw** [comment]
Default generated code more or less :

`Route::group(['middleware' => 'web', 'prefix' => 'backoffice', 'namespace' => 'Modules\BackOffice\Http\Controllers'], function()
{
    Route::get('/test', ['as' => 'back.dashboard', 'uses' => 'BackOfficeController@index']);

});`

**Comment by Fagl4** [comment]
What url are you trying to  access, are you prepending the url with the prefix?
In your case the url to the `back.dashboard` route would be

`yourhost.dev/backoffice/test`

**Comment by eness** [comment]
Try to define more obvious route in your module's route file, after clearing previous ones : 
```php
Route::get('hello', function() {
   return "John Doe";
});
```

and go to this url:  yourhost.dev/hello and check if this routing works via the module.

**Comment by enextiarg** [comment]
Hi Nicolas,
Did you have some issue when declaring resource routes in modules? 
If i declare get, post, any, etc. routes its works.
But when I declare resources routes for eg.

Route::group(['middleware' => ['web','role:admin'], 'as' => 'users.' ,'prefix' => 'users', 'namespace' => 'Modules\Auth\Http\Controllers'], function()
{
    Route::resource('/', 'UsersController');
});

It doesnt work. But the interesting is that in the route list the routes the id is not declared.

|        | DELETE                         | users/{}                       | users.destroy      | Modules\Auth\Http\Controllers\UsersController@destroy                      | web,role:admin      |
|        | PUT|PATCH                      | users/{}                       | users.update       | Modules\Auth\Http\Controllers\UsersController@update                       | web,role:admin      |
|        | GET|HEAD                       | users/{}                       | users.show         | Modules\Auth\Http\Controllers\UsersController@show                         | web,role:admin      |
|        | GET|HEAD                       | users/{}/edit                  | users.edit         | Modules\Auth\Http\Controllers\UsersController@edit                         | web,role:admin  

Regards

**Comment by JunaidQadirB** [comment]
I'm having the same issue with the latest version, that is, v7.1

**Comment by JunaidQadirB** [comment]
I tried uninstallin and reinstalling but still no luck. I also created a new midule but all in vein,

**Comment by enextiarg** [comment]
What is the specific error?

**Comment by JunaidQadirB** [comment]
I didn't get any error. 
Sorry I had to switch to another way(another package actually) to load my packages because of a deadline.

**Comment by vishal2pc** [comment]
Any solution to this issue? I'm having the same issue.

**Comment by ossycodes** [comment]
same issue here, @vishal2pc did you find any solution to this ?

**Comment by enextiarg** [comment]
What laravel-modules version is? Did you check if routes are in Modules/YourModules/Routes/web.php ?

**Comment by ossycodes** [comment]
@enextiarg nWidart/laravel-modules ~8.2, routes in ModuleNameA/Routes/web.php do not get loaded

**Comment by enextiarg** [comment]
Could you check if ModuleNameA/Providers/RouteServiceProvider.php is pointing to the correct route file?
Please try to remove bootstra/cache/* files some time the cache desnt update the routes.

**Comment by enextiarg** [comment]
Another question. Is the module active? you can check with` php artisan module:list `

**Comment by ossycodes** [comment]
it's active @enextiarg
