### ISSUE TITLE
Need to add two command "make:enum" and "make:class" for the modules

### ISSUE THREAD

**Issue by Siam401** [nWidart/laravel-modules#1800]
Laravel 11 added enum and class making command "class"  command is useful when creating custom service class for the controller

**Comment by solomon-ochepa** [comment]
Yeah, I read the release documents and certainly, these two pieces are great. We'll incorporate them as soon as possible.

**Comment by dcblogdev** [comment]
I've added a whole bunch of missing commands, make-class is being worked on.

https://github.com/nWidart/laravel-modules/releases/tag/v11.0.8
