### ISSUE TITLE
Target a specific part of standard page of Laravel project by modules

### ISSUE THREAD

**Issue by usama-kabel** [nWidart/laravel-modules#1801]
I'm currently developing an ERP Laravel project and have successfully implemented a module to manage multiple exchange rates within it.
My goal now is to focus on a particular page where I can incorporate a specific view. This view will enable users to select the desired currency for conducting rate exchanges, apply these changes for insertion purposes, and generate invoices accordingly. Importantly, I aim to achieve this without altering the main selling page.
Do you think this approach is feasible?

**Comment by solomon-ochepa** [comment]
> I'm currently developing an ERP Laravel project and have successfully implemented a module to manage multiple exchange rates within it. My goal now is to focus on a particular page where I can incorporate a specific view. This view will enable users to select the desired currency for conducting rate exchanges, apply these changes for insertion purposes, and generate invoices accordingly. Importantly, I aim to achieve this without altering the main selling page. Do you think this approach is feasible?

Yes, that sounds highly feasible!

I'm not entirely familiar with your workflow, but I believe the following recommendations could be beneficial:

1. Modal:
Consider creating a modal component that pops up on the same page, allowing the user to fill out the exchange form. Upon submission, trigger the `Invoice` module to generate the invoice based on the incoming request.

3. Create a Livewire `exchange` component within the Exchange module.
This component should have properties such as `amount`, `x_amount`, `currency`, and `x_currency`. When initializing the component, bind the `amount` and `currency` properties. Then, only the `x_currency` dropdown input should be interactive, with attributes `wire:change="calculator"` and `wire:model.live="x_currency"`. Additionally, include a read-only input field for `x_amount`.
Whenever a user changes the `x_currency`, the `calculator` method within the exchange component will be triggered, updating the `x_amount` property accordingly.

If you require further assistance with the implementation or encounter any related issues, feel free to contact me via WhatsApp at https://wa.me/2348162672618 or email me at solomonochepa@gmail.com.

Nevertheless, I strongly suggest you consider posting your issues here first to benefit from broader support coverage.

**Comment by dcblogdev** [comment]
Yep sounds a fine approach, having a dedicated LW component as @solomon-ochepa suggested should work well.
