### ISSUE TITLE
Migration Command Not Working

### ISSUE THREAD

**Issue by RanjanGumanju** [nWidart/laravel-modules#1807]
Refreshing Migration Blog module ............................................................................. 12ms FAIL

   Illuminate\Database\QueryException 

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'migration' in 'where clause' (Connection: mysql, SQL: select count(*) as aggregate where `migration` = 2024_04_04_134727_create_posts_table)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:829
    825▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    826▕                 );
    827▕             }
    828▕ 
  ➜ 829▕             throw new QueryException(
    830▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    831▕             );
    832▕         }
    833▕     }
 While running every migration rollback commands, this issue encountered everytime.

**Comment by dcblogdev** [comment]
can you provide any other details? I've been unable to replicate this.

**Comment by RanjanGumanju** [comment]
![image](https://github.com/nWidart/laravel-modules/assets/20850797/03a55b71-fef3-4e8d-9104-35896142a6b7)
Every Migrate command(reset, refresh,rollback) not worked.

**Comment by robertojohansalim** [comment]
I found similar problem with fresh install of laravel 10.

I am able to migrate using `php artisan module:migrate` but unable to rollback using `php artisan module:migrate-rollback`
I am able to rollback using `php artisan migrate:rollback`

Seems like the SQL STATE missing the table `FROM` statement, is this intended or am i missing something?
```
SQLSTATE[42703]: Undefined column: 7 ERROR:  column "batch" does not exist
LINE 1: select max("batch") as aggregate where "migration" in ($1)
                   ^ (Connection: pgsql, SQL: select max("batch") as aggregate where "migration" in (2024_04_17_085802_create_form))
```

Is it is suppose to print `select max("batch") as aggregate FROM "migrations" where "migration" in ($1)` where the statement missing its `FROM "migrations"` part?

**Comment by dcblogdev** [comment]
I can't replicate this on L10 or 11

try doing a composer update

**Comment by fxpw** [comment]
still not working 
![Image](https://github.com/user-attachments/assets/e3877498-16e9-4321-a4a8-c45b94509f5b)

![Image](https://github.com/user-attachments/assets/9527e9aa-d4bf-4009-8c91-c2ffc33da46b)

```
❯ make php_module_rollback_test
docker compose exec cp_laravel_app php artisan module:migrate-rollback 

 ┌ Select Modules ──────────────────────────────────────────────┐
 │ All                                                          │
 └──────────────────────────────────────────────────────────────┘


   Illuminate\Database\QueryException 

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'batch' in 'field list' (Connection: mysql, SQL: select max(`batch`) as aggregate where 0 = 1)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:825
    821▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    822▕                 );
    823▕             }
    824▕ 
  ➜ 825▕             throw new QueryException(
    826▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    827▕             );
    828▕         }
    829▕     }

      +28 vendor frames 

  29  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

make: *** [Makefile:267: php_module_rollback_test] Error 1
```

**Comment by fxpw** [comment]
@dcblogdev should I create a new issue or will you re-open this?

**Comment by dcblogdev** [comment]
@fxpw I think it would be best to open a new issue, thanks.
