### ISSUE TITLE
Modular inertiajs

### ISSUE THREAD

**Issue by Skaywalker** [nWidart/laravel-modules#1814]
Hello, I need a little help.
I would like to use the modular option. De vue under inertiajs app. I couldn't find a script for it anywhere. Can someone help me how I can modify the package so that it works with inertiajs?
I don't know how to configure the package so that it works with vue. How the vite pulls it in.

**Comment by dcblogdev** [comment]
Have a look at https://github.com/nWidart/laravel-modules/issues/1532

**Comment by Boendestodet** [comment]
Would be awesome to make it as choose when installing.

**Comment by dcblogdev** [comment]
Happy to receive a PR that tackles this.
