### ISSUE TITLE
Migration Invalid Priority

### ISSUE THREAD

**Issue by osama-98** [nWidart/laravel-modules#1816]
Hello, I'm facing an issue in priority in migrations only.

```php
Schema::create('books', function (Blueprint $table) {
            $table->id();
            $table->json('name');
            $table->string('code')->unique();
            $table->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();
            $table->softDeletes();
        });
```

I have the priorities as below:
1. **UserModule**: 1
2. **BookModule**: 10

When I do 
```php artisan module:migrate```
I expect the modules will be migrated as their priorities UserModule and then BookModule. However, it does not.
It seems it is working alphabetically in migrations; Since, the BookModule worked before UserModule

**Comment by prg-hussam** [comment]
@dcblogdev

**Comment by dcblogdev** [comment]
We've pushed a release to address this.
