### ISSUE TITLE
Views

### ISSUE THREAD

**Issue by laravel0317** [nWidart/laravel-modules#182]
I have 3 modules, module1, module2, and module3. How can I visit a specific module in the browser?

ex.:
localhost/nwidart/module1 ?

**Comment by nWidart** [comment]
just as you would in a normal laravel app: create routes in your modules, which will be accessible via the browser.

**Comment by laravel0317** [comment]
Thanks for the answer, but I already have route.php in my module1,2, and 3. I tested it with :

```
Module1/Http/routes.php
Route::get('/', function(){
   return 'This is the Module1';
});

_____________________________________________________________________
Module2/Http/routes.php
Route::get('/', function(){
   return 'This is the Module2';
});


_____________________________________________________________________

Module3/Http/routes.php
Route::get('/', function(){
   return 'This is the Module3';
});


```


.after that, I tried to visit localhost/nwidart/module1 and it says "NotFoundHttpException in RouteCollection.php line 161". I have also check the documentation, and maybe you should provide more info about the documentation. Thanks a lot!

**Comment by nWidart** [comment]
Did you also load those route files ?

From a module route service provider (for example) you'll need to `require` those files.

**Comment by laravel0317** [comment]
How can I do that?

**Comment by nWidart** [comment]
as I said before by using `require`.

**Comment by laravel0317** [comment]
Alright. Thanks!
