### ISSUE TITLE
Extending Laravel 11 EventServiceProvider

### ISSUE THREAD

**Issue by danielDigitalArt** [nWidart/laravel-modules#1824]
Hi,

i used the Package in Laravel 8 and updated it now to Laravel 11, my Package is currently still on Version 8.2, but i think the Problem is more related to the Documentation here: [https://laravelmodules.com/docs/v11/registering-module-events#creating-an-eventserviceprovider](https://laravelmodules.com/docs/v11/registering-module-events#creating-an-eventserviceprovider)

In Laravel 11 the EventServiceProvider got a new Function called `configureEmailVerification`, this function is automatically called which leads to multiple request for the `sendEmailVerificationNotification` Event, which means for every Module that has the EventServiceProvider extended another email is being generated. For example i had 3 Modules active which all had events registered, thus i received 4 emails.

A simple fix is to create an abstract class and then let the EventServiceProvider of these Modules extend from this class instead of extending the Core Class. Then add an empty Function into it. The Code for this abstract class can be found here:
[https://github.com/laravel/framework/issues/50783#issuecomment-2072458671](https://github.com/laravel/framework/issues/50783#issuecomment-2072458671)

I think it would make sense to either add this info to the documentation, or even better, add a default EventServiceProvider when creating a Module, which already has this fix in it.

**Comment by dcblogdev** [comment]
thanks I've added a make:event-provider command and added this to module creation.

the events service provider contains the configureEmailVerification method to override the default.
