### ISSUE TITLE
Locating Modules

### ISSUE THREAD

**Issue by laravel0317** [nWidart/laravel-modules#183]
How can I locate specific modules in the browser, for example, I have **Module1** with...
```
Route:;get('/', function(){
   return 'Module1';
});
```
..and I have **Module2** with...

```
Route::get('/', function(){
    return 'Module2';
});
```

.. then how can I locate these modules in the browser?  when I tried to locate `localhost/myProject/Module1` in the browser, it says 

> NotFoundHttpException in RouteCollection.php line 161

Here's my code in **composer.json**:
```
"autoload": {
        "psr-4": {
            "App\\": "app/",
            "Modules\\": "Modules/"
        }
}
```

**Comment by nWidart** [comment]
Just as any laravel app, you need to load your route file(s).

**Comment by laravel0317** [comment]
I have already loaded it, then how can I visit it to the browser?  for example my Module1?
