### ISSUE TITLE
Migrations artisan commands

### ISSUE THREAD

**Issue by jonjie0317** [nWidart/laravel-modules#184]
The command `php artisan module:publish-migrations Module1` in the [documentation](https://nwidart.com/laravel-modules/v1/advanced-tools/artisan-commands) is not working, my terminal says:

```
[InvalidArgumentException]
Command "module:publish-migrations" is not defined.
Did you mean one of these?
    module:publish-migration
    module:make-migration
    module:publish-translation
    module:publish
    module:make-seed
    module:seed
    module:make-model
    module:setup
    module:use
    module:make-mail
    module:make-notification
    module:make-job
    module:publish-config
    module:dump
    module:make-request
    module:update
    module:migrate-rollback
    module:make-event
    module:make-listener
    module:enable
    module:disable
    module:make-command
    module:make-controller
    module:make-middleware
    module:make-provider
    module:migrate-refresh
    module:migrate-reset
    module:migrate
    module:list
    module:route-provider
    module:install
    module:make
```
.. and when I tried the `php artisan module:publish-migration Module1`   **without a "s"** then nothings happen. What happen to that?  Any help?

Thanks!

**Comment by nWidart** [comment]
Sorry for the late reply & thanks for reporting the issue. I'll fix the docs, and try to find why it's failing.

**Comment by nWidart** [comment]
Documentation has been fixed. The command works, but isn't showing any output. However it does publish the migrations as expected.
