### ISSUE TITLE
Target class [cache] does not exist when using Redis as a session driver

### ISSUE THREAD

**Issue by DaLukasDev** [nWidart/laravel-modules#1844]
When Redis is configured as a session driver I get the error:

```
In Container.php line 906:

  Target class [cache] does not exist.


In Container.php line 904:

  Class "cache" does not exist


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

However changing the session driver back to file fixes this issue.
I saw this stale/close issue [#1529]  maybe they are related somehow.

**Comment by dcblogdev** [comment]
I'm not getting this when running redis on Laravel 11 and Laravel Modules v11

```bash
SESSION_DRIVER=redis
CACHE_STORE=redis
```

Do you have any steps I can follow?

I have a local redis server running, my application runs normally, doing a composer update or dump-autoload

**Comment by DaLukasDev** [comment]
I found our issue. We were returning an exception in our bootstrap/app.php which the redis session driver was not to happy about. 😅 

Thanks for the quick answer and sorry for wasting your time!

**Comment by dcblogdev** [comment]
no problem, glad you found the cause.
