### ISSUE TITLE
commands not working

### ISSUE THREAD

**Issue by vtscarlos** [nWidart/laravel-modules#185]
Hello, when loading the package I see that when trying to launch a command in the terminal does not detect the commands of the modules, I have configured the following.

![sin titulo](https://cloud.githubusercontent.com/assets/5741090/24397014/63867c0c-13a5-11e7-9486-5e351f25eafe.png)

```    
"require": {
        "php": ">=5.6.4",
        "nwidart/laravel-modules": "^1.19",
        "barryvdh/laravel-ide-helper": "*",
        "filp/whoops": "*",
        "graham-campbell/exceptions": "^9.3.0",
        "kodeine/laravel-meta": "dev-master",
        "laracasts/flash": "^2.0",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "*",
        "laravelcollective/html": "*",
        "maatwebsite/excel": "*",
        "santigarcor/laratrust": "3.2.*"
    },
```

```
Providers;
Nwidart\Modules\LaravelModulesServiceProvider::class,

Aliases:
'Module' => Nwidart\Modules\Facades\Module::class,

**Comment by nWidart** [comment]
Hi,

You need to load your commands into laravel after you created one. Check the laravel documentation on how to do this.

**Comment by vtscarlos** [comment]
Laravel está funcionando con los demás modulos correctamente , es al meter este paquete cuando sucede esto

**Comment by LeonardoAthayde** [comment]
Check out the version, maybe is not compatible

**Comment by nWidart** [comment]
You need to register your commands into laravel, just as in any laravel app.
