### ISSUE TITLE
include file issue 

### ISSUE THREAD

**Issue by Sulan27** [nWidart/laravel-modules#1852]
im using this 
<script src="{{asset('Modules/CourseSetting/Resources/assets/js/course.js')}}"></script>
but i got the error like the file is not found . i have the file in modules folder .

**Comment by dcblogdev** [comment]
If the file exists in that location maybe it's cached? is the module enabled?

is your resources folder spelt Resources? if it's resources it won't work due to case sensitivity on Linux systems

**Comment by Sulan27** [comment]
![Screenshot_1](https://github.com/nWidart/laravel-modules/assets/160002759/519a5909-324e-49bf-b3a0-4dc92c15ce43)
check this image

**Comment by dcblogdev** [comment]
Is the module enabled? 

```bash
php artisan module:enable CourseSetting
```

Clear the cache

```bash
php artisan optimize:clear
```

**Comment by Sulan27** [comment]
yes sir, its enabled and i already cleared the cache but it still shows like that ...
![image](https://github.com/nWidart/laravel-modules/assets/160002759/3f8c6321-78e0-4cd9-89d7-b3888cca41d0)

**Comment by dcblogdev** [comment]
oooh I see what's happening. You cannot call the file directly as it's outside the public folder. Instead, you should use vite or webpack to build the assets

See https://laravelmodules.com/docs/v11/compiling-assets for more details.
