### ISSUE TITLE
php artisan module:migrate-refresh Otp not working with me

### ISSUE THREAD

**Issue by KhuloodBatis** [nWidart/laravel-modules#1853]
i tray to do fresh migration by using this commnd 
`php artisan module:migrate-refresh Otp`

but not working and show me this error 

![Screenshot 2024-05-06 at 2 16 57 PM](https://github.com/nWidart/laravel-modules/assets/50932099/9492d581-1d6f-4f0f-bcab-588f8aa6c69e)

i do not want to do migration fresh on all my project but in the module Otp

**Comment by solomon-ochepa** [comment]
The issue originates from the migrations table. The migration column cannot be found, indicating that either the column doesn't exist or the table structure has been tampered with.

Please, check out the migrations table to confirm.

**Comment by KhuloodBatis** [comment]
the issue not for column but the command  
`php artisan module:migrate-refresh Otp`

 not working i should use the refresh all migration without specific tables

**Comment by dcblogdev** [comment]
when version of Laravel and the package are you using?

This command has recently been updated to only the module is effected https://github.com/nWidart/laravel-modules/blob/master/src/Commands/Database/MigrateRefreshCommand.php

**Comment by KhuloodBatis** [comment]
laravel 10
