### ISSUE TITLE
Class "Modules\Admin\Providers\AdminServiceProvider" not found

### ISSUE THREAD

**Issue by ksaif121786** [nWidart/laravel-modules#1856]
showing me  this  Class "Modules\Admin\Providers\AdminServiceProvider" not found and composer dump-autoload not working

**Comment by irvine48** [comment]
https://github.com/nWidart/laravel-modules?tab=readme-ov-file#autoloading

try to update this part, i successful solve this issue on my latest pull.

**Comment by yangwenqian** [comment]
I have encountered the same situation with laravel 11. Have you resolved it?

**Comment by yangwenqian** [comment]
I have encountered the same situation with laravel 11. Have you resolved it?
my step:
1.laravel new website (v11)

**Comment by yangwenqian** [comment]
I have encountered the same situation with laravel 11. Have you resolved it?
my step:
1.laravel new website (v11) & artisan migrate
2.composer require nwidart/laravel-modules & vendor:publish
3.update extra in composer.json
![12](https://github.com/nWidart/laravel-modules/assets/3896297/5612abc8-a83a-464f-b425-0e3090ed74a6)
4.composer dump-autoload
5.php artisan module:make Blog
then:
Class "Modules\Blog\Providers\BlogServiceProvider" not found
![13](https://github.com/nWidart/laravel-modules/assets/3896297/d504246d-acf7-4279-baed-1f9a47a20a3b)

**Comment by solomon-ochepa** [comment]
Can you share a screenshot of your module's `composer.json`, `module.json` and the provider class?

**Comment by solomon-ochepa** [comment]
> I have encountered the same situation with laravel 11. Have you resolved it?
>
> my step:
> 1. laravel new website (v11) & artisan migrate
> 2. composer require nwidart/laravel-modules & vendor:publish
> 3. update extra in composer.json
![12](https://private-user-images.githubusercontent.com/3896297/331490697-5612abc8-a83a-464f-b425-0e3090ed74a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NzI2MTAsIm5iZiI6MTcxNTk3MjMxMCwicGF0aCI6Ii8zODk2Mjk3LzMzMTQ5MDY5Ny01NjEyYWJjOC1hODNhLTQ2NGYtYjQyNS0wZTMwOTBlZDc0YTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTdUMTg1ODMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzIyMzY5ZDU1NzI2YmY2ZmUyOGExYjI0MjVmYzU2NTE0NDRhMTk0MzEzNGZlZTkzNTZiYTc2MmVhYTBkMDdmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7Kwu-I-0e67w8nY5b9prFP2a81wSLbH9TVT8x_GtWHY)
> ...

Your main `composer.json` file is okay.

**Comment by yangwenqian** [comment]
It is currently running normally, it is my own problem. opcache setting error.

**Comment by yangwenqian** [comment]
> Can you share a screenshot of your module's `composer.json`, `module.json` and the provider class?

It is currently running normally, it is my own problem. opcache setting error. 
thanks.

**Comment by ami-hp** [comment]
I have the same problem with v11
any solutions?
![image](https://github.com/nWidart/laravel-modules/assets/83532676/3f81c99d-3292-4a41-907f-95cfb0e323c1)

**Comment by solomon-ochepa** [comment]
> I have the same problem with v11 any solutions? ![image](https://private-user-images.githubusercontent.com/83532676/334583829-3f81c99d-3292-4a41-907f-95cfb0e323c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjUzODcsIm5iZiI6MTcxNjk2NTA4NywicGF0aCI6Ii84MzUzMjY3Ni8zMzQ1ODM4MjktM2Y4MWM5OWQtMzI5Mi00YTQxLTkwN2YtOTVjZmIwZTMyM2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA2NDQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YjkxYzdjZTgwMGYyZWJjN2RjYzFhMDA0MTFmNDg2NzBkNmFiOTg2YmRhYzA1MTVmYzMyMDlkYzRiOTJkYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vzVkNy3tUDxxAui5d9EMaXkDMOerNAkSX_m3w3ka_OQ)

Check your module composer.json, module.json and the Service Provider itself. Compare the value of the namespace in each of the files.

**Comment by solomon-ochepa** [comment]
Lastly, try run `composer dump-autoload`

**Comment by ami-hp** [comment]
@solomon-ochepa i ran ```composer dump-autoload```
modules composer :
```
{
    "name": "nwidart/user",
    "description": "",
    "authors": [
        {
            "name": "Nicolas Widart",
            "email": "n.widart@gmail.com"
        }
    ],
    "extra": {
        "laravel": {
            "providers": [],
            "aliases": {

            }
        }
    },
    "autoload": {
        "psr-4": {
            "Modules\\User\\": "app/",
            "Modules\\User\\Database\\Factories\\": "database/factories/",
            "Modules\\User\\Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Modules\\User\\Tests\\": "tests/"
        }
    }
}
```

module.json:
```
{
    "name": "User",
    "alias": "user",
    "description": "",
    "keywords": [],
    "priority": 0,
    "providers": [
        "Modules\\User\\Providers\\UserServiceProvider"
    ],
    "files": []
}
```

i even added psr-4 to composer to make sure and ran it all again.
![image](https://github.com/nWidart/laravel-modules/assets/83532676/e5ed8c6f-c873-4eba-8b42-6203d1c9d51d)

by the way this is out of the box and according to documentation. didn't change anything yet

**Comment by solomon-ochepa** [comment]
Could you remove the addition at line 30 from the module's `composer.json` (image above)?

Please ensure the main `composer.json` doesn't include the modules in its autoload.psr-4 section.

If the problem persists, please feel free to reach out for direct support. To assist you effectively, I would need limited access to your code.
WhatsApp: https://wa.me/2348162682618, Telegram: https://t.me/solomon_ochepa or solomonochepa@gmail.com

**Comment by yaobiao131** [comment]
same error for me

**Comment by Mohamedalbarbary** [comment]
same error with laravel11

**Comment by Mohamedalbarbary** [comment]
**To Fix This Issue**
Please update extra in composer.json :

![extra](https://github.com/nWidart/laravel-modules/assets/48839408/2b3a29f3-2bb4-4d1b-84ff-d23974e0680c)

Run Command : `composer dump-autoload`

**Comment by DeRaja** [comment]
Hello!

Surprisingly, I have the same and identical error on Laravel 12 and am shoicked as this error is still there, although it was declared before one year as completed.

I also noticed in the above that  the Error ["Class "Modules\Blog\Providers\BlogServiceProvider" not found] is obvious because it is generating files under "Modules\Blog\ -->App\>-- Providers\BlogServiceProvider". The BlogServiceProvider resides or is created under the dir app.

In the module.json, I added the App as well as in the namespaces of app files generated.

I (as a test) created a new module "Core". It is giving me an error:

```
Generating optimized autoload files
Class Modules\Core\Http\Controllers\CoreController located in ./Modules/Core/app/Http/Controllers/CoreController.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.
Class Modules\Core\Providers\EventServiceProvider located in ./Modules/Core/app/Providers/EventServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.
Class Modules\Core\Providers\RouteServiceProvider located in ./Modules/Core/app/Providers/RouteServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.
Class Modules\Core\Providers\CoreServiceProvider located in ./Modules/Core/app/Providers/CoreServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.
Class Modules\Core\Database\Seeders\CoreDatabaseSeeder located in ./Modules/Core/database/seeders/CoreDatabaseSeeder.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error

  Class "Modules\Core\App\Providers\CoreServiceProvider" not found
```

In the composer.json extra, I already have merge-plugin to include ("Modules/*/composer.json") as well as in psr-4 ("Modules\\": "Modules/").


Any further suggestions?

**Comment by solomon-ochepa** [comment]
> Hello!
> 
> Surprisingly, I have the same and identical error on Laravel 12 and am shoicked as this error is still there, although it was declared before one year as completed.
> 
> I also noticed in the above that  the Error ["Class "Modules\Blog\Providers\BlogServiceProvider" not found] is obvious because it is generating files under "Modules\Blog\ -->App\>-- Providers\BlogServiceProvider". The BlogServiceProvider resides or is created under the dir app.
> 
> In the module.json, I added the App as well as in the namespaces of app files generated.
> 
> I (as a test) created a new module "Core". It is giving me an error:
> 
> ```
> Generating optimized autoload files
> Class Modules\Core\Http\Controllers\CoreController located in ./Modules/Core/app/Http/Controllers/CoreController.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.
> Class Modules\Core\Providers\EventServiceProvider located in ./Modules/Core/app/Providers/EventServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.
> Class Modules\Core\Providers\RouteServiceProvider located in ./Modules/Core/app/Providers/RouteServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.
> Class Modules\Core\Providers\CoreServiceProvider located in ./Modules/Core/app/Providers/CoreServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.
> Class Modules\Core\Database\Seeders\CoreDatabaseSeeder located in ./Modules/Core/database/seeders/CoreDatabaseSeeder.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.
> > Illuminate\Foundation\ComposerScripts::postAutoloadDump
> > @php artisan package:discover --ansi
> 
>    Error
> 
>   Class "Modules\Core\App\Providers\CoreServiceProvider" not found
> ```
> 
> In the composer.json extra, I already have merge-plugin to include ("Modules/*/composer.json") as well as in psr-4 ("Modules\\": "Modules/").
> 
> 
> Any further suggestions?
> 

This issue occurs because the current `modules.paths.app_folder` and it's replacement logic doesn't work as expected (it forced everything to be on the root "./" without consideration that some may want to maintain the default Laravel structure `./app/` or even custom path such as `./src/`

A PR has been submitted to fix this issue already. It will be rectified soon.

**Comment by AliYazdanifar** [comment]
I have this problem too. 
Larval 12
Does anyone have an idea to solve this?

**Comment by puntodamar2** [comment]
> [@AliYazdanifar](https://github.com/AliYazdanifar) Try the above solution I write for Laravel 12 and let me know

in my case composer dump-autoload return the same error
