### ISSUE TITLE
Enabling Cache on server problem

### ISSUE THREAD

**Issue by AbdallahAli912** [nWidart/laravel-modules#1858]
- when cache enabled locally every thing is ok, but while deploying on server it failed with error.
<img width="1012" alt="Screenshot 2024-05-21 at 11 36 06 AM" src="https://github.com/nWidart/laravel-modules/assets/54299150/4c60ed19-25c4-4332-95e3-bc5c8c4d0588">
- Here is my cache  in config file modules.php
 'cache' => [
        'enabled' => true,
        'key' => 'laravel-modules',
        'lifetime' => 60,
    ],
 - cache driver is  file.
 - "php": "^8.0"
 - "laravel/framework": "^9.0" 
 - "nwidart/laravel-modules": "^8.2",
 
plz some help

**Comment by heshammostafa123** [comment]
same issue

**Comment by dcblogdev** [comment]
we have changed how caching works internally, you no longer need to setup caching and turn it on yourself its now automatic. Cache is stored in app/bootstrap/cache/modules.php

if you need to refresh it run `php artisan module:clear-compiled`

**Comment by misog** [comment]
@dcblogdev what should be used in deployment? The command `php artisan module:clear-compiled` is not documented.
