### ISSUE TITLE
Service Injection in module blade template

### ISSUE THREAD

**Issue by designvoid** [nWidart/laravel-modules#186]
So I am currently trying to do the following:

	@inject('data', 'Modules\Atoz\Providers\AtozServiceProvider')

	<div>
		Monthly Revenue: {{ $data->getData() }}.
	</div>

But its throwing this error:

	Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\ServiceProvider (View: /home/vagrant/Code/Mekon/Modules/Atoz/Resources/views/dash-widget.blade.php) (View: /home/vagrant/Code/Mekon/Modules/Atoz/Resources/views/dash-widget.blade.php)

Any ideas? I'm kid of at a loss... Everything else is functioning perfectly with the module.

**Comment by nWidart** [comment]
I've never used that feature of laravel, and wont be any time soon so I can't really help you here.

I doubt you want to inject a service provider into a view, maybe a repository instead ? Make sure that repository is bound in the IoC container.
