### ISSUE TITLE
The package does not emit any events

### ISSUE THREAD

**Issue by osama-98** [nWidart/laravel-modules#1862]
Can this package have an events?

Like having an event after the database is migrated, database seeded, module created, or more events.

**Comment by osama-98** [comment]
@dcblogdev

**Comment by BechirAhmed** [comment]
any answers? how to listen to module events? like once is disabled or enabled...

**Comment by dcblogdev** [comment]
yes, I've added details event documentation

https://laravelmodules.com/docs/v11/registering-module-events#module-events
