### ISSUE TITLE
Migration priority ignored when using artisan migrate

### ISSUE THREAD

**Issue by danilogiacomi** [nWidart/laravel-modules#1865]
Hi all,
I've read all the issues here, and I understand that the _artisan module:migrate_ command respects the priority set in the module.json files in each module, but when I run the 
 
> _artisan migrate:fresh_ 

command it also execute the migration from the modules, but then it doesn't respect the priorities and perform them in alphabetical order.

I can't find a configuration to ignore modules migrations when running the global _artisan migrate:fresh_ command, therefore (since some modules migrations have foreign keys to another module table) it fails as it tries to migrate the modules in the "wrong" order.

Is there a way to let the _migrate:fresh_ honor the priorities set in each model or to ignore the models migration at all? (I would then run the _module:migrate_ artisan comand to finish it up)

Thanks!

**Comment by alissn** [comment]
Hi,

I am currently refactoring this command to improve its functionality and efficiency.
If possible, i'll add this option.
