### ISSUE TITLE
Class "Modules\Faq\Providers\FaqServiceProvider" not found

### ISSUE THREAD

**Issue by abodh-addweb** [nWidart/laravel-modules#1869]
when i run php artisan module:make Faq i get same issue
Class "Modules\Faq\Providers\FaqServiceProvider" not found

**Comment by alikhansalmani** [comment]
hi,
 are you run command `composer du` ? 
 also check [upgrade](https://laravelmodules.com/docs/v11/upgrade) or [Installation and Setup](https://laravelmodules.com/docs/v11/installation-and-setup) page.

**Comment by inkomomutane** [comment]
@abodh-addweb 
By default the module classes are not loaded automatically. You can autoload your modules by adding merge-plugin to the extra section:

```json 

 "extra": {
    "laravel": {
        "dont-discover": []
    },
    "merge-plugin": {
        "include": [
            "Modules/*/composer.json"
        ]
    }
},
    ```
    I think this issue should be closed.

**Comment by abodh-addweb** [comment]
thank you so much it's work
