### ISSUE TITLE
Create module without artisan

### ISSUE THREAD

**Issue by montyclt** [nWidart/laravel-modules#187]
Is a good idea create modules creating the directory (and subdirectories) in modules directory whitout using artisan? I'm making a private app and I want to offer documentation and API to others developers for create modules of my app, but never showing all code of my app, simply creating the module directory, zipping it and uploading it via the app.

Is safe do it? Maybe problems loading the module?

**Comment by nWidart** [comment]
You can create modules manually indeed without issues. I often do this for very simple modules with few classes.

**Comment by montyclt** [comment]
I ask it because I see the modules have a ServiceProvider that register translations, views and more.

Do I need create this provider in my new modules that I create creating the folder?

Is posible do the "module initialization" without a provider?

Thanksyou

**Comment by nWidart** [comment]
No you need a provider do put this code in. Up to you where, and which provider (could be in the native AppServiceProvider).
