### ISSUE TITLE
How to add package in module?

### ISSUE THREAD

**Issue by treetechsuman** [nWidart/laravel-modules#188]
Suppose i have product module and i need image intervention for this module how can i add this package in my product module, i want to wrap up every things with in module is this possible?

**Comment by nWidart** [comment]
**If module will be re used**

You can add that dependency in the module compose.json file, and then run `php artisan module:update yourmodule`. This will add your dependency to the main composer.json file & install the requirement.

**If module won't be re-used**

Add your dependency to the main composer.json file only.
