### ISSUE TITLE
Migration: Nothing to migrate

### ISSUE THREAD

**Issue by osama-98** [nWidart/laravel-modules#1881]
After the last release the migration is not working as expected, instead it goes through all the modules without finding the migrations and prints "noting to migrate" on each module

this is the [update](https://github.com/nWidart/laravel-modules/commit/6ab190dcefde58ba2ff1d1cefee39ee0c85e330c) that causes the issue.

**Comment by osama-98** [comment]
@dcblogdev

**Comment by alissn** [comment]
Hi, @osama-98

Please follow the steps below to identify the issue and share your results:

1. Modify the file located at `vendor/nwidart/laravel-modules/src/Commands/Database/MigrateCommand.php` on line 38:

```diff
         $this->migrator = app('migrator');
-        $this->migration_list = collect($this->migrator->paths());
+        $this->migration_list = collect($this->migrator->paths())->dd();
     }
```

2. Run the command `php artisan migrate` or `php artisan migrate:fresh`.

The result should not be empty and should include the migration paths of each module.

If it is empty, check your module provider. It should include this line to register migrations:

```php
        $this->loadMigrationsFrom(module_path($this->moduleName, 'Database/Migrations'));
```

Let me know if this resolves your issue.

**Comment by JohnnyMaynne** [comment]
After the update  v11.0.10 => v11.0.11 , migrations stopped working and show the message "Nothing to migrate". Now you need to create a service provider in each module and register migrations in it, although previously everything worked without this. Now we have to do a lot of work just to run migrations.

**Comment by trants** [comment]
Same issues!
