### ISSUE TITLE
installition issue 

### ISSUE THREAD

**Issue by EslamTeleb1** [nWidart/laravel-modules#1886]
after going with the docs to install it got this problem with the first module created 

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error

  Class "Modules\Admin\Providers\AdminServiceProvider" not found

  at vendor\laravel\framework\src\Illuminate\Foundation\Application.php:855
    851▕      * @return \Illuminate\Support\ServiceProvider
    852▕      */
    853▕     public function resolveProvider($provider)
    854▕     {
  ➜ 855▕         return new $provider($this);
    856▕     }
    857▕
    858▕     /**
    859▕      * Mark the given provider as registered.

  1   vendor\laravel\framework\src\Illuminate\Foundation\Application.php:789
      Illuminate\Foundation\Application::resolveProvider("Modules\Admin\Providers\AdminServiceProvider")

  2   vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:75
      Illuminate\Foundation\Application::register("Modules\Admin\Providers\AdminServiceProvider")

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by alissn** [comment]
Hi, @EslamTeleb1 

do you add `extra` section to your composer.json?

more info on document [Autoloading](https://laravelmodules.com/docs/v11/installation-and-setup#autoloading).

after that,  you need run command `composer update` or `composer dump-autoload `

**Comment by EslamTeleb1** [comment]
hi @alissn 
thanks for replying , 
yes , this my composer.json :
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The skeleton application for the Laravel framework.",
    "keywords": ["laravel", "framework"],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.3",
        "laravel/tinker": "^2.8",
        "nwidart/laravel-modules": "v10.0.1",
        "spatie/laravel-translatable": "^6.7",
        "tymon/jwt-auth": "^2.1"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders"
        },
        "files": [
            "app/Helpers/codeGenerator.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        },
        "merge-plugin": {
            "include": [
                "Modules/*/composer.json"
            ]
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true,
            "wikimedia/composer-merge-plugin": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}

**Comment by alissn** [comment]
after run `compser update` problem not solved?

**Comment by EslamTeleb1** [comment]
unfortunately , yes
I have tried also to remove vendor and composer.lock 
then install but causes the same problem 
i have tried to delete the package an install it again 
i was working , so i  have guessd the version updated itself during the development so i have downgrade it to match laravel v10 
but still have this problem ,why ?
what else should i try ?

**Comment by EslamTeleb1** [comment]
hello, 
i have got htis error 

composer dump-autoload
Generating optimized autoload files
Class Modules\Admin\Http\Controllers\AdminController located in ./Modules/Admin/app/Http/Controllers/AdminController.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                 
Class Modules\Admin\Http\Controllers\AuthController located in ./Modules/Admin/app/Http/Controllers/AuthController.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                   
Class Modules\Admin\Models\Admin located in ./Modules/Admin/app/Models/Admin.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.
Class Modules\Admin\Providers\AdminServiceProvider located in ./Modules/Admin/app/Providers/AdminServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                     
Class Modules\Admin\Providers\EventServiceProvider located in ./Modules/Admin/app/Providers/EventServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                     
Class Modules\Admin\Providers\RouteServiceProvider located in ./Modules/Admin/app/Providers/RouteServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                     
Class Modules\Admin\Database\Seeders\AdminDatabaseSeeder located in ./Modules/Admin/database/seeders/AdminDatabaseSeeder.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                             
Class Modules\Admin\Database\Seeders\AdminSeeder located in ./Modules/Admin/database/seeders/AdminSeeder.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                             
Class Modules\Category\Http\Controllers\CategoryController located in ./Modules/Category/app/Http/Controllers/CategoryController.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                     
Class Modules\Category\Http\Controllers\SubCategoryController located in ./Modules/Category/app/Http/Controllers/SubCategoryController.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                               
Class Modules\Category\Http\Requests\SubCategoryCreateRequest located in ./Modules/Category/app/Http/Requests/SubCategoryCreateRequest.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                               
Class Modules\Category\Http\Requests\SubCategoryUpdateRequest located in ./Modules/Category/app/Http/Requests/SubCategoryUpdateRequest.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                               
Class Modules\Category\Http\Requests\UpdateCategoryRequest located in ./Modules/Category/app/Http/Requests/UpdateCategoryRequest.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                     
Class Modules\Category\Models\Category located in ./Modules/Category/app/Models/Category.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                                             
Class Modules\Category\Models\SubCategory located in ./Modules/Category/app/Models/SubCategory.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                                       
Class Modules\Category\Providers\CategoryServiceProvider located in ./Modules/Category/app/Providers/CategoryServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                         
Class Modules\Category\Providers\EventServiceProvider located in ./Modules/Category/app/Providers/EventServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                               
Class Modules\Category\Providers\RouteServiceProvider located in ./Modules/Category/app/Providers/RouteServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                               
Class Modules\Category\Database\Seeders\CategoryDatabaseSeeder located in ./Modules/Category/database/seeders/CategoryDatabaseSeeder.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                 
Class Modules\Category\Database\Seeders\CategorySeeder located in ./Modules/Category/database/seeders/CategorySeeder.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                 
Class Modules\Client\Http\Controllers\AuthController located in ./Modules/Client/app/Http/Controllers/AuthController.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                 
Class Modules\Client\Http\Controllers\ClientController located in ./Modules/Client/app/Http/Controllers/ClientController.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                             
Class Modules\Client\Http\Controllers\FavoriteController located in ./Modules/Client/app/Http/Controllers/FavoriteController.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                         
Class Modules\Client\Http\Controllers\ShippingAddressController located in ./Modules/Client/app/Http/Controllers/ShippingAddressController.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                           
Class Modules\Client\Http\Requests\ClientEditRequest located in ./Modules/Client/app/Http/Requests/ClientEditRequest.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                 
Class Modules\Client\Http\Requests\ClientRegisterRequest located in ./Modules/Client/app/Http/Requests/ClientRegisterRequest.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                         
Class Modules\Client\Http\Requests\StoreShippingAddressRequest located in ./Modules/Client/app/Http/Requests/StoreShippingAddressRequest.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                             
Class Modules\Client\Http\Requests\UpdateShippingAddressRequest located in ./Modules/Client/app/Http/Requests/UpdateShippingAddressRequest.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                           
Class Modules\Client\Interfaces\SmsInterface located in ./Modules/Client/app/Interfaces/SmsInterface.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                                 
Class Modules\Client\Models\Client located in ./Modules/Client/app/Models/Client.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                                                     
Class Modules\Client\Models\Favorite located in ./Modules/Client/app/Models/Favorite.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                                                 
Class Modules\Client\Models\ShippingAddress located in ./Modules/Client/app/Models/ShippingAddress.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                                   
Class Modules\Client\Providers\ClientServiceProvider located in ./Modules/Client/app/Providers/ClientServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                 
Class Modules\Client\Providers\EventServiceProvider located in ./Modules/Client/app/Providers/EventServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                   
Class Modules\Client\Providers\RouteServiceProvider located in ./Modules/Client/app/Providers/RouteServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                   
Class Modules\Client\Providers\SmsProvider located in ./Modules/Client/app/Providers/SmsProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                                     
Class Modules\Client\Services\SmsMisr located in ./Modules/Client/app/Services/SmsMisr.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                                               
Class Modules\Client\Database\Seeders\ClientDatabaseSeeder located in ./Modules/Client/database/seeders/ClientDatabaseSeeder.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                         
Class Modules\Product\Http\Controllers\ProductController located in ./Modules/Product/app/Http/Controllers/ProductController.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                         
Class Modules\Product\Http\Requests\ProductCreateRequest located in ./Modules/Product/app/Http/Requests/ProductCreateRequest.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                         
Class Modules\Product\Http\Requests\ProductUpdateRequest located in ./Modules/Product/app/Http/Requests/ProductUpdateRequest.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                         
Class Modules\Product\Models\Product located in ./Modules/Product/app/Models/Product.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                                                 
Class Modules\Product\Providers\EventServiceProvider located in ./Modules/Product/app/Providers/EventServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                 
Class Modules\Product\Providers\ProductServiceProvider located in ./Modules/Product/app/Providers/ProductServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                             
Class Modules\Product\Providers\RouteServiceProvider located in ./Modules/Product/app/Providers/RouteServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                 
Class Modules\Product\Transformers\ProductCollection located in ./Modules/Product/app/Transformers/ProductCollection.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                 
Class Modules\Product\Transformers\ProductResource located in ./Modules/Product/app/Transformers/ProductResource.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                                     
Class Modules\Product\Database\Seeders\ProductDatabaseSeeder located in ./Modules/Product/database/seeders/ProductDatabaseSeeder.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                                                                                                                     
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error

  Class "Modules\Admin\Providers\AdminServiceProvider" not found

  at vendor\laravel\framework\src\Illuminate\Foundation\Application.php:855
    851▕      * @return \Illuminate\Support\ServiceProvider
    852▕      */
    853▕     public function resolveProvider($provider)
    854▕     {
  ➜ 855▕         return new $provider($this);
    856▕     }
    857▕
    858▕     /**
    859▕      * Mark the given provider as registered.

  1   vendor\laravel\framework\src\Illuminate\Foundation\Application.php:789
      Illuminate\Foundation\Application::resolveProvider("Modules\Admin\Providers\AdminServiceProvider")

  2   vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:75
      Illuminate\Foundation\Application::register("Modules\Admin\Providers\AdminServiceProvider")

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by Max-Hutschenreiter** [comment]
I also have not the does "not comply with psr-4 autoloading standard" for pretty much every class in a Module.

**Comment by alissn** [comment]
@Max-Hutschenreiter 

what is you laravel and package version?
you have fresh project or migrate from old version to v11 ?

**Comment by Saiful-islam-sohan** [comment]
By default, the module classes are not loaded automatically. You can autoload your modules using psr-4

{
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Modules\\": "Modules/"
    }
  }
}
"extra": {
    "laravel": {
        "dont-discover": []
    },
    "merge-plugin": {
        "include": [
            "Modules/*/composer.json"
        ]
    }
},
add this two things

**Comment by Max-Hutschenreiter** [comment]
@alissn I think I found my problem 

I searched via google for the documentation and then it suggests 
https://nwidart.com/laravel-modules/v6/installation-and-setup
but this is the outdated version since its only going until v6.

@Saiful-islam-sohan that is the correct solution for me as stated in the readme file of the package.
