### ISSUE TITLE
Migration priority ignored 

### ISSUE THREAD

**Issue by JohnnyMaynne** [nWidart/laravel-modules#1887]
Laravel: v11.1.2
Package: v11.0.11

I have such a list in a module: 

<img width="1283" alt="image" src="https://github.com/nWidart/laravel-modules/assets/26120256/8db65136-f3f4-45bf-8377-488748ed8f92">

If you look into it, it becomes clear that I have 4 modules that have a priority of 10, this is necessary because the tables of these modules have foreign keys to the users table in the User module, which has a priority of 0.

But I get an error because modules ignore priority and are executed not in priority order, but in name order

<img width="1310" alt="image" src="https://github.com/nWidart/laravel-modules/assets/26120256/99d926f8-899b-46d7-8689-dfeeae03081d">

**Comment by dcblogdev** [comment]
@alissn would you be able to look into this?, if not I'll look at it as soon as I get a chance.

**Comment by alissn** [comment]
@dcblogdev i'll check it.

**Comment by alissn** [comment]
@JohnnyMaynne 

Hi,

When calling the command with the `--direction` option, the modules are sorted by `priority`. You can view the order in the laravel Prompt `Select Modules`.

The order logic hasn't changed. First, the method `allEnabled` is called, and then the modules are sorted based on the specified direction. You can view the relevant [code here](https://github.com/nWidart/laravel-modules/blob/593202ff3409cdf5bc0cdc802d1825a7bc54a769/src/FileRepository.php#L266-L283).

In your case, the initial list looks like this:
```
[
'Auth',
'Author',
'Briefcase',
...
'Timer',
'User'
]
```
After sorting, it changes to this:
```
[
'Auth',
'Briefcase',
'Core'
...
'Author',
'Comment',
'Member',
'Timer'
]
```

Is it okay to run the migration for the `Auth` module first? Do you agree with this approach?

**Comment by JohnnyMaynne** [comment]
@alissn in fact, in Prompt `Select Modules` they are sorted in a priority order even without a flag, but for some reason migration doesn’t happen that way

<img width="576" alt="image" src="https://github.com/nWidart/laravel-modules/assets/26120256/0757ad5b-5ee5-400d-aced-e0e0d2c2d9be">

**Comment by JohnnyMaynne** [comment]
Another strange thing is that it shows that migrations are performed in the Auth module, although they are not there

<img width="1284" alt="image" src="https://github.com/nWidart/laravel-modules/assets/26120256/84b94529-b946-4c2d-a031-f7f3166bda22">

**Comment by alissn** [comment]
> @alissn in fact, in Prompt `Select Modules` they are sorted in a priority order even without a flag, but for some reason migration doesn’t happen that way

it's correct, command option define in class, and logic [here](https://github.com/nWidart/laravel-modules/blob/593202ff3409cdf5bc0cdc802d1825a7bc54a769/src/Commands/BaseCommand.php#L85-L89):
```php
        $modules = $this->hasOption('direction')
            ? array_keys($this->laravel['modules']->getOrdered($input->hasOption('direction')))
            : array_keys($this->laravel['modules']->all());
```

and command `module:migrate` has `dirction` option, [here](https://github.com/nWidart/laravel-modules/blob/593202ff3409cdf5bc0cdc802d1825a7bc54a769/src/Commands/Database/MigrateCommand.php#L71-L80):
```php
    protected function getOptions()
    {
        return [
            ['direction', 'd', InputOption::VALUE_OPTIONAL, 'The direction of ordering.', 'asc'],
            ...
        ];
    }
```

**Comment by alissn** [comment]
> Another strange thing is that it shows that migrations are performed in the Auth module, although they are not there.

When the `migrations` table does not exist, it is created first.

The package uses the `migrate` command from the Laravel framework to perform migrations. If you check the migrate command of the framework, you will see that it first checks whether the `migrations` table exists before running other migrations. You can find the relevant code [here](https://github.com/laravel/framework/blob/980e8d5cd0bfe72f2cd878a785e8d2c22eefaf18/src/Illuminate/Database/Console/Migrations/MigrateCommand.php#L109-L130) and [here](https://github.com/laravel/framework/blob/980e8d5cd0bfe72f2cd878a785e8d2c22eefaf18/src/Illuminate/Database/Console/Migrations/MigrateCommand.php#L138-L155)

**Comment by JohnnyMaynne** [comment]
Thank you for the detailed explanation, but unfortunately, even with the directive `php artisan module:migrate --direction`, the order is not being followed.

**Comment by alissn** [comment]
@JohnnyMaynne 
Please change you module priority.

When priority is equal, sort by module name alphabetically.

**Comment by JohnnyMaynne** [comment]
@alissn As soon as I set the first module (in alphabetical order) priority 1 - everything worked. 

I think I understand the point - the module that comes first in alphabetical order must have a priority greater than zero. 

Thank you for helping me solve the problem, I really appreciate it 👍
