### ISSUE TITLE
Seeders do not sow

### ISSUE THREAD

**Issue by JohnnyMaynne** [nWidart/laravel-modules#1888]
Laravel: v11.1.2
Package: v11.0.11

I have this module structure, which I changed in the configuration. 

<img width="201" alt="image" src="https://github.com/nWidart/laravel-modules/assets/26120256/e5c8041c-899b-44a3-8fca-5f8672e0a154">

I issue a command `php artisan module:seed`, it is executed but the data is not sown:

<img width="1262" alt="image" src="https://github.com/nWidart/laravel-modules/assets/26120256/045f4e0b-afcc-4e73-807b-9ae329329aec">

**Comment by solomon-ochepa** [comment]
Register the seeder (`$this->call([...])`) in the `run()` method of the base file `UserDatabaseSeeder.php`, and take note of the "DatabaseSeeder" in the name!

**Comment by JohnnyMaynne** [comment]
> Register the seeder (`$this->call([...])`) in the `run()` method of the base file `UserDatabaseSeeder.php`, and take note of the "DatabaseSeeder" in the name!

I did this before creating issue, but this is a workaround

<img width="396" alt="image" src="https://github.com/user-attachments/assets/4d22b01f-066a-4d07-8330-218d43fc0af2">
