### ISSUE TITLE
Cache - Dont Update

### ISSUE THREAD

**Issue by LeonardoAthayde** [nWidart/laravel-modules#189]
Hello,

Anything code update, on controller, on service provider even views or middleware. I need to wait about 60 seconds to see the changed. It is bad when I am debuging. So there is any solution for this?

**Comment by nWidart** [comment]
Hello,

You should check your php configuration, opcache for instance. This package doesn't cache your php code.

**Comment by LeonardoAthayde** [comment]
Its works, thnks a lot!!!!
