### ISSUE TITLE
use Module to define new auth guard

### ISSUE THREAD

**Issue by BechirAhmed** [nWidart/laravel-modules#1891]
Hi @nWidart,
I'm just asking about something I did and want to ensure it was a good idea. I have used this module package to implement a modular system. Today, I implemented a new module requiring a new auth guard. In an older issue here, I saw that you define configs from the module provider, so I did it (see the code below). I'm wondering if this is the best approach and if it has any side effects. By the way, it works fine as of now.
```
protected function registerClientAuthGuard(): void
{
    $guards = array_merge(config('auth.guards'), [
        'client' => [
            'driver' => 'session',
            'provider' => 'clients',
        ],
    ]);
    config()->set('auth.guards', $guards);

    $providers = array_merge(config('auth.providers'), [
        'clients' => [
            'driver' => 'eloquent',
            'model' => \Modules\CRM\Models\Client::class,
        ],
    ]);
    config()->set('auth.providers', $providers);

    $passwords = array_merge(config('auth.passwords'), [
        'clients' => [
            'provider' => 'clients',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ]);
    config()->set('auth.passwords', $passwords);
}

```

**Comment by adnane-ka** [comment]
I've explored the documentation and reviewed various suggestions but didn't find a more convenient approach than yours. Many other solutions require publishing configuration files, which isn't ideal for a modular system. I'll proceed with your method.
I've also made some refinements:

```php
/**
* @return void
*/
private function registerUserGuard(): void
{
   $auth = include(__DIR__.'/../../config/auth.php');

   foreach($auth as $key => $value){
       config()->set("auth.{$key}", array_merge(config("auth.{$key}"), $value));
   }
}
```

And all your new config should reside in `module/config/auth.php` as follows:
```php
<?php 

return [
    'guards' => [
        'users' => [
            'driver' => 'session', 
            'provider' => 'users', 
        ],
    ],
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => Modules\SaaSModule\Models\User::class,
        ],
    ],
];
```

**Comment by BechirAhmed** [comment]
@adnane-ka Your code is more elegant 👌
