### ISSUE TITLE
Filament panels aren't registered when configured inside a module

### ISSUE THREAD

**Issue by gsmeira** [nWidart/laravel-modules#1892]
I created a module to store all Filament-related files, but I noticed that the panels aren't registered when I load them inside a module (adding them to the `module.json` providers array). Everything works perfectly if I load the ServiceProvider inside the module directly through the `bootstrap/providers.php` file.

```php
use Filament\PanelRegistry;

//...

public function register(): void
{
  $this->app->resolving(PanelRegistry::class, function () {
      dd('test!!!');
  });
}
```

Any idea why the `app->resolving` callback isn't being called when the ServiceProvider is loaded through the `module.json`? Thank you!

**Comment by dcblogdev** [comment]
you may need to run `php artisan module:clear-compiled` to update the cache.
