### ISSUE TITLE
  Trait "Illuminate\Console\Prohibitable" not found

### ISSUE THREAD

**Issue by mktmsameera** [nWidart/laravel-modules#1893]
I need to install this dependencies to my laravel 11 fresh project. when i install, it will return the error as bellow.

Trait "Illuminate\Console\Prohibitable" not found

  at vendor/nwidart/laravel-modules/src/Commands/BaseCommand.php:17
     13▕ use Symfony\Component\Console\Output\OutputInterface;
     14▕ 
     15▕ use function Laravel\Prompts\multiselect;
     16▕ 
  ➜  17▕ abstract class BaseCommand extends Command implements PromptsForMissingInput
     18▕ {
     19▕     use ConfirmableTrait;
     20▕     use Prohibitable;

How can i fix it.

**Comment by alissn** [comment]
Hi, @mktmsameera 


Hi @FMpoli ,

What version of the Laravel framework and package are you trying to install?

also see #1875

**Comment by solomon-ochepa** [comment]
This issue comes up when you are using Laravel `10.x` and laravel-modules `^10.0.11`

Either way, to solve this issue kindly use `10.0.10` instead of `^10.0.11`

**Comment by alissn** [comment]
> This issue comes up when you are using Laravel `10.x` and laravel-modules `^10.0.11`
> 
> Either way, to solve this issue kindly use `10.0.10` instead of `^10.0.11`

@solomon-ochepa 
the latest version of v10 of this package is: [10.0.6](https://github.com/nWidart/laravel-modules/releases/tag/10.0.6)

**Comment by solomon-ochepa** [comment]
> > This issue comes up when you are using Laravel `10.x` and laravel-modules `^10.0.11`
> > Either way, to solve this issue kindly use `10.0.10` instead of `^10.0.11`
> 
> @solomon-ochepa the latest version of v10 of this package is: [10.0.6](https://github.com/nWidart/laravel-modules/releases/tag/10.0.6)

Sorry, I mean 11.0.10

Thanks for the correction.
