### ISSUE TITLE
Creating module error: mkdir(): File exists

### ISSUE THREAD

**Issue by sr-44** [nWidart/laravel-modules#1894]
```shell
rm -rf Modules/WishList
sail artisan optimize:clear
sail artisan module:make WishList --api --force
``` 

![изображение](https://github.com/user-attachments/assets/2b3eb84e-4d68-4509-9c6b-13ee2505384d)

package version: "nwidart/laravel-modules": "^10.0"

**Comment by sr-44** [comment]
![изображение](https://github.com/user-attachments/assets/44eca01e-11f3-4918-b2cd-6168ce7f1be6)

**Comment by solomon-ochepa** [comment]
> ```shell
> rm -rf Modules/WishList
> sail artisan optimize:clear
> sail artisan module:make WishList --api --force
> ```
> 
> ![изображение](https://private-user-images.githubusercontent.com/128609088/348527132-2b3eb84e-4d68-4509-9c6b-13ee2505384d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1Mjk1NDcsIm5iZiI6MTcyMTUyOTI0NywicGF0aCI6Ii8xMjg2MDkwODgvMzQ4NTI3MTMyLTJiM2ViODRlLTRkNjgtNDUwOS05YzZiLTEzZWUyNTA1Mzg0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMVQwMjM0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzA1YjdhOTM2YTQ3MDdhNjU3NGIxNTE1ZGUzYjcwOTJkODhkNWIzZDE5ZmY3YzhlNGY4Mjk0NzM2Yzc2ZGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o8dTrLnO-iUOgCguRQTpmhjdPMCiUMXt139LN0E9Pd0)
> 
> package version: "nwidart/laravel-modules": "^10.0"

You removed the module wrongly!

To delete the WishList module, use `sail artisan module:delete WishList` instead of `rm -rf Modules/WishList`.

To recreate the module, remove the module from the `modules-status.json` file at the root.

**Comment by faridibin** [comment]
@sr-44 

Autoloading
from v11.0 autoloading "Modules\\": "modules/", is no longer required.

By default the module classes are not loaded automatically. You can autoload your modules by adding merge-plugin to the extra section:

```
"extra": {
    "laravel": {
        "dont-discover": []
    },
    "merge-plugin": {
        "include": [
            "Modules/*/composer.json"
        ]
    }
},
```
