### ISSUE TITLE
Prioritizing routes

### ISSUE THREAD

**Issue by alekslyse** [nWidart/laravel-modules#19]
Is it any support for overriding default routes from the modules?

Say if I want to use subdomains instead of subfolder it would be easiest if subdomain.domain.com/something would override domain.com/something

At least kind of option to be set on the group / route to let it override the "default" routes

**Comment by nWidart** [comment]
This isn't something this package provides no.

However leveraging how laravel creates its routes I'm sure you can make it work that way.

**Comment by macwinnie** [comment]
Hi @nWidart,

I struggled about something that correlates to this, I think ...

Let the Laravel app be available at `example.com` (1).
I've implemented a second domain to my Laravel-Application, so `subdomain.example.com` (2) will map to the app as well.

Now, the regular domain (1) should be handled by the default Laravel routes – what really works well.

The `routes/web.php` (3) looks like that:

```php
Route::get('/', 'ExampleController@index');
```

Now I want a module to handle the subdomain. The app is generally running, the `Modules/SubDomain/Routes/web.php` (4) should look like that (in my opinion and understanding):

```php
Route::group(['domain' => 'subdomain.example.com'], function(){
    Route::get('/', 'SubDomainController@index');
});
```

Now, the problem looks like this: the subdomain is also showing the content of the main domain, the default routes are overriding the module ones. If I place the 3 lines of code out of (4) within (3) in front of the definition above, all works fine. Even if I delete the definition out of (3) and leave that file empty, everything is working fine. Only if I split the routes up like above – like it would be clean coded – it fails.

There are a lot of confusing tips out there – on stackoverflow, Laracast and even here on your GitHub-Issues. But none of them really helps me to fix my problem.

Probably you could tell me, why a module should not be abled to do the things mentioned above – or probably reopen this issue for finding a solution? =)

Both of it would be great =)
Cheers,
Martin

**Comment by mikemand** [comment]
Hi Martin,

Would you try wrapping all your default routes in a group with the regular domain? Does that change anything?

What does the output of `php artisan route:list` show?

Also, I would say you should probably open your own issue for this.

**Comment by macwinnie** [comment]
Thanks @mikemand … I'll move to a new issue #670 ;)
