### ISSUE TITLE
Database Driver

### ISSUE THREAD

**Issue by poppabear8883** [nWidart/laravel-modules#191]
Hello,

I'm interested in **extending** your package to be able to support or even add in the ability to use a database driver for manifest data .. (instead of the local .json store) can I get a very basic idea how to do this (what do i need to **implement** or **extend** and how to **register** it), I want to use **Eloquent `Module` model** .. just having a hard time understanding how i can implement this considering your current code base doesn't support this natively.

**Comment by nWidart** [comment]
This is something I'm planning on implementing at some point. Discussed also in  #171

**Comment by poppabear8883** [comment]
i'm working on at-least extending it in my project to include persisting to the database.

example:
```php
class ModuleRepository extends Repository
{

    public function scan()
    {
        $modules = parent::scan();

        foreach ($modules as $key => $module) {
            $find = Module::where('name', $module->name)->get();

            if ($find->isEmpty()) {
                Module::create([
                    'name' => $module->name,
                    'alias' => $module->get('alias'),
                    'description' => $module->get('description')
                ]);
            }
        }

        return $modules;
    }

...
```

temporarily could add in the code base to check config options for example:

```php

'database' => [
    'enabled' => true,

    // the model to use for CRUD operations (ideally Eloquent Model)
    'model' => \App\Module::class, // used for the data layer

    // a custom repository that abides by the `RepositoryInterface` contract
    'repository' => \App\Repositories\ModuleRepository::class
],

```

or something to that effect ...

That IMO would at least be a good start.

Issues I am noticing with the current code base:

- No abstract BaseRepository class
- Separate `Drivers` examples `LocalRepository extends BaseRepository` and `EloquentRepository extends BaseRepository`
- Your Repository class is tightly coupled with the Module class (consider DI for this, or from the above config example)

I will be forking the repository and will contribute PR's as much as possible. I would like to keep this discussion open. Mark as enhancement ?

Thanks in advance

**Comment by nWidart** [comment]
Hm multiple issues with this. There is no need to loop over modules and creating them in DB, as they will be created when they're generated. Something like this could be considered with a console command to move over existing modules to the DB.

I also wouldn't make the interface configurable, when if someone customises it with new methods ? All implementations would break.

There's a lot to take into account for this feature, with a little bit of patience, I'll get to it. 😄

**Comment by poppabear8883** [comment]
Interesting idea on the console command ... 

And as for the interface being configurable, sorry not sure where the confusion is with this, i don't see where i mentioned this ?

**Comment by nWidart** [comment]
I'll close this so we don't have a duplicate with #171
