### ISSUE TITLE
Target class [cache] does not exist. 

### ISSUE THREAD

**Issue by mstfkhazaal** [nWidart/laravel-modules#1916]
I cannot Access to Module Facad in AppServiceProvider

```
   /**
     * Register any application services.
     */
    public function register(): void
    {

        if (Module::isEnabled('CMS')) {
            $this->app->register(CMSPanelProvider::class);
        }

    }
```

I get this error

`Target class [cache] does not exist. `

**Comment by dcblogdev** [comment]
I've been unable to replicate this, I have done a new release try updated and posting back if you still have the problem.
