### ISSUE TITLE
Module Provider Not Found

### ISSUE THREAD

**Issue by nthnyvllflrs** [nWidart/laravel-modules#1917]
Can someone help me with my current issue? It seems like the module provider is not found or located.
![image](https://github.com/user-attachments/assets/1ca33869-1805-4fc2-b9e3-0389a1f9b4ec)

**Comment by alissn** [comment]
Hi,

Does this issue occur after creating a new module?  
Try running `composer dump-autoload`; it might solve the problem.

If the issue persists, feel free to share more details so I can assist further.
