### ISSUE TITLE
Setting or Install Module on Production Env.

### ISSUE THREAD

**Issue by LeonardoBAV** [nWidart/laravel-modules#192]
Hello,

So I just finished my first module! I never create a packet too. I upload my module to git and then submit to Packagist. But when I install I fresh Laravel I would like to know, how can I make the module Works?

1- Is needed the laravel-modules packet to be installed, or this packet is just to developing module?
2- The path of many files (Like namespace) of module is  on the Modules/name-module, but now my module is in Vendor folder. I need to publish all the files of the Module into the Module folder? how can I make do this? cp comando Linux? 

Thnks People!

**Comment by LeonardoBAV** [comment]
Ok, I try to following, setting this packet in my module "joshbrw/laravel-module-installer", on my composer.json module file!

But I woud like to know what to do, after to required on composer my module on fresh laravel installed, what I need to do.

**Comment by LeonardoBAV** [comment]
I am gotting this error when install my packet

"Ensure your package's name is in the format <vendor>/<name>-<module>"

I know that this error come from  joshbrw/laravel-module-installer packet, but I dont know what to do!

Name Module: Base
Name Packet: leonardo-bav/base (composer.json)

I need to change the name Module?

**Comment by LeonardoBAV** [comment]
Why My packet name need to be in this format <vendor>/<name>-<module> ...

What name I need to put in composer.json once my name module is just "Base"

**Comment by nWidart** [comment]
You should post this issue on Joshe's repository 👍

**Comment by joshbrw** [comment]
Please name your module {{base-module}}.
