### ISSUE TITLE
Double files generated when using artisan

### ISSUE THREAD

**Issue by KSVQ** [nWidart/laravel-modules#193]
I noticed something odd on one of my installs of laravel 5.4 with laravel modules. When I use artisan to create module models and controllers they end up being created both in module folder where they are expected and in default laravel app folder. 

Do you have an idea why this might be happening? Maybe I've set up something wrong somewhere?

I am running three projects. One is purely for testing and breaking things. One is a much cleaner version of testing and one is an actual project. Nothing goes into the project that wasn't put through the first two. Of course I noticed this on the actual project one,, lol,, >.<.

If you have suggestions or thoughts on this I'd appreciate a nudge in the right direction.

**Comment by nWidart** [comment]
This is odd as no tests are picking this up, I was also unable to reproduce this.

Maybe something on your triple setup that causes issues ?

**Comment by KSVQ** [comment]
I will get back to you on this when I have more info.
