### ISSUE TITLE
Error on Shared Hosting After Installing Laravel Module Package (Laravel 11 & laravel-module-installer)

### ISSUE THREAD

**Issue by HkaanUsta** [nWidart/laravel-modules#1933]
Hello everyone!
I'm using laravel 11 with laravel-modules and also as suggested package for publishing and installing module package ( joshbrw/laravel-module-installer ). I did my module as a package uploaded it to the packageist.org, downloaded and everthing worked well for local dev env. When I uploaded it to the shared hosting, It threw and an error I attached above. I couldn't find the solution. I'm open any feedback or question to explan my code. 
Thanks
![image](https://github.com/user-attachments/assets/2829fa04-752d-4f8c-a0d9-721a704863e7)
![image](https://github.com/user-attachments/assets/d3879ec9-2d24-42d2-b501-29e2fbd76f4d)
![image](https://github.com/user-attachments/assets/2b1d89d5-2245-4114-ad8e-3ee8d6b17fc3)

**Comment by alissn** [comment]
hi,

you should update package version to 11.

and need to make some change on your project. more info [here](https://laravelmodules.com/docs/v11/upgrade)

**Comment by HkaanUsta** [comment]
Hi,

I have updated the package version to 11.0 as instructed and made the necessary changes, but the issue still persists.

**Comment by alissn** [comment]
@HkaanUsta 

Hi,
please run `composer update` and share result.

also share section `autoload` on root composer.json of project. 
and composer.json of module User.

**Comment by dcblogdev** [comment]
if this is still an issue please let us see what your root `composer.json` contains.
