### ISSUE TITLE
How can i Vendor:publish in a module

### ISSUE THREAD

**Issue by redtusker** [nWidart/laravel-modules#1938]
unable to vendor publish config and assets and there is no command way to do so 

i.e want to run the following but its not working there is no commands for module to do so

php artisan vendor:publish --provider="Spatie\WebhookServer\WebhookServerServiceProvider"

**Comment by alissn** [comment]
Hi,

To publish configuration files, you can use the following command:
```sh
php artisan module:publish-config
```

To publish assets, use this command:
```sh
php artisan module:publish
```

Both commands support the `--all` option to publish for all modules. You can also specify multiple module names like this:
```sh
php artisan module:publish-config Base User Tag
```


for publish package config,vite-loader and stubs :
```sh
php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"
```

**Comment by redtusker** [comment]
Hi, thanks for replying 

I tried those commands but it didn't work the config and migrations are not published

![image](https://github.com/user-attachments/assets/6c1e0fc8-e6cf-48da-b399-be2e76e6aa09)

**Comment by alissn** [comment]
ensure you module contain this function on provider and call on `boot` method.

```php
    /**
     * Register config.
     */
    protected function registerConfig(): void
    {
        $this->publishes([module_path($this->moduleName, 'config/config.php') => config_path($this->moduleNameLower.'.php')], 'config');
        $this->mergeConfigFrom(module_path($this->moduleName, 'config/config.php'), $this->moduleNameLower);
    }
```

reference on module sutb:
https://github.com/nWidart/laravel-modules/blob/15dec6bed2826feba9012a59bf08f880ecc9ba7d/src/Commands/stubs/scaffold/provider.stub#L74-L81

**Comment by redtusker** [comment]
Yes the module contain this function on the provider

 ```
protected function registerConfig(): void
    {
        $this->publishes([module_path($this->moduleName, 'config/config.php') => config_path($this->moduleNameLower.'.php')], 'config');
        $this->mergeConfigFrom(module_path($this->moduleName, 'config/config.php'), $this->moduleNameLower);
    }
```

**Comment by redtusker** [comment]
but still its not working as expected and still unable to publish those files

**Comment by dcblogdev** [comment]
identified the problem, applied a fix, will be doing a release shortly.
