### ISSUE TITLE
Class "Modules\NetworkAdmins\Providers\NetworkAdminsServiceProvider" not found

### ISSUE THREAD

**Issue by islamV** [nWidart/laravel-modules#1948]
### Versions:
- laravel-modules Version: 11
- Laravel Version: 11
- PHP Version: 8.3

### Steps To Reproduce:

- …

**Comment by alissn** [comment]
Run `composer dump-autoload`.

**Comment by narenderrai23** [comment]
By default, the module classes are not loaded automatically. You can autoload your modules by adding merge-plugin to the extra section:

"extra": {
    "laravel": {
        "dont-discover": []
    },
    "merge-plugin": {
        "include": [
            "Modules/*/composer.json"
        ]
    }
}

add merge-plugin in composer.json
