### ISSUE TITLE
[How to] Share Backend views / Structure Backend

### ISSUE THREAD

**Issue by cewlbird** [nWidart/laravel-modules#195]
Hi,

first of all thank you for this great package!

I made some modules and encountered the problem how to share the default backend views like the sidebar or the top navigation which should be visible for all modules.

Do you have any idea whats the best way to achieve this with your package?

I thought about creating the backend by just putting the backend views (Master Layout etc.) in the global view folder of laravel and just use modules for creating the routes, the forms and other assets for some areas of the backend like the settings module etc.

Thank you in advance.

Best Regards,

CEWLBIRD

**Comment by nWidart** [comment]
Hello & thanks for the kind words! 😄 

That's all up to you. You can view how I do it in AsgardCMS for inspiration.

**Comment by zhiru** [comment]
Hey @cewlbird , maybe you wanna do like this 

![image](https://cloud.githubusercontent.com/assets/4226997/24707703/113034ce-19eb-11e7-9593-d84e50d0ebd6.png)

use @include('module-name::path-inside-view-folder.blade-file-name') 

this is how i share my back views, i hope this help you 👍

**Comment by cewlbird** [comment]
Hey @nWidart, thank you, I totally forgot about it, as I was playing around with AsgardCMS a few days ago. I think I found today a good way for accomplishing the task, thanks!

Hey @zhiru, thats exactly how I am doing it right now. I made a backend module which holds all my backend related stuff like assets, views etc. and I load them the exact way like you.

I am just unsure about the assets and how to load them properly across all modules, but at the moment I am using the default mix setup (Laravel 5.4) with some customizations.

I basically load the module assets like JS or SCSS into different global files like app.scss and backend.scss. Same goes for the JS files. I also separated the vendor files and my custom ones.

So I just run npm run dev and compile a few different files, grouped by frontend and backend which means I just load one vendor-front.js as well as the app.css for the frontend. For my backend I just load the vendor-backend.js and the backend.css.

I hope thats a good way to handle the assets of all modules.
Seems like you are using an Asset package for handling assets?


Best Regards,

CEWLBIRD

**Comment by nWidart** [comment]
Sounds like a very good way of handling assets indeed, something the current backend lacks of a bit (not compiled/concat).
It's a custom made asset manager that is currently used yeah.

**Comment by nWidart** [comment]
I'll close the issue for now, but the discussion can continue of course. 😄

**Comment by zhiru** [comment]
@nWidart i'm continuing the discussion 😄
Hey @cewlbird, yes i'm using a "stolz/assets", with gulp (made my on), every change I make, I publish in public, so it's being easy for use.
@cewlbird  a couple of images:
![image](https://cloud.githubusercontent.com/assets/4226997/24799039/916998da-1b6f-11e7-9c66-fb4205d1dca9.png)
![image](https://cloud.githubusercontent.com/assets/4226997/24799051/9e29493a-1b6f-11e7-97a2-fbdd97b4d48b.png)
![image](https://cloud.githubusercontent.com/assets/4226997/24799058/a2c5f6d2-1b6f-11e7-94f5-feffd29bd2b7.png)
![image](https://cloud.githubusercontent.com/assets/4226997/24799073/b4a0995c-1b6f-11e7-9458-a33c0335075a.png)

With that becomes very easy for me, hahah, hope you enjoy it

**Comment by cewlbird** [comment]
Hi @zhiru, thank you for sharing this!
Seems great to me, I'm gonna have a look at this Stolz package, this could be interesting.

Best Regards,

CEWLBIRD
