### ISSUE TITLE
Disabled modules still register the ServiceProvider

### ISSUE THREAD

**Issue by locnguyen1842** [nWidart/laravel-modules#1950]
### Versions:
- laravel-modules Version: 11.1.1
- Laravel Version: 11.23
- PHP Version: 8.3

### Description:
- The module service provider still load( register ) even it was disabled

### Steps To Reproduce:

- …

**Comment by locnguyen1842** [comment]
hi @alissn , yes i'm using the command `php artisan module:disable`  but it is not working

**Comment by alissn** [comment]
Hi @locnguyen1842,

Although there are events for creating, deleting, disabling, and enabling modules to clear the `bootstrap/cache/module.php` file, it seems that these events aren't functioning as expected.

i create new pull request to revet register of the providers to previous version. #1952
