### ISSUE TITLE
ServiceProvider only loads after running module:enable

### ISSUE THREAD

**Issue by turbo124** [nWidart/laravel-modules#1958]
### Versions:
- laravel-modules Version: ^11
- Laravel Version: ^11
- PHP Version: 8.2.22

### Description:
Despite the module displaying "Enabled" the Modules service providers are not loaded on a fresh installation

```
  Status / Name ........................................................................................ Path / priority  
  [Enabled] Admin .................................................................................... Modules/Admin [0] 
```

modules_statuses.json has the module name with value true

yet the module will only be enabled if we explicitly run

```
php artisan module:enable
```

Any clues as to where to start debugging this please?

**Comment by dcblogdev** [comment]
If you've manually edited `modules_statuses.json` run `php artisan module:clear-compiled` this will update the cache.

If this is still an issue, let me know the steps to replicate.

**Comment by turbo124** [comment]
@dcblogdev thanks that has resolved this particular issue.
