### ISSUE TITLE
Change file routes.php to another folder

### ISSUE THREAD

**Issue by marcelogarbin** [nWidart/laravel-modules#196]
Hi, 
I've just started testing the functionality of laravel-modules.
I have a question about renaming folders.
I would like to move the "Http/routes.php" file to "Routes/routes.php"

What I did, in the file:
- config/modules.php: I renamed the array: stubs = ['routes' => 'Routes / routes.php'];
- I created in the array generator = ['routes' => 'Routes'];

So far so good, but the content of the "start.php" file always creates stub: require __DIR__. '/Http/routes.php'; Being that it would have to be require __DIR__. '/Routes/routes.php';

Would you add something in the modules.php file to configure that part? (To get the routes.php file in another folder, in the case "/Routes/routes.php")

Thank's

**Comment by nWidart** [comment]
Hello,

That seems to be hardcoded in the generated start.php stub file.
You can still move the routes file where you want, you'll just have to remove that line from the start.php file.

In asgardcms the wholo module generation is wrapped around by asgard itself to be able to automate things like this.

**Comment by marcelogarbin** [comment]
In this case will I always have to edit the start.php file in each module? 

Or could you edit the start.stub file for when a new module is already created with the default path?

Another question:
Can I edit files with .stub extension without compromising the package and these issues if there is an update?

**Comment by nWidart** [comment]
You can as I'm also doing in asgardcms, make a wrapper around the generate command to do a bunch of stuff, after module generation.

It's not a good idea to edit the stub files in the vendor folder. However, you can see in this [config file](https://github.com/nWidart/laravel-modules/blob/master/config/config.php#L27) that you can set where the stubs are, meaning you can copy all the stubs and put them in a custom folder, and edit them there.

**Comment by marcelogarbin** [comment]
Sorry, I had not thought of that. It's a good idea what you wrote.

I'll test this to see how it behaves, I'll pre-define stub's, I have a system to do, so I'm thinking of creating a default preconfigured framework for laravel so all other projects look the same.

I'm still relatively new to Laravel (previously I used CodeIgniter), I'll check your code on the asgardcms to get a better base.

Thank's bro
