### ISSUE TITLE
Breaks if no lang directory exists

### ISSUE THREAD

**Issue by rrmesquita** [nWidart/laravel-modules#1960]
### Versions:
- laravel-modules Version: 11.1.4
- Laravel Version: 11.27.2
- PHP Version: 8.2.22

### Description:

Recently during dependencies update, I noticed several tests in my project started failing.

Digging deeper into which package was causing those failures, I found out that [this change](https://github.com/nWidart/laravel-modules/pull/1946) was the one responsible. I confirmed that by creating `lang/.gitkeep` in all modules, and the errors were gone.

I don't think creating such directory should be mandatory, because I don't use the module generator and I like keeping the project lean.

### Steps To Reproduce:

- Sorry, I can't think of any. I haven't tested if the app breaks or if it's just the tests.

**Comment by dcblogdev** [comment]
I can't seem to replicate this, the lang folder is not required, its also not something I tend to use either.

Hard to debug since its working on my installs with no lang directories in my modules.
