### ISSUE TITLE
service provider not found when init the module 

### ISSUE THREAD

**Issue by abdulkareemh** [nWidart/laravel-modules#1961]
the location of the file is in app/providers that make the system does not see it 
it should be a outside the app directory

**Comment by fsepdiansyah** [comment]
struggled for this for a while too, hope this will help.

in config.module change `'app_folder' => 'app/'` to `'app_folder' => ''` will fix the issue.
and i still dont know what happen. lol.

**Comment by Jangbe** [comment]
add this line in main folder composer.json
```json
    "extra": {
        "laravel": {
            "dont-discover": []
        },
        "merge-plugin": {
            "include": [
                "Modules/*/composer.json"
            ]
        }
    },
```
and then type in terminal 

```bash
composer dump-autoload
```
