### ISSUE TITLE
loading routes based on priority

### ISSUE THREAD

**Issue by teksite** [nWidart/laravel-modules#1971]
### Versions:
- laravel-modules Version: 11.4
- Laravel Version: 11.4
- PHP Version: 8.3

### Description:
**the order of loading routes (in web.php) is not based on priority in module.json .**
i have three module Blog, Page, Software
if i have a same route in the modules, first i see response fron Blog then Page and in the last Software
whereas priorities are=>Page: 0, Software: 1, blog :3

### Steps To Reproduce:

i've changed priority but it still loads routes based on their name

**Comment by dcblogdev** [comment]
when you change the priority ensure you run `php artisan module:clear-compiled` this will update the cached manifest file in app/bootstrap/cache/modules.php
