### ISSUE TITLE
Factories

### ISSUE THREAD

**Issue by ImLiam** [nWidart/laravel-modules#198]
Along with managing database-related objects such as migrations and seeders in an individual module, it would be very beneficial to be able to define the factories that the seeders can use inside its own directory, and for this to be configured in the default stub.

It's possible to register a new factory directory from a service provider like so:

```
$this->app->singleton(Factory::class, function () {
    return Factory::construct('path/to/database/factories/directory');
});
```

**Comment by nWidart** [comment]
Hello,

Sorry for the late reply. Looks more like a statement, didn't directly know what to reply 😄 

Interesting setup for factories inside modules, this is probably something that could be added in the documentation as this question has come up before a few times. 👍

**Comment by ImLiam** [comment]
Ah I can see the confusion - sorry about that. This was more of a suggestion to implement it into the default service provider so that factories will be easily and readily available to use. I think it makes sense to implement it as a standard feature since it continues allowing the normal Laravel workflow as soon as you create a new module, and goes alongside the already implemented seeding.

**Comment by nWidart** [comment]
You're right, it's a good idea to have this provided by default. Feel free to send in a pull request with the required changes. 👍

**Comment by nWidart** [comment]
This has been added on dev-master, and documented.

- http://nwidart-docs.app/laravel-modules/v1/advanced-tools/module-resources#factories
- https://github.com/nWidart/laravel-modules/commit/4b34b57b9dbfe4231cc02acc9faa1ae0776951a9

**Comment by nWidart** [comment]
This was tagged.

**Comment by nWidart** [comment]
Your solution doesn't seem valid after all, as that will overwrite the existing database factory path and not append to it.
