### ISSUE TITLE
ModelShowCommand's parent class was changed in Laravel 11.33.0

### ISSUE THREAD

**Issue by cosmastech** [nWidart/laravel-modules#1989]
### Versions:
- laravel-modules Version: #.#.#
- Laravel Version: 11.33.0
- PHP Version: #.#.#

### Description:
I introduced a change [in this patch](https://github.com/laravel/framework/pull/53541) that I believe will break functionality for the ModelShowCommand, as it no longer has a `qualifyModel()` method.

I believe to fix this, we'll want to override the `handle()` method on the extended class and have it call qualifyModel, then pass that to `ModelInspector`, and finally pass the result to `display()`.

I'm happy to work on this, though I'm not sure how soon I'll have time to work on it.

### Steps To Reproduce:

- …

**Comment by alissn** [comment]
Hi, @cosmastech 

Thank you for reporting this! The issue has been fixed in pull request #1990.
