### ISSUE TITLE
Issue with @vite(\Nwidart\Modules\Module::getAssets()) and npm run dev

### ISSUE THREAD

**Issue by artytechy** [nWidart/laravel-modules#1993]
Hi there,

I’m encountering an issue with `@vite(\Nwidart\Modules\Module::getAssets())`. When I run `npm run dev`, it returns an empty array and doesn’t discover any assets. However, after running `npm run build`, everything is included, which leads to conflicts between some assets from the main project and the module.

As a temporary solution, I’m using:
`@vite(['Modules/Blog/resources/assets/sass/app.scss', 'Modules/Blog/resources/assets/js/app.js'])`
This works fine, but I’d prefer to resolve the issue properly.

I’ve read the documentation and followed the steps carefully, but it still isn’t working as expected.

Could anyone advise on how to fix this issue?

Thanks in advance!

**Comment by artytechy** [comment]
Alright, I see that this is a custom package that was previously created by someone. It is truly amazing, and I hope someone will look after it in case something unforeseen happens.

**Comment by dcblogdev** [comment]
That's the package?

**Comment by artytechy** [comment]
In Laravel, building a module system or a package isn't actually difficult. For example, let's say I have a module called "Blog," and I want its CSS and JS files to be automatically discovered. It’s relatively straightforward to implement this. One approach I used is to extract the URL and find the module name using regular expressions to match the URL with some of my modules. While this worked for me, there’s likely a better and more efficient solution available.
