### ISSUE TITLE
Class "Modules\ModuleName\Providers\ModuleNameServiceProvider" not found

### ISSUE THREAD

**Issue by dipaksarkar** [nWidart/laravel-modules#1997]
### Versions:
- laravel-modules Version: 11.1
- Laravel Version: 11.0
- PHP Version: 8.3

### Description:

Class "Modules\ModuleName\Providers\ModuleNameServiceProvider" not found

I'm creating some module as add-on and want to exclude from release branch. But, I'm getting error when delete the module folder from /modules directory.

### Steps To Reproduce:

1. php artisan module:make ModuleName --api  
2. delete folder modules/ModuleName
3. delete vendor folder
4. composer install

**Comment by dcblogdev** [comment]
if you manually delete then you may need to run `php artisan  module:clear-compiled` to update `bootstrap/cache/modules.php`

if you can remove via running `php artisan module:delete name`
