### ISSUE TITLE
Call to a member function fireEvent() on null 

### ISSUE THREAD

**Issue by ali-amento** [nWidart/laravel-modules#1998]
### Versions:
- laravel-modules Version: 11.1.6
- Laravel Version: 11.9
- PHP Version: 8.3

### Description:

I'm encountering an issue when creating a plain module through the console. Although the module is created successfully, I still receive an error message in the console.

### Use Case:

I’m building a module uploader feature in my app that allows users to upload new modules via a zip file, which is then extracted and installed. The process involves creating a plain module, copying the zip contents into the module's directory, and running commands from within that module.
Problem:

When I try to create a blank module, I face the following issues:

1. If I don't include the -p argument, the console outputs nothing, causing the execution to halt.
2. After the module is created and the installation is complete, I get an error stating that the ModuleServiceProvider is not found.

I would appreciate any assistance or guidance in resolving this issue.

### Steps To Reproduce:

- php artisan module:make Blog -p

**Comment by alissn** [comment]
Hi @ali-amento,

It will be fixed after merging my PR and releasing a new version.

**Comment by dcblogdev** [comment]
A new release has been issues, do a `composer update` and you should be good.
