### ISSUE TITLE
can you add Kebab case in generator file

### ISSUE THREAD

**Issue by satis-apex** [nWidart/laravel-modules#2001]
### Summary

for web route it would be better if kebab name is auto generated instead of lower case

i want this
```Route::resource('$KEBEB_NAME$', $STUDLY_NAME$Controller::class)->names('$KEBEB_NAME$');```
 in stub file for route 
old code
```Route::resource('$LOWER_NAME$', $STUDLY_NAME$Controller::class)->names('$LOWER_NAME$');```

**Comment by dcblogdev** [comment]
hmm I don't think we have kabab replacement anywhere, I'll look at this.

**Comment by dcblogdev** [comment]
I've added a new release which adds this support. https://github.com/nWidart/laravel-modules/pull/2002
