### ISSUE TITLE
Impossible to publish configs due hardcoded value

### ISSUE THREAD

**Issue by webmake** [nWidart/laravel-modules#202]
Hi, there is no possibility to publish configs, when having custom namespaced service provider, due hardcoded `Modules` word:
```
    private function getServiceProviderForModule($module)
    {
        $studlyName = studly_case($module);

        return "Modules\\$studlyName\\Providers\\{$studlyName}ServiceProvider";
    }
```
Our case, when we have under company namespace.
seems config has no effect:
```
    /*
    |--------------------------------------------------------------------------
    | Module Namespace
    |--------------------------------------------------------------------------
    |
    | Default module namespace.
    |
    */

    'namespace' => 'Company',
```

for example:
`module:publish-config`
generates following command:
`vendor:publish --provider="Modules\\Test\\Providers\\TestServiceProvider"`

**Comment by nWidart** [comment]
Good catch, it should indeed use that namespace config value. Will fix when possible.

**Comment by webmake** [comment]
Also notable, there is trick with vendors, we also use vendor scan, so namespace can differ, I'm not sure how to bypass this using this module.. 
```
    'scan' => [
        'enabled' => true,
        'paths' => [
            base_path('vendor/OtherCompany/*/src'),
        ],
    ],
```

**Comment by nWidart** [comment]
This is now fixed on master branch, tagging as soon as Travis is green.

For your second issue however it is currently not supported to have multiple namespaces for different modules.

**Comment by webmake** [comment]
Thanks.

Yeah, for multiple namespaces solution would a little bit harder. Seems enough to add into `Module` class namespace, that
```
        foreach ($this->laravel['modules']->enabled() as $module) {
            $this->publishConfiguration($module->getNamespace());
        }
```
would take it, but 
```
        if ($module = $this->argument('module')) {
            $this->publishConfiguration($module);

            return;
        }
```
 would need to load module again somehow and reparse..

**Comment by nWidart** [comment]
I'll close this now as the main issue was resolved.

The other issue seems more like an edge case, as modules should be in the same namespace ideally. 
However, if you have a working setup of it working, feel free to send a pull request for me to look at.  👍
