### ISSUE TITLE
L5.4 default Auth middleware dosen't work

### ISSUE THREAD

**Issue by elephantux** [nWidart/laravel-modules#204]
File: /Modules/News/Http/routes.php
```
Route::group([
    'namespace' => 'Modules\News\Http\Controllers\Admin',
    'prefix' => 'admin',
    'as' => 'admin.',
    'middleware' => ['auth', 'force_locale']
], function () {

    Route::get('/news', ['as' => 'news.index', function () {
        dd(123);
    }]);

});
```
In main route if I check Auth::check() (user logged in) it return true, in module/routes it always false. Where  is the my mistake?

**Comment by elephantux** [comment]
My custom 'force_locale' middleware (in app/http/middlewre/..) work fine.

**Comment by nWidart** [comment]
Possibly the session / middleware haven't ran yet when the route file is loaded.

**Comment by elephantux** [comment]
Middleware ran but `Auth::check()` always false!

**Comment by nWidart** [comment]
If it's true in your controller it's something to do with your setup.

**Comment by elephantux** [comment]
@nWidart it's true in `/app/Http/Controllers` but false in `/Modules/Http/Controllers`. All other functionality of Module package work fine.

**Comment by elephantux** [comment]
```php
# routes/web.php
...
Route::get('/', function () {
    dd(Auth::check()); # return true
    return view('home');
});
...

```php
# Modules/News/Http/routes.php
...
Route::get('/news', ['as' => 'news.index', function () {
    dd(Auth::check()); # return false
}]);
...
```

Module News was enabled

**Comment by elephantux** [comment]
Maybe someone can check this in issue in self code?

**Comment by elephantux** [comment]
In `Modules/News/Http/Controllers/NewsController.php` `Auth::check();` return true.
Can't understand why 'auth' middleware return false

**Comment by elephantux** [comment]
In this way middleware 'auth' work:
```php
Route::group(['middleware' => 'web', 'prefix' => 'news', 'namespace' => 'Modules\News\Http\Controllers'], function()
{
    Route::get('/', 'NewsController@index')->name('admin.news.index')->middleware('auth');
});
```

In this dosen't:
```php
Route::group(['middleware' => 'auth', 'prefix' => 'news', 'namespace' => 'Modules\News\Http\Controllers'], function()
{
    Route::get('/', 'NewsController@index')->name('admin.news.index');
});
```

**Comment by elephantux** [comment]
Finally I found the problem. In documentation:
> Out of the box, the web middleware group is automatically applied to your  routes/web.php file by the RouteServiceProvider.

In web middleware start sessions and if I add 'web' moddleware to my module routes group all work fine:
```php
# Modules/News/Http/routes.php
Route::group(['middleware' => ['web','auth'], 'prefix' => 'news', 'namespace' => 'Modules\News\Http\Controllers'], function()
{
    Route::get('/', 'NewsController@index')->name('admin.news.index');
});
```

**Comment by istylesidev** [comment]
@elephantux  i just wanna thank you veeery mush. this problem make me headache for 2 day. and it finally solved now T^T /

**Comment by asifzcpe** [comment]
in middleware please add web middleware too
it works for me
```
Route::group(['namespace'=>'App\Modules\Order\Controllers','middleware'=>['web','auth']],function(){
    Route::resource('orders','OrderController');
});
```
