### ISSUE TITLE
Custom module loading on same url depending on user login

### ISSUE THREAD

**Issue by AzazealDoe** [nWidart/laravel-modules#207]
How can I load a module depending on a user column like "town"? 

For example, I have authenticated users and multiple similar modules. The users have a database param.  called "town":

- if town is **empty** and user requests "**real-estate/**", the called module is "**Modules/Realestate**"
- if town is "**Chelsea**" and user requests "**real-estate/**", the called module is "**Modules/RealestateChelsea**"
- if town is "**London**" and user requests "**real-estate/**", the called module is "**Modules/RealestateLondon**"

Thanks!

**Comment by nWidart** [comment]
This is now possible as all modules are loaded by default.

In the future however, when the module status is stored in database, this might be a possible use case for it.

**Comment by AzazealDoe** [comment]
I want something like this:

`$town = Auth::user()->town;`
`if ($town == 'Chelsea' && Module::has('Realestate'.$town))`
`{`
`//load module`
`} `

Can you give me a example? Thank you.

**Comment by nWidart** [comment]
I can't. In my previous message, you can see I explained how this isn't possible.

Up to you, however, to wrap logic around the modules to make it work for your project.
