### ISSUE TITLE
How can I vendor:publish in a module

### ISSUE THREAD

**Issue by majidalaviadeh** [nWidart/laravel-modules#208]
I'm trying to create a module with some dependencies, I found this solution for composer :
https://github.com/pingpong-labs/modules/issues/193

Now, some of packages need command like `php artisan vendor:publish --tag=blahblah` , 

How can I run this command for a modules?

**Comment by nWidart** [comment]
Use the same command ? Use the --help flag if you're not sure how.

**Comment by majidalaviadeh** [comment]
for example when I using `php artisan vendor:publish --tag=laratrust` the configuration files will create in `/config`, is there any way to create on `/Modules/{module}/Config` ?

I want design an isolated module, so I need to add packages to `Modules/composer.json` and then configure they on `Modules/Config` folder.

**Comment by nWidart** [comment]
Modules can have dependencies, and configuration. Dependencies config file don't go into modules config folder. 
Published configuration files should always end up in the laravel config folder.
