### ISSUE TITLE
Facades not working

### ISSUE THREAD

**Issue by comdexxsolutionsllc** [nWidart/laravel-modules#209]
I have a facade in Modules\Api\Facade called Api.  It's loading an Entity in Modules\Api\Entities\ApiHelper.  I've loaded the alias in modules.conf like so:

    "aliases": {
        "API": "Modules\\Api\\Facades\\ApiHelper"
    },

and composer dump afterwards and it's still not working.

bound to a service provider called ApiServiceProvider and 

    public function register()
    {
        $this->app->bind('API', function() {
            return new Modules\Api\Entities\ApiHelper;
        });
    }

and is in the module.conf as
    "providers": [
        "Modules\\Api\\Providers\\ApiServiceProvider",
        "Modules\\Api\\Providers\\DcasApiServiceProvider"
    ],

Getting "Class ApiHelper does not exist"

**Comment by nWidart** [comment]
Hello,

Are you sure your facade is setup correctly according to the laravel documentation ?

The second error, also seems to be an issue with the setup. Make sure that class exists, and has the correct namespace etc.
