### ISSUE TITLE
How to initialise my module middleware inside kernel.php file

### ISSUE THREAD

**Issue by vijaykoogu-axatech** [nWidart/laravel-modules#21]
Kernel file
~~~~~~~~~
 protected $routeMiddleware = [
 'superadmin' => \Modules\Superadmin\Middleware\Superadmin::class,
];
~~~~~~~~~

Module Route

~~~~~~~~~~~~
Route::group(['middleware' => ['web', 'superadmin'], 'prefix' => 'superadmin', 'namespace' => 'Modules\Superadmin\Http\Controllers'], function()
{
	Route::get('/', 'SuperadminController@index');
});
~~~~~~~~~~

**Comment by nWidart** [comment]
You can use the usual laravel way of registering your middleware.

In your service provider you have access to the `Router` class, which has a `middleware` option.

Example: https://github.com/AsgardCms/Core/blob/master/Providers/CoreServiceProvider.php#L101

**Comment by vijaykoogu-axatech** [comment]
Thanks thats works actually i missed \HTTP\middleware now it's working fine.
