### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ecodrutz** [nWidart/laravel-modules#211]
Hello,
Will there be support for the json translation files Laravel 5.4 supports now? I have just tried to create in my module an en.json file and is not loaded.
Thanks.

**Comment by nWidart** [comment]
I don't know how laravel handles json translations. From my understanding, it was supposed to work as is, without any changes on our end.

Feel free to send a pull request with the required changes as well as an explanation as to why/what it's doing.

**Comment by irvine48** [comment]
Hi @nWidart ,

I facing this issue, according to basic laravel translation 
```
@lang("modulename::filename.samplekey")

en.php "sample" => "Sample"
cn.php "sample" => "manple"
```

another method will be
```
@lang("Sample")

cn.json "Sample" : "manple"
```

second method which is using default English name as KEY for others translation files. State in [Documentation](https://laravel.com/docs/5.4/localization#defining-translation-strings)

I tried with @lang("modulename::Sample") and create a new cn.json file on module lang folder in that module and not working. I think there is a miss out on that section.
