### ISSUE TITLE
Include module view in an existing view without hardcoding

### ISSUE THREAD

**Issue by hypemedia** [nWidart/laravel-modules#212]
I have created an module for a slider. The backend works well as I have a specific route for adding the slider but the problem is when I want to show the slider on the front. There is an existing homepage controller and view and inside that home view I want to include the view for the slider from my module but I want to do this without hardcoding anything related to module slider controller in the home controller. Is this possible?

**Comment by nWidart** [comment]
This is related to this package.

However, I think you might want to look up view composers. It would allow you to bind data to the view(s) you want, that hold that view name you want. With this you can use that variable in the view, without having the view name hardcoded.
