### ISSUE TITLE
route not load with "arcanedev/localization" package 

### ISSUE THREAD

**Issue by yemenifree** [nWidart/laravel-modules#213]
hi,

when I use `arcanedev/localization` with modules the route URL doesn't register also not show in `route:list`, `arcanedev/localization` override binding default router class of laravel to `Arcanedev\Localization\Routing\Router`

I tried to add service provider of modules before/after service provider of package but not work

**Comment by nWidart** [comment]
Hello,

I'm not familiar with that package. Did you load it as usual ? If it's not showing up seems like its service provider isn't loaded.

**Comment by yemenifree** [comment]
package work fine with all route they registered in main route file of laravel "web.php",
i tried disabled override binding router from the package is work fine

I'll focus to check router class of package to know where is the problem

**Comment by nWidart** [comment]
If the routes work in the web.php file, I'm guessing your module route file isn't loaded. Did you try to add a `dd();` on your module route file to make sure it's loaded ?

**Comment by yemenifree** [comment]
is already loaded but I guess they loaded & registered with default `Router` class of laravel instead of override `Router` by package

**Comment by nWidart** [comment]
ah ok. Can't really help you with this package, I'm guessing you need to use their Router class then.

**Comment by yemenifree** [comment]
I found problem and send [PR](https://github.com/ARCANEDEV/Localization/pull/108) to solve problem in original package for any one have same problem

Thanks

**Comment by nWidart** [comment]
Cool, thanks for the heads-up.
