### ISSUE TITLE
Access for multiple config files.

### ISSUE THREAD

**Issue by montyclt** [nWidart/laravel-modules#215]
Hi!

In my module, I've many files in config folder:

`
Modules/
--Config/
----config.php
----secret.php
`

Using `Config::get('modulename.key')` I can retrieve info for `config.php`.

How can I retrieve key-value data of others files in config folder of my module?

**Comment by nWidart** [comment]
Hello,

You need to use is as in laravel, ie: `module.file.keys`. So for your example:

```
config('modulename.secret.key-in-secret-file');
```

**Comment by montyclt** [comment]
Hello, sorry for not responding, I did not realize your answer.

I have not tried it since I've come up with another solution for my particular problem, but thanks for the reply.

**Comment by teddywest32** [comment]
@nWidart Is there any way to get the `config`  from `Modules\ModuleName\Config\config.php` without publishing the config? We could use `Config::get()` for `vendor ` packages for the same scenario but is there any other method to get the config running from `Modules`?

**Comment by nWidart** [comment]
You don't need to publish configuration to access it.
You just need to let laravel know where to get it, that's explained on the laravel docs.

**Comment by teddywest32** [comment]
@nWidart I didn't got in the first place but this answer explained more. 

`https://stackoverflow.com/a/28497233/3887342`

Thanks ;)

**Comment by ismatBabirli** [comment]
HI. I Have the same problem. Who is fixed this?

**Comment by srakl** [comment]
how do i read config in modules?

**Comment by dcblogdev** [comment]
you call the `config` helper and pass in the path like blog.name for a blog module:

```
config('blog.name')
```

Which would read a name property from a blog module.

**Comment by srakl** [comment]
my config is in modules/blog/config. how do i read `version`?

I tried `config('blog.version')` but nothing shows

```
return [
    'name' => 'Blog',
    'version' => '1' 
];
```

**Comment by NaumovAndrew** [comment]
@srakl try config('blog.config.blogVersion')
