### ISSUE TITLE
module:migrate test is lackluster

### ISSUE THREAD

**Issue by gmox** [nWidart/laravel-modules#216]
https://github.com/nWidart/laravel-modules/blob/master/tests/Commands/MigrateCommandTest.php

This appears to be pretty old. I don't have time to do a PR for it at the moment, but if anyone wants to tackle that before I get a chance to, have at it.

**Comment by nWidart** [comment]
Hello,

Indeed, that test is even de-activated (abstract) because I couldn't get it to work. Testing the migration class is the big thing missing for a higher coverage, so if you know how, it would be very welcome. 😄
