### ISSUE TITLE
Command "module" is not defined.

### ISSUE THREAD

**Issue by Vostro11** [nWidart/laravel-modules#217]
i followed your installation guide properly but when i run 
`php artisan module`
error says "Command 'module' is not defined."
It didn't happened before.

my configuration is

"require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "nwidart/laravel-modules": "^1.20"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/",
            "Modules\\": "Modules/"
        }
    },

**Comment by nWidart** [comment]
Hello,

That's because there is no `module` command. Check the documentation or type `php artisan` to view all available commands.

**Comment by zahid-avyatech** [comment]
You need check if not exsitn this file in 'providers' => [
	Nwidart\Modules\LaravelModulesServiceProvider::class,
]

then add first

php artisan config:cache
php artisan module
