### ISSUE TITLE
Cann't use Auth::guard inside middleware

### ISSUE THREAD

**Issue by vijaykoogu-axatech** [nWidart/laravel-modules#22]
Sorry for asking so many Question... 

AdminMiddleware.php

Error:
***
ErrorException in Superadmin.php line 20:
Undefined variable: guard
***
~~~~~~
namespace Modules\Superadmin\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;


 if (Auth::guard($guard)->guest()) {
~~~~~~~~

**Comment by nWidart** [comment]
Please refer to the laravel documentation.

All your issues are not related to this package.

The error here very clear, the variable isn't available.
