### ISSUE TITLE
bug in laravel 5.4.23

### ISSUE THREAD

**Issue by vahidalvandi** [nWidart/laravel-modules#222]
hi in laravel 5.4.23 after add laravel-module 
return error bellow
FatalThrowableError in ProviderRepository.php line 208:
Class 'Nwidart\Modules\LaravelModulesServiceProvider' not found

**Comment by nWidart** [comment]
Hello,

I'm able to reproduce this issue. Did you run composer dump-autoload & artisan clear-compiled just in case ?

**Comment by vahidalvandi** [comment]
ok fixed

**Comment by nWidart** [comment]
Awesome. 👍
