### ISSUE TITLE
have error 

### ISSUE THREAD

**Issue by vahidalvandi** [nWidart/laravel-modules#223]
after install fresh laravel and install laravel-modules then copy modules folder in root it  return

FatalThrowableError in Application.php line 612:
Class 'Modules\Accounting\Providers\AccountingServiceProvider' not found

also i run composer dump-autoload

**Comment by Gkiokan** [comment]
Did you add PSR-4 autoload and dump composer afterwards?
Check your composer.json for correct writing. The documentation says Module but it have to be acctually Modules.

**Comment by nWidart** [comment]
This is indeed related to your autoloading.

I'll close this for now. Feel free to comment if you're still experiencing the issue.
