### ISSUE TITLE
How does routes works ?

### ISSUE THREAD

**Issue by arieltoledo** [nWidart/laravel-modules#224]
@nWidart Im using your package ands works great so far. But im having issues including some of the modules routes in my root app.  Some routes works as expected, i have created a modules call indicators.   There I have a created a controller called "tendencies". Im able to get to the index method "app.url/indicators/tendencies" fine. But When I try to store I get a **MethodNotAllowedHttpException** error message. ( im using request for validation by the way).

Thanks in advance.

**Comment by nWidart** [comment]
Hello,

That's a laravel exception meaning you're trying to post to a route defined a `GET` for instance, ie there's a mismatch in the route methods (get,post,put,delete,...).

Make sure the route definition is correct.

**Comment by arieltoledo** [comment]
Thats the thing, I dont know hot to include the module controller in the app routes or a resource ? 
  Route::resource('reports', 'Module::Controller') ? How should I do that ?

**Comment by nWidart** [comment]
Just like you would in a laravel app, by specifying the namespace. Your modules are namespaced, so for example if you have this controller : `Modules\Product\Http\Controllers\ProductController`, your route would use that:

`Route::resource('reports', 'Modules\Product\Http\Controllers\ProductController') `

**Comment by arieltoledo** [comment]
Great ! thanks a lot @nWidart. Working fine. About the route provider, I have to generate the route provider with the artisan command and nothing else ? Its, any config envolve ?

**Comment by nWidart** [comment]
Just generate it yes, and then you need to load it. This can happen in the module.json file, there's a `providers` key. Or you could just load it the usual way in config/app.php.

**Comment by arieltoledo** [comment]
Great thanks a lot ! I didnt find this info at the docs, could be very usefull. Ready to close this one.

**Comment by nWidart** [comment]
Good idea! I'll have to find a spot on the docs where to put this information, maybe a new page. 🤔
