### ISSUE TITLE
There are no commands defined in the "artisan module" namespace.

### ISSUE THREAD

**Issue by ridwanskaterock** [nWidart/laravel-modules#225]
i running artisan command on controller Artisan::call('artisan module:migrate');

why the system give response There are no commands defined in the "artisan module" namespace.

can you help me ?

**Comment by ridwanskaterock** [comment]
any way for make command on controller like this 

$moduleMigrate->fire(); ?

**Comment by nWidart** [comment]
That's because you just need to use `Artisan::call('module:mgirate')` if I'm not mistaken.

**Comment by ridwanskaterock** [comment]
lol my problem cause i define artisan call like this 

Artisan::call('artisan module:migrate');

thanks for it

**Comment by jayadevkv** [comment]
Migration for a specific module from controller is not working. 
For eg. Artisan::call('artisan module:migrate User');

It gives command does not exists error

**Comment by twf-nikhila** [comment]
@jayadevkv  yes it doesn't work.
@nWidart  any solution to this? Shows command not found. Please help with it.

**Comment by nWidart** [comment]
Not sure no. I have this working without issues.

Maybe take a look if the package is loaded by the time you call the command.

**Comment by twf-nikhila** [comment]
@nWidart Checked your asgard project, got it working now.

This works:
`Artisan::call('module:migrate', ['module' => "ModuleName"]);`

This doesn't work:
`Artisan::call('module:migrate ModuleName');`
