### ISSUE TITLE
error occur on php artisan config:cache

### ISSUE THREAD

**Issue by treetechsuman** [nWidart/laravel-modules#227]
when i create foldar Module/Module_name/Http/Helpers/MyHelper.php and include in module.json as
{
    "name": "Category",
    "alias": "category",
    "description": "",
    "keywords": [],
    "active": 1,
    "order": 0,
    "providers": [
        "Modules\\Category\\Providers\\CategoryServiceProvider"
    ],
    "aliases": {},
    "files": [
        "start.php",
         "Http/Helpers/MyHelper.php"
    ],
    "requires": []
}

then i got error when runnign php artisan config:cache

**Comment by treetechsuman** [comment]
$ php artisan config:cache
Configuration cache cleared!
PHP Fatal error:  Cannot redeclare getCategoryNameById() (previously declared in
 C:\xampp\htdocs\projects\Modules\Modules\Category\Http\Helpers\CategoryHelper.p
hp:3) in C:\xampp\htdocs\projects\Modules\Modules\Category\Http\Helpers\Category
Helper.php on line 6


  [Symfony\Component\Debug\Exception\FatalErrorException]
  Cannot redeclare getCategoryNameById() (previously declared in C:\xampp\htd
  ocs\projects\Modules\Modules\Category\Http\Helpers\CategoryHelper.php:3)




  [Symfony\Component\Debug\Exception\FatalErrorException]
  Cannot redeclare getCategoryNameById() (previously declared in C:\xampp\htd
  ocs\projects\Modules\Modules\Category\Http\Helpers\CategoryHelper.php:3)

**Comment by treetechsuman** [comment]
<?php

function getCategoryNameById($category_id){
	$category = DB::table('categories')->where('id',$category_id)->first();
	return $category['name'];
}

**Comment by treetechsuman** [comment]
<?php

function getCategoryNameById($category_id){
	$category = DB::table('categories')->where('id',$category_id)->first();
	return $category['name'];
}

**Comment by nWidart** [comment]
The error is pretty clear on what's going wrong. `Cannot redeclare getCategoryNameById()`.

**Comment by treetechsuman** [comment]
i done have redeclear this function

**Comment by treetechsuman** [comment]
i have only one function in my project wiht name 
getCategoryNameById()

**Comment by treetechsuman** [comment]
function getCategoryNameById($category_id){
	$category = DB::table('categories')->where('id',$category_id)->first();
	return $category['name'];
}

**Comment by nWidart** [comment]
look at the error, it shows you which file.

**Comment by treetechsuman** [comment]
i have seen file and that is fine, i have define function on Modules/Module_name/Http/Helpers/MyHelper.php it work fine but when i run php artisan config:cache then i got error

**Comment by nWidart** [comment]
I'll close this for now as it's related to your code.

Make sur your method isn't defined twice.

**Comment by treetechsuman** [comment]
i m sure method is not defined twice, i will be happy if you suggest to how and where to add help file,

**Comment by zotopteam** [comment]
i have this too,  define a funtion in the start.php and php artisan config:cache or php artisan route:cache, PHP Fatal error:  Cannot redeclare

then in the asgardcms , before define a function , it use  function_exists to deal it

**Comment by treetechsuman** [comment]
@zotopteam  if you found solution plz write it here

**Comment by seba316d** [comment]
@nWidart you still haven't fixed it ?

**Comment by dcblogdev** [comment]
You can solve this by checking for the existence of the function ie:

```php
if (! function_exists('demo')) {
    function demo()
    {
        //does something
    }
}
```

**Comment by seba316d** [comment]
I know but this is not resolve problem. Problem is some in core.

**Comment by leadstreet-roy** [comment]
> You can solve this by checking for the existence of the function ie:
> 
> ```
> if (! function_exists('demo')) {
>     function demo()
>     {
>         //does something
>     }
> }
> ```

this one solves my issue
