### ISSUE TITLE
modules.used not found

### ISSUE THREAD

**Issue by zeeshan-activemarketing** [nWidart/laravel-modules#228]
With following command:
php artisan module:make-listener Cms --event events

I am getting this error:
getting app/modules/modules.used not found error

**Comment by nWidart** [comment]
Hi,

That's because you either didn't use `module:use` before, and thus it can't find a default module, or you didn't pass in the module parameter name to the command.

use the --help flag to get a quick reminder of what arguments a command needs.

**Comment by zeeshan-activemarketing** [comment]
Thanks for help it worked, I missed
php artisan module:use
