### ISSUE TITLE
Multiple Files in Config Folder not getting published.

### ISSUE THREAD

**Issue by ronitd** [nWidart/laravel-modules#229]
php artisan module:publish-config, command only publishes config.php file of a module to root config.
And i am looking to publish all my configuration file in module config folder to root config, so that other modules can also have access to it.

**Comment by nWidart** [comment]
Hello,

You can do that if you register your files to publish with laravel. 
Example for the config files: https://laravel.com/docs/5.4/packages#configuration

**Comment by ronitd** [comment]
Thanks for the prompt reply and solution. :+1:
