### ISSUE TITLE
Using multiple modules within a single view

### ISSUE THREAD

**Issue by kbanse** [nWidart/laravel-modules#231]
I'm guessing it's not related to the package but I'm not 100% sure what I am looking for. 

I'll describe.

In module one called 'Task' a user can create tasks etc...
In module two called 'Board' a user has a board with multiple areas...

The board module is an "addon" and isn't part of the original application.

I would like to create a view that renders the Tasks on the left and the board on the right so a user can move tasks onto the board.

These are two separate modules but I would like to combine them into one view but I'm not sure how to given that each module has it's own view/controller.

Is this done with View Composers? or does the this package have a "correct" way to combine modules?

Thanks, any assistance or pointing me in the right direction is appreciated.

**Comment by nWidart** [comment]
Hi,

You're correct, I would use view composers for this use case. 
Add the view to the module that is considered the "main" one, on the view, and the other module can attach data to that view using view composers.

If none of the 2 modules really 'own' the view, you can have your view in the resources/views folder for example, and having both modules attach data to that view using composers.
