### ISSUE TITLE
Composer install (php artisan optimize) error

### ISSUE THREAD

**Issue by aaesis** [nWidart/laravel-modules#232]
Hi can I ask? why when I composer install > php artisan optimize I got an error like this?

It has no problem in my local, only live server.

![screen shot 2017-05-19 at 4 57 45 pm](https://cloud.githubusercontent.com/assets/802180/26240702/7e764794-3cb4-11e7-8bf1-b4fbc8222cf2.png)

**Comment by nWidart** [comment]
Hi,

The error says it can't find a routes file. So make sure that file exists. 👍

**Comment by aaesis** [comment]
this is now ok, ive use relative path. absolute path is not working.
