### ISSUE TITLE
performance issue (response time is 4s)

### ISSUE THREAD

**Issue by eafshary** [nWidart/laravel-modules#233]
I have about 40 modules and response time is 4 seconds !!!
I found bottleneck in Json->getAttributes when reading modules json files
How can I fix that? 

sorry for my eng

**Comment by nWidart** [comment]
Hello,

Did you try to enable the caching feature in your configuration file ?

**Comment by eafshary** [comment]
yes, but still response time is 4s
Is there any way to save all module.josn in a single file for production?

**Comment by nWidart** [comment]
That's not possible currently no. It won't fix the issue either since it'll still perform the same IO operations.
There haven't been any reported issues with a large amount of modules, on the contrary. So check if you're reading the module.json file yourself.

**Comment by eafshary** [comment]
I just create new laravel project and create about 40 modules with caching feature enabled.
I did not do extra work
you can test it.

**Comment by nWidart** [comment]
could you provide a blackfire (https://blackfire.io/) link to your app so I can see the bottleneck(s) ?

**Comment by Ifnot** [comment]
@eafshary I think your problem is not related with `laravel-modules`. I am running with a big app and 10 modules with a 100ms project loading.

Please can you give us your environment ? OS, web-server used ?
