### ISSUE TITLE
[Bug Report] Error when creating modules with --plain parameter

### ISSUE THREAD

**Issue by krizztianz** [nWidart/laravel-modules#234]
I tried to make some modules with default parameter
`php artisan module:make Time `

and it's working like a charm!

But when i tried to make new modules with **"--plain"** parameter, i always got an error.

Command:
`php artisan module:make User --plain`

Output:
`Module [User] created successfully.`

After that, everytime i tried to run:
`composer dump-autoload && php artisan clear-compiled`

I always got this error:
`[Symfony\Component\Debug\Exception\FatalThrowableError]`
`Class 'Modules\User\Providers\UserServiceProvider' not found`

**Comment by nWidart** [comment]
Hello,

I managed to reproduce the issue. When using the `--plain` flag, it doesn't generate anything, yet in the module.json it adds a `UserServiceProvider`, which doesn't exist, hence your error.

You can fix it on your end by removing that line until it's fixed here for all future generations.

Thanks for reporting the issue! 👍

**Comment by nWidart** [comment]
I just fixed the bug on `master` branch.

**Comment by krizztianz** [comment]
Thanks for the fast response.
So now i can directly update your packages via composer?

**Comment by nWidart** [comment]
Same as any compose package, by running composer update.

However since this isn't tagged yet, you'll have to use `dev-master` version constraint if you want it now.

**Comment by nWidart** [comment]
Release [1.22.0](https://github.com/nWidart/laravel-modules/releases/tag/1.22.0) was just released. You can now update without having to switch to dev-master.
