### ISSUE TITLE
Laravel Auth

### ISSUE THREAD

**Issue by marcelogarbin** [nWidart/laravel-modules#235]
Hi,

How do I use the "php artisan make:auth" command with laravel-modules?

Thanks

**Comment by nWidart** [comment]
Hello,

Same as before, by running it.
Up to you to move / do something with generated files to a module.

**Comment by marcelogarbin** [comment]
I made changes in the structure of the folders to get better organized the project.

How can I track what is going wrong?

I am returning the following error when trying the command "php artisan make:auth":

>   [RuntimeException]
>   Unable to detect application namespace.

my composer.json
```
"psr-4": {
    "App\\": "app/Core/",
    "Modules\\": "app/Modules/"
}
```

I also changed the namespace in the files (I changed "App\" by "App\Core\":

- All files that are within "App\Core\"

-  bootstrap\app.php

- config\app.php

Can you help me? Thanks

Attachments:
![screenshot_26 20170521 16 29 23](https://cloud.githubusercontent.com/assets/9335588/26286786/9531731a-3e43-11e7-8bd9-2d4dc394d590.png)

**Comment by nWidart** [comment]
I'm assuming laravel can't detect the namespace. Set the namespace back to its default so laravel can generate the needed files.

**Comment by marcelogarbin** [comment]
The idea would be to take all the code generated by make:auth and transfer it to a module created with laravel-modules?

Example: Create the users module and transfer the laravel auth files to it? that?

**Comment by nWidart** [comment]
That's up to you to decide how you want this in your application.

I'll close this up as it's not really an issue with this package. 😄

**Comment by RadhaGupta91** [comment]
I have used"nwidart/laravel-modules": "^8.2" to implement moduler approach.
but I am not able to access Auth:user() in models whereas I am able to access it in controller.
Can you provide me a solution?
