### ISSUE TITLE
There are no commands defined in the "module" namespace

### ISSUE THREAD

**Issue by dinajpuri** [nWidart/laravel-modules#236]
Hello,

When I'm trying to make a module [ php artisan module:make Blog ] in Laravel 5.4.23 I'm getting the following error-

`[Symfony\Component\Console\Exception\CommandNotFoundException]`
`There are no commands defined in the "module" namespace.`

**Comment by nWidart** [comment]
Hi,

That means you didn't register the service provider of this package in your `config/app.php` file.

**Comment by alhassansumon** [comment]
hello bro,
 php artisan module:make Blog not work  please select your command line:
->php artisan make:module Blog (then work)

**Comment by madhankd** [comment]
add the following in app.php under providers :

> 'providers' => [
             ........
>          Nwidart\Modules\LaravelModulesServiceProvider::class
> ]
