### ISSUE TITLE
add helper function module_path()?

### ISSUE THREAD

**Issue by KerrickChan** [nWidart/laravel-modules#237]
it's a suggestion function.
add helper function module_path()?
return the base path of module folder

**Comment by nWidart** [comment]
That could be helpful, PR welcome for that. Don't forget it needs to accept an argument, the module name.

**Comment by nWidart** [comment]
This has been added. 

https://github.com/nWidart/laravel-modules/commit/114b3344f3ff59ef9282f0318e3a8f9f22a5a76a
