### ISSUE TITLE
Not automatically scan /vendor directory?

### ISSUE THREAD

**Issue by krizztianz** [nWidart/laravel-modules#239]
Hey there, 
I tried to clone my module from a private repository.
I once added the module in the app/Modules directory, after that i pushed that module to my Bitbucket.

I added that repository to the composer.json and run `composer install`
And it's working like a charm, the module's cloned into the vendor directory.

But when i tried to run `composer dump-autoload` and `php artisan clear-compiled` it says the module's Service Provider not found.
What can i do?

**Comment by nWidart** [comment]
Did you enable the vendor directory scan in the config file ?

**Comment by krizztianz** [comment]
Yes i've enabled it in the config file bu changing the enabled to true

**Comment by nWidart** [comment]
You can debug it by going into your module and add `dd()` in the service provider for instance, and step by step seeing where your module is not registered.

**Comment by krizztianz** [comment]
Okey i'll try it.
I'll let you know if it's working

**Comment by krizztianz** [comment]
![screenshot from 2017-06-06 22-22-45](https://user-images.githubusercontent.com/17529726/26837141-dc2e5d26-4b06-11e7-9e02-a243cc20b229.png)
Hello bro...
Still the same, i cannot run `php artisan clear-compiled`

**Comment by nWidart** [comment]
No it can work with modules in the vendor folder, others have it setup like that, working.

**Comment by krizztianz** [comment]
That's weird...

Here i attach the log.
Hope you can help me reproduce this.

> [2017-06-06 16:00:10] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Modules\Beacon\Providers\BeaconServiceProvider' not found in /opt/lampp/htdocs/thermalbaas/system/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:612
Stack trace:
#0 /opt/lampp/htdocs/thermalbaas/system/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(570): Illuminate\Foundation\Application->resolveProvider('Modules\\Beacon\\...')
#1 /opt/lampp/htdocs/thermalbaas/system/vendor/nwidart/laravel-modules/src/Module.php(265): Illuminate\Foundation\Application->register('Modules\\Beacon\\...')
#2 /opt/lampp/htdocs/thermalbaas/system/vendor/nwidart/laravel-modules/src/Module.php(231): Nwidart\Modules\Module->registerProviders()
#3 /opt/lampp/htdocs/thermalbaas/system/vendor/nwidart/laravel-modules/src/Repository.php(296): Nwidart\Modules\Module->register()
#4 /opt/lampp/htdocs/thermalbaas/system/vendor/nwidart/laravel-modules/src/Providers/BootstrapServiceProvider.php(22): Nwidart\Modules\Repository->register()
#5 /opt/lampp/htdocs/thermalbaas/system/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Nwidart\Modules\Providers\BootstrapServiceProvider->register()
#6 /opt/lampp/htdocs/thermalbaas/system/vendor/nwidart/laravel-modules/src/LaravelModulesServiceProvider.php(35): Illuminate\Foundation\Application->register(Object(Nwidart\Modules\Providers\BootstrapServiceProvider))
#7 /opt/lampp/htdocs/thermalbaas/system/vendor/nwidart/laravel-modules/src/LaravelModulesServiceProvider.php(27): Nwidart\Modules\LaravelModulesServiceProvider->registerModules()
#8 [internal function]: Nwidart\Modules\LaravelModulesServiceProvider->boot()
#9 /opt/lampp/htdocs/thermalbaas/system/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#10 /opt/lampp/htdocs/thermalbaas/system/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#11 /opt/lampp/htdocs/thermalbaas/system/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#12 /opt/lampp/htdocs/thermalbaas/system/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#13 /opt/lampp/htdocs/thermalbaas/system/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(788): Illuminate\Container\Container->call(Array)
#14 /opt/lampp/htdocs/thermalbaas/system/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(771): Illuminate\Foundation\Application->bootProvider(Object(Nwidart\Modules\LaravelModulesServiceProvider))
#15 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Nwidart\Modules\LaravelModulesServiceProvider), 16)
#16 /opt/lampp/htdocs/thermalbaas/system/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(772): array_walk(Array, Object(Closure))
#17 /opt/lampp/htdocs/thermalbaas/system/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#18 /opt/lampp/htdocs/thermalbaas/system/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#19 /opt/lampp/htdocs/thermalbaas/system/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(267): Illuminate\Foundation\Application->bootstrapWith(Array)
#20 /opt/lampp/htdocs/thermalbaas/system/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(114): Illuminate\Foundation\Console\Kernel->bootstrap()
#21 /opt/lampp/htdocs/thermalbaas/system/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 {main}
