### ISSUE TITLE
Controller class and file name missmatch

### ISSUE THREAD

**Issue by unxp** [nWidart/laravel-modules#24]
After running command like this: `php artisan module:make-controller Users UserModule` class named `Users` will be created, but file will be named `UsersController.php`. It should be consistent with appending `Controller` to either both or none.

**Comment by nWidart** [comment]
Thank you for reporting the issue.

It was fixed in https://github.com/nWidart/laravel-modules/commit/3b1e4b24c6e53512a0e27d33756dcd6e602c8551

Will tag as soon as travis passes.

**Comment by nWidart** [comment]
And now tagged in [0.10](https://github.com/nWidart/laravel-modules/releases/tag/0.10)

**Comment by unxp** [comment]
Awesome, thanks for quick response :)
