### ISSUE TITLE
Views not updated after composer update

### ISSUE THREAD

**Issue by cent89** [nWidart/laravel-modules#242]
After the last composer updated, the views inside the modules are not updated, even if I clear the view cache. I have downgrade to version 1.19 but nothing happens. Can you help me?
Thanks!
EDIT: The view folder are moved to resources/view folder, outside Modules folder. Why? 

Roberto

**Comment by nWidart** [comment]
Hi.

Nothing changed on the package end concerning views.
Make sure your setup is correct, check the service provider if you want or not views to be published for instance.

**Comment by LeonardoBAV** [comment]
Hello I see that my views was published. But In any moment I had publish the view. And I cant understand, because the pack even havent a command line to publish the views. how it is possible?

**Comment by nWidart** [comment]
Read my response just above yours.
