### ISSUE TITLE
php artisan module:make-model Post Blog --migration

### ISSUE THREAD

**Issue by irvine48** [nWidart/laravel-modules#243]
Possible include this command?

Reference from Laravel:
```
php artisan make:model User --migration
php artisan make:model User -m
```
I used to this command to generate my model and migration file to avoid typo.

and for controller (inverse?):
```
php artisan make:controller UserController --resource
php artisan make:controller UserController -r
```
```
php artisan module:make-migration create_posts_table Blog --plain
php artisan module:make-migration create_posts_table Blog -p
```

Just my personal view and suggestion, thank for reading this.

**Comment by nWidart** [comment]
Hello and thanks for the suggestions.

I've just added the flag to generate the migration file with a model on dev-master.

Concerning the controller, this is already implemented.
And concerning the last `make-migration` suggestion, I don't think this is needed as the first already covers this. Even more so since we don't specifically know the model name.

**Comment by irvine48** [comment]
Thank You so much for this!

**Comment by harshalone** [comment]
Just to reiterate if you want to create a model inside your module.

Command given in the documentation on nwidart website is: 
`
php artisan module:make-model Post Blog`


Which is confusing. The correct command is:

```
php artisan module:make-model [name of your module] [name of your model]

ex.

php artisan module:make-model Events Events
```

Reference: https://github.com/nWidart/laravel-modules/issues/1027

**Comment by EssDaniels** [comment]
php artisan module:make-model [name of your model]  [name of your module] 

ex.

php artisan module:make-model Events Events

**Comment by admiral9200** [comment]
But let's say! I am gonna make a model named 'EventListener' in existing 'Events' module. In this case, how can I do?
