### ISSUE TITLE
Modules cache doesn't work

### ISSUE THREAD

**Issue by webmake** [nWidart/laravel-modules#246]
Exception:
```
(1/1) FileNotFoundException
File does not exist at path /module.json
```

It doesn't work with vendor scan due this hardcoded line https://github.com/nWidart/laravel-modules/blob/808ab448522f9168349f794e289ca04ae286e215/src/Repository.php#L162

used config
```
    'scan' => [
        'enabled' => true,
        'paths' => [
            base_path('vendor/OtherCompany/*/src'),
        ],
    ],
```

**Comment by nWidart** [comment]
Hello & thanks for reporting this.

I don't use vendor scan myself so feel free to send a PR with a possible fix for the issue.
