### ISSUE TITLE
Listening events in another module

### ISSUE THREAD

**Issue by renanBritz** [nWidart/laravel-modules#247]
Hello!

I'd like my modules to be able to listen to events dispatched by other modules.

When I create an event listener and try to use the event from another module, it won't generate the namespace correctly. For example:

`php artisan module:make-listener --event=\Module\Sales\Events\SalesEvent Financial`

So I want my Financial module to listen to a Sales module event.

But the handle method in the SalesListener class doesn't have the correct namespace to the event class:

```
public function handle(\Modules\Financial\Events\ModulesSalesEventsSalesEvent $event)
{
    //
}
```
That forces me to rewrite the path manually.

It's also seems to be necessary to bind an EventListener to the module's EventServiceProvider in order for this to work. Like so:

```
<?php

namespace Modules\Financial\Providers;

use Illuminate\Support\ServiceProvider;

class EventServiceProvider extends ServiceProvider
{
    protected $defer = false;

    public function register()
    {
        \Event::listen(\Modules\Sales\Events\SalesEvent, \Modules\Financial\Listeners\SalesListener);
    }

    //...
}
```

If you could point me to better solutions I would appreciate.

Best regards!

**Comment by nWidart** [comment]
I don't use the generator for such a simple class.

You can just listen to the desired event in the `handle` method, just like any laravel app.
In the same way, you can setup event registration like in any laravel app.

Look at for example this service provider: https://github.com/Idavoll/User/blob/2.0/Providers/EventServiceProvider.php

**Comment by renanBritz** [comment]
Hello @nWidart !

I see... I was extending the ServiceProvider instead of the EventServiceProvider. That's why the $listen attribute was ignored before.

I'll create the classes by hand then. But if you want to reconsider... the generators are great for productivity and to minimize errors, specially for those that are still learning.

Thank you for your support!

**Comment by nWidart** [comment]
Feel free to send a PR which fixes bugs. 👍

**Comment by hadi-mansoori** [comment]
Hi, I added $listen to the EventServiceProvider of module but it doesn't work
 protected $listen = [

        RegistrationEvent::class => [
            NotifyToUserListener::class,
            EmailNotifyToUserListener::class,
            SmsNotifyToUserListener::class,
        ],
    ];

**Comment by ianwinstanley** [comment]
I found that I needed to remove `public function register()` and `public function provides()` to get the `$listen` to trigger.
