### ISSUE TITLE
Auth data is lost after login 

### ISSUE THREAD

**Issue by dagulo** [nWidart/laravel-modules#248]
On login I redirected the request to a module but  Auth::user() will now return null. If I redirect to a non module route Auth::user() has data.

Any idea?

**Comment by nWidart** [comment]
Are you using that in a __construct ? The session isn't started at that time.

**Comment by dagulo** [comment]
Upon further investigation I found out that the 'web' middleware wasn't called when using the module routes. I created a route group to make it work 
`Route::group( [ 'middleware' => [ 'web' ], 'prefix' => 'hris/admin', 'namespace' => 'Modules\Hris\Http\Controllers\Admin' ],        function(){
            Route::get( 'dashboard', 'HrisAdminController@dashboard' );
 });`

**Comment by nWidart** [comment]
Ah yes that would do it. 😄  Good find.

**Comment by paanblogger** [comment]
This solution is not working for me.
By default , routes file in modules directory already have route group with middleware 'web'.
But still , I cannot get Auth data for controller on the Modules directory.

Changing route group middleware to Auth , also make laravel redirect to login page , eventhough , I have already login.
