### ISSUE TITLE
 There are no commands defined in the "module" namespace. 

### ISSUE THREAD

**Issue by prayas-sapkota** [nWidart/laravel-modules#251]
Hello,

I install modules and trying to run below command.

php artisan module:make pharmacy

It shows below error:

  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "module" namespace.        

How can I solve the issue?

Thanks

**Comment by treetechsuman** [comment]
composer dump-autoload 
work for me

**Comment by nWidart** [comment]
Make sure you installed the package correctly (adding the service provider) and indeed ran dump autoload.

**Comment by prayas-sapkota** [comment]
Thank you for your reply. Yes, composer dump-autoload works.

**Comment by nWidart** [comment]
Cool 👍

**Comment by hoangcao10** [comment]
ran composer dump-autoload still not working

**Comment by andrewdaluz** [comment]
If someone comes here to find a solution, here will help you: 
### Solution 1:

The general main cause of this kind of error is missing **etc/module.xml** file in your module. Or, missing **setup_version** code in **module.xml** file.

Here is a sample **module.xml** file of a module named **YourNamespace_YourModule**.

`app/code/YourNamespace/YourModule/etc/module.xml`

```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd"> 
    <module name="YourNamespace_YourModule" setup_version="2.0.0" /> 
</config>
```

If you are not sure which module is creating this problem, you can try removing each module and check to find the problematic module.

### Solution 2:

If solution 1 doesn’t help then you can try this second solution.

Give full control (read/write/execute) to **var** and **pub** directory solved this issue for me.

```
sudo chmod -R 777 var pub
```

You may also try running the following command:

```
sudo php -f bin/magento module:enable --clear-static-content YourNamespace_YourModule
```

Reference: http://blog.chapagain.com.np/magento-2-invalidargumentexception-there-are-no-commands-defined-in-the-setup-namespace/

**Comment by mikemand** [comment]
I'm pretty sure this is not a Magento repository... Or in any way related to Magento...

**Comment by bosz** [comment]
Having same issue, tried `composer dump-autoload` several times but does not work for me.

**Comment by alhassancse** [comment]
composer dump-autoload still not working

**Comment by infomani** [comment]
`manikandan@manikandan /var/www/html/MyProject $ 
manikandan@manikandan /var/www/html/MyProject $ 
manikandan@manikandan /var/www/html/MyProject $ 
manikandan@manikandan /var/www/html/MyProject $ php artisan cache:clear
Cache cleared successfully.
manikandan@manikandan /var/www/html/MyProject $ composer dump-autoload
Generating optimized autoload filesCarbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Package manifest generated successfully.
Generated optimized autoload files containing 2050 classes
manikandan@manikandan /var/www/html/MyProject $ php artisan module:make mymod

                                                            
  There are no commands defined in the "module" namespace.  
                                                            

manikandan@manikandan /var/www/html/MyProject $`

**Comment by ReubenRahul** [comment]
if you are using  linux system it may be due to permission issue. so you can give the permission by command
sudo chmod -R 777 your_project_folder_path

thanks

**Comment by mranonyms022** [comment]
not working for me I have tried all methods.
