### ISSUE TITLE
can i use this with lumen?

### ISSUE THREAD

**Issue by winnie80** [nWidart/laravel-modules#252]
I would like to add modular function to my lumen project. 
Is it possible to use this package?
Reason is because I have developed some of modules in asgardCms that I would like to re-use in my next lumen projects.
Thank you all for your help.

**Comment by nWidart** [comment]
Hi,

I don't use Lumen so I couldn't tell you. Feel free to send a PR if need to make it compatible with lumen.

**Comment by winnie80** [comment]
Sorry if I open this again.
I finally just use Asgard CMS instead of lumen.
With Asgard I can create API access for our headless project, just by activating adding Http/apiRoutes.php inside our custom modules
Override Exceptions/Handlers is also possible, so our API can produce error messages in JSON format.
Thanks nWidart for this cms and laravel-modules.

**Comment by nWidart** [comment]
Of course yes, just like you would in any laravel app. Return json responses from your controllers.
