### ISSUE TITLE
Route model bindings

### ISSUE THREAD

**Issue by yNaxon** [nWidart/laravel-modules#253]
Laravel's model binding seem to not work with this package.

When written in Laravel's default web routes file, routes/web.php, this script dumps page title:

```
Route::get('/admin/pages/{page}/edit', function(Modules\Pages\Entities\Page $page) {
  dd($page->title);
});

```

but when I put it inside module's route file, it will dump `null`.

Is there a way to get around this?

**Comment by nWidart** [comment]
They do work, I use them all the time.

You probably need to define the binding before the route.

**Comment by yNaxon** [comment]
@nWidart would you care to share an example? I tried explicit binding with no success

**Comment by nWidart** [comment]
From the docs:

``` php
Route::bind('user', function ($value) {
    return App\User::where('name', $value)->first();
});
```

**Comment by yNaxon** [comment]
That's exactly what I did, putting it in the beginning of routes.php:

```
Route::bind('page', function ($value) {
    return Modules\Pages\Entities\Page::where('id', $value)->first();
});
```

**Comment by nWidart** [comment]
Are you sure you don't have a typo somewhere? Make sure this closure is called by running a `dd` inside it for instance.

**Comment by yNaxon** [comment]
I ran a dd inside the binding closure  and it runs
Also, If I take the exact same route definition and put it in laravel's default routes file, it works even without explicit binding.. So strange

**Comment by nWidart** [comment]
well then I don't see the issue. If the closure is called means it's working as intended.

**Comment by yNaxon** [comment]
As it turns out,
I needed to add 'web' middleware in order to enable model binding.

@nWidart thanks for your immediate help!

**Comment by nWidart** [comment]
Ah nice, that's good to know! Thanks for letting us know here. 😄

**Comment by marufdevops** [comment]
This is also not working for me! 

Here is the code snippet 

`Route::bind('program', function ($value) {
    dd(1);
    return Program::where('id', $value)->first();
});`

`Route::middleware(['web', 'auth'])->group(function () {
    Route::get('/', 'ProgramController@index');
    Route::get('programs/{program}', function(){
        dd(1);
    });
});
`

placed the same code on module service provider boot method. Can someone please help here.
