### ISSUE TITLE
Route Domains on Modules

### ISSUE THREAD

**Issue by davidlares** [nWidart/laravel-modules#256]
Hello!

I'm using this module for a Ecomm Project, reviewing the docs it seems there's no functionalities for `Route::domain` (new in ver 5.4) or the `['domain' => '{account}.myapp.com']` (older versions)

On the main routes.php on Laravel both ways worked as expected, but inside a module it can't be done. Does the package have a practical solution for this? or wi'll be a Feature later?.

Thanks for your time.

**Comment by nWidart** [comment]
Hi,

This package doesn't do anything with routes, meaning you can do anything laravel does with routes.

Make sure you have everything setup. [For instance this recent issue](https://twitter.com/ircmaxell/status/879806118062690304).

**Comment by davidlares** [comment]
ok, I'll take a look again, I'm pretty sure there's no syntax error. Does the prefix or the namespace attrs on the Route::group are neccesary?

I'll post back in a bit with a response. Thanks again

**Comment by davidlares** [comment]
@nWidart There's no problem with your package, it's a server subdomain problem. I'm closing it right away

**Comment by nWidart** [comment]
Alright, awesome. Good to know you found the fix. 😄
