### ISSUE TITLE
What will be the url for controller under module

### ISSUE THREAD

**Issue by prayas-sapkota** [nWidart/laravel-modules#257]
Hello,

I just created a controller under a module with:
php artisan module:make-controller DepartmentsController Lab

How do I access this page?

I tried http://project.dev/lab/departments but it says page not found.

Please help me.

Thanks

**Comment by nWidart** [comment]
Hi,

Just like any other laravel app, you'll need a route pointing to that controller.

**Comment by prayas-sapkota** [comment]
Thanks @nWidart 

I will give a try. And if no luck I will ask you again.

Would it be like:
Route::get('/lab/departments', 'DepartmentsController');

Thanks

**Comment by prayas-sapkota** [comment]
Hello @nWidart will you please help me on this?

Thanks in advance.

**Comment by nWidart** [comment]
Not sure what you want, this is all just regular stuff, the laravel documentation can help you here.

You can also look at existing modules on the [Idavoll](https://github.com/idavoll) namespace (asgardcms).

**Comment by yassersharaf** [comment]
@prayas-sapkota 
Let's say you created CMS module. Go to routes/web.php and add for example:
Route::get('/cms', '\Modules\CMS\Http\Controllers\CMSController@index');
