### ISSUE TITLE
How to manage modules with a separate git repository

### ISSUE THREAD

**Issue by anardil** [nWidart/laravel-modules#260]
Hello,

Do you have any ideas to manage modules with a separate git repository?

Thank you.

**Comment by nWidart** [comment]
Hi,

You can have modules in a git repository yes, that's up to you to handle however you prefer.
Check the github.com/asgardcms/ modules for example.

**Comment by anardil** [comment]
Hello,

Thanks.
But how do you manage this with git? Do you use git submodules or subtree.
I'm new with git and I don't know what's the best method.

**Comment by nWidart** [comment]
Every module used to be a separated git repository, no submodules/trees. This is the simplest way really. 
Version 2 of asgardcms changed this and is now using subsplits, but this is a lot more complex.

**Comment by gmox** [comment]
is there a reason for that split that might affect (positively or negatively) other people? Or is it personal preference?

**Comment by nWidart** [comment]
Yes, it was explained in the [2.0 blog post](https://asgardcms.com/blog/posts/version-2-0-released). tl;dr : making contributions a lot easier.
