### ISSUE TITLE
Route resource is not working. 

### ISSUE THREAD

**Issue by machii28** [nWidart/laravel-modules#261]
![image](https://user-images.githubusercontent.com/11863084/27769111-65433124-5f55-11e7-9c5c-a60039a3a7b5.png)

Here's the problem. I've generated a restful controller and added a route::resource in the routes folder but the argument that need to be passed on the route resource is not added or not generated although I've already indicated the arguments in the function.

**Comment by nWidart** [comment]
I did the same thing, yet it works.

![screen shot 2017-07-02 at 12 51 57](https://user-images.githubusercontent.com/882397/27769204-4af6be4c-5f25-11e7-8781-10850b48f0cd.png)


Make sure you've setup everything properly.

**Comment by machii28** [comment]
Thank you for the very fast response. It's my fault too make my code like this. 

```
Route::group(['prefix' => 'user'], function() {
    Route::resource('/', 'UserController');
});
```

**Comment by machii28** [comment]
Thank you i'll close this

**Comment by machii28** [comment]
Thanks

**Comment by machii28** [comment]
Thanks
