### ISSUE TITLE
Move 'Modules' package inside 'App' package safely.

### ISSUE THREAD

**Issue by montyclt** [nWidart/laravel-modules#263]
Hi!

I would like use [Laravel Annotation](https://laravelcollective.com/docs/master/annotations) with my modules, but this package only can scan all App namespace.

I think my best way is move Module folder to app package, but is it safe? What is the safe form to do it?

**Comment by nWidart** [comment]
Hi,

That's too bad for that package, probably worth contributing to it to allow any namespace.

If you want to change the location you can do so by changing the configuration file. 
There's the `namespace` key and the `modules.paths` one that will be relevant to you.

**Comment by nWidart** [comment]
From the Annotation doc:

> If you have changed the top-level namespace to something like 'MyCompany', then you would use the new namespace instead of 'App'.

This sounds like it's possible no ?

**Comment by montyclt** [comment]
Sorry, I said _this package only can scan all App namespace_, but is not it is not true.

In the docs, there are examples specifying directly the model, events and routes classes, and talks too about an alternative: _Alternatively, you can set protected $scanEverything to true to automatically scan all classes within your application's namespace._

Here, the package internally use the `getNamespace()` method of `Container` instance for get the application namespace. My application namespace remains `App` and I want to remain `App`.

**Comment by nWidart** [comment]
I didn't get what you said but, you're free to use any namespace you want.

**Comment by montyclt** [comment]
My question is, regardless of the reasons, can I move safetly the 'Modules' folder to 'App' folder?

**Comment by nWidart** [comment]
Yes ... I explained how in my first response.

**Comment by montyclt** [comment]
Sorry, I did not notice, I read directly the second, thanks you!
