### ISSUE TITLE
create laravel module problem

### ISSUE THREAD

**Issue by md-reyad** [nWidart/laravel-modules#264]
←[37;41m  [Symfony\Component\Console\Exception\CommandNotFoundException]  ←[39;4
9m
←[37;41m  There are no commands defined in the "module" namespace.

**Comment by nWidart** [comment]
You did not install this package completely.

Please add the service provider.

**Comment by md-reyad** [comment]
I have already add service provider config/app.php where are problem, please help me..

**Comment by nWidart** [comment]
did you run `composer dump-autoload` ?

**Comment by md-reyad** [comment]
Yes I have run the command before.

**Comment by nWidart** [comment]
You need to run it after you installed the package.

**Comment by md-reyad** [comment]
Yes I know that.

**Comment by md-reyad** [comment]
I have follow the documentation from https://nwidart.com/laravel-modules/v1/installation-and-setup.
Every step is completed. But not working for me showing an error for laravel 5.4.

**Comment by nWidart** [comment]
I just installed on clean laravel installation, no issues. Make sure you followed the steps.

**Comment by md-reyad** [comment]
Can you please send me the your fresh sample project? email: imam.reyad93@gmail.com

**Comment by nWidart** [comment]
No. Just install the package as any laravel package and it will work.

**Comment by md-reyad** [comment]
I think here is some problem in this package :( I have installed it followed by your given steps . Also I have trying to another computer but unfortunately it not working in my both computer.

**Comment by nWidart** [comment]
I don't think so. I just installed on a clean install and working. You must have something wrong somewhere.

**Comment by md-reyad** [comment]
I am really confused about it. If you send your clean project. then it will help me to find out my mistake.

**Comment by armababy** [comment]
@md-reyad you can get clean project by installing fresh laravel and then this package. No need to send files over internet :)

**Comment by md-reyad** [comment]
Ok I'll try again using fresh laravel version. Thanks for your cooperation. Also, I'll inform you regarding this issue.

**Comment by md-reyad** [comment]
Thanks, Now it's working for me.

**Comment by alhassancse** [comment]
Same issue face..

"There are no commands defined in the "module" namespace."

error this command line when create module.
