### ISSUE TITLE
Can't add variable in 'asset'

### ISSUE THREAD

**Issue by quienti** [nWidart/laravel-modules#265]
When a use this :

`{!! Module::asset("images/" . $variable. ".jpg") !!}`

I have this error => `Undefined offset: 1 (View: D:\Documents\Dev\Php\Starlight\Modules\Page\Resources\views\includes\footer.blade.php)`

Works fine if I use ``{!! asset("images/" . $variable. ".jpg") !!}``

**Comment by nWidart** [comment]
That's normal. Please read the documentation. You can find it here: https://nwidart.com/laravel-modules/v1/advanced-tools/facade-methods

**Comment by quienti** [comment]
I forgoten to add my module name ... Sorry!

Thanks!

**Comment by nWidart** [comment]
Awesome.

I've changed it so that it will throw a cleaner exception in case this happens:

```
Module name was not specified in asset [somefile.js]. 
```

**Comment by quienti** [comment]
Nice!

Thanks you
