### ISSUE TITLE
Module with changes in different projects

### ISSUE THREAD

**Issue by elephantux** [nWidart/laravel-modules#267]
For example, I made a module "team" in which default fields are name, email, phone. I have it in git as a private repository and use it in the some projects. 
But what if in a certain project in this module it is necessary to add a photo? If I do changes directly in the module code I need to commit it and use this unwanted functionality in other projects (if I do git pull on it).
Just don't do commit? Git branch? How can there be logic? Any ideas?

**Comment by nWidart** [comment]
That's up to you. It basically depends if you value keeping the ability to update the module or not.

If you do, then you can fork your module and make the changes while keeping the ability to update.

If not it's more easily, remove your module from composer, and customise on a per project basis.

I usually go for the second option. It's all about the trade offs.
