### ISSUE TITLE
Hook in the install process

### ISSUE THREAD

**Issue by Goopil** [nWidart/laravel-modules#268]
Hello
I'm looking for a simple way to hook in the install / uninstall process.

Is there any events triggered, when command are called ?

This is to have a route registration mechanism to populate menu. Do you have some pointers ?

thanks you in advance.

**Comment by nWidart** [comment]
Hello,

I don't recall having events in the install command (there is no uninstall one). 
This could a good idea to have so I'd accept a PR for this feature.

**Comment by Goopil** [comment]
Ok i will look in to it. Just to be sure, how you see it. It should be a "beforeInstall" "afterInstall" and expose the module and the command (to make prompt if needed) is this implementation ok for you ?

**Comment by nWidart** [comment]
I think we could simply trigger 2 events, in these locations:

- https://github.com/nWidart/laravel-modules/blob/master/src/Process/Installer.php#L133 (before, `ModuleIsInstalling`)
- https://github.com/nWidart/laravel-modules/blob/master/src/Process/Installer.php#L142 (after, `ModuleWasInstalled`)

These events could accept the module name.

**Comment by Goopil** [comment]
Ok i will try somethings, what about enabled & disabled ? Are you also interested ?

**Comment by nWidart** [comment]
Not yet, as that feature will change in the near future.

**Comment by Goopil** [comment]
do you have a roadmap somewhere ?

**Comment by nWidart** [comment]
No roadmap no. Note that PR need start and go to the 1.0 branch, which is for laravel 5.4

**Comment by Goopil** [comment]
You're right, it is a mather of context to have directly the module inside it. So here you'are.
