### ISSUE TITLE
how to run migration for specific module without cli, i try this but not working

### ISSUE THREAD

**Issue by treetechsuman** [nWidart/laravel-modules#269]
Artisan::call('module:migrate gallery', array('--path' => 'Modules/Gallery/Database/Migrations'));

**Comment by nWidart** [comment]
you need to specify the module name in the array.

**Comment by treetechsuman** [comment]
can you provide example please

**Comment by nWidart** [comment]
`Artisan::call('module:migrate', ['module' => 'gallery', '--path' => 'Modules/Gallery/Database/Migrations')`
