### ISSUE TITLE
How to use factory

### ISSUE THREAD

**Issue by benvindo** [nWidart/laravel-modules#270]
Hi, I tried use factory, but when run **php artisan module:seed**  show me this:

> Seeding: Modules\Cliente\Database\Seeders\ClienteTableSeeder
> Unable to locate factory with name [default] [Modules\Cliente\Entities\Cliente].

**/Modules/Cliente/Database/Seeders/ClienteTableSeeder.php**
```
<?php

namespace Modules\Cliente\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Modules\Cliente\Entities\Cliente;

class ClienteTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Cliente::truncate();
        factory(Cliente::class, 10)->create();

    }
}
```

**/Modules/Cliente/Database/Factories/ModelFactory.php**
```
<?php


$factory->define(\Modules\Cliente\Entities\Cliente::class, function (Faker\Generator $faker) {

    return [
        'name' => $faker->name,
        'responsible' => $faker->name,
        'email' => $faker->unique()->safeEmail,
        'phone' => $faker->phoneNumber,
        'address' => $faker->address,
        'obs' => $faker->sentence,
    ];
});
```

How to fix it?

**Comment by nWidart** [comment]
You need to load your factories. https://github.com/nWidart/laravel-modules/blob/master/src/Commands/stubs/scaffold/provider.stub#L95

**Comment by benvindo** [comment]
Okay, thanks it's work

**Comment by Phu1237** [comment]
![image](https://user-images.githubusercontent.com/9032235/96210083-5d9f4a80-0f9b-11eb-868f-91c81c511b17.png)
![image](https://user-images.githubusercontent.com/9032235/96210143-7e67a000-0f9b-11eb-8812-4c823966b7ab.png)

Sorry but i meet this too and i haven't find a way to fix this yet. Can you help me? I have added factory to provider at "Modules\Test\Providers\TestServiceProvider.php" @benvindo 
P/s: Please see my images. Tks!

**Comment by OsmairCoelhoGY** [comment]
> You need to load your factories. https://github.com/nWidart/laravel-modules/blob/master/src/Commands/stubs/scaffold/provider.stub#L95

I am trying to run my seed but it's not working, he said "You need to load your factories." but how to do that?

![image](https://github.com/nWidart/laravel-modules/assets/134397238/aeb34f47-fd79-4bf8-aeea-fdeed79d9051)

**Comment by OsmairCoelhoGY** [comment]
After writing this code in my model works for me

I took the solution from https://laracasts.com/discuss/channels/general-discussion/laravel-module-package-not-working-with-factory 

that redirect to https://github.com/nWidart/laravel-modules/issues/1094    
    
![image](https://github.com/nWidart/laravel-modules/assets/134397238/b1a674a5-f0ac-4288-95fe-f04333e00c23)


![image](https://github.com/nWidart/laravel-modules/assets/134397238/8f05daa4-745f-49cf-a671-b69c4794685c)
