### ISSUE TITLE
Laravel 5.3 routes update

### ISSUE THREAD

**Issue by Reastyn** [nWidart/laravel-modules#28]
Hello,
first of all I love laravel-modules and that you're taking care of this package. Would you consider the Laravel 5.3 support with the "routes" folder for all of the modules routes? The support for not adding unused folders by default would be really awesome as well.
Thanks

**Comment by nWidart** [comment]
It is already supported if you look at the composer.json file.

I'm not sure what you mean by routes folder as nothing will change for 5.3.

**Comment by Reastyn** [comment]
Yeah I've seen it but there's some changes with routes in 5.3. There's a routes folder now and I think that module's routes should be in that folder
https://mattstauffer.co/blog/routing-changes-in-laravel-5-3

**Comment by nWidart** [comment]
Yes, but again, this isn't related to the package.

Current built in routes are in app/routes.php, that doesn't mean module routes are located there. Same logic for `/routes.php`.

**Comment by Reastyn** [comment]
Well when there's a routes folder why to have every module have it's own routes.php file?

**Comment by nWidart** [comment]
Because that's the point of this package. Every module can be independently installed and used.

**Comment by Reastyn** [comment]
Oh I see.. Sorry my bad.. What about the ServiceProvider that registers the route. Is there a way to register the route using the namespace so I don't have to have Route::group in the routes.php file?

**Comment by nWidart** [comment]
Yes you're free to do it whatever way you want.

In asgardcms, the `$router` variable is available in the routes.
