### ISSUE TITLE
How can I prioritise the order in which routes are loaded

### ISSUE THREAD

**Issue by aidanbigg** [nWidart/laravel-modules#280]
Is there any way I can prioritise the way routes are loaded?

I am building a CMS and need a catch-all route for dynamic pages. However the catch all route is also picking up the "/admin" url.

I'd like to be able to change the order in which routes are loaded so that the catch-all route is always last

Thank you

**Comment by nWidart** [comment]
Use the order key in the module.json.

**Comment by aidanbigg** [comment]
Is there a value I can use which will always include it at the bottom, or will I have to continuously update they order key value which each module I add?

**Comment by nWidart** [comment]
no you need to maintain the order key yourself.

**Comment by aidanbigg** [comment]
OK, thank you

**Comment by nWidart** [comment]
However a feature, to puts a module always last could maybe be interesting to have.

**Comment by aidanayala** [comment]
I can see that if I set the module I wanted loaded last to "-1" and then change the direction in Repository::getOrdered(), it'll load it last.

But I can't see where $direction is set

**Comment by nWidart** [comment]
That's interesting. The ordering happens here: https://github.com/nWidart/laravel-modules/blob/master/src/Repository.php#L262

**Comment by aidanayala** [comment]
Yeah but I can't see anywhere in the config to set the direction

**Comment by nWidart** [comment]
It's in module.json

**Comment by aidanayala** [comment]
Sorry, but I don't see direction anywhere in module.json. I'd of thought it'd be a global thing set in one place?

**Comment by nWidart** [comment]
Hm I misunderstood, you can't the direction, only the order.

**Comment by aidanayala** [comment]
Okay. It just seems strange that there's an if statement to switch between asc/desc, yet we can't set it in config even though it's set via config/option. If you see what I mean?

https://github.com/nWidart/laravel-modules/blob/master/src/Commands/ListCommand.php#L65

**Comment by nWidart** [comment]
yup totally. that asc/desc could be set via a configuration probably.

**Comment by aidanayala** [comment]
Can this be a feature request?

**Comment by nWidart** [comment]
yes, feel free to send a PR 😄

**Comment by aidanayala** [comment]
I wouldn't know where to start :'(
