### ISSUE TITLE
module.php instead of module.json

### ISSUE THREAD

**Issue by bert-w** [nWidart/laravel-modules#282]
What is the reason why modules use a `modules.json` instead of a `modules.php` file? I'm simply comparing to existing laravel config like `config/app.php` which is ofcourse a similar file but with php syntax.

The reason I ask is because I'd like to do some little logic which only loads a serviceprovider in a specific environment (production). This is impossible with just the `.json` file since it doesnt allow logic

**Comment by nWidart** [comment]
Hello,

No real reason, more like a legacy thing, pingpong/modules had it this way.
I've recently thought about this same thing, if it would be worth changing this, but ended up deciding with others on the AsgardCMS slack channel that it wasn't worth the trouble (& major BC).

My argument was only for performace though.

The logic you talk about shouldn't ge in a config file either anyway.
If you need this logic, I would suggest loading your service provider from a service provider. Like debugbar for instance.

**Comment by vankaiser** [comment]
Hi Author,

Basic question, how do you require a module as a prerequisite for another module to be enabled?
I have tried adding it to module.json of the extension module but I can enable it even the prerequisite module(core) was disabled.

Thanks!

**Comment by nWidart** [comment]
@vankaiser this will help you: https://github.com/AsgardCms/Platform/wiki/custom-module-dependency

**Comment by vankaiser** [comment]
Many thanks.
