### ISSUE TITLE
Class Module ServiceProvider not found

### ISSUE THREAD

**Issue by jakecorn** [nWidart/laravel-modules#283]
hi,

I would like to ask about this problem.

I able to create a module named Teacher using this command php artisan module:make Teacher. However, when I create another module or even run php artisan serve it shows me this error.

 **[Symfony\Component\Debug\Exception\FatalThrowableError]
 Class 'Modules\Teacher\Providers\TeacherServiceProvider' not found**

Every command I tried but it shows me the same error I even tried php artisan.

I already added this  **'Module' => Nwidart\Modules\Facades\Module::class,** to aliases and **Nwidart\Modules\LaravelModulesServiceProvider::class**, to  provider.

please help me , thank you.

**Comment by nWidart** [comment]
Hello,

That means your module was created, the package found your service provider, but composer wasn't able to load the service provider.

Meaning you probably forgot to add the psr-4 part of the documentaiton.

**Comment by jakecorn** [comment]
Thank you for the response.

Im done with psr-4 but the error is still there. 
This is my code in composer.json

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "nwidart/laravel-modules": "^1.27"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        **"psr-4": {
            "App\\": "app/",
		"Modules\\": "Modules/"
        }**
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}

**Comment by hybrid1969** [comment]
'composer update' should fix your issue.

**Comment by nWidart** [comment]
or dump autoload (which is run after an update).

**Comment by jakecorn** [comment]
I found same issue https://github.com/nWidart/laravel-modules/issues/4, same solution as you have just suggested,this fixed my problem. Thank you

**Comment by nWidart** [comment]
Cool.

I've added this info on the readme and documentation website. 👍

**Comment by humphreymhonja** [comment]
hi,
i have this problem in my app laravel5.4 itried to display the output but i get an error of app\Instructor not found still i define it at the top
    <?php
     
    namespace App\Http\Controllers;
     
    use Illuminate\Http\Request;
    use app\Instructor;
     
    class CreatesController extends Controller
    {
       public function home(){
           $instructors=Instructor::all();
           print_r($instructors);
           
              }
       }
     
     

Arguments

    "Class 'app\Instructor' not found"

**Comment by bosz** [comment]
Oh, i had this same issue, as @nWidart  pointed out, I forgot to add `"Modules\\": "Modules/"` to my composer.json. As soon as i added it and did `composer dump-autoload`, it works. 

Thanks for the awesome package @nWidart

**Comment by DonOndeje** [comment]
Great...I had the same issue but it is all fixed now. Thanks @nWidart

**Comment by amirex128** [comment]
nice guys

**Comment by kerell78us** [comment]
Hey Guys, I have a question regarding the usage of namespace (with the laravel-module package). Is that we're tied to using the namespace "Modules" instead of the Developer's name as per below;
"Modules\Activity\Providers\ActivityServiceProvider" instead of "DeveloperName\Activity\Providers\ActivityServiceProvider"

**Comment by SocolaDaiCa** [comment]
```php
return [

    /*
    |--------------------------------------------------------------------------
    | Module Namespace
    |--------------------------------------------------------------------------
    |
    | Default module namespace.
    |
    */

    'namespace' => 'Modules',

```

You can config namespace before create new module, It is DeveloperName

**Comment by kerell78us** [comment]
> ```
> return [
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Module Namespace
>     |--------------------------------------------------------------------------
>     |
>     | Default module namespace.
>     |
>     */
> 
>     'namespace' => 'Modules',
> ```
> 
> You can config namespace before create new module, It is DeveloperName

Thanks @SocolaDaiCa. That's what I thought but when I change it I get **Class "KerwinEllis\Listing\Providers\ListingServiceProvider" not found**.

**Comment by SocolaDaiCa** [comment]
```
{
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Modules\\": "Modules/",
      "KerwinEllis\\": "Modules/"
    }
  }
}
```

you need config autoload

**Comment by SocolaDaiCa** [comment]
after that, maybe need run composer dumpautoload

**Comment by kerell78us** [comment]
> ,
>       "KerwinEllis\\": "Modules/"

Aha, it worked, @SocolaDaiCa thanks a million

**Comment by mubi351** [comment]
Thank you.It worked for me also

**Comment by Vatiraije** [comment]
Hi, i have  problem when testing my laravel api in postman
i am getting this error"
Error: Class &quot;App\Models\ServiceProvider&quot; not found in file C:\xampp\htdocs\GMS\adminS-laravel\app\Http\Controllers\Api\FormSubmissionController.php on line 22" however i have configured everything that needs to be configured .please help me fix this error

**Comment by mardhy21** [comment]
how to fix it Class "Modules\Products\Providers\ProductsServiceProvider" not found in laravel 11

**Comment by dcblogdev** [comment]
> how to fix it Class "Modules\Products\Providers\ProductsServiceProvider" not found in laravel 11

ensure you've updated composer:

> from v11.0 autoloading "Modules\\": "modules/", is no longer required.

By default, the module classes are not loaded automatically. You can autoload your modules by adding merge-plugin to the extra section:

```
"extra": {
    "laravel": {
        "dont-discover": []
    },
    "merge-plugin": {
        "include": [
            "Modules/*/composer.json"
        ]
    }
},
```

Tip: don't forget to run composer dump-autoload afterwards

**Comment by GempitaRizki** [comment]
> how to fix it Class "Modules\Products\Providers\ProductsServiceProvider" not found in laravel 11

same issue on laravel 11

**Comment by GempitaRizki** [comment]
> "merge-plugin": {
>         "include": [
>             "Modules/*/composer.json"
>         ]
>     }

its work , Thank you

**Comment by jhonymiler** [comment]
Run the command: artisan module:publish
Add the "namespace" variable to the items in the "generator" array.
![image](https://github.com/nWidart/laravel-modules/assets/18699320/77055a84-2507-4e01-8613-87670d25a8fc)

The team forgot about PSR-4 with PHP 8.2.

**Comment by mardhy21** [comment]
Done, tnks

**Comment by mnarbash** [comment]
In Laravel 11 and Laravel Module 11,
ensure that "wikimedia/composer-merge-plugin" is set to true in composer.json,
like this:

```
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true,
            "wikimedia/composer-merge-plugin": true
        }
    }, 
```

**Comment by hadjamagamy** [comment]
PS C:\Users\MagamyGBANEADJA\OneDrive - FINACTU INTERNATIONAL\Bureau\example-modulaire-app> composer update
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating optimized autoload files
Class Modules\Auth\Http\Controllers\AuthController located in ./Modules/Auth/app/Http/Controllers/AuthController.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                 
Class Modules\Auth\Providers\AuthServiceProvider located in ./Modules/Auth/app/Providers/AuthServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                     
Class Modules\Auth\Providers\EventServiceProvider located in ./Modules/Auth/app/Providers/EventServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                   
Class Modules\Auth\Providers\ModuleServiceProvider located in ./Modules/Auth/app/Providers/ModuleServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                 
Class Modules\Auth\Providers\RouteServiceProvider located in ./Modules/Auth/app/Providers/RouteServiceProvider.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.                   
Class Modules\Auth\Database\Seeders\AuthDatabaseSeeder located in ./Modules/Auth/database/seeders/AuthDatabaseSeeder.php does not comply with psr-4 autoloading standard (rule: Modules\ => ./Modules). Skipping.             
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error

  Class "Modules\Auth\Providers\AuthServiceProvider" not found

  at vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:206
    202▕      * @return \Illuminate\Support\ServiceProvider
    203▕      */
    204▕     public function createProvider($provider)
    205▕     {
  ➜ 206▕         return new $provider($this->app);
    207▕     }
    208▕ }
    209▕

  1   vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:142
      Illuminate\Foundation\ProviderRepository::createProvider("Modules\Auth\Providers\AuthServiceProvider")   

  2   vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:61
      Illuminate\Foundation\ProviderRepository::compileManifest()

**Comment by tajik2020** [comment]
I am getting same issue


   Error 

  Class "Modules\AppLogin\Providers\AppLoginServiceProvider" not found

  at vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:206
    202▕      * @return \Illuminate\Support\ServiceProvider
    203▕      */
    204▕     public function createProvider($provider)
    205▕     {
  ➜ 206▕         return new $provider($this->app);
    207▕     }
    208▕ }
    209▕ 

      +11 vendor frames 

  12  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Nwidart\Modules\LaravelModulesServiceProvider), "Nwidart\Modules\LaravelModulesServiceProvider")
      +6 vendor frames 

  19  artisan:13
      Illuminate\Foundation\Application::handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))

**Comment by dcblogdev** [comment]
can you upload this to a repo so I can investigate.

**Comment by hasanablak** [comment]
> > how to fix it Class "Modules\Products\Providers\ProductsServiceProvider" not found in laravel 11
> 
> ensure you've updated composer:
> 
> > from v11.0 autoloading "Modules\": "modules/", is no longer required.
> 
> By default, the module classes are not loaded automatically. You can autoload your modules by adding merge-plugin to the extra section:
> 
> ```
> "extra": {
>     "laravel": {
>         "dont-discover": []
>     },
>     "merge-plugin": {
>         "include": [
>             "Modules/*/composer.json"
>         ]
>     }
> },
> ```
> 
> Tip: don't forget to run composer dump-autoload afterwards

I think this solution need to add documentation

**Comment by dcblogdev** [comment]
> I think this solution need to add documentation

Its in the README the installation page and upgrade page of the docs already.

<img width="1828" height="840" alt="Image" src="https://github.com/user-attachments/assets/4069f75b-7215-4dec-9a62-ee7e74b31f19" />

<img width="1454" height="1070" alt="Image" src="https://github.com/user-attachments/assets/204190e2-ecb0-4886-ac38-710128560e21" />

<img width="1490" height="908" alt="Image" src="https://github.com/user-attachments/assets/8b4b84f9-c431-4bf0-936a-573cf263925b" />

**Comment by AliYazdanifar** [comment]
If you still have a problem, follow my workaround, I fixed it 
I made a small mistake that caused this error 
I put it like this in composer.json by mistake 

`"extra": {
        "laravel": {
            "dont-discover": [],
            "merge-plugin": {
                "include": [
                    "Modules/*/composer.json"
                ]
            }
        }
    }, `

While we have to put this part in this way 
`"extra": {
        "laravel": {
            "dont-discover": []
        },
        "merge-plugin": {
            "include": [
                "Modules/*/composer.json"
            ]
        }
    }, `

And now the problem is solved
There is no need for this section 
 "Modules\\": "modules/"

from v11.0 autoloading "Modules\\": "modules/", is no longer required, and should be removed from your composer.json if present.

**Comment by Quantumben** [comment]
Thank you i will update the doc
