### ISSUE TITLE
Unable to load Module assets

### ISSUE THREAD

**Issue by jakecorn** [nWidart/laravel-modules#284]
hi, I would like to know if how to load an asset in same module and from other module.

This is my file structure.
Modules/Teacher/Assets/js/script1.js
Modules/Contact/Assets/js/script2.js

1. I like to load assets from same module to this view Module/Teacher/Resources/views/master.blade.php.

2. I like to load assets from Teacher module in Module/Contact/Resources/views/master.blade.php.

Thank you.

**Comment by nWidart** [comment]
This is explained in the docs.

Use the Module:: facade.

**Comment by fdeployer** [comment]
@nWidart I tried: `Module::asset('blog:img/logo.img');` but where do you store the assets?

My folder struct is: `Modules/xModule/Assets/js/`, it has a file `module.js` in it.

I've tried:
- `Module::asset('blog:Assets/js/module.js');`
- `Module::asset('blog:js/module.js');`

it gives back 
- `//a.com/modules/cardManager/Assets/js/module.js`
- `//a.com/modules/cardManager/js/module.js`

But it just can't be found.

**Comment by nWidart** [comment]
Did you publish your assets?

**Comment by fdeployer** [comment]
@nWidart Yes, that solved it. =)
