### ISSUE TITLE
Error in artisan commands for Laravel 5.5.*

### ISSUE THREAD

**Issue by SpringAutumn** [nWidart/laravel-modules#285]
Hi, I use `Laravel 5.5` for my project. There are errors when I execute any artisan commands defined in `laravel-modules`, with errors as follows:
```
 [ReflectionException]                                                 
  Method Nwidart\Modules\Commands\MakeCommand::handle() does not exist  
```
Seems that it is a bug in Laravel 5.5, workaround in [this link](https://laracasts.com/discuss/channels/laravel/tinkercommandhandle-does-not-exist) works.

**Comment by nWidart** [comment]
That seems to requires to edit a vendor file, which should never be done.


@wittonzhao has a work with a workaround. https://github.com/wittonzhao/laravel-modules/commit/c282a6095c8521710ee8b9fbec02230844df3526

However, I plan to add a new master branch that will be for 5.5, and a 5.4 branch that will be for 5.4 and below.

This will allow to completely rename the handle method to fire.

**Comment by nWidart** [comment]
Laravel 5.5 support is ready on master branch.
