### ISSUE TITLE
Issue publishing assets  and resources while development phase.

### ISSUE THREAD

**Issue by lokeshyadav88** [nWidart/laravel-modules#287]
Resources and assets are not getting copied when we publish module. Previously published fiiles persist in the public and main resource folder.

**Comment by dhirendradaffodil** [comment]
I am facing the same issue..please suggest if we are doing wrong

**Comment by nWidart** [comment]
Hello,

I just tested this again, and I can't reproduce this.

What I did:

- Adding an asset in Modules/Blog/Assets/js/myjs.js
- ran `php artisan module:publish Blog`
- saw the file published in `public/modules/blog/js/myjs.js`

**Comment by dhirendradaffodil** [comment]
But when we update again Modules/Blog/Assets/js/myjs.js  and then publish module it will not reflect the updated   changes here public/modules/blog/js/myjs.js

**Comment by nWidart** [comment]
I changed the content of my js file, published the module, and the change was in public.

Are you sure phpstorm or your IDE isn't caching it ?

**Comment by dhirendradaffodil** [comment]
I have already checked the file in the different editors.

**Comment by nWidart** [comment]
It can only be that kind of issue. Try to open in via the finder etc.
