### ISSUE TITLE
Call lang of module not working

### ISSUE THREAD

**Issue by raank** [nWidart/laravel-modules#288]
I had called the function `dd( \Lang::get( 'products::table.action' ) );`, but not working.

My module lang file:

**App/Products/Resource/lang/table.php**:

`return [
    'action' => 'Ação'
];`

what this problem?

**Comment by nWidart** [comment]
Did you tell laravel to find translations in that folder ?

**Comment by raank** [comment]
Disregard.

I did not insert it in the language folder.

I so sorry;

Thanks for your help
