### ISSUE TITLE
Module Test

### ISSUE THREAD

**Issue by ayolana** [nWidart/laravel-modules#294]
How can create and run test for each of the modules i generate?

Can I also use Laravel dusk on each?

**Comment by nWidart** [comment]
You can run tests as any laravel app or package for that matter.

I wouldn't sugges running dusk inside a module as per definition dusk is an integration test.

**Comment by ayolana** [comment]
Okay thanks for the feedback.

I noticed each generated Module created comes with a Test Directory.

Running php artisan make:test *UserTest* dumps the test file into the base Test directory. 

Is there a command to dump each test into a generated Module Test Directory or do i have to copy it into the Test directory of the generated Module directory?

**Comment by nWidart** [comment]
There is no command for this for modules. You can just create tests manually in your module.

**Comment by ayolana** [comment]
Thanks
