### ISSUE TITLE
How to add composer requirements

### ISSUE THREAD

**Issue by xtf1** [nWidart/laravel-modules#298]
It pulls the whole requirements for asgardcms to the module vendor dir.

**Comment by nWidart** [comment]
if you plan on re-using your module: module composer.json file + main composer json file

if not: main composer json file only.

**Comment by nWidart** [comment]
That's not true https://github.com/nWidart/laravel-modules/blob/1.0/src/Commands/stubs/composer.stub

You might be talking about asgardcms, which does add those.

Glad you found the solution. 👍
