### ISSUE TITLE
When will the version 2.0 for laravel 5.5 be released?

### ISSUE THREAD

**Issue by bvcvb** [nWidart/laravel-modules#299]
When will the version 2.0 for laravel 5.5 be released?

**Comment by nWidart** [comment]
when laravel 5.5 is released.

**Comment by nmedelmehdi** [comment]
Larael 5.5 is released now :) https://laravel.com/docs/5.5/releases

**Comment by nWidart** [comment]
No it's not. It'll be released during/after laraconeu.

**Comment by nWidart** [comment]
- https://twitter.com/taylorotwell/status/896126845116006400
- https://twitter.com/taylorotwell/status/897492281275691008
- https://twitter.com/taylorotwell/status/898006493211054080
