### ISSUE TITLE
Does it work for Laravel 5.2?

### ISSUE THREAD

**Issue by teddywest32** [nWidart/laravel-modules#3]
Hello @nWidart it is nice to hear that you are contributing to a modular approach. :+1:  
I have a question that does this module works on Laravel 5.2 and will it be supporting the upcoming 5.3 version? 
Thanks for the good work.

**Comment by nWidart** [comment]
Hello,

Thanks for the kind words! 

It indeed supports laravel 5.2 currently, and I will add 5.3 support asap when it comes out. AsgardCMS will be upgrading to 5.3 so I have every reason to make this compatible. 😄 

What it doesn't support, yet, is 5.1, which I should do at som point, I'm pretty sure it actually does, but I just locked the composer.json file to 5.2.

**Comment by teddywest32** [comment]
@nWidart Thanks for the support. ;) Hope we can work without any worries :)
