### ISSUE TITLE
making a dynamic sidebar for modules

### ISSUE THREAD

**Issue by moeinrahimi** [nWidart/laravel-modules#30]
hi how can i make a dynamic sidebar for modules so it gets module names and routes then make anchor tags in sidebar dynamic?
any idea how to do this ?
i thin i shoud use config files for each modules and save my data, then retrive it? but how get all module's config data

**Comment by nWidart** [comment]
Hi,

This isn't related to this package. It's up to your to develop that feature.
On AsgardCMS [laravel-sidebar](https://github.com/maatwebsite/laravel-sidebar) is used.

**Comment by moeinrahimi** [comment]
thanks for quick reply !
one mor thing how can i loop through configs ?
like this : 
``` blade
@foreach(Module::enabled() as $module)
{!! config($module.name) !!}
@endforeach

i'm stuck at config section don't know how to pass variable via string

**Comment by mirkokroese** [comment]
You can get the name from the module and append the rest of the config key to it within the config helper.
Like so:
`{!! config($module->getLowerName() . '.name') !!}`
