### ISSUE TITLE
trans publish folder

### ISSUE THREAD

**Issue by chieftaha** [nWidart/laravel-modules#301]
Hi, I'm a bit new to your great package. 

I've published my module language files with the artisan command:
`module:publish-trans [module-name]`

I'm wondering why the trans files are being copied  in "_resources/lang/[module-name]/[lang]/[file]_", instead of "_resources/lang/**vendor**/[module-name]/[lang]/[file]_" as laravel suggests for [Overriding Package Language Files](https://laravel.com/docs/5.4/localization#overriding-package-language-files).

Is there any technical explantation, or am I missing something?

**Comment by nWidart** [comment]
Hi,

No real reason no.

**Comment by chieftaha** [comment]
Thank you for your prompt reply. Since I didn't find a way to use the published files, I suggest a very small change. I will create a pull request for that, in case you are interested.
