### ISSUE TITLE
Create multi controller via module:make

### ISSUE THREAD

**Issue by abdullahtekin** [nWidart/laravel-modules#302]
I want to create multi controller more than one. How can I do make a file name dynamic variable?

```php
<?php
'stubs' => [
        'path' => base_path() . '/stubs',
        'files' => [
            'controller-admin' => 'Http/Controllers/'.$STUDLY_NAME$.'AdminController.php',
        ],
        'replacements' => [
            'controller-admin' => ['STUDLY_NAME', 'MODULE_NAMESPACE', 'LOWER_NAME'],

        ],

];
```

```
'controller-admin' => 'Http/Controllers/'.$STUDLY_NAME$.'AdminController.php',
```

**Comment by nWidart** [comment]
You want the scaffold to create multiple controllers? That's not possible with that command.

However, it's easy for you to wrap that command in a custom command you make to add everything you need custom in a module.

**Comment by abdullahtekin** [comment]
👍 
How will I do custom command? :(

**Comment by nWidart** [comment]
The docs are a good start. https://laravel.com/docs/5.4/artisan#writing-commands

**Comment by abdullahtekin** [comment]
Thanx for support, I am newbie of L5
