### ISSUE TITLE
Can not add middleware auth together with web in route group

### ISSUE THREAD

**Issue by jakecorn** [nWidart/laravel-modules#304]
Hi sir,

Please help me about this problem with my codes below. Im using nwidart module. What I want is to implement authentication using auth middleware in my route::group()

 Route::group(['middleware' => ['web','auth'], 'prefix' => 'teacher', 'namespace' => 'Modules\Teacher\Http\Controllers'], function()
{
    Route::get('/setsession', 'TeacherController@index');
    Route::get('/', 'TeacherController@getClassRecordList')->name('getClassRecordList');
});

In the code above, when I access directly the route **getClassRecordList** without logging in I will be redirected to login,this is OKAY the route is secured. 
When I successfully logged in I will be redirected also to route **getClassRecordList**  but after reloading the page I will be redirected to login and can not access  the route **getClassRecordList**. I have to log in again.

The code below is working when I remove the auth in the middleware, everything works fine but no authentication. 

 Route::group(['middleware' => 'web', 'prefix' => 'teacher', 'namespace' => 'Modules\Teacher\Http\Controllers'], function()
{
    Route::get('/setsession', 'TeacherController@index');
    Route::get('/', 'TeacherController@getClassRecordList')->name('getClassRecordList');
});

Please help me.

Thank you.

**Comment by nWidart** [comment]
Hello,

This seems to be an issue with your application itself.

Some things to consider:

- Make sure your middleware only returns the redirect when needed
- Make sure you're storing your sessions correctly
