### ISSUE TITLE
Generator to generate multiple view master files

### ISSUE THREAD

**Issue by Laipak** [nWidart/laravel-modules#305]
Currently, we could set how it should generate the view path/file under _config/modules.php_.

Is it possible to have it generate multiple master views, let say a back-end and a front-end master view:

`'views/master' => [`
`    'Resources/views/layouts/back-end/master.blade.php',`
`    'Resources/views/layouts/front-end/master.blade.php',`
`]`

**Comment by nWidart** [comment]
Hello,

Not out of the box no. 
This is similar to https://github.com/nWidart/laravel-modules/issues/302#issuecomment-323855435

Where can easily create a custom command and wrap the module:make inside it.
