### ISSUE TITLE
Module Migration ordering?

### ISSUE THREAD

**Issue by LukeArthurs** [nWidart/laravel-modules#306]
Is there a way to determine the order in which the migrations are ran?
For instance when modules are have foreign keys towards each other.

The behavior I see now is that it goes in order of directory name.

**Comment by LukeArthurs** [comment]
Thanks for the info! It was indeed the order key in the module.json.
The timestamp doesn't matter anymore when it comes to module migrations since they're ordered by id in the database.

And I figured that foreign keys between modules isn't the way its supposed to be used but I have a unique situation where its kind of a must.

Thanks you!

**Comment by cristenicu** [comment]
The migrations should be run only ordered by their timestamps regardless the order of modules. Is this implemented?

Let's take a simple example with some migrations:
```
ModuleA
   1_create_users_table
   3_add_user_profile_foreign_key
ModuleB
   2_create_users_profile_table
```
The order should be `1, 2, 3` but with current implementation are executed in order `1, 3, 2`. And this is wrong.

**Comment by iamriajul** [comment]
I think the migration should honor the `requires` value in `module.json` file:
![image](https://user-images.githubusercontent.com/24244379/142396782-f8efbb40-d946-4133-995c-66d401f4711f.png)
