### ISSUE TITLE
Multiple stubs and wrong replacements

### ISSUE THREAD

**Issue by webmake** [nWidart/laravel-modules#308]
Hello,

I noticed cool feature to generate custom named stubs as I want, but (similar to https://github.com/nWidart/laravel-modules/issues/305) makes sense to generate api.php and web.php for routes as laravel does (https://github.com/laravel/laravel/blob/master/routes/api.php and https://github.com/laravel/laravel/blob/master/routes/web.php), but encountering with error
```
local.ERROR: ErrorException: Array to string conversion in /project/vendor/nwidart/laravel-modules/src/Generators/ModuleGenerator.php:303
```

Second issue related also with custom files, for example defining in `files` [array](https://github.com/nWidart/laravel-modules/blob/1.0/config/config.php#L29) `'route-provider' => 'Providers/RouteServiceProvider.php',` (turning on existing stub), in stub used variables [`$NAME$` and `$MODULE$`](https://github.com/nWidart/laravel-modules/blob/1.0/src/Commands/stubs/route-provider.stub#L3) have no replacements. For name could be used STUDLY_NAME, but MODULE I see is generated only via commands in [generateResources](https://github.com/nWidart/laravel-modules/blob/1.0/src/Generators/ModuleGenerator.php#L263). I understand there exists command for route provider, but it doesn't work with files array, so it is not customizable as we need.. So I think missing one command `getModuleReplacement` which could take ir from input

**Comment by nWidart** [comment]
Hi,

I'm not sure I follow. But the first error is because you tried to pass an array where it should be a string.

Besides that I recommend wrapping the command within a custom command with your custom stuff. As explained https://github.com/nWidart/laravel-modules/issues/302#issuecomment-323855435
