### ISSUE TITLE
Question: Vue components and JS dependencies per module

### ISSUE THREAD

**Issue by flaviomsb** [nWidart/laravel-modules#309]
First of all, let me tell you that I cannot remember a time I was so excited about a library like now. Man, 1000 times kudos!

My question is about JS components. I am assuming I can have a _package.json_ per module along with a _webpack.mix.js_ per module right? Just in case, do you have a little tutorial, article or some hints on how should I handle my Vue components per module? I am envisioning the fantastic possibility of having the components also isolated in a per module basis.

Thanks in advance.

**Comment by mikemand** [comment]
Hi @flaviomsb,

What I do is create some directories in the module's `Resources` directory. `js`, `sass` (or `less`),  etc. This is where you would put your unprocessed assets. You could then use Mix to process them into the `Assets` directory (`Assets/js`, `Assets/css`, etc.) and then publish them whichever way works best for your development process.

I personally don't keep processed assets in version control, but other people do. I don't think there is a _wrong_ way to do it.

**Comment by flaviomsb** [comment]
Hi @mikemand 

Thanks a lot for your comments. I will precisely do what you say (I don't version control processed assets either).

F

**Comment by marcelogarbin** [comment]
Olá @flaviomsb  você está usando o Vue.js com esse pacote? Se sim, Qual sua experiência até aqui?
