### ISSUE TITLE
Can't run command : php artisan module:migrate-refresh --database=testing

### ISSUE THREAD

**Issue by BhagiLimbu** [nWidart/laravel-modules#311]
When I run artisan command on, its throw an exception - 

Command : php artisan module:migrate-refresh --database=testing

Exception: 
 [Nwidart\Modules\Exceptions\ModuleNotFoundException]  
  Module [] does not exist! 

In documents site, it mention support a module:migrant-refresh command. Any idea why its throw an exception ? 

Thank you.

**Comment by nWidart** [comment]
This is a duplicate of #297
