### ISSUE TITLE
I created a module named "Testing" and when tried to start server I got this serror "Class 'Modules\Testing\Providers\TestingServiceProvider' not found in "

### ISSUE THREAD

**Issue by TaranjeetSinghWri** [nWidart/laravel-modules#312]
I am using laravel 5.4

- I just created a new project and followed the instruction from [https://nwidart.com/laravel-modules/v1/installation-and-setup](url)

- if have updated the composer.json file as {
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Modules\\": "Modules/"
    }
  }
}

- Then create a module named "Testing" with command `php artisan module:make Testing`

- Then when I tried starting server with `php artisan serve` I got following error

`Class 'Modules\Testing\Providers\TestingServiceProvider' not found in D:\xampp_new\htdocs\test_case\testing\vendor\laravel\framework\src\Illuminate\Foundation\Application.php on line 612`

`[Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Modules\Testing\Providers\TestingServiceProvider' not found`

**Comment by TaranjeetSinghWri** [comment]
composer dumpautoload also tried but error not resolved.

**Comment by nWidart** [comment]
Hi,

Are you sure that file exists?
If it does, then it's for sure an autoloading issue with composer.
