### ISSUE TITLE
Suppresed failures does not inform about module commands failures

### ISSUE THREAD

**Issue by webmake** [nWidart/laravel-modules#313]
Hello,
There is a bug, which prevents from not informing about failed seeds, for example, having any kind of error in sql, running in tests this:
`$this->artisan('module:seed');`
exit status is supressed and echoed as 0. https://github.com/nWidart/laravel-modules/blob/1.0/src/Commands/SeedCommand.php#L47
To check exit status you can use
`echo $?`

If you pay attention, here is how laravel handles exit statuses at any exception https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Console/Kernel.php#L128

**Comment by webmake** [comment]
More over:
```
$ php artisan module:seed notExists
Module [NotExists] does not exists.

$ echo $?
0
```
by adding   `throw  $e;` in mentioned file, output as expected:
```
$ php artisan module:seed notExists
Module [NotExists] does not exists.

                                       
  [RuntimeException]                   
  Module [NotExists] does not exists.  
                                      
$ echo $?
1
```

**Comment by nWidart** [comment]
Sorry for the late reply, this has finally made it in. 🎉 

Will be for `2.4`.

Thanks for reporting the suggestion!
