### ISSUE TITLE
Where do models go? 

### ISSUE THREAD

**Issue by kirkaracha** [nWidart/laravel-modules#314]
Where do models go? Database or Repositories, or somewhere else?

I put them in Repositories using this logic:

Database = putting stuff into the database
Repositories = getting stuff out

Thanks!

**Comment by deividaspetraitis** [comment]
Models in laravel is so called "Entities" and I think it should go to Entities directory. Database folder mostly is used for seeders and migration files.

**Comment by nWidart** [comment]
Indeed.
You're free to use any structure you like. There isn't one good answer for this.
