### ISSUE TITLE
How and where should I register new artisan commands?

### ISSUE THREAD

**Issue by carlosrgzm** [nWidart/laravel-modules#315]
Hi, I've used `module:make-command` for creating a new artisan command in my application (php artisan module:make-command CreatePostCommand Blog), but if I do `php artisan` my new command does not appear in the list. 

If I go to Kernel.php under app/Console/ and add my generated command class to `protected $commands =[]` it's working fine, so my question is: Is there any way to register my commands inside the module in which I'm working or should I register in Kernel.php file ?

Thanks,

**Comment by nWidart** [comment]
Hi,

You can do that in your module service provider with the `$this->commands()` method.
