### ISSUE TITLE
Error when creatin module

### ISSUE THREAD

**Issue by zimbar** [nWidart/laravel-modules#316]
Hy,
I create a first module with this command "php artisan module:make Sale", the module was created and all is ok, after I wanted to create another module "php artisan module:make Purchase" but i get an error "  Call to undefined function Modules\Sale\Providers\resource_path()  ". Do you  have an idea of what is wrong.

Thanks

**Comment by nWidart** [comment]
What version of laravel are you using?

**Comment by zimbar** [comment]
laravel 5.1

**Comment by nWidart** [comment]
Ah ok that explains it. You'll have to use an older version for that, I'm not sure which one but you can try to go down versions until it works.

**Comment by zimbar** [comment]
ok thanks, i will try.

**Comment by jonjie0317** [comment]
@nWidart I'm facing this issue right now. I tried to use the `1.19` version but still showing the error. In my previous project, I used the laravel 5.1 version and `1.19` modules version but working.
