### ISSUE TITLE
[ASK] Laravel 5.5

### ISSUE THREAD

**Issue by krizztianz** [nWidart/laravel-modules#318]
Hey @nWidart 
I just migrated to Laravel 5.5, and it seems your package doesn't compatible yet with Laravel 5.5?
Is it true?

I tried to make new module but getting this error instead

```
$ php artisan module:make Core
  [ReflectionException]
  Method Nwidart\Modules\Commands\MakeCommand::handle() does not exist
```

**Comment by nWidart** [comment]
It's compatible with 5.5, you need to use version 2 as explained in the docs.
However it's not tagged yet.

**Comment by jakobploens** [comment]
@krizztianz you need to give the explicit version in your composer.json:

```
"require": {
    "nwidart/laravel-modules": "2.0.x-dev"
},
```

**Comment by krizztianz** [comment]
Oke bro...
Thanks for the info :)

**Comment by nWidart** [comment]
Version 2 has been tagged so no more need to use the 2.0.x-dev
