### ISSUE TITLE
[SUGGESTION] GenerateResourceCommand

### ISSUE THREAD

**Issue by jjsquady** [nWidart/laravel-modules#320]
A new artisan command comes with 5.5 version. **make:resource**.

This suggestion aims to include a new module command: **module:make-resource**, that creates a new **Resource** object in \Http\Resources folder inside a module.

DOC: https://laravel.com/docs/5.5/eloquent-resources

Nice work! I love it this package.
Cya!

**Comment by nWidart** [comment]
Good idea! 👍

**Comment by nWidart** [comment]
Added for 2.4 👍
