### ISSUE TITLE
The composer.json of all modules is not being updated.

### ISSUE THREAD

**Issue by morningmemo** [nWidart/laravel-modules#321]
[spec]
laravel 5.5
laravel-modules 2.0.x-dev

when i typed msg : 'php artisan module:update' in root, composer.json in all modules is not being updated and i only saw msg : 'Module [Api] updated successfully.'.

how can i update all modules ?

**Comment by nWidart** [comment]
I don't think that possible currently.

Also please update to stable 2.0 release, that was tagged last week. 😄

**Comment by morningmemo** [comment]
thanks @nWidart!

https://github.com/pingpong-labs/modules#auto-scan-vendor-directory

"
Update dependencies for all modules.
php artisan module:update
"

It's possible on base project of this project.
would you have any plans to add this feature?

**Comment by nWidart** [comment]
Easiest for this would be to just run the usual composer update. As module update will add the module dependencies to the main composer.json file.
