### ISSUE TITLE
But the interesting is that in the route list the routes the id is not declared.

### ISSUE THREAD

**Issue by ByJacoB27** [nWidart/laravel-modules#323]
Hello,
But the interesting is that in the route list the routes the id is not declared.

| | DELETE | users/{} | users.destroy | Modules\Auth\Http\Controllers\UsersController@destroy | web,role:admin |
| | PUT|PATCH | users/{} | users.update | Modules\Auth\Http\Controllers\UsersController@update | web,role:admin |
| | GET|HEAD | users/{} | users.show | Modules\Auth\Http\Controllers\UsersController@show | web,role:admin |
| | GET|HEAD | users/{}/edit | users.edit | Modules\Auth\Http\Controllers\UsersController@edit | web,role:admin

Regards

**Comment by nWidart** [comment]
Looks like you didn't define the routes as they should.

**Comment by ByJacoB27** [comment]
Route::group(['middleware' => ['web','role:admin'], 'as' => 'users.' ,'prefix' => 'users', 'namespace' => 'Modules\Auth\Http\Controllers'], function()
{
Route::resource('/', 'UsersController');
});
thanks for reply but
this is my routes

**Comment by nWidart** [comment]
I can only suggest to read up on the laravel documentation, something must be missing.
