### ISSUE TITLE
How to create another directory beside of Modules like Core which the 2 are working?

### ISSUE THREAD

**Issue by ardnor** [nWidart/laravel-modules#324]
Hi @nWidart 

How to create another directory beside of Modules like Core which are the 2 are working?

I hope it will work and supported.

Thank you. 

Best Regards,

Ardnor

**Comment by nWidart** [comment]
Hi,

This isn't related to this package. 
You can create as module directories as you want, by using composer autoloading.
Just register your directory in your composer.json file.
