### ISSUE TITLE
Add make-test command to module

### ISSUE THREAD

**Issue by savander** [nWidart/laravel-modules#325]
I suggest adding make-test command to package. 

the only thing to change by hand would be `PHPUnit.xml`

```xml
        <!-- Modules tests -->
        <testsuite name="Modules Features">
            <directory suffix="Test.php">./Modules/*/Tests/Feature</directory>
        </testsuite>

        <testsuite name="Modules Unit">
            <directory suffix="Test.php">./Modules/*/Tests/Unit</directory>
        </testsuite>
```

**Comment by nWidart** [comment]
I don't see this being a good idea to edit the main phpunit file. Not everyone has the same setup.

**Comment by savander** [comment]
I don't want force you to modify that file, but to make information in the documentation, about information that you can do it that way. + Command to make tests easier and faster :)

**Comment by nWidart** [comment]
I see, adding documentation about it is probably a good idea.

I'm not against adding a command to create a test, though that doesn't really add much since a test is pretty much a class, extending phpunit.

**Comment by savander** [comment]
Yeah, but it would be still a nice, to have possibility to generate test like for a regular Laravel app : )

**Comment by nWidart** [comment]
Added for `2.4`. 👍
