### ISSUE TITLE
Support for factories inside module

### ISSUE THREAD

**Issue by savander** [nWidart/laravel-modules#326]
Since Laravel 5.5 added convention to split factories by name and class, for example: `UserFactory.php`.
I suggest adding a new directory to a module called Factories and command to make a factory.

**Comment by nWidart** [comment]
This is already possible.

**Comment by savander** [comment]
It isn't, actually that line: https://github.com/nWidart/laravel-modules/blob/master/src/Commands/stubs/scaffold/provider.stub#L98

is wrong written, I found it now. should be
` app(Factory::class)->load(__DIR__ . '/../Database/factories');`
because that file is in `Providers` folder

**Comment by IllyaMoskvin** [comment]
For the record, this has been fixed by commit https://github.com/nWidart/laravel-modules/commit/b518826819cd8423c95a2fc19e5fff80cc0b4d0c.
