### ISSUE TITLE
Add trait for refreshing database for tests. 

### ISSUE THREAD

**Issue by savander** [nWidart/laravel-modules#327]
I suggest adding trait `RefreshDatabase` for tests. 
With package commands: `module:migrate-refresh` ( or` fresh`, but not exists at the moment)
https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Testing/RefreshDatabase.php

**Comment by nWidart** [comment]
You can have this with laravel or orchestra/testbench.

**Comment by savander** [comment]
Yes, but does these command will execute migrations from modules?

**Comment by nWidart** [comment]
Hm they should. I migrate modules with orchestra/testbench. I'd have to check for the refreshes databases trait.

**Comment by savander** [comment]
`php artisan migrate` says nothing to migrate, since `php aritsan module:migrate` will migrate things from modules. 
That's why I'm asking for a trait, which could be used in Tests ( like laravel's RefreshDatabase trait)
Laravel's `Tests` classes extend `TestCase` class, which should be also a bit modified to accept additional Trait ( with custom `RefreshDatabase` trait that will run `php artisan module:migrate`).  
At the moment, `TestCase` will implement their own RefreshDatabase instead of that from package.

**Comment by nWidart** [comment]
Did you add `this->loadMigrationsFrom` in your module SP?

I can migrate modules with php artisan migrate since 5.5

**Comment by savander** [comment]
Hmm, probably not. Where exactly?

**Comment by nWidart** [comment]
in the boot method of your module service provider.

``` php
$this->loadMigrationsFrom(__DIR__ . '/../Database/Migrations');
```

**Comment by savander** [comment]
Cool, works :)

So maybe, we should add that line by default? Or it's intended to not be included?

**Comment by nWidart** [comment]
That could indeed be a good idea. 😄

**Comment by savander** [comment]
Great :)

**Comment by nWidart** [comment]
Pushed this on `master` branch.
