### ISSUE TITLE
Module config is not working after publish

### ISSUE THREAD

**Issue by ardnor** [nWidart/laravel-modules#329]
I tried to published the config using this command 

> php artisan module:publish-translation

 and call my config key using this code

>  dd(trans("employee::test.key")); also I tried \Lang::get("employee::test.key")

but it only display

>  "employee::test.key"

but if I copy the module name inside the vendor folder in **view/lang/vendor/employee/{locale}** and also added locale. It well work. 

Note: I am using **php7.0** and **laravel5.5**

Please advise where I get wrong.

Thanks.

Best Regards,

Ardnor

**Comment by nWidart** [comment]
That probably means you didn't tell laravel to merge the published configuration with your module configuration. You can view how to do this in the laravel docs.
