### ISSUE TITLE
Why don't  you use the package in AsgardCMS?

### ISSUE THREAD

**Issue by mahmutbayri** [nWidart/laravel-modules#33]
Hi Nicolas,
We use AsgardCMS as custom configured. Could we use this package instead of pingpong/module (which is not provided from you).

Do you plan to implement this package to AsgardCMS?

Thanks.

**Comment by armababy** [comment]
It is used in AsgardCMS v2.

**Comment by nWidart** [comment]
It is indeed used in AsgardCMS v2.

And if you look closely to your v1 composer.json file, it also uses a forked version of pingpong/modules.
