### ISSUE TITLE
Prevent disabling module

### ISSUE THREAD

**Issue by i960** [nWidart/laravel-modules#331]
I would like to see a feature where you can prevent individual modules from being disabled.  In the app I'm building, I have a core module, and it provides functionality that the app cannot work without.  I also have modules that depend on other modules to function.  I know you can just not modify the module.json file, or not run php artisan module:disable.  But silly mistakes sometimes happens.

My suggestion is to add a new key to module.json called "protected".  You can set it to 0 by default so modules can be enabled or disabled, and nothing changes unless you want it to.  If you set it to 1, then DisableCommand.php will check that, and skip disabling the module.  It's just an extra layer of protection, so you have to be very deliberate if you want to disable a module.

As a work around, I found I can set the module.json file to read only, but that is a hacky way of doing it.  Another way I did it was to create my own DisableDisableCommand that extends yours, uses the same signature, and the just prints out "This command is not allowed".  It's also a hacky way of doing this.  I think this would be a useful feature to have in the package itself.

**Comment by nWidart** [comment]
This is up to you to do, not the package.

AsgardCMS does this for example. It prevents disabling any of the core modules provided.

**Comment by jjth** [comment]
For those wondering, below solution works to block the "module:disable" artisan command for specific modules:

Create app/Console/Commands/DisableModuleCommand.php
```
<?php

namespace App\Console\Commands;

use Nwidart\Modules\Commands\DisableCommand;

class DisableModuleCommand extends DisableCommand
{
    /**
     * Execute the console command.
     */
    public function handle()
    {
        $module = $this->laravel['modules']->findOrFail($this->argument('module'));

        if ($module->get('required') === true) {
            return $this->comment("Module [{$module}] cannot be disabled.");
        }

        if (!$module->enabled()) {
            return $this->comment("Module [{$module}] has already disabled.");
        }

        $module->disable();
        $this->info("Module [{$module}] disabled successful.");
    }
}
```

This will override the existing module:disable command.

Then add ``"required": true`` in the module.json of the modules you don't want to be disabled.
