### ISSUE TITLE
Artisan make listener or event - Module [] does not exist!

### ISSUE THREAD

**Issue by marcelogarbin** [nWidart/laravel-modules#334]
Hello,

I can not create events or listeners. I get the following error:

![Alt text](https://i.imgur.com/tWf9rIT.png)

P.S .: Other commands are working normally.

**Comment by nWidart** [comment]
Hm strange, I can't reproduce this.
Also the test https://github.com/nWidart/laravel-modules/blob/master/tests/Commands/GenerateEventCommandTest.php where it specifically sets a module passes.

**Comment by marcelogarbin** [comment]
I believe I discovered the problem, I changed the application folders. All folders contained in "app" I created a subfolder called "Core". The path was "app/Core".

my composer.json:
```
"psr-4": {
 "App\\": "app/Core/",
 "Modules\\": "app/Modules/"
}
```

Strange that the commands create module, request, model, migration, etc ... They work, however the make-event or listener command does not. I'm trying to figure out what happened. Or do I have to use the default folder structure?

My Structure:
![Alt text](https://i.imgur.com/Np1Mm2G.png)

**Comment by marcelogarbin** [comment]
Update composer.json to:
```
"psr-4": {
            "App\\": "app/",
            "Helpers\\": "app/Helpers/",
}
```
I updated all namespace files within "app/Core/". It worked. Problem solved. Thank you

**Comment by nWidart** [comment]
ah nice good to know. :)

**Comment by guicara** [comment]
Hello,

I have also the following error message when I use the `module:make-even` command:

```
  [RuntimeException]
  Unable to detect application namespace.
```

I have deleted the default "app" folder created by Laravel because I have created a "Core" module.

Other commands are working normally.

**Comment by nWidart** [comment]
Hi, 

Please don't delete the app folder. Laravel needs that.

**Comment by guicara** [comment]
You're right. Since Laravel 5.3 it seems that the "app" directory is hardcoded in the `Application::path()` method...

```
    /**
     * Get the path to the application "app" directory.
     *
     * @param string $path Optionally, a path to append to the app path
     * @return string
     */
    public function path($path = '')
    {
        return $this->basePath.DIRECTORY_SEPARATOR.'app'.($path ? DIRECTORY_SEPARATOR.$path : $path);
    }
```

**Comment by wnsgaurav** [comment]
I have no name!@f01ed16470c7:/var/www/html$ php artisan module:make-seed App SeederClassName

In FileRepository.php line 396:

  Module [SeederClassName] does not exist!
