### ISSUE TITLE
Laravel 5.5 - Route resourceVerbs

### ISSUE THREAD

**Issue by marcelogarbin** [nWidart/laravel-modules#336]
After upgrading to the version of Laravel 5.5, I noticed that the Route::resourceVerbs function stopped working.
Note: I did a clean installation to test.

AppServiceProvider.php (https://laravel.com/docs/5.5/controllers#restful-localizing-resource-uris)
```
public function boot()
    {
        //
        Route::resourceVerbs([
            'create' => 'criar',
            'edit' => 'editar',
        ]);
    }
```

**Comment by nWidart** [comment]
I've never used that method myself. But if it stopped working it's most likely due to a change in laravel, as this package doesn't do anything to the routes.

**Comment by marcelogarbin** [comment]
Probably, I would like to migrate to 5.5, but I still do not know if the time is right. In my project with Laravel 5.4 it is working normally.

**Comment by nWidart** [comment]
I'll close this for now.

**Comment by marcelogarbin** [comment]
@nWidart I started a new project with Laravel 5.5, and this "problem" has surfaced. I ended up finding out what happens, but I still do not understand why it happens.
I did according to the documentation without your package: https://laravel.com/docs/5.5/controllers#restful-localizing-resource-uris
Until then it worked accordingly, but when I installed laravel-modules, the translations were not accepted on the new routes.
I tested the module service provider boot and there it has the right parameters of the resourceVerbs function. But when it passes to the "register()" method they are again swapped by default.
To resolve this I did the following, instead of adding the "Route::resourceVerbs" function inside the "boot()" method of AppServiceProvider, I put it inside the "register()", and this worked. But I did not understand why. Being that in the Laravel documentation is to add inside the "boot()".

I don't know if I can be clear.

**Comment by rockymontana** [comment]
I’m not 100% sure, but I believe it’s like this:

When the ServiceProvider is instanciated it’ll run the register function, then it runs the the rest of the stuff in the application. This means that when the router stuff is instanciated it haven’t run the boot method yet, and therefor it doesn’t know about your change. The boot method run when instanciating the module stuff which is done later in the process.

Note that I’m not a 100% super mega sure about this. But it seems logical to me :)

**Comment by marcelogarbin** [comment]
@rockymontana I will not contest what you wrote, because I am not knowing the background of the functioning of the framework yet.
But I did 2 tests with clean installations.
With Laravel 5.4 + Laravel-modules v1, I did the basics here: https://laravel.com/docs/5.4/controllers#restful-localizing-resource-uris
Worked perfectly.

But when I did the Laravel 5.5 + Laravel-modules v2 test following the same logic: https://laravel.com/docs/5.5/controllers#restful-localizing-resource-uris
It did not work, so I had to by the "Route::resourceVerbs" function inside the "register()" method to work.

It seems that with version 5.5, when starting the provider and reaching the module provider, it is overwriting when starting the "register()" method, even though it is empty.

You can test what I am saying by following what I said.

By logic I understand that the provider should respect what is added in the "boot()" method, because it will be the first one to be called, or not?

I still believe something is overwriting what is added from the `AppServiceProvider.php` -> `public function boot(){}` after being called the serviceproviders of the modules.

I don't know more than that...

**Comment by rockymontana** [comment]
No. register() runs before boot().
Hold, I’ll show you from the docs

**Comment by rockymontana** [comment]
https://laravel.com/docs/5.5/providers

“The Boot Method
So, what if we need to register a view composer within our service provider? This should be done within the boot method. This method is called after all other service providers have been registered, meaning you have access to all other services that have been registered by the framework”

**Comment by marcelogarbin** [comment]
Understood, but even so it gets weird hehehe .. In the Laravel manual says one thing, however I have to do another to work hehehe..
