### ISSUE TITLE
Documentation: Creating module listener incorrect syntax

### ISSUE THREAD

**Issue by ardnor** [nWidart/laravel-modules#337]
Hey, I would like to inform you that the command syntax on creating listener is incorrect.

**From your documentation:** `php artisan module:make-listener Blog --event events` which is found here https://nwidart.com/laravel-modules/v2/advanced-tools/artisan-commands#modulemake-listener-blog-event-events

**And the error above occurred was this:**  [Nwidart\Modules\Exceptions\ModuleNotFoundException]  
  Module [] does not exist!

**I found out that it should be:** `php artisan module:make-listener ListenerClassName ModuleName --event EventClassName`

I hope it will help and it will update your documentation.

Thanks this package is really helps.

Best Regards,

Ardnor

**Comment by nWidart** [comment]
Hello,

Thanks for noticing.
I've just pushed the fix.

In the future feel free to PR the [documentation repository](https://github.com/nWidart/nwidart-docs).

**Comment by ardnor** [comment]
Hi, Thanks no problem. If I found other issues about the documentation I will update it directly to your documentation repo.
