### ISSUE TITLE
Add command for generating job classes for module

### ISSUE THREAD

**Issue by samueldervis** [nWidart/laravel-modules#34]
Really like this package. 
I would suggest you include commands for generating job classes within the module.

Such as 
`php artisan module:make-job SomeJob module`

Also would love to have option for generating migrations for a model created.
For instance in L5 i could do
`php artisan make:model TheModel -m`
where the '-m' generates the migration for the model.
It would be nice to achieve that in the module

Thanks

**Comment by nWidart** [comment]
Hello,

Good idea about the job class.

On the migration, that's probably something you can develop wrapping the package.
That's for instance something that's done in AsgardCMS module scaffolding tool.

**Comment by nWidart** [comment]
I added this in the following commit https://github.com/nWidart/laravel-modules/commit/df848290fc2db813bcc5703f38ffdb058463bc62 

Feel free to test dev-master until it's tagged.

**Comment by samueldervis** [comment]
Checking it out .
Thanks.

**Comment by nWidart** [comment]
This was tagged recently.
