### ISSUE TITLE
What does module:use do?

### ISSUE THREAD

**Issue by Kyslik** [nWidart/laravel-modules#340]
Can not wrap my head around :D 

>Use a given module. This allows **you to not specific the module** name on other commands requiring the module name as an argument.

I think there is also a typo "specific" -> "specify" or maybe missing "be" word.

Either way, is it useful for controlling the development workflow? So, when I am working with module Blog I just do the `use` command and every other following command will use Blog. How do I "reset" to default ("unset")?

**Comment by nWidart** [comment]
Correct that's a typo.

There's no command to unset it.

**Comment by Kyslik** [comment]
I guess I should open issues in the right repository... will do next time.

Thanks for clarifying.

**Comment by nWidart** [comment]
No worries.
I've created a new issue for the `unused` command.

**Comment by nWidart** [comment]
The new command has been added on dev-master.
