### ISSUE TITLE
View cache issue

### ISSUE THREAD

**Issue by yassersharaf** [nWidart/laravel-modules#343]
Hi
I'm having an issue with view cache. it was working fine but later changes I make in the view don't display even if I delete all the content of the view file unless I change the view file name from index to anything else. I have no issue with application other view like home .... 
return view('orders::index');
The problem is related to all modules not just one module
I tried to clear cache in every possible way
php artisan view:clear
php artisan config:clear
php artisan config:cache
php artisan clear-compiled
And deleted files in this path: storage\framework\views
But still having view cache issue. Any ideas?

**Comment by nWidart** [comment]
Hm that strange, maybe you have some application cache somewhere.

**Comment by nWidart** [comment]
I'll close this as it's likely related to the application/environment. Feel free to re-open if not.

**Comment by SkandaLonline** [comment]
Hi;
I'm having the same problem that your friend @yassersharaf  lived with. I've tried the issue on multiple different servers, and I'm seeing this problem only in module files.
