### ISSUE TITLE
Create a module:make-policy [name] [module] command

### ISSUE THREAD

**Issue by Kyslik** [nWidart/laravel-modules#344]
Duplicate of #53.

**Comment by nWidart** [comment]
Feel free to send a PR.

**Comment by shuxx** [comment]
@Kyslik your on it ?

**Comment by Kyslik** [comment]
@shuxx Feel free to add this I may later on tackle other ones :), during the week.

**Comment by shuxx** [comment]
Ok if you need some help i'm can help you, no much time for making that :(
