### ISSUE TITLE
How to handle dependencies between modules?

### ISSUE THREAD

**Issue by MatzeSchmitt** [nWidart/laravel-modules#345]
We´re thinking about to use this package in one of our next projects. First of all, thanks for providing this package.

This is more a structual questions rather than a technical one. How do you handle those situations where you need a model of module B in module A? Or the relationship?

Use Case:
Let´s assume there is model "Order" in module "Orders". Futhermore there is a model "Customer" in module "Customers". Now you would like to fetch all Orders with their Customers via a related repository in module "Orders".

Maybe we can start a discussion about dependencies and how to handle them between modules.

Thanks.

**Comment by MatzeSchmitt** [comment]
#35

**Comment by aphoe** [comment]
You can define the requirement in the `module.json` file at the root of the module.
