### ISSUE TITLE
Code refactor/rename

### ISSUE THREAD

**Issue by Kyslik** [nWidart/laravel-modules#349]
I think folder [src/commands](https://github.com/nWidart/laravel-modules/tree/master/src/Commands) needs some redoing since naming is really confusing. Some files are "generators" other are named "make" and for newcomers its confusing, or is there difference?

 - [x] rename files in source
 - [x] rename files in tests accordingly
 - [ ] add docblocs where needed
 - [ ] update config keys to match either singular or plural form

**Comment by nWidart** [comment]
Probably true yes, and no there's no difference.

**Comment by Kyslik** [comment]
Same for config keys, some are in plural some are in singular. That will be BC.

**Comment by nWidart** [comment]
Let's keep the config rename to the next major version 😄

**Comment by Kyslik** [comment]
Yes! thats BC.

Martin Kiesel

**Comment by nWidart** [comment]
I've created #370 to 4.0 milestone for this.
