### ISSUE TITLE
How to use models from other Modules?

### ISSUE THREAD

**Issue by n4p4** [nWidart/laravel-modules#35]
Say I have a **User** module.
And say I also have a **Blog** module.

The **Blog** module has a Post model/entity.

I want to use the User entity from the **User** module in a `posts()` relationship to the Post entity from the **Blog** module.

I.e. `$user->posts()`

In Ruby, this was possible by way of `class_eval`, which allows you to re-open an existing class and add methods to it. E.g., in this case we could've re-opened the User entity (which is from a different module) from within the **Blog** module and added a `public function posts()` method. 

How can we do this in PHP and Laravel?

**Comment by nWidart** [comment]
Hi,

This isn't a question related to this package. Please look up the laravel documentation to learn how you can do this. You could also go to the laracasts.com and view the videos.

**Comment by n4p4** [comment]
No, this is a question related to this package. You probably think I'm talking about hasOne/hasMany relationships in Laravel, but no I'm not.

I'm asking, how do you make entities from one module usable by entities from another module without hard coding the dependencies? Do I have to create a 3rd module to connect the two modules?

E.g., I don't see a user_id field in the AsgardCMS Blog module. How would you connect the User and the Blog module such that a user_id is available in the Blog module without hardcoding the Post entity into the User module?

**Comment by nWidart** [comment]
You would do it the same way, by using the namespace of the second module in your first module.

``` php
// in module User
public function posts()
{
    return $this->hasMany(Modules\Blog\Models\Posts::class);
}
```

If you want another way to avoid dependencies that would be up to you to find your preferred approach.

**Comment by armababy** [comment]
I don't understand why you mention AsgardCMS here, if it's issue on that you should fill issue there.

You can do relations however you like there are no constraints, this one just separates resources into module like structure, so it's much more easier to maintain without clutter in 1-2 folders.
Example provided by @nWidart is a standart laravel way of doing relation.

**Comment by n4p4** [comment]
I mentioned AsgardCMS to give an example because the maintainer of this package is the creator of the CMS. 

This issue does relate to this package . The issue is how can we create relationships between modules without hard-coding the dependencies? If someone can provide a good answer, it would help many people using this package to create even more modular systems.

**Comment by armababy** [comment]
Okay, i see what you want.
You can look at this example: [AsgardCMS/Page](https://github.com/AsgardCms/Page/blob/master/Entities/Page.php#L44-L58)
It's dynamically loaded into entity.

**Comment by n4p4** [comment]
That's great, thanks!

**Comment by boynet** [comment]
@armababy Thanks it's the first question popped to my mind when found this library, was suprised its not mentioned anywhere

**Comment by nWidart** [comment]
Because it's not this package role to do this. I handled it that way in asgardcms, but you can just as well find a better way to do it altogether. 😄

**Comment by atehnix** [comment]
As another way: https://github.com/greabock/tentacles
Maybe this is not the best way, but there is something to think about.
;)

**Comment by twf-nikhila** [comment]
@n4p4 @nWidart Can't we extend User _Model_ in Post _Modules_ and then add a relationship in the extended User Model?

**Comment by nWidart** [comment]
You can yes, this is just php indeed.

**Comment by turbo124** [comment]
Using a closure in the config's will break artisan config:cache. Is there a way to __call without passing back a closure from the config?

**Comment by kathmandu1** [comment]
when i am seeding , newly created modules seeder files are not seed ,

**Comment by beganovich** [comment]
Are you sure, you are using the right command? [php artisan module:seed {module name} @kathmandu1 
?

Otherwise, you can always try with composer dump-autoload, you know just in case.

**Comment by brideo** [comment]
Hi I stole this answer from Issue 345:

You can define the requirement in the module.json file at the root of the module.

That's how I am probably going to proceed.

**Comment by bilalsheikh1** [comment]
Here is your solution please check this link
https://github.com/imanghafoori1/eloquent-relativity

**Comment by robsontenorio** [comment]
@bilalsheikh1 @nWidart 

I am sorry for bumping this. Yeah, I know .. I can install both packages. 

But the “eloquent-relativity” package  should be a great addition to this package it self. It is killer feature. 

Because it solves a common problem when working with modules, once you want a truly independent modular approach.

**Comment by twf-nikhila** [comment]
I used this approach and it worked.

Check screenshot - 

![image](https://github.com/nWidart/laravel-modules/assets/3498959/fcb361a2-39ef-4db2-9b8a-c238cb185c3c)

**Comment by iacreative** [comment]
Hi,

This discussion has been going on for quite some time. And it actually helped me a lot about what I want to do in a new project!

But regarding the dependency between modules, I had a question.

How do you deal with dependencies in migrations?

Following the model proposed by the problem.

How do you deal with the user_id that is in the User Module and that will be included in the Post migration that is in the Blog module?

In this case we would still have interdependence between modules, right?
