### ISSUE TITLE
Use Events

### ISSUE THREAD

**Issue by dlouvard** [nWidart/laravel-modules#359]
Hi,

How can i use your package with events, i would like use in a module Event and Listener.

Thanks you
Regards
Damien

**Comment by nWidart** [comment]
Hello,

You can use events like any laravel application.
Create your event & listener, and register them either in your module service provider, or in a dedicated events service provider.

**Comment by dlouvard** [comment]
Ok, thanks you for your answer.

**Comment by nWidart** [comment]
I've created a new documentation page explaining exactly how to proceed:

https://nwidart.com/laravel-modules/v2/advanced-tools/registering-module-events

👍
