### ISSUE TITLE
Laravel 5.3

### ISSUE THREAD

**Issue by mybigman** [nWidart/laravel-modules#36]
Hi,

Any plans to support 5.3 since its released?

Problem 1
    - Installation request for nwidart/laravel-modules ^0.10.0 -> satisfiable by nwidart/laravel-modules[0.10].
    - Conclusion: remove laravel/framework v5.3.0

thanks

**Comment by nWidart** [comment]
It will support 5.3 yes.

**Comment by JulienTant** [comment]
plz now A+

**Comment by felipemarques** [comment]
+1 

I had to downgrade to 5.2.41 and change the signatures of methods services providers in the folder app/Providers/

**Comment by nWidart** [comment]
5.3 support has been added. https://github.com/nWidart/laravel-modules/releases/tag/0.11.0

**Comment by mybigman** [comment]
@nWidart 

Still cant be installed as its dependent on laravelcollective which currently not available for 5.3 :(

thanks

**Comment by nWidart** [comment]
Hello,

I see, very strange since the tests were passing on 5.3 (meaning it could get all dependencies, or so I thought).
We're indeed going to have to wait on laravelcollective to tag their release as stable.

**Comment by nWidart** [comment]
I've tagged version 0.11.1 which uses their development version. Though it still requires to add `"minimum-stability": "dev",` in the composer.json file to allow for it.

**Comment by nWidart** [comment]
Tagged to use stable version of laravelcollective/html 😄 

https://github.com/nWidart/laravel-modules/releases/tag/0.11.2
