### ISSUE TITLE
Help me with architecture

### ISSUE THREAD

**Issue by oldpunk** [nWidart/laravel-modules#362]
I made some modules, push it on packagist. In each module wrote dependencies. When I install project I wont all modules will be installed. But further when I add some dependency in root composer.json I dont wont this modules will be updated. 
In other words, I want use this modules as template for further  work

**Comment by nWidart** [comment]
I don't understand what you want.

If you require a module that has dependencies, composer will get those as well.

If you require a dependency in the root project, not in the module, the module won't be affected.

**Comment by oldpunk** [comment]
For example, I have module News. I add it like composer require vendor/News
it already has NewsController, in it I write my code.
After I modify News module, not in this project, add trait to NewsController. Push changes to github and packagist.
And when I will update composer in my project, NewsController will lost all my code

**Comment by nWidart** [comment]
That's how composer works yes.

Do you change code in `vendor/` as well and don't expect it to overwrite your changes?

**Comment by oldpunk** [comment]
@nWidart it was a question. How to download them with dependencies, but not update in future

**Comment by Kyslik** [comment]
The only way is to fork the package, and force composer to use your fork instead of "the original".
