### ISSUE TITLE
Migration path is hardcoded in loadMigrationsFrom call

### ISSUE THREAD

**Issue by IllyaMoskvin** [nWidart/laravel-modules#363]
When generating a new module, if I change my `migration` generator path in `modules.php`, my newly-generated service provider will still attempt to load migrations from the default `Database/Migrations` path. Please see [provider.stub#L28](https://github.com/nWidart/laravel-modules/blob/bcb3025009cb15f29730a8b2d5499611e60c7baa/src/Commands/stubs/scaffold/provider.stub#L28) and relevant tests.

I think the more "dynamic" alternative would be to substitute `Database/Migrations` with `config('modules.generator.migration')` on that line, but I'm not sure of the consequences.

I'm also not sure if this requires a fix, it's more of a heads-up than anything.

I love this project, btw! Looking forward to digging in deeper. It's a shame that component-based architectures aren't more prevalent in the PHP community.

**Comment by nWidart** [comment]
Hello,

Hm that's a good point. We have the migrations path here https://github.com/nWidart/laravel-modules/blob/master/config/config.php#L85 but that couldn't be used as it's the absolute path, and load from migrations needs the relative 🤔

**Comment by nWidart** [comment]
Though you're correct, `generator.migration` could be used since that's not a full path.

**Comment by IllyaMoskvin** [comment]
Would it be safe to use it here? Would there be any times when it's undefined, and should there be some sort of fallback? From first look, it seems kosher, but I'm unfamiliar with the codebase.

If you'd like, I can put together a PR.

**Comment by nWidart** [comment]
I've got the change working locally, with all tests green.

The configuration was already used for things like the [config path, language path etc](https://github.com/nWidart/laravel-modules/blob/master/src/Commands/ProviderMakeCommand.php#L88-L90). I've added one for the migrations path.

The config call could indeed get the default value of `Database/Migrations` just in case.

**Comment by nWidart** [comment]
[And here it is.](https://github.com/nWidart/laravel-modules/commit/b0b4a8025eeadcb9c103c900cb3e7f9ef309b8df)

**Comment by IllyaMoskvin** [comment]
Awesome, thank you! I think [some tests](https://github.com/nWidart/laravel-modules/search?utf8=%E2%9C%93&q=loadMigrationsFrom) may also need to be updated.

**Comment by nWidart** [comment]
Hm how so? The value of still the same by default.

**Comment by IllyaMoskvin** [comment]
My mistake. I assumed that test may involve (currently or in the future) testing to see how the generated output changes when config params change. I'm not too familiar with testing methodologies yet, so I cannot say whether that's a productive way to go.

**Comment by nWidart** [comment]
I see. I've added [a test for this](https://github.com/nWidart/laravel-modules/commit/b11228f038616e2d89cf27072945bd115406aa5e) though this is just testing laravel configuration so not sure it's worth it.

**Comment by IllyaMoskvin** [comment]
Ah, I understand how these tests work now. Yes, I hope this isn't too much overhead. Thanks again!

**Comment by nWidart** [comment]
No problem. I'll close this as it's ready to be tagged.
