### ISSUE TITLE
Factory path is hardcoded in provider.stub

### ISSUE THREAD

**Issue by IllyaMoskvin** [nWidart/laravel-modules#364]
I don't think this is high-priority, but it would be nice to make the `factory` path configurable via the `generator` option in `modules.php`. Please see [provider.stub#L99](https://github.com/nWidart/laravel-modules/blob/bcb3025009cb15f29730a8b2d5499611e60c7baa/src/Commands/stubs/scaffold/provider.stub#L99).

Just seems fitting, since the paths for `seeder` and `migration` are configurable too.

**Comment by nWidart** [comment]
I'm on it. I see that the make-factory command is also hardcoded.

**Comment by nWidart** [comment]
Done.

**Comment by IllyaMoskvin** [comment]
Thank you! For posterity: see commit 9eed5d3.
