### ISSUE TITLE
Routes path is hardcoded in start.stub

### ISSUE THREAD

**Issue by IllyaMoskvin** [nWidart/laravel-modules#365]
It would be good to use the `stubs.files.routes` config value from `modules.php` instead.

Please see [start.stub#L16](https://github.com/nWidart/laravel-modules/blob/1fab66502704b09919a6a482489e234ef1b750dc/src/Commands/stubs/start.stub#L16) and [route-provider.stub#L38](https://github.com/nWidart/laravel-modules/blob/b51e5e300ae8bf16019fb7cd1bb13fb5d060f526/src/Commands/stubs/route-provider.stub#L38).

Potential (retroactive) solution to #196.

**Comment by nWidart** [comment]
Good idea, done. 👍

**Comment by IllyaMoskvin** [comment]
Awesome! Thanks again!

For posterity: see commits 24badff, 94c6fe5, 6dced18.

**Comment by Kyslik** [comment]
Is this tagged?

**Comment by IllyaMoskvin** [comment]
I believe this has been tagged in [2.5.0](https://github.com/nWidart/laravel-modules/tree/2.5.0)
