### ISSUE TITLE
Console Command

### ISSUE THREAD

**Issue by golaod** [nWidart/laravel-modules#37]
How to register them?

**Comment by nWidart** [comment]
You can do it in the module itself. Just use the `$this->commands()` inside your service provider.

**Comment by golaod** [comment]
Sorry, don't know how I missed that :)

**Comment by swapnilsarwe** [comment]
Custom command under the module are not visible on `php artisan list`, i tried `$this->commands(['CustomCommand']);` i keep on getting `[ReflectionException]                                                                                                                   
  Class ...CustomCommand.php does not exist`. Am i missing anything ?

**Comment by adelowo** [comment]
i think it should be `$this->commands([CustomCommand::class]);` instead.. Have a look at this, https://github.com/nWidart/laravel-modules/blob/master/src/Providers/ConsoleServiceProvider.php#L48-L89

**Comment by davidlares** [comment]
Hello @nWidart  @adelowo referring to this same closed Issue, Im facing a tiny problem, but i really tried a lot of "fixes" without success.

I made with `$this->commands([ChangeStatus::class]);` and it gets printed on the artisan commands list, but when i execute it, throw this error: **Not enough arguments (missing: "example").** 

There's some i can do? any help, guide?

Thanks for your time :)

**Comment by nWidart** [comment]
That probably means your command isn't following the laravel syntax. Please refer to the laravel documentation for this. https://laravel.com/docs/5.4/artisan#writing-commands

**Comment by davidlares** [comment]
You we're right @nWidart in part of it,  it wasn't a Syntax, was the protected method getArguments and getOptions that came with the command instance by default.

Now I have a problem, with scheduling the command, there's any documented solution for it?

Thanks again for your time :)

**Comment by nWidart** [comment]
Yes, on the documentation.

**Comment by davidlares** [comment]
I'll check it right away, thanks! @nWidart
