### ISSUE TITLE
Can't add module in subdirectory

### ISSUE THREAD

**Issue by blendsoft** [nWidart/laravel-modules#371]
### Summary of issue
Cant create module in other directory than default

### Steps to reproduce
I made module in Modules/Moonbite/MoonUsers
with module.json

```
{
    "name": "MoonUser",
    "alias": "moonuser",
    "active": 1,
    "order": 1,
    "providers": [
        "Modules\\Moonbite\\MoonUser\\Providers\\RouteServiceProvider"
    ],
    "aliases": {
    },
    "files": [
    ]
}
```
and config:

```
'scan' => [
        'enabled' => true,
        'paths' => [
            //base_path('vendor/*/*'),
            base_path('Modules/Moonbite/*'),
        ],
    ],
```

Now I can't start

```
php ./artisan serve
                                                           
[Illuminate\Contracts\Filesystem\FileNotFoundException]  
File does not exist at path /module.json        
```

but when I disable module cache:
```
 'cache' => [
        'enabled' => false,
        'key' => 'laravel-modules',
        'lifetime' => 60,
    ],
```
it works

### System Details
- `Asgardcms/Platform` 3.0.2

**Comment by nWidart** [comment]
I can't reproduce this. Are you sure you're autoloading your module?

**Comment by nWidart** [comment]
Oh I see you created a module, in a module. That's not supported.

**Comment by blendsoft** [comment]
Ok my directory structure made misunderstanding
My second attempt
I made directory MoonModules in root directory as sibling of Modules directory.
in composer I have
```
 "psr-4": {
            "App\\": "app/",
            "Modules\\": "Modules/",
            "MoonModules\\": "MoonModules/"
        }
```
In MoonModules I made module MoonUsers with
```
{
    "name": "MoonUser",
    "alias": "moonuser",
    "active": 1,
    "order": 1,
    "providers": [
        "MoonModules\\MoonUser\\Providers\\RouteServiceProvider"
    ],
    "aliases": {
    },
    "files": [
    ]
}
```
in modules.php
```
 'scan' => [
        'enabled' => true,
        'paths' => [
            base_path('vendor/*/*'),
            base_path('MoonModules/*'),
        ],
    ],
```
then 
```
php ./artisan serve                                                           
[Illuminate\Contracts\Filesystem\FileNotFoundException]  
File does not exist at path /module.json        

```
but it works only if 
```
 'cache' => [
        'enabled' => false,
        'key' => 'laravel-modules',
        'lifetime' => 60,
    ],
```
looks like module cache problem.

**Comment by nWidart** [comment]
I see, and did you find a solution?

**Comment by nWidart** [comment]
Hm strange I tried to reproduce your setup, but I don't get that error.

I have a module in `Modules/` and `MoonModules/`, my scan option looks like this:

``` php
'scan' => [
    'enabled' => true,
    'paths' => [
        base_path('Modules'),
    ],
],
```

No need to add more since the MoonModules one is loaded via `paths.modules`. And then also enabled caching.

**Comment by blendsoft** [comment]
When I disable cache then I can run serve, then when enable cache, and refresh browser I have full debug output, I think I can fix it.

**Comment by nWidart** [comment]
You can try to replace the following inside the `Repository` classs:

```php
public function getScanPaths() : array
{
    $paths = $this->paths;

    $paths[] = $this->getPath();

    if ($this->config('scan.enabled')) {
        $paths = array_merge($paths, $this->config('scan.paths'));
    }
    $paths = array_map(function($path) {
        return str_finish($path, '/*');
    }, $paths);

    return $paths;
}
```

This makes the routes work for both module locations.

**Comment by blendsoft** [comment]
I made it, my error still appear, my issue is
![screenshot-localhost-8000-2017-10-05-10-32-53](https://user-images.githubusercontent.com/1213251/31217947-fc4e4ede-a9b8-11e7-9989-623162c4d595.png)

**Comment by nWidart** [comment]
I see, I can't reproduce this.

**Comment by blendsoft** [comment]
Ok, I will make more investigation

**Comment by nWidart** [comment]
The reason I can see is that a path is not setup correctly somewhere. Did you remove the double includes in the scan setup?

**Comment by blendsoft** [comment]
Ok, lets get back to the  issue.
in
laravel-modules/src/Laravel/Repository.php

you are adding paths.modules to cached modules.
so modules in other directiores than path.modules won't work.
```
 protected function formatCached($cached) {
    $modules = [];

    foreach ($cached as $name => $module) {
      $path = $this->config('paths.modules') . '/' . $name;

      $modules[$name] = new Module($this->app, $name, $path);
    }

    return $modules;
  }
```

**Comment by nWidart** [comment]
I can't reproduce this. I have modules in other directories, and no errors.

**Comment by blendsoft** [comment]
Maybe I am missing something, maybe $this->config('paths.modules') sholud be set somewhere else, in module configuration ? it looks like when I try to use module from custom directory, $this->config('paths.modules')  is just empty.

**Comment by blendsoft** [comment]
Finally I found a solution. You not caching path of exact module, just adding path from config('paths.modules') + name of module, so modules in other directory than Modules wont work with cache. I had to back to my first concept. I made subderictory in Modules, named MoonModules, then put my MoonUser modules in it. Then in module config I set name of module to "MoonModules/MoonUser",
Now path is correct and module works with cache.

**Comment by nWidart** [comment]
Hm I'm not sure im following but if you found the solution feel free to PR the fix, as long as it doesn't break the normal behaviour. 👍

**Comment by blendsoft** [comment]
It's possible

**Comment by pravnkay** [comment]
@blendsoft Can you please say if it was possible to achieve a structure like 

-app
-bootstrap
-Modules
--Foo
---LoremModule
--Bar
---IpsumModule

And, if yes , could you please explain how ?

I am using v8. and I tried everything to my knowledge. Nothing works.
Any help is much appreciated.
