### ISSUE TITLE
How to register service providers and facades of packages required in a module?

### ISSUE THREAD

**Issue by dinajpuri** [nWidart/laravel-modules#374]
Hello,

I'm trying to create a reusable User login-regitration module. I've also required a captcha package in the module's **composer.json** which was installed when I updated the module (php artisan module:update Module)
`"require": {
        "anhskohbo/no-captcha": "dev-master"
    }`

Now, if I'm to register Service Provider and Facade, where to do it?

Regards

**Comment by nWidart** [comment]
You can do that in the module.json `providers` and `aliases` keys. If the package supports auto-discovery, you don't even have to add this.

You should also add this dependency in your module `composer.json` file.

**Comment by dinajpuri** [comment]
Thank you replying so fast.

**Comment by nWidart** [comment]
No problem 👍
