### ISSUE TITLE
How to handle Laravel   Routing for web and API

### ISSUE THREAD

**Issue by vishaljamwal159** [nWidart/laravel-modules#375]
In Laravel 5.4 and 5.5, routes are defined in routes folder (web.php,api.php etc). When we use this package it only generates routes.php which is like web.php. How we can separate web routes and API routes per module and how we can use Eloquent API resources per module

**Comment by nWidart** [comment]
Hello,

The default routes file is just an example. You can call the command `module:route-provider` that will generate a service provider to more easily load more route files.
Of course this is optional and you may choose to load your routes files as you want.

**Comment by vishaljamwal159** [comment]
I tried to run the above-mentioned command got following error

 php artisan module:route-provider admin
 [Symfony\Component\Debug\Exception\FatalThrowableError] 
 Class 'Modules\Admin\Providers\AdminServiceProvider' not found

AdminServiceProvider is there so can you guide me with an example if possible

                                                                  4
9m

**Comment by nWidart** [comment]
That means you didn't autoload your modules probably. Look that up in the docs.

**Comment by vishaljamwal159** [comment]
Thanks a lot for support. I am able to create different route files for web and API for each module.
