### ISSUE TITLE
Using Modules with Lumen 5.5

### ISSUE THREAD

**Issue by shineforce** [nWidart/laravel-modules#377]
[ReflectionException]             
  Class path.public does not exist

**Comment by SOSTheBlack** [comment]
How do you solve it, I have the same problem

**Comment by ahmdqader** [comment]
how to solve it?

**Comment by diesousil** [comment]
I've addded this code on bootstrap file, before registering ServiceProvider:

$app->bind('path.public', function() {
 return __DIR__ . 'public/';
});

I've found this solution here:  https://nwidart.com/laravel-modules/v2/lumen

**Comment by doankiem** [comment]
Thanks @diesousil but I 've added 
$app->bind('path.public', function() {
 return __DIR__ . 'public/';
});
before adding configure:
$app->configure('modules');

**Comment by ahrasel** [comment]
@josk2 Thanks. it's worked for me
