### ISSUE TITLE
Model default namespace is hardcoded

### ISSUE THREAD

**Issue by Kyslik** [nWidart/laravel-modules#378]
I don't remember if we already talked about hardcoded namespaces (default ones)

https://github.com/nWidart/laravel-modules/blob/54b42c28168f15dd1c8304f1b3a94ce6d0c28102/src/Commands/ModelMakeCommand.php#L158-L166

So if I change configuration lets say to "Models", generator creates `Modules\Blog\Entities\Model`, I think its also with all other generators.

**Comment by nWidart** [comment]
Weren't you the one removing all these dynamic parts for hardcoded ones?

**Comment by nWidart** [comment]
I'm fixing it now.

**Comment by nWidart** [comment]
Added. https://github.com/nWidart/laravel-modules/commit/81f5aec6ba4374fb8736ac2616957e1cb0f6f18f

**Comment by Kyslik** [comment]
I guess I was, and I had pretty good reason for it, if we'd use the config values namespaces slashes would be reversed... so hardcoded was better at the time.

**Comment by nWidart** [comment]
yea I added a thing where front-slashes are replaced to make sure.

**Comment by montyclt** [comment]
In my case, I removed the modules services providers and empty `providers` array in `module.json`.

To register translations, config and views, I have a `ModuleServiceProvider` in `App` namespace with this content in `boot` method:

```
$modules = $this->app['modules']->enabled();

foreach ($modules as $module) {
            $this->registerTranslations($module);
            $this->registerConfig($module);
            $this->registerViews($module);
        }
```

And in these methods, I get the path and name:
```
protected function registerTranslations(Module $module)
    {
        $this->loadTranslationsFrom($module->getPath() . '/Resources/lang', $module->getLowerName());
    }
```

@nWidart If you like it, I can send a PR this weekend with this changes.

**Comment by nWidart** [comment]
That used to be done that way before too. But decided to move that logic on each module instead of letting the package do this.

**Comment by montyclt** [comment]
Ok, I will not send the PR.

**Comment by NassarX** [comment]
@montyclt Tried your way before but when run `php artisan module:publish [module-name]` or even  `php artisan module:publish` do no thing as behind scene it get `--provider` argument from [module-name]. could you handled that ?!

**Comment by daveismyname** [comment]
I don't think https://github.com/nWidart/laravel-modules/commit/81f5aec6ba4374fb8736ac2616957e1cb0f6f18f has been released as yet, on 2.5 the problem exists still. ie generated models that's got a default name in the config of models still used entities when generated.

**Comment by nWidart** [comment]
Correct, it doesn't have a date, and still under the `next` title.

**Comment by nWidart** [comment]
Has been tagged as 2.6.
