### ISSUE TITLE
L 5.3 problem..

### ISSUE THREAD

**Issue by amitshrestha221** [nWidart/laravel-modules#38]
Hello sir,

 

I need a help from you. I am about to start a project in office since today. I started in L5.3 and used your modules extenstion from GitHub. The problem is, after using modules plugin, no any class is being supported in my Controllers.

Eg: Input Class not found.

 

I used to do projects in L 5.1  where I used pingping-sky and everything was working well. When I compared those two modules created by pingpong in 5.1 and laravel-modules in 5.3, I found that

 

 

In modules created by ping ping : there is this line

use Pingpong\Modules\Routing\Controller;

 

set by default in Newly created module, which is not present in the module created by laravel/modules. Do you think this is the issue?

 

Hoping positive solution from you ! It would be an big help if you could take some of your time to reply this message.

 

Thanks !!

**Comment by nWidart** [comment]
Hello

This isn't related to this package.
You need to correctly import your namespaces into your files.
