### ISSUE TITLE
Reusing a module - installing dependancy while it registers service provider

### ISSUE THREAD

**Issue by dinajpuri** [nWidart/laravel-modules#380]
Hello,
I've an ImageManager module from another package which requires
`        "intervention/image": "^2.4" `

and registers the following service provider in module's composer.json

` "Intervention\\Image\\ImageServiceProvider"`

When I'm trying to use the module in a new project, I can't install the dependancies (php artisan module:update...) cause it throwse error
` 
 [Symfony\Component\Debug\Exception\FatalThrowableError]
`
 ` 
  Class 'Intervention\Image\ImageServiceProvider' not found
`
which makes sense.

Now how do I use the module without modifying its code ( I mean removing the service provider and adding it after installing the required packages) ?
Laravel 5.5's "auto discovery" maybe a solution.

Regards

**Comment by nWidart** [comment]
With laravel autodiscovery you don't need to register the service provider.

Service providers can't be added to composer.json as well.

Just require the package and you're done.

**Comment by dinajpuri** [comment]
I thought so.
Btw, I registered service provider in module.json
