### ISSUE TITLE
Seeder path is hardcoded in SeedCommand.php

### ISSUE THREAD

**Issue by IllyaMoskvin** [nWidart/laravel-modules#381]
Please see `getSeederName` method, c. [SeedCommand.php#L156](https://github.com/nWidart/laravel-modules/blob/bc87d50f375765ab0b5bda43473b5545aa6c3736/src/Commands/SeedCommand.php#L156).

Compare with `getDestinationFilePath` method in [SeedMakeCommand.php#L87](https://github.com/nWidart/laravel-modules/blob/bc87d50f375765ab0b5bda43473b5545aa6c3736/src/Commands/SeedMakeCommand.php#L87).

**Comment by nWidart** [comment]
Thanks, done in https://github.com/nWidart/laravel-modules/commit/f777a6707c5fbbf145b4db016ce24141e5574a78

**Comment by JulienTant** [comment]
You can probably close this !

**Comment by IllyaMoskvin** [comment]
Thank you!

**Comment by nWidart** [comment]
Has been tagged as 2.6.
