### ISSUE TITLE
CSRF token mismatch on shared hosting!!

### ISSUE THREAD

**Issue by sonminh18** [nWidart/laravel-modules#383]
Hi,
I'm building my project with nwidart laravel modules and I do some ajax call in my script, by following instruction ajax call in laravel ,I added 
`$.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });`
and
`<meta name="csrf-token" content="{{ csrf_token() }}" />
`
It's worked perfectly on `php artisan serve` but when I deployed to shared hosting, It show error token mismatch, after some debug ,the token when ajax header call and `$request->session()->token()` not match. Is this error from this package or I did something wrong?

**Comment by Kyslik** [comment]
I don't think package has anything to do with token mismatch, try searching other possibilities first.

**Comment by nWidart** [comment]
Indeed the package doesn't touch your headers.
