### ISSUE TITLE
Updating base directory for the module NameSpace prefix

### ISSUE THREAD

**Issue by NassarX** [nWidart/laravel-modules#385]
Hi @nWidart 

Is there any ability to modify base directory for the module NameSpace prefix  while generating the module without needing to run  `composer dumpautoload` every time or to fork !
ex:
`
"psr-4": {
            "vendor\\User\\": ""
        }`

to be 
`
"psr-4": {
            "vendor\\User\\": "src"
        }`

**Comment by nWidart** [comment]
What do you mean by prefix?
You can customise the namespace & folder of your modules. There is no need to dump autoload after a module was generated.

**Comment by NassarX** [comment]
I wanna build something like that :
```
Modules  
    ├── Patient  
        ├── config    
        ├── console  
        ├── database   
        ├── resources    
        ├── routes  
        │   └── routes.php  
        ├── src  
        │   ├── Http  
        │   │   ├── Controllers  
        │   │   │   └── PatientController.php   
        │   │   └── Requests  
        │   ├── Providers  
        │   │   └── PatientServiceProvider.php  
        │   ├── Repositories    
        ├── composer.json  
        ├── module.json  
        └── start.php
```

so  need customize namespace so can look after `src` directory !

**Comment by nWidart** [comment]
You can do this already. Just create your src and autoload it.
Though you will lose all capabilities to generate classes for modules I think.

**Comment by NassarX** [comment]
Generate classes for modules works great after autoload, but still need to autoload everytime after generating a module and customize module' composer.json psr-4 namespace.

**Comment by nWidart** [comment]
Oh I see ok. Hm not sure how to prevent that in this case, as you're adding a new record to autoload of each module. So it's normal it requires a dump autoload.

The reason the "normal" setup doesn't is b/c we autoload the modules folder, and not each individual module.

**Comment by NassarX** [comment]
Aha, Thanks a lot for your comments.
