### ISSUE TITLE
Uncaught ErrorException: require(..$ROUTES_LOCATION$): failed to open stream: No such file or directory in..start.php:16

### ISSUE THREAD

**Issue by dinajpuri** [nWidart/laravel-modules#386]
Hi,

I'm getting the following error with new modules, probably its after update laravel-modules to version 2.5

`Uncaught ErrorException: require(F:\xampp2\htdocs\laravel55\Modules\Lorem$ROUTES_LOCATION$): failed to open stream: No such file or directory in F:\xampp2\htdocs\laravel55\Modules\Lorem\start.php:16`

In start.php file I see
`require __DIR__ . '$ROUTES_LOCATION$';`

instead of
`require __DIR__ . '/Http/routes.php';`

Regards

**Comment by nWidart** [comment]
Please read https://github.com/nWidart/laravel-modules/issues/372
