### ISSUE TITLE
PHP Fatal error:  Cannot declare class LoremServiceProvider, because the name is already in use in \Modules\Lorem\Providers\LoremServiceProvider.php on line 112

### ISSUE THREAD

**Issue by dinajpuri** [nWidart/laravel-modules#387]
Hi,

I'm getting the following error when I create new modules. Its probably its after updating laravel-modules to version 2.5 yesterday.

`PHP Fatal error:  Cannot declare class Modules\Lorem\Providers\LoremServiceProvider, because the name is already in use in F:\xampp2\htdocs\laravel55\Modules\Lorem\Providers\LoremServiceProvider.php on line 112`

I tried with several module names and get same error.

Regards

**Comment by nWidart** [comment]
Hm I can't reproduce this. The error means you have the same class name multiple times.

**Comment by dinajpuri** [comment]
Nope. I tried with different names like lorem ipsum.

**Comment by nWidart** [comment]
Tests are green, I can't reproduce this. Must be your setup.

**Comment by guicara** [comment]
I also has this error, but I don't know exactly how I manage to fix it. I htink that you need to edit your `config/modules.php`, because there is some differences between the last versions and the new version.

**Comment by dinajpuri** [comment]
Looks like the auto-generated service provider line in **module.json** is redundant and its causing the error
`"providers": [`
  `      "Modules\\Ipsum\\Providers\\IpsumServiceProvider"`
  `  ],`
Without this line module works **even if I have disabled auto discover**

**Comment by dinajpuri** [comment]
@guicara I've republished the config which didn't fix the error

**Comment by nWidart** [comment]
Hm I'm generating modules locally and it's not causing the error.
Did you re-publish with the `--force` flag?

Are you maybe registering the service providers manually or otherwise yourself?

**Comment by dinajpuri** [comment]
@nWidart yes I've force-published

**Comment by dinajpuri** [comment]
Solved.
I again force-published config file, cleared cache, created new module and no error using new modules.

**Comment by IllyaMoskvin** [comment]
Have you taken a look at #373? This probably happened because `path.generator.factory` was missing from your old config file, specifically. It was added in v.2.5.0.

Glad you got it fixed!

**Comment by nWidart** [comment]
Closing this as it's solved 😄
