### ISSUE TITLE
When and how handling errors for the authentication?

### ISSUE THREAD

**Issue by guicara** [nWidart/laravel-modules#388]
Hello,

I know that my question is not directly related to this package. I must do something wrong, but I need your advices to understand how to handle the default login routes and the framework exceptions.

I have created few modules, including `Core` and `Auth`. 

The `Core` module (order 0) defines all the base classes and logic and the `Auth` module (order 1) is responsible for managing user sign in, sign out, forgotten password, etc.  I have moved the pre-built authentication controllers shipped by Laravel in the `Auth` module. I have also a `User` module.

All the pages of my application requires that the user is logged, except for the `login`, `logout`, `password/*` and `register` routes.

When a user is not logged, the `AuthenticationException` is thrown and handled by the `App\Exceptions\Handler` class. Then the `unauthenticated` method of `Illuminate\Foundation\Exceptions\Handler.php` try to call the `login` named route (see [here](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Exceptions/Handler.php#L180)).

The problem is that I define this route in my `Auth` module. **The exception handler is called before this module, before the routes are loaded**. Finally Laravel returns a `InvalidArgumentException` exception because the route login is not defined.

I try to figure out how AsgardCMS handle the exceptions with the authentication of the user, but I still not understand.

Should I remove the default `App\Exceptions\Handler::class` from the `bootstrap/app.php` file and use a custom handler class in my `Core` module, and another handler only for the `AuthenticationException` exception in my `Auth` module?

What is the best way?

Thanks!

**Comment by nWidart** [comment]
Hello,

This is up to you how to handle this.
I wouldn't suggest to remove the default Exceptions/Handler class.

**Comment by estaticfear** [comment]
Dear, my auth module still need use App\Exceptions\Handler::class for redirect if unauthenticated, it's not good, How can i handle unauthenticated on my module ?

**Comment by daveismyname** [comment]
what I do is have an AdminController that uses the auth middleware that if a user is not logged in they will be redirected to the login page:

```php
use App\Http\Controllers\Controller;

class AdminController extends Controller
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public function __construct()
    {
        return $this->middleware('auth');
    }
}
```

then all other controllers that need to be secured I extend from it:

```php
use App\Http\Controllers\AdminController as BaseController;

class PostsController extends BaseController
{
```

For my login / forgot routes I extend from a default controller
