### ISSUE TITLE
[Enhancement] php artisan module:make support for lumen

### ISSUE THREAD

**Issue by ReinierH** [nWidart/laravel-modules#389]
Hi! 

any plans on implementing the php artisan module:make commands for lumen? 

Regards

**Comment by IllyaMoskvin** [comment]
Could I ask which version of Lumen are you using? I haven't tried this package with Lumen yet, but I was under the impression that it worked with Lumen as-is (cf. #310).

Are you getting any errors w/ the `module:make` command specifically? Or are you having trouble getting started with the module as a whole?

It's possible that if you are using Lumen 5.4, you will need to take a couple extra steps when installing v.2.0^ of this package. See ["Add Service Provider"](https://github.com/nWidart/laravel-modules/tree/1.0#add-service-provider) in the README on the `1.0` branch.

**Comment by ReinierH** [comment]
I'm using Lumen 5.5. I tried to manually add Laravel-modules but I cannot get it to work. I've added the LumonModulesServiceProvider to bootstrap/app.js ($app->register(....) and checked if the module was added to autoload_psr4 by composer. I'm still unsure how to manage with the config file as Lumen doesn't have a config folder.

**Comment by IllyaMoskvin** [comment]
Hmm... I'm not sure how publishing config files works for Lumen. I think it might be missing the `vendor:publish` command. You could likely pull in [laravelista/lumen-vendor-publish](https://github.com/laravelista/lumen-vendor-publish), but you can also "publish" this package's config file manually:

1. Create a `config` folder in your repo root.
2. Copy `vendor/nwidart/laravel-modules/config/config.php` to `config/modules.php` 
3. Load the configuration file in `boostrap/app.php`, before `LumenModulesServiceProvider`:

```
$app->configure('modules');
...
$app->register(Nwidart\Modules\LumenModulesServiceProvider::class)
```
Let me know how it goes!

**Comment by ReinierH** [comment]
Just manually added the laravel-modules module to my lumen project. When I run php artisan it returns an error saying:

`  [ReflectionException]
  Class path.public does not exist`

**Comment by nWidart** [comment]
A lumen helper was added for this. Not sure if you need to autoload it or not. It was added here https://github.com/nWidart/laravel-modules/pull/357

**Comment by ReinierH** [comment]
it's not autoloaded, would it be an idea to add it to the LumenModuleServiceProvider under registerHelpers(); ?

**Comment by ReinierH** [comment]
adding a helper.js file in app/ containing the config_path() function and defining path.public in bootstrap/app.js did the trick

**Comment by ReinierH** [comment]
is it an idea to add 

`if ( ! function_exists('config_path'))
 {
     /**
      * Get the configuration path.
      *
      * @param  string $path
      * @return string
      */
     function config_path($path = '')
     {
         return app()->basePath() . '/config' . ($path ? '/' . $path : $path);
     }
 }`

 to the helpers function?

**Comment by nWidart** [comment]
Similarly to how the `public_path` helper was added why not yes.
