### ISSUE TITLE
Question: Using assets (js,css,img) directly form module asset folders

### ISSUE THREAD

**Issue by laravelbap** [nWidart/laravel-modules#390]
Hi,

is it possible to uses files (js, css, images) directly from module asset folders without publishing to "public" ?

**Comment by nWidart** [comment]
Hello,

That's not possible due how laravel works. 
You can, however, make a symlink, or front controller to access them this way.

**Comment by laravelbap** [comment]
Hi,
thank you for the quick reply! I was thinking about symlink myself. What do You mean by front controller ?

**Comment by nWidart** [comment]
It means having to go through a route + controller, which servers the proper assets.

This is usually done when files need to be protected by roles/passwords etc.
