### ISSUE TITLE
Route.php file in subfolder 

### ISSUE THREAD

**Issue by espositodaniele** [nWidart/laravel-modules#393]
Hello, 

I tried to move the route.php in a subfolder outside of Http folder but is not working, it returns 404 page.
Is not possible to do that ? 

Thanks 

D

**Comment by nWidart** [comment]
It is, you need to tell laravel that file has changes location.

check the module.json if you're loading the routes file there.

**Comment by espositodaniele** [comment]
Could you be more explicit on how Can I do that? I have now in the modules folder a new folder Route and inside of it, I moved the route.php. Then what should I do? 

Thanks

**Comment by espositodaniele** [comment]
That's the error I get : 

"Nwidart\Modules\Module::main(): Failed opening required

**Comment by espositodaniele** [comment]
I tried to change the start.php as well but nothing. 

That's the error I get: 

![modules](https://user-images.githubusercontent.com/26567236/31812744-501da4e8-b584-11e7-8c5f-989be856ab39.PNG)

Nwidart\Modules\Module::main(): Failed opening required

Thanks

**Comment by nWidart** [comment]
strange, maybe you're loading those routes somewhere else too.

**Comment by espositodaniele** [comment]
But which is the process that I should follow to achieve that? Maybe I can do it again. 

Thanks

**Comment by nWidart** [comment]
There is no process. You're free to load your routes however you like. This package doesn't do anything with with it.

**Comment by espositodaniele** [comment]
Okay, Sorry. I didn't pay attention to what I was doing. I was calling the file route.php with the wrong path as I show in the pic. The path wasn't require __DIR__ . '/Http/Routes/routes.php' but require __DIR__ . '/Routes/routes.php' !

Thanks anyway for the support and well done with this package it saves me lot of time, you got my star.

**Comment by nWidart** [comment]
Good to know, no worries happens to all of us! 

👍
