### ISSUE TITLE
Enable/Disable

### ISSUE THREAD

**Issue by espositodaniele** [nWidart/laravel-modules#396]
Hello there, 

I can't really figure out how module:enable and module:disable work. What does it mean? I have read the documentation but it shows you just the command without explanation of what really does.  I have installed the package and created a variety of modules, now I would understand the concept of disabling a module. 

Btw good job. 

Thanks

**Comment by nWidart** [comment]
Hi,

It doesn't mean much. It's simply a flag in `module.json`. If it's disabled, nothing in that module will be loaded.

**Comment by espositodaniele** [comment]
@nWidart Hello, 

Thanks for the reply, I did a try and it's petty simple. What I'm trying to do now is to run this command when some event is fired, like a button click to disable a specific module. I'm using Laravel, any idea on how I can achieve that? I will appreciate it. 

Thanks, 

D

**Comment by nWidart** [comment]
Yes, look at the Repository/Module class in order to programmatically disable/enable modules.

**Comment by nWidart** [comment]
There isn't a repository folder. I mentioned "Module/Repository" _class_.

Module: https://github.com/nWidart/laravel-modules/blob/master/src/Laravel/Module.php
Repository: https://github.com/nWidart/laravel-modules/blob/master/src/Laravel/Repository.php

**Comment by espositodaniele** [comment]
I got them but still no idea on how to achieve that. In the meantime, I have seen in src/module.php abstract class two methods disable and enable, both of them fire an event to disable the current module, It can be done?

**Comment by espositodaniele** [comment]
@nWidart  Yes, there is where I was looking into, but how I cant use as the Target [Nwidart\Modules\Module] is not instantiable??

**Comment by espositodaniele** [comment]
@nWidart So I solved used facade, 

Thanks for the support.
