### ISSUE TITLE
ServiceProvider Not Found

### ISSUE THREAD

**Issue by clonex1** [nWidart/laravel-modules#4]
I'd like to say this is nice module.
It has an error that says afte creating Backend module.

Class 'CustomNameSpace\Backend\Providers\BackendServiceProvider' not found.

L v5.2.39

**Comment by nWidart** [comment]
It looks like it couldn't find your namespace. Double check if the case on `CustomNameSpace` is the same everywhere.

Also try with the default `Modules` namespace to see if we can pinpoint the issue.

**Comment by clonex1** [comment]
Hi,
I have changed namespace to default "Modules" uppercase "M", I still got the same issue.
Class 'Modules\Backend\Providers\BackendServiceProvider' not found

**Comment by nWidart** [comment]
Changing the namespace alone won't do anything, as it's PSR-4, your folder structure needs to match, or your composer.json file needs to be adapted.

**Comment by clonex1** [comment]
This is composer.json on root directory

>         "psr-4": {
>             "App\\": "app/",
>             "Modules\\": "modules/"
>         }

Am I missing anything!

**Comment by nWidart** [comment]
You need to check the namespaces yes.

The folder structure needs to match the namespace.

**Comment by clonex1** [comment]
- Modules folder exists in root directory /modules
- composer.json root directory contents as follows:

>     "psr-4": {
>         "App\\": "app/",
>         "Modules\\": "modules/"
>     }

- Folder stucture trace to BackendServiceProvider as follows:

> /modules/Backend/Providers/BackendServiceProvider.php

- namespace declaration in BackendServiceProvider.php

> <?php namespace Modules\Backend\Providers;

- composer.json content for Backend module as related to psr-4:

> 	"autoload": {
> 		"psr-4": {
> 			"Modules\\Backend\\": ""
> 		}
> 	}

**Comment by nWidart** [comment]
You just linked 2 different psr-4 autoload section. You can only use one of them, keep the first one.

Also run a `composer dumpautoload` and `php artisan clear-compiled`.

**Comment by clonex1** [comment]
Thanks! That fixed it!

**Comment by nWidart** [comment]
Awesome 👍

**Comment by Elikar-KM** [comment]
> You just linked 2 different psr-4 autoload section. You can only use one of them, keep the first one.
> 
> Also run a `composer dumpautoload` and `php artisan clear-compiled`.

Woking for me also, thanks

**Comment by jhonymiler** [comment]
> I'd like to say this is nice module. It has an error that says afte creating Backend module.
> 
> Class 'CustomNameSpace\Backend\Providers\BackendServiceProvider' not found.
> 
> L v5.2.39

Run the command: artisan module:publish
Add the "namespace" variable to the items in the "generator" array.
![image](https://github.com/nWidart/laravel-modules/assets/18699320/77055a84-2507-4e01-8613-87670d25a8fc)

The team forgot about PSR-4 with PHP 8.2.

**Comment by mugnet** [comment]
I have the same issue @nWidart. 
Laravel v11

```php
Class "Modules\Portal\Providers\PortalServiceProvider" not found
  

here is my composer.json

 "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Modules\\": "Modules/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
 ```

Module folder structure:
```python
Modules
└── Portal
    ├── app
    │   ├── Http
    │   │   └── Controllers
    │   │       └── PortalController.php
    │   └── Providers
    │       ├── EventServiceProvider.php
    │       ├── PortalServiceProvider.php
    │       └── RouteServiceProvider.php
    ├── composer.json
    ├── config
    │   └── config.php
    ├── database
    │   ├── factories
    │   ├── migrations
    │   └── seeders
    │       └── PortalDatabaseSeeder.php
    ├── module.json
    ├── package.json
    ├── resources
    │   ├── assets
    │   │   ├── js
    │   │   │   └── app.js
    │   │   └── sass
    │   │       └── app.scss
    │   └── views
    │       ├── index.blade.php
    │       └── layouts
    │           └── master.blade.php
    ├── routes
    │   ├── api.php
    │   └── web.php
    ├── tests
    │   ├── Feature
    │   └── Unit
    ├── vendor
    │   ├── autoload.php
    │   └── composer
    │       ├── ClassLoader.php
    │       ├── LICENSE
    │       ├── autoload_classmap.php
    │       ├── autoload_namespaces.php
    │       ├── autoload_psr4.php
    │       ├── autoload_real.php
    │       └── autoload_static.php
    └── vite.config.js
 ```

Did I miss something?

**Comment by dcblogdev** [comment]
@mugnet have you ran `php artisan module:clear-compiled` this removes `bootstrap/cache/modules.php` which will then be reset.

For v11 you need to remove "Modules\\": "Modules/", and the merge-plugin to the extra section of `composer.json`

```php
"extra": {
    "laravel": {
        "dont-discover": []
    },
    "merge-plugin": {
        "include": [
            "Modules/*/composer.json"
        ]
    }
},
```

**Comment by mugnet** [comment]
@dcblogdev thank you for the quick response but it gave the same issue.

**Comment by dcblogdev** [comment]
ah you may need to run `composer dump-autoload`

**Comment by mugnet** [comment]
Yeah awesome thanks! @nWidart is right too about  the namespaces and folder structure both should matched then. Thank you so much man appreciate it.

**Comment by ilramdhan** [comment]
> [@mugnet](https://github.com/mugnet) have you ran `php artisan module:clear-compiled` this removes `bootstrap/cache/modules.php` which will then be reset.
> 
> For v11 you need to remove `"Modules\\": "Modules/",` and the merge-plugin to the extra section of `composer.json`
> 
> "extra": {
>     "laravel": {
>         "dont-discover": []
>     },
>     "merge-plugin": {
>         "include": [
>             "Modules/*/composer.json"
>         ]
>     }
> },

Thankyouu this work for me!!!

**Comment by uttampun44** [comment]
@dcblogdev  "extra": {
    "laravel": {
        "dont-discover": []
    },
    "merge-plugin": {
        "include": [
            "Modules/*/composer.json"
        ]
    }
}, merge-plugin plugin after run command composer-update

**Comment by naseemkhan-netizen** [comment]
## Provider not found error in Laravel 12 with nwidart/laravel-modules

### Environment
- **PHP Version:** 8.4.13
- **Laravel Version:** ^12
- **Package Version:** nwidart/laravel-modules ^12.0

### Description
After following the setup steps for `nwidart/laravel-modules`, I'm still encountering a "provider not found" error when trying to use modules in Laravel 12.

### Configuration

**Root `composer.json`:**
```json
{
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "App\\Modules\\": "app/Modules",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        },
        "merge-plugin": {
            "include": [
                "app/Modules/*/composer.json"
            ]
        }
    }
}
```

**`app/Modules/Platform/composer.json`:**
```
{
//...
    "autoload": {
        "psr-4": {
            "App\\Modules\\Platform\\": "app/",
            "App\\Modules\\Platform\\Database\\Factories\\": "database/factories/",
            "App\\Modules\\Platform\\Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Modules\\Platform\\Tests\\": "tests/"
        }
    }
}
```

**`config/modules.php`:**
```php
'namespace' => 'App\Modules',
//.....
'paths' => [
    'modules' => base_path('app/Modules'),
],
```

### Steps to Reproduce

1. Install package: `composer require nwidart/laravel-modules`
2. Publish config: `php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"`
3. Add `"App\\Modules\\": "app/Modules"` to root `composer.json` autoload section
4. Run `composer dump-autoload`
5. Create module: `php artisan module:make Platform`

### Directory Structure
```
├── app
│   ├── Modules
│   │   └── Platform
│   │       ├── app
│   │       │   ├── Http
│   │       │   │   └── Controllers
│   │       │   └── Providers
│   │       ├── config
│   │       ├── database
│   │       │   ├── factories
│   │       │   ├── migrations
│   │       │   └── seeders
│   │       ├── resources
│   │       │   ├── assets
│   │       │   │   ├── js
│   │       │   │   └── sass
│   │       │   └── views
│   │       ├── routes
│   │       └── tests
│   │           ├── Feature
│   │           └── Unit
│   └── Providers
```

### Expected Behavior
Modules should be discovered and loaded without errors.

### Actual Behavior
Getting "provider not found" error.

### Additional Context
- All configuration appears correct
- `composer dump-autoload` has been run
- Module structure is generated correctly by the package

### Question
What additional steps or configuration am I missing to resolve this "provider not found" error in Laravel 12?
