### ISSUE TITLE
Install laravel package in a module

### ISSUE THREAD

**Issue by sebasbz** [nWidart/laravel-modules#402]
Hello how to  install laravel package like adminlte, https://github.com/acacha/adminlte-laravel, https://github.com/yajra/laravel-datatables and register their providers and aliases in a specific module
thank you so much

**Comment by nWidart** [comment]
Feel free to read the documentation.

A module is a package, meaning you require whatever you want. Add its service provider in module.json if it doesn't have auto-discovery.

**Comment by sebasbz** [comment]
i was adding the service provider in the module.js  but always it is tell me the class is no found 
![captura de pantalla 2017-10-26 a las 1 55 49 p m](https://user-images.githubusercontent.com/8251670/32071636-7bc352ca-ba55-11e7-9fb5-652ac26d473c.png)
![captura de pantalla 2017-10-26 a las 1 55 14 p m](https://user-images.githubusercontent.com/8251670/32071637-7bdc9578-ba55-11e7-968f-6b06b74b419c.png)

**Comment by mikemand** [comment]
Don't use `::class` in the `module.json`. `::class` is a PHP language construct for getting the FQCN (fully qualified class name), rather than having to type out the full namespace and class as a string.

**Comment by sebasbz** [comment]
@mikemand  thank you so much I could solve it

**Comment by manhboo1305** [comment]
I followed but it didn't work, can you help me?
