### ISSUE TITLE
Have regular routes take precedence when using a catchall

### ISSUE THREAD

**Issue by daveismyname** [nWidart/laravel-modules#404]
I have a catchall route in a module:

```php
Route::group(['middleware' => 'web', 'namespace' => 'Modules\Pages\Http\Controllers'], function()
{
    Route::get('{slug}', 'PagesController@fetch')->where('slug', '(.*)');
});
```

What I'm wondering is there a way in the /routes/web.php to be read first. Currently, any routes defined don't take effect due to my catchall route above.

**Comment by nWidart** [comment]
you can use module order to control when it'll be loaded.

**Comment by pmochine** [comment]
@nWidart Do you know how I can set the order?

**Comment by pmochine** [comment]
I found out. In every module there is a module.json with the order
