### ISSUE TITLE
Call to a member function make() on null

### ISSUE THREAD

**Issue by 3s2ng** [nWidart/laravel-modules#405]
We started using the laravel-modules but we experience a very weird problem. Any code error we always see "**Call to a member function make() on null**" be it DB error, php code error or any types or error. 

 It's very hard for us to debug the application as we always see the same error message regardless of the error. 

PHP Fatal error:  Uncaught Error: Call to a member function make() on null in /api/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:66

**Comment by nWidart** [comment]
that's odd, doesn't sound like an issue with this package though. I can only suggest to make sure te application is setup correctly.
