### ISSUE TITLE
Class ServiceProvider not found  

### ISSUE THREAD

**Issue by Leshgan** [nWidart/laravel-modules#406]
Hello.
I created new module 'Admin' from manual and when run php artisan I get this error:

Class 'Modules\Admin\Providers\AdminServiceProvider' not found  
but file Modules\Admin\Providers\AdminServiceProvider.php is present 
Running 'composer dump-autoload' doesn't help

**Comment by mrcage** [comment]
Same issue for me, using laravel 5.7 and laravel-modules 4.0
