### ISSUE TITLE
Module views automatic created inside resource views

### ISSUE THREAD

**Issue by dayachand-systematix** [nWidart/laravel-modules#407]
Module views automatic created copy of our modular views inside resource views.

**Comment by nWidart** [comment]
What?

**Comment by ashraf777** [comment]
I don't know what @dayachand-systematix tried to say but may be he got this confusion same as I am facing - There is a view directory under individual module (Ex-Todo) and module genaration also created a Todo directory under main app resource/view directory. So where to edit the template? In my case I have to edit in main app resource. Module view is not effecting in any where. How can change template from module view?  main documentation is not giving much information. It will be great if there is more in documentation. thanks.

**Comment by nWidart** [comment]
Module generation should not create a folder under the laravel resource directory.

**Comment by ashraf777** [comment]
Yah ... really confused I have created another module (Name- Test) it didn't created anything in main app resource. 

here is the screen shot - 
![sdasdasdad](https://user-images.githubusercontent.com/11267756/34664029-0095fe72-f484-11e7-8532-33ced95b7f44.png) 

Thanks for ur quick reply and also for ur great package. any plan to make the documentation more robust?

**Comment by ashraf777** [comment]
Yes, it could happen. I will try to find what I have made wrong. Thanks

**Comment by dayachand-systematix** [comment]
I am also confused when module views replica creates in resource/views directory. but its created sometimes. 

Solution for this: You can delete from resource /views directory.
