### ISSUE TITLE
how to config Frontend and Backend module ?

### ISSUE THREAD

**Issue by sonminh18** [nWidart/laravel-modules#409]
Hello,
I'm using nwidart package .I want to create structure for my project below to 2 part Frontend and Backend like this:

+ frontend
   + module-one
      + controllers
          - controllers-one.php
          - controllers-two.php
      + models
          - model-one.php
          - model-two.php
      + views
          - view-one.php
          - view-two.php
   + module-two
   + module-three
+ backend
   + module-one
   + module-two
   + module-three

How to do that with this package?

**Comment by nWidart** [comment]
I don't think this is possible, was discussed in a previous issue.
You can test with the configuration file which has an option to load from multiple locations.
