### ISSUE TITLE
Don't boot or register not requested module

### ISSUE THREAD

**Issue by raywill** [nWidart/laravel-modules#41]
Since application is separated into modules, any http request should only access one module at a time.  

Just imagine we have hundreds of modules, unrequested modules should not be booted or registered at all.

Should we provide a mechanism to archive this goal?

**Comment by nWidart** [comment]
I don't think this is needed. You can also just leverage laravel's deferred service providers if needed.

This is the usual routing, as in laravel will try to get a matching route.

**Comment by raywill** [comment]
I did an experiment and found the result not as expected:

1. I created to modules named Help, Game using ``php artisan module:make Help Game`` , change their provider's $defer = true. Other code is kept the same as generated.
2. turned on module cache
3. add log to Help and Game providers
4. do some warmup by access /game page several times
5. clean log
6. access /game
7. the log indicated both providers are accessed. 

Expect:

```
[2016-09-06 16:21:36] production.INFO: register Game provider
[2016-09-06 16:21:36] production.INFO: boot Game provider
```

Actual:
```
[2016-09-06 16:21:36] production.INFO: register Help provider
[2016-09-06 16:21:36] production.INFO: register Game provider
[2016-09-06 16:21:36] production.INFO: boot Help provider
[2016-09-06 16:21:36] production.INFO: boot Game provider
```

**Comment by nWidart** [comment]
That's normal as providers are booted by the package.

**Comment by raywill** [comment]
yes, I understand.

But, what do I need to do to make it not loading Help provider?

I do have hundreds of modules. It is too slow and waste of cpu cycles to touch those undesired ones

**Comment by nWidart** [comment]
Mark them as deferred and don't let the package load them (ie vie the providers key). 
If loading a simple service provider is slow for you , you're most likely doing something wrong in them.
