### ISSUE TITLE
@include and @component does not work ...

### ISSUE THREAD

**Issue by FredAzevedo** [nWidart/laravel-modules#414]
After installation, @include and @component in views is not working. What could have happened?

**Comment by nWidart** [comment]
this has nothing to do with the package. Please refer to laravel documentation.

**Comment by FredAzevedo** [comment]
Thanks for answering. So, I'm using @include as I've always used it, when I run tests before installing Laravel Modules the @include works, after installing Laravel Modules it does not work.
