### ISSUE TITLE
migrations --create

### ISSUE THREAD

**Issue by daveismyname** [nWidart/laravel-modules#415]
Is there a reason --create flag does not exist for module migrations?

ie:

```
module:make-migration create_events_table --create=events
```

outputs

```
 [Symfony\Component\Console\Exception\RuntimeException]
  The "--create" option does not exist.
```

**Comment by nWidart** [comment]
Not sure what that flag is supposed to do, but the command guesses the action from the migration name. 
Example if your migration name is `create_events_table` it'll know it's to create a table and prepare the correct boilerplate for it.

**Comment by daveismyname** [comment]
Yes I've just realised it still creates the boilerplate code. So yes you're right it's not needed.

Thanks 👍

**Comment by makobongo** [comment]
Hello how can l alter the table using this package i.e. I used php artisan module:make-migration add_is_pending_to_finance_payments_cash finance --table='finance_payments_cash'; to try and alter my table within my finance module and i get  The "--table" option does not exist.
