### ISSUE TITLE
Change boot order of LaravelModuleServiceProvider

### ISSUE THREAD

**Issue by pixelarbeit** [nWidart/laravel-modules#416]
Hey,

the LaravelModuleServiceProvider is automatically loaded. Is there a possibility to add it manually so it's booted after a certain ServiceProvider? I tried to publish the Provider and set it in the app.config, but that didn't help.

I want to change this, so my modules will overwrite Routes if they already exists.

**Comment by nWidart** [comment]
Hello,

This is laravel related.
Laravel has a `dont-discover` key in composer.json file, to disable autodiscovery of packages. You should be able to add the package here, and register it manually pre-5.5.

**Comment by nWidart** [comment]
More about how here: https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518

**Comment by pixelarbeit** [comment]
Thanks for the quick answer. I will have a look and it. Right now I found a workaround.
