### ISSUE TITLE
Cannot define custom scan path not ending with '/*'

### ISSUE THREAD

**Issue by aleron75** [nWidart/laravel-modules#417]
Hello,
since `Nwidart\Modules\Repository\getScanPaths()` always adds a trailing `/*` to each path (not already ending with `/*`), I am not able to register a custom scan path like, for example:

    'scan' => [
        'enabled' => true,
        'paths' => [
            base_path('vendor/*/*/src'),
        ],
    ],

Thus, for example in Laravel, the `Nwidart\Modules\Laravel\Repository::scan()` method will fail at finding the `module.json` under my path, because the `$path` used here:

`$manifests = $this->app['files']->glob("{$path}/module.json");`

will be `/var/www/html/vendor/*/*/src/*/module.json` instead of the correct one, which is `/var/www/html/vendor/*/*/src/module.json`.

Since it doesn't seem that the `Nwidart\Modules\Repository\getScanPaths()` is used elsewhere, why the `/*` is always added at the end of the path?

Workaround: I use `'vendor/*/*/'` as base path but this brings to scanning more directories than needed and could find other `module.json` files.

Thank you

**Comment by nWidart** [comment]
Hello,

Interesting use-case.
This was recently added since version 2.6 to allow loading modules in subfolders.
Ideally this path needs to point to the parent folder, where the modules (plural) can live.

**Comment by jnbn** [comment]
Maybe instead of using str_finish we may consider using a regexp or something to allow multiple wildcard subdirectories?

**Comment by nWidart** [comment]
This was just tagged in 2.7.
Sorry for the delay!
