### ISSUE TITLE
Artisan commands declared in modules not working

### ISSUE THREAD

**Issue by daaru00** [nWidart/laravel-modules#418]
Hi,

I trying to create a custom artisan command inside a module, first of all I try using:
`php artisan module:make-command TestCommand MyModule`.

Inside the generated file I change the protected `$name` property in "test:test"
```php
class TestCommand extends Command
{
    /**
     * The console command name.
     *
     * @var string
     */
    protected $name = 'test:test';
```

but when I try to exec it I receiving an error: 
`There are no commands defined in the "test" namespace. `

I also try to clear the composer autoload and laravel cache but I still receive the same errore, seems the commands are not loaded.

I noticed that the laravel `artisan make:command` create a different property name:
```php
class TestCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'command:name';
```
using signature instead of name it does not give results.

Am I doing something wrong?
Thank you.

**Comment by nWidart** [comment]
Hello,

You're on a good path, but just forgot to register this command with laravel.
Use `$this->commands([TestCommand::class])` inside your service provider.

**Comment by daaru00** [comment]
Hi, many thanks for the prompt reply,

so the commands are not registered automatically from the path? 
Registering it "manual" in the service provider, like this:
```php
   /**
     * Register commands.
     *
     * @return void
     */
    protected function registerCommands()
    {
        $this->commands([
            \Modules\MyModule\Console\TestCommand::class
        ]);
    }
```
and adding on boot the function `$this->registerCommands();` it works, thx.

**Comment by nWidart** [comment]
Not automatic is a choice of laravel sadly: https://twitter.com/themsaid/status/888041249780924416

**Comment by daaru00** [comment]
I use a similar solution adding this method in the service provider:
```php
   /**
     * Register commands
     *
     * @param string $namespace
     */
    protected function registerCommands($namespace = '')
    {
        $finder = new Finder(); // from Symfony\Component\Finder;
        $finder->files()->name('*Command.php')->in(__DIR__ . '/../Console');

        $classes = [];
        foreach ($finder as $file) {
            $class = $namespace.'\\'.$file->getBasename('.php');
            array_push($classes, $class);
        }

        $this->commands($classes);
    }
```
and in boot method adding:
```php
  $this->registerCommands('\My\Module\Console');
```
this seems working, even if is little bit "quick and dirty".

**Comment by nWidart** [comment]
yeah why no 👍 

(I'll close this issue as it has been resolved :) )

**Comment by daaru00** [comment]
Thanks for the support.

**Comment by ahlechandre** [comment]
In Laravel 5.6 [Registering Commands](https://laravel.com/docs/5.6/artisan#registering-commands) section:

> Because of the load method call in your console kernel's commands method, all commands within the app/Console/Commands directory will automatically be registered with Artisan. In fact, you are free to make additional calls to the load method to scan other directories for Artisan commands:

```php
/**
 * Register the commands for the application.
 *
 * @return void
 */
protected function commands()
{
    $this->load(__DIR__.'/Commands');
    $this->load(__DIR__.'/MoreCommands');

    // ...
}
```

**Comment by lucassmacedo** [comment]
@ahlechandre @daaru00  @nWidart 
``    /**
     * Register commands.
     *
     * @return void
     */
    protected function registerCommands()
    {
        $commands = collect(glob(base_path('Modules/*/Console/*.php')))
            ->map(function ($item) {
                preg_match(sprintf("/%s.*/", config('modules.namespace')), $item, $matches);
                return str_replace(['/', '.php'], ["\\", ''], $matches[0]);
            })->toArray();


        $this->commands($commands);
    }``

**Comment by lucassmacedo** [comment]
On this way i have all commands from my modules registreds
