### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by PeilunCC** [nWidart/laravel-modules#42]
excuse me, I used your laravel-modules for laravel 5.3, but I 'm have difficulty, 
I follow the steps install laravel-modules
when I type `php artisan module:make Bulletin` is ok
and then type `php artisan module:list` is not ok
because it show:
`[Symfony\Component\Debug\Exception\FatalThrowableError]
Class 'Modules\Bulletin\Providers\BulletinServiceProvider' not found`

I checked the folder, this file exists.
Do I less steps !?
And other question can create route to Modules\Bulletin\route\api.php or web.php !?
And how do use restful api ?

thanks.

**Comment by nWidart** [comment]
Looks like you didn't autoload your modules.


> Do I less steps !?
Not English.


> And other question can create route to Modules\Bulletin\route\api.php or web.php !?
Yes.



> And how do use restful api ?
Same as any laravel app.

**Comment by PeilunCC** [comment]
haha, sorry, my english isn't good
and I found my question, because I forgot use `composer dump-autoload`

> And other question can create route to Modules\Bulletin\route\api.php or web.php !?
how can I do when I use `php artisan module:make module_name`?

**Comment by nWidart** [comment]
I don't understand the question.

You're free to set your routes files where ever you want.

**Comment by PeilunCC** [comment]
sorry, I mean when I use php artisan module:make Bulletin
this folder struct is
Modules
-Bulletin
--Assets/Config/Console/Database ...

and the route.php in HTTP folder
how can I change default folder in routes/api.php and web.php 
when I use php artisan module:make Bulletin

**Comment by nWidart** [comment]
You can do that by changing the path in the RouteServiceProvider to your new location.

**Comment by PeilunCC** [comment]
OK, thanks.
