### ISSUE TITLE
How to use Faker factory?

### ISSUE THREAD

**Issue by chimmel** [nWidart/laravel-modules#421]
I try seeding a table and get
`[Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Modules\Cars\Database\Seeders\Faker\Factory' not found`
Tried `use \Faker\Factory as Faker` with the backslash in front with same result.

**Comment by patrick204nqh** [comment]
@chimmel I have the same problem, how to fix it?

**Comment by notklaavins** [comment]
l
