### ISSUE TITLE
Method validate does not exist.

### ISSUE THREAD

**Issue by bhattraideb** [nWidart/laravel-modules#422]
Here is my controller

```
<?php
namespace Modules\Admin\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;


class AdminLoginController extends Controller
{
    public function __construct()
    {
        $this->middleware('guest:admin');
    }

    public function showLoginForm()
    {
        return view('admin::login');
    }

    public function login(Request $request)
    {
        //validate form data
        $this->validate($request, [
            'email' => 'required|email',
        ]);

        //attempt to log the user in
        if(Auth::guard('admin')->attempt(['email' => $request->email, 'password' => $request->password], $request->remember)){
            return redirect()->intended(route('admin.dashboard'));
        }
    }
```

The error I am getting is "Method [validate] does not exist."
Does anyone faced the same issue? Please share the solution.

**Comment by nWidart** [comment]
You need to import the trait to validate
```
Illuminate\Foundation\Validation\ValidatesRequests;
```

**Comment by bhattraideb** [comment]
Hi Nicolas Widart,
I imported the trait, but did not work. What wrong am I  doing, Below is my code: 
`<?php
namespace Modules\Admin\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
Illuminate\Foundation\Validation\ValidatesRequests;

class AdminLoginController extends Controller
{
     public function login(Request $request)
    {
        //validate form data
        $this->validate($request, [
            'email' => 'required|email',
        ]);
    }
}`

Also I tried to impport within the class like:

`<?php
namespace Modules\Admin\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;

class AdminLoginController extends Controller
{
Illuminate\Foundation\Validation\ValidatesRequests;
     public function login(Request $request)
    {
        //validate form data
        $this->validate($request, [
            'email' => 'required|email',
        ]);
    }
}`

**Comment by nWidart** [comment]
That's because you're not importing the trait. Please refer to the laravel/php docs.

Example here: https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Controller.php#L12

**Comment by bhattraideb** [comment]
I am very sorry @nWidart,
I did not understand, My main controller inside app/Http/Controller is same as: https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Controller.php#L12

**Comment by nWidart** [comment]
and you're extending `use Illuminate\Routing\Controller;`... please, read the documentation.

**Comment by bhattraideb** [comment]
Thanks @nWidart, understood now, working well now.  
Cheers!

**Comment by Ramonivandy** [comment]
`<?php
namespace Modules\Admin\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Foundation\Validation\ValidatesRequests;

class AdminLoginController extends Controller
{
     public function login(Request $request)
    {
        //validate form data
        $this->validate($request, [
            'email' => 'required|email',
        ]);
    }
}`

already insert the 'use Illuminate\Foundation\Validation\ValidatesRequests;' but still get validate does not exist.

and 'use Validator;' isnt work too.

**Comment by bhattraideb** [comment]
@Ramonivandy,  replace 'use Illuminate\Routing\Controller;' with 'use App\Http\Controllers\Controller;'
because 'use Illuminate\Routing\Controller' might have already added in '\App\Http\Controllers\Controller.php'.
Hope this will solve the issue.

**Comment by amitshahc** [comment]
Then my question is: why the controllers under nWidart modules not using `'use App\Http\Controllers\Controller;'` by default ?

**Comment by amitshahc** [comment]
> and you're extending `use Illuminate\Routing\Controller;`... please, read the documentation.

sorry, but i must say. above eloborates nothing until i read the last reply from @bhattraideb. I am still wondering how did he got you?

**Comment by bhattraideb** [comment]
Good question from @amitshahc. @nWidart it would be great if you can override  'use Illuminate\Routing\Controller;' to 'use App\Http\Controllers\Controller;' by default when creating a controller.

**Comment by sergx** [comment]
If you want to have `use App\Http\Controllers\Controller;` by default in your project you can changed stub file, wich located in `\vendor\nwidart\laravel-modules\src\Commands\stubs\controller-api.stub`
