### ISSUE TITLE
Module does not exist!

### ISSUE THREAD

**Issue by rafapaulino** [nWidart/laravel-modules#423]
I published a module in the packagist, however at the time of installing the module it does not work and generates this error:

  [Nwidart\Modules\Exceptions\ModuleNotFoundException]
  Module [Blog] does not exist!

How do I solve this? I tried with the command: php artisan module:install rafapaulino/blog

**Comment by nWidart** [comment]
Hello,

Did you try to require it with composer using `composer require`? You may also need to specify to load it in the configuration and set the vendor config to true in the config file.
