### ISSUE TITLE
Route Priority? Want to have multiple auth for different module

### ISSUE THREAD

**Issue by shiroamada** [nWidart/laravel-modules#434]
My system has 2 modules for login.
-Member: www.example.com
-Admin: admin.example.com
-Agent: agent.example.com

I would like to implement three different login layout
-Member: member.example.com/login
-Admin: admin.example.com/login
-Agent: agent.example.com/login

For member I use default laravel app/ workflow to implement.
Now I am create an agent module.
in
Modules/Agent/Http/routes.php

```
<?php
//namespace Modules\Agent\Http\Controllers;
//Agent
\Route::domain('agent.example.com')->group(function () {
    
    \Route::group(['middleware' => 'web', 'prefix' => '', 'namespace' => 'Modules\Agent\Http\Controllers'], function()
    {
        \Route::get('login', 'Auth\LoginController@showLoginForm')->name('agent.login');
        \Route::post('login', 'Auth\LoginController@login');
        \Route::post('logout', 'Auth\LoginController@logout')->name('logout');

        // Registration \Routes...
        \Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('agent.register');
        \Route::post('register', 'Auth\RegisterController@register');

        // Password Reset \Routes...
        \Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('agent.password.request');
        \Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('agent.password.email');
        \Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('agent.password.reset');
        \Route::post('password/reset', 'Auth\ResetPasswordController@reset');

        \Route::get('/', 'AgentController@index');
    });

});

```

However, Laravel keep access to www.example.com/login layout, eventhough the URL is I access is agent.example.com/login

But if I change the 
```
        \Route::get('agent-login', 'Auth\LoginController@showLoginForm')->name('agent.login');
```
Then it is display correctly. 

How do I make sure it is login to the correct method? I already use `Route::domain()` to group it.

**Comment by nWidart** [comment]
Hi,

You can use the `order` key in `module.json` to define the order the modules are loaded.
You could also not add the RouteServiceProvider in `module.json`, but load them manually in the order you prefer in `config/app.php`
