### ISSUE TITLE
How to have env by module ?

### ISSUE THREAD

**Issue by jeffbarretocopam** [nWidart/laravel-modules#436]
Hello. I am triyin to figure out how to create env by module .Is there any option to define it ?

**Comment by nWidart** [comment]
I'm not sure what you mean, but the package doesn't do anything to the environment, that's all up to you.

**Comment by bayanbts** [comment]
@nWidart We are using this package to include a laravel project (as module ) into another laravel project (because we have two laravel projects and we want to put one into the other).
 so can we make .env file for the module?and do you think that our try is ok??

**Comment by mgip** [comment]
@nWidart @BayanMAljerf Hello guys, i need this, i try to figure out, but unsuccessfully... The packages/modules are a sub laravel skeleton project, nWidart/laravel-modules must have a native way to read a module .env file and overwrite the parent laravel project .env file.  In the docs i dont see anything about it. ¿could you help me to figure out? ... thanks.

**Comment by mgip** [comment]
Finally, i figure out

In the Module Service Provider put on boot() method

    $lines = @file($this->app->basePath('Modules/') . $this->moduleName . '/.env', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);

    if(!$lines) $lines = [];
    foreach ($lines as $line) {

        if (strpos(trim($line), '#') === 0) {
            continue;
        }

        list($name, $value) = explode('=', $line, 2);
        $name = trim($name);
        $value = trim($value);

        if (!array_key_exists($name, $_SERVER) && !array_key_exists($name, $_ENV)) {
            putenv(sprintf('%s=%s', $name, $value));
            $_ENV[$name] = $value;
            $_SERVER[$name] = $value;
        }
        
    }

Load the module .env

Cheers
