### ISSUE TITLE
How to share a module to Github and Packagist

### ISSUE THREAD

**Issue by szewang2805** [nWidart/laravel-modules#44]
Hello, i have installed your package and organized laravel into modular structure.
I have created a module call User  for example, how can i share to github ?
i want to know which folder of my module i need to GIT INIT?

can you show me some step?

thx
Create A Module.
Push the module to github.
Submit your module to the packagist website. Submit to packagist is very easy, just give your github repository, click submit and you done.

**Comment by nWidart** [comment]
That would be up to you to find the approach you prefer most.

One way is to go into your User module folder, and git init in there.

**Comment by samueldervis** [comment]
Hi @nWidart. Just need a concept on how to force the modules to install into the Modules folder instead of vendor. Also the package name to begin Caps.

**Comment by nWidart** [comment]
that's up to you to do. On asgardcms I use composer installer plugin.
