### ISSUE TITLE
Where can set a package configuration that is used in a modules of laravel-modules

### ISSUE THREAD

**Issue by ahmadbadpey** [nWidart/laravel-modules#440]
I want to use [laravel-modules][1] package to create a modular laravel app. 

For example one of the custom module that I want to create is called **Tag** .for that I want to use [etrepat/baum][2] package (that seems is best in this case).

My first question is which composer file I should add **Baum** package ? individual **Tag** module or main composer file of whole project? and what is differences ? 

And second is suppose I added it to **Tag** `composer.json` file , but then where do I added should `'Baum\Providers\BaumServiceProvider'` that is required to run Baum package while there is not any `app.php` file in `Config` directory created in **Tag** module. 

  [1]: https://github.com/nWidart/laravel-modules
  [2]: https://github.com/etrepat/baum

**Comment by nWidart** [comment]
Hello,

[This should answer your first question](https://github.com/asgardcms/platform/wiki/custom-module-dependency)

You should add the baum service provider in your `module.json` file. Though packages now will usually work with auto-discovery.
The baum config file will be in the `config/` directory as always.

**Comment by moosavimaleki** [comment]
@nWidart module config dir or root config dir?

**Comment by nWidart** [comment]
@moosavimaleki for what? 

A package: will be in root config dir.
A module configuration, in module config.

**Comment by Parables** [comment]
It took me about 20 jumps, searching the issues with this: `is:issue is:closed module composer.json ` just to find this answer.

Don't you think a FAQ in the docs can save lots of hours and repeated issues being raised here?
