### ISSUE TITLE
Doing something wrong? Arugment #2 not an array?

### ISSUE THREAD

**Issue by SeoRoman** [nWidart/laravel-modules#443]
I created to Modules "A" and "B"

I attempted to use the following command:

`php artisan module:use A`
Error: array_merge(): Argument #2 is not an Array

`php artisan module:list`
Error: array_merge(): Argument #2 is not an Array

How does this work?

**Comment by SeoRoman** [comment]
NEVERMIND! Looks like something may have gotten "touched" and messed everything up

**Comment by SeoRoman** [comment]
I lied... Ok, so to replicate this issue...

I deleted the module I was trying to "Module:Use" and I was able to re-create new modules and that module again..

when I attemped to do module:use "B" it "broke" Module B... and I couldn't do any module commands after that while "B" was still an active and included Module. Once, I deleted Module B then it was fixed and I could recreate Module B, until I attempted to module:use it once again...

**Comment by SeoRoman** [comment]
module:list doesn't work either

**Comment by SeoRoman** [comment]
Resolved!

Apparently I had a previous config in my /config/ that was named the same as a new module I was testing... because I wanted to move the information to the module...

the config was causing issues.

**Comment by nWidart** [comment]
Hi,

I'm not able to reproduce this. I can:

- use `module:use blog`  
- run `module:make-controller MyController`
- use `module:use recipe`
- run `module:make-controller MyController`

Both controllers are generated.

**Comment by SeoRoman** [comment]
Thanks, I have closed it. Apparently it was a busted config I had loaded in my app/config that matched the name of a module I was going to use... :D

**Comment by nWidart** [comment]
Ah ok glad to see you fixed it. 😄
