### ISSUE TITLE
add module in vendor 

### ISSUE THREAD

**Issue by vahidalvandi** [nWidart/laravel-modules#446]
i use laravel-module in my cms system, i have multiply project then each project in self laravel project . then i add module in the laravel . like module/cms or module/shop 
i have big problem in version control . how i develop modules in one core and each project after change cms commit in version control. then after composer update each project update to last version cms ??

**Comment by vahidalvandi** [comment]
i work with package but nwidart is smiple

**Comment by nWidart** [comment]
That's up to you to develop. Asgardcms does this for instance.

**Comment by vahidalvandi** [comment]
i need this technical  CMS in example
