### ISSUE TITLE
module:seed not working properly

### ISSUE THREAD

**Issue by mustafa2033** [nWidart/laravel-modules#447]
module:seed only seeding the modules that created before updating the package to 2.5 on laravel 5.5, all modules are seeded except the newly created with no message in the console.
i have tried to seed all modules and got messages from console about what seeded but still no luck with new modules **so help please.**

**Comment by ysrinu** [comment]
@mustafa2033 Can you paste error here in text and screenshot?

**Comment by gregoriochiko** [comment]
Hi, I have a similliar problem.
The `php artisan module:seed <module>` not giving me any output.

Steps to reproduce:
1. In functional test
```php
public function init()
{
    // ...
    Artisan::call('module:migrate', ['Blog']);
    Artisan::call('module:seed', ['Blog']);
    // ...
}
```

2. Console command
```zsh
php artisan module:seed Blog
```

Output:
```zsh

```

Did I miss some configuration or something like that?

**Comment by gregoriochiko** [comment]
Forget it, I've figured it why.

I have no `BlogDatabaseSeeder.php` file on my module.
So, adding that file and call the other table seeders will work in my case.

Thanks!
