### ISSUE TITLE
Error when using API Resource

### ISSUE THREAD

**Issue by mg-freelancer** [nWidart/laravel-modules#452]
``` return new CustomerResource(Customer::find(1)); ``` 
when I write this snippet in my controller, it gives me an error ``` { "message": "Undefined property: Illuminate\\Database\\Query\\Builder::$id" ``` because ```$this``` context not defined in CustomerResource file, how to fix it ?

**Comment by nWidart** [comment]
Hello,

This is not related to this package. Please make sure to check the laravel documentation.
