### ISSUE TITLE
csrf_token not working with custom Middleware

### ISSUE THREAD

**Issue by altdev91** [nWidart/laravel-modules#453]
Hello,

I have a problem with csrf_tolen and custom middleware. 

`Route::group(['middleware' => 'authin', 'prefix' => 'admin', 'namespace' => 'Modules\Admin\Http\Controllers'], function() {
...ajax/login // admin/ajax/login

});`

<meta name="csrf-token" content="{{ csrf_token() }}"> => empty content,

But when I change middleware "authin" to" web, csrf_token working.

**Comment by nWidart** [comment]
Hello,

This is not related to this package.
