### ISSUE TITLE
How can i define new Middleware in module

### ISSUE THREAD

**Issue by jacktv1** [nWidart/laravel-modules#454]

**Comment by nWidart** [comment]
You can register your middleware inside your module service provider using `this->middleware()` method. Or add it in the Kernel.php of the app/Http directory.

**Comment by praditha** [comment]
Could you provide me the sample please?

**Comment by mybigman** [comment]
@nWidart that no longer works, you must use ->aliasMiddleware()

**Comment by vahidalvandi** [comment]
Call to undefined method Modules\Vproducts\Providers\VproductsServiceProvider::middleware()

**Comment by xavi7th** [comment]
In case anyone is still confused, in your module's service provider's boot method, add register your middleware thus
`app()->make('router')->aliasMiddleware('auth2', \Your\Namespace\Class\Auth2::class);`

This assumes you are trying to create a middleware called auth2. Then you can use it on your controllers or routes like:

`Route::middleware('auth2') .... `

`$this->middleware('auth2') ....`

**Comment by MilanUnjiya4149** [comment]
Find module service provider file under Module->Providers->ModuleServiceProvider.php, Append middleware in boot method.

Exa.
InstallerServiceProvider.php

public function boot(\Illuminate\Routing\Router $router)
{
        $this->registerTranslations();
        $this->registerConfig();
        $this->registerViews();
        $this->loadMigrationsFrom(module_path($this->moduleName, 'Database/Migrations'));

        #solution 1
        $router->middlewareGroup('update', [\Modules\Installer\Http\Middleware\CanUpdate::class]);

        #solution 2
        app()->make('router')->aliasMiddleware('update', \Modules\Installer\Http\Middleware\CanUpdate::class);
}

This work fine!
