### ISSUE TITLE
How the routes to module work?

### ISSUE THREAD

**Issue by sonminh18** [nWidart/laravel-modules#456]
Hello,
I'm using this package and I'm wondering how the routes to module work? Where is the config for route to module?
For example:
I create module "blog" and when I access URL "localhost:8000/blog", It will be pointed towards blogController@index. 
But I wonder how Laravel found the route will point towards /Modules/Blog/Http/routes.php.
I have this question because I want to change the route to module like below.
localhost:8000/admin/blog -> blogController@index.
Thanks.

**Comment by zhiru** [comment]
Hello @sonminh18 ,

In any module you have routes.php file on Http path (example: /Modules/Teste/Http/routes.php), if you look there is prefix on Route:group, that can be admin, system or anything you want.

But for more understanding you can read [Routes Prefixes](https://laravel.com/docs/5.4/routing#route-group-prefixes) and Route Groups from laravel docs 

See ya

:smile:

**Comment by sonminh18** [comment]
Hello @zhiru ,
Thanks for your information. I knew routes.php file in module folder control route and prefix for my module. But i'm looking for why main laravel app route can find routes.php file in module folder, where's config?

**Comment by zhiru** [comment]
ohhh sorry, my bad!!

Some configuration is in config/modules.php, there has the next:

'files' => [
            'start' => 'start.php',
            'routes' => 'Http/routes.php',
            'views/index' => 'Resources/views/index.blade.php',
            'views/master' => 'Resources/views/layouts/master.blade.php',
            'scaffold/config' => 'Config/config.php',
            'composer' => 'composer.json',
        ],

And in start.php is calling the rotues :D
And for laravel app call each module you can look on module.json too

Hope this helps

#badenglish
