### ISSUE TITLE
Use subdomains instead prefix

### ISSUE THREAD

**Issue by richardfeliciano** [nWidart/laravel-modules#457]
Can i use subdomains instead prefix? i mean it will be nice if i can set a subdomain for each module. I mean
blog.example.com responds to routes in Modules/Blog

**Comment by rockymontana** [comment]
It's just the regular Laravel Router that is being used.
So what you'd need to do in your routes-file is to:
```
Route::group(['domain' => 'someModule.example.com'], function() {
    Route::get('/', ['uses' => 'someController@index']);
});
```

**Comment by richardfeliciano** [comment]
Nice

**Comment by GoodM4ven** [comment]
I've managed to workaround the route priority overriding issue - even locally - by enforcing the domain in the main routes file! 😃

1. In the main routes file:

   ```php
   Route::domain('localhost')->group(function() {
       Route::view('/', 'home');
   });
   ```

2. In the module's:

   ```php
   Route::domain('module.localhost')->group(function() {
       Route::get('/', 'ModuleController@index');
   });
   ```
