### ISSUE TITLE
How to Use phpunit for module 

### ISSUE THREAD

**Issue by pc-mon** [nWidart/laravel-modules#458]
Hello
Thank you for great work:)
I just Wanna know how to run phpunit code for one model for example I have Module by name User and then Test class is LoginTest.
How can I test it
Thank you in advance

**Comment by zhiru** [comment]
Hello @pc-mon :D

It not has a sample on the docs, but for make phpunit work, open your phpunit.xml  and create a directory, sample:


    <testsuites>
        <testsuite name="Feature">
			<directory suffix="Test.php">./Modules/Example/Tests/Feature</directory
        </testsuite>

        <testsuite name="Unit">
            <directory suffix="Test.php">./Modules/Example/Tests/Unit</directory
        </testsuite>
    </testsuites>

**Comment by pc-mon** [comment]
Ok I see Thank you:)

**Comment by rockymontana** [comment]
I would recommend to do it like this instead:

```<testsuites>
    <testsuite name="Feature">
		<directory suffix="Test.php">./Modules/**/Tests/Feature</directory
    </testsuite>

    <testsuite name="Unit">
        <directory suffix="Test.php">./Modules/**/Tests/Unit</directory
    </testsuite>
</testsuites>```

That way you won't have to add a configuration for each module.

**Comment by zhiru** [comment]
@rockymontana good to know tks :D

**Comment by Nowi5** [comment]
How do you manage code coverage in this setup. As the modules also include the blade.php my phpunit.xml fails - when running the phpunit testing it responses with the html code from blade files:

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="vendor/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false">
    <testsuites>
        <testsuite name="Feature">
            <directory suffix="Test.php">./tests/Feature</directory>
        </testsuite>
        <testsuite name="Unit">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>

        <testsuite name="Modules">
            <directory suffix="Test.php">./Modules/**/Tests</directory>
        </testsuite>
        <testsuite name="Modules-Feature">
            <directory suffix="Test.php">./Modules/**/Tests/Feature</directory>
        </testsuite>
        <testsuite name="Modules-Unit">
            <directory suffix="Test.php">./Modules/**/Tests/Unit</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
            <directory suffix=".php">./modules</directory>
        </whitelist>
    </filter>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="BCRYPT_ROUNDS" value="4"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="sync"/>
        <env name="MAIL_DRIVER" value="array"/>
		<const name="PHPUNIT_RUNNING" value="true"/>
    </php>
</phpunit>

```

**Comment by dothem1337** [comment]
Any news about this? Any configuration example? I need to export the report HTML.

**Comment by elemes1** [comment]
@dothem1337  here is how i do mine 
`    <logging>
        <log type="coverage-html" target="./.tmp/report" lowUpperBound="35"
             highLowerBound="70"/>
        <log type="coverage-clover" target="./.tmp/coverage.xml"/>
        <log type="coverage-php" target="./.tmp/coverage.serialized"/>
        <log type="coverage-text" target="php://stdout" showUncoveredFiles="false"/>
        <log type="junit" target="./.tmp/logfile.xml"/>
        <log type="testdox-html" target="./.tmp/testdox.html"/>
        <log type="testdox-text" target="./.tmp/testdox.txt"/>
    </logging>`

**Comment by dothem1337** [comment]
@elems1, that doesnt work. It only run 1 test when i add you snipped. And does only scan the "app" folder, not the "modules".

**Comment by elemes1** [comment]
here is a full PHP unit i use for all my module project 

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="vendor/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false">
        <testsuites>
            <testsuite name="Feature">
                <directory suffix="Test.php">./Modules/**/Tests/Feature</directory>
            </testsuite>

            <testsuite name="Unit">
                <directory suffix="Test.php">./Modules/**/Tests/Unit</directory>
            </testsuite>
        </testsuites>
        <filter>
            <whitelist processUncoveredFilesFromWhitelist="false">
                <directory suffix=".php">./Modules</directory>
            </whitelist>
        </filter>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="BCRYPT_ROUNDS" value="4"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_CONNECTION" value="sync"/>
        <env name="MAIL_DRIVER" value="array"/>
        <env name="DB_CONNECTION" value="sqlite" force="true"/>
        <env name="DB_DATABASE" value="database/database.sqlite" force="true"/>
        <env name="DB_DRIVER" value="sqlite" force="true"/>
        <env name="API_STANDARDS_TREE" value="x"/>
        <env name="API_SUBTYPE" value="standard"/>
        <env name="API_DOMAIN" value="127.0.0.1"/>
        <env name="API_VERSION" value="v1"/>
        <env name="API_DEFAULT_FORMAT" value="json"/>
        <env name="API_STRICT" value="false"/>
    </php>
    <logging>
        <log type="coverage-html" target="./.tmp/report" lowUpperBound="35"
             highLowerBound="70"/>
        <log type="coverage-clover" target="./.tmp/coverage.xml"/>
        <log type="coverage-php" target="./.tmp/coverage.serialized"/>
        <log type="coverage-text" target="php://stdout" showUncoveredFiles="false"/>
        <log type="junit" target="./.tmp/logfile.xml"/>
        <log type="testdox-html" target="./.tmp/testdox.html"/>
        <log type="testdox-text" target="./.tmp/testdox.txt"/>
    </logging>
</phpunit>


```
you can ignore the dingo part 
can you post what you use ?

**Comment by Mohib1992** [comment]
what is the console command to run the test.my phpunit.xml is prefect as ppl recommend no top but the console command is saying that it did find the test file

**Comment by doyoque** [comment]
Hello I know it's been a long but I still don't understand why phpunit keep reading the testsuite in tests/ directory. Here's my phpunit.xml
`<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="vendor/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false">
    <testsuites>
        <testsuite name="Unit">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>

        <testsuite name="Feature">
            <directory suffix="Test.php">./tests/Feature</directory>
        </testsuite>

        <testsuite name="Frontend">
            <directory>./Modules/Frontend/Tests</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
        </whitelist>
    </filter>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="BCRYPT_ROUNDS" value="4"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="MAIL_DRIVER" value="array"/>
        <env name="QUEUE_CONNECTION" value="sync"/>
        <env name="SESSION_DRIVER" value="array"/>
    </php>
</phpunit>
`

As you can see I've added new testsuite named Frontend that pointing at /Modules/Frontend/Test directory and the test class is Frontend. Whenever I run ./vendor/bin/phpunit it only test the two of that testsuite (Unit and Feature). Did I miss some configuration or there's something wrong in my Frontend class testsuite?

**Comment by henryonsoftware** [comment]
You can config your phpunit.xml like this
```
<testsuites>
      <testsuite name="Modules">
          <directory suffix="Test.php">./modules/*/Tests/Integration</directory>
          <directory suffix="Test.php">./modules/*/Tests/Feature</directory>
          <directory suffix="Test.php">./modules/*/Tests/Unit</directory>
      </testsuite>
      <testsuite name="Integration">
          <directory suffix="Test.php">./modules/*/Tests/Integration</directory>
      </testsuite>
      <testsuite name="Feature">
          <directory suffix="Test.php">./modules/*/Tests/Feature</directory>
      </testsuite>
      <testsuite name="Unit">
          <directory suffix="Test.php">./modules/*/Tests/Unit</directory>
      </testsuite>
</testsuites>
```

And run `phpunit --testsuite=<TestSuite name>`
Ex: `phpunit --testsuite=Modules`
