### ISSUE TITLE
Get current module instance

### ISSUE THREAD

**Issue by ajoaespinola** [nWidart/laravel-modules#461]
Hello:

I want to manage all the modules with a centralizated user/role control feature, so when a user opens one module I want to get all the role/permissions for that user in that module.

My question is: How can I get the current module instance where the user is located and then used that info to get it's role/permissions?

**Comment by nWidart** [comment]
That's up to you to decide how you want to handle this. This package does not provide such feature but it is possible. Asgardcms has something similar.
