### ISSUE TITLE
start.php file when renamed...

### ISSUE THREAD

**Issue by snipiba** [nWidart/laravel-modules#462]
Main issue:

when you change name of start file for example to init.php instead of start.php,
composer dumpautoload crashed with error about failed to open stream, because
it looks for start.php instead of new filename from configuration..

config/modules.php (configuration for laravel-modules)
`
        'files' => [
            'start' => 'init.php', // instead of start.php
`

error:
In Module.php line 292:
include (path_to_file/*start.php*) expected including file (path_to_file/*init.php*)

***probably needs to check how is generated module.json*** 
where is stored information about start file where is used start.php instead of changed ***init.php***

**Comment by snipiba** [comment]
check #463

**Comment by webmake** [comment]
module.json is the file, which is responsible for loading files, so according your case
```
{
    "name": "Secondary",
    "alias": "secondary",
    "description": "",
    "keywords": [],
    "active": 1,
    "order": 0,
    "providers": [
        "Modules\\Secondary\\Providers\\SecondaryServiceProvider"
    ],
    "aliases": {},
    "files": [
        "init.php"
    ],
    "requires": []
}
```
works well, so I don't understand what's wrong with existing stub generation, apart manual change in json file?

**Comment by nWidart** [comment]
Yeah, I think he wants to remove the manual editing part. Every time he creates a module, he'd like init.php to be used instead of start.php

At least that's my understanding.

**Comment by snipiba** [comment]
nWidart... you got it right...
