### ISSUE TITLE
Error 404 - for routes defined in module, but can see in route:list

### ISSUE THREAD

**Issue by swapnilsarwe** [nWidart/laravel-modules#464]
Hello,

I recently ran `composer update` and `nwidart/laravel-modules` got updated to version `2.7.0` & started getting 404 errors on all the routes defined inside my modules.

Surprisingly I can see all my routes when i run `php artisan route:list`, but when i am hitting from the browser i get `Sorry, the page you are looking for could not be found.`

In the last update too I got the similar issue, but I got it fixed by changing the `scan` value in `config/modules.php`
from
```php
'scan' => [
        'enabled' => true,
        'paths' => [
            base_path('vendors/*/*'),
        ],
    ],
```
to
```php
'scan' => [
        'enabled' => true,
        'paths' => [
            base_path('modules/*'),
        ],
    ],
```

But current version `2.7.0` its not working as expected.

The application was working just fine before I hit composer update. I understand that the package is not breaking, but need guidance in what exactly in update could have triggered this. Coz' according to me changes in update seem fine.
Can anyone guide what exactly did I miss or what I should be looking for this issue?

**Comment by nWidart** [comment]
This is normal.
The behavior has been changed here : https://github.com/nWidart/laravel-modules/pull/441

**Comment by swapnilsarwe** [comment]
Perfect.

But still unable to debug why `route:list` show all my routes, but not working on browser. 
Even after changing the `scan` value, still unable to get the web routes working.

Previous version `2.6.0` it worked the moment i made a fix for  `scan` value in `config/modules.php`. Any guidance is appreciated.

 I am still investigating, will update if I find the root cause & the solution for the same..

**Comment by nWidart** [comment]
Not sure what issue you have. It is indeed possible you have to edit your config/modules.php scan key, but since that's a published file that's ok.

**Comment by swapnilsarwe** [comment]
Well with new installation it works well. Should be able to figure out the solution for my application too.
Closing the issue.

Thanks @nWidart

**Comment by stefnats** [comment]
Whoever stumbles upon this, i had the exact same problem after upgrading to `^6.0`

I just needed to use the new `config/modules.php` file and that fixed the bug.

**Comment by andrefigueira** [comment]
On a fresh install of laravel and this @ v7.2 and i'm also getting this exact same issue, can't seem to figure it out, i can see the routes file is being loaded, the RouteService provider is running, but literally every route i setup within a module gives a 404, really wanna use this package too, but been stuck for days.

**Comment by mahdi29sh** [comment]
> On a fresh install of laravel and this @ v7.2 and i'm also getting this exact same issue, can't seem to figure it out, i can see the routes file is being loaded, the RouteService provider is running, but literally every route i setup within a module gives a 404, really wanna use this package too, but been stuck for days.

hi andrefigueira i haw same issue . fix it or not?

**Comment by stefnats** [comment]
Disclaimer: I don't have that issue.
Did you try to use named routes and use the `route('my.route.name')` helper to display the url?
Did you compare the current version of `RouteServiceProvider` with the current version?

**Comment by otherperspectives** [comment]
I am trying to fix this behavior for more than 6 hours. This is just incredible... Did anyone manage to fix this issue?

**Comment by m-housni** [comment]
I am running into the same issue and can not find any quick fix :/

**Comment by tech-surendra** [comment]
I have similar issue:
->created module "abc" using "php artisan module:make abc"
-> loaded successfully with url: 
--> http://127.0.0.1:8000/abc (php artisan serve) and
--> http://localhost/prj/test1/index.php/abc (apache server)

the problem is that it shows "404" while accessing through
http://localhost/prj/test1/abc
I placed ".htaccess" file from public folder to root folder but didn't worked...
Please share if you have solution....
Laravel 8.4 & laravel-modules 8.2

**Comment by AmirHoseinBahrami** [comment]
i just run php artisan route:cache

**Comment by seongbae** [comment]
Having same issue...
