### ISSUE TITLE
Request does not exist

### ISSUE THREAD

**Issue by BuiHuyCuong** [nWidart/laravel-modules#466]
When i create request file on module, i have a problem:

ReflectionException
Class Modules\Auth\Http\Requests\{requestname}Request does not exist

Can you help me now?
Thanks!

**Comment by nWidart** [comment]
There's probably something wrong with your namespace. Double check that the namespace is correct in both files.

**Comment by BuiHuyCuong** [comment]
before when i implement rules function, it's working, but after isn't working.

**Comment by nWidart** [comment]
Well the error is clearly is namespace/autoloading issue, so I'd start there.

**Comment by BuiHuyCuong** [comment]
Controller: use Modules\Auth\Http\Requests\RegisterRequest;
On Request file, i implement:
<pre>
public function rules()
    {
        return [
            'name'      =>  'required|min:2|max:50',
            'username'  =>  'required|min:4|max:20|unique:users'
            'email'     =>  'required|email|max:50|unique:users',
            'password'  =>  'required|min:6',
        ];
    }
</pre>

i dont understand what error.
