### ISSUE TITLE
modules.used not found

### ISSUE THREAD

**Issue by gzai** [nWidart/laravel-modules#47]
Hello,

when I want to generate new middleware class in command,

show error : 

[Illuminate\Contracts\Filesystem\FileNotFoundException]
File does not exist at path F:\xampp\htdocs\new\black\storage\app/modules/modules.used

how to fix that?

Thank you

**Comment by nWidart** [comment]
Please look at this issue: https://github.com/nWidart/laravel-modules/issues/11

**Comment by gzai** [comment]
Thanks :+1: 

after generate middleware in module, can we add new middleware in routemiddleware in that module, like kernel.php do?
or add in kernel.php routemiddleware as usual?

**Comment by nWidart** [comment]
You can add a middleware however you prefer. Either in the global kernel.php, or in your service provider.

**Comment by gzai** [comment]
Thanks again :)

yeah, can added in module service provider

just add : 

$router->middleware('staf', \Modules\Rights\Http\Middleware\StafOnlyMiddleware::class );
