### ISSUE TITLE
Namespace and path resolving issues

### ISSUE THREAD

**Issue by jnbn** [nWidart/laravel-modules#470]
After installing 2.7.0 I realized that there were many updates including seed command since 2.5.1

The fixes were good but, as I mentioned before, if you're using modules within any subdirectory configuration things are starting to get harder.

I know that scan paths issue were fixed recently but as I realized we're concatenating our seeder names like

```
return $namespace . '\\' . $name . '\\' . $seederPath . '\\' . $name . 'DatabaseSeeder';
```

which resolves to Modules\Modulename\src\Database\Seeders\Seeder name which is also invalid.

I didn't want to go with a quick fix so I wondered how we can solve this with a much more simple way instead of fixing it on SeedCommand.php.

As there's no other way than removing 'src/' [that's not a common solution] or find a new way of returning the namespace from all modules in a more generic way instead of an assumption of path string leads to it.

Can anybody please also try to work on some test cases using ./src as their psr-4 autoload and adding src/ as a path prefix on generator config like below on forthcoming versions?

```
'config' => ['path' => 'src/Config', 'generate' => true],
'command' => ['path' => 'src/Console', 'generate' => true],
'migration' => ['path' => 'src/Database/Migrations', 'generate' => true],
...
...
...

**Comment by nWidart** [comment]
Hello,

Sorry for the late reply here.
I'm not sure what the issue is. If you have an src/ folder, you can just rename the modules folder in the config file to src.

**Comment by jnbn** [comment]
I mean 

We were using a custom configuration for generating packages to use as vendor packages later on. So we have a structure like

```
Modules
| - ModuleName
   | - src
       | -  ...
```

But we end up with directory issues (like on DatabaseSeeders etc) as the paths were defined as src/... but there were no src's shown under vendor.

We decided to define different namespaces for each module on composer that references src folders and continue with default config file.

So we can mark it as resolved for now.

**Comment by rockymontana** [comment]
Having this issue too. I don't want to keep my tests and config stuff in the same directory as my src. But when updating the path the namespaces becomes `Module\ModuleName\src\Providers\`, but I don't want the src in the namespace. 

I think it would make sense to separate the path from the namespace in the config. 

Is that possible?

Sorry for hijacking your thread jnbn 😬

**Comment by nWidart** [comment]
Hello @rockymontana ,

This is indeed already possible, there is a `namespace` key you can set, [example](https://github.com/nWidart/laravel-modules/blob/master/tests/Commands/JobMakeCommandTest.php#L78).

**Comment by rockymontana** [comment]
Perfect! Thanks
