### ISSUE TITLE
  Type error: Argument 1 passed to Nwidart\Modules\Commands\SeedCommand::reportException() 

### ISSUE THREAD

**Issue by karneaud** [nWidart/laravel-modules#471]
I'm running ASGARDCMS 3.4 and using Laravel Framework 5.5.31 with PHP >= 7

I n trying to run the command `php artisan module:seed {modulename}` I get the subject error

>    Type error: Argument 1 passed to Nwidart\Modules\Commands\SeedCommand::reportException() must be an instance of Exception, instance of Error given, called in /home/vagrant/Code/dohlapse/vendor/nwidart/laravel-modules/src/Commands/SeedCommand.php on line 50

**Comment by nWidart** [comment]
Thanks for reporting the issue, this is a duplicate of #465
