### ISSUE TITLE
Class 'Modules\Support\Providers\SupportServiceProvider' not found

### ISSUE THREAD

**Issue by altdev91** [nWidart/laravel-modules#475]
I create a new project with laravel 5.6, after I create module Support and visit home page abc.com

get error: 

Class 'Modules\Support\Providers\SupportServiceProvider' not found

Please help me fix it!

**Comment by nWidart** [comment]
which version of laravel-modules did you use?

**Comment by altdev91** [comment]
I run composer require nwidart/laravel-modules
This cmd get 3.0 version?

**Comment by guicara** [comment]
Hello @nWidart,

I would like to update my Laravel project from 5.5 to 5.6.
The 3.0 version of `laravel-modules` is not yet tagged on Github and on packagist. Do you know when you will release this new version?

Thanks ;)

**Comment by nWidart** [comment]
Soon™. You can already use version `3.0-dev` if you're 5.6
