### ISSUE TITLE
module not found?

### ISSUE THREAD

**Issue by huglester** [nWidart/laravel-modules#476]
Hello, 

I am using 2.7 version.
if I do: ```php artisan module:make Tests```
```module:make Users```
- it all works
but:
```module:make Exchanges``` - when I go to:
```/exchanges``` I get:
No hint path defined for [exchanges].

So it finds the controller (probablay because of routes.php).
But ServiceProvider is not loaded (tries dd()) - what could be wrong?

**Comment by nWidart** [comment]
You can check if the routes exists, if there's a matching controller etc.
