### ISSUE TITLE
Empty strings for model root directory

### ISSUE THREAD

**Issue by rockymontana** [nWidart/laravel-modules#477]
Hello!
at the moment it’s not possible to set an empty directory for the module root in modules.php.
Let’s say that I would want to keep models within the root directory as is within a basic Laravel application (modules/moduleName/ModelName.php).
I’ve tried with empty string and a “/“, but when doing any of that an error is being thrown.
Is it possible to do that or is it limited to live within an actual subdirectory in the module?
I see that the default is Entities, but I would like to keep my modules as much like the app-directory as possible.

If it’s not possible I might be able to throw in an PR when I get the time, but I wanted to check with you first.

Thanks for an awesome package!

**Comment by nWidart** [comment]
Hello,

If I understand it correctly you would like to have your module in the root of laravel so : 

- app/
- config/
- Module1
- Module 2

If this is correct, it isn't possible

**Comment by rockymontana** [comment]
No, you misunderstood. Sorry if I was being vague.

What I want is for my models to live within the **modules**  root directory.
So let's say that I have a module called MyModule.
Then the path to that module would be `Modules/MyModule` - right.
Now I want to create a model for MyModule called `SomeModel`, but I don't want it to be placed in `Modules/MyModule/Enteties/` but rather directly in the module root directory (`Modules/MyModule`).

So when I'm generating it, the generator looks to `config('modules.generator.model')` to know where it should be placed.
If I set the path in the model to be an empty string I thought it would create the model in `Modules/MyModule`, but instead it throws an error.
Is there a way to configure so that scaffolded models will be placed within the root directory of the module or do they have to live within a subdirectory (such as Enteties)?
I've also seen that if I delete the model config all together it will still set the namespace to be `\Modules\MyModule\Enteties` (I guess it's falling back on the configuration of the package if it's not defined at all?)

Example:
`config/modules.php`
```'generator' => [
    'config' => ['path' => 'Config', 'generate' => true],
    'model' =>  ['path' => '/', 'generate' => true],
]```

**Comment by nWidart** [comment]
Ah ok I see.
Hm I wouldn't recommend doing this, but I agree it should be possible. Though it might require a lot of changes which might not be worth it for the value.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
