### ISSUE TITLE
Method has() inconsistency

### ISSUE THREAD

**Issue by vmosoti** [nWidart/laravel-modules#480]
Seems like the function `has($name)` is inconsistent with how the parameter `$name` is passed
example:

`Module::find('Blog')` //successful if module Blog exists
`Module::find('blog') ` //successful if module Blog exists

`Module::has('Blog')` //returns truel if module Blog exists
`Module::has('blog')`  // returns false if module Blog exists

Perhaps use method `getLowerName()` inside `has()` ? or is this by design?

**Comment by nWidart** [comment]
I don't think this is possible as the `has()` method reads the `all` array, which contains all modules in original casing.

I think it's fine for now that `has()` is strict.
