### ISSUE TITLE
api route is not working with middleware

### ISSUE THREAD

**Issue by MicroDreamIT** [nWidart/laravel-modules#481]
Version L5.6

here is my main kernel is look like, 

kernel.php
```
protected $routeMiddleware = [
        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'cache.headers' => \Illuminate\Http\Middleware\SetCacheHeaders::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'company'=>\App\Http\Middleware\CompanyMiddleware::class
    ];
```

RouteServiceProvider.php
```

protected $namespaceInventory = 'Modules\Inventory\Http\Controllers';
public function map()
    {
        $this->mapApiInventoryRoutes();
    }

protected function mapApiInventoryRoutes()
    {
        Route::prefix('api')
            ->middleware('api')
            ->namespace($this->namespaceInventory)
            ->group(base_path('/Modules/Inventory/routes/api.php'));
    }
```
api.php
```
Route::group(['middleware' => ['auth:api', 'company']], function () {
    Route::resource('inventory/warehouses', 'WarehouseController');
```

Problem 1: auth, company middleware is not working because its looking into inventory/http. What's is the solution
 Problem 2: I am Logged in Web route but not logged in in api routes, why?

**Comment by nWidart** [comment]
Api routes are working with middlware, I use it all the time with this package. You can view examples of this in AsgardCMs.

Make sure you define your middleware according to the documentation.

**Comment by nWidart** [comment]
Yes, that's what I do too.

**Comment by MicroDreamIT** [comment]
where is the problem then in this code, 
Modules/Inventory/routes/api.php
```
Route::group(['middleware' => ['auth:api', 'company']], function () {
    Route::resource('inventory/warehouses', 'WarehouseController');
```
problem1: auth is not found. Its searching for `Class Modules\Inventory\Http\Controllers\Auth\LoginController does not exist`

why is that?

**Comment by nWidart** [comment]
I don't know. From what you've shown I don't see why the login controller would be called.

**Comment by pbalan** [comment]
@MicroDreamIT @nWidart I have the same question. Doesn't work with Laravel 5.5 for me.

**Comment by buruhsd** [comment]
i have same problem, i m using laravel passport oauth. and when i created api it still unauthenticated.
![Cuplikan layar dari 2019-07-11 12-50-18](https://user-images.githubusercontent.com/3405292/61025305-7e611380-a3da-11e9-9fb8-5249b09b1899.png)

this is my controller:
![Cuplikan layar dari 2019-07-11 12-51-27](https://user-images.githubusercontent.com/3405292/61025342-a05a9600-a3da-11e9-96d7-64a48910c39d.png)
`public function __construct()
    {
        $this->middleware('auth:api');
    }

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        return Menu::get();
    }
`
and this is my route inside route module folder

`Route::apiResources([
    '/skenjo' => 'SkenjoController',
]);`

**Comment by JamesBuretta** [comment]
Add this  'client_credentials' => \Laravel\Passport\Http\Middleware\CheckClientCredentials::class  on your Kernel.php on your laravel project

**Comment by JamesBuretta** [comment]
Also add bindings if not included on the Kernel.php on this part ..... 'api' => [
            'throttle:60,1',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
            'bindings',
        ], ......
