### ISSUE TITLE
View share in App\Controller ad Routing\Controller

### ISSUE THREAD

**Issue by mahmoudarafat** [nWidart/laravel-modules#482]
I have [ View::share ] in App\Http\Controller.
what should I do to make this share found in [ Routing\Controller ] in all modules.

in Usual use I can make routes with Parent Controller.
How can I make route with parent controllers that is used in modules

**Comment by nWidart** [comment]
I'm not sure what you're trying to achieve. 

You can use all laravel features with modules.
