### ISSUE TITLE
How to use created models for the modules

### ISSUE THREAD

**Issue by dbsoftsolutions** [nWidart/laravel-modules#484]
Hi,
I just started using your package for Laravel 5.5 (have not upgraded to 5.6 just yet). I created a new module called "Core" in which I created a model called "Role" which is located in Modules\Core\Entities\Role.php. I use this with the default Laravel login system where it is to work with the User model found under - app\User.php

I have 2 questions:

1) If I am to create an Eloquent relationship between the two models, for User.php I added:

`use Modules\Core\Entities\Role;`

and added the following function:
`public function role(){`
`return $this->hasOne(Role::class, 'roleid');`
`}`

I assumed that is correct?

2) When using PHP tinker, when I try to create an object using:
`$role = new Modules\Core\Entities\Role;`
I get the following error:

`PHP Fatal error:  Undefined constant Modules\Core\Entities\Role in eval()'d code on line 1`

How do I get this to work? Sorry but I could not find this in the documentation.

**Comment by nWidart** [comment]
Hello,

You can use the usual laravel way of defining relationships.
I'm not familiar with your php tinker. 
Please refer to the laravel documentation for relationships.
