### ISSUE TITLE
Laravel 5.6 has deprecated optimize command

### ISSUE THREAD

**Issue by OscarKoitla** [nWidart/laravel-modules#487]
For the 3.x branch the package still calls optimize command in MigrationMakeCommand.php:161

As for 5.6 this was removed: https://github.com/laravel/framework/pull/20851/files

**Comment by nWidart** [comment]
Thanks for reporting this. I'll fix it asap.

**Comment by Bipinkumarr2050** [comment]
can I place two sub modules into one simple folder under modules folder like 
modules
       test
             test1(http folder, resource folder and so on)
             test2(http folder, resource folder and so on)

**Comment by billyadelphia** [comment]
this issue has been fixed ? I get `Command "optimize" is not defined.` while create migration

**Comment by nWidart** [comment]
it has, but I still need to release this. I'll try to do this today.

**Comment by nWidart** [comment]
tagged in 3.1, sorry for the delay!

**Comment by felipemarques** [comment]
Thankyou @nWidart !
