### ISSUE TITLE
How to get current module name. 

### ISSUE THREAD

**Issue by AgustinJimenez** [nWidart/laravel-modules#488]
Is there any method for this feature?

**Comment by nWidart** [comment]
Hello,

Yes, you can find your module using the Repository class or Module class, and call ->name() on it.

**Comment by AgustinJimenez** [comment]
Do you mean something that work like this? 
`$current_path[array_search( 'Modules', $current_path = explode( '/', __FILE__) )+1]`

using just `\Module::name()` ?

**Comment by nWidart** [comment]
No: https://github.com/nWidart/laravel-modules/blob/master/tests/RepositoryTest.php#L75
and on the module class you have methods to get the name.
