### ISSUE TITLE
module:migrate-rollback doesnt take an --database option

### ISSUE THREAD

**Issue by hatem93** [nWidart/laravel-modules#49]
hey there, thanks alot for this package it have been very useful to me ,i have been having a problem with trying to rollback a certain module  in a certain database not the default one , it is working correctly with module:migrate by stating --database=connectionName

**Comment by Abusal7** [comment]
+1

**Comment by nWidart** [comment]
Hello,

This is currently not possible indeed, because it's using a custom migrator class.

Feel free to send in a pull-request to make this work.

This would be where the change is needed: https://github.com/nWidart/laravel-modules/blob/master/src/Migrations/Migrator.php#L96
