### ISSUE TITLE
Customize the file-name of generated classes

### ISSUE THREAD

**Issue by Brotzka** [nWidart/laravel-modules#490]
Hey,

I'm generating some additional files (e.g. routes). So I've copied all the stub-files from your package to a sub-folder in my project-directory and changed the config:

```
'stubs' => [
        'enabled' => true,
        'path' => base_path() . '/stubs/modules',
        'files' => [
            'start' => 'start.php',
            'routes' => 'routes/frontend.php',
            'routes-dashboard' => 'routes/dashboard.php',
            'controller-frontend' => 'Http/Controllers/FrontendController.php',
            // other files
        ],
        'replacements' => [
            'start' => ['LOWER_NAME', 'ROUTES_LOCATION'],
            'routes' => ['LOWER_NAME', 'STUDLY_NAME', 'MODULE_NAMESPACE'],
            'routes-dashboard' => ['LOWER_NAME', 'STUDLY_NAME', 'MODULE_NAMESPACE'],
            'controller-frontend' => ['CLASS_NAMESPACE', 'CLASS', 'LOWER_NAME','STUDLY_NAME', 'MODULE_NAMESPACE'],
            // other replacements
        ],
        'gitkeep' => true,
    ],
```

So I've created an other controller in my stub-directory named ``controller-frontend`` with the following content:

```
namespace $MODULE_NAMESPACE$\$STUDLY_NAME$\Http\Controller;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;

class $STUDLY_NAME$FrontendController extends Controller
{
    // methods ...
}
```

This works fine. But unfortunately the file name of the created controller could not be changed. It is hard-coded in my config-file (see above). I've tried something like ``'controller-frontend' => 'Http/Controllers/$STUDLY_NAME$FrontendController.php'``. Nothing works. It has to be named like ``[ModuleName]FrontendController.php``.

Is there a way of modifing the file name of created files dynamically? 

Thanks in advance!

**Comment by nWidart** [comment]
Hello,

What you seem to desire here is not possible out of the box. However it is doable. In AsgardCMS for instance I wrapped the `module:make` command with another command, that adds and removes files as needed for that project.
This way you can do whatever you want with the structure, make something custom for your company etc.

**Comment by Brotzka** [comment]
Hi,

thanks for that tip. I'll give it a try.
