### ISSUE TITLE
Module.json providers

### ISSUE THREAD

**Issue by dev-itbinc** [nWidart/laravel-modules#491]
Hello. I created module, required package via composer and added Providers to module.json. But when i require this module with module-installer. Application has exception like "Class 'vendor/package/ServiceProvider' not found". Its because my application doesnt download vendor of module. So its because i cant launch 'artisan module:update'. Maybe you any suggestion?

**Comment by nWidart** [comment]
Hello,

Where did it install the dependency?
Try to run the `composer require ` command in the root of your project.

**Comment by dev-itbinc** [comment]
@nWidart i need to require it for Module, and when im making composer require myVendor/myPackage i need to install the module dependencies to root vendor. 

Now im doing like this: im disable Module, then making php artisan module:update Module, then enabling module. But to disable module i need to do it hard in module.json cause i have Exception Class not found

**Comment by nWidart** [comment]
You have to run it in the root dir, otherwise your project won't be able to use it.

**Comment by dev-itbinc** [comment]
@nWidart so, how i can use it as a composer package? Maybe any suggestion?

**Comment by dev-itbinc** [comment]
@nWidart in producation i will execute "composer require vendor/myModule" and i need to install all dependency to global vendor

**Comment by nWidart** [comment]
I'm not sure what you want but you can read this part: https://github.com/nWidart/laravel-modules/pull/472

It covers the dependencies info.

**Comment by SpinyMan** [comment]
@dev-itbinc I met this problem too and I found solution!
1) Rename section `providers` in `module.json` into `_providers`
2) open `start.php` and add at the beginning:
```
/** @var \Nwidart\Modules\Module $this */
foreach ($this->get('_providers', []) as $provider) {
	if( !class_exists($provider) ) continue;

	$this->app->register($provider);
}
```
3) Run command `php artisan module:install`

PS: Possible problems: you have to insert this code in every module's `start.php` where section `providers` is used.

That's it!
