### ISSUE TITLE
Change structure folder

### ISSUE THREAD

**Issue by altdev91** [nWidart/laravel-modules#493]
I want change structure from
`{root project}/Modules/Module_Name/`
to
```
{root project}themes/theme_name/Module_Name/
{root project}themes/theme_name2/Module_Name/
{root project}themes/theme_name3/Module_Name/
```
Ex: I have a Modules Blog

Current, {root project}/Modules/Blog
I want:
+ {root project}/themes/storefront/Blog
+ {root project}/themes/twentyfifteen/Blog

Thank you so much!

**Comment by nWidart** [comment]
Hello,

This won't be possible out of the box. However, you can easily wrap the make command to do what you want here.

I'll close this issue as it's out of the scope of this project.
