### ISSUE TITLE
Defer Module provided ServiceProviders

### ISSUE THREAD

**Issue by Levivb** [nWidart/laravel-modules#495]
Hey,

Note: I did see this (closed) issue: https://github.com/nWidart/laravel-modules/issues/89
But since it's been almost 1.5 years it might be worth to take another look at this.

In Laravel 5.4 and before, the ModulesServiceProvider would loop through the modules which in turn would register all known providers in the app. Regardless of the `defer` property. Now I understand the rationale behind this as Laravel doesn't seem to call any method when creating the services.php. So there's no way to support the `defer` property from the modules. It would've been better though, to throw a LogicException in `laravel-modules/src/Module.php:272` (`v1.30`) when the `$provider->isDeferred()` resolved to `true`. Developers are falsely under the impression their Providers are deferred.

Now in Laravel 5.5 the Modules aren't looping through their own list of Providers but are using the Laravel 5.5 provided `ProviderRepository`:
```php
(new ProviderRepository($this->app, new Filesystem(), $this->getCachedServicesPath()))
            ->load($this->get('providers', []));
```
in `laravel-modules/src/Laravel/Module.php:26`
As such, the `defer` property is no longer ignored, but due to the lack of support for loading deferred ServiceProviders from the Modules, the deferred ServiceProvider is no longer called at all. It took me a while to figure this out, especially since not a single command to flush any of the caches (`redis flushall`, `artisan cache:clear`, `artisan view:clear`, `artisan clear-compiled`), does actually flush the `[module_name]_module.php` in bootstrap (`laravel-modules/src/Laravel/Module.php:18`).

When upgrading from `laravel-modules` `v1.30` to `v2.7` the cached service files are generated once and then never flushed. So after setting the property `defer` in a Module provided ServiceProvider to `false`, the change is ignored forever. (or until you manually remove `bootstrap/cache/*.php`) I'll create a separate issue for this here: https://github.com/nWidart/laravel-modules/issues/494

Now, the compiled manifest file is written here: `laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:149` (`laravel/framework` `v5.5.35`)
At this moment I don't see any way to hook into the writing of the manifest, but you might have a better understanding of the laravel framework as creator of this package.

A potential fix would be to use the `isDeferred` call in the `ModulesServiceProvider`. This would resolve to true as soon as there's a deferred ServiceProvider in one of the modules and the `provides` method of the ModulesServiceProvider will provide the combined result of all `provide` methods on the deferred ServiceProviders in the Modules. This would expand the responsibility of the ModulesServiceProvider though, since now all provided bindings in the Module provided deferred ServiceProviders will resolve to the ModulesServiceProvider.

Another possible solution (I suppose) would be to extend the ProviderRepository to overrule the `compileManifest` method and use that class in `laravel-modules/src/Laravel/Module.php:26`

Either way, if the deferred loading of ServiceProviders can't be fixed, it would be extremely helpful to throw a LogicException to make the developers aware that their ServiceProvider will never be registered anymore.

But I'll leave that up to you.

Let me know what you think.

Regards,
Levi

**Comment by nWidart** [comment]
Hello,

This has been fixed since [2.1.0](https://github.com/nWidart/laravel-modules/releases/tag/2.1.0).

👍

**Comment by Levivb** [comment]
That response time though! :open_mouth:

But, hmm, that's weird. We're using 2.7.0.
Is there some setting or config I should be taking into account?
Could you point me to the commit in which it is fixed, so I can take a look at the implementation (just curious)

Regards,
Levi

**Comment by nWidart** [comment]
Hm strange, this was the PR adding this feature: https://github.com/nWidart/laravel-modules/pull/322 done by @mathieutu .

**Comment by Levivb** [comment]
Yup, it works now. This was the careful collaboration of my lack of understanding of deferred ServiceProviders, the funky Laravel documentation (missing the `boot` method example in https://laravel.com/docs/5.5/providers), an incorrect copy-paste and the `[module_name]_module.php` which was never rewritten (https://github.com/nWidart/laravel-modules/issues/494) despite changes to the `defer` property.

Thanks for the exceptional fast response and pointing me into the right direction!

**Comment by nWidart** [comment]
Ah nice good to know you made it working! 👍
