### ISSUE TITLE
Laravel Scout Command is not here

### ISSUE THREAD

**Issue by rakib-09** [nWidart/laravel-modules#499]
I want to run artisan command inside module directory. I want to import my product model. 

I tried this way : 
`php artisan scout:import '\Modules\Details\Entities\Product'
`
But Its not working. 
Can anyone help me ??
Thanks in advance.

**Comment by BrekiTomasson** [comment]
Shouldn't it be enough to just invoke Scout by using the Searchable Trait in your product model?

**Comment by nWidart** [comment]
I haven't used scout before, but I can assume that it's indeed just like any other php feature. Just follow its documentation.

**Comment by mehrdad517** [comment]
i use this package and i want import product model in elastic. when model created in app directory its work but when we used in module directory laravel scout not imported correctly

**Comment by meshjak** [comment]
![image](https://user-images.githubusercontent.com/70071758/133800297-bd061f1f-c612-4b68-91b3-95b8b09a885d.png)
i run command and i havent any problem
use ( " ) instead of ( ' ) and use
