### ISSUE TITLE
Class 'Modules\{Module-name}\Providers\PagesServiceProvider' not found

### ISSUE THREAD

**Issue by teddywest32** [nWidart/laravel-modules#5]
I have installed your module and created a module and got some error.
https://gist.github.com/teddywest32/5d762735723619a67493c69cc8201b0f
I tried changing "module" folder to "Module" and php artisan started working but when i tried to create a controller it gave an error.
https://gist.github.com/teddywest32/8b268b57ef2b86bc03ba22e6d86e76ce

Could you confirm this is some issue or i am doing something wrong?

**Comment by adelowo** [comment]
You need to register the provider in `module.json`. I think the second gist has to do with autoloading though, you could run `composer-dumo-autoload` or `module:dump`

**Comment by teddywest32** [comment]
@adelowo I have provider registered in <code>module.json</code>
{
    "name": "Pages",
    "alias": "pages",
    "description": "",
    "keywords": [],
    "active": 1,
    "order": 0,
    "providers": [
        "Modules\\Pages\\Providers\\PagesServiceProvider"
    ],
    "aliases":{},
    "files": [
        "start.php"
    ]
}

I have tried running <code>composer dump-autoload</code> and <code>php artisan module:dump</code>.
They work perfectly fine but when i run <code>php artisan module:make-controller HomeController pages</code> 
it still gives
<code>
[Nwidart\Modules\Exceptions\ModuleNotFoundException]
Module [pages] does not exist! </code>

**Comment by nWidart** [comment]
By any chance, to try to pinpoint the issue, do you have caching enabled in the config file ?

**Comment by teddywest32** [comment]
@nWidart I have the default cache.php that laravel provides
https://gist.github.com/teddywest32/f2f49135bc0f242eea7e636c1cb7d9d5

Also tried to clear cache, delete views, sessions but it didn't worked.

**Comment by nWidart** [comment]
I'm talking about caching in modules.php

**Comment by teddywest32** [comment]
@nWidart It is set to false.

    'cache' => [
        'enabled' => false,
        'key' => 'laravel-modules',
        'lifetime' => 60,
    ],

**Comment by nWidart** [comment]
alright, then it must be something related to the autoloaded / registering of the module. Make sure the module is loaded correctly.

**Comment by teddywest32** [comment]
@nWidart I got the solution to my issue. Firstly there is an error in the module folder naming convention in modules.php.
<code>
'modules' => base_path('modules'),
</code> 
should be 
<code>
'modules' => base_path('Modules'),
</code>

Secondly i had to register the module for the first time using
<code>php artisan module:setup</code>

Thanks for the hint ;)
Also could you change the <code>module</code> folder to <code>Module</code>
else it would give the error as:
<code>
[Nwidart\Modules\Exceptions\ModuleNotFoundException]
Module [Pages] does not exist! 
</code>

**Comment by nWidart** [comment]
I will thanks 😄

**Comment by nWidart** [comment]
Done. https://github.com/nWidart/laravel-modules/commit/b29bcb26c1470c5663a1138f83acb215accf5b84

**Comment by GhulamJafar** [comment]
I am have installed you package for module management "nWidart" with git hub guide.
I have just installed and created new Module "Page" and I am getting error.
"Class 'App\Modules\\Page\Providers\PageServiceProvider' not found"

Other strange thing is that when i see the module.json or any other file is showing namespace like below
Module.json
"App\\Modules\\\\Page\\Providers\\PageServiceProvider"
Composer.json
"App\\Modules\\\\Page\\": ""
routes.php
Route::group(['middleware' => 'web', 'prefix' => 'page', 'namespace' => 'App\\Modules\\\Page\Http\Controllers'], function()
{
	Route::get('/', 'PageController@index');
});
Why its showing the double slashes everywhere. Please let me know is this module stable. I have to build Employee portal and i am new to laravel. Can you guide me about below things. 
1.How to add make facade of module to access module in another module?
2. How to manage assets? I have admin assets will be used in different modules. So how can i set assets used in all modules? I want assets on centralized place accessible for all modules
I have laravel 5.2
thanks

**Comment by nWidart** [comment]
This package is stable and being used for about 2 years on [AsgardCMS](https://asgardcms.com/), however you need to know how to use composer.

**Comment by GhulamJafar** [comment]
Why its creating double slashes in it? why its adding app before module? Is it right?

**Comment by GhulamJafar** [comment]
Sorry issue resolved with above steps. 

But i think issue was due to another module package in laravel installation. Its Caffenate.

I have installed fresh laravel and added you module its fixed the issue. Now its working fine.

Now i have 2 question.
Why we need to execute below commands?
>composer dump-autoload
>php artisan module:dump

**Comment by lex0r** [comment]
I'm not sure the issue is really fixed. I got same errors as @GhulamJafar namely:

`Parse error: syntax error, unexpected '\' (T_NS_SEPARATOR), expecting identifier (T_STRING)`
because of
`'App\Modules\\Test\Providers\TestServiceProvider'` being used in the generated module code instead of `'App\Modules\Test\Providers\TestServiceProvider'`.

This looks like a generator issue, I managed to fix it by replacing globally in the modules code instances of `Modules\\` with `Modules\`.

**Comment by teddywest32** [comment]
@lex0r I am still using this package to create my all of the modules and is not facing any issue with it.

I am not sure but why are you trying to create the `Modules` directory inside `App` ??
Could you post your `modules.php` file located inside your `config`  directory?

**Comment by ikbal1989** [comment]
how to get current module name in controller

**Comment by nWidart** [comment]
You can use the `Repository` class.

**Comment by m-muttaqi** [comment]
Delete that module you just created. Try to make a plain module using `php artisan make:module Blog --plain`. It will solve the issue..
