### ISSUE TITLE
Fresh install on linux: There are no commands defined in the "module" namespace.

### ISSUE THREAD

**Issue by yassersharaf** [nWidart/laravel-modules#501]
Hi,

I'm trying to install the package on a fresh laravel project on linux. I do

    php composer.phar dump-autoload

    php composer.phar require nwidart/laravel-modules

Then

    php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"

But no Modules directory is created and the config/app is not edited at all. Then I add this to the composer.json in the autoload section

    "Modules\\": "Modules/"

Then

    php composer.phar dump-autoload

When I want to create a model I get this

     There are no commands defined in the "module" namespace. 

The "nwidart" folder exists in "vendor" folder.

vendor/composer/autoload_files.php contains:

    '9f394da3192a168c4633675768d80428' => $vendorDir . '/nwidart/laravel-modules/src/helpers.php',

vendor/composer/autoload_psr4.php contains this:

    'Nwidart\\Modules\\' => array($vendorDir . '/nwidart/laravel-modules/src'),
    'Modules\\' => array($baseDir . '/Modules'),

In error log

[2018-03-05 12:53:17] local.ERROR: Symfony\Component\Console\Exception\CommandNotFoundException: There are no commands defined in the "module" namespace. in /opt/lampp/htdocs/blog/vendor/symfony/console/Application.php:564
Stack trace:

#0 /opt/lampp/htdocs/blog/vendor/symfony/console/Application.php(604): Symfony\Component\Console\Application->findNamespace('module')

#1 /opt/lampp/htdocs/blog/vendor/symfony/console/Application.php(229): Symfony\Component\Console\Application->find('module:make')

#2 /opt/lampp/htdocs/blog/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#3 /opt/lampp/htdocs/blog/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#4 /opt/lampp/htdocs/blog/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

Any solution?

**Comment by yassersharaf** [comment]
[Update]

The "nwidart" folder exists in "vendor" folder.

vendor/composer/autoload_files.php contains:

    '9f394da3192a168c4633675768d80428' => $vendorDir . '/nwidart/laravel-modules/src/helpers.php',

vendor/composer/autoload_psr4.php contains this:

    'Nwidart\\Modules\\' => array($vendorDir . '/nwidart/laravel-modules/src'),
    'Modules\\' => array($baseDir . '/Modules'),

**Comment by Goten87** [comment]
find the psr-4 in the composer.json and add this or replease it
"psr-4": {
            "App\\": "app/",
            "Modules\\": "Modules/"
        }

sorry dont know how i make it nice looking with a frame around it

**Comment by yassersharaf** [comment]
Hi Goten87,

I already added the code to the autoload 

    "Modules\\": "Modules/"

The modules directory doesn't exist at all after installing and publishing the plugin via composer.

**Comment by nWidart** [comment]
It looks like you didn't install it correctly. 

If it shows that error it means laravel isn't aware of the package. Please follow the install instructions. 

You don't have to edit config/app.php

**Comment by Goten87** [comment]
the module folder is made when u do the command `php artisan module:make <module name>`
when u do that the folder will be made if it dont exist
and yeah u dont have to do anything in any php files 
i just had to do the `psr-4` part and dump again that was wat fixed it for me

**Comment by nWidart** [comment]
But the error is not related to that module folder. It is saying that the commands `php artisan module:` don't exist.

You can verify this by typing `php artisan` and it'll show you all available commands. If the module related commands are not present, it means the package wasn't installed correctly.

**Comment by yassersharaf** [comment]
https://app.box.com/s/dui44vjbhivhbxs43afe1a9hk6uxwrv3
https://app.box.com/s/y1rib8b5ynjjpgggq74d2q166cwxhkf7
https://app.box.com/s/mflhru5uf4eye0gqtdnxd0zdkkrcneru
https://app.box.com/s/i2lx568m1vhqoxoo7d7cdidnze4mo9yn
https://app.box.com/s/wcweipi6jyps2xb7du4taxuif0shhasx
https://app.box.com/s/8iltvcdlxphy3ou3lrjza3q5cqgd5xya

Have a look at the screenshots please. A new fresh Laravel project I didn't change anything at all.

**Comment by nWidart** [comment]
From you screenshot it shows that you're using laravel 5.4 . Meaning you can't follow the instructions for laravel 5.5+ which has autodiscovery.

This means that you need to add the service provider of the package, in config/app.php.

This is explained here: https://nwidart.com/laravel-modules/v1/installation-and-setup

**Comment by yassersharaf** [comment]
That solved the problem Thank you.

**Comment by nWidart** [comment]
Awesome. 👍
