### ISSUE TITLE
Eloquent relationship problem

### ISSUE THREAD

**Issue by rakib-09** [nWidart/laravel-modules#502]
I tried to make hasmany relationship between models.
one model located at  `App\User` and  another one ` Modules/Profile/entities/Userinfo`.
How can I make this relation through model ?

**Comment by IllyaMoskvin** [comment]
This seems like a general Laravel question, not specific to this project. You may have better luck at the [Laravel Forum](https://laravel.io/forum) or StackOverflow.

We can't help you without seeing your code or being provided more details. It's not clear whether your relationship is a many-to-many or a many-to-one. It's also not clear which way you want the relationship to go.

However, if I'm understanding correctly, you just need to specify the full namespace path to the model. Assuming your relationship is that a `User` `hasOne` `Userinfo`, i.e. the `users` table has a column named `userinfo_id`, your code should look something like this:


```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{

    public function userinfo()
    {
        return $this->hasOne('Modules\Profile\Entities\Userinfo');
    }

}
```
...and:
```
<?php

namespace Modules\Profile\Entities;

use Illuminate\Database\Eloquent\Model;

class Userinfo extends Model
{

    public function users()
    {
        return $this->hasMany('App\Users');
    }

}
```

You could alternatively add `use` statements, e.g. `use App\User` and `hasMany(User::class)` to `class Userinfo`. But in either case, this question doesn't seem specific to `laravel-modules`.

**Comment by rakib-09** [comment]
@IllyaMoskvin I am asking this question here because in laravel one to one relations we write like: 
In the User model:
` public function phone()
    {
        return $this->hasOne('App\Phone');
    }`
and in the Phone model we write:
` public function phone()
    {
        return $this->hasOne('App\User');
    }`
but when I am using `laravel-module` there is two of my models are in different place. 
**User** model is in the App folder and **Userinfo** model is inside the Modules/Profile/Entities folder.

and in the documentation of `laravel-module` there is no topic on **eloquent-relationships**. 
for that I am asking this question here. 

and I wish now you understand what I need actually.

**Comment by rakib-09** [comment]
@IllyaMoskvin my problem is solved !!
Actually I mismatched the namespace name. 
Thank you 💯
