### ISSUE TITLE
Cannot use module translations in module service provider

### ISSUE THREAD

**Issue by benkelukas** [nWidart/laravel-modules#507]
Hi,
I'm trying to build a menu using ```nwidart/laravel-menus``` from a Module service provider, everything works, however I'm not able to use translations from module in the service provider, framework translations loads fine, but module translations seems not to be loaded at that point (in service provider).

Here is the relevant code from my module service provider
``` 
Menu::create('admin-sidebar', function (MenuBuilder $menu) {
    $menu->style('coreUiSidebar');

    $menu->route(
        'admin.dashboard.index',
        trans('core::menu_items.dashboard.label'),
        [

        ],
        1,
        [
            'icon' => 'icon-speedometer'
        ]
    );
});
```
Here is a dump when trying to get package translation from service provider:
```
dd(trans('core::menu_items'));
"core::menu_items" //no translation available here
```
Here is a dump when trying to get framework translations from service provider (located in ```resources/lang``` in project root)
```
dd(trans('auth'));
array:2 [▼
  "failed" => "These credentials do not match our records."
  "throttle" => "Too many login attempts. Please try again in :seconds seconds."
]
```
The module service provider is loaded as last after all of the other providers. Module translations in view works.

Am i using the package wrong? Is it possible to use module translations from service provider? If not, can you suggest where to register the menu items instead of service provider?

Also, i have noticed that after referencing module translation from service provider then i cannot use the referenced translation in views anymore, always returns the fallback string. However, if i rename the file containing the translations, then the view starts working, service provider stays the same (falls back to string key of translation)

Thanks.

**Comment by nWidart** [comment]
Hello,

Did you try to run this in the `boot` command?

**Comment by benkelukas** [comment]
Hi, yeah, tried that and that did the trick. Closing the ticket and thanks for your response :)
