### ISSUE TITLE
Route Configuraion

### ISSUE THREAD

**Issue by nasirkhan** [nWidart/laravel-modules#508]
How can i configure the routes of a specific module? How the directory structure should be and how to handle the `web` and `api` routes?

**Comment by nasirkhan** [comment]
did not find age doc related to the `route` can you please share the steps to manage module specif routes

**Comment by nWidart** [comment]
You can do that however you like.
The default is a start.php file, I recommend a `RoutingServiceProvider`.

**Comment by sokeno** [comment]
Is there a way one can register a default module when the application loads?

**Comment by akkerise** [comment]
@nasirkhan Are you a solution for configuring the routes of a specific module? I having trouble with api, web of a module. Thanks you before ...

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
