### ISSUE TITLE
serviceprovider not found on host

### ISSUE THREAD

**Issue by moeinrahimi** [nWidart/laravel-modules#51]
hi i have one module that is working fine on localhost which is windows, but my module got below error when i move it to linux hosting
FatalErrorException in Application.php line 598: Class 'Modules\SlideShow\Providers\SlideShowServiceProvider' not found

**Comment by nWidart** [comment]
That sounds like a file case issue. Make sure you used correct file names, linux being case sensitive.

**Comment by moeinrahimi** [comment]
i changed modules folder from Modues to modules now my 'serviceprovider' issue is done but there is more issues, for example in my app controller i used 'modules\Blog\Entities\Post' and the namespace of post model is 'Modules\Blog\Entities', app says Class 'Modules\Blog\Entities\Post' not found, there is no matter i typed it upper or lowercase

**Comment by szewang2805** [comment]
i have the same issue, laravel complained CustomerServiceProvider not found after i just make the module by aritsan command, pls help

**Comment by szewang2805** [comment]
my laravel version 5.3.10

**Comment by nWidart** [comment]
Just autoload your classes correctly and it will work.

**Comment by mithleshjs** [comment]
You forgot to run this command :  composer dump-autoload

**Comment by szewang2805** [comment]
i have composre dump-autoload, but still not work.
laravel can find my CustomerServiceProvider now, but there is another error

when i type URL xyz.com/customer/test

it shows
NotFoundHttpException in RouteCollection.php line 161:

the routes.php is

Route::group(['middleware' => 'web', 'prefix' => 'customer', 'namespace' => 'Modules\Customer\Http\Controllers'], function()
{
    Route::get('/test', 'CustomerController@index');
});


i notice that laravel 5.3.10 has spilt the routes into api.php, console.php and web.php, will it causes the error?
thx

**Comment by mithleshjs** [comment]
This problem has nothing to do with Laravel 5.3. It's working fine.

**Comment by szewang2805** [comment]
still not working... seesm that laravel does not notice the routes.php in my new module, thx
