### ISSUE TITLE
how to setup domain in route

### ISSUE THREAD

**Issue by satishkadyan** [nWidart/laravel-modules#512]
Hi,

I want to setup domain based routing for module, but it is not working. how can i set up a module to work with m.abc.com
and another module that can work with www.abc.com for example. when trying to configure with domain route config in routes.php it is giving error, without modules setting domain based routing works well.
please suggest how to proceed

**Comment by nWidart** [comment]
Hi,

You can do this like you would in a normal laravel application.

**Comment by irvine48** [comment]
Sub-Domain Routing
Route groups may also be used to handle sub-domain routing. Sub-domains may be assigned route parameters just like route URIs, allowing you to capture a portion of the sub-domain for usage in your route or controller. The sub-domain may be specified by calling the domain method before defining the group:

```
Route::domain('{account}.myapp.com')->group(function () {
    Route::get('user/{id}', function ($account, $id) {
        //
    });
});
```

Source: https://laravel.com/docs/5.6/routing

**Comment by bloggervista** [comment]
i guess this can be closed now :) Think module as a package so nothing is going to be changed :)

**Comment by satishkadyan** [comment]
hi,
 thanks all,
its working fine. 
can close this now.
