### ISSUE TITLE
adding styleci to this package?

### ISSUE THREAD

**Issue by bloggervista** [nWidart/laravel-modules#513]
I guess we need style ci to make code consistent right? As it is public it is free also?

**Comment by nWidart** [comment]
The package uses [phpcsfixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) for this purpose.
Style ci sadly can't parse the configuration file of phpcsfixer.

**Comment by bloggervista** [comment]
hmm style ci have preset named laravel and i guess all feature of phpcsfixer can be implemented and its one time isn't it?

**Comment by nWidart** [comment]
Indeed, but we don't use the laravel style.
I tried out styleci a while ago in this package I believe and it wasn't fitting the need.

**Comment by bloggervista** [comment]
oh then its ok
