### ISSUE TITLE
Create a new Disk

### ISSUE THREAD

**Issue by alexandretaz** [nWidart/laravel-modules#514]
I'm creating a file share module, and I want to know how to create an specific path to my directory as a disk, putting as default on Config\config.php, and been overwrited by .env variable MODULE_DISK_PATH

**Comment by nWidart** [comment]
You can configure disks like in any laravel app, in the filesystems.php configuration file.

**Comment by nWidart** [comment]
I'll close this due to inactivity.

**Comment by jjth** [comment]
It is possible to register disks within modules by creating a service provider that appends your config to the "filesystems.disks" option.

You can then add your own logic to this file (load your custom config, MODULE_DISK_PATH env variable etc...).

Basic example:
```php
    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $moduleName = 'mymodule';

        Config::set('filesystems.disks.' . $moduleName . '.disk1', [
            'driver' => 'local',
            'root' => storage_path('app/modules/' . $moduleName . '/disk1'),
            'visibility' => 'public',
        ]);
    }
```
