### ISSUE TITLE
Module tags

### ISSUE THREAD

**Issue by mitajunior** [nWidart/laravel-modules#515]
Looking for a way a can tag the modules.

Say I have may modules *themes*, *plugins* etc. A module can only be one of these and be able to call say 

Module::byType('themes')->all()

**Comment by nWidart** [comment]
The module class implements the `Macroable` trait, so you could in theory add a method like this on it.

**Comment by mitajunior** [comment]
Thanks @nWidart . Also on a related topic is there a way i can access a certain method or attribute that i want all my modules to have but each implement it diferently. e.g

$m =Module::find('x')
$m->hello_word();

**Comment by nWidart** [comment]
Yes, each module has the `Macroable` trait.
