### ISSUE TITLE
Is it possible to have a module override a view under resources/views

### ISSUE THREAD

**Issue by dicarlosystems** [nWidart/laravel-modules#516]
Hi,

Struggling to see how I can replace a base view with that of a module, e.g. replace product.blade.php from resources/views with an equivalent from a custom module?  I'd rather not modify the core file, if I can help it, as that kind of defeats the purpose of using a module to add the functionality.  I had envisioned the module kind of overlaying the customized view to add the additional functionality.

Any help is appreciated!

Cheers,

Chris

**Comment by nWidart** [comment]
Yes, it's possible, it's done in [AsgardCMS](https://github.com/AsgardCms/Platform/blob/3.0/Modules/Core/Providers/CoreServiceProvider.php#L190). You can take a look at that.

**Comment by nWidart** [comment]
I'll close this due to inactivity.

**Comment by AMSFauzi786** [comment]
May I know how to make it work on the above matter? I  am a newbie for Laravel, PHP and laravel-modules. I have an existing project which uses Laravel 8 and PHP version 7.4. I installed laravel-modules on it and try to override test.blade.php under resources/views/test/ by creating the same file structure in Module such as Resources/views/test/test.blade.php but it's not working.

Can someone help on this, thanks
