### ISSUE TITLE
Custom configuration properties are not loaded to Illuminate\Config\Repository

### ISSUE THREAD

**Issue by arthurkushman** [nWidart/laravel-modules#518]
There are problems with laravel-modules configuration - it seems like only standard properties from global .env set to the app environment (Illuminate\Config\Repository), so even if u execute
`php artisan config:cache`
it won't be there, thus u can't get value by config('extra_key')
In local/dev envs it is ok, but in production mode either `env()` returns `null` and `config()` returns errors trying to get non-existent key=value.

I understand that config properties should be set up in `Modules/{ModuleName}/Config/config.php`, but in my case this file is auto-generated. Moreover, because of the security reasons we can't hold secret settings there (passwords, hash keys etc).

It would be great to have an ability getting those user defined values in `.env` file by Laravel's config() function.

**Comment by nWidart** [comment]
Hm I think I've used environment variables in my module configuration before. Not sure why it wouldn't work.

**Comment by arthurkushman** [comment]
Got it, sorry for disturbing  - I should place the 
```php
'jwt_secret' => env('JWT_SECRET', 'secret'),
```
in global `config/app.php` and then it will be loaded to `Illuminate\Config\Repository`
