### ISSUE TITLE
Possible Redundancy? 

### ISSUE THREAD

**Issue by shirshak55** [nWidart/laravel-modules#519]
1.
Isn't magic method __call is called whenever there is no existing method ?
Meaning __call is never called for `method_exists($this, $method)`? so it is just redundant right?

https://github.com/nWidart/laravel-modules/blob/d56e518737fcc411ef197c59135a1990a95f91c5/src/Json.php#L224

2. In `Repository.php` as `getCached()` is already in array  what is point of using `formatCached($this->getCached())`?

3. Consistency

in update($module) method we did `with(new Updater($this))->update($module);` cannot we do similar in install method like this

with(new Installer($name, $version, $type, $subtree))->run();

**Comment by renanBritz** [comment]
The __call magic method intercepts ALL method calls.

At first it checks if the methods exists within the Json class instance. If not, it assumes you're calling a collection method and passes the call to the 'attributes' property which is of type \Illuminate\Support\Collection.

I hope it clarifies.

Regards!

**Comment by bloggervista** [comment]
@renanBritz hi bro.

Suppose i asked for `$class->hello();`

If `hello` is in class then it will be used before `__call` so why do we need to check if $class has method `hello` or not?

**Comment by nWidart** [comment]
1. This can also check for other classes that extend this for instance, iirc.
2. I don't remember, check the code :D 
3. ?

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
