### ISSUE TITLE
No hint path defined for <Module> on view render

### ISSUE THREAD

**Issue by hsjgrobler** [nWidart/laravel-modules#52]
Hi, I have setup my base composer.json to have and created a module called "Auth":

`"psr-4": {
            "App\\": "app/",
            "Modules\\": "Modules/"
        }`

But when I try to render the view: "auth::login" it gives me the following error: "No hint path defined for [Auth]."

I understand that this is composer PSR-4 related error, however, I don't know how to fix it.

Do you have any ideas? I am running Laravel 5.3

**Comment by Schweppesale** [comment]
Check your service providers.  

Verify that you've registered a path for the "auth" namespace.

>     $this->loadViewsFrom(__DIR__.'/path/to/views', 'auth');

**Comment by hsjgrobler** [comment]
I seem to have overwritten the AuthProvider, works now. Thank you! :)
