### ISSUE TITLE
Speed Issue?

### ISSUE THREAD

**Issue by jijoel** [nWidart/laravel-modules#520]
Have you found performance to degrade significantly when many modules? I am working on a large project which may ultimately have several dozen modules; currently at 8, we're experiencing a noticeable lag before getting results. I ran some quick time tests:

Starting with a fresh installation of laravel on homestead, phpunit finishes in about 2.5 seconds on my machine.

> composer require nwidart/laravel-modules
> for i in `seq -w 1 100`; do time php artisan module:make Test$i; done

The more modules we have, the slower the artisan command runs:

    001  real 0m1.582s   user 0m0.180s  sys 0m0.792s
    042  real 0m12.797s  user 0m0.524s  sys 0m6.660s
    071  real 0m17.172s  user 0m0.692s  sys 0m9.260s
    100  real 0m29.843s  user 0m1.268s  sys 0m15.056s

Once finished, running phpunit takes 14.5 seconds, still for the same two tests.

In a browser (wget), we go from 0.733 to 6.854s to respond with the welcome page. 

I love the concept, but how do we make it faster?

**Comment by nWidart** [comment]
Hello,

I've had projects with 10-15 modules, and no performance hit. I've heard of other people with similar amounts of modules and more without any performance issues either.

Maybe you could try to profile you app using blackfire.io . It's using that tool that many performance improvements have been applied on the package.

**Comment by pjhartin** [comment]
I'm noticing the same in development environment, although it is yet to be deployed to a production environment, so I don't want to optimize too early. But simply having the modules register & boot on each request seems like it is impacting response times for a simple 200 OK endpoint.

**Comment by nWidart** [comment]
That's how laravel and php en general works though.
