### ISSUE TITLE
override app config in a module?

### ISSUE THREAD

**Issue by Tazoeur** [nWidart/laravel-modules#525]
Hi,

I've seen that specifying new config param is possible with the `Config/config.php file`
Is it possible to override some configuration param, let's say the auth guard & provider used ?

Sorry if this is a stupid question, I am quite new to laravel and I didn't find any help about this particular point on your documentation.

**Comment by renanBritz** [comment]
Hello.

A module's configuration is prefixed with the module name. You can, however, set an app configuration in the module's Service Provider.

Edit the boot method of Modules/{ModuleName}/Providers/{ModuleName}ServiceProvider.php

> ModuleServiceProvider.php

```php
public function boot()
 {
    // Set your app config.
    config(['app_config' => 'value']);

    // Don't change this...
    $this->registerTranslations();
    $this->registerConfig();
    $this->registerViews();
    $this->registerFactories();
    $this->loadMigrationsFrom(__DIR__ . '/../Database/Migrations');
 }
```
