### ISSUE TITLE
Class not found in a new module.

### ISSUE THREAD

**Issue by RickyFeria** [nWidart/laravel-modules#528]
I'ḿ trying this packages to see if I can use it in my job but when I try to create an instance of DateTime a get this error in whoops "Class 'Modules\Shipping\Http\Controllers\DateTime' not found" by the way Iḿ using laravel 5.6

**Comment by nWidart** [comment]
Hello,

Try to use `\DateTime` instead. This isn't related to the package but rather to how namespaces work in php.

**Comment by RickyFeria** [comment]
Oh! thank you! I really appreciate it! =)

**Comment by nWidart** [comment]
No problem! 👍
