### ISSUE TITLE
Getting the name of the module in config file.

### ISSUE THREAD

**Issue by zhovtyj** [nWidart/laravel-modules#535]
Is there a way to get name of the module in config file that going to be created. I want to setup folder for views something like this:
`'views/index' => '../../themes/DevelopmentBackEnd/views/'. **$name_of_new_module**.'/index.blade.php',`

**Comment by nWidart** [comment]
Hello,

You can view all available replacements in the config file: https://github.com/nWidart/laravel-modules/blob/master/config/config.php#L47
