### ISSUE TITLE
In ProviderRepository.php line 208: Class 'Modules\Modulename\Providers\ModulenameServiceProvider' not found

### ISSUE THREAD

**Issue by krishna8723** [nWidart/laravel-modules#536]
When i run php artisan module:make Modulename, files were created in terminal but actually there is no module and its file. I am using laravel 5.5 and modules ^2.0.

**Comment by nWidart** [comment]
Hello,

Version 2 is not supported anymore. Please update to the latest.
It looks like some files were generated though, otherwise, you wouldn't have this error.

**Comment by daviddiramio** [comment]
Is there a solution for this? I am using Laravel 5.6 and v3.2 and getting this same error. Thanks!

**Comment by nWidart** [comment]
Not without more information no.

**Comment by daviddiramio** [comment]
@nWidart 
I installed the package and published the configuration file.
I ran the the artisan command to create a "Meal" module:
php artisan module:make Meal

Files are created and it says Module [Meal] created successfully.

I then run composer dump-autoload and get the following error:
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In ProviderRepository.php line 208:

  Class 'Modules\Meal\Providers\MealServiceProvider' not found


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

At this point, I am no longer able to run any artisan commands as I get the following error:
In ProviderRepository.php line 208:

  Class 'Modules\Meal\Providers\MealServiceProvider' not found

Hope this helps!  Thanks!

**Comment by nWidart** [comment]
did you add the autoloading in composer.json?

**Comment by daviddiramio** [comment]
@nWidart, that was it! I didn't have it in the main composer.json file. Thanks!

**Comment by virgiawndwir** [comment]
@nWidart how?

**Comment by nWidart** [comment]
How what?
The autoloading section is mentioned here: https://github.com/nWidart/laravel-modules#autoloading
