### ISSUE TITLE
Configuration of other module in routes

### ISSUE THREAD

**Issue by NathanGeerinck** [nWidart/laravel-modules#537]
Hi there,

If I want to acces a configuration file of another module, then it's returning nothing. Is there a way to get around this?

Thanks!

**Comment by nWidart** [comment]
Hello,

You can access the configuration of any module anywhere by using the same laravel convention.

**Comment by NathanGeerinck** [comment]
After looking three times I found my own stupid mistake. 

Anyway.. thanks for your response!
