### ISSUE TITLE
Do not use route prefix admin in file routes.php in module

### ISSUE THREAD

**Issue by dang-tien** [nWidart/laravel-modules#539]
Hi all,
I created module Product ( with Laravel Boilerplate)
I make `Modules/Product/Http/Controllers/Backend/ProductController.php` with content
( namespace is ok)
```
    public function create()
    {
        return view('product::backend.create');
    }
```
 and view `Modules/Product/Resources/views/backend/create.blade.php`
In `Modules/Product/Http/routes.php`
```
Route::group([
    'namespace' => 'Modules\Product\Http\Controllers\Backend',
    'prefix' => 'admin/product',
    'as' => 'admin.',
    'middleware' => 'admin'
    ], function () {
        Route::get('/create', 'ProductController@create');
    });
```
When i redirect to `admin/product/create`, application auto redirect to `admin/dashboard`.
I aready login with `admin@admin.com`
What i wrong?
Thank for help!

**Comment by nWidart** [comment]
Hi,

This is not related to this package.

Check your middleware for issues as that's probably where the redirect happens.
