### ISSUE TITLE
How are modules loaded?

### ISSUE THREAD

**Issue by MauroB45** [nWidart/laravel-modules#54]
Hi,

I just migrate from ping-pon modules. Thanks for continue supporting this package! 

I just noticed I don't need to add the module service provider to the application anymore. However I tried to deploy this but the application does not recognise de modules. I run php artisan module:list but there is no modules. I could add the service provider but I would like to know how it works in my local.  

Thanks,

**Comment by nWidart** [comment]
Possible because you had the old service provider still loaded.

**Comment by MauroB45** [comment]
I fixed the issue by enabling the scan configuration and adding the modules folder (custom namespace). Now it recognizes my modules.

Thanks.
