### ISSUE TITLE
please show sample for update and install one module with composer

### ISSUE THREAD

**Issue by vahidalvandi** [nWidart/laravel-modules#540]
please show sample for update and install one module with composer
thank you

**Comment by nWidart** [comment]
Hi,

This is not related to this package. It's the usual composer behaviour.

```
composer install vendor/name
composer update vendor/name
```

**Comment by vahidalvandi** [comment]
why in each module create composer.json ?
do can use in vertion control in production ? like v1.1 or upgrade to v1.2 in tag system ?
