### ISSUE TITLE
Use package other in Module

### ISSUE THREAD

**Issue by dang-tien** [nWidart/laravel-modules#542]
Hi,
I created module Image
I modified composer.json of my module

```
    "require": {
        "intervention/image": "^2.2"
}
```
then `cd Modules/Image` and run `composer install`
and module created new folder vendor with package already installed
But in my controller i use `use Intervention\Image\Facades\Image`  
i got  message

`"Class 'Intervention\Image\Facades\Image' not found"`
Hope you help me! Thanks

**Comment by nWidart** [comment]
You need to require intervention in your root module.

**Comment by vahidalvandi** [comment]
like this
https://github.com/MahdiMajidzadeh/laravel-kavenegar
