### ISSUE TITLE
Class 'Form' not found

### ISSUE THREAD

**Issue by bocanhcam** [nWidart/laravel-modules#543]
Hi, I try to use class Form in laravelcollective/html package. But it seems doesn't work.
I have this error Class 'Form' not found.
Can you give me a hand.
My code is simple like this : 
`{!! Form::select('category_ids[]', $categories, $category_ids, [
                            'class'=>'form-control select2',
                            'id'   => 'category_ids',
                            'required' => true,
                            'multiple' => true,
                            ] ) !!}`

PHP 7
Laravel version 5.4
laravel-modules v3

**Comment by nWidart** [comment]
hello,

This is not related to this package. Please refer to the package or laravel documentation.
