### ISSUE TITLE
Disable all module migrations in subdirectory from running on artisan migrate command

### ISSUE THREAD

**Issue by sp01010011** [nWidart/laravel-modules#545]
Can someone please point  me to some direction on how i can accomplish this.

I have some module migrations stored in subdirectory database/tenant 

What i want is to migrate any module migrations in database with arisan migrate but not any migrations in subdirectory e.g. database/tenant, i'm using mt package hyn which implements command tenants:migrate that migrates all migrations under database/tenant.

Now what i have to do is create all my module migrations publis, move migration in their respective directory database or database/tenant  and delete all module migrations otherwise the artisan migrate command would migrate module migrations in subdir.

How can i go about disabling artisan migrate from migrating all migrations under database/tenant for modules and only migrate them when tenants:migrate command is involved.

Maybe i am overlooking things.

Thank you for your help.

**Comment by nWidart** [comment]
It looks like you've detailed the steps you need to take to make it happen, time to develop 😄 

This is out of the scope of this package though.

**Comment by enextiarg** [comment]
You could use `php artisan migrate --path database/migrations/` in order to specify the migrations
