### ISSUE TITLE
How to register service provider?

### ISSUE THREAD

**Issue by rafailml** [nWidart/laravel-modules#546]
There are no app.php in Module/config
Can I add 'providers' => [] in config.php?

**Comment by nWidart** [comment]
You can register however you prefer.

`module.json` has a key for this.

**Comment by vigneshpalanivel** [comment]
No, this isn't working. 

Target [Modules\Settings\Repositories\SiteSettingsRepositoryInterface] is not instantiable.

I'm getting this error after adding Provider in module.json. I used this code to register my Repository Interface,

$this->app->bind('Modules\Settings\Respositories\SiteSettingsRepositoryInterface', 'Modules\Settings\Respositories\SiteSettingsRepository');

I tried this same code in Laravel new package, its worked.

**Comment by nWidart** [comment]
Ah yes that's the way to do it in a service provider. 
The question was how to register a service provider, which you can use the module.json for.

What you're doing is not registering a service provider.

**Comment by vigneshpalanivel** [comment]
Yes, It might call Service provider, but, register function bind is not working. That's why I'm getting below error. What is the solution for this? Because, its working fine in Laravel new package. 

Target [Modules\Settings\Repositories\SiteSettingsRepositoryInterface] is not instantiable.

**Comment by vigneshpalanivel** [comment]
I think, I'm properly using it.. Please see my code below.

SiteSettingsRepositoryInterface.php

```
namespace Modules\Settings\Repositories;

interface SiteSettingsRepositoryInterface
{
    public function getAll();
}
```

SiteSettingsRepository.php

```
namespace Modules\Settings\Repositories;

use Modules\Settings\Entities\SiteSettings;
use Modules\Settings\Repositories\SiteSettingsRepositoryInterface;

class SiteSettingsRepository implements SiteSettingsRepositoryInterface
{
    protected $model;

    public function __construct(SiteSettings $site_settings)
    {
        $this->model = $site_settings;
    }

    public function getAll()
    {
        return $this->model->all();
    }
}
```

SettingsController.php

```
namespace Modules\Settings\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\Settings\Repositories\SiteSettingsRepositoryInterface;

class SettingsController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index(SiteSettingsRepositoryInterface $site_settings)
    {
        dd($site_settings->getAll());
        return view('settings::index');
    }
}

```
SettingsServiceProvider.php

```
public function register()
    {
        $this->app->bind('Modules\Settings\Respositories\SiteSettingsRepositoryInterface', 'Modules\Settings\Respositories\SiteSettingsRepository');
    }
```
