### ISSUE TITLE
Install previously created modules

### ISSUE THREAD

**Issue by nasirkhan** [nWidart/laravel-modules#547]
Is there any example to building a module installer? i created a number of modules and i need to use some of them. can i create a installer to add and remove that dynamically

**Comment by nWidart** [comment]
Hello,

You can look at [AsgardCMS](https://github.com/AsgardCms/Platform) which uses modules heavily for example.
You can also look at the [dependents](https://packagist.org/packages/nwidart/laravel-modules/dependents) on packagist.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
