### ISSUE TITLE
Bind main app event with module listener

### ISSUE THREAD

**Issue by Pawlox** [nWidart/laravel-modules#55]
Hey,

I've got event in my main application and handler/listener class in my new module - is there any way to bind those two classes in modules service provider? I tried adding

```protected $listen = [
    'App\Events\MainAppEvent' => [
    'Modules\MyModule\Events\Handlers\EventHandler',
		],
	];```

but it seems that it doesn't work :/

**Comment by nWidart** [comment]
You need to extend `Illuminate\Foundation\Support\Providers\EventServiceProvider` and not the usual SP to use that.

**Comment by Pawlox** [comment]
Oh, great! Why I didn't tought about it :) Thanks a lot!

**Comment by nWidart** [comment]
Awesome, no worries 👍

**Comment by franciskisiara** [comment]
@nWidart, if its not too much to ask, please indicate this in your docs, its quite easy to miss and can cost one some time trying to figure it out.

**Comment by nWidart** [comment]
@franciskisiara I can do that 😄 You can too, the docs are open source https://github.com/nWidart/nwidart-docs
