### ISSUE TITLE
Can't find app/Bootstrap.php 

### ISSUE THREAD

**Issue by thevis009** [nWidart/laravel-modules#550]
I can't finish configured lumen for app/bootstrap.php who not find in my project.
What can i Do?

![img_20180613_185231](https://user-images.githubusercontent.com/40207502/41382649-176b9ae4-6f3b-11e8-8b0e-c6aa440518e6.jpg)

**Comment by nWidart** [comment]
Hello,

I'm not familiar with Lumen, though when looking at the lumen repository I can see an `[bootstrap/app.php](https://github.com/laravel/lumen/blob/master/bootstrap/app.php)` which could correspond to your needs?

**Comment by nWidart** [comment]
I've updated the documentation to reflect this.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
