### ISSUE TITLE
More flags for module:make

### ISSUE THREAD

**Issue by JeyKeu** [nWidart/laravel-modules#552]
It's cumbersome to run `module:make ModuleName` the `module:make-model Model ModuleName`.
There are always 1+ modules from start. and it becomes very unpleasant getting started.

Please introduce flags such as 

`-m` for model
`-s` for seed
`-f` for factory and so on
and finally
`-a` for all. to generate models resources and migrations

**Comment by nWidart** [comment]
Hm I haven't seen the need for this yet given there's a `--plain` option which won't create the `stubs.files`, seeds, providers, controller.
After which you can then easily call a generate method to generate the wanted classes/files when needed.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
