### ISSUE TITLE
Add API Controller artisan command option

### ISSUE THREAD

**Issue by ahlechandre** [nWidart/laravel-modules#553]
By using the default artisan commands we can easily generate an API resource controller:

```bash
php artisan make:controller API/PhotoController --api
```

I think that adding this option would be useful on "module:make-controller" command.

**Comment by nWidart** [comment]
Hello,

Controllers by default are resource controllers, and to have the "usual" empty controller you can use the `--plain`, `-p`  option.

**Comment by renanBritz** [comment]
Hello.

The API controller should not include the create and edit methods.

It would also be very useful to have a -m flag in the make-controller command to specify which Model (resource) the controller will be responsible for.

Thank you!

**Comment by nWidart** [comment]
Hm, I don't see why a resource controller shouldn't be a full resource. As a generated API I can only see the full CRUD operations being available.
If for some reason it's not needed it's easy to remove it anyway.

I guess the model flag could be an enhancement indeed. However, I have currently limited time available for open source so I probably won't have time to look into this in the near future. Pull requests accepted though. 😄 
Now that I think about it, not so sure it's a good idea as the people have different ways of handling resources/models. Using repositories, models, etc. The way it's done now, leaves the options open to any option, and is easy to fill in the methods as needed.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
