### ISSUE TITLE
Generate absolute namespace instead of relative

### ISSUE THREAD

**Issue by ahlechandre** [nWidart/laravel-modules#554]
When we run any `module:make-*` command, the generated classes contains relative namespaces in document blocks. For example:

```php
/**
* Display a listing of the resource.
* @return Response
*/
public function index()
{
    return view('system::index');
}
```

This isn't useful mainly because we can't figure out which "Response" object this method will return:

![response](https://user-images.githubusercontent.com/7119058/41468898-6c3ed22c-7079-11e8-86de-da8fd4e1b2df.jpg)

Instead of this, I would propose you to use absolute namespaces just like Laravel already does:

> And also add a line break after description text.

```php
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
      //
  }
```

**Comment by nWidart** [comment]
Hello,

I agree with your reasoning, makes sense. 👍 
I'd accept a PR for this 😄

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
