### ISSUE TITLE
Auth::user() returns null on Module __construct()

### ISSUE THREAD

**Issue by nasirkhan** [nWidart/laravel-modules#556]
I created a new Module named `Article`. Some backend routes needed authentication and i added `auth` middleware and an additional permission `view_backend`. I am using https://github.com/spatie/laravel-permission package for role-permissions. 

the issue is when i try to access the route `admin/article/posts` it prompts me the login as expected. But after login it show null on `__construct()` method for `Auth::user()`;

I added `web` middleware as mentioned on #204 but it did not solve the issue. Can you please guide me to resolve this? My project is on Laravel 5.6 and using the latest version of Laravel-Modules

```
Route::group(['namespace' => 'Modules\Article\Http\Controllers\Backend', 'as' => 'backend.article.', 'middleware' => ['web', 'auth', 'can:view_backend'], 'prefix' => 'admin/article'], function () {
 
    Route::resource("posts", "PostsController");
});
``` 

My project is hosted at Github, https://github.com/nasirkhan/laravel-starter/tree/module

**Comment by nasirkhan** [comment]
@nWidart can please suggest me any solution to overcome this situation?

**Comment by socbaysky** [comment]
@nasirkhan i am using your laravel-starter, did you find out how to fix this problem? i got it now!!
