### ISSUE TITLE
Create module folders like vendorName/moduleName

### ISSUE THREAD

**Issue by dacalin** [nWidart/laravel-modules#557]
Hello!
I tried to create a module named vendor/moduleName and I got an error in Repository.php on line 382 (Module does not exists!). I don't know if the module will work fixing only that.... Will it?

**Comment by nWidart** [comment]
Hello,

This is indeed not supported. A module name shouldn't include the vendor name.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by kuptsovv** [comment]
Hello @nWidart! Do you have any plans to implement this feature in the future? I think it would be really great to have an opportunity to split modules by a vendor name.

**Comment by nWidart** [comment]
Not sure that can work as every module would need a vendor prefix.
