### ISSUE TITLE
The Mix manifest does not exist.

### ISSUE THREAD

**Issue by DataPartnerBr** [nWidart/laravel-modules#558]
The Mix manifest does not exist.

Before install npm Running Mix. Error persist.

**Comment by nWidart** [comment]
Hello,


@KABBOUCHI might have more insight into this.

**Comment by felipemarques** [comment]
Hello @nWidart , a have an problem with this message... This occurs after I created a new module using the command:

$ php artisan module:make VideoChat

this is the code into blade view , that produce this error:

```
@extends('videochat::layouts.master')

@section('content')
    <h1>Hello World</h1>

    <p>
        This view is loaded from module: {!! config('videochat.name') !!}
    </p>
@stop

```

**Comment by felipemarques** [comment]
![image](https://user-images.githubusercontent.com/2640656/46227596-1c955880-c336-11e8-883a-34a707fe4e28.png)

**Comment by KABBOUCHI** [comment]
do u have an old version?

plz check the layout? should be like this https://github.com/nWidart/laravel-modules/pull/533/files#diff-cb9956a906db6a30ea0dca8950de6401
