### ISSUE TITLE
After make 4 modules the size of my application 743 Mo (779 688 787 octets)

### ISSUE THREAD

**Issue by yagami271** [nWidart/laravel-modules#559]
hi, 
it's normal after having 4 module the applicaiton size is 743 Mo (779 688 787 octets) ?

is there solution ? 

thank you

**Comment by nWidart** [comment]
Did you run composer inside each module? If so, you don't have to do this.

**Comment by yagami271** [comment]
No i didn't do it but i think the probleme come from de node_modules directory 

Each module has node_modules of 126 Mo

**Comment by nWidart** [comment]
Ah yes, that's the javascript world... welcome 😄
