### ISSUE TITLE
php artisan module:migrate-rollback, not working

### ISSUE THREAD

**Issue by Abusal7** [nWidart/laravel-modules#56]
Hi there, thank you for this package,

The problem is that when I execute 

`php artisan module:migrate-rollback`

this error appear
  **[BadMethodCallException]
  Method lists does not exist.**

I search and found that laravel 5.3 replaced **_lists_** by [**_pluck_**](https://laravel.com/docs/5.3/collections#method-pluck)

**Comment by nWidart** [comment]
Hello,

Thanks.

This was fixed here, https://github.com/nWidart/laravel-modules/commit/9686dbf44d7f9c5281d569d12318858fe40e7189 , but I see I forgot to tag. Can you try dev-master and confirm the fix ?

**Comment by Fanmade** [comment]
I've just had the same problem. Updating to dev-master worked fine

**Comment by nWidart** [comment]
Thank you, I will tag this asap. 😄

**Comment by Abusal7** [comment]
Thank you, I have seen that you have fixed this problem in the master branch after I submitted this issue, and I watting for you to make a tage for this fix.


Thank you very much.
