### ISSUE TITLE
full management of modules in database

### ISSUE THREAD

**Issue by vahidv** [nWidart/laravel-modules#562]
HI,
is there a way to keep data for modules in database? i mean put module.json details for each module in a table(modules) and manage theme from database not in json file.
in this way we can do more actions, because i need full management for modules through view actions.
for example:
list of modules with full details in data tables
create module in form view with some extra info 
active/inactive theme
delete any module
and ....
(or maybe some actions for authorizing user role more easier)

I think module methods are too few too manage theme and we should use artisan command to complete theme.
so, when every thing is in database you can do any thing you want just by execute some CRUD queries.
please help me to find some solutions for my requirements.

**Comment by renanBritz** [comment]
There isn't.

But it doesn't mean you can't manage modules...

See [here](https://nwidart.com/laravel-modules/v3/advanced-tools/facade-methods) and [here](https://nwidart.com/laravel-modules/v3/advanced-tools/module-methods).

**Comment by nWidart** [comment]
Indeed, as @renanBritz mentioned you can already do a lot.

However, storing modules in a database was an idea that I never had time to work on. 
I've started something with this commit https://github.com/nWidart/laravel-modules/commit/d5fec20c08e4ef339c1079d547b525d42ebe95ba

And also on this branch https://github.com/nWidart/laravel-modules/tree/feature/database-modules

**Comment by nWidart** [comment]
Closing in favour of #171

**Comment by lucasantoniooficial** [comment]
Does this possibility still exist in future versions of managing modules through the database?
