### ISSUE TITLE
module system with not working with laravel 5.6 (routes)

### ISSUE THREAD

**Issue by Patrikgrinsvall** [nWidart/laravel-modules#567]
Hi

I just did a fresh install of larvel, composer etc. I noticed they changed path for the routes.php file and also renamed it web.php.

This doesnt seem to work at all with the modular system since each module contain its own route file. The default laravel route is loaded and if i remove it i get an error. I really dont have a work around for this.

Are there any solutions to this?

**Comment by Patrikgrinsvall** [comment]
Sorry, it seems i missunderstod a concept. It does seem to work. Sorry.

**Comment by nWidart** [comment]
No worries, I'll close it down. 👍
