### ISSUE TITLE
Vue js v-on:click events not working

### ISSUE THREAD

**Issue by rvalde28** [nWidart/laravel-modules#568]
Hello, I am having issues with v-on:click events not being able to work on Modules. The components are called and everything loads, however vue-click events dont work. JS/jQuery events work fine though. Was wondering if anyone had a solution to this problem. Thanks.

**Comment by nWidart** [comment]
Hi,

I'm not sure why you would think this is related to laravel-modules.
Please refer to the vuejs documentation.

**Comment by rvalde28** [comment]
Hi nWidart,

Vue js click events work outside of laravel-modules. When inside the Resources/assets/js path which is where they should be, it doesnt work. Its related and i thought people might have a solution to my problem.

**Comment by nWidart** [comment]
There's absolutely no reason for this.

**Comment by rvalde28** [comment]
Its okay if i find a solution ill post it here. thanks

**Comment by rvalde28** [comment]
Solution:
add ".extract(['vue'])" to mix.js(....) in webpack.mix.js file.  So it should look something like this:

mix.js(__dirname + '/Resources/assets/js/app.js', 'js/test.js')
  .extract(['vue'])
    .sass( __dirname + '/Resources/assets/sass/app.scss', 'css/test.css');

**Comment by KABBOUCHI** [comment]
@rvalde28 it's working fine for me, whats exactly your problem? can you reproduce it in an new project and share the code/repo?

**Comment by rvalde28** [comment]
hi @KABBOUCHI 
So my vue events werent working whatsoever, but I realized that I wasnt loading vue code inside of the Modules webpack. This was solved by having the doing what the solution above mentions. That was my honest mistake. But it works now :) so im back to using this awesome library!
