### ISSUE TITLE
How to include views within module ? 

### ISSUE THREAD

**Issue by narayandhoj** [nWidart/laravel-modules#570]
I tried to include using @include but it always try to pull view form main resource. I want to include the view from module. Please help me thanks

**Comment by rjrodriguezalvarez97** [comment]
`@include('module::index') ` where `module` is the alias for your module and assuming `index` is inside of `view` directory. You have to do the same if you return a view from your controller.

**Comment by narayandhoj** [comment]
thanks, it worked :)

**Comment by xSavitar** [comment]
What is there is a sub-directory in the `views` directory? Will it now be something like `@include('module::subdir::index')`?

I've tried the above and it's not working.

**Comment by xSavitar** [comment]
> I've tried the above and it's not working.

So what works is `@include('module::subdir.filename')` in case of a sub-directory in the views directory. Thanks!

**Comment by SergyKor** [comment]
I try to display the module in a block on another page:
@extends('layout.app')

@section('content')
    <h1>Welcome</h1>
    @include('blog::index')
@endsection

I get: "No hint path defined for [blog]. (View: D:\OSPanel\domains\laravel\resources\views\welcome.blade.php)"

**Comment by serkor** [comment]
the output method of the module on other pages of the application needs to be added to the documentation

**Comment by nWidart** [comment]
Here you go: https://github.com/nWidart/nwidart-docs

**Comment by finsnfurs2020** [comment]
I have tried **@include('module::admin.layouts.head')** but 
I got 
No hint path defined for [module]. (View: C:\xampp\htdocs\mme\Modules\Admin\Resources\views\dashboard.blade.php)
this error

**Comment by MetaiR** [comment]
@finsnfurs2020 I know this is a bit old, but did u managed to find the solution?

**Comment by srakl** [comment]
> I have tried **@include('module::admin.layouts.head')** but I got No hint path defined for [module]. (View: C:\xampp\htdocs\mme\Modules\Admin\Resources\views\dashboard.blade.php) this error

any solution for this?  


mine is `include('Reports::sample-report')` where `sample-report.blade.php` is in `resources/views/samplae-report.blade.php` and im getting the error `No hint path defined for [Reports].`

Any ideas how to fix this?
