### ISSUE TITLE
How do you rename a module?

### ISSUE THREAD

**Issue by rjrodriguezalvarez97** [nWidart/laravel-modules#571]
Let's say I have a module called `foo` and I want to rename it to `bar`. I didn't try it but I guess if I just rename the directory it won't change its name when you execute `module:list`

**Comment by nWidart** [comment]
Hello,

Indeed you start by renaming the directory and then the `module.json` (which is used by `module:list`)

**Comment by rjrodriguezalvarez97** [comment]
Thank you for your quick answer :)

**Comment by hadi-mansoori** [comment]
of course but after change it we must rename all namespaces and etc ...

> Hello,
> 
> Indeed you start by renaming the directory and then the `module.json` (which is used by `module:list`)

of course but after change it we must rename all namespaces and etc ... ?
