### ISSUE TITLE
Composer scripts not running?

### ISSUE THREAD

**Issue by renanBritz** [nWidart/laravel-modules#572]
Hello!

In #171 there's a suggestion to ignore the module.json file and commit a module.json.example to vcs, just like .env.example. I'm trying to do just that, but I'm also trying to have the example file copied by composer scripts. However, **they seem to not be running**.

"Module composer scripts" seems to be implemented, from what I could understand by reading #163.

This is how my module's composer.json file looks:
```
{
    "name": "*******/person-module",
    "description": "",
    "type": "laravel-module",
    "authors": [
        {
            "name": "********",
            "email": "**********"
        }
    ],
    "extra": {
        "laravel": {
            "providers": [
                "App\\Modules\\Person\\Providers\\PersonServiceProvider"
            ],
            "aliases": {
                
            }
        }
    },
    "autoload": {
        "psr-4": {
            "App\\Modules\\Person\\": ""
        }
    },
    "scripts": {
        "post-install-cmd": [
            "@php -r \"file_exists('module.json') || copy('module.json.example', 'module.json');\""
        ],
        "post-update-cmd": [
            "@php -r \"file_exists('module.json') || copy('module.json.example', 'module.json');\""
        ]
    }
}
```

I tried many different commands, as described [here](https://getcomposer.org/doc/articles/scripts.md). But none of them worked, that is, **the file was not copied after running composer update in the project root**. OR, no errors / messages were displayed.

Maybe it's worth noting that I'm using [joshbrw/laravel-module-installer](https://github.com/joshbrw/laravel-module-installer/)...

I'm probably doing something wrong. Could you please point it out?

Thank you very much!

**Comment by eberkund** [comment]
I don't think the `composer.json` file is used as most people might expect. It also does not make use of packages specified in `composer.json` in the `require: {}` section.

**Comment by nWidart** [comment]
@eberkund It does, but on install.

a composer plugin like https://github.com/wikimedia/composer-merge-plugin can do it all the time.

**Comment by eberkund** [comment]
Ah I see, thanks

**Comment by nWidart** [comment]
@renanBritz Does this answer your question?
Scripts/dependencies are only run on install. You can have it all the time with a plugin like composer-merge-plugin.

**Comment by renanBritz** [comment]
Oh, I see. I'll check it out.

Thank you!
