### ISSUE TITLE
Module [] does not exist!

### ISSUE THREAD

**Issue by Mrp12** [nWidart/laravel-modules#573]
after creating successful Module i want to make model with this command:

`php artisan module:make-model SystemTickets`

but i get this error:

```
   Nwidart\Modules\Exceptions\ModuleNotFoundException  : Module [] does not exist!

  at C:\xampp\htdocs\diabet\vendor\nwidart\laravel-modules\src\Repository.php:382
    378|         if ($module !== null) {
    379|             return $module;
    380|         }
    381|
  > 382|         throw new ModuleNotFoundException("Module [{$name}] does not exist!");
    383|     }
    384|
    385|     /**
    386|      * Get all modules as laravel collection instance.

  Exception trace:

  1   Nwidart\Modules\Repository::findOrFail("")
      C:\xampp\htdocs\diabet\vendor\nwidart\laravel-modules\src\Repository.php:489

  2   Nwidart\Modules\Repository::getUsedNow()
      C:\xampp\htdocs\diabet\vendor\nwidart\laravel-modules\src\Traits\ModuleCommandTrait.php:14

  Please use the argument -v to see more details.

```

**Comment by nWidart** [comment]
Hello,

What's the value in your `module.json` file under the module name?

**Comment by Mrp12** [comment]
@nWidart I'm so sorry you have right

**Comment by Qinliny** [comment]
Hello, have you solved your problem?I have a similar problem. Can you tell me how to solve it?

**Comment by soundar8562** [comment]
> Hello, have you solved your problem?I have a similar problem. Can you tell me how to solve it?
Have you tried in this format?
php artisan module:make-model model_name module_name

**Comment by mtijtsma** [comment]
I ran into this problem on Laravel 9. I fixed it with module:enable Module again. It says it has already enabled. But the module:migrate works after enabling it again.

**Comment by mtkumar82** [comment]
Hi,
I am facing the same problem when trying to make any operations to modules, Like
php artisan module:make-component AmazonRepricer

its giving me below error

  Nwidart\Modules\Exceptions\ModuleNotFoundException

  Module [] does not exist!

  at D:\www\laravelcms\vendor\nwidart\laravel-modules\src\FileRepository.php:366
    362▕         if ($module !== null) {
    363▕             return $module;
    364▕         }
    365▕
  ➜ 366▕         throw new ModuleNotFoundException("Module [{$name}] does not exist!");
    367▕     }
    368▕
    369▕     /**
    370▕      * Get all modules as laravel collection instance.

  1   D:\www\laravelcms\vendor\nwidart\laravel-modules\src\FileRepository.php:464
      Nwidart\Modules\FileRepository::findOrFail("")

  2   D:\www\laravelcms\vendor\nwidart\laravel-modules\src\Traits\ModuleCommandTrait.php:14
      Nwidart\Modules\FileRepository::getUsedNow()

None of commands working there, I have module installed and enabled too

D:\www\laravelcms>php artisan module:list
  Status / Name ...................................................................................... Path / priority
  [Enabled] Acl .................................................................... D:\www\laravelcms\Modules/Acl [0]
  [Enabled] AclManager ...................................................... D:\www\laravelcms\Modules/AclManager [0]
  [Enabled] Amazon .............................................................. D:\www\laravelcms\Modules/Amazon [0]
  [Enabled] AmazonAws ........................................................ D:\www\laravelcms\Modules/AmazonAws [0]
  [Enabled] AmazonRepricer .............................................. D:\www\laravelcms\Modules/AmazonRepricer [0]
  [Enabled] AmazonSqs ........................................................ D:\www\laravelcms\Modules/AmazonSqs [0]
  [Enabled] AmazonSubscription ...................................... D:\www\laravelcms\Modules/AmazonSubscription [0]
  [Enabled] Export .............................................................. D:\www\laravelcms\Modules/Export [0]
  [Enabled] Histories ........................................................ D:\www\laravelcms\Modules/Histories [0]
  [Enabled] Import .............................................................. D:\www\laravelcms\Modules/Import [0]
  [Enabled] Marketplaces .................................................. D:\www\laravelcms\Modules/Marketplaces [0]


Please suggest the solution and what wrong I am doing there? I tried to run composer update but not works

**Comment by dcblogdev** [comment]
it appears you're only passing 1 value ie the component name, you also need to pass the module name too

```php
php artisan module:make-component ComponentName AmazonRepricer
```

**Comment by mtkumar82** [comment]
Thanks @dcblogdev , It works for me now, I missed that argument there.

**Comment by doubleprincez** [comment]
In previous versions, running ```php artisan module:seed``` so what is your equivalent of ````php artisan db:seed``` ?

**Comment by dcblogdev** [comment]
> In previous versions, running `php artisan module:seed` works so what is the new equivalent of `php artisan db:seed` ?

Its still `php artisan module:seed` which will ask you which module to see either selecting a module or for pass the module name or all like

`php artisan module:seed --all`

**Comment by doubleprincez** [comment]
What could be the reason for this?
![Screenshot 2024-06-17 203955](https://github.com/nWidart/laravel-modules/assets/37469720/92f306b1-3e1d-4eb2-9905-c02209c175e4)

**Comment by dcblogdev** [comment]
Hmm it should look like this

![CleanShot 2024-06-17 at 20 43 50@2x](https://github.com/nWidart/laravel-modules/assets/1018170/5be08475-78b1-4a68-bc30-7cc3d20f3f3d)

I don't know why you have a module there called 0, does it work if you select the all option or one of the other modules?

**Comment by doubleprincez** [comment]
This is a new project on  
```       "php": "^8.2",
        "darkaonline/l5-swagger": "^8.6",
        "laravel/framework": "^11.0",
        "laravel/sanctum": "^4.0",
        "laravel/tinker": "^2.9",
        "nwidart/laravel-modules": "^11.0",
        "spatie/laravel-activitylog": "^4.8",
        "spatie/laravel-permission": "^6.4"
```

**Comment by dcblogdev** [comment]
thanks for the details, I wonder if this is a difference due to the OS. I'm on MacOS

Does it work if you select all or a different module?

**Comment by doubleprincez** [comment]
It works im on windows 11

![Screenshot 2024-06-17 210025](https://github.com/nWidart/laravel-modules/assets/37469720/429527c7-9424-4129-865f-a7e757fbcf03)

**Comment by doubleprincez** [comment]
Hello, please It works only when i add the seeded module name at the end but doesn't when i need to seed all modules at once, what could be the cause please

**Comment by doubleprincez** [comment]
My Query hasn't been resolved yet though, single module seeding works but not  ```php artisan module:seed```

**Comment by doubleprincez** [comment]
I apologize for my oversight; Some important files were missing.... was able to fix it when I run 
```php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"``` 
that copied config.php and stubs\nwidart-stubs files
