### ISSUE TITLE
Question for multiple tenants

### ISSUE THREAD

**Issue by Nowi5** [nWidart/laravel-modules#575]
Hi guys,

thank you for this package. I have two small questions:
1. Would this allow to have Modules and even some core still in the app folder? I think some basic thinks make sense to keep there e.g. the user as this is used everywhere.
2. Did you had a look to other packages especially to multi tenants e.g. https://github.com/hyn/multi-tenant
They have a really great structure to overload the basic by tenant specific coding. Would be great if you could have a look and share your opinion.

Thank you!

**Comment by nWidart** [comment]
Hi,

1. Yes. Nothing is blocking you to have classes in the app folder...
2. I know that package by name, not used yet. I don't the question.

**Comment by Nowi5** [comment]
Thank you, I just ask as this package has two migrations one for tenants one for system. Question is now if I can have the same within the moduls... Guess I need to test.

**Comment by mtasuandi** [comment]
@Nowi5 I was using the pingpong-modules before the project unmaintained and now @nWidart continue the project by publishing this project. So far, I have about 20 modules and everything is based on this package.

**Comment by nWidart** [comment]
I'll close this since nothing is indicating an issue. Don't hesitate to open a new one should something come up. 👍 

Thanks for the feedback @mtasuandi 😊

**Comment by twf-nikhila** [comment]
@nWidart 

> I know that package by name, not used yet. I don't the question. I worked on projects with multi tenants, handled that myself. No issues with laravel-modules of course...

How did you handled multi-tenant without package? Any reference, really like to convert a SaaS application to multi-tenant but scared to use /hyn/multi-tenant package. Any blog or code reference will be great.

**Comment by zoxed** [comment]
@twf-nikhila can i ask you about the same question you posted years ago xD ?
