### ISSUE TITLE
Question: nWidart/laravel-modules vs caffeinated/modules

### ISSUE THREAD

**Issue by Nowi5** [nWidart/laravel-modules#576]
Hi Community,

with the recent hours and even days I'm looking for a good start for a large application with a modular concept and multi tenant (SaaS)(https://github.com/hyn/multi-tenant). So I located the both packages nWidart/laravel-modules & caffeinated/modules, which looks somehow similar. nWidart has some more github stars, but any additional features (e.g. more stable, works with multi tenants,...) compared to caffeinated?

Thank you for your support.

**Comment by Nowi5** [comment]
https://github.com/caffeinated/modules/issues/365

**Comment by nWidart** [comment]
Hi,

It's up to you to compare and chose whichever you like more.

Know that features like multi-tenant are not related to any of our packages whatsoever. Up to you to develop your application.

**Comment by Nowi5** [comment]
Right and thanks for the quick answer! But if there are no differences between the packages, why are they two? So they need to be one in some regards?

**Comment by nWidart** [comment]
Historically, as far as I know, laravel-modules was the first package to propose this modular feature. Its first commit was [8 Feb 2014](https://github.com/pingpong-labs/modules/commit/37f8cb3c092065383f8ffd117525ee7d15c57dee#diff-a084b794bc0759e7a6b77810e01874f2), vs [25 Sep 2014](https://github.com/caffeinated/modules/commit/455d0967231c2aa018d19cc851d2f7370cddceaa#diff-9879d6db96fd29134fc802214163b95a) for caffeinated/modules.

So no idea what they created another one. They are other copies too with same feature set.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
