### ISSUE TITLE
Enabeld: Config from Database

### ISSUE THREAD

**Issue by Nowi5** [nWidart/laravel-modules#577]
Hi all,

to have a more configurable Module perspective, have you thought about to have the Module itself as a Model with attributes at the database? Of course this entry need to be cached, but I think having a description and the possibility enable/disable at UI makes sense.

I looking in addition into the way to have the enable/disable depending on environment / database setting in a multi tenant application, means I would have depending on domain a module enabled or not.

Even if you say, a config on database level makes no sense for you, it would be great to have the option to overwrite different function by creating a own Service Provider by extending yours and change a config setting. My favorit example for that is Saptie/permission e.g. 

```
 'models' => [
        /*
         * When using the "HasRoles" trait from this package, we need to know which
         * Eloquent model should be used to retrieve your permissions. Of course, it
         * is often just the "Permission" model but you may use whatever you like.
         *
         * The model you want to use as a Permission model needs to implement the
         * `Spatie\Permission\Contracts\Permission` contract.
         */
        'permission' => Spatie\Permission\Models\Permission::class,
        /*
         * When using the "HasRoles" trait from this package, we need to know which
         * Eloquent model should be used to retrieve your roles. Of course, it
         * is often just the "Role" model but you may use whatever you like.
         *
         * The model you want to use as a Role model needs to implement the
         * `Spatie\Permission\Contracts\Role` contract.
         */
        'role' => Spatie\Permission\Models\Role::class,
    ],
```

What do you think about this?

**Comment by nWidart** [comment]
Hi,

Yes, it has been discussed in multiple issues before, one open still.
And something is under way here... https://github.com/nWidart/laravel-modules/tree/feature/database-modules

Though, it's already possible to have a ui to enable/disable modules and so on, I do this on AsgardCMS.
You can also enable/disable modules based on roles/tenant etc. etc. 

I don't understand your service provider thing. Laravel already allows overriding over services providers built in.

**Comment by Nowi5** [comment]
"You can also enable/disable modules based on roles/tenant etc. " Yes I see, but I look to have on the same coding tenant1.domain.com a module enabled and under tenant2.domain.com not. So I need a where condition while reading if a module should be enabled or not, and so the caching need to be adjusted too. 

Regarding your comment about the provider, more specific; how would I overwrite your function all() and related caching within  laravel-modules/src/FileRepository.php to save the enabled status not in cache or file but in a model which I can extend (because my caching base on model with where('tenant', 'tenantid')?

**Comment by Nowi5** [comment]
When you have a look at caffeinated/modules they have two additional parameters in there config:

`/*
    |--------------------------------------------------------------------------
    | Default Module Driver
    |--------------------------------------------------------------------------
    |
    | This option controls the module storage driver that will be utilized.
    | This driver manages the retrieval and management of module properties.
    | Setting this to custom allows you to specify your own driver instance.
    |
    | Supported: "Local" or "Custom"
    |
    */

    'driver' => 'Local',

    /*
     |--------------------------------------------------------------------------
     | Custom Module Driver
     |--------------------------------------------------------------------------
     |
     | Using a custom module driver, the 'driver' value need to be set to 'custom'
     | The path to the driver need to be set in addition at custom_driver.
     |
     | @warn: This value will be only considered if driver is set to custom.
     |
     */

    // 'custom_driver' => 'Caffeinated\Modules\Repositories\LocalRepository',`

This need to be read at your  laravel-modules/src/Providers/ContractsServiceProvider.php

Old:
`$this->app->bind(RepositoryInterface::class, LaravelFileRepository::class);`

New:
`
$driver = ucfirst(config('modules.driver'));

        if (strcasecmp($driver, 'Custom') == 0) {
            $repositoryClass= config('modules.custom_driver');
        } else {
            $repositoryClass= LaravelFileRepository::class;
        }

        $this->app->bind(RepositoryInterface::class, $repositoryClass);

`

**Comment by nWidart** [comment]
I see, that's what the branch I linked is for.

I'll close this in favour for #171
