### ISSUE TITLE
Adding a Service Provider other than Module's gives Not Found Error

### ISSUE THREAD

**Issue by n4p4** [nWidart/laravel-modules#58]
A custom Module does not accept additional Service Providers besides its own. Whenever I try to add a new one, it gives me a Not Found Error in the console even though I added this new provider to the providers array in module.json!

**Comment by dumindu** [comment]
Run 
```
composer dump-autoload
php artisan module:dump
```
and check

**Comment by nWidart** [comment]
I'll close this as this was asked multiple times.
