### ISSUE TITLE
Commands in Module not working

### ISSUE THREAD

**Issue by nasirkhan** [nWidart/laravel-modules#581]
I created a new command for one of my modules. But when it is not available on the list (`php artisan list
`). I checked the issue #418 but it did not solve the issue. There is no details found on the doc as well.

Can you please give a link where can i find details about creating a command within a module.

**Comment by nWidart** [comment]
Hello,

How are you registering your command in laravel?

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
