### ISSUE TITLE
How can i use laravel dusk in laravel module?

### ISSUE THREAD

**Issue by dang-tien** [nWidart/laravel-modules#584]
Hi all,
In my small project, i want to apply laravel dusk into laravel module.
But laravel module have not support command for it yet.
I am so sad about that :((
Can you add it in the next version? 
In my case now, can you teach me a simple way to help me apply laravel dusk?
Have nice day!
Thank you so much.

**Comment by nWidart** [comment]
Hi,

I don't see why it wouldn't work. Just use laravel dusk as usual.

**Comment by dang-tien** [comment]
Hi, I mean when i try to run `php artisan module:dusk-install ModuleExample`
The folder Browser will be create in Modules/ModuleExample/Tests/
So we can use laravel dusk for Module specific

**Comment by nWidart** [comment]
I see.

From what I see in Dusk it creates this: https://github.com/laravel/dusk/blob/3.0/src/Console/stubs/test.stub

This seems to be fairly minor so not sure I see added value here, especially since it's not native in laravel but a package.
With this reasoning people will ask to generate things from other packages too.

**Comment by jamesratcliffe** [comment]
Tip for running tests outside of Dusk's default directory:
https://laracasts.com/discuss/channels/testing/laravel-dusk-test-cases-in-different-sub-dir-than-browser

Basically, you create a phpunit.dusk.xml file that points to your tests.

Example test suite section:
```xml
    <testsuites>
        <testsuite name="Browser">
            <directory suffix="Test.php">./Modules/**/Tests/Browser</directory>
        </testsuite>
    </testsuites>
```

**Comment by nWidart** [comment]
Nice! Thanks for the tip! 👌
