### ISSUE TITLE
Possibility of renaming module

### ISSUE THREAD

**Issue by sykorax** [nWidart/laravel-modules#585]
Hey,

What do you guys think about this feature? It would be so useful in some situations.

The rename command could change the module namespace part in all related php files by itself.
I have found a similar command in the Laravel Foundation package, called ``AppNameCommand (php artisan app:name {name})``.
Also the command could optionally rewrite the entry service provider which was generated from the module name initially.

Is there any chance to implement it?

**Comment by nWidart** [comment]
Hello,

Hmm not sure. I can see the usefulness but it seems to be a small part of writing a module.
An idea like phpstorm will do a lot of this for instance.

Changing the service provider seems dangerous too.

Maybe something that simply renames the namespace, possibly.

**Comment by nWidart** [comment]
I'm not sure I understand why you want to service provider to read `module.json`. It would be a performance issue.

**Comment by sykorax** [comment]
The service provider could read the alias name of module so the provider could register the view and translation namespace with the alias obtained from the modules.json. It would be nice in case you have to rename the entire module.

Maybe the content of module.json can be cached. So it wouldn't cause performance issues.

### Example
#### This is it now
```php
     /**
     * Register translations.
     *
     * @return void
     */
    public function registerTranslations()
    {
        $langPath = resource_path('lang/modules/tenant-application');

        if (is_dir($langPath)) {
            $this->loadTranslationsFrom($langPath, 'tenant-application');
        }
        else {
            $this->loadTranslationsFrom(__DIR__ . '/../Resources/lang', 'tenant-application');
        }
    }
```

#### It could be
```php
     /**
     * Register translations.
     * @param string $alias The alias name which is obtained form the module.json file. 
     * @return void
     */
    public function registerTranslations($alias)
    {
        $langPath = resource_path('lang/modules/' . $alias);

        if (is_dir($langPath)) {
            $this->loadTranslationsFrom($langPath, $alias);
        }
        else {
            $this->loadTranslationsFrom(__DIR__ . '/../Resources/lang', $alias);
        }
    }
```

### Additional advantages
You made me think about this module.json stuff and realised it can be used easily to configure your modules as dynamically as you wish.
For us it is good to create custom attributes in the module.json file so we can determine which module is purchasable and not. With a nice built-in caching feature it would allow us to easily utilize custom fields.
(And well, we can describe the dependency tree of each module. So the user can see the desired module depends on other purchasable modules)

Actually i think this module.json could be a nice place to hold custom data attributes of a module.

You may say why do we not track the purchasable flag for each module in the database? 
Well, to be honest, we have a tons of configurable thing around and don't want to mess with one more seeder and syncer.

**Comment by sykorax** [comment]
I frogot to say.
You may say the module config file is ideal to store such info like the purcasable flag. Yes, that's correct.
But i think configs are more like parameters and not attributes.

An attribute can describe the module partially but configurations are parameters for the module that tells how module should behave.

This is just philosophy idea, nothing more. I can accept that module.json files are not made for this purpose. :)

**Comment by nWidart** [comment]
I see, you can already use the module.json file for this purpose. There's a method on the Module class to get any property out of the file. Here: https://github.com/nWidart/laravel-modules/blob/master/src/Module.php#L226-L229

I don't believe it's a good idea to do this (by default) in the service provider though as it has a performance impact. However you can use if you wish.

**Comment by sykorax** [comment]
Okay, thank you. Closing this :)
