### ISSUE TITLE
Prefixed migrations

### ISSUE THREAD

**Issue by sykorax** [nWidart/laravel-modules#586]
Hey,

We are using a lot of (custom) modules - written in nWidart - for our projects. We really do love the module-specific migration and seeding methods provided by the package. We have multiple multi-tenant application and there's one which uses per / tenant application pattern which means that we can install / remove certain packages in the tenant context automatically. In order to make it work nicely we can use the module specific migrations for tenant specific database operations and schema management.

However sometimes it's getting difficult when we have for example two different module with the absolutely same migration name. We know that Laravel requires migrations to be absolutely unique in the application wide level.

Is it possible to make nWidart to create migrations with prefixes optinally? I mean the package would create migrations with the module name prefix automatically.

Example:
We have two modules.
- TenantApplication
- PortalApplication

Let's say the authentication happens in the PortalApplication module but we need two different user entities for the moduels. So both modules will have a ``User`` entity.
It would be nice if the package could create migrations for these entities prefixed with the module name.

##### Entity
``Modules/TenantApplication/Entities/User.php``

##### Migration
``Modules/TenantApplication/Database/migrations/{timestamp}-create_tenant_application_users_table.php``

##### Entity
``Modules/PortalApplication/Entities/User.php``

##### Migration
``Modules/PortalApplication/Database/migrations/{timestamp}-create_portal_application_users_table.php``

**Comment by bloggervista** [comment]
Yea I guess it will be fairly simple to implement also :D

**Comment by nWidart** [comment]
Hello,

AsgardCMS does this by wrapping the `module:make` command and customising things to that use case (one of which prefixes the migration names)

I think this kind of customisation is better left to everyone to wrap & customise since there are a lot of possible use cases and solutions.

**Comment by nWidart** [comment]
Edit: looks like you want the file names to be prefixed. I think this could indeed be done.

PR's accepted 🙄 It would have to be backwards compatible.

**Comment by sykorax** [comment]
Yes, you got the point. Sorry if i was not understandable :)

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
