### ISSUE TITLE
Installation problem in Lumen

### ISSUE THREAD

**Issue by denissuarez** [nWidart/laravel-modules#587]
Hello,

I installed the laravel-module component in a clean installation of lumen, I configured the autoloading. Then I followed the steps described in the following URL: https://nwidart.com/laravel-modules/v3/lumen

After all the installation I created my first module with the command "php artisan module: make blog", after creating it I receive the following error:

```
In BlogServiceProvider.php line 73:

   Class 'Config' not found
```

Line 73 of the BlogServiceProvider.php file contains the following:

```
$ this->loadViewsFrom(array_merge (array_map (function ($path) {
             return $path.'/modules /blog';
         }, \Config::get ('view.paths')), [$sourcePath]), 'blog');
```

Can anybody help me?

Regards, and thank you very much

**Comment by denissuarez** [comment]
I'm not understanding what you're asking me. The error code is generated by the command mentioned above. The version of lumen is 5.5.

Thank you very much

**Comment by nWidart** [comment]
I can't help you without more information.

This is not related to this package, please refer to the lumen docs.

**Comment by denissuarez** [comment]
The error I get after installing the laravel-module package, and generating a new module with the command available in your package. That's why I post it here. The same I explained wrong, my English is pretty bad ...

I get the error after executing the command:
php artisan module: make <module-name>

It is in the generated module where said error appears.

**Comment by nWidart** [comment]
Yes but it's not related to this package.

Your issue is with php and lumen usage.

**Comment by alexdrakeonline** [comment]
Hello,

I installed lumen, then installed the laravel-module I also followed the steps described at https://nwidart.com/laravel-modules/v3/lumen

run command "php artisan module:make User" as per instructions module generated 
after this trying to create migrations by following doc https://nwidart.com/laravel-modules/v3/advanced-tools/artisan-commands getting error 

In Application.php line 176:

  Class 'Modules\User\Providers\UserServiceProvider' not found

Can anybody help me?
Thanks in advance
