### ISSUE TITLE
creating Plain module does not generate start.php

### ISSUE THREAD

**Issue by ejlocop** [nWidart/laravel-modules#588]
**package version**: 3.x

when creating a plain module does not generate start.php but the modules.json wants it. and producing an error in:
> vendor\widart\laravel-modules\src\Module.php:292
> include(Modules/Blog/start.php): failed to open stream: No such file or directory

here's the modules.json
```
{
    "name": "Blog",
    "alias": "Blog",
    "description": "",
    "keywords": [],
    "active": 1,
    "order": 0,
    "providers": [
        
    ],
    "aliases": {},
    "files": [
        "start.php"
    ],
    "requires": []
}
```

you just have to remove the start.php in order to run.

**Comment by MladenJanjetovic** [comment]
same here. plane module created and it's asking for start.php. Tnx

**Comment by ejlocop** [comment]
@MladenJanjetovic just remove the start.php inside the modules.json file.

```
    "files": [
        "start.php"
    ],
```

**Comment by MladenJanjetovic** [comment]
@ejlocop Thanks. I have used the start.php from full build, so I can have routes initialized
