### ISSUE TITLE
Why use Routing Controller?

### ISSUE THREAD

**Issue by renanBritz** [nWidart/laravel-modules#589]
Hello!

I believe that resource controllers generated with `module:make-controller` should extend the `App\Http\Controllers\Controller`, because it has useful traits, such as (AuthorizesRequests, DispatchesJobs, ValidatesRequests).

Artisan's `make:controller` command generates resource controllers that extends that class.

Regards!

**Comment by nWidart** [comment]
good idea. Feel free to contribute.
