### ISSUE TITLE
Support for Laravel LTS version (5.1)

### ISSUE THREAD

**Issue by dumindu** [nWidart/laravel-modules#59]
I tried to integrate this package to a Laravel 5.1 project but get,
"**ReflectionException in Container.php line 741: Class web does not exist**" error when accessing module urls. more info: http://pastebin.com/baJgfzdt

### Steps to reproduce
* composer create-project laravel/laravel laravel_test_ii "5.1.*"
* cd laravel_test_ii
* composer require nwidart/laravel-modules
* update config/app.php (provider & alias)
* php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"
* update composer json  ("Modules\\": "Modules/")
* php artisan module:make Blog User Auth
* composer dump-autoload
*  php artisan module:dump
* php artisan module:list (enabled)
* php artisan serve
* http://localhost:8000/blog

Please support for LTS versions. And any idea how to solve this?

**Comment by nWidart** [comment]
You need to install an older version for the LTS support. I think [0.9](https://github.com/nWidart/laravel-modules/releases/tag/0.9)

**Comment by dumindu** [comment]
Tested with 0.10 and 0.9 and not worked. But as I saw, those are older versions with lesser features, unsolved bugs and etc. So I don't think that it's wiser to use this package with LTS versions.

**Comment by nWidart** [comment]
LTS will not be supported.

You can use the older version which worked before.
