### ISSUE TITLE
module:seed --class Does not seem to work

### ISSUE THREAD

**Issue by Instanced** [nWidart/laravel-modules#590]
hi, I use `php artisan module:seed User --class=xxx` Does not seem to work?

**Comment by renanBritz** [comment]
Hello!

It does not seem to work indeed. Did you find a solution?

Regards.

**Comment by Instanced** [comment]
@renanBritz  see #591

**Comment by wakjoko** [comment]
hey guys,

i got it my custom seeder class working.

to insert seeded data you'll need to define it in `module.json`
```
{
    "name": "Rates",
    "alias": "rates",
    .
    .
    .
    "migration": {
        "seeds": [
            "Modules\\Rates\\database\\seeds\\v1\\DatabaseSeeder"
        ]
    }
}
```
then run command
`php artisan module:seed Rates` to seed all the seeders defined there or
`php artisan module:seed Rates --class=DatabaseSeeder` to seed one single seeder.

the key here is to define your seeder classes in `module.json`

**Comment by sachinKriss** [comment]
you are the best, you saved my day
