### ISSUE TITLE
Call to undefined method Illuminate\Foundation\Application::configure()

### ISSUE THREAD

**Issue by jwilkersonPericia** [nWidart/laravel-modules#595]
I followed the guide exactly but when I try to load the site, I get the following error:

Fatal error: Uncaught Error: Call to undefined method Illuminate\Foundation\Application::configure() in C:\xampp\htdocs\ExpoCRM\bootstrap\app.php:19 Stack trace: #0 C:\xampp\htdocs\ExpoCRM\public\index.php(38): require_once() #1 {main} thrown in C:\xampp\htdocs\ExpoCRM\bootstrap\app.php on line 19

I'm getting the error following this step: https://nwidart.com/laravel-modules/v3/lumen

My bootstrap/app.php is as follows (some comments taken out for brevity):

```
<?php

$app = new Illuminate\Foundation\Application(
    realpath(__DIR__.'/../')
);

//loading the config and service provider
$app->configure('modules');
$app->register(\Nwidart\Modules\LumenModulesServiceProvider::class);


$app->singleton(
    Illuminate\Contracts\Http\Kernel::class,
    App\Http\Kernel::class
);

$app->singleton(
    Illuminate\Contracts\Console\Kernel::class,
    App\Console\Kernel::class
);

$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    App\Exceptions\Handler::class
);

$app->bind('path.public', function() {
 return __DIR__ . 'public/';
});

return $app;
```

**Comment by nWidart** [comment]
Please format your code blocks.

**Comment by nWidart** [comment]
I'm unfamiliar with lumen. Lets group all lumen issue in one issue #594, thanks.
