### ISSUE TITLE
Loading order

### ISSUE THREAD

**Issue by spescina** [nWidart/laravel-modules#6]
Hi. Is there a way to load modules in a specific order?

**Comment by nWidart** [comment]
Hello,

Yes, the `module.json` file has an `order` key which is used to determine the loading order.

**Comment by spescina** [comment]
loading order is from lowest to highest, right?

**Comment by nWidart** [comment]
Correct, 0 will be loaded first.

**Comment by patrick204nqh** [comment]
So if you need to arrange the modules to override each other (such as overriding routes, controllers, views, ...), how to configure them?

      Modules
        |-- Carts 
              |-- Resources
              |-- Routes
              |-- Providers
               ....
        |-- Products
              |-- Resources
              |-- Routes
              |-- Providers
              .....

=> How to override routes of Carts to Products? -> ProductsServiceProvider load later CartsServiceProvider..
