### ISSUE TITLE
Versionable modules

### ISSUE THREAD

**Issue by msieprawski** [nWidart/laravel-modules#60]
Hi,

In my system I've got products units table (part of Products module) where I keep pre-defined units: cm/mm/kg. Let's say I want to add extra unit to this table. My site is live (production) so I can't simply reinstall it to call a seeder once again with new values. I need to add new Seeder with just one line (new unit). It's not a cleanest way to do it. Is there any better way for that kind of actions?

**Comment by nWidart** [comment]
I don't know what you mean exactly, but you shouldn't have to run the seeds on production.

Versioning modules is however you want, for instance composer

**Comment by msieprawski** [comment]
All right. What if I need to add one extra record to my products unit table. Where I should put the "update" module logic? Should I do this as a migration? And then on production call `php artisan module:migrate products`?

**Comment by nWidart** [comment]
Where ever you prefer.

Adding new records can be a seed class, or a migration.

**Comment by msieprawski** [comment]
All right. Thanks for explanation.
