### ISSUE TITLE
Can't import react component

### ISSUE THREAD

**Issue by shawnhind** [nWidart/laravel-modules#600]
I'm trying to switch one of the modules in my application to use react rather than Vue.

What I've done:
Went into Module/MyModule directory
npm install react --save
npm install react-dom --save

Next I modified Module/MyModule/webpack.mix.js and changed mix.js to mix.react (changing nothing else).

Next I created an example component in Module/MyModule/Resources/Assets/js/components/Main.js

Next I went into my Module/MyModule/Resources/Assets/js/app.js (it was previously empty) so I just added "import Main from ./components/Main;"

Next I did:
npm install && npm run dev

npm run dev fails saying it can't find Main.js.

I'm not sure what I'm doing wrong.  I'm new to Laravel.

**Comment by nWidart** [comment]
Hi,

There's is nothing special related to this package when using frontend stuff.
