### ISSUE TITLE
How to link to css or js files in laravel module?

### ISSUE THREAD

**Issue by dang-tien** [nWidart/laravel-modules#602]
Hi guys!
I have a problem. I need a help.
I want to link to the css or js file inside the module.
When I try to run the command
`{{Module :: asset ('blog: css / blog.css')}}` in the module's app.blade.php file.
is on the head tag but it does not work.
I have public module as follows
`php artisan module: publish`
But everything is not better.
Here is my directory structure:
```
-Modules
     -Blog
          -Assets
              -css
                  blog.css
          -Providers
              BlogServiceProvider.php
          -Resource
              -views
                  app.blade.php
```
Do I need to configure anything in BlogServiceProvider.php file?
Thanks for all the help.
I wish you a happy day

**Comment by KABBOUCHI** [comment]
you can use Laravel Mix to copy ``blog.css`` to the ``public`` folder and use ``mix('css/blog.css')``

```js
//webpack.mix.js
const { mix } = require('laravel-mix');

mix.setPublicPath('../../public');
mix.copy( __dirname + '/Assets/blog.css', 'css/blog.css');
```

**Comment by KABBOUCHI** [comment]
@dang-tien if your issue has been resolved, plz close it :)
