### ISSUE TITLE
vendor autoload problem

### ISSUE THREAD

**Issue by Hackman1993** [nWidart/laravel-modules#604]
I'm writing a module with autodesk\forge-client.And my composer.json in the module require part looks like this:
```
"require": {
        "autodesk/forge-client": "^1.0",
        "klein/klein": "^2.1",
        "vlucas/phpdotenv": "^2.5"
    },
    "autoload": {
        "psr-4": {
            "Modules\\MyProject\\": ""
        }
    }
```
After I updated,the thirdparty lib is absoluty in the vender directory in the module.but i still can't use the classes in this module,such as Autodesk\Auth\OAuth2\TwoLeggedAuth.
the page throws Class 'Autodesk\Auth\OAuth2\TwoLeggedAuth' not found. Do i have to add some prefix or something  to refenrence the class which was required in the module's vendor directory?

PS: I'm new to php,and thank you for your time

**Comment by Al-bambino** [comment]
I have the same problem with other lib, does someone knows what should be done?

**Comment by nWidart** [comment]
Indeed you need to require the module in the main composer package.
You can also avoid this by using the _composer merge plugin_.

**Comment by Hackman1993** [comment]
Thank you for your answer,problem resolved

**Comment by mowses** [comment]
I am facing the same issue. @Hackman1993 can you please describe the solution you used to address the problem?

@nWidart I still have doubts about your answer : If my modules require other composer packages, should I require my module in the main composer package? Why composer just dont look into the Modules/MyPackage/composer.json file and installs the required packages into the main application vendor folder?

**Comment by Hackman1993** [comment]
> I am facing the same issue. @Hackman1993 can you please describe the solution you used to address the problem?
> 
> @nWidart I still have doubts about your answer : If my modules require other composer packages, should I require my module in the main composer package? Why composer just dont look into the Modules/MyPackage/composer.json file and installs the required packages into the main application vendor folder?

As the author said, download a composer merge plugin will resolve this problem
