### ISSUE TITLE
Dusk test not being included from modules

### ISSUE THREAD

**Issue by filtration** [nWidart/laravel-modules#605]
I have a test folder under `app\Timeline\Tests\Browser` when I run `php artisan dusk` non of my tests run, but if I cd `app\Timeline` and run `php artisan dusk` my tests run, I have the psr autoload in my composer under timeline:

    "autoload": {
        "psr-4": {
            "App\\Timeline\\": "",
            "App\\Timeline\\Tests\\": "tests/"
        }
    }

Any ideas?

**Comment by nWidart** [comment]
I haven't used dusk so I can't help you with this sorry.

I assume it's just the same as any usual test.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
