### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by alexdrakeonline** [nWidart/laravel-modules#610]
Hello,

I installed lumen latest version, then installed the laravel-module I also followed the steps described at https://nwidart.com/laravel-modules/v3/lumen

run command "php artisan module:make User" as per instructions module generated
after this trying to create migrations by following doc https://nwidart.com/laravel-modules/v3/advanced-tools/artisan-commands getting error

In Application.php line 176:

Class 'Modules\User\Providers\UserServiceProvider' not found

Can anybody help me?
Thanks in advance

**Comment by nWidart** [comment]
Please refer to #594
