### ISSUE TITLE
View Dosen't change

### ISSUE THREAD

**Issue by pc-mon** [nWidart/laravel-modules#613]
Hello
First of all I'd thank you for the great package,It's so amazing 
So Suddenly Views in modules only is working from cache or somewhere,When I change  blade file it dosen't work as I changed it,It's works as in last commit in git,so please help me
thank you in advance

**Comment by pc-mon** [comment]
Please don't tell me try:
composer dump-autoload
php artisan view:clear 
php artisan clear:cache 
php artisan optimize 
php artisan route:cache
because It dosn't fix my issue
php artisan route:clear
php artisan config:cache

**Comment by nWidart** [comment]
Hi,

The package doesn't do anything with your views. Check you didn't publish the views and maybe that's used instead.

**Comment by pc-mon** [comment]
Thank you for your replay 
May you explain more 
how view is work and how follow the issue apical there is no error 
I just want tutorials to help me
thank you Mr
