### ISSUE TITLE
where to run npm scripts

### ISSUE THREAD

**Issue by walidabou** [nWidart/laravel-modules#615]
Hello, I'm wondering where to run npm scripts to compile assets such as "npm run watch". Is inside a Module folder or in main laravel root ?

**Comment by KABBOUCHI** [comment]
inside the module folder

**Comment by KABBOUCHI** [comment]
Yes, in every module run `npm install && npm run watch`

if you want you can setup a custom one like this one #448 but it's not truly modular (it's fine, if u don't want to re-use the modules in other projects)

**Comment by walidabou** [comment]
So every Module must contains a node_modules folder or just the one that resides in root directory would be sufficient ?

**Comment by KABBOUCHI** [comment]
When you run `npm install` in the module will create for you `node_modules` folder.

every module has it's own`package.json` which contain the desired packages.

**Comment by walidabou** [comment]
Thank you very much for your help.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by ShanakaNCG** [comment]
Without installing npm in each Modules is there a way to keep node_modules folder in root level of laravel project and use it in each modules. Because I'm using vue in each modules and have to install vue and other npm packages in each modules

**Comment by pmochine** [comment]
@ShanakaNCG Good question! I wonder how one can fix it.

**Comment by samerzaki** [comment]
any news about installing modules node packages in the root folder without having node_modules folder for each module ?

**Comment by rutvij2292** [comment]
Basically I have placed Modules folder inside app directory and how I fixed it. I know it looks ugly but I don't know how can I do it efficiently. Poor me. :D

```
// Changes I have made in webpack.mix.js inside each modules

mix.setPublicPath('../../../public').mergeManifest();

mix.js(__dirname + '/Resources/assets/js/app.js', '../../../public/js/modules/blog.js')
    .sass( __dirname + '/Resources/assets/sass/app.scss', '../../../public/css/blog.css');

/*
app/Modules/Blog
../../../ 
*/
```

**Comment by satyam147** [comment]
I have linked root node_modules folder to every module using symlink

**Comment by ShanakaNCG** [comment]
After two years I'm replying to my own question [here ](https://github.com/nWidart/laravel-modules/issues/615#issuecomment-490830799) 
you need to configure webpack.mix file to use laravel mix to compile all of js and install all of the node modules in the root and you can use those node modules for any of your nWidart laravel modules inside of your project and you should not install any of node in nWidart laravel modules. just need to create app.js or any of your js files that will import your useful node modules from the root directory for your nWidart laravel module. I will explain to you if needed any more details. Practically this approach maked my production deployment 15 min to 3 min now and no need to install the same node modules for each nWidart laravel module. @pmochine This will help you

**Comment by jstam89** [comment]
> After two years I'm replying to my own question [here ](https://github.com/nWidart/laravel-modules/issues/615#issuecomment-490830799) you need to configure webpack.mix file to use laravel mix to compile all of js and install all of the node modules in the root and you can use those node modules for any of your nWidart laravel modules inside of your project and you should not install any of node in nWidart laravel modules. just need to create app.js or any of your js files that will import your useful node modules for vue components, from the root directory for your nWidart laravel module. I will explain to you if needed any more details. Practically this approach made my production deployment 15 min to 3 min now and no need to install the same node modules for each nWidart laravel module. @pmochine This will help you

Can you elaborate some more about this question? I'm currently facing the same problem and with 50 modules it takes a lot of time to run npm install & npm run dev everywhere.

**Comment by shan-gamage** [comment]
@jstam89 sure. I can help you with this. Can explain me a little bit of your project structure. ( I also had a lots of modules inside of a project and did the research and learnt to optimize the project deployment also)
