### ISSUE TITLE
check if module is enabled

### ISSUE THREAD

**Issue by Surt** [nWidart/laravel-modules#616]
Hi @nWidart ,

I was wondering if there is any method to check if a given module exists and is enabled. I can ask for all enabled modules and perform a key isset but it would be great to have that method already created on \Module.

I need it to check if a given module is enabled or exists so I can render its routes on my layout without an error (route does not exists)

By the way, when doing a ```Module::all()``` I can't see the module status (active or not) and it says 
```
 #hasBeenBootstrapped: true
 #booted: true
```
when I already "disabled" them. Is there any way to avoid bootstrap and boot if the module is disabled?

**Comment by nWidart** [comment]
Hi,

Indeed there is:

https://github.com/nWidart/laravel-modules/blob/master/src/Module.php#L323-L326

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by Surt** [comment]
Thank you a lot @nWidart it was just as you said!

**Comment by nWidart** [comment]
Awesome! 👍

**Comment by alagoroVigo** [comment]
I was looking for the same. `Module::find('module-name')->active` returns 1 for active/enabled and 0 for inactive/disabled. But, what about if the module isn't even under the Modules directory, that is, if ot doesn't exist?
