### ISSUE TITLE
Can i disable module for specific domain route

### ISSUE THREAD

**Issue by SparkosisNR** [nWidart/laravel-modules#617]
Hello,

I would like to know if i can disable a specific module in a specific route.

For example,

I have a route 
```php
 Route::domain('{account}.myapp.com')->group(function () { Route::get('user/{id}', function ($account, $id) { // }); }); 
```

i would like to disable module if this domain can't have the module without impact other domains ?

if i have module blog for mydomain1.com and not in mydomain2.com i want to disable module only for mydomain2.com

Thanks for advance,

**Comment by SparkosisNR** [comment]
Thanks,

I have to check if my customer have blog module and get blog module and disable it with disable method, right ?

**Comment by nWidart** [comment]
That's correct.

**Comment by SparkosisNR** [comment]
Nice, thanks again for your time :D and thanks for ur great package :) very helpful

**Comment by nWidart** [comment]
Now that I think of it, if I'm not mistaken that will change the module.json file. So you might have to do something more custom in order to achieve this.

**Comment by SparkosisNR** [comment]
Oh, yeah i see, so it can disable it for others domains too. Im gonna to think about it

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by rvzug31** [comment]
Hi, what is the best approach to prevent a module to be loaded at runtime?

E.g.: I've 5 modules, and a couple of Routes that only require one module. At this moment all the modules are loaded while bootstrapping and taking unnecessary memory/time. 

I could think about middleware and disable the module manually, but this is (if i'm right) after bootstrapping. Also the other Routes should use more (or all) modules, so using ``Module::disable`` and changing the module.json is not a good option.

Thanks
