### ISSUE TITLE
Documentation of classes changes

### ISSUE THREAD

**Issue by YellowFish085** [nWidart/laravel-modules#619]
Hello,

First of all thanks for this amazing package which I basically use in every project I work.

I just updated the packages of a project I'm working on (we were on 3.0.0 and now on 3.0.1). First things weird is that it seems that you renamed the [src/Laravel/Repository into src/Laravel/LaravelFileRepository](https://github.com/nWidart/laravel-modules/blob/master/src/Laravel/LaravelFileRepository.php) in the 3.0.0 release, but looking at the content of the package in our vendor directory we still had the old file. We double checked just a moment ago by doing a clean install of the packages in 3.0.0 and it's was the old file.

In any cases, in some of our code we inject this class (with dependency injection, we don't use Laravel Facades system), but since this changes was not documented in the changelog for 3.0.1 nor 3.0.0 (which again seems to be the release when the change were made even if our 3.0.0 had the old file), we spent some time figuring out why our the module was suddenly not working anymore.

It _could_ be nice if such changes were tracked in the changelog. It's not a really big issue, but since not everyone use the Facades system this could be nice to know some changes like that :)

So yeah, not a real issue, just a recommendation maybe?

Again thanks for the work on this package, cheers!

**Comment by nWidart** [comment]
Hello,

Thank you for the kind words.
I'm not sure to which changes you're referring. If it's the breaking changes of 3.0, they're documented in the changelog file, as well as the releases page: https://github.com/nWidart/laravel-modules/releases

**Comment by YellowFish085** [comment]
I'm referring to [d5fec20](https://github.com/nWidart/laravel-modules/commit/d5fec20c08e4ef339c1079d547b525d42ebe95ba) where `src/Laravel/Repository` was renamed to `src/Laravel/LaravelFileRepository`. This change seems to be included in the [3.0.0 release](https://github.com/nWidart/laravel-modules/compare/3.3.0...master) (like I said "seems" since for a weird reason the change is not present when we use the 3.0.0 in our project).

As you can see in the [release post](https://github.com/nWidart/laravel-modules/releases/tag/3.3.0) and in the [changelog](https://github.com/nWidart/laravel-modules/blob/master/CHANGELOG.md#330---2018-06-21), the change is not documented.

___

In our code, instead of using [the Facade](https://nwidart.com/laravel-modules/v3/advanced-tools/facade-methods), he have (had) things like
```php
<?php

use Nwidart\Modules\Laravel\Repository;

class MyClass
{

    protected $repository;

    public function __constructor(Repository $repository)
    {
        $this->repository = $repository;
    }

    public function anAction()
    {
        $moduleA = $this->repository->find('module_A');

        // more code
    }
}

```

With the change, we had to change our `use Nwidart\Modules\Laravel\Repository;` into `use Nwidart\Modules\Laravel\LaravelFileRepository;`.


That being said, maybe we should inject another class, or an interface, instead of `LaravelFileRepository`? Which could be why the change was not documented since we're not supposed to directly inject this class?

**Comment by nWidart** [comment]
Oh yes, I see. Indeed you're right I should have documented this. 
The interface was not changed if I'm not mistaken so if you type hinted the interface there shouldn't have been issues. 

In your example, I would suggest type-hinting the interface instead of the implementation.

**Comment by YellowFish085** [comment]
Okay then I will do that.

Thanks for the answers!
