### ISSUE TITLE
How to list routes for specific module?

### ISSUE THREAD

**Issue by itsursujit** [nWidart/laravel-modules#624]
Hello,
Thank you for this package. I'm trying to dump the routes for modules in separate JSON files. How can I list routes for modules and dump them to JSON?

**Comment by itsursujit** [comment]
Thank you for your response.
How can same thing be achieved in application via browser?

**Comment by KABBOUCHI** [comment]
```php
function getModuleRoutes($moduleName, $baseModulesPath = 'Modules')
{
	return collect(Route::getRoutes())->filter(function ($item) use ($baseModulesPath, $moduleName) {
		return isset($item->action['namespace']) && starts_with($item->action['namespace'], "{$baseModulesPath}\\{$moduleName}");
	})->values()->all();
}

Route::get('/test', function () {
	return getModuleRoutes('Blog');
});

```

**Comment by itsursujit** [comment]
Great! Thank you that helped

**Comment by blackhat-power** [comment]
php artisan route:list | grep 'Modules\\Blog'
is this still working?? i have tried it in laravel 8 and it has returned nothing.
