### ISSUE TITLE
Middleware not working on routes when registered to module's service provider

### ISSUE THREAD

**Issue by itsursujit** [nWidart/laravel-modules#625]
I created a module `Gateway` with a middleware `HelperMiddleware` in the module:

```
class HelperMiddleware
{
    public function handle(Request $request, Closure $next, $id)
    {
        dd($request->all());
    }
}
```

In GatewayServiceProvider I added the middleware in `boot()` function:
```
        $router = $this->app['router'];
        $router->pushMiddlewareToGroup('gateway', HelperMiddleware::class);
```

Then I tried to call it on routes.php as:
```
Route::group(['middleware' => 'gateway', 'prefix' => 'api'], function()
{
    Route::group(['prefix' => 'gateway', 'namespace' => 'Modules\Gateway\Http\Controllers'], function()
    {
        Route::get('/{slug?}', 'GatewayController@index');
    });
});
```

But the middleware is not executed at all.

Please let me know how could I add custom middleware in the module and use it in routes

**Comment by nWidart** [comment]
This is not related to this package as it doesn't touch anything with laravel. 

I'm not familiar with `pushMiddlewareToGroup`.

**Comment by itsursujit** [comment]
No as I wanted to get middleware(related) to module registered in Service Provider so that nothing on main app is changed

**Comment by nWidart** [comment]
you can do that yes.

**Comment by itsursujit** [comment]
Any supportive code snippet? I tried but that didn't work.

**Comment by nWidart** [comment]
https://github.com/AsgardCms/Platform/blob/3.0/Modules/Core/Providers/CoreServiceProvider.php#L113

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
