### ISSUE TITLE
Does commands auto-registered?

### ISSUE THREAD

**Issue by howtomakeaturn** [nWidart/laravel-modules#626]
Hi, quick question, I use php artisan module:make-command to generate command files.

Does these commands auto-registered in the app?

Or I should manually register them in app/Console/Kernel.php?

Thanks!

**Comment by nWidart** [comment]
Hello,

it won't no sadly because laravel itself doesn't want it, I asked them about it a while ago.
So you have to register them yourself. It doesn't have to be in the kernel.php file though, it can be in a service provider.

**Comment by howtomakeaturn** [comment]
Hi, according to the official doc here:

https://laravel.com/docs/5.6/artisan#registering-commands

> Because of the load method call in your console kernel's commands method, all commands within the app/Console/Commands directory will automatically be registered with Artisan.

So the default assumptions is like 'command files under Command folder will be auto-registered'.

Maybe in the service provider generated from your package, load the commands files, too?

        $this->registerTranslations();

        $this->registerConfig();

        $this->registerViews();

        $this->registerFactories();

        $this->registerCommands(); // maybe add this?

        $this->loadMigrationsFrom(__DIR__ . '/../Database/Migrations');

What do you think?

And what does 'laravel itself doesn't want it' mean?

Thanks!

**Comment by nWidart** [comment]
> And what does 'laravel itself doesn't want it' mean?
It means I asked on twitter if they wanted to have it work for more than just the `app/` folder but they don't.
