### ISSUE TITLE
Access Views in Default Laravel View Paths

### ISSUE THREAD

**Issue by plunkettscott** [nWidart/laravel-modules#628]
Is there a way to access the views loaded into Laravel’s view.paths array? Anytime I try to do this I get a view not found error. Basically I want my module to be able to extend a base Laravel layout for pages it implements.

I have built a Laravel themes package that handles the theming, all it does is adds the theme view paths to the beginning of the view.paths config option in Laravel. Themes work just fine in normal Laravel, but when I load the module it cannot find the themes. I dumped the values of \Config::get(‘view.paths’) in the module and it only included the default Laravel paths.

I have a suspicion it has to do with the order that modules are loaded into. Any suggestions to handle this? I need the themes to be extendable by the modules.

Scott

**Comment by nWidart** [comment]
A module should be able to use a view in the "global" views folder yes.
I also use themes in AsgardCMS which uses this package too and it works.

**Comment by mikemand** [comment]
It doesn't seem to work in Asgard 3.0, @nWidart. I tried to include a theme view from `/Themes/Mytheme/views/blog/post.blade.php` (`return view('blog.post', \compact('post'));`) in an Admin controller (`\Modules\Blog\Http\Controllers\Admin\PostPreviewController`), and Laravel kept telling me that "`View [blog.post] not found`".

I tried `composter dump-autoload`, `artisian clear-compiled` (and manually deleting all `.php` files in `/bootstrap/cache/` because the Module's cached files aren't cleared with this command), `artisian view:clear`, `artisian cache:clear`, etc...

**Comment by nWidart** [comment]
Hm strange, that's maybe more related to the theme package than modules then.
I just tried to use a view from the global views folder inside a module, and it works.

Example in a clean install of laravel 5.7 & one generated module

```php
    public function index()
    {
        return view('welcome');
    }
```
Returns that view correctly.

**Comment by mikemand** [comment]
So it may be something with the way Asgard is registering themes, then. I created a fresh v3 and dumped the `view.paths` config in various places. All of theme came back as such:

```
array:1 [▼
  0 => "/Users/micheal/Documents/Code/Sandbox/Blog/resources/views"
]
```

**Comment by nWidart** [comment]
yea it's weird because I thought the view first goes through the global folder, then the theme folder and so on. This is how the dashboard works at the moment if I'm not mistaken.

Though this issue at hand here from OP should be ok. 😄

**Comment by nWidart** [comment]
Here's an interesting tweet: https://twitter.com/freekmurze/status/1045679508928561152

And solution : https://twitter.com/taylorotwell/status/1045680305120661507

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
