### ISSUE TITLE
Composer requirements installation path

### ISSUE THREAD

**Issue by freescout-helpdesk** [nWidart/laravel-modules#630]
When the module is installed, where will be the packages required in composer.json installed? In the root `/vendor` folder of the Laravel project? Or in the module's `vendor` folder (for example `/Modules/Blog/vendor` or `/Modules/vendor`)?

**Comment by nWidart** [comment]
By default it's the vendor folder. If you create a composer plugin you can place it where ever you want.

**Comment by freescout-helpdesk** [comment]
Thanks, can you give a hint where more info on using composer plugins with laravel-modules can be found?
