### ISSUE TITLE
Different Database for different module

### ISSUE THREAD

**Issue by cindyming** [nWidart/laravel-modules#631]
Hi,
I try to use different DB for different module for the API requirement, Now all things goes well. Now only one thing will cause issue for that, Even we have different DB for each module, but the migrations is the global, the migrations record only exist in the default connection DB. So the migration will be confused. Such as like

we have two connection, 
- mysql
- mysql2

We have two module:
- blog (use mysql)
------ 2018_09_21_031323_create_blog_table.php
- news(use mysql2)
------ 2018_09_19_144957_create_news_table.php

we execute:
php artisan migrate
- The two migration will be executed

php artisan migrate-rollback 
- two of them will be rollbacked, How can we protected module migration is rollbacked by root migrate::rollback

Thanks
Cindy

**Comment by nWidart** [comment]
Hi,

I don't think that's possible since migrations are registered in laravel.
You'll probably have to create your own migrator.

**Comment by renanBritz** [comment]
Hello!

Try using the module specific command for migrations, you can run migrations individually that way. For example: `php artisan module:migrate Blog` ([docs](https://nwidart.com/laravel-modules/v3/advanced-tools/artisan-commands))

However, the migration connection is defined in the Schema class. See [here](https://laravel.com/docs/5.7/migrations#tables).

Regards!

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
