### ISSUE TITLE
Module load slow

### ISSUE THREAD

**Issue by quienti** [nWidart/laravel-modules#634]
Hi,

I have a problem loading modules.
Indeed, after having analyzed my project, I remade that the last modules are more and more slow.
I am also attaching a result of my research.

One of my last modules is a support module, with a loading order (order to 50 in module.json).
![untitled 2](https://user-images.githubusercontent.com/7326954/45956751-5803f000-bfe1-11e8-9d6e-6cb4ed0ec691.jpg)

And now, if I ask him to load first (order at 0 in module.json)
![untitled 1](https://user-images.githubusercontent.com/7326954/45956768-6225ee80-bfe1-11e8-94cc-d3c57901dcce.jpg)

We see a clear difference in loading, knowing that no code has changed.

Do you have an idea about this problem?

Thank you in advance for your help

Laravel => 5.7
Laravel Module => ^4.0
Php => 7.2.6

**Comment by nWidart** [comment]
Seems you have something that's slow in your app.

Laravel modules has been tested and used with a lot of modules (10+), and still be sub 200ms.

**Comment by renanBritz** [comment]
Hello!

This is a long shot but...

If you're using homestead with virtualbox, shared folders could be a major overhead. File synchronization and disk performance is just slow. Try using NFS if that's the case.

Regards!

**Comment by quienti** [comment]
Hi !

No, I'm local on a windows 10 and wamp
I would have to ask my colleague what she is using because she was the one who reported the problem to me with your much higher times
(about 7 seconds)

**Comment by renanBritz** [comment]
Other than that, [blackfire.io](https://blackfire.io/docs/introduction) may help you identify performance issues.

Regards!

**Comment by quienti** [comment]
Okay, I have found my problem !!

````
/**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->registerTranslations();
        $this->app->register(RouteServiceProvider::class);
    }
````

The registerTranslations function is my problem!

But my problem is that I need to add the translations because I translate my urls in the road

An idea of ​​how I could achieve this?

**Comment by quienti** [comment]
Hi,

Thank you for your help
This problem is not from this package !

Sorry !

**Comment by AnthonyConklin** [comment]
Would like to add I was seeing same issues with this package. When I was running a local linux environment with everything running locally, it was just fine (sub 70ms). I moved my project to a dockerized environment and saw 2-6 second load times... (fastest being 800ms). I went to a fresh laravel install and migrated my code for a specific part of the project to this and was down to 30-45 ms load times. Believe it has to do with dir / file scans depending on environment its used on has drastic differences.

**Comment by Viruscom** [comment]
Hi,
I have same slow down.
I create new Laravel app (ver. 9) with no code. Response time 50ms to 58ms. After that i install 35 modules with php artisan module:make ModuleNameHere and response time goes to 3.4 sec.

Your package is aweseme, but can you check why that issue occur?
Thank you in advance.

**Comment by agwidarsito** [comment]
I seem to have the same thing, tracing shows a lot of time spent in this package during boot :(

**Comment by ayzerobug** [comment]
I'm experiencing the same thing. It's booting all modules and taking longer time

**Comment by MarianoCuenca** [comment]
We are working on a project in Laravel 9 with +50 modules and our Laravel app is taking time with each new module we create, do you have any advice? Currently our app takes more than 10 seconds to respond for each load.

**Comment by Viruscom** [comment]
In config/modules.php activate cache.

` 'cache'      => [
        'enabled'  => true,
        'key'      => 'laravel-modules',
        'lifetime' => config('default.app.cache.ttl_seconds'),
    ],`

**Comment by MarianoCuenca** [comment]
> In config/modules.php activate cache.
> 
> ` 'cache'=> ['enabled' => true, 'key'=> 'laravel-modules', 'lifetime' => config('default.app.cache.ttl_seconds')],`

I have the cache activated
'cache' => [
        'enabled' => true,
        'key' => 'laravel-modules',
        'lifetime' => 60,
 ],
 
The minimum time it takes to load a page is +8 seconds without counting the login page, but for example my login page loads in 6 seconds but if i change the status of all the modules to false in my modules_statuses.json file, i do a cache:clear and reload the same page, the time is reduced to 400 milliseconds.

**Comment by MarianoCuenca** [comment]
> In config/modules.php activate cache.
> 
> ` 'cache'=> ['enabled' => true, 'key'=> 'laravel-modules', 'lifetime' => config('default.app.cache.ttl_seconds')],`

I have the cache activated
`'cache' => [
        'enabled' => true,
        'key' => 'laravel-modules',
        'lifetime' => 60,
 ],`
 
The minimum time it takes to load a page is +8 seconds without counting the login page, but for example my login page loads in 6 seconds but if i change the status of all the modules to false in my modules_statuses.json file, i do a cache:clear and reload the same page, the time is reduced to 400 milliseconds.

**Comment by Viruscom** [comment]
Then try to debug the boot method for your module.
For example if you have module "Icons" you can go to Modules\Icons\Providers\IconsServiceProvider and in boot method you can  comment each line to check the reduction of time. After that you can try to cache the static resources like translation files or migration files. In my case, translation files was the problem. It's not the best practice, but it works.

**Comment by aspirantzhang** [comment]
> In config/modules.php activate cache.
> 
> ` 'cache'=> ['enabled' => true, 'key'=> 'laravel-modules', 'lifetime' => config('default.app.cache.ttl_seconds')],`

It's been incredibly helpful!
Here's a brief update on my situation: With around 30 modules, the booting stage was initially taking 1.20 seconds per request, which was far from ideal. 
I've managed to cut down the boot time to 700ms. It's still a bit longer than I'd like, but it's a significant improvement and manageable for now. I'll keep investigating to further optimize this. Your advice saved me a lot of time and pointed me in the right direction—much appreciated!

**Comment by peter-mw** [comment]
I have the same problem, it loads for 10 seconds with 50 modules enabled
