### ISSUE TITLE
Basic Question Regarding Webpack

### ISSUE THREAD

**Issue by mbrown1408** [nWidart/laravel-modules#636]
So, new to this whole world, I have a basic question. 

For each module created there is a dedicated package.json file, layouts folder for a master layout as well as webpack.mix.js file.

Does that mean I need to include the Laravel  base public/css/app.css and public/js/app.js containing mostly BS4 and related dependency files in every module master view? Is there a way to inherit this some how? 

If I made a change to compile an additional file that I want to be globally used, I'd have to go to every model and update the webpack.mix.js?

Thank you for assisting the new guy. I'm certain I'm missing something basic here.

**Comment by mbrown1408** [comment]
My only thought is to do an include in the master layout file containing a partial with the css/js file. It keeps from having to repeat the code in every Module.

**Comment by KABBOUCHI** [comment]
I have one module "Dashboard", contains the layout and the css framework.

Other modules extend the dashboard layout + css/js

```php
// Modules/School/Resources/views/layouts/app.blade.php
@extends('dashboard::layouts.app')

@push('styles')
    <link rel="stylesheet" href="{!! mix('/css/school.css') !!}"/>
@endpush

@push('scripts')
    <script src="{!! mix('/js/school.js') !!}" type="text/javascript"></script>
@endpush
```

**Comment by mbrown1408** [comment]
Thank you Kabbouchi,

That makes sense and the extraction information was quite helpful. Much appreciated. Not sure how I missed that section in the docs. I read up on it here: https://laravel.com/docs/5.7/mix#vendor-extraction
