### ISSUE TITLE
Help with module dependencies?

### ISSUE THREAD

**Issue by renanBritz** [nWidart/laravel-modules#637]
Hello!

Every module I create goes into a separate repository, which is probably a common scenario, from what I could see in AsgardCMS. 

What I'm having difficulty with, is when I push changes to multiple modules, and then a co-worker needs to pull those changes on their side, OR when we have to deploy the application to the test server.

We're using composer update for that, but the issue is that it takes too long, reducing our productivity. We're also having conflicts with the composer.lock file because of this.

I noticed that if I use composer update on my machine, and push the composer lock file, my co-workers can use the composer.lock to run a composer install, which is much faster.

I'm probably doing something wrong here. Can someone enlighten me?

Regards!

**Comment by nWidart** [comment]
The "composer merge plugin" might be something for you to look into. It merges mutliple composer files.

**Comment by renanBritz** [comment]
Thank you for your reply @nWidart !

I tested the merge-plugin, but it didn't pull module changes. It looks like it only merges the composer dependencies from the modules. Since my modules do not declare composer dependencies, it only printed "Nothing to update"...

Regards!

**Comment by nWidart** [comment]
Hm ok, I misunderstood the question then.

I'm not sure what the issue is.

**Comment by renanBritz** [comment]
Hm, I see.

Thanks again for your reply. I'll look for ways to improve that performance then; Plugins, maybe switch to vmware which has a better shared folder performance; Try to make use of deployment pipelines etc.

Regards!
