### ISSUE TITLE
Resource routes with parameters, expected: 404, given: route pattern error

### ISSUE THREAD

**Issue by dgbrunoh** [nWidart/laravel-modules#638]
Hi there,

1st of all, there's a chance of me doing something wrong hehe, but I'd like to check if this is happening with you also, I'm getting the error: 
```
Route pattern "/api/resource/{slug}/{{slug}}" cannot reference variable name "slug" more than once.
```
when I was supposed to receive a "404" error.

The steps to reproduce:

1. Create any new module
2. Create a resource api route with a parameter, like {slug}
3. Access the route giving the parameter: Should pass -> Passed
4. Access the route not giving parameter: Should receive a 404 -> Received the route pattern error 
5. Access any other fake route: Should receive a 404 -> Received the route pattern error (same one)

Let me know if you guys can reproduce that, or if I should be doing something extra

Thanks!

**Comment by dgbrunoh** [comment]
Hi,

I agree, and that's not the case... in a clean version my routes work.
Laravel version: 5.7
Modules: 4.0

Routes:
```
<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/

Route::resource('/forms/{slug}', 'CommonFormsController');
```

I have no idea why is doubling on the error exception

Thanks,

**Comment by arthvrian** [comment]
Hi

sorry, clean installation but wrong route (I put Route::get not Route::resource)
however, it did not work either, shows the same error

investigating a bit, I found that it's a laravel related 'error'
https://stackoverflow.com/questions/44774830/laravel-route-pattern-cannot-reference-variable-name-more-than-once

Working route:
`Route::resource('/forms/{slug}', 'CommonFormsController', ['parameters' => ['{slug}' => 'not_id']]);`

**Comment by nWidart** [comment]
Glad you got it to work 👍
