### ISSUE TITLE
Issue creating new module after upgrade

### ISSUE THREAD

**Issue by yassersharaf** [nWidart/laravel-modules#640]
PHP 7.2
Laravel 5.6
Modules version 4 ("nwidart/laravel-modules": "^4.0",)

php artisan module:make Categories
Created : \Modules/Categories/module.json

In Stub.php line 106:

  file_get_contents(\vendor\nwidart\laravel-modules\src\Support/../Commands/stubs/start.stub): failed to op
  en stream: No such file or directory

**Comment by nWidart** [comment]
Please update your configuration file, version 4 has changes to it.

**Comment by yassersharaf** [comment]
Instructions please.

**Comment by yassersharaf** [comment]
First error was 
 Nwidart\Modules\Module::main(): Failed opening required '\Modules\Categories$ROUTES_LOCATION$' (include_path='php\PEAR')

So I changed "require __DIR__ . '$ROUTES_LOCATION$';" in the start.php of the module I created to "require __DIR__ . '/Http/routes.php';" that allowed me to create the module but when I try to create another one I get the issue of "Stub.php line 106"

**Comment by yassersharaf** [comment]
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Module Namespace
    |--------------------------------------------------------------------------
    |
    | Default module namespace.
    |
    */

    'namespace' => 'Modules',

    /*
    |--------------------------------------------------------------------------
    | Module Stubs
    |--------------------------------------------------------------------------
    |
    | Default module stubs.
    |
    */

    'stubs' => [
        'enabled' => false,
        'path' => base_path() . '/vendor/nwidart/laravel-modules/src/Commands/stubs',
        'files' => [
            'start' => 'start.php',
            'routes' => 'Http/routes.php',
            'views/index' => 'Resources/views/index.blade.php',
            'views/master' => 'Resources/views/layouts/master.blade.php',
            'scaffold/config' => 'Config/config.php',
            'composer' => 'composer.json',
        ],
        'replacements' => [
            'start' => ['LOWER_NAME'],
            'routes' => ['LOWER_NAME', 'STUDLY_NAME', 'MODULE_NAMESPACE'],
            'json' => ['LOWER_NAME', 'STUDLY_NAME', 'MODULE_NAMESPACE'],
            'views/index' => ['LOWER_NAME'],
            'views/master' => ['STUDLY_NAME'],
            'scaffold/config' => ['STUDLY_NAME'],
            'composer' => [
                'LOWER_NAME',
                'STUDLY_NAME',
                'VENDOR',
                'AUTHOR_NAME',
                'AUTHOR_EMAIL',
                'MODULE_NAMESPACE',
            ],
        ],
    ],
    'paths' => [
        /*
        |--------------------------------------------------------------------------
        | Modules path
        |--------------------------------------------------------------------------
        |
        | This path used for save the generated module. This path also will added
        | automatically to list of scanned folders.
        |
        */

        'modules' => base_path('Modules'),
        /*
        |--------------------------------------------------------------------------
        | Modules assets path
        |--------------------------------------------------------------------------
        |
        | Here you may update the modules assets path.
        |
        */

        'assets' => public_path('modules'),
        /*
        |--------------------------------------------------------------------------
        | The migrations path
        |--------------------------------------------------------------------------
        |
        | Where you run 'module:publish-migration' command, where do you publish the
        | the migration files?
        |
        */

        'migration' => base_path('database/migrations'),
        /*
        |--------------------------------------------------------------------------
        | Generator path
        |--------------------------------------------------------------------------
        |
        | Here you may update the modules generator path.
        |
        */

        'generator' => [
            'assets' => 'Assets',
            'config' => 'Config',
            'command' => 'Console',
            'event' => 'Events',
            'listener' => 'Listeners',
            'migration' => 'Database/Migrations',
            'model' => 'Entities',
            'repository' => 'Repositories',
            'seeder' => 'Database/Seeders',
            'controller' => 'Http/Controllers',
            'filter' => 'Http/Middleware',
            'request' => 'Http/Requests',
            'provider' => 'Providers',
            'lang' => 'Resources/lang',
            'views' => 'Resources/views',
            'test' => 'Tests',
            'jobs' => 'Jobs',
            'emails' => 'Emails',
            'notifications' => 'Notifications',
        ],
    ],
    /*
    |--------------------------------------------------------------------------
    | Scan Path
    |--------------------------------------------------------------------------
    |
    | Here you define which folder will be scanned. By default will scan vendor
    | directory. This is useful if you host the package in packagist website.
    |
    */

    'scan' => [
        'enabled' => false,
        'paths' => [
            base_path('vendor/*/*'),
        ],
    ],
    /*
    |--------------------------------------------------------------------------
    | Composer File Template
    |--------------------------------------------------------------------------
    |
    | Here is the config for composer.json file, generated by this package
    |
    */

    'composer' => [
        'vendor' => 'nwidart',
        'author' => [
            'name' => 'Nicolas Widart',
            'email' => 'n.widart@gmail.com',
        ],
    ],
    /*
    |--------------------------------------------------------------------------
    | Caching
    |--------------------------------------------------------------------------
    |
    | Here is the config for setting up caching feature.
    |
    */
    'cache' => [
        'enabled' => false,
        'key' => 'laravel-modules',
        'lifetime' => 60,
    ],
    /*
    |--------------------------------------------------------------------------
    | Choose what laravel-modules will register as custom namespaces.
    | Setting one to false will require to register that part
    | in your own Service Provider class.
    |--------------------------------------------------------------------------
    */
    'register' => [
        'translations' => true,
    ],
];

**Comment by yassersharaf** [comment]
config/modules.php

[modules.zip](https://github.com/nWidart/laravel-modules/files/2446238/modules.zip)

**Comment by mikemand** [comment]
Make sure you've made the changes to the configuration file, like so:

https://github.com/nWidart/laravel-modules/compare/3.3.1...4.0.0#diff-215adb4f17e6c57786bec362c538ccb8

**Comment by arthvrian** [comment]
You must update your config/modules.php with the new version 
https://github.com/nWidart/laravel-modules/blob/master/config/config.php

Or you can delete config/modules.php and republish it

`php artisan vendor:publish`

**Comment by mada2u** [comment]
I upgraded from v2 to v4 and i faced this issue
i have solved it by clear cache and configurations
`$ php artisan cache:clear`
`$ php artisan config:cache`
