### ISSUE TITLE
[enhancement?] Truly resource module

### ISSUE THREAD

**Issue by arthvrian** [nWidart/laravel-modules#641]
when a module is created, by default, it comes with a controller filled with resource methods (create, show, edit, etc.) but without the routes or the views

It does not seem so complicated to do, I see two ways

1. modify the web route file and add the missing views = all modules are 'resource modules'
2. adding a --resource option in the module creation command, which would create a module as in the previous point. Without this option only the index method in the controller

**Comment by nWidart** [comment]
Hello,

I don't think this is good to have in the package itself, it would add to much bloat.
I do think it's good to have in a wrapper around the package. For example, asgardcms does this.

Thank you for the idea though!

**Comment by arthvrian** [comment]
I mean this:

https://github.com/nWidart/laravel-modules/blob/46977409dc5ee3459624051010a00058f412a94e/src/Commands/stubs/controller.stub#L20-L71

this is bloat
you have the methods but not the views or the routes

in my case many times I do not need a resource controller and it is necessary to delete that bloat
when I need it, I must modify the routes file and create the views

that's why I said that as well as the `--plain` option exists, could or should exist the `--resource` option, in the creation of the module or, when it is created without options the views and routes must be included as default, creating a '100%' functional 'resource module' without doing anything else

**Comment by nWidart** [comment]
and you can remove these methods with the plain flag as you're mentioning.
