### ISSUE TITLE
Disable module

### ISSUE THREAD

**Issue by jake142** [nWidart/laravel-modules#643]
Hi,

I'm trying to figure out what the module disable command does. As I understood it should not autoload any class from that module?

1. I have split my project into 2 modules (ModuleA, ModuleB). 
2. ModuleA has 1 job (JobA). 
3. I disabled ModuleA and tried to call dispatch(new ModuleA\JobA()); from a controller in ModuleB. 

I was expecting class not found exception (since the class should not be autoloaded) but the job is added to the queue and processed if I run artisan queue:listen. I tried composer dump-autoload after disabling ModuleA.

After installing laravel-modules I added: 

    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/",
            "Modules\\": "Modules/"
        }
    },

Is that the wrong approach if I need to disable modules?

**Comment by nWidart** [comment]
I don't think disabling a module won't autoload its classes. It's an internal status flag basically of the module api (list of modules etc.)

**Comment by jake142** [comment]
Ok, thank you.

I ended up writing my own "module system" to support disabling/enabling.

**Comment by nWidart** [comment]
Cool 👍 

There's a work in progress here to add modules in database here https://github.com/nWidart/laravel-modules/tree/feature/database-modules which would allow dynamic enabling/disabling of modules. 
Should be easy to finish if interested.

Also see #171

**Comment by jake142** [comment]
I used composer instead (wrapped in artisan commands) to require/remove modules.

https://github.com/jake142/laravel-service

**Comment by sprklinginfo** [comment]
Is this feature still in progress or abandoned?
