### ISSUE TITLE
module specific validation.php file not getting loaded

### ISSUE THREAD

**Issue by amitshahc** [nWidart/laravel-modules#645]
Hi i have created `Modules/admin/lang/en/validation.php` file. I have copy paste all the code from default validation.php file of laravel and modified the text. but when I am using the Validator:make method in controller of my admin module. the validation messages are as per default file and not module specific. 

Caveat: 
the below code is untouched in my moduleServiceProvider.php file

    public function registerTranslations()
    {
        $langPath = resource_path('lang/modules/shopowner');

        if (is_dir($langPath)) {
            $this->loadTranslationsFrom($langPath, 'shopowner');
        } else {
            $this->loadTranslationsFrom(__DIR__ .'/../Resources/lang', 'shopowner');
        }
    }

**Comment by nWidart** [comment]
Hello,

The resource path looks off. Does that path exist?

Did you try to debug what's happening by adding `dd()` for example?

**Comment by amitshahc** [comment]
it goes into else part and `dd(__DIR__ .'/../Resources/lang');` inside else prints: "D:\Installation\Apache24\htdocs\spaadvisor.com\Modules\ShopOwner\Providers/../Resources/lang" 

the above path exists as per below
! [lang folder path](https://ibb.co/eBGtLq)
! [validation.php](https://ibb.co/kpEf0q)

**Comment by nWidart** [comment]
So I don't see an issue. I would check with the laravel docs.

**Comment by Zeitwaechter** [comment]
I'ld like to reopen the issue - or at least recap the current behaviour.

Please take a look at the [L5.8 Validation Docs](https://laravel.com/docs/5.8/validation), e.G. under section _Specifying Custom Attributes In Language Files_.

1. If I place a validation rule message in a key named `attributes` in the `validation.php` of any language the `:attribute` portion of the validation message is not translated.
1. If I place the same thing into `/resources/lang/{country}/validation.php` the `:attribute` portion of the validation message is translated.

Example (`validation.php`):
```php
    return [
        'attributes' => [
            'meta.gender' => 'Your gender is missing and',
            'meta.street' => 'Your address\' street name is missing and',
            'meta.post_code' => 'Your address\' post code is missing and',
        ],
    ];
```

Example (`Request`):
```php
        public function rules(): array
        {
            $rules = [
              'meta.gender' => 'required',
              'meta.street' => 'required',
              'meta.post_code' => 'required',
            ];

            return $rules;
        }
```

I'ld be glad to get any reply if I'm missing something.

Greetings :)

**Comment by nWidart** [comment]
Hi,
This seems to be a different issue as the OP? If I remember correctly I used dynamic parts in validation messages and they worked fine.
I'm thinking this might be related to the translatable package instead of this one.

**Comment by Zeitwaechter** [comment]
Oh, hm.. okay.

I'll look into it more closely and get in touch if anything essential comes up :S

**Comment by Hieupham2k1** [comment]
hello, I have a problem with module in laravel 7, i have 2 module in my project, my first module has no problem, but my second one face the same problem as @amitshahc, the message returned is fixed, even when i use the same validate request, please help!

**Comment by Hieupham2k1** [comment]
![Screenshot (56)](https://user-images.githubusercontent.com/64056698/96337490-bfea6f00-10b1-11eb-9563-3bd764ae1523.png)
here is my request file
