### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by andrei94ro** [nWidart/laravel-modules#648]
There is a problem with migrations. 
If i have two modules, first module called 'Images' and second 'Categories' and i have two migrations

2018_10_18_183307_create_categories_table.php --- module Categories
2018_10_18_183306_create_images_table.php --- module Images

The first migration who will run is 2018_10_18_183307_create_categories_table.php with command php artisan module:migrate (because the modules will be read alphabetical)

This is bad, because if i start a project from scratch and i have 2 tables to migrate, i need to run only one command, not php artisan module:migrate Images, after php artisan module:migrate Categories. Imagine if there will be a lot of modules, and you need to setup the project. 

The command php artisan module:migrate should respect the increment id. 2018_10_18_183306 < 2018_10_18_183307 like default laravel.

**Comment by nWidart** [comment]
Hello,

I don't see the problem. What's the issue exactly?

You can run multiple migrations in one command by running `php artisan module:migrate`

Migrations will be in the right order because it has the timestamp as prefix.

**Comment by andrei94ro** [comment]
No, it is not in the right order. Is in the right order only in specific module. But if i have two different modules, this will not work.

**Comment by nWidart** [comment]
it has worked for me. Feel free to show an example project where it's not the case.

In any case, the order of modules should not matter.

**Comment by andrei94ro** [comment]
u have an foreign key? i have a foreign key in my migrations. 
in my blog migration i have a foreign key to my images. Because images are after blog, the blog migration will run first, and there is the problem, foreign key failed because migration table of images will run after blog migration.

**Comment by andrei94ro** [comment]
Hmm, i understand. If you try my example you will understand the problem. Sorry if i made a mistake.
The problem is the foreign keys outside from a module, because is true, the migrations use timestamps, but only in current module. (because `foreach ($this->module->getOrdered($this->option('direction')) as $module) {` will run migrations for the current module.)

**Comment by nWidart** [comment]
Ah yes indeed, I guess you can set the order of your modules to avoid the issue. If you put the blog module a higher order as the image module.

**Comment by andrei94ro** [comment]
This is not an optimal solution, is just a trick. I will try to fix this.

**Comment by nWidart** [comment]
Considering how the module migrations work, it looks like a solution.

**Comment by andrei94ro** [comment]
Yes, but it can be different situations, and u need new order, etc.

**Comment by andrei94ro** [comment]
I think i will try to read all migrations, and after run them in order.

**Comment by wazirsoft** [comment]
> Ah yes indeed, I guess you can set the order of your modules to avoid the issue. If you put the blog module a higher order as the image module.

I have this same issue but I don't understand what solution are you proposing here?

**Comment by wazirsoft** [comment]
Oh ok, you mean order in `module.json`, that sounds good

**Comment by albertatnerdbrain** [comment]
Hello,
I think this is the right place to post my issue. We have a relational database and the tables use foreign keys. This is an issue, because one table has to exist before another table can be created. We try to make logical separated modules out of this monolith. but resolving in big trouble with migration (crosstables, referential integrity...). Is this a question of designing the database? Do we have to spread the contraints seperatly, Or is there another way to handle this constraints between modules? We hope you can help us, because the idea of your project is the right way to modularize our project.

**Comment by kenmasters** [comment]
encountering problems about having two migrations in a module, it seems that migrate-refresh does not drop tables
