### ISSUE TITLE
Reusing router configurations in modules

### ISSUE THREAD

**Issue by diegomagikal** [nWidart/laravel-modules#649]
Thanks for this amazing project!

In my main project api.php file, I have this: 
```
Route::group(['prefix'=>'v2', 'as'=>'api.', 'middleware'=>['auth:api', 'verified', 'creator']], function(){
```
How I can inherit the prefix and middlewares for the routes group of each module that I create?

**Comment by tiagosimoesdev** [comment]
I'm interested as well but for web.php . For now I'm adding manually in each route:group for each module but it would be great to inherit.

**Comment by nWidart** [comment]
You can use general php for this problem. Create a base route file, a base route controller, etc.
