### ISSUE TITLE
What is the function that controls the active element in the JSON?

### ISSUE THREAD

**Issue by Todyxe** [nWidart/laravel-modules#653]
Hello,

I search since one moment the function that controls the active element in the JSON (module.json) for my project. I went make in my controller of my laravel app a similar function than the function that controls the active element. I want find this function. I don't speak of the "setActive" function or "enabled or disable" function but the function which defined the active element.

The function that says that if active is equal to 1 then the module is activated otherwise it is disabled.

Thanks for reading,
excuse my english i'm a French.

**Comment by nWidart** [comment]
I don't understand what you want. The active module is just a method in the module class, or a field in the json file.

**Comment by Todyxe** [comment]
Hello,

Yes I know, but I'm looking for the function that manages the "active" element found in the module.json.

**Comment by nWidart** [comment]
Like I told you , the module class. https://github.com/nWidart/laravel-modules/blob/master/src/Module.php#L345

**Comment by Todyxe** [comment]
Thanks for your response,

But I'm looking for the function that says "if 'active' is equal to 1 then the module is activated otherwise it is disabled", I'm looking specifically for the function that allows to disable the module in the background without going through the "active" element ".

**Comment by nWidart** [comment]
SAme file, couple of lines higher.

**Comment by Todyxe** [comment]
I really apologize for the inconvenience but I do not see where it is in Module File...
