### ISSUE TITLE
Support for themes

### ISSUE THREAD

**Issue by kamov** [nWidart/laravel-modules#657]
There is support for themes?

something like: https://github.com/shipu/themevel

**Comment by nWidart** [comment]
You can already use themes however you like yes. AsgardCMS uses a theme package too with laravel modules.

**Comment by kamov** [comment]
Thanks. I can't find any reference about?

**Comment by nWidart** [comment]
What reference do you need? You only need the documentation of your prefered theme package.

**Comment by kamov** [comment]
I am not sure if I explain well myself.

I would like to have multiple themes, for example views/default/.. and a views/custom-theme/..

If custom-theme is enabled, then first is check in this folder, and default folder is used as fallback..

**Comment by nWidart** [comment]
I understand. And this is not related to this package. Please use the documentation of your preferred theme package.

**Comment by kamov** [comment]
Ok, I want just to know if this support.

However, my doubt is about that this theme package allow you to have one custom theme folder and default lavarel folder.

Using modules we have multiple views folder...

I will try to test

**Comment by kamov** [comment]
can you please point me to the right direction how to do this with your modules package?

**Comment by kamov** [comment]
I was able to make work multi themes. Seem work after quick check.

I just change the registerView like this:


```

public function registerViews()
    {
        $themePath = resource_path('views/custom/modules/pages');
        $viewPath = resource_path('views/modules/pages');
        $sourcePath = __DIR__.'/../Resources/views';

        $this->publishes([
            $sourcePath => $viewPath
        ],'views');

        $this->loadViewsFrom(array_merge([$themePath], array_map(
                function ($path) {
                    return $path . '/modules/pages';
                }, \Config::get('view.paths')), [$sourcePath]), 'pages');
    }

```


Now there is 3 locations of views:

- in Modules/Resources/views
- in resources/views
- in resources/views/THEME_NAME/

First load from resources/views/THEME_NAME/, then from resources/views and last from Modules/Resources/views


I am not sure if this is right way, but seem work.

**Comment by nWidart** [comment]
That looks good. I think I do something similar in asgardcms. 👍
