### ISSUE TITLE
Question about packages vs modules

### ISSUE THREAD

**Issue by kamov** [nWidart/laravel-modules#658]
I would like to know which are benefit using this modules instead of a packages that laravel already offer?

Thanks

**Comment by nWidart** [comment]
https://nicolaswidart.com/blog/writing-modular-applications-with-laravel-modules

**Comment by kamov** [comment]
This article explain why is good to have a module based architecture.

But I know the benefits.

My question is why not just use "packages" ?

I am using laravel packages right now, and I am not sure why switch to modules that this package offer.

Seem the same thing in the end.

**Comment by kamov** [comment]
@nWidart

**Comment by kamov** [comment]
@nWidart I play now with your modules last weeks, but I really don't see difference with package. I mean that I could archive the same with package. No? Which more features I get with modules that is not available with packages?

**Comment by laharshah** [comment]
I have the same question, what is the benefit of using modules over the standard packages - https://laravel.com/docs/6.x/packages ?

**Comment by nWidart** [comment]
If you don't see the benefit, packages are good for you.

**Comment by bernhardh** [comment]
I am a big fan of a modular architecture and currently playing around with laravel-modules.

But till now, the only benefit I see is great the command line tool for creating a module, compared to package creation by hand, but this could be also done for packages (for example https://github.com/Jeroen-G/laravel-packager). On the other hand, packages can be easier namespaced and placed in subdirectories or grouped in categories and are the "standard" of laravel supported by the team and most of the packages.

So @nWidart why do you prefere modules over packages or in which situations? Your Blogpost is, as @kamov said, just a good explanation why you should use modular structure at all, not why your package. 

Don't get me wrong, you don't have to "sell" your package to me (or us), but I just want to understand the benefit.

**Comment by nWidart** [comment]
Personally I like to develop outside the vendor folder. 😛
Having my code under a proper namespace, outside of app just makes sense to me.

**Comment by bernhardh** [comment]
Yes, you are right, but thats exactly what packages do as well. If you create your package you will place it at packages/YOUR_COMPANY_NAME/PACKAGE_NAME, which isn't the vendor folder. Thats btw exactly what for example laravel-packager does:

composer.json
```json
        "caravel/grid": {
            "type": "path",
            "url": "/path/to/project/packages/CompanyName/PackageName"
        }
```

You can even name the main folder "modules" if you prefer that. 

composer.json
```json
        "caravel/grid": {
            "type": "path",
            "url": "/path/to/project/modules/CompanyName/PackageName"
        }
```

So I still don't get it.

**Comment by nWidart** [comment]
The initial commit of larave-modules was [8th of feb 2014](https://github.com/pingpong-labs/modules/commit/6ab77fa91f1f3ee3d29ab0a340ea85210f3cf5f8)

your package is [10th of june 2015](https://github.com/Jeroen-G/laravel-packager/commit/c236db17cc546fe9c8ccf39863fa917171e531c5).

So maybe you should ask these questions there?

**Comment by Parables** [comment]
I think [Uncle Bob answers why you need to use Laravel Modules](https://www.youtube.com/watch?v=asLUTiJJqdE).

I usually create full-stack applications with Laravel where I have USSD, Web, and API features 

Until I saw this package, all of them were clustered in the default Laravel folder structure and there was no way you could tell the architecture of the project by just looking at the top directories.... you would have to first have to dig into the routes, only to find I have a `ussd` route, then follow the controller's method to see its implementation. You literally have to do lots of digging until you can fully understand what the project is for and what it can do.

Now with this package: my structure looks clean:
Modules
 |_USSD
 |_API
 |  |_V1
 |  |_V2
 |_Web  


The https://laravel.com/docs/9.x/packages is more about creating reusable packages for others to install and use, while the package basically helps you to architect a clean code structure.
