### ISSUE TITLE
Cache option has no effect

### ISSUE THREAD

**Issue by freescout-helpdesk** [nWidart/laravel-modules#659]
Even if `cache.enabled` is set to `true` in [Module.php](https://github.com/nWidart/laravel-modules/blob/master/src/Module.php) (line 214) module's json file is read:
```
return $this->moduleJson[$file] = new Json($this->getPath() . '/' . $file, $this->app['files']);
```

If you have 10 modules, it reads 10 manifest files every page load.

**Comment by nWidart** [comment]
It depends how you configured your cache in laravel.

**Comment by freescout-helpdesk** [comment]
1) Enable cache:
```
    'cache' => [
        'enabled' => true,
        'key' => 'laravel-modules',
        'lifetime' => 60,
    ],
```
2) Reload the page (now all `module.json` files must be cached)
3) Remove some `module.json`
4) Reload the page.

App will throw exception `module.json` not found.

**Comment by nWidart** [comment]
It still depends how you configured your cache in *laravel*.

**Comment by freescout-helpdesk** [comment]
OK :)
Can you give a hint: how `Nwidart\Modules\Module` is being converted into array containing it's `module.json` data in [FileRepository.php](https://github.com/nWidart/laravel-modules/blob/d5fec20c08e4ef339c1079d547b525d42ebe95ba/src/FileRepository.php)
```
        return $this->app['cache']->remember($this->config('cache.key'), $this->config('cache.lifetime'), function () {
            return $this->toCollection()->toArray();
        });
```

**Comment by nWidart** [comment]
You can see it calls toArray. Not sure why you want me to explain how code works. You can debug it yourself in that case.

**Comment by freescout-helpdesk** [comment]
Problem is in `getAttributes()` in [Json.php](https://github.com/nWidart/laravel-modules/blob/master/src/Json.php): on line 122 it reads the file:
```
$attributes = json_decode($this->getContents(), 1);
```
And after the file has been read, it checks the cache on line 133:
```
return app('cache')->remember($this->getPath(), config('modules.cache.lifetime'), function () use ($attributes) {
    return $attributes;
});
```
So it does not matter how you configure the cache, it is never used.

**Comment by nWidart** [comment]
https://github.com/nWidart/laravel-modules/blob/master/src/FileRepository.php#L146

Use a profiler to see that it is used.

**Comment by freescout-helpdesk** [comment]
Yes. Cache is used, but before using the cache it READS the file.
Normally we first check cache and if there is nothing found we read the file.

**Comment by nWidart** [comment]
I don't think that's the case. Please use a profiler.

**Comment by MarianoCuenca** [comment]
The minimum time it takes to load a page is +8 seconds without counting the login page, but for example my login page loads in 6 seconds but if i change the status of all the modules to false in my modules_statuses.json file, i do a cache:clear and reload the same page, the time is reduced to 400 milliseconds.
