### ISSUE TITLE
Laravel 5.3 Notification

### ISSUE THREAD

**Issue by webreinvent** [nWidart/laravel-modules#66]
How to create notification like https://laravel.com/docs/5.3/notifications  in your modules?

**Comment by nWidart** [comment]
Just like the documentation explains.

There is also a scaffold command to help, as per the docs:

```
php artisan module:make-notification InvoicePaid
```

**Comment by webreinvent** [comment]
tried ```php artisan module:make-notification UserCreated core``` ```Core``` is my module name, it shows the following error:
```
 [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "module:make-notification" is not defined.
```

**Comment by nWidart** [comment]
Not sure this is tagged, so use dev-master.

**Comment by webreinvent** [comment]
did you mean dev-master branch? sorry i did not get it

**Comment by webreinvent** [comment]
in ```composer.json``` changed to ```"nwidart/laravel-modules": "dev-master"```, will let you know if worked

**Comment by webreinvent** [comment]
it worked 👍
