### ISSUE TITLE
TypeError: modules[moduleId] is undefined

### ISSUE THREAD

**Issue by kamov** [nWidart/laravel-modules#660]
I am getting tihs error after run "npm run dev" on root of my project.

The modules installed at the moment don't have any JS or SCSS, all is still in root under resources/

I change the webpack.mix.js of root in this way (as suggested in docs):

```js
const mix = require('laravel-mix');

/* ADDED custom for laravel-modules */
require('laravel-mix-merge-manifest');
mix.mergeManifest();

/// Autoload globally jquery
mix.autoload({
    'jquery': ['$', 'window.jQuery', 'jQuery'],
    //'tether': ['window.Tether', 'Tether'],
});


/// Application
mix.js('resources/js/main.js', 'public/js')
    .extract(['jquery', 'popper.js', 'bootstrap', 'select2']);


/// Main app.css
mix.sass('resources/sass/app.scss', 'public/css/app.css');

``` 

I am not sure what I missed, but I was not sure what you mean here:

"Mix is a configuration layer on top of Webpack, so to run your Mix tasks you only need to execute one of the NPM scripts that is included with the **default laravel-modules package.json file**"

Thanks

**Comment by kamov** [comment]
I was able to solve this

**Comment by nWidart** [comment]
Can we know how?

**Comment by kamov** [comment]
For some reason the manifest.js file it's added under another folder, /js/pages and not under /js/vendor

I am not sure why, but loading manifest.js from /js/pages and not from /js/vendor worked fine.

So this error was generated when manifest.js was wrong.

In my code I load vendor to /js/vendor and then I load some specific js for pages like:

mix.js('resources/js/pages/admin-dashboard.js', 'public/js/pages/admin-dashboard.js')

Seem that mix create manifest.js on the last used folder or something like that.

**Comment by elliottregan** [comment]
@kamov @nWidart and anyone else here trying to fix this, I was able to solve it by using Webapck "magic comments" to set a chunk name. Looks like this, now:
```js
import(/* webpackChunkName: "moduleName" */'./path/to/module.js')
```
`moduleName` could be anything you want. I always choose the filename of the module.
