### ISSUE TITLE
Ending up with wrong namespace for controller action

### ISSUE THREAD

**Issue by cryogenfx** [nWidart/laravel-modules#663]
Ok, I may have done something horribly wrong here, but I've been scouring my code for hours and hours, and I can't for the life of me find out what I've done wrong.
Setup is as follows:
I have a Projects module, and in my ProjectsController i hit the update action, which looks like the following:

```php
namespace Modules\Projects\Http\Controllers;
...snip, snip...
    public function update(UpdateProject $form, Project $project)
    {
        $project = $form->persist();

        Toastr::info('Prosjekt er oppdatert.', $project->project_number);

        return redirect()->action('ProjectsController@index');
    }
```

the persist method takes care of updating the project, and returns it.
However, when I hit that method, it squawks with the following:
```php
InvalidArgumentException
Action Modules\Users\Http\Controllers\ProjectsController@index not defined.
```

So now it suddenly has the namespace of one of my other modules, Users
And I can't figure out why?
I can bypass it by using the fully qualified namespace with a starting backslash, but it's a hassle, and looks dirty. and it worked with using it like that before i started rewriting it to use laravel modules, and the Users namespace is just boggling...

Any ideas what is causing this? I can provide more code if needed, just not sure what, as I have no idea where this happens...

**Comment by nWidart** [comment]
Hm strange, what does your route definition look like?

**Comment by mikemand** [comment]
Not just the route definition, but your route service provider too? What namespace is it using for your routes?

Depending on which version of Laravel you're using, you can use the `::class` notation to bypass the route's default namespace:

```php
return redirect()->action([\Modules\Projects\Http\Controllers\ProjectsController::class, 'index']);
```

**Comment by cryogenfx** [comment]
My routes from Projects module:
```php
Route::group(['middleware' => 'auth'], function () {
    Route::resource('projects',                             'ProjectsController', ['except' => 'destroy']);
});
```

My Route service provider from Projects Module is untouched from artisan command:
```php
    protected function mapWebRoutes()
    {
        Route::middleware('web')
            ->namespace($this->namespace)
            ->group(__DIR__ . '/../Routes/web.php');
    }
```

**Comment by cryogenfx** [comment]
@mikemand Yeah, this is what I'm currently doing, but it just looks so bulky.
And I'm using PHP 7.2.10 with Laravel 5.7

**Comment by mikemand** [comment]
@cryogenfx Do you have a `User` module? Does it have a `ProjectController`, too? Your service provider looks fine, and the routes should be fine. You could double check with an Artisan command:

`php artisan route:list`

If nothing else works, you could try named routes. See if the command above indicates route names and try that with your redirect:

`redirect()->route('projects.index'); // or whatever name it looks like its using`

**Comment by cryogenfx** [comment]
Yes, I do have a Users module, but a UsersController. and this happens on every one of my 15 modules, it just gets a totally diffrerent namespaced controller, so it never finds the actual controller...

and yes, named routes work, using fqn also works. it's just that i had to rewrite 40+ controllers, importing fully qualified namespaces for 3+ actions on each controller, but it's done now, but i still don't understand why it happens, and just thought I would report it. but if no one else has this issue, feel free to close the issue.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by aespinoza** [comment]
@cryogenfx did you solve your issue?
