### ISSUE TITLE
Extra service provider in module

### ISSUE THREAD

**Issue by freescout-helpdesk** [nWidart/laravel-modules#664]
Hi,

Is it possible to add an extra service provider in the module?

I've tried to use `providers()` function in my module's service provider, but it seems to be never called:

```
    public function provides()
    {
        echo 123;
        exit();
        return [];
    }
```

**Comment by nWidart** [comment]
Hi,

Yes, you can add as many service providers as you wish in a module.
After adding the provider you need to tell laravel about it. One way to do this is by adding it to the providers key in the `module.json` file.

**Comment by freescout-helpdesk** [comment]
It works. Thanks.
