### ISSUE TITLE
Module Reusability

### ISSUE THREAD

**Issue by dave-miller** [nWidart/laravel-modules#665]
What is the best approach for having modules talk to other modules?  Looking for your advice to help get started.

**Comment by twf-nikhila** [comment]
@dave-miller 

As far as I think, there can be a few possible ways to do it:

1. Using Laravel Events.
2. Defining a custom function/helper with arguments like the name of module, Controller & function name, arguments to be passed to the module function. That way you can call functions from one module to another.

As of now, I'm using both of the above ways depending on the usage requirements.

Hope that make sense.

**Comment by nWidart** [comment]
Indeed, I also suggest the event point.

**Comment by dave-miller** [comment]
I was able to solve this issue and wanted to post it here for you to provide to all.

If your module service provider, bind a class/service to the container.
```
public function register()
{
    $this->app->register(RouteServiceProvider::class);
    $this->app->singleton('myservice', function ($app) {
        return new MyService;
    });
}
```

Then access it using
```
public function test()
{
    app('myservice')->myMethod();
}
```
