### ISSUE TITLE
change artisan commands signature

### ISSUE THREAD

**Issue by mohammedmanssour** [nWidart/laravel-modules#668]
Hi

I'm a big fan of this Laravel package and I use it in almost all of my clients project, but I'm not in favor of the current artisan commands signature `module:make-something` specially that Laravel has a different signature for its commands `make:something`.

so what do you think about chaning artisan signature? from `module:make-someting` to `make:module:someting`, this way - I think - it would be more comfortable and intuitive to use.

if you don't want to make a breaking change, we can build command aliases for the original commands

`make:module:something` is an alias for `module:make-someting`.

if you agree with this suggestion, then I'd more than happy to make a PR.

Thanks

**Comment by nWidart** [comment]
Hi,

I'm not sure what this would accomplish.
The current command naming pattern was not intended to look like the ones in laravel, and I don't see a proper reason to so.
