### ISSUE TITLE
Override packages configs

### ISSUE THREAD

**Issue by freescout-helpdesk** [nWidart/laravel-modules#669]
I've included a package via composer.json:
```
    "require": {
        "adldap2/adldap2-laravel": "v4.0.10"
    },
```
and copied it's configs info module's `/Config` folder. But those configs are never loaded. Is it possible to load configs for other packages from module's `/Config` folder?

**Comment by mohammedmanssour** [comment]
You need to load config from Module's Service Provider
```
$this->mergeConfigFrom(module_path(`ModuleName`).'/Config/config_file.php')
```

**Comment by freescout-helpdesk** [comment]
Thanks
