### ISSUE TITLE
Module getAssetPath Error

### ISSUE THREAD

**Issue by webreinvent** [nWidart/laravel-modules#67]
```{{Module::getAssetPath('core')}}``` generating following error:

```
FatalErrorException in Facade.php line 237:
Call to undefined method Nwidart\Modules\Repository::getAssetPath()
```

**Comment by lchoate** [comment]
I'm not sure if this was an error in documentation or method name, but 
`Module::assetPath('core')` would work for you. My code uses assetPath from the old module docs.

**Comment by webreinvent** [comment]
https://github.com/nWidart/laravel-modules  find ```Module::getAssetsPath();```

**Comment by nWidart** [comment]
@webreinvent did you try with the method provided by @lchoate ?

**Comment by nWidart** [comment]
You have 2 methods:

```
Module::getAssetsPath()

// or

Module::assetPath($moduleName)

```

Here is the strucure:

``` php
/**
 * Get module assets path.
 *
 * @return string
 */
public function getAssetsPath()
{
    return $this->config('paths.assets');
}
/**
 * Get asset path for a specific module.
 *
 * @param $module
 *
 * @return string
 */
public function assetPath($module)
{
    return $this->config('paths.assets') . '/' . $module;
}
```

**Comment by robertnicjoo** [comment]
> 

This methods doesn't exist!
