### ISSUE TITLE
Using route error in lumen 5.7

### ISSUE THREAD

**Issue by sniperwzq** [nWidart/laravel-modules#671]
Hi @nWidart,
I use your project in lumen,when i make new module, lumen throw :Class 'Illuminate\Foundation\Support\Providers\RouteServiceProvider' not found,i say your project,RouteServiceProvider use laravel route,but lumen do not support it, so how can i use it in lumen?
My English is not good.Sorry.
I hope you can help me solve it.
Thank you.

**Comment by nWidart** [comment]
Hello,

Lumen support is currently limited, it's quite possible it's not functional anymore.

Did you check the page about usage in Lumen : https://nwidart.com/laravel-modules/v4/lumen ?

**Comment by sniperwzq** [comment]
yes, i check the page about usage in Lumen : https://nwidart.com/laravel-modules/v4/lumen, i see your project ,you use RouteServiceProvider,but lumen do not support it.Do you plan to support lumen? or Which version supports lumen?
I'm looking forward to your support for Lumen.

**Comment by nWidart** [comment]
I don't use Lumen myself, so I cannot support it. Lumen support was added via a contribution. 
Since then lumen has has issues like possibly the one you're facing now.

I'm considering removing lumen support entirely, unless someone shows up who can fix and support it.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
