### ISSUE TITLE
Use module without enabling it in Module.json

### ISSUE THREAD

**Issue by ajsheldon93** [nWidart/laravel-modules#672]
I have an application with many different modules. I want to be able to have someone access only specific modules, but other users have access to different ones. I know I can enable/disable as needed, but that makes the change in the module.json file. I want to be able to default all modules to disabled and enable specific modules based on a User's authorization for just that page load. 

Is there some kind of `$module->use()` or `$module->tempEnable()` that exists or can be added? I want to be able to enable a list of modules tied to a specific user.

Thanks!

**Comment by nWidart** [comment]
Hello,

Indeed I agree you shouldn't use the module enable/disable to do this.
I would suggest using roles and permissions to disallow users from using certain features.

**Comment by nWidart** [comment]
There's currently no way to do this.

I would avoid having modules with the same route.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
