### ISSUE TITLE
Where to add spa routes?

### ISSUE THREAD

**Issue by hkmsadek** [nWidart/laravel-modules#673]
I am trying to add a spa route in web.php (not in any modules)

```

// spa routes...
Route::any('{slug}', function(){
    return view('welcome');
})->where('slug', '([A-z\d-\/_.]+)?');

```

Normally this works for normal set up and this code has to be `AT THE END OF THE WEB.PHP ` file. 
I have few more routes in a `User` module. This spa runs if i call the `user/login` routes. This `spa` route should run if any route matches are not found.

How to do this? Thanks

**Comment by nWidart** [comment]
You can look at the page module which has this kind of route too.
The key is the order of the modules.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
