### ISSUE TITLE
migrate:refresh --seed

### ISSUE THREAD

**Issue by robov** [nWidart/laravel-modules#676]
Thanks for your awesome package.
To create my database I run 

`php artisan migrate:refresh --seed`

This works nice, creates the databases of the modules too... however it does not call the module seeder class, 
I can do

`php artisan module:seed `

But I would like just 1 command to run all the creation and database seeding. Is this possible ?
or am I doing something wrong ?

**Comment by nWidart** [comment]
Hi,

You can quite easily create a wrapper command yourself for those 2 commands. A laravel command can call other laravel commands.

So you could have one, that calls these 2 commands.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
