### ISSUE TITLE
Controller extending wrong class?

### ISSUE THREAD

**Issue by 13dev** [nWidart/laravel-modules#678]
https://github.com/nWidart/laravel-modules/blob/9323980e0c9bbeec5a0ea5ab5a2c3c769d2ce44d/src/Commands/stubs/controller.stub#L7

should not be `Nwidart\Modules\Routing\Controller` ? because Routing Controller dosen't have common traits

**Comment by nWidart** [comment]
You can change it yourself or use the one from the app folder, or create your own. 

I'd say not all controllers need this, thus it's not done by default.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
