### ISSUE TITLE
Config not published

### ISSUE THREAD

**Issue by robov** [nWidart/laravel-modules#679]
when I execute
`php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"`

Then I see no additional config files in my system. Am I doing something wrong ?

**Comment by nWidart** [comment]
Hello,

Hm no that looks like the correct command. It's strange that's it's not publishing. 
Which version are you using?

**Comment by robov** [comment]
Both the latest...

**Comment by nWidart** [comment]
I just installed a clean laravel install, required the package, and the config file was published. These were the steps:

- composer create-project laravel/laravel modules-test-config
- composer require nwidart/laravel-modules
- php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"

```
╰─ php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"
Copied File [/vendor/nwidart/laravel-modules/config/config.php] To [/config/modules.php]
Publishing complete.
```

So I assume you made a typo, or installation issue somewhere.

**Comment by robov** [comment]
Thanks... at least I am sure it is on my side... thanks for an awesome package

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
