### ISSUE TITLE
add aliases in modules.json

### ISSUE THREAD

**Issue by klaravel** [nWidart/laravel-modules#68]
How can I add aliases in module.json?

**Comment by klaravel** [comment]
How can I add aliases in module.json?

```json
{
    "name": "Core",
    "alias": "core",
    "description": "",
    "keywords": [],
    "active": 1,
    "order": 0,
    "providers": [
        "Modules\\Core\\Providers\\CoreServiceProvider"
    ],
    "aliases":[
        {"Menu": "Modules\\Code\\Facades\\Menu"}
    ],
    "files": [
        "start.php"
    ]
}
```

I have added like this one but it's not working.

```json
 "aliases":[
        {"Menu": "Modules\\Code\\Facades\\Menu"}
    ],
```

**Comment by mikemand** [comment]
Check your spelling.

`Modules\\Code\\Facades\\Menu` should probably be `Modules\\Core\\Facades\\Menu` unless you have a `Code` module that has a Menu facade.

**Comment by klaravel** [comment]
Opps. That's only on here on comment but still could not find "Menu".
