### ISSUE TITLE
Have plugins per module

### ISSUE THREAD

**Issue by erotundo** [nWidart/laravel-modules#680]
Hi!

I'm new using the module package in Laravel and i have a question 

It's possible have a composer require package per module and when runs the command composer update do the installation of this packages requirement?

Regards

**Comment by nWidart** [comment]
Hello,

Yes, if you use [composer-merge-plugin](https://github.com/wikimedia/composer-merge-plugin).

**Comment by erotundo** [comment]
Hi Mr. @nWidart 

Thanks for your answer i go to test that :)
