### ISSUE TITLE
How to call module in vendor ?

### ISSUE THREAD

**Issue by sdenni** [nWidart/laravel-modules#681]
I have publish my module from 'myprojectmodule' in packagist.
I have created new fresh laravel project

And execute

`composer require myprojectmodule/mymodule`

mymodule was saved inside vendor folder
and I change composer.json from my fresh laravel,

```
       "psr-4": {
            "App\\": "app/",
            "Modules\\": "vendor/myprojectmodule/"
        },
```

but when I call

`php artisan module:migrate mymodule`

it return

` Module [mymodule] does not exist!`

is there a better way to call module from another fresh project.
or how do I solve this problem
thanks

**Comment by nWidart** [comment]
Hi,

You also need to enable a feature that will allow the package to scan the vendor folder:
https://github.com/nWidart/laravel-modules/blob/master/config/config.php#L135

**Comment by sdenni** [comment]
> 
> 
> Hi,
> 
> You also need to enable a feature that will allow the package to scan the vendor folder:
> https://github.com/nWidart/laravel-modules/blob/master/config/config.php#L135

great, thx
