### ISSUE TITLE
Problem with model and auth

### ISSUE THREAD

**Issue by rubenrios3dids** [nWidart/laravel-modules#682]
Hello, im have a bit problem with the models and modules.

I have a model User with more functions than User model original.

When i use Auth()->User for get user model, i retrieve the user model global of laravel, i cant call functions of the User model of the module.

Now i use this: \Modules\Chat\User::where('id', Auth()->User()->id)->first() to get the user, but this generate a extra sql query.

you know other form to realize this?

**Comment by nWidart** [comment]
Hi, I don't think this is related to this package.
The laravel docs explain how to eager load, to avoid additional queries.

**Comment by rubenrios3dids** [comment]
Hi, but when i use Auth::user() this already fetch the user with user model original.

I will like use user from module in auth::user(), i know about eager load, but i cant use that with auth::user for load another user from same table.

If not, I will forget this problem xD

a regards and thx!

**Comment by flavius-constantin** [comment]
> Now i use this: \Modules\Chat\User::where('id', Auth()->User()->id)->first() to get the user, but this generate a extra sql query.

Why you don't try to solve it like this?
`\Modules\Chat\User::with('relation')->where('id', auth()->user()->id)->first()`

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by jamesratcliffe** [comment]
If anyone has the same question in the future, you can also change the model use by Laravel's authentication in the config. The key is `auth.providers.users.model`.

This was Laravel will use your module's model directly, so you don't need `\App\User` at all.

Example for OP's situation:
```php
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => Modules\Chat\User::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],
```
