### ISSUE TITLE
How to get current module name in a middleware?

### ISSUE THREAD

**Issue by amirhosseindz** [nWidart/laravel-modules#685]
Hi,
in a middleware(in app not in a module) is there anyway to get current module name according to the current route?

**Comment by nWidart** [comment]
Hello,

Probably not, as there is no such thing as "current module". If you have something custom, ie one route per module, you can make the appropriate logic to determine this.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
