### ISSUE TITLE
How to run migrate:fresh

### ISSUE THREAD

**Issue by bhattraideb** [nWidart/laravel-modules#686]
I am getting Error "Command "module:migrate-fresh" is not defined." while running php artisan module:migrate-fresh Admin 
Is there is any other command for this?

**Comment by bhattraideb** [comment]
I tried this but getting this error: "  There are no commands defined in the "module:migrate" namespace.  
Did you mean this?  module"
I guess the fresh option is not there. It is not there on the command list.

**Comment by rubenrios3dids** [comment]
What is your laravel version?

**Comment by bhattraideb** [comment]
Laravel 5.7

**Comment by krubenrc** [comment]
I use Laravel 5.7 too, i only use two commands, the first generate migrations from laraval base and modules, the second use seeders from every module.

php artisan migrate:fresh --seed
php artisan module:seed


Try this :)

**Comment by nWidart** [comment]
The command `module:migrate-fresh` does not exist indeed.
There is however a `module:migrate-refresh` command which re-migrates the database, and optionally seeds it.

**Comment by bhattraideb** [comment]
I was creating migrations inside the module itself like for example inside the Admin module there are some migrations and inside Company some migrations. 
I think this is the wrong approach to do since there will be a relation between the models, so as per my understanding make migration on default migration dir only.

**Comment by KhuloodBatis** [comment]
> module:migrate-refresh

not working also
