### ISSUE TITLE
Multiple gates to access different modules

### ISSUE THREAD

**Issue by byanju** [nWidart/laravel-modules#687]
I am trying to integrate two different applications - build for accounts and inventory in two different modules using laravel-modules. I have another different module for authentication which is a common module for both accounts and inventory. This authentication module uses role and permission based authentication system. There will be other common models that will be used by both accounts and inventory.

Plan : I am trying to use guards to control the access of accounts and inventory modules. E.g. For accounts, guard will be account_guard and for inventory, it will be inventory_guard. Guard for common modules like authentication and other common models will be accessible via both account_guard and inventory_guard. All these guards have a common provider i.e. User model from authentication module.

Questions:
1. I want to get some review before actually implementing this plan, are there any chances to encounter any problem with this idea in a long run?

2. Is there something already built in in laravel-modules to handle such type of authentication problem?

3. Is there any better way to solve this problem?

Thanks.

**Comment by nWidart** [comment]
Hello,

This looks pretty good to me. 
There's no built-in way in the package to perform this, which leaves more flexibility to the users using the package.

**Comment by nWidart** [comment]
I haven't used gates & policies myself, but it should be the same as documented.
