### ISSUE TITLE
   Command "module:make-policy" is not defined.

### ISSUE THREAD

**Issue by kathmandu1** [nWidart/laravel-modules#689]
when i creating policy , it throw this error 
  Command "module:make-policy" is not defined.
please help me

**Comment by nWidart** [comment]
Hi,

That means this command does not exist. There's currently no command to create policies in a module, you need to create that class manually.

**Comment by bosz** [comment]
I am having this same issue. @nWidart , reading from the documentation, [Artisan commands](https://nwidart.com/laravel-modules/v4/advanced-tools/artisan-commands), it shows that command is supported. Maybe its a mistake?  I think the documentation should be updated cos the command is shown there as one of the commands the package supports.

**Comment by bosz** [comment]
Made a PR on the doc to [Removed "module:make-policy" command from doc](https://github.com/nWidart/nwidart-docs/pull/20)

**Comment by nWidart** [comment]
Little update, I can see the command here: https://github.com/nWidart/laravel-modules/blob/master/src/Commands/PolicyMakeCommand.php
