### ISSUE TITLE
php artisan view:cache throws [InvalidArgumentException] directory does not exist

### ISSUE THREAD

**Issue by sachicortes** [nWidart/laravel-modules#692]
As seen in #642 there is an issue when trying to cache views declared inside module's resources directory with php artisan view:cache. This is because the loadViewsFrom method of the module's service provider will load a wrong path:

```
$this->loadViewsFrom(array_merge(array_map(function ($path) {
    return $path . '/modules/ModuleName';
 }, \Config::get('view.paths')), [$sourcePath]), 'ModuleName'); 
```

This can be avoided if this is done:

```
$this->loadViewsFrom(array_merge(\Config::get('view.paths'), [$sourcePath]), 'ModuleName');
```

laravel modules version: 4.0
laravel version: 5.6.39

**Comment by nWidart** [comment]
Hi,

This sounds like it could be a pull request 😄

**Comment by nrdmn** [comment]
This solution overwrites any views in the module's namespace with views with the same name from the main namespace. For example, if you have a view `layout.master` and a view `ModuleName::layout.master`, accessing the latter will give you `layout.master` instead.

Your solution from #642 seems to work correctly:
```php
$this->loadViewsFrom(array_merge(array_map(function ($path) {
    return __DIR__.'/../Resources/views';
}, \Config::get('view.paths')), [$sourcePath]), 'moduleName');
```

**Comment by nWidart** [comment]
Thanks for the heads up that's good to know 👍
