### ISSUE TITLE
How to use Gate in all the app from "Module"AuthProvider?

### ISSUE THREAD

**Issue by baka298** [nWidart/laravel-modules#694]
Hi
I write my gate in the register function of my moduleAuthprovider,
and now i want to use them but nothing happens.

thx for your help. sry for my english i'm french :smile:

**Comment by nWidart** [comment]
Hi,

You can use gates like an any laravel application.
I haven't used them myself so I can't help you on the specifics, however, it should be as any other app.

**Comment by baka298** [comment]
yes it work, the problem is the other package for adminlte he can get the news gate from the modules.

thx for your help.

**Comment by nWidart** [comment]
Sorry I can't help you more here. I haven't used the default laravel Gate system and I'm not familiar with your project structure.

**Comment by nWidart** [comment]
Stackoverflow might be able to help you more on this question.
