### ISSUE TITLE
Cath-all routes if there was no route

### ISSUE THREAD

**Issue by majidalavizadeh** [nWidart/laravel-modules#695]
I want to catch all routes if there was no predefined route in modules, so I wrote this code in `routes/web.php` :

```php
Route::any('{query}', 'MainController@index')->where('query', '.*');
```

But the `routes/web.php` load before modules routes so this line will run every time and my modules routes cannot work properly.

Is there any way to handle this problem?

**Comment by majidalavizadeh** [comment]
Oops, update,
when I use `Route::any` in `routes/web.php`, all modules routes will be discarded.

**Comment by nWidart** [comment]
You could create a module that contains this catch all route, and have the module order as last.

**Comment by majidalavizadeh** [comment]
@nWidart Thanks for your solution.
I had an application before with this method, my routes work without any problem with Laravel 5.4 and `"nwidart/laravel-modules": "^1.19"`. Are there any changes in modules routes concept?

**Comment by nWidart** [comment]
Hm I think before routes were being included the "php way", ie a routes.php file, and include.
Now, they use a `RouteServiceProvider` which is the new way that laravel does it.

This is all laravel infrastructure though so not really anything in this package.
