### ISSUE TITLE
Json module definition

### ISSUE THREAD

**Issue by spescina** [nWidart/laravel-modules#7]
Is there a specific reason for using json in module definition?

Why not plain php config files? Having to write service provider and alias in js is rather a pain...

**Comment by nWidart** [comment]
Because that's how it was handled in the legacy package. Json is also easily parsed.

You mean a pain because you need to use a double backslash instead of single,  `\\` ?

**Comment by spescina** [comment]
yes. I cannot copy/paste from laravel `app.php` config file and I cannot use `::class` syntax too

**Comment by nWidart** [comment]
Yup that's true, `::class` can't be used.

I don't see this changing in the near future as it's a main component of the package.
