### ISSUE TITLE
Database factories ??

### ISSUE THREAD

**Issue by klaravel** [nWidart/laravel-modules#70]
Is there any way we can use database factories on module?

I am looking for making some admin panel modules with database factories.

Thanks for making great package.

**Comment by nWidart** [comment]
Yes, as usual.

**Comment by klaravel** [comment]
@nWidart  I have tested lots different way but factories are not working.

Below is my factory file code.

```php
<?php

/**
 * Cms Pages
 */
$factory->define(Modules\Pages\Http\Page::class, function(Faker\Generator $faker){
    $title = $faker->realText(40, 1);
    $status = array('draft', 'publish');

    return [
        'title'     => $title,
        'slug'  => str_slug($title),
        'content'   => $faker->paragraphs(3, true),
        'status'    => $status[array_rand($status)],
    ];
});
```

File Path: `Modules\Pages\Database\factories\PagesFactory.php`

**Comment by KevinHivert** [comment]
Same problem here.

Based on @klaravel example, if you do somthing like this 

```php
factory('Modules\Pages\Http\Page')->make();
```

It just won't work, because the Factory class looks only at 1 folder (As far as I know, but I may be wrong),
and by default this folder is ``/database/factories``.

However, as this package is made to allow us to work with multiple modules, it's just not a good solution to have only one folder for all our factories.

I just worked something out to have access to multiple factories folders, __but I do not know if there is any better solution__, add this to the register method of your module service provider

```php
$this->app['pagesfactory'] = $this->app->share(function ($app) {
    $faker = $app->make(\Faker\Generator::class);

    return Factory::construct($faker, __DIR__.'/../Database/factories');
});
```

And add 'pagesfactory' to the array returned by the ``provides`` method.

Then you can do: 

```php
app('pagesfactory')->of('Modules\Pages\Http\Page')->make();
```

**Comment by klaravel** [comment]
@KevinHivert 

Thank you for solution.

I have register method and try to execute factories but got error.

http://screencast.com/t/KXhRf0G0FWPV

```
[Symfony\Component\Debug\Exception\FatalThrowableError]
Class 'Modules\Pages\Providers\Factory' not found
```

Can you please help for that one?

**Comment by KevinHivert** [comment]
@klaravel 

You must have forgot ``use Illuminate\Database\Eloquent\Factory;`` on top of your Provider ;)

**Comment by klaravel** [comment]
@KevinHivert 

Awesome. it's working. It was my silly mistake.

----

Also one more thing if you can help me.

How can I include my tests run with phpunit from my modules?

I know that I can pass arguments for path.

But I want include my all modules test cases.

I found one trick that I have to manually add folder in phpunit.xml file.

```
<testsuites>
        <testsuite name="Application Test Suite">
            <directory suffix="Test.php">./tests</directory>
            <directory suffix="Test.php">./Modules/Pages/Tests</directory>
        </testsuite>
    </testsuites>
```

**Comment by KevinHivert** [comment]
@klaravel 

I think something like this should work fine : 

```xml
<testsuite name="Modules Test Suite">
    <directory suffix="Test.php">./Modules/*/Tests</directory>
</testsuite>
```

And a little update on my first answer, this is better : 

```php
$this->app->singleton('pagesfactory', function ($app) {
    $faker = $app->make(\Faker\Generator::class);

    return Factory::construct($faker, __DIR__.'/../Database/factories');
});
```

You can also add this to your ``start.php`` file (or create a ``helpers.php`` or whatever is your choice) of your module, something similar to the ``factory()`` helper method declaration you can find in the ``Illuminate/Foundation/helpers.php`` file of the laravel framework. Allowing to use something like :  

```php
pagesFactory(Pages::class, 5)->make();
```

**Comment by klaravel** [comment]
@KevinHivert 

Awesome help for testing solution.
----

I have register below on service provider.
```php
$this->app->singleton('pagesFactory', function ($app) {
            $faker = $app->make(\Faker\Generator::class);

            return Factory::construct($faker, __DIR__.'/../Database/factories');
        });
```

When try to call `pagesFactory(Modules\Pages\Http\Page::class, 5)->create();`
It's generate error.
`PHP Fatal error:  Call to undefined function pagesFactory() in eval()'d code on line 1`

I have also try to put that code on start.php from modules file but still same error.

**Comment by bashet** [comment]
@KevinHivert any suggetion for 5.4 to use factories from modules? 
Because share method does not exist anymore! I have tried with singleton which claimed to be replacing share but it doesn't work either!

**Comment by vsilva472** [comment]
@bashet Look at https://github.com/laravel/framework/issues/11881#issuecomment-261688266 
Works on 5.4 too.
