### ISSUE TITLE
loadJsonTranslationsFrom

### ISSUE THREAD

**Issue by messi89** [nWidart/laravel-modules#701]
Hi guys;

In order to handle string base translation (json file) I would suggest to add loadJsonTranslationsFrom on ModuleServiceProvider

```php
public function registerTranslations()
    {
        $langPath = resource_path('lang/modules/core');

        if (is_dir($langPath)) {
            $this->loadTranslationsFrom($langPath, 'core');
        } else {
            $this->loadTranslationsFrom(__DIR__ .'/../Resources/lang', 'core');
            $this->loadJsonTranslationsFrom(__DIR__ .'/../Resources/lang'); //this line allow us to put json translation files on our module directory instead of default laravel lang folder
        }
    }
```

leave a comment If you have a better idea

**Comment by nWidart** [comment]
Hello,

I found this PR in relation: https://github.com/nWidart/laravel-modules/pull/412

This will add some performance overhead for a use-case not everyone takes advantage of. I believe this can be added on a case by cases basis in projects.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
