### ISSUE TITLE
Module Routes

### ISSUE THREAD

**Issue by orangethakkali** [nWidart/laravel-modules#702]
Hi,
I have defined routes as below,
```
Route::domain('admin.mysite.com')->group(function () {
    Route::get('/login',function(){
      return View('mymodule::auth/login');
    });

```
When I point to http://admin.mysite.com/login, the view that displays is the Laravel default login view and not the custom login view I created. Do I have to have unique route name though I use modules.

**Comment by nWidart** [comment]
Hi,

I'm not sure, it's been a while since I've used domain routes in laravel. 
You could try to put that route definition inside the usual laravel routes file to see if it behaves differently.

I would suggest to remove the login route from laravel though.
