### ISSUE TITLE
Caching,disable/enable is disabled

### ISSUE THREAD

**Issue by wilbur-oo** [nWidart/laravel-modules#705]
laravel version 5.7.21
php version 7.3.1
cache driver redis
![image](https://user-images.githubusercontent.com/7148309/51406284-a0987800-1b93-11e9-8065-cf90a12aac8e.png)
![image](https://user-images.githubusercontent.com/7148309/51406333-ce7dbc80-1b93-11e9-9877-c0b38aa29814.png)

**Comment by nWidart** [comment]
Thank you for reporting this, this has been fixed for the upcoming version 5. 👍
