### ISSUE TITLE
Do enable and  disable modules

### ISSUE THREAD

**Issue by masami6871** [nWidart/laravel-modules#706]
Hello,dear Mr Nicolas Widart 
I have a problem that i cant resolve it and i was hoping you could help me.
I work with your package.  
I created a module with name:Users  and i enabled that,this module contains of one Model with 

<name:User>.i can Fetch my users information's with this modules and <Model:User> with below code :

$users=User::find(1)->first();

But when i disable <Module:Users>,i can Fetch my users information's again! .but I do not want to 

have access to <Model:User> and <Module:Users> when this module is DISABLE . 

I do not understand the concept of this case(disable/enable).

Thank you for reading this issue.
Best wishes .

**Comment by nWidart** [comment]
Disabling module just means it wont appear in the module list. Composer is the one autoloading your module.

You can manually autoload each of your modules one by one, and remove one of those if you don't want it to be loaded.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
