### ISSUE TITLE
Disable and delete module

### ISSUE THREAD

**Issue by darvishiyan-mahdi** [nWidart/laravel-modules#707]
Hi i want to disable or delete some module i create ?
which command do you suggest to use?

**Comment by nWidart** [comment]
Hi,

Search these issues for disabling.
I don't believe there's a delete command, though it's easy for you to make one.

**Comment by darvishiyan-mahdi** [comment]
is the any command or way to safely delete a module?

**Comment by nWidart** [comment]
There isn't no.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
