### ISSUE TITLE
RouteServiceProvider on v4.0.0

### ISSUE THREAD

**Issue by sthaiya** [nWidart/laravel-modules#708]
I tried v4.0.0 of laravel-modules on laravel v5.7 and php 7.1.26.

I used the command **php artisan module:make Blog** to create a new module in my app. While everything runs perfectly, there is an error where all URL actions for routes existing on the main app fail as they the namespace has changed to \Modules\Blog\Http\Controllers. I have not modified  \Modules\Blog\Providers\RouteServiceProvider

**Comment by marcelogarbin** [comment]
Same problem here. 
When I try to use the API route file, ex.:
```
Route::get('/profile', function(){
   return redirect()->action('UsuarioController@show', ['id' => auth()->user()->id]);
})
```
It returns me the namespace of another controller, and ends up causing the error "Action not defined."
It appears that you are not setting the namespace correctly in the route that is called the action. (is overwriting the controller namespace).

@sthaiya any news?

**Comment by mimbar** [comment]
> Hi,
> 
> I'm not sure of the issue you're having. If you changed routes, you need to change the definition of the routes.

I Installed v4 to lumen. everythings are okay until i make new module. the error is like this:

> (1/1) FatalErrorException
> Class 'Illuminate\Foundation\Support\Providers\RouteServiceProvider' not found

and this is the file

> use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by MetaiR** [comment]
I have the same problem in v6
what did u do @mimbar

**Comment by philipretl** [comment]
@MetaiR do you find some solution ? i have the same problem.

**Comment by jackbaron** [comment]
@philipretl do you find solution for this?
