### ISSUE TITLE
Laravel mix in blade

### ISSUE THREAD

**Issue by erotundo** [nWidart/laravel-modules#710]
Hi!

It's me again, now i have a little trouble i to put a example to explain the situation

I have module **Modules\Example** and i use the laravel mix to generate and put the .js and .css into the public folder and all goes good, but get i use in the blade the command **{{ mix('js/app.js') }}** the route generated not resolve the position of the file and only shows <script src="/js/app.js" />

I don't know if i need more configuration 

Regards

ER

**Comment by KABBOUCHI** [comment]
replace `app.js` with lower case module name `example.js`

**Comment by erotundo** [comment]
Hi!

I tested but not works

**Comment by KABBOUCHI** [comment]
can u share webpack.mix.js content!? and public/laravel-mix.json

**Comment by wenslim** [comment]
I work it well, I will show you my steps.
For example your module name is 「**Blog**」， the first thing you should do is open terminal and cd your module, install dependency, It's install in your **modlue**, here is blog , please pay attention to it.
`> yarn install`
and then
`> npm run dev`
the blog.css and blog.js will generate in public.
include it in your default blade.

_Modules / Blog / Resources / views / layouts / master.blade.php_
`<link rel="stylesheet" href="{{ mix('css/blog.css') }}">`
`<script src="{{ mix('js/blog.js') }}"></script>`

finally goto https://your-domain/blog

**Comment by erotundo** [comment]
Hi!

Sorry for not reply quickly.

@wenslim thanks for the step, it's the same step in the nwidart guide to use Laravel Mix

But with this steps the resolution of the .js not work and get 404

Here it's webpack.mix.js

`const { mix } = require('laravel-mix');
require('laravel-mix-merge-manifest');

mix.setPublicPath('../../public').mergeManifest();

mix.js(__dirname + '/Resources/assets/js/app.js', 'js/shopcart.js')
    .sass( __dirname + '/Resources/assets/sass/app.scss', 'css/shopcart.css');

if (mix.inProduction()) {
    mix.version();
}`

and public\mix-manifest.json

`{
    "/js/app.js": "/js/app.js",
    "/css/app.css": "/css/app.css",
    "/js/example.js": "/js/example.js",
    "/css/example.css": "/css/example.css"
}
`
Regards

**Comment by erotundo** [comment]
Hi!

I put a example as a name of the module :)

So change example for other name I got the same result

Regards

**Comment by wenslim** [comment]
@erotundo 

Hi, My laravel version is 5.5, and I used laravel-module v4.

I have changed default config, and assets after mix work well.
I move the module into app, It's just my habit
config / modules.php
```
<?php
    'namespace' => 'App\Modules',
    ...
    'paths' => [
        'modules' => base_path('app/Modules'),
    ]
```
app / Modules / Blog / webpack.mix.js
```
// mix.setPublicPath('../../public').mergeManifest();
mix.setPublicPath('../../../public').mergeManifest();
```
and then
```
$ php artisan module:make Blog
```

the following things as same as doc. So I suggest you check your version. Of course you have to check this package in your module dir`require('laravel-mix-merge-manifest');`
`$ yarn add laravel-mix-merge-manifest`
Good luck! 😄

**Comment by erotundo** [comment]
Hi! @wenslim @KABBOUCHI 

I found the error, the detail it's i'm working with a subroute http://localhost/project so when the mix do a resolution of js the route returned it's "/js/example.js" and gave the 404 error, the right route it's "/project/js/example.js"

The laravel mix process not detected if you working in a subroute

Thanks for your answers and sorry for disturbing
