### ISSUE TITLE
Facade not found after update

### ISSUE THREAD

**Issue by ryssbowh** [nWidart/laravel-modules#712]
Hi,
I'm rather sure I'm missing something quite obvious here but can't figure it out after a few hours spent on this, seems it has to do with deferred providers but I'm not too sure :

I'm was using this amazing package v3.0, with [Asset](https://github.com/orchestral/asset) 3.6 everything was working okay until I realised it's laravel 5.7 I have installed, so I updated modules to 4.0 (and did the config update) and Asset to 3.7.
I now cannot access the Facade 'Asset' from within a boot method of my core module, error thrown is 'Class 'Asset' not found'.
The funny thing is I have another module that uses this facade in the exact same way and it works. The only difference it seems is that this module has a bigger order specified in the module.json (core is 0, all the others are 1).

core module.json :
```
{
    "name": "Core",
    "alias": "core",
    "description": "",
    "keywords": [],
    "active": 1,
    "order": 0,
    "providers": [
        "Orchestra\\Asset\\AssetServiceProvider",
        "Barryvdh\\Debugbar\\ServiceProvider",
        "Igaster\\LaravelTheme\\themeServiceProvider",
        "Modules\\Core\\Providers\\CoreServiceProvider"
    ],
    "aliases": {
        "Asset":"Orchestra\\Support\\Facades\\Asset",
        "Theme" : "Igaster\\LaravelTheme\\Facades\\Theme",
        "TextSnippet":"Modules\\Core\\Facades\\TextSnippet",
        "ContextualLinks":"Modules\\Core\\Facades\\ContextualLinks",
        "Notify":"Modules\\Core\\Facades\\Notify"
    },
    "files": [
        "start.php"
    ],
    "requires": []
}
```

I tried to clear caches, emptied the bootstrap/cache folder, changed the order of the providers in the module.json, set defer to false in the AssetServiceProvider but no luck so far.

This probably has to do with my lack of understanding of deferred providers, is there anything I do wrong here ?

Regards

**Comment by nWidart** [comment]
hm I'm not that familiar with deffered providers either. You could try to add that facade in the `config/app.php` to see.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by ryssbowh** [comment]
Hi,

Didn't have time to work on this recently but I've just tried your solution and it does work, thanks !
Now I'm not totally happy with this solution as it's kind of breaking the idea of having modules declaring their own dependencies, ideally I'd like not to touch app.php and have all my providers imported in my modules, so that if one day I need to update laravel core, I can just do it, if that make sense (?).
What do you reckon, would that be related to this package ? Is this something you can help with ?
Or should I ask Orchestra Asset developers for help ?

Happy to help in any way I can.

Thank you.
