### ISSUE TITLE
How Use Config key modules in my view

### ISSUE THREAD

**Issue by mnamazi** [nWidart/laravel-modules#715]
Hi,
how are you ?
i use nWidart/laravel-modules package, i need use myModulesName Config keys in view. plz help me.
my config path : Modules\Tickets\Config\config.php
and my config.php is:
```
<?php

return [
    'name' => 'Tickets',

    'status' => [
        '1' => 'باز',
        '2' => 'درحال بررسی',
        '3' => 'بسته شده'
    ],
    'color' => [
        '1' => 'label-danger',
        '2' => 'label-warning',
        '3' => 'label-success',
    ],
];
```

now, in my view, how use config keys ?

Thank you

**Comment by nWidart** [comment]
Just as in laravel you can use the `Config` facade. Your modules are namespaces, so : `Config::get('module::key')`

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
