### ISSUE TITLE
How create a new module without artisan (in cms like photo)

### ISSUE THREAD

**Issue by masami6871** [nWidart/laravel-modules#716]
Hi  Mr Widart.   
i  used your  package  and  i'm creating my cms  .  my cms is modular system. and i prepare a cms that developers  can  install plugin on that .  
for be easy to create  basic module I decided to design a page that developers can Give the name and  create a new module and download that as a zip file and develop that.  like below photo :  

![1](https://user-images.githubusercontent.com/29583593/52636644-7d3ac180-2ee2-11e9-95d8-9d3ce7fec5eb.png)

I tried so hard , i tired with your Generators class  but i dint have any result . 
can  you  help  me ? I would be grateful if you guided me through this.

**Comment by nWidart** [comment]
Sorry I won't make a cms in your place.

**Comment by masami6871** [comment]
No dear  .  i just want  to  know how create  module without artisan command.  
please  help me  sir .

**Comment by nWidart** [comment]
You can use the command for your UI too.

You can look at the code of that command to find that out.

**Comment by masami6871** [comment]
> You can use the command for your UI too.
> 
> You can look at the code of that command to find that out.

how ? please tel me  where is  that  commands  code  ? I tried so hard :(
