### ISSUE TITLE
Module genetator does not respect config path

### ISSUE THREAD

**Issue by michail1982** [nWidart/laravel-modules#717]
in modules config I changed path to configs to lowercase, and after generation i saw both config and Config folders (on screenshot) https://imgur.com/n9KGpiN

**Comment by nWidart** [comment]
Hello,

Sorry for the delayed response.
I just checked this out, and it seems to only do this with casing changes.
However, the path sent to the laravel Finder, receives the correct path with modules lowercase for instance.

So I assume this is OS related and not the laravel filesystem itself.
