### ISSUE TITLE
Is it possible to use in App already developed?

### ISSUE THREAD

**Issue by BechirAhmed** [nWidart/laravel-modules#718]
Is It possible to use the package with already developed app? if so, how?

**Comment by nWidart** [comment]
Hello,

Yes you can. Just require the package and start creating modules. 👍

**Comment by BechirAhmed** [comment]
But how about the old codes? How to module them? Did I've to delete them and recreate them as modules? Or what's the best way to do that

**Comment by nWidart** [comment]
You can do whatever you want with it. It will keep working in app if you leave it there.
If you want to extract it to modules, you can do that too.

**Comment by BechirAhmed** [comment]
That's super, thanks so much

**Comment by BechirAhmed** [comment]
Please if you have any idea of how to module the old codes without deleting them?

**Comment by nWidart** [comment]
Nope, that's up to you to decide how you want to proceed.

This article might help you: https://nicolaswidart.com/blog/writing-modular-applications-with-laravel-modules
