### ISSUE TITLE
when exculate php artisan module:list display nothing

### ISSUE THREAD

**Issue by js0exp** [nWidart/laravel-modules#719]

**Comment by js0exp** [comment]
i just git pull  in other mac book , and i get this, 
# php artisan module:list
+------+--------+-------+------+
| Name | Status | Order | Path |
+------+--------+-------+------+

**Comment by palashk92** [comment]
Check the module.json file in your modules. That particular file is used to pull out details of he modules

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
