### ISSUE TITLE
how can i modify blades that created by nwidart command(php artisan module:makke moduleName)

### ISSUE THREAD

**Issue by mithradatr13** [nWidart/laravel-modules#721]
hello my dear freinds in github

i use nwidart in old project that created by another developer when i create module by this artisan command:
php artisan module:make name
create a default module for me by default blades in resourses/views folder
i want edit blades for all modules who created by php artisan module:make but i cannot finde resourses of creating this blades (my project automatically add 3 blades create/edit/list) i read nwidart docs but i dont find answe please help me if you know

**Comment by nWidart** [comment]
You can edit all the files this command generates.
