### ISSUE TITLE
Support laravel 5.8

### ISSUE THREAD

**Issue by djoudi** [nWidart/laravel-modules#722]
Are supporting laravel 5.8?

**Comment by nWidart** [comment]
![image](https://user-images.githubusercontent.com/882397/53358475-c4886f80-3930-11e9-9a46-dd733adb657c.png)

**Comment by vahidv** [comment]
prbolem with deprecated fire method in events
using dispatch instead    
    protected function fireEvent($event)
    {
        $this->app['events']->dispatch(sprintf('modules.%s.' . $event, $this->getLowerName()), [$this]);
    }

**Comment by nWidart** [comment]
Ah that's good to know, thanks!

**Comment by nWidart** [comment]
Laravel 5.8 has been added, available as a prerelease now as `5.0-dev`.
