### ISSUE TITLE
how can i create API in this laravel module package?

### ISSUE THREAD

**Issue by sanketr43** [nWidart/laravel-modules#723]
hello, I have laravel modular project. How can create API in this?

**Comment by nWidart** [comment]
Hi,

It would be the same as any laravel application, nothing different.

**Comment by sanketr43** [comment]
okay. I will try it. Thanks @nWidart

**Comment by sotengboy** [comment]
Hello,
I tried to make api endpoints but not working, it's got 404 page. i have some modules like Product, Blogs, ect. and i tried make (product) api.php inside Modules/Products/Routes/api.php but got 404 page. What i mistakes? 
Thanks

**Comment by jesnababu** [comment]
how to creat api in fleetcart

**Comment by MetaiR** [comment]
> Hello,
> I tried to make api endpoints but not working, it's got 404 page. i have some modules like Product, Blogs, ect. and i tried make (product) api.php inside Modules/Products/Routes/api.php but got 404 page. What i mistakes?
> Thanks

same problem here

**Comment by kacemelyes** [comment]
try to use the controller's full path while creating the api
