### ISSUE TITLE
How to apply Middleware to a group of Module Route?

### ISSUE THREAD

**Issue by PhanPirang** [nWidart/laravel-modules#725]
I have these 3 module routes

// Finances routes file
Route::group(['middleware' => ['auth'], 'prefix' => 'admin/finances', 'namespace' => 'Modules\Finances\Http\Controllers'], function()
{
    Route::get('/', 'FinancesController@index');
});

// Jobs routes file
Route::group(['middleware' => ['auth'], 'prefix' => 'admin/jobs', 'namespace' => 'Modules\Jobs\Http\Controllers'], function()
{
    Route::get('/', 'JobsController@index');
});

The question is how can I apply auth middleware to these two routes at one place. So when I want to add or change middleware, I can change it once only.

**Comment by nWidart** [comment]
You can add the middleware to a "core" module, that contains logic common for multiple modules. Consumer modules would then use this middleware.

**Comment by PhanPirang** [comment]
I mean I want to apply middleware to these 2 modules or some routes of these two.

ex:
// This one is to apply to the whole route of these two modules
Route::group(['middleware' => ['custom-middleware'],function()
{
   Route::resource('/', 'FinancesController');
   Route::resource('/', 'JobsController');
});

// This one apply on only some routes of these two module
Route::group(['middleware' => ['custom-middleware'],function()
{
   Route::get('/', 'FinancesController@index');
   Route::get('/', 'JobsController@index');
});

How can i do it?

**Comment by nWidart** [comment]
Same answer as above. Please refer to the laravel documentation.
