### ISSUE TITLE
Is it possible to do nested modules?

### ISSUE THREAD

**Issue by benlonsdale** [nWidart/laravel-modules#729]
I can't see any documentation on this, but is there a way to install sub-modules inside a module?

**Comment by nWidart** [comment]
Hi,

Not using any of the modules commands no.
You could do it manually if you want to, but I wouldn't recommend having submodules in the first place.

**Comment by benlonsdale** [comment]
Okay, follow up question then. Are there any examples of including an external module installed through composer?

**Comment by nWidart** [comment]
Yeah, [AsgardCMS](https://github.com/AsgardCms/Platform) does this. Though that's a bit more special since it's using composer plugin (which installs the module in the Modules folder instead of vendor). But you should get the idea from that.

**Comment by benlonsdale** [comment]
Thanks for your help 👍
