### ISSUE TITLE
Error when rolling back migrations while testing app

### ISSUE THREAD

**Issue by msieprawski** [nWidart/laravel-modules#73]
Hey,

I've created simple test:
```
<?php
use Illuminate\Foundation\Testing\DatabaseMigrations;

class UserTest extends TestCase
{
    use DatabaseMigrations;

    public function testExample()
    {
        $this->assertTrue(true);
    }
}
```

When I run `phpunit` it ends with error:
`1) UserTest::testExample
ErrorException: Undefined index: 2016_10_10_143026_create_users_table`

This is my Users module migration so I think that Laravel can't find module migrations and tries to rollback non-existing migration. Any ideas?

**Comment by nWidart** [comment]
You need to register your migrations using the new laravel method to do so.

**Comment by msieprawski** [comment]
Is there any sample code for that? That could be very useful. And it should be added to the documentation as well.

**Comment by nWidart** [comment]
It's on the laravel documentation. No need for duplicate data.

```
$this->loadMigrationsFrom(__DIR__ . '/../Database/Migrations');
```

**Comment by msieprawski** [comment]
All right. Thanks.
