### ISSUE TITLE
How to access config values in routes.php?

### ISSUE THREAD

**Issue by simar88** [nWidart/laravel-modules#732]
Hi everyone,
i'm having trouble in accessing config values from routes.php all inside the modules folder.
Example route inside the module.
`Route::get(config("blog.slug.it"), function () {
                        return 'test';
                    });`
The  value of config("blog.slug.it") is always null...can you help me?
The value exists becuase it returns me the expected result if i use the route in the following way:
`Route::get(config("blog.slug.it"), function () {
                        return config("blog.slug.it");
                    });`
Thanks in advance,
Simone

**Comment by nWidart** [comment]
you need to prefix your config call with the namespace, by default the module name.

```
Config::get('moduleName::key')
```
