### ISSUE TITLE
5.8 support - but why drop php7.1?

### ISSUE THREAD

**Issue by huglester** [nWidart/laravel-modules#735]
Hello
why drop php71?
Laravel 5.8 runs on php71...

Thanks

**Comment by nWidart** [comment]
Hi,

Because of phpunit which is 7.2 and higher.

**Comment by huglester** [comment]
Cant phounit be lowered?

I mean it would be better to at least stick to laravel version

**Comment by nWidart** [comment]
It could, but I'd like to use up to date software, instead of outdated ones.

**Comment by huglester** [comment]
Maybe just make it accept phpunit both versions. So in newer php env it
will install new phpunit. Otherwise- older version?

**Comment by nWidart** [comment]
That's a good idea indeed. I've added phpunit 7 to the [composer contraint](https://github.com/nWidart/laravel-modules/commit/4cd29bf18d037c975d7afff83988e13963c680c9).

Can you let me know if this works for you on php 7.1?

**Comment by nWidart** [comment]
Any news @huglester ?

**Comment by huglester** [comment]
sorry did not post back. Will reply when be back home in the evening.
Thanks. I was doing some workaround while waiting for a reply :)

**Comment by raank** [comment]
But Laravel#5.8 requires php >= 7.1 [composer of laravel](https://github.com/laravel/laravel/blob/master/composer.json) and phpunit#7.5.8 requires php 7.1 also [composer of phpunit](https://github.com/sebastianbergmann/phpunit/blob/7.5.8/composer.json).

My server is PHP 7.1.27 version, having any solution?

**Comment by nWidart** [comment]
Yes, read this issue and let me know if it works.

**Comment by rebz** [comment]
This is not working still. Requires v7.2. We are using 7.1.28 with Laravel 5.8.

**Comment by nWidart** [comment]
You can always run `--ignore-platform-reqs` with composer.

**Comment by chiiya** [comment]
Seeing as you already lowered the PHPUnit requirement, how about changing the PHP requirement as well, since otherwise it won't have any meaningful effect?

```diff
"require": {
-    "php": ">=7.2"
+    "php": ">=7.1.3"
},
```

**Comment by MahdiMajidzadeh** [comment]
I need to php 7.1 ,too

**Comment by maciejfikus** [comment]
@nWidart - any chances here?

I work on huge system and we are using this package. However, we are not able to fully upgrade Laravel to 5.8 as your package requires php 7.2 while we are forced to use 7.1. Going with --ignore is not an option aswell. 
Is there any reason to stick to 7.2 while this version is ment to work with Laravel 5.8 (php 7.1)?

**Comment by mikemand** [comment]
PHP 7.1 is no longer receiving any kind of support: https://www.php.net/supported-versions.php

PHP 7.2 is also nearing the end of its lifecycle (10 months of security-only updates left), so you might as well upgrade to 7.3 ASAP.

Why are you "forced" to use 7.1? If it's not a server you control, and your server host refuses to upgrade (especially for security concerns), jump ship immediately and find a new host.

**Comment by maciejfikus** [comment]
@mikemand - version 5.0 of this package is also an old one. It was even made compatible with PHP 7.1, as you can see above. Only small change of composer.json is needed.

Sometimes, when you work on really big projects with corporations or banks you have to understand that there a procedures you have to follow. You usually can't switch version from day to day.

**Comment by mikemand** [comment]
This isn't day-to-day version switching though... PHP 7.1 hasn't had security-only support since December 1, 2019, and regular support ended over a year ago. I understand banks and corporations are slow lumbering beasts, but security concerns are becoming ever greater for old software.

Version 5 of this package is also no longer receiving support as far as I am aware. **If** there are no PHP 7.1 incompatible features, you could fork from the 5.0 branch and use [Composer's `vcs` feature](https://getcomposer.org/doc/05-repositories.md#vcs) load your fork. Make sure you change the PHP requirement in your fork, of course. You'll have to play around with versions in your software's `composer.json` to get the correct branch (probably `dev-5.0` as a version constraint, but I am not 100% sure).
