### ISSUE TITLE
How to call Modules::asset() func inside config files?

### ISSUE THREAD

**Issue by anburocky3** [nWidart/laravel-modules#738]
I'm using [SEO package](https://github.com/artesaos/seotools) . I need to setup an default image in the `config/seotools.php`. How to call the `Modules::asset()` func inside the config files?

Calling like:
`' 'images'      => \Module::asset('site:img/assets/banner.png')` not working, throwing 

> Class 'Module' not found

**Comment by nWidart** [comment]
That's because laravel didn't register facades at that point.

You can't do this in a config file. Instead do it in a service provider for instance.

**Comment by anburocky3** [comment]
Can you be elaborate on how to do that?

**Comment by nWidart** [comment]
You can set configuration values anywhere. like `config()->set()`

**Comment by anburocky3** [comment]
Thank you. i have moved the default image into laravel original layout and now its working..
Another doubt?
I created a model using the following command
`php artisan module:make-model Career Site` it created Career model inside `Entities` folder.
Now, how to call this model in my `Http/SiteController.php` ?
Doing traditional way, is not working like: `App\Career::first()` 
Also please update the documentation regarding it.

**Comment by nWidart** [comment]
You call php classes like always, this is still PHP.
