### ISSUE TITLE
Only Compact works, Data Passing not working 

### ISSUE THREAD

**Issue by anburocky3** [nWidart/laravel-modules#739]
I have the following controller.

**This doesn't works.**
`$careers = Career::first();`
`return view("site::pages/careers/careers", careers);`
(In Laravel, it working cool as expected. Not working on Laravel Modules)

**This works:**
`$careers = Career::first();`
`return view("site::pages/careers/careers", compact('careers'));`

**Comment by nWidart** [comment]
Hi,

This isn't related to the package. Please refer to the php/laravel docs.

**Comment by anburocky3** [comment]
I'm sorry that. It works on core laravel. Not working only on your package. 👎

**Comment by nWidart** [comment]
This package does not change how php works.

**Comment by nWidart** [comment]
I use compact all the times in modules: https://github.com/AsgardCms/Platform/blob/3.0/Modules/Page/Http/Controllers/Admin/PageController.php#L62
