### ISSUE TITLE
how to access module name inside stub?

### ISSUE THREAD

**Issue by moreiraandre** [nWidart/laravel-modules#740]
Hello, I would like to access the constant with the module name inside the migration stub so I can identify a custom module configuration, for example:
```php
Schema::create(config('$MODULE$.dbSchema').'$TABLE$', function (Blueprint $table) {
            $table->bigIncrements('id');
$FIELDS$
            $table->timestamps();
            $table->softDeletes();
        });
```
> In the `dbSchema` index I will save the prefix of the tables in the database.

**Comment by nWidart** [comment]
Hi,

I don't think you can. You can just try to use the `Module` class and find out, but I doubt it will be available.

**Comment by nWidart** [comment]
Oh my bad, inside a stub. In that case, you can refer to the generator commands to see what tokens are being replaced.

**Comment by moreiraandre** [comment]
Okay, thank you so much, friend.
