### ISSUE TITLE
[Feature Request] Add factory stub option to model generation

### ISSUE THREAD

**Issue by sykorax** [nWidart/laravel-modules#741]
Hey,

Laravel itself supports the factory generation for the model making command:

```
php artisam make:model <Model> --factory|-f
```

Could we have this feature for this package aswell? :)

**Comment by sykorax** [comment]
I was able to make a PR which can create a raw factory stub however i wanted to go deeper so i decided to refactor the factory generator to handle optional model option. In such a case the command would generate the FQN namespace of given model and insert into the right stub.

After a while running tests said that:

```
Error : Class 'Modules\Blog\Providers\BlogServiceProvider' not found
```

Not sure what causes this problem. I have not modified PSR-4 loaders in package.json or any other configuration stuff. After i restored the local history to the git head problem still persistend.

**Comment by sykorax** [comment]
(Sorry if i did not mention: Tests ran successfully several times)

**Comment by nWidart** [comment]
Hi,

This is usually when an error occurs and the clean up didn't run, this deletes the generated module.
You can find this module under `vendor/orchestra/testbench/testbench-core/laravel` if I'm not mistaken.

**Comment by sykorax** [comment]
Oh, okay. Will look at it.
Would be this PR welcomed by the way?

**Comment by nWidart** [comment]
Sorry for the late reply! Yes a PR for this would be nice 👌
