### ISSUE TITLE
Containerize Concept

### ISSUE THREAD

**Issue by developerbravo** [nWidart/laravel-modules#742]
Hi,
Your package is really helpful but I was wondering if you can add a feature that multiple modules will group in one folder?, like **containerize** concept.

**Example: permission, role, user** modules will be inside **System** folder/container.

Like what I have done below.

![image](https://user-images.githubusercontent.com/48985275/55067790-5368e300-50bb-11e9-9833-047bbd046327.png)

Based on my experience, it will really help building very large application like school erp system were doing. Dropping thousands of modules in one folder is very hard to know which modules belongs to Human Resource, Accounting, Registrar, Admission and so on.

Hope you consider this idea. :-)

**Comment by nWidart** [comment]
Hi,

This has been requested before, currently, it is not planned to have this feature.
In my opinion, such applications should not exist anymore. If an app really has 1000 modules, it means something can be split up into multiple applications.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
