### ISSUE TITLE
Create general module 

### ISSUE THREAD

**Issue by ahmedprog** [nWidart/laravel-modules#743]
How I can create  "core" module that contains logic common, to implement that common logic

**Comment by nWidart** [comment]
Hi, there's nothing special to it. Just create the module, and put common logic in it.

**Comment by ahmedprog** [comment]
if I need create middlewares  in this module , and other module will use those middlewares ?

**Comment by sykorax** [comment]
Yes, sure all other modules can use that middleware.
However always keep in mind that your modules will have dependency on that module which provides that middleware.
