### ISSUE TITLE
View cache problem

### ISSUE THREAD

**Issue by SkandaLonline** [nWidart/laravel-modules#746]
Hi;
I'm having the same problem that your friend @yassersharaf  lived with. I've tried the issue on multiple different servers, and I'm seeing this problem only in module files.

Reference #343 @nWidart

**Comment by nWidart** [comment]
Same answer as the other issue, this is related to your app's setup.

**Comment by SkandaLonline** [comment]
I noticed something like this.
Within the resources folder in Laravel, a folder named modules has been opened and the binder files of all modules have been cached here. Even if we do cache cleanup, we call the file from the controller file of the module, not from within the module when we call the blade file. Therefore, the changes are not reflected. How do I prevent this cache from occurring?
@nWidart  @yassersharaf

**Comment by nWidart** [comment]
I don't think the package does any view caching, so I would check with laravel's caching.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by collinsNick** [comment]
hi all just experienced the same view issue where when i modify a view the changes are not reflected, this started happening after i had used **php artisan vendor:publish** and the folder @SkandaLonline is talking about was created in the view folder a config file for each module was also created in the config folder. So forme deleteing these files and the module folder in the views folder solved the issue
