### ISSUE TITLE
[Feature Request] Add make-observer command

### ISSUE THREAD

**Issue by sykorax** [nWidart/laravel-modules#747]
Would be useful to have [this](https://laravel.com/docs/5.8/eloquent#observers) one in the package.

**Comment by nWidart** [comment]
Hello,

Why not indeed. I'd accept a PR on this feature with tests. 😄

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by ugurdnlr** [comment]
Hello,

Has this arrangement been added? Because I need this.

**Comment by 4n70w4** [comment]
+1

**Comment by 4n70w4** [comment]
https://github.com/nWidart/laravel-modules/pull/915
