### ISSUE TITLE
Class 'Modules\<module-name>\Providers\<module-name>ServiceProvider' not found

### ISSUE THREAD

**Issue by BHEADRICK** [nWidart/laravel-modules#75]
I ran the artisan command to create a module, and then when I attempted to create a second one - or really do anything, I get this error. 

I have added the provider and alias to the App/config/app.php and I even added the autoload stuff to composer.json, but the module's serviceprovicer still isn't resolving somehow.

I'm running Laravel 5.2 and php 7, fwiw

**Comment by nWidart** [comment]
Looks like you forgot to autoload your module. Do that using composer.

**Comment by BHEADRICK** [comment]
you mean this?

{
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Modules\\": "Modules/"
    }
  }
}

Did that already

**Comment by nWidart** [comment]
Indeed. Check with the autoloading. It's trying to load something it can't find. 

Check also if your module was generated correctly.

**Comment by suleodu** [comment]
i am having the same issue

**Comment by adelowo** [comment]
This does happen quite often, just run the `composer dump` command like @nWidart said

**Comment by suleodu** [comment]
Okay I did that and it works fine now thanks

**Comment by nWidart** [comment]
Awesome 😄
