### ISSUE TITLE
install in linux mint lampp

### ISSUE THREAD

**Issue by lucasmichel** [nWidart/laravel-modules#750]
I'm doing an install on a new project using Laravel 5.4. After the installation, I am running the command "sudo chmod 777 -R / opt / lampp / folderApplication" to give full permission to folder "folderApplication". When executing the command "composer require nwidart / laravel-modules" the system displays at a certain moment the msgm "Writing lock file
"and the artisan does not recognize the" make: module "command.What could cause this type of problem? I would like to emphasize that I used the same commands in the windows environment and it worked normally.

**Comment by nWidart** [comment]
Hi,

I don't fully remember, but it's possible that laravel 5.4 doesn't have the auto discovering of service providers. You might have to add the provider & facade yourself in config/app.php

**Comment by lucasmichel** [comment]
Hi, actually with version 5.8 of laravel worked correctly, thanks
