### ISSUE TITLE
Route to module index not fount

### ISSUE THREAD

**Issue by alagoroChapela** [nWidart/laravel-modules#751]
Route [importacion.index] not defined

I've created a new module with php artisan module:make importacion

In the nav.blade.php where I have the menu, I set:
```
@if(Module::has('Importacion'))
@if(Module::find('importacion')->active===1) 
      <li><a class="nav-link" href="{{ route('importacion.index') }}">Importación</a></li>
@endif
@endif
```

If I write propietarios.index, in works ----> importacion is enabled

If I go to url `http://xxx/importacion`---->it works, goes to index.blade under Importacion module.

Also went to config/modules.php and modified:
'scan' => [
        'enabled' => true,
        'paths' => [
            base_path('modules/*'),
        ],
    ],

To make a modules work do I have to modify any config file or execute a command?

**Comment by nWidart** [comment]
Hi,

Nothing needs to be done granted you followed the installation instructions.
Did you autoload your modules?

**Comment by alagoroChapela** [comment]
Hi,

Ah! I have another module, Realestate, that works, but I don't remember what I did to make it work. So the module package is correctly installed. 

I don't really know what you mean with autoloading **my** modules. composer dump-auto?

**Comment by nWidart** [comment]
If your other module works it's probably not this, but did you add this to your composer.json file:

```json
{
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Modules\\": "Modules/"
    }
  }
}
```

**Comment by alagoroChapela** [comment]
> If your other module works it's probably not this, but did you add this to your composer.json file:
> 
> ```json
> {
>   "autoload": {
>     "psr-4": {
>       "App\\": "app/",
>       "Modules\\": "Modules/"
>     }
>   }
> }
> ```

yes, it is added and looking around in the autoload_classmap.php

```
    'Modules\\Importacion\\Providers\\ImportacionServiceProvider' => $baseDir . '/Modules/Importacion/Providers/ImportacionServiceProvider.php',
    'Modules\\Importacion\\Providers\\RouteServiceProvider' => $baseDir . '/Modules/Importacion/Providers/RouteServiceProvider.php',

```
And files exist ...

**Comment by alagoroChapela** [comment]
I found 
`<li><a class="nav-link" href="/importacion">Importación</a></li>`
works. Is there a default module?

I try to look around asgardCMS, but there is no routes/web.php files in each module. Structure is different to nwidart/laravel-modules v4.0.

Anybody using modules with more than one module working?

**Comment by nWidart** [comment]
It's the same in asgardcms, expect that I customised it to use route service providers.
There's absolutely no reason for routes to work in one module and not the other. 

Without looking at your code there's no way for me to guess.
So if you can, upload a sample project where I can take a look at.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
