### ISSUE TITLE
Activé/désactivé un module

### ISSUE THREAD

**Issue by Morpheons** [nWidart/laravel-modules#754]
Bonjour, 
Je souhaite élaborer la liste de mes modules; je procède ainsi
ma methode 
` public function index()
    {
        $modules = Module::scan();
        /*dd($modules);*/
        return view('admin::module',compact('modules'));
    }
`
puis dans ma vue, j'utilise un datable
`
<table id="e2hdatatable" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Path</th>
                        <th>Actif</th>

                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($modules as $module)
                        <tr>
                            <td>{{$module->name}}</td>
                            <td>{{$module->path}}</td>
                            <td align="center">
                                <a href="" class="btn btn-danger ml-2 btn-sm delete"> <i class="fas fa-trash-alt"></i></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
`
1 / autant j'arrive à afficher le nom du module mais pas son chemin mais bon ce n'est pas grave. je peu m'en passer.
2/ Par contre j'aime rais à partir du tableau pouvoir activer/desactiver ce module.
je ne comprend pas ce que je dois faire pour y arriver. qui pourrait m'aider ?

Merci de votre aide.

**Comment by Morpheons** [comment]
Soory nicolas,
i try to explain my work . (sorry for may english)

i make this method
`
public function changeEtat(request $request)
    {

        if(Module::has($request->modulename)){
            $module = Module::find($request->modulename);
            dd($request->etat);
            if ($request->etat == "on") {
                $module->disable();
                }
            else {
                $module->enable();
            }
        }
        $message = array('type' => 'danger', 'message' => 'Mise à jour du module acceptée');
        Session::flash('notifications', $message);
        return redirect()->route('admin_module');
    }
`

and on my view i make this

`
 @foreach ($modules as $module)
                        <tr>
                            <td>{{ $module->name }}</td>
                            <td>{{ $module->description}}</td>
                            <td>
                                @if($module->name != "Admin" )
                                    <form method="post" action="{{route('admin_etat_module')}}">
                                        <input type="hidden" name="modulename" value="{{$module->name}}"/>
                                        <input type="checkbox" name="etat" @if($module->active) checked  @endif data-toggle="toggle" data-size="xs" class="submit" />
                                        {{csrf_field()}}
                                    </form>
                               @endif
                            </td>
                        </tr>
                    @endforeach
`
I have a script on js to submit form

But this 
`
if ($request->etat == "on") {
                $module->disable();
                }
            else {
                $module->enable();
            }
`
doesn't work.
Have you a idea?

**Comment by nWidart** [comment]
Not without information about what doesn't work.

**Comment by Morpheons** [comment]
Oo Cheat i find why it doesn't work
i make mistake 
now it's good because :

if ($request->etat == "on") { $module->enable(); } else { $module->disable(); }

**Comment by Morpheons** [comment]
Thanks A Lot Nicolas
your job it's very good!
it's easy finaly to use it

**Comment by nWidart** [comment]
Awesome 👍
