### ISSUE TITLE
Routes not configured correctly in provider when default module stubs are changed

### ISSUE THREAD

**Issue by ZaidBarghouthi** [nWidart/laravel-modules#756]
When changing the default module stubs paths for routes, the generated `RoutesSerivceProvider` dose not load the routes correctly

```
'stubs' => [
        'enabled' => false,
        'path' => base_path() . '/vendor/nwidart/laravel-modules/src/Commands/stubs',
        'files' => [
            'routes/web' => '_routes/web.php',
            'routes/api' => '_routes/api.php',
```

The files are generated correctly but the 'RoutesServiceProvider` does not point to them
```
protected function mapWebRoutes()
    {
        Route::middleware('web')
            ->namespace($this->moduleNamespace)
            ->group(__DIR__ . '/../Routes/web.php');
    }
```
I know its minor :P

**Comment by nWidart** [comment]
Hi,

Thanks for reporting this!

It has been fixed in commit https://github.com/nWidart/laravel-modules/commit/fabea24955fe8968e322b7eaca62ad8d65617627
