### ISSUE TITLE
get list of enabled modules name  only

### ISSUE THREAD

**Issue by webreinvent** [nWidart/laravel-modules#76]
I have tried ```Module::all();``` but it gives whole lots of information. I just need list of "enabled" modules name in an array. Is there any quick way?

**Comment by nWidart** [comment]
That would be the way to do it.

**Comment by webreinvent** [comment]
```Module::all();``` give a big data object.

**Comment by nWidart** [comment]
Yes. Loop over that and call the getName() method for instance to get each module name.
