### ISSUE TITLE
cannot generate model

### ISSUE THREAD

**Issue by shahdinesh** [nWidart/laravel-modules#760]
I cannot generate model inside a module with artisan 
`php artisan module:make <MODULE_NAME>`.

or am i missing something. Here is config for module

`
'generator' => [
            'config' => ['path' => 'Config', 'generate' => true],
            'command' => ['path' => 'Console', 'generate' => false],
            'migration' => ['path' => 'Database/Migrations', 'generate' => false],
            'seeder' => ['path' => 'Database/Seeders', 'generate' => false],
            'factory' => ['path' => 'Database/factories', 'generate' => false],
            'model' => ['path' => 'Entities', 'generate' => true],
            'controller' => ['path' => 'Http/Controllers', 'generate' => true],
            'filter' => ['path' => 'Http/Middleware', 'generate' => false],
            'request' => ['path' => 'Http/Requests', 'generate' => false],
            'provider' => ['path' => 'Providers', 'generate' => true],
            'assets' => ['path' => 'Resources/assets', 'generate' => false],
            'lang' => ['path' => 'Resources/lang', 'generate' => false],
            'views' => ['path' => 'Resources/views', 'generate' => false],
            'test' => ['path' => 'Tests', 'generate' => false],
            'repository' => ['path' => 'Repositories', 'generate' => false],
            'event' => ['path' => 'Events', 'generate' => false],
            'listener' => ['path' => 'Listeners', 'generate' => false],
            'policies' => ['path' => 'Policies', 'generate' => false],
            'rules' => ['path' => 'Rules', 'generate' => false],
            'jobs' => ['path' => 'Jobs', 'generate' => false],
            'emails' => ['path' => 'Emails', 'generate' => false],
            'notifications' => ['path' => 'Notifications', 'generate' => false],
            'resource' => ['path' => 'Transformers', 'generate' => false],
        ],
[module.txt](https://github.com/nWidart/laravel-modules/files/3172686/module.txt)

`

**Comment by nWidart** [comment]
Try to copy the config file from this repository or run the publish command with `--force`.

**Comment by shahdinesh** [comment]
done that. it did not work.

**Comment by nWidart** [comment]
Ok, what error do you get?

**Comment by shahdinesh** [comment]
the model file is not being generated even if generate is set true in configuration. 
command i used was 
`php artisan module:make <MODULE_NAME>`

**Comment by nWidart** [comment]
And do you get an error? What's the output in the console?

I can't seem to reproduce the error on my end.

**Comment by shahdinesh** [comment]
the command does not generate model file.
that's the problem i am having.

**Comment by nWidart** [comment]
Feel free to provide more information when you can.

**Comment by masbenx** [comment]
I used the same config as @shahdinesh but model folder didn't show up in my modules..
the console result is like this

`Created : /Users/masbenx/Projects/Servers/pht-agroforest/html/Modules/Blog/module.json
Created : /Users/masbenx/Projects/Servers/pht-agroforest/html/Modules/Blog/Routes/web.php
Created : /Users/masbenx/Projects/Servers/pht-agroforest/html/Modules/Blog/Routes/api.php
Created : /Users/masbenx/Projects/Servers/pht-agroforest/html/Modules/Blog/Resources/views/index.blade.php
Created : /Users/masbenx/Projects/Servers/pht-agroforest/html/Modules/Blog/Resources/views/layouts/master.blade.php
Created : /Users/masbenx/Projects/Servers/pht-agroforest/html/Modules/Blog/Config/config.php
Created : /Users/masbenx/Projects/Servers/pht-agroforest/html/Modules/Blog/composer.json
Created : /Users/masbenx/Projects/Servers/pht-agroforest/html/Modules/Blog/Resources/assets/js/app.js
Created : /Users/masbenx/Projects/Servers/pht-agroforest/html/Modules/Blog/Resources/assets/sass/app.scss
Created : /Users/masbenx/Projects/Servers/pht-agroforest/html/Modules/Blog/webpack.mix.js
Created : /Users/masbenx/Projects/Servers/pht-agroforest/html/Modules/Blog/package.json
Created : /Users/masbenx/Projects/Servers/pht-agroforest/html/Modules/Blog/Database/Seeders/BlogDatabaseSeeder.php
Created : /Users/masbenx/Projects/Servers/pht-agroforest/html/Modules/Blog/Providers/BlogServiceProvider.php
Created : /Users/masbenx/Projects/Servers/pht-agroforest/html/Modules/Blog/Providers/RouteServiceProvider.php
Created : /Users/masbenx/Projects/Servers/pht-agroforest/html/Modules/Blog/Http/Controllers/BlogController.php
`
