### ISSUE TITLE
v5 Documenatiaon not available

### ISSUE THREAD

**Issue by nasirkhan** [nWidart/laravel-modules#762]
Thank you for releasing a new version of the package. 

Which using the package i found that the doc has not been available for v5 and there is no upgrade guide. Is there any date for the doc availability?

**Comment by nWidart** [comment]
Hi,

Indeed I haven't had the time to do so. In the meantime, you can view the [release notes](https://github.com/nWidart/laravel-modules/releases) on github. Nothing has changed between v4 and v5 basically, just the laravel version.

**Comment by nWidart** [comment]
v5 was added via contribution. 👌
