### ISSUE TITLE
Register a web middleware

### ISSUE THREAD

**Issue by nasirkhan** [nWidart/laravel-modules#765]
I use [lavary/laravel-menu](https://github.com/lavary/laravel-menu) to generate menu of my application. On the previous version of the [nWidart/laravel-modules](https://github.com/nWidart/laravel-modules) there was a `start.php` file where i added the menus. 

on the new version `start.php` is removed. So i followed the approach mentioned on the doc and generated a new middleware. But i did not find any doc related to registering the middleware. Can you please show me how can i add a new middleware to the `web` group?

Update
---
I followed the issue https://github.com/nWidart/laravel-modules/issues/175 and added the middleware like the following, but i want to know how can i add to `web` or `api` group?

```php
// adding global middleware
$kernel = $this->app->make('Illuminate\Contracts\Http\Kernel');
$kernel->pushMiddleware('Modules\Travel\Http\Middleware\GenerateMenus');
```

**Comment by nWidart** [comment]
Hi I wouldn't create the menus in a middleware. You can still create that start.php file, and then add it in the module.json as you had before.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by GabrielsPortal** [comment]
You can add middleware to a group :

// adding route middleware groups
        $router = $this->app->make(Router::class);
        $router->pushMiddlewareToGroup('web', GenerateMenus::class);

Don't forget to add on top of page 

use Illuminate\Routing\Router;

**Comment by AbiruzzamanMolla** [comment]
> You can add middleware to a group :
> 
> // adding route middleware groups $router = $this->app->make(Router::class); $router->pushMiddlewareToGroup('web', GenerateMenus::class);
> 
> Don't forget to add on top of page
> 
> use Illuminate\Routing\Router;

Thanks, this works for me on Laravel 10

**Comment by swartjie** [comment]
> > You can add middleware to a group :
> > // adding route middleware groups $router = $this->app->make(Router::class); $router->pushMiddlewareToGroup('web', GenerateMenus::class);
> > Don't forget to add on top of page
> > use Illuminate\Routing\Router;
> 
> Thanks, this works for me on Laravel 10

I am really struggling with this...
How do you guys use the above method but still pass route variables into the menu builder?

I get the middleware to fire, but I can't get in my case the `client` parameter in the url so my routes bomb out??
Any advice?

**Comment by dcblogdev** [comment]
I don't use middleware for that but register in the boot method directly.

```php
public function boot(): void
{
    $this->registerCommands();
    $this->registerCommandSchedules();
    $this->registerTranslations();
    $this->registerConfig();
    $this->registerViews();
    $this->loadMigrationsFrom(module_path($this->moduleName, 'database/migrations'));

    Menu::make('AdminMenu', function ($menu) {
        $menu->add('Clubs', url('admin/clubs'))->data('icon', 'fa-book')->data('order', 0);
    })->sortBy('order');
}
```

**Comment by swartjie** [comment]
> I don't use middleware for that but register in the boot method directly.
> 
> ```
> public function boot(): void
> {
>     $this->registerCommands();
>     $this->registerCommandSchedules();
>     $this->registerTranslations();
>     $this->registerConfig();
>     $this->registerViews();
>     $this->loadMigrationsFrom(module_path($this->moduleName, 'database/migrations'));
> 
>     Menu::make('AdminMenu', function ($menu) {
>         $menu->add('Clubs', url('admin/clubs'))->data('icon', 'fa-book')->data('order', 0);
>     })->sortBy('order');
> }
> ```

What class do you use for the menu though?
And how do you pass url parameters into the menu without it bombing out as soon as livewire sends a request?

My menu using Spatie's menu class works if I add the below into my boot function for the module service provider:
```
Menu::macro('main', function () {
            $client = request()->route('client');
            if($client){
                return Menu::new()
                    ->addClass('nav-tabs')
                    ->setActiveClass('text-indigo-600 border-indigo-500')
                    ->setActiveFromRequest()
                    ->add(Link::to(route('Client.Manage', $client), 'Summary')
                        ->addParentClass('whitespace-nowrap border-b-2 border-transparent px-1 py-4 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700'))
                    ->add(Link::to(route('Client.Profile', $client), 'Profile')
                        ->addParentClass('whitespace-nowrap border-b-2 border-transparent px-1 py-4 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700'))
                    ->add(Link::to(route('Client.Users', $client), 'Users')
                        ->addParentClass('whitespace-nowrap border-b-2 border-transparent px-1 py-4 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700'))
                    ->add(Link::to(route('Client.Contacts', $client), 'Contacts')
                        ->addParentClass('whitespace-nowrap border-b-2 border-transparent px-1 py-4 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700'));
            }
        });
```

But as soon as I fire any livewire click event, the menu is just lost, because the $client variable then is null due to the route('client') no longer existing according to it?

**Comment by dcblogdev** [comment]
I'm using lavary/laravel-menu

I don't really have anything similar to what your doing but if I need to access auth I'll use a closure within a view composer like:

```php
View::composer('admin::layouts.app', function($view) {
    if (auth()->user()->can('View Reports')) {
        Menu::make('LeftMenu', function ($menu) {
            $menu->add('Reports', url('admin/reports'))->data('icon', 'far fa-chart-line')->data('order', 11);
        })->sortBy('order');
    }
});
```

Maybe the same idea for requests too.

**Comment by swartjie** [comment]
> I'm using lavary/laravel-menu
> 
> I don't really have anything similar to what your doing but if I need to access auth I'll use a closure within a view composer like:
> 
> ```
> View::composer('admin::layouts.app', function($view) {
>     if (auth()->user()->can('View Reports')) {
>         Menu::make('LeftMenu', function ($menu) {
>             $menu->add('Reports', url('admin/reports'))->data('icon', 'far fa-chart-line')->data('order', 11);
>         })->sortBy('order');
>     }
> });
> ```
> 
> Maybe the same idea for requests too.

Do you have an idea if livewire will get triggered using a view composer?
Because my issue is livewire fires, but does not trigger any other form of events...

**Comment by swartjie** [comment]
> ```
> View::composer('admin::layouts.app', function($view) {
>     if (auth()->user()->can('View Reports')) {
>         Menu::make('LeftMenu', function ($menu) {
>             $menu->add('Reports', url('admin/reports'))->data('icon', 'far fa-chart-line')->data('order', 11);
>         })->sortBy('order');
>     }
> });
> ```

Thank you, Based on your info, I created a view provider, and I then added the following code to it:

```
public function boot(){
        View::composer('clients::layouts.master', function($view) {
            $cacheKey = 'client_' . session()->getId();

            $client = request()->route('client');

            if ($client)  Cache::put($cacheKey, $client, now()->addMinutes(30));
            else $client = Cache::get($cacheKey);

            $this->app->singleton('client-summary-tab-menu', function () use($client) {
                return Menu::new()
                    ->addClass('nav-tabs')
                    ->setActiveClass('text-indigo-600 border-indigo-500')
                    ->setActiveFromRequest()
                    ->add(Link::to(route('Client.Manage', $client), 'Summary')
                        ->addParentClass('whitespace-nowrap border-b-2 border-transparent px-1 py-4 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700'))
                    ->add(Link::to(route('Client.Profile', $client), 'Profile')
                        ->addParentClass('whitespace-nowrap border-b-2 border-transparent px-1 py-4 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700'))
                    ->add(Link::to(route('Client.Users', $client), 'Users')
                        ->addParentClass('whitespace-nowrap border-b-2 border-transparent px-1 py-4 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700'))
                    ->add(Link::to(route('Client.Contacts', $client), 'Contacts')
                        ->addParentClass('whitespace-nowrap border-b-2 border-transparent px-1 py-4 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700'));
            });
        });
    }
```
    
    This helps mitigate the issue with livewire reloading and losing the client id.
    
    My only issue left is when livewire submits the wire:click command, the "setActiveFromReuqest()" fails and no longer marks the menu as active. But I'll have to rise that on their end and find a work around.
    Your advise helped me a lot thank you!
