### ISSUE TITLE
Extend Package

### ISSUE THREAD

**Issue by lazosweb** [nWidart/laravel-modules#768]
@nWidart is there a way to extend your package without messing with your code?

If for example I would like add some more methods to the Module Class how I can do that?

Is it possible for me to create a package that extends yours?

If it's possible can you provide a sample please?

**Comment by nWidart** [comment]
Hello,

The Module class has the [Macroable](https://github.com/nWidart/laravel-modules/blob/master/src/Module.php#L13) trait so you can add methods to it using that.

Example here: https://laravel.com/docs/5.8/collections#extending-collections

**Comment by lazosweb** [comment]
Thank you. This is what I needed.
