### ISSUE TITLE
Remove the folder assets in resources

### ISSUE THREAD

**Issue by pmochine** [nWidart/laravel-modules#770]
Hey ho :)

Now could you remove the assets folder in resources, because since Laravel 5.8 we don't use it anymore.

Thanks, :D (p.S. I wanted to  create a pull request, but just couldn't find the stub for it...)

**Comment by mikemand** [comment]
Hi,

It's done here: https://github.com/nWidart/laravel-modules/blob/c370a51c9e1bc7dacebc88d5588157151de27080/config/config.php#L35-L36

You can change this in your own config until someone PRs it.

**Comment by JThompsonNZ** [comment]
@pmochine We still have the option to use the assets folder in 5.8. It's just a case of creating the assets folder and updating webpack.mix.js

Having an assets folder is much preferred in any case.

**Comment by pmochine** [comment]
> @pmochine We still have the option to use the assets folder in 5.8. It's just a case of creating the assets folder and updating webpack.mix.js
> 
> Having an assets folder is much preferred in any case.

Sorry, I should have written it better. I don't mean the folder `/Assets/`, but meant `Resources/assets`

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
