### ISSUE TITLE
Handling modules with tenants

### ISSUE THREAD

**Issue by devonecube** [nWidart/laravel-modules#771]
Hi,

First thanks for your work on this package. Second, I'm using hyn for a multitenants app. Tenant 1 needs module1 to be activated but not the second tenant. How can I handle activation / deactivation modules by tenants with your module ?

There is a json file but what about with tenants ?

Thanks for your answer

**Comment by nWidart** [comment]
Hi,

You currently can't do this. There's a branch where I started working on the database repository which could allow this.

However, you can still achieve the same result by not disabling modules, but by limiting their access.

**Comment by devonecube** [comment]
Hi and thnaks for your answer.
Ok a middleware for example could do the trick ;) Thanks for your explanation

**Comment by phuclh** [comment]
> Hi,
> 
> You currently can't do this. There's a branch where I started working on the database repository which could allow this.
> 
> However, you can still achieve the same result by not disabling modules, but by limiting their access.

I just installed this package yesterday. This is really an awesome package. I have the same issue with @devonecube, do you have any plan to release that branch?
