### ISSUE TITLE
How to overrride config in app/app.php

### ISSUE THREAD

**Issue by anhchungite** [nWidart/laravel-modules#772]
I have 2 modules Backend & Frontend, but I want them display with 2 difference language and 2 difference timezone.
If I config locale and timezone at `app/app.php`, it work in both modules Backend & Frontend.
So how to I can individual configuration for each modules?

**Comment by nWidart** [comment]
Hi,

You can use the Config api from laravel. Example `$app['config']->set('key', 'value');`

**Comment by anhchungite** [comment]
> Hi,
> 
> You can use the Config api from laravel. Example `$app['config']->set('key', 'value');`

Thanks for reply.
I have tried, but it not work.
In `app\app.php`

```
return [
...
'locale' => 'vi'
...
];
```

in `Providers\BackendServiceProvider.php`

  ```
public function boot()
    {
        $this->app['config']->set('app.locale', 'en');
        // $this->app->setLocale('en'); // also not work
        $this->registerTranslations();
        $this->registerConfig();
        $this->registerViews();
        $this->registerFactories();
        $this->loadMigrationsFrom(__DIR__ . '/../Database/Migrations');
    }
```

After then I clear cache:
```
php artisan config:clear
php artisan cache:clear
```

Finally it also not work, my Backend still display locale __vi__ instead of __en__

**Comment by nWidart** [comment]
You must be overriding it somewhere else then. I'm using the method to do exactly this.

I'll close the issue as it's not related to this package.

**Comment by anhchungite** [comment]
I have detected, config of Frontend module has override config of Backend.
In `BackendServiceProvider.php`
```
public function boot()
    {
        echo 'backend';
        $this->app->setLocale('en');

        $this->registerTranslations();
        $this->registerConfig();
        $this->registerViews();
        $this->registerFactories();
        $this->loadMigrationsFrom(__DIR__ . '/../Database/Migrations');
    }
```

In `FrontendServiceProvider.php`
```
public function boot()
    {
        echo 'frontend';
        $this->app->setLocale('vi');

        $this->registerTranslations();
        $this->registerConfig();
        $this->registerViews();
        $this->registerFactories();
        $this->loadMigrationsFrom(__DIR__ . '/../Database/Migrations');
    }
```
And when I access `http://localhost:8000/backend`, I get `backendfrontend` and locale is `vi`.
Seem Frontend module still load while I access Backend. 
I think that will be affect peformance and can't individual configuration for each modules.

**Comment by nWidart** [comment]
In that case just make sure to only perform backend login when you know a user is on the backend.

**Comment by anhchungite** [comment]
Sorry But I don't understand what you mean.
Is there any solution to solve my problem?
Thanks!
