### ISSUE TITLE
module:publish

### ISSUE THREAD

**Issue by s79dev** [nWidart/laravel-modules#775]
I apologize if the question is repeated
Sorry for my english
I have module "ExtendCharacters" when I use "module:publish ExtendCharacters". I get in public directory ".../modules/extendcharacters" and need use "{{Module::asset('extendcharacters:js/test.js')}}". When i use "{{Module::asset('ExtendCharacters:js/test.js')}}" i got 404 (not error in php (catalog not found))
Why change letter in name module? Where else does the name register change? Why not catalog error?
And why in "module:publish" not use  link?

**Comment by nWidart** [comment]
Hi,

This is probably to avoid issues in OSs and browsers that don't support case sensibility.

**Comment by s79dev** [comment]
But this make trouble for OS where use case sensibility.  And as far as I understand it is all Linux hosting

**Comment by nWidart** [comment]
I'm not sure this is a good idea. In general we shouldn't depend on case sensitivity.
