### ISSUE TITLE
Event Listeners in a specific module

### ISSUE THREAD

**Issue by VeRJiL** [nWidart/laravel-modules#777]
Hi,
In laravel itself, There is EventServiceProvider that we register our events and related listeners in it.
Should we create a EventServiceProvider for each module individually? Or we register our events and listeners in the main EventServiceProvider ?

**Comment by nWidart** [comment]
Hi,

That's up to you. I would personally have one per module, because I like modules to contain their own logic.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
