### ISSUE TITLE
Creating Controller through command line

### ISSUE THREAD

**Issue by VeRJiL** [nWidart/laravel-modules#778]
Hi,
If you use php artisan module:make-controller ControllerName ModuleName, the created controller extends the wrong controller.
It extends Illuminate\Routing\Controller instead of App\Http\Controllers\Controller

**Comment by nWidart** [comment]
Hi,

This is intended, we don't want to depend on things from the app namespace.
If you prefer to do so, you can override the controller stub and change the base controller namespace according to your preference.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
