### ISSUE TITLE
swagger documentation

### ISSUE THREAD

**Issue by JHONF2078** [nWidart/laravel-modules#779]
hello 
how can I do the integration with the library l5-swagger to document each module

**Comment by nWidart** [comment]
Hi,

I haven't used that package so I can't help you with that.
Though I assume like explained on their documentation.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by unaveen** [comment]
I'm using swagger package but unable to integrate with each module in Laravel 6

**Comment by serkansahinn** [comment]
Hi,

You can make it in swagger's config.

```
'annotations' => [
            base_path('app'),
            base_path('Modules'),
        ],
```

**Comment by zkenstein** [comment]
How about scribe?
