### ISSUE TITLE
Invalid migration name when creating migration

### ISSUE THREAD

**Issue by msieprawski** [nWidart/laravel-modules#78]
Hi,

I'm experiencing pretty weird exception being thrown when I try to create migration using `module:make-migration` command. First of all I want to change my column name on existing table. I'm trying to execute `module:make-migration change_spent_at_to_date`. I can see that parser allows only: create, drop, delete and add action. I think that you should also add `/migration/blank.stub` and there just put:

``` php
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class $CLASS$ extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {

    }
}
```

What do you think?

**Comment by nWidart** [comment]
I agree, I've had this block me multiple times as well.

I'd gladly accept a PR with a default option if the parser didn't match anything else.

**Comment by nWidart** [comment]
I fixed this on `dev-master` feel free to test it out.

**Comment by nWidart** [comment]
Tagged on 1.15.0
