### ISSUE TITLE
With Vue, how register Components in Module's file app.js

### ISSUE THREAD

**Issue by rodmayes** [nWidart/laravel-modules#780]
Hi,

how can I register  module's components in its file app.js folder, not in file app.js from /root?

/root
-/app
-/resources
-/assets
--/js
---app.js <-- NO
-/Modules
--/ModuleName
---/resources
----/assets
-----/js
------**app.js <-- HERE**

**Comment by jjsquady** [comment]
Register all components in a master file (like _components.js and export it) and import that file to application main app.js.

**Comment by rebortec** [comment]
But the main application does not know that the module exists. Such as a marketplace

**Comment by jjsquady** [comment]
Suck as a marketplace, u need to register that module into main application.

**Comment by rebortec** [comment]
Any way to do it dynamically? I'm trying with the 'fs' module but I can not

**Comment by nWidart** [comment]
There is, I remember seeing somebody doing this. I can't you on how to do this though as it's more related to javascript than this package.
