### ISSUE TITLE
Listeners in modules not support ShouldQueue ?

### ISSUE THREAD

**Issue by NexxusPlexx** [nWidart/laravel-modules#782]
I'm trying to implement "ShouldQueue" functionality in my event listener as Laravel Documentation but I think there is an issue because I got an error: **Serialization of 'Closure' is not allowed** when I try to **Implement ShouldQueue**, I remove all my logic inside this listener to test if something inside is wrong but even if is empty the handle method is crashing

<pre>

namespace Modules\Payments\Listeners;

use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Support\Facades\Mail;
use Modules\Payments\Emails\PaymentReceiptMail;

Class SendPaymentReceiptListener implements ShouldQueue --> **this does not work**
{

    public function __construct()
    {

    }

    public function handle($event)
    {
        //Mail::to($event->request->email)->send(new PaymentReceiptMail());
    }
}
</pre>
If I try with a normal event and listener native of Laravel inside App\Listeners, everything works fine, the problem is inside the module when I try to use **ShouldQueue**

Could you give me an idea of what is happening?

Thank You!

**Comment by jjsquady** [comment]
Can you show the event implementation?

**Comment by NexxusPlexx** [comment]
> Can you show the event implementation?

Yes sure this the Event:
<pre>

namespace Modules\Payments\Events;

use Illuminate\Queue\SerializesModels;

class NewPaymentHasBeenProcessedEvent
{
    use SerializesModels;
    public $request;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($request)
    {
        $this->request = $request;
    }

    /**
     * Get the channels the event should be broadcast on.
     *
     * @return array
     */
    public function broadcastOn()
    {
        return [];
    }
}
</pre>


**And this is the EventService Provider:**

<pre>

class EventServiceProvider extends ServiceProvider
{

    protected $listen = [
        NewPaymentHasBeenProcessedEvent::class => [
            SendPaymentReceiptListener::class,
        ],
    ];
}

</pre>

**Comment by jjsquady** [comment]
Don't pass `$request` to the constructor. If u need get an request value, try to pass the value instead full `$request` object or pass all request values as array.

Change:
```
public function __construct($request)
    {
        $this->request = $request;
    }
```
To:
```
public function __construct($request)
    {
        $this->toEmail = $request->email;
        // or $this->request = $request->all();
    }
```
And change on Listener:
```
public function handle($event)
    {
        //Mail::to($event->request->email)->send(new PaymentReceiptMail());
    }
```
To:
```
public function handle($event)
    {
        Mail::to($event->toEmail)->send(new PaymentReceiptMail());
        // or Mail::to($event->request['email'])->send(new PaymentReceiptMail());
    }
```

Source: 
https://laracasts.com/discuss/channels/laravel/serialization-of-closure-is-not-allowed-in-queuing-a-mail?page=1

**Comment by NexxusPlexx** [comment]
> Don't pass `$request` to the constructor. If u need get an request value, try to pass the value instead full `$request` object or pass all request values as array.
> 
> Change:
> 
> ```
> public function __construct($request)
>     {
>         $this->request = $request;
>     }
> ```
> 
> To:
> 
> ```
> public function __construct($request)
>     {
>         $this->toEmail = $request->email;
>         // or $this->request = $request->all();
>     }
> ```
> 
> And change on Listener:
> 
> ```
> public function handle($event)
>     {
>         //Mail::to($event->request->email)->send(new PaymentReceiptMail());
>     }
> ```
> 
> To:
> 
> ```
> public function handle($event)
>     {
>         Mail::to($event->toEmail)->send(new PaymentReceiptMail());
>         // or Mail::to($event->request['email'])->send(new PaymentReceiptMail());
>     }
> ```
> 
> Source:
> https://laracasts.com/discuss/channels/laravel/serialization-of-closure-is-not-allowed-in-queuing-a-mail?page=1

Thank You very much it Works!, I did not realize that I was passing the full object Request in my constructor
