### ISSUE TITLE
Publishing Modules 

### ISSUE THREAD

**Issue by nasirkhan** [nWidart/laravel-modules#783]
I want to publish my modules and use across multiple projects. I [found a doc](https://nwidart.com/laravel-modules/v5/advanced-tools/publishing-modules) regarding this followed the steps. I published a module at Packagist https://packagist.org/packages/nasirkhan/article-module

On some previous discussion i might see that you mentioned that https://nwidart.com/laravel-modules can install the published modules and no need to install additional package like https://github.com/joshbrw/laravel-module-installer

So i followed the first part of the doc and tried to install the module with the following command

```php
composer require nasirkhan/article-module
```
But unfortunately it did not install the module package and showed the error as below, 

```php
                                                                                                                       
[InvalidArgumentException]                                                                                           
Could not find a version of package nasirkhan/article-module matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability. 
```

**Comment by nWidart** [comment]
Hi,

You're close, that's just composer telling you you're trying to require a branch like `dev-master`. Check you minimum stability config in your `composer.json` file. Or tag your module and then require that version.

**Comment by nasirkhan** [comment]
Thanks. It worked.

**Comment by nasirkhan** [comment]
Sorry, the install was ok, but did not moved to the Module directory. my module is on the vendor directory.

**Comment by nWidart** [comment]
that is the expected behaviour. A module is just a composer package. 
There are ways to have it in the modules dir though, I do this with asgarcms, where modules are put in the modules dir.
You'll have to research composer plugins for this. 
This PR explains a bit about this: https://github.com/nWidart/nwidart-docs/pull/24

**Comment by nasirkhan** [comment]
Thanks for your response. 
composer packages would be installed on the vendor dir and it is the expected behavior. But on the issue description i asked you that if there is still a need to install a separate package to change this default behavior. when you replied that changing the min stability or tagging a version could solve the install issue, i assumed that you were mentioning install with changed behavior. 

Now i understand that the https://github.com/joshbrw/laravel-module-installer is still necessary to get the changed behavior of the composer. right?

**Comment by nWidart** [comment]
Sorry I was replying to the question you asked after re-opening the issue:
> Sorry, the install was ok, but did not moved to the Module directory. my module is on the vendor directory.

I think you're confusing things. You were getting an error on composer stability which is not related to the location of modules.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
