### ISSUE TITLE
Multiple Folder in one Alias

### ISSUE THREAD

**Issue by ariefun98** [nWidart/laravel-modules#784]
Is possible load multiple folder like folder Modules & Core?

**Comment by nWidart** [comment]
I don't believe it is no.

**Comment by narwy** [comment]
You've not really explained your question. but if you're talking about adding another autoload folder you can do so by adding it to the psr-4 tag in the autoload of your composer file.

```
"autoload": {
        "psr-4": {
            "App\\": "app/",
	    "Modules\\": "Modules/",
	    "Core\\": "Core/"
        },
}
```

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
