### ISSUE TITLE
Route module overwrite by laravel route

### ISSUE THREAD

**Issue by LeonardoBAV** [nWidart/laravel-modules#785]
Hello!!!

I have a situation that, I want the module routes to override some standard laravel routes (eg AuthRoutes, Home). For this, the module routes must be loaded after the laravel routes.

In the project that I develop the modules this occurs correctly. But when I create a laravel project and install the module by composer (using , joshbrw/laravel-module-installer), the module routes are loaded before and so the laravel overrides the module routes. This is happen becausethe provider module  is loading before the laravel providers.

Can someone help me

**Comment by narwy** [comment]
You will need to disable the loading of the framework routes. They will take priority over any routes you add as they're already loaded before it hit's the route files.

**Comment by LeonardoBAV** [comment]
How to do that?

**Comment by nWidart** [comment]
You can look at the laravel documention. Look at the route service provider.
