### ISSUE TITLE
Activator feature

### ISSUE THREAD

**Issue by ryssbowh** [nWidart/laravel-modules#789]
Hi there,

In my project I needed to take the activation logic out of the Module class, the main reason for this being that the activation status being in a git tracked file, I find it makes it messy when pushing changes to modules (as composer packages) and pulling them in other projects.
If I'm developing a module, it's obviously enabled, but I might not want it enabled by default when pulling it in another project, maybe I have some logic to be made before etc..

Anyway I've implemented that in my project, with a default FileActivator that stores the activation status in a separate file, but it could be a database activator or anything else.

I'm not doing a pull request as it's quite a change but if that's of any interest I'll do one https://github.com/ryssbowh/laravel-modules/tree/activator/.

Thanks again for this great package !

**Comment by nWidart** [comment]
You can take a look at the [database-modules[(https://github.com/nWidart/laravel-modules/tree/feature/database-modules) branch for this too.

**Comment by nWidart** [comment]
I just looked at your branch, I like the idea of this. 👌  It's a good intermediary solution.

**Comment by ryssbowh** [comment]
Thanks,

I did have a look at the database branch, but didn't feel I had the level to take it on.

Doing a pull request now.

**Comment by SeoRoman** [comment]
@nWidart What all does the database-modules system still need?

**Comment by lexdewilligen** [comment]
@nWidart I've started working on the database implementation using your database branch. I've implemented some methods that were abstract, but I don't know how to go on. Could you take a look at my branch and tell me what needs to be done next? 

https://github.com/lexdewilligen/laravel-modules/commit/0fe036eb7f81d904b641f4780058bd3431a0c2b1

**Comment by nWidart** [comment]
Thank you!

I believe if you need the database implementation for maintaining module statuses, using the activator feature will be your fastest way to get this up and running.

**Comment by lexdewilligen** [comment]
@nWidart Yes, but I don't understand how to implement the activator feature for the database..

**Comment by ryssbowh** [comment]
Hi,

If you write a new Activator class that implements the ActivatorInterface and reference it in your config :
```
'activators' => [
        'file' => [
            'class' => FileActivator::class,
            'statuses-file' => storage_path('modules_statuses'),
            'cache-key' => 'activator.installed',
            'cache-lifetime' => 604800,
        ],
        'database' => [
            'class' => DatabaseActivator::class
        ]
    ],

    'activator' => 'database'
```
That should work

**Comment by lexdewilligen** [comment]
Yes I also got to that part, but more on the specific implementation of the DatabaseActivator. 

How should I implement the following for example:

```php
    /**
     * @inheritDoc
     */
    public function setActiveByName(string $name, bool $status): void
    {
        $this->modulesStatuses[$name] = $status;
        $this->writeJson();
        $this->flushCache();
    }
```

I'd say:

```php
    /**
     * @inheritDoc
     */
    public function setActiveByName(string $name, bool $status): void
    {
        $this->moduleEntity->is_active = $status;
        $this->moduleEntity->save();
    }
```

Or should that be done differently?

**Comment by nWidart** [comment]
that looks ok yes. Probably a `findByModuleName` or something just before.

**Comment by lexdewilligen** [comment]
Okay, I've implemented the DatabaseActivator, however, there are still a few issues:

- `loadMigrationsFrom` does not load the packages migration
- Modules don't get booted/registered

Any clue on why this is the case? How/where are modules booted using the FileActivator?

https://github.com/lexdewilligen/laravel-modules/tree/feature/database-activator

**Comment by nWidart** [comment]
Hi @lexdewilligen ,
I had a quick look at your branch and it looks good. 
I would do a couple of changes but as start this is very promising, good job!

**Comment by lexdewilligen** [comment]
Thank you @nWidart ! I've just got it "working" last night. I'll improve the code and then submit a pull request.

**Comment by joshtorres** [comment]
Hey @lexdewilligen @nWidart was this ever finished, or did you find another way of doing this without a Database Activator? I took a look at the code and it looks at least close to complete. I could finish it out if needed.
