### ISSUE TITLE
All Modules Routes mapping by core

### ISSUE THREAD

**Issue by GhulamJafar** [nWidart/laravel-modules#79]
How you have loaded all routes of multiple modules by core module in asgard cms?

I have module user page, setting, application, so i want to load all routes by core module. How to do this?

**Comment by nWidart** [comment]
Look at the RoutingServiceProvider in the core module of asgardcms.

**Comment by GhulamJafar** [comment]
Please see my case, its not working for me.unable to trace this issue. Or tell me how to accomplish this.

Modules\core\providers\RoutingServiceProvider
`<?php namespace Modules\Core\Providers;

use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
use Illuminate\Routing\Router;

abstract class RoutingServiceProvider extends ServiceProvider
{
    /**
     * The root namespace to assume when generating URLs to actions.
     *
     * @var string
     */
    protected $namespace = '';

    /**
     * Define your route model bindings, pattern filters, etc.
     *
     * @param  \Illuminate\Routing\Router $router
     * @return void
     */
    public function boot(Router $router)
    {
        parent::boot($router);
    }

    /**
     * @return string
     */
    abstract protected function getFrontendRoute();

    /**
     * @return string
     */
    abstract protected function getBackendRoute();

    /**
     * @return string
     */
    abstract protected function getApiRoute();

    /**
     * Define the routes for the application.
     *
     * @param  \Illuminate\Routing\Router $router
     * @return void
     */
    public function map(Router $router)
    {
        $router->group(['namespace' => $this->namespace], function (Router $router) {
            $this->loadApiRoutes($router);
        });

        $router->group(['namespace' => $this->namespace ], function (Router $router) {
            $this->loadBackendRoutes($router);
            $this->loadFrontendRoutes($router);
        });
    }

    /**
     * @param Router $router
     */
    private function loadFrontendRoutes(Router $router)
    {
        $frontend = $this->getFrontendRoute();

        if ($frontend && file_exists($frontend)) {
            $router->group(['middleware' => config('myconfig.core.core.middleware.frontend', [])], function (Router $router) use ($frontend) {
                require $frontend;
            });
        }
    }

    /**
     * @param Router $router
     */
    private function loadBackendRoutes(Router $router)
    {
        $backend = $this->getBackendRoute();
        if ($backend && file_exists($backend)) {
            $router->group(['namespace' => 'Admin', 'prefix' => config('seedout.core.core.admin-prefix'),
                'middleware' => config('myconfig.core.core.middleware.backend', [])],
                function (Router $router) use ($backend) {
                    require $backend;
                });
        }
    }

    /**
     * @param Router $router
     */
    private function loadApiRoutes(Router $router)
    {
        $api = $this->getApiRoute();

        if ($api && file_exists($api)) {
            $router->group(['namespace' => 'Api', 'prefix' => 'api', 'middleware' => config('myconfig.core.core.middleware.api', [])], function (Router $router) use ($api) {
                require $api;
            });
        }
    }
}
`
Code of user module route service provider
Modules\user\providers\RouteServiceProvider
`<?php namespace Modules\User\Providers;

use Modules\Core\Providers\RoutingServiceProvider as CoreRoutingServiceProvider;

class RouteServiceProvider extends CoreRoutingServiceProvider
{
    /**
     * The root namespace to assume when generating URLs to actions.
     *
     * @var string
     */
    protected $namespace = 'Modules\User\Http\Controllers\Admin';

    /**
     * @return string
     */
    protected function getFrontendRoute()
    {
        return __DIR__ . '/../Http/frontendRoutes.php';
    }

    /**
     * @return string
     */
    protected function getBackendRoute()
    {
        return __DIR__ . '/../Http/backendRoutes.php';
    }

    /**
     * @return string
     */
    protected function getApiRoute()
    {
        return false;
    }
}
`
Code for user module backendRoutes.php
Modules\user\http\
`use Illuminate\Routing\Router;

$router->group(['prefix' => 'user' ], function (Router $router) {

    /*User*/
    //$router->get('/test/test_email', ['uses' => 'testmail@sendEmailReminder','as' => 'test.email']);
    $router->get('/{user_type?}', ['uses' => 'UserController@index','as' => 'user.list']);
    $router->post('/delete', ['uses' => 'UserController@destroy','as' => 'user.delete']);
    $router->get('/create/user', ['uses' => 'UserController@create','as' => 'user.create']);
    $router->post('/save/user', ['uses' => 'UserController@store','as' => 'user.save']);
    $router->get('/{user_id}/edit', ['uses' => 'UserController@edit','as' => 'user.edit']);
    $router->put('/{user_id}/edit', ['uses' => 'UserController@update','as' => 'user.update']);
    $router->get('/{user_id}/view', ['uses' => 'UserController@view','as' => 'user.view']);
    $router->post('/update_status', ['uses' => 'UserController@update_status','as' => 'user.update_status']);

});`

**Following error occurs.**

`NotFoundHttpException in RouteCollection.php line 161:

in RouteCollection.php line 161
at RouteCollection->match(object(Request)) in Router.php line 821
at Router->findRoute(object(Request)) in Router.php line 691
at Router->dispatchToRoute(object(Request)) in Router.php line 675
at Router->dispatch(object(Request)) in Kernel.php line 246
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in InitiateTheme.php line 19
at InitiateTheme->handle(object(Request), object(Closure))
at call_user_func_array(array(object(InitiateTheme), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
at CheckForMaintenanceMode->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
at Pipeline->then(object(Closure)) in Kernel.php line 132
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 99
at Kernel->handle(object(Request)) in index.php line 54`

**Comment by GhulamJafar** [comment]
Sorry i got it, Actually i didn't loaded User Routeserviceproder by composer. Issue Resolved.

Thanks for your assistance
