### ISSUE TITLE
Modules admin and user

### ISSUE THREAD

**Issue by bolus150** [nWidart/laravel-modules#791]
Hi,

I would like to make such a structure: 
Modules: 
-- Admin
-- User

I coped with - Admin by setting modules.php 'modules' => base_path ('Modules / Admin'), but this limits and I can not give from User. Is there any way to separate this way?

**Comment by bolus150** [comment]
Can you help me?

**Comment by nWidart** [comment]
I'm not sure what you're asking. Yes you can create an Admin module and a User module.

**Comment by bolus150** [comment]
Forgive me that I have not clearly described what I would like to achieve. I would like to separate the administrator modules from user modules.
Modules
--Admin
----ExampleModule
--User
----OtherModule.

Do you now understand what I want to achieve?

**Comment by nWidart** [comment]
Ah I see, you can't do this with this package, I don't recommend doing this.

**Comment by bolus150** [comment]
Can you recommend something? How to do something similar?

**Comment by nWidart** [comment]
No, as I said I wouldn't this.
User logic belongs to a user module not split across 2 modules. If you have the user Model, where do you put it? 

Keep things grouped.

**Comment by bolus150** [comment]
So you suggest the user module normally in the app folder?

**Comment by nWidart** [comment]
No, I suggest using this package. I'd leave `app` as much as possible empty.

**Comment by bolus150** [comment]
That is, omit the Modules directory and the main directory to do, e.g. AdminModules and UserModules?

**Comment by nWidart** [comment]
No, I'd keep the module directory and have one User module.

**Comment by bolus150** [comment]
Ok, and what if the user has modules for invoices, data editing, reports and some other. What structure would you do?

**Comment by nWidart** [comment]
Then I would have an invoices module etc.

**Comment by bolus150** [comment]
In directory Modules? Without Admin and User directory?

**Comment by nWidart** [comment]
yes... I'm closing this as it's going nowhere.
