### ISSUE TITLE
Disable calls from modules to DB / Auth for 3rd party developers

### ISSUE THREAD

**Issue by stefnats** [nWidart/laravel-modules#792]
Hi,

i want to enable third party developers to extend our web app via laravel-modules.
However, i don't want them to access the raw user data, so to disallow something like

`User::all()`

or

`DB::table('users')->query()->get()`

or even

`auth()->user()` or `Auth::user()`

Is this possible using this package or do you recommend using other approaches?

**Comment by nWidart** [comment]
Hi,

This is not in the scope of this package, probably any package as it's custom stuff.
I suggest you make your own wrapper classes around `User` `DB` etc, where you check for roles/permissions before proxying through the main class.

**Comment by stefnats** [comment]
You're right, that's a good idea.
Do you know which would be the easiest way to, let's say, change the `DB::table('users')->query()->get()` method (just the `get`) without screwing with the laravel code managed by composer?

**Comment by nWidart** [comment]
I didn't mean you have to change laravel's code. I meant you create your _own_ wrapper class which proxies calls through laravel's class. 

Something to look up, the decorator pattern.

**Comment by stefnats** [comment]
Thanks, Nicolas!

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
