### ISSUE TITLE
module browserSynch

### ISSUE THREAD

**Issue by spawn81** [nWidart/laravel-modules#793]
Hi,
first of all, I would to thank you for the awsome package.
I have a problem: I use mix.browserSynch, everything works fine if I edit the app, but it doesn't track any changes in the Module folder.
here is the main webpack.min.js

```
const mix = require('laravel-mix');
require('laravel-mix-merge-manifest');
mix.mergeManifest();
mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css');
mix.browserSync('http://localhost:8000');
```

and this is the automated generated webpack.min.js 

```
const mix = require('laravel-mix');
require('laravel-mix-merge-manifest');

mix.setPublicPath('../../public').mergeManifest();

mix.js(__dirname + '/Resources/assets/js/app.js', 'js/questionario.js')
    .sass( __dirname + '/Resources/assets/sass/app.scss', 'css/questionario.css');

if (mix.inProduction()) {
    mix.version();
}
mix.browserSync('http://localhost:8000');
    mix.options({
        hmrOptions: {
            host: 'localhost',
            port: 8000
        }
    })
```
Thank you for any advice on that

**Comment by nWidart** [comment]
Hello,

Sorry, I haven't used this feature, don't really know how it works.

**Comment by ppmathis** [comment]
If anyone else stumbles across this issue and wants to get Browsersync working, the trick is to explicitly specify the file paths which should be monitored, e.g.:

```js
mix.browserSync({
    files: [
        'app/**/*.php',
        'modules/**/*.php',
        'resources/views/**/*.php',
        `${Config.publicPath || 'public'}/**/*.(js|css)`,
    ],
})
```

With the exception of `modules/**/*.php` (which has been added to support projects using this repository) all paths were taken from the [Laravel Mix repository](https://github.com/JeffreyWay/laravel-mix/blob/73d0fa424221602de251379e382209186fdbda22/src/components/Browsersync.js#L54-L58) where the default Browsersync configuration resides.
