### ISSUE TITLE
Module not reading vendor files inside views

### ISSUE THREAD

**Issue by poseso** [nWidart/laravel-modules#794]
Hello, I am using Arcanedev Log viewer:
https://github.com/ARCANEDEV/LogViewer

The problem I'm facing is that it's not reading the view files i have under Modules\MyModule\Resources\views\vendor, it keeps reading the one from the package itself, I want to know if I need to do something to override  the views from the package, so I can customize it?

Thank you

**Comment by nWidart** [comment]
You can check how modules views are loaded in the `registerViews` method of your module service provider. 
There you can adjust based on your needs.

**Comment by poseso** [comment]
When I  php artisan publish:vendor, it creates a vendor folder under rootDirectory/resources/views/vendor/log-viewer which i can customize, but if I put that vendor folder inside Modules\MyModule\Resources\views\vendor any customization i make doesn't reflect in the view, it's like it doesn't exists, I can call any view inside my module and include it for ex: @include('core::includes.partials.messages') and works great, but its how to override packages vendors views inside my module?

**Comment by nWidart** [comment]
You can't do that, unless you own the package. Packages won't expect views to be in your modules folder.

**Comment by poseso** [comment]
it's weird because then packages won't expect views to be either under root_folder/resources/views/vendor, if i delete the vendor folder from root_folder/resources/views/vendor it reads the one from root_folder/vendor/package, and if I copy it to  root_folder/resources/views/vendor/package it can be customize, so I don't understand why it cannot be read from Modules\MyModule\Resources\views\vendor, if there is now way let me know so I can close this, and thank you for your quick response!

**Comment by nWidart** [comment]
I'm confused to what you want. You can use other package's views as always.

**Comment by poseso** [comment]
I want to override packages views

**Comment by nWidart** [comment]
You can do that the way the packages document to do it.

**Comment by poseso** [comment]
okay

**Comment by abhishek-pokhriyal** [comment]
> You can't do that, unless you own the package. Packages won't expect views to be in your modules folder.

@nWidart I also ran into this problem and it so happens that I own the package! 


```php
<?php

namespace Vendor\Package;

use Illuminate\Support\ServiceProvider;

class PackageServiceProvider extends ServiceProvider
{
    // ...

    public function register()
    {
        // ...
        $this->loadViewsFrom(__DIR__ . '/../resources/views', 'package');
    }

    // ...
}
```
