### ISSUE TITLE
Module url not viewing page

### ISSUE THREAD

**Issue by imamideb** [nWidart/laravel-modules#795]
Hi,
I have installed the module package according to your instructions but after creating a "test" module, im unable to view it while accessing the path at http://mydomain.com/test
The page says: the url or page cannot be found.
Can you let me know what im missing?
Thanks
PS1 - I can see the "test" folder being created under "modules" folder.
PS2 - I have also included psr4 under "autoload" in composer.json and ran the last composer command aswell.

**Comment by nWidart** [comment]
Hi, 

Did you create a route for this url in this test module?

**Comment by imamideb** [comment]
There is already a route created when I have created the "test" module. Is that not enough?

**Comment by nWidart** [comment]
Should be yes, did you check the routes service provider? Is it called? Check the controller, etc.

**Comment by imamideb** [comment]
Im unable to understand. Should I upload the .zip file?
