### ISSUE TITLE
Module within and remove artisan cmds

### ISSUE THREAD

**Issue by imamideb** [nWidart/laravel-modules#796]
Hello,
I have 2 questions:
1. Is it possible to have multiple modules within 1 module? (Yes) How?
2. Your artisan cmd creates a bunch of things. I just dont want to create DB files. Is it possible? (Yes) How?
Thanks

**Comment by nWidart** [comment]
Hi,

1. No, it's not possible to have submodules
2. The `module:make` command has a `--plain` flag which will generate much fewer files.
