### ISSUE TITLE
On linux can not access modules's route 

### ISSUE THREAD

**Issue by aifeigao** [nWidart/laravel-modules#797]
Hi,
I just started using Laravel-modules for the last few days and I have problem on URL routing:

Local can work well,  but on our test linux can not work.    A moudle module cannot be loaded in a Linux environment. Access route 404 under a moudle 

PHP version | PHP/7.1.17
-- | --
Laravel version | 5.8.27

**Comment by aifeigao** [comment]
server {
        listen  2001;  
	set $root_path '/data/webapps/mobdata_admin/public';  
	root $root_path;   
	index index.php index.html index.htm;  
 	try_files $uri $uri/ @rewrite;

        location @rewrite {
                rewrite ^/(.*)$ /index.php?_url=/$1;
        }	
	location ~ \.php {    
	        fastcgi_pass 127.0.0.1:7171;  
	        fastcgi_index /index.php;    
                fastcgi_split_path_info       ^(.+\.php)(/.+)$;  
		fastcgi_param APP_ENV test;
	        fastcgi_param PATH_INFO       $fastcgi_path_info;  
                fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;  
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;  
		include                       fastcgi_params;
	}  	  
	location ~* ^/(css|img|js|flv|swf|download)/(.+)$ {  
                root $root_path;  
	}  	  
	location ~ /\.ht {  
                deny all;  
	}  
    }

**Comment by nWidart** [comment]
did you autoload your module?
Did you try to `dd()` inside the route?
