### ISSUE TITLE
Permissions to Module Json

### ISSUE THREAD

**Issue by Morpheons** [nWidart/laravel-modules#798]
Hello,
I'm having a permissions problem with module.json access.

 `file_put_contents(/var/www/e2hcms/Modules/Catalogue/module.json): failed to open stream: Permission denied`

I use a raspeberry pi3 B +.
My user is pi@192.168.1.20
when I activate or deactivate the module. the state changes and the owner of the file becomes user: root and the group: root
while my access is user: pi and group: www-data

What should I do to fix this problem?

Thanks for your help.

**Comment by nWidart** [comment]
This doesn't seem related to this package. Did you try to change the permissions of that file?

**Comment by Morpheons** [comment]
yes I changed the right with the order
sudo chown -R 775 * of the directory and I modify the user and the group
masi to cahque fosi that I activate or I descendative it gives the user root and the group root

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
