### ISSUE TITLE
Mixing using modules in Laravel

### ISSUE THREAD

**Issue by siddheshr** [nWidart/laravel-modules#799]
Created module and adding js and css files in Modules/webpack.js. I had some global js and css files which i induced in global/webpack.js. After running npm run watch only js which are in global/webpack.js are minified. Js files from modules/webpacks are not minified. No module_name.js and module_name.cs file is created.

Global webpack.mix.js
let mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

/* Allow multiple Laravel Mix applications*/
require('laravel-mix-merge-manifest');
mix.mergeManifest();

mix.js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css');

mix.styles([
    'admin/vendor/bootstrap/css/bootstrap.css',
    'admin/vendor/animate/animate.css',
    'admin/vendor/font-awesome/css/all.min.css',
    'admin/vendor/magnific-popup/magnific-popup.css',
    'admin/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.css',
    'admin/vendor/pnotify/pnotify.custom.css',
    'admin/css/theme.css',
    'admin/css/custom.css',
], 'public/css/all.css');

mix.scripts([
    'admin/vendor/jquery/jquery.js',
    'admin/vendor/jquery-browser-mobile/jquery.browser.mobile.js',
    'admin/vendor/jquery-cookie/jquery.cookie.js',
    'admin/master/style-switcher/style.switcher.js',
    'admin/vendor/popper/umd/popper.min.js',
    'admin/vendor/bootstrap/js/bootstrap.js',
    'admin/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js',
    'admin/vendor/common/common.js',
    'admin/vendor/nanoscroller/nanoscroller.js',
    'admin/vendor/magnific-popup/jquery.magnific-popup.js',
    'admin/js/custom.js',
    'admin/js/theme.js',
    'admin/js/theme.init.js',
    'admin/js/examples/examples.wizard.js',
    'admin/vendor/modernizr/modernizr.js',
    'admin/master/style-switcher/style.switcher.localstorage.js'
], 'public/js/all.js');

This is my module webpack.mix.js
const mix = require('laravel-mix');
require('laravel-mix-merge-manifest');

mix.setPublicPath('../../public').mergeManifest();

mix.js(__dirname + '/Resources/assets/js/app.js', 'js/formwizard.js')
    .sass(__dirname + '/Resources/assets/sass/app.scss', 'css/formwizard.css');

mix.scripts(
    ['admin/vendor/jquery-validation/jquery.validate.js',
        'admin/vendor/bootstrap-wizard/jquery.bootstrap.wizard.js',
        'admin/vendor/pnotify/pnotify.custom.js'
    ], 'js/formwizard.js');

if (mix.inProduction()) {
    mix.version();
}

What am i missing

**Comment by nWidart** [comment]
I haven't used this so can't help you with this.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
