### ISSUE TITLE
laravel collective dependency

### ISSUE THREAD

**Issue by spescina** [nWidart/laravel-modules#8]
I see in the main service provider the `registerHtml` method. Am I wrong or It's never used? Laravel Collective dependency is there for a legacy requirement?

**Comment by nWidart** [comment]
Looks like it's not used yes.

**Comment by spescina** [comment]
So do you plan to remove it from the package?

**Comment by nWidart** [comment]
Maybe, why does it matter to you ?

Pull requests are open fyi.

**Comment by spescina** [comment]
Cause my app depends on Laravel\Collective so I'm trying to understand if duplicate the requirement or not.
