### ISSUE TITLE
Problem with protocol-agnostic asset url and e-mails

### ISSUE THREAD

**Issue by mfcanovas** [nWidart/laravel-modules#800]
I have a "communication" module which is responsible for all the communication stuff.

I'm trying to use my company logo in an e-mail template using the asset url:
```
<tr>
    <td class="header">
        <a href="{{ $url }}"><img src="{{ Module::asset('communication:images/logo.png') }}" alt="{{ config('app.name') }}" style="margin-top:10px; margin-bottom:0;" height="60" border="0"></a>
    </td>
</tr>
```
Module::asset generates a protocol-agnostic url (//my.host/modules/communication/images/logo.png).

This kind of url does not work well with some e-mail clients and 3rd party services like Sendgrid (wich has an option to convert external images to base64 embeded images).

As seen on 
https://github.com/nWidart/laravel-modules/blob/d7cf6180312c5fe0fb07f7e18e8cad539d56d149/src/FileRepository.php#L547, 
protocol is always removed from asset url, so the only workaround I've found is to concat the protocol to the generated asset url. But it doesn't seem very nice:

```
<tr>
    <td class="header">
        <a href="{{ $url }}"><img src="https:{{ Module::asset('communication:images/logo.png') }}" alt="{{ config('app.name') }}" style="margin-top:10px; margin-bottom:0;" height="60" border="0"></a>
    </td>
</tr>
```

**Comment by nWidart** [comment]
Hi,

Interesting use-case, I think what you can do too is create a new method on the Module class using the `Macroable` trait.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
