### ISSUE TITLE
Module composer dependencies and how they work

### ISSUE THREAD

**Issue by robertdrakedennis** [nWidart/laravel-modules#801]
HI there,

I'm currently using Modules for a open source project, it heavily uses modules for other users to extend and add to my project with how they see fit. That being said, would it be a good idea / recommended to allow modules composer dependencies to install to the root vendor folder? Or should they install to each respective module? Thanks for any advice or solutions.

**Comment by nWidart** [comment]
Hi,

As far as I know, modules have to install their dependencies in the root vendor folder for composer to pick them up.
The moment you want dependencies in the module's vendor folder is when you run tests for a module in CI for instance.

**Comment by robertdrakedennis** [comment]
I appreciate the information, that's all I needed. Thank you!
