### ISSUE TITLE
Session flash message problem

### ISSUE THREAD

**Issue by Todyxe** [nWidart/laravel-modules#805]
Hello,

Excuse my English I am French. I currently have a problem, having developed a module, I wanted via a POST method to use this code: `return redirect ()->back()->with (['alert' => 'danger', 'message' = > 'Error']); `The problem is that no flash session is sending .. so it does not send me anything at all ..

thank you,
Good evening to you.

**Comment by nWidart** [comment]
Hi,

I don't think this is related to this package.
The laravel documentation has more information on how to achieve this.

**Comment by StringKe** [comment]
> Hello,
> 
> Excuse my English I am French. I currently have a problem, having developed a module, I wanted via a POST method to use this code: `return redirect ()->back()->with (['alert' => 'danger', 'message' = > 'Error']); `The problem is that no flash session is sending .. so it does not send me anything at all ..
> 
> thank you,
> Good evening to you.

```php
return back()->with (['alert' => 'danger', 'message' = > 'Error']);
```
