### ISSUE TITLE
I put CSS file under the module，How should I quote？Can asset() be used?

### ISSUE THREAD

**Issue by mengyonghang** [nWidart/laravel-modules#809]
I put CSS file under the Modules，How should I quote？Can asset() be used?
I make the Modules --Web,Create folders /Modules/Web/Public/css/index.css
How should I quote it in my views? please help me,Thank you very much.

at first run the commands 
`php artisan module:publish Web`

I use
` {{ Module::asset('web:Public/css/index.css') }} `
it can make the url  //127.0.0.1:8003/modules/web/Public/css/index.css
but 404 error。

**Comment by nWidart** [comment]
Hi,

You should publish these assets in the public folder, and then use `asset()` to reference them.
There's a module publish command to do this.

**Comment by mengyonghang** [comment]
> 嗨，
> 
> 您应该在公用文件夹中发布这些资产，然后使用`asset()`它们来引用它们。
> 有一个模块发布命令来执行此操作。

i used edition is v2,my laravel is 5.5.
i see theArticle  https://github.com/nWidart/laravel-modules/issues/151，
Do the same， but not ok。。。

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by faadmin** [comment]
Hello nWidart,
I am able to publish assets in the public folder but I need to type-in /public in my url in-order to get the complete url; though I have remove the /public from my url.
Can you please help me on this.
Thanks

**Comment by imamideb** [comment]
Hello nWidart,
I am able to publish assets in the public folder but I need to type-in /public in my url in-order to get the complete url; though I have remove the /public from my url.
Can you please help me on this.
Thanks

**Comment by nWidart** [comment]
You need to configure nginx/apache to point the directory root, to /public. You can find information about this on google.
