### ISSUE TITLE
module not found after change the modules path in configuration 

### ISSUE THREAD

**Issue by mahmouddev** [nWidart/laravel-modules#81]
I created some modules by default structure in Modules directory
then i change the config to create the modules in workbench directory

`'modules' => base_path('workbench'),`
 then 

`php artisan module:list`

all modules in Modules directory no found 

@nWidart is there any solution for that ??

**Comment by lchoate** [comment]
I just solved a similar problem moving from my development machine (Mac) to an Amazon Ec2 instance (ubuntu). If you have upgraded from the defunct pingpong package, know that for whatever reason this fork is sensitive to directory case.

When running pingpong, my directory worked fine as /modules/SomeModule
But after moving this fork into our test server (ubuntu EC2) I needed to (at least temporarily) create a symbolic link from modules to Modules with:

`ln -s modules Modules`

Don't forget to do a `composer dumpautoload` to pick up your modules.

You can test to see exactly what path you're looking for by running `php artisan tinker`
then

    Module::getScanPaths();
You should get back:

    => [
        "/var/www/lms-laravel/Modules/*",
    ]

See how "Modules" is now capitalized? I don't why that happened, but If you see that, it's a case sensitivity issue. Try the symbolic link. If that corrects the problem, we'll need to understand why a composer.json that autoloads like this:

    "psr-4": {
        "App\\": "app/",
        "Modules\\": "modules/"
    },

doesn't find the modules path.
