### ISSUE TITLE
Linux cannot access modules ；BUG

### ISSUE THREAD

**Issue by 583128870** [nWidart/laravel-modules#810]
No way to load  module.json;

public function scan()
    {
        $paths = $this->getScanPaths();

        $modules = [];

        foreach ($paths as $key => $path) {
            **$manifests = $this->app['files']->glob(str_replace('\\','/',"{$path}/module.json"));**

**Comment by nWidart** [comment]
Hi,

I haven't had any issues with this, applications run in production, on linux successfully.

What exactly doesn't work? Did you check your file permissions? The user:group?

**Comment by StringKe** [comment]
@nWidart I uploaded the entire project to my centos server, the modules router didn't work, the page was always 404 and I couldn't find the route.

**Comment by StringKe** [comment]
@nWidart The module I created on mac os is uppercase, but the module I created on centos is lowercase.

**Comment by nWidart** [comment]
I see. Don't create modules with case differences for this reason. 👍
