### ISSUE TITLE
vendor dirs within module?

### ISSUE THREAD

**Issue by baradhili** [nWidart/laravel-modules#811]
I'm building a module encapsulating the spatie/laravel-backup with a GUI
I'm wondering how I tell Laravel to find the vendor packages within a module - I need for the spatie 'backup:run' artisan command to be visible..

**Comment by nWidart** [comment]
You shouldn't try to do this. Add the dependencies to your project compsoer file too.

You can check out "composer merge plugin" for something automated too.

**Comment by narwy** [comment]
There's no reason you'd ever have two vendor locations, the autoloader needs to pick the packages up from your root vendor folder and the composer.json file.

**Comment by baradhili** [comment]
yeah I know.. teh reason for it is that Akaunting uses modules, and they also use it to enable an "app store" I did want to build a backup module for the app store... looks like I basically have to unpackage spatie's package and integrate it directly...

**Comment by nWidart** [comment]
No you don't have to copy spatie's package. You can require it like any other package and use it in your module.

**Comment by baradhili** [comment]
Yup, but I can't push it into the main Akaunting for a user without
some intervention - so if I have a end user who simply clicks on "add
app" within Akaunting - nothing happens :| since Akaunting doesn't run
composer install...

On Mon, 26 Aug 2019 at 17:23, Nicolas Widart <notifications@github.com> wrote:
>
> No you don't have to copy spatie's package. You can require it like any other package and use it in your module.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Bret Watson
Director
IT Interim Management Pty Ltd T/A TICM
Mob: +61 (0)41 33 03 840
Email:bret@IT-Interim.Management
"The contents of this e-mail transmission are intended solely for the
named recipient(s), may be confidential, and may be privileged or
otherwise protected from disclosure in the public interest. The use,
reproduction, disclosure or distribution of the contents of this
e-mail transmission by any person other than the named recipient(s) is
prohibited. If you are not a named recipient please notify the sender
immediately."

**Comment by IrajAzarvand** [comment]
Hey Nicolas, hope you doing well.
I'm new to laravel project and also your modules package.
wondering how can i reuse a module that i've created in one of my projects in another one!?
tnx. and good luck.

**Comment by MIS-Center** [comment]
this is a really good point... 
I have developed a module that needs PayPal package, but I am inforced to add this package inside root vendor instead of the vendor of the module itself !
anyone can suggest a solution?
