### ISSUE TITLE
[Bug] Default modules incompatible with route:cache command

### ISSUE THREAD

**Issue by OwenMelbz** [nWidart/laravel-modules#815]
Hi, Would just like to say thanks for the work so far, is my first time using the package and has been a good experience, however I've now run into an issue which there seems to be a few similar issues which have been previously closed - however not being addressed by the package maintainers.

How to reproduce:

- `php artisan module:make DemoModule`
- `php artisan view:cache`

--

It seems to be because the way the package scaffolds the service providers. e.g. it does:

```php
    public function registerViews()
    {
        $viewPath = resource_path('views/modules/demomodule');

        $sourcePath = __DIR__.'/../Resources/views';

        $this->publishes([
            $sourcePath => $viewPath
        ],'views');

        $this->loadViewsFrom(array_merge(array_map(function ($path) {
            return $path . '/modules/demomodule';
        }, Config::get('view.paths')), [$sourcePath]), 'demomodule');
    }
```

This seems to **assume** that `resource_path('views/modules/demomodule');` exists as when it runs 

```
$this->loadViewsFrom(array_merge(array_map(function ($path) {
    return $path . '/modules/demomodule';
}, Config::get('view.paths')), [$sourcePath]), 'demomodule');
```

This is the section that breaks the vanilla Laravel commands.

Would you please investigate into a way to making this compatible with the Laravel defaults?

Many thanks :)

**Comment by nWidart** [comment]
Feel free to suggest a solution in a pull request.

**Comment by OwenMelbz** [comment]
Sorry why has this just been closed? The bug is outstanding? Or is this package no longer maintained?

**Comment by nWidart** [comment]
Why would you think this package is not maintained anymore? Do you see commits recently? Do you see activity in issues or pull requests recently?

I closed the ticket because I don't use the view cache feature and currently do not have to the to figure this one out.
I can leave it open for others to take a look though, I'll re-open it.

**Comment by ridwans2** [comment]
Keep update Widart , you are good man

**Comment by rabol** [comment]
In the service provider of the module e.g. BlogServiceProvider, there is a method called registerViews()

in that method there is a call to loadViewsFrom(), the default one parses an array, change that to:

$this->loadViewsFrom($sourcePath, 'blog');

$sourcePath is also generated' in the registerViews() method

I'm not really sure why passing an array does not work

then:
php artisan view:clear
php artisan view:cache

and your views should now be cached

**Comment by rabol** [comment]
Unfortunately there is no artisan command to publish the views, that would have been another solution

**Comment by rabol** [comment]
have a look at https://github.com/nWidart/laravel-modules/issues/899

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
