### ISSUE TITLE
error class name not recognized when installing package through module`s composer

### ISSUE THREAD

**Issue by faniuta** [nWidart/laravel-modules#819]
I created a module with Laravel Module and I want to install a package in a this module. The package was installed in a module's vendor but the problem is that its class is not defined somewhere else in the project. 

Here is my composer.json : 

```json
{
    "name": "nwidart/audit",
    "description": "",
    "authors": [
        {
            "name": "Nicolas Widart",
            "email": "n.widart@gmail.com"
        }
    ],
    "extra": {
        "laravel": {
            "providers": [
                "Modules\\Audit\\Providers\\AuditServiceProvider"
            ],
            "aliases": {
                
            }
        }
    },
    "autoload": {
        "psr-4": {
            "Modules\\Audit\\": "Modules/Audit/"
        }
    },
    "require": {
        "owen-it/laravel-auditing": "^9.2",
    }
}
```

**Comment by nWidart** [comment]
hi,

You need to require the package in the root project too.

**Comment by faniuta** [comment]
I used that in the root and it worked fine, but the problem is that I wanted to use this module in another project with all package's dependencies but with your approach I have to install all of its package dependencies individually. Is there any solution for this issue?

**Comment by nWidart** [comment]
Yes, add the dependency in both places. You can also look up `composer merge plugin`.

**Comment by faniuta** [comment]
thanks for the help. for those who have the same problem here is the sulotion
https://github.com/wikimedia/composer-merge-plugin

just note :
`{
    "require": {
        "wikimedia/composer-merge-plugin": "dev-master"
    },
    "extra": {
        "merge-plugin": {
            "include": [
                "composer.local.json",
                "extensions/*/composer.json"
            ],
            "require": [
                "submodule/composer.json"
            ],
            "recurse": true,
            "replace": false,
            "ignore-duplicates": false,
            "merge-dev": true,
            "merge-extra": false,
            "merge-extra-deep": false,
            "merge-scripts": false
        }
    }
}`

**Comment by nWidart** [comment]
Cool, I'll close this then. 👍
