### ISSUE TITLE
Force Drop

### ISSUE THREAD

**Issue by narwy** [nWidart/laravel-modules#820]
```
   MongoDB\Driver\Exception\CommandException  : a collection 'funder.batches' already exists

  at /Users/narwy/Desktop/GitHub/php-app/vendor/mongodb/mongodb/src/Operation/CreateCollection.php:205
    201|         if (isset($this->options['writeConcern']) && ! \MongoDB\server_supports_feature($server, self::$wireVersionForWriteConcern)) {
    202|             throw UnsupportedException::writeConcernNotSupported();
    203|         }
    204| 
  > 205|         $cursor = $server->executeWriteCommand($this->databaseName, $this->createCommand(), $this->createOptions());
    206| 
    207|         if (isset($this->options['typeMap'])) {
    208|             $cursor->setTypeMap($this->options['typeMap']);
    209|         }

  Exception trace:

  1   MongoDB\Driver\Server::executeWriteCommand("funder", Object(MongoDB\Driver\Command), [])
      /Users/narwy/Desktop/GitHub/php-app/vendor/mongodb/mongodb/src/Operation/CreateCollection.php:205

  2   MongoDB\Operation\CreateCollection::execute(Object(MongoDB\Driver\Server))
      /Users/narwy/Desktop/GitHub/php-app/vendor/mongodb/mongodb/src/Database.php:209
```

Using:
`module:migrate-refresh Funder`
Then
`module:seed Funder`
Doesn't drop the current collections using MongoDB, Everything else seems to work fine, but even using the `--force` tag doesn't have any affect either.

**Comment by nWidart** [comment]
Hi,

As you can see here:

https://github.com/nWidart/laravel-modules/blob/master/src/Commands/SeedCommand.php#L143-L145

The force flag is directly sent to laravel. I would check this with laravel.

**Comment by narwy** [comment]
Hey,

If I do:
`php artisan db:seed --class="Modules\Funder\Database\Seeders\FunderContactsTableSeeder" --force`

It works fine?

**Comment by narwy** [comment]
What about the `module:migrate-refresh` what command is that running to pass params?

**Comment by nWidart** [comment]
is that a question?

If so you could try to see what it doesn't in the module seed command.

**Comment by nWidart** [comment]
You can view the code of every command.

**Comment by narwy** [comment]
Can't find anything referencing to `migrate:fresh` not refresh?

**Comment by nWidart** [comment]
What is this then? https://github.com/nWidart/laravel-modules/blob/master/src/Commands/MigrateRefreshCommand.php

**Comment by narwy** [comment]
https://laravel.com/docs/5.8/migrations

`php artisan migrate:fresh` and `php artisan migrate:fresh --seed`

There's no support for `fresh` then?

**Comment by nWidart** [comment]
There's no fresh command in this package no.

**Comment by narwy** [comment]
Are we okay with me doing a PR for it?

**Comment by nWidart** [comment]
That'd be nice yeah. 👍

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
