### ISSUE TITLE
ABOUT ROUTES

### ISSUE THREAD

**Issue by Amitkpr** [nWidart/laravel-modules#822]
hi i have intalled version 5 in laravel 5.8 but. I have problem with api routes otherwise web routes are working fine. please help me how can solve that.
Thanks

**Comment by nWidart** [comment]
Hi,

You need to find out if your routes are loaded, for example in your route service provider.

**Comment by Amitkpr** [comment]
where do i need to load my routes in module service provider or my main laravel service provider, getting confused with them, please help my out. Thanks

**Comment by Amitkpr** [comment]
Thanks @nWidart routes problem is now solved. I have loaded routes in main laravel routes service provider instead of module's routes service provider.
