### ISSUE TITLE
Can not seed module

### ISSUE THREAD

**Issue by quienti** [nWidart/laravel-modules#823]
Hi !

I have found a problem, I can not seed modules with command
`artisan module:seed`

Nothing are seed

I have found the problem

https://github.com/nWidart/laravel-modules/blob/master/src/Commands/SeedCommand.php#L165

You need to change `$config->getNamespace()` by `$seederPath` to solve the problem

Thank you !

Laravel: 6.0.1
Modules : 6.0-dev

**Comment by nWidart** [comment]
Hello,

Thanks for reporting, I've fixed the issue.
