### ISSUE TITLE
Cannot create module

### ISSUE THREAD

**Issue by taqie** [nWidart/laravel-modules#824]
Hello, 
after update to 5.1.0 i have an error at creating module
![image](https://user-images.githubusercontent.com/19823642/64591814-f2a03f00-d3aa-11e9-9bf0-50bd031ff64d.png)

**Comment by nWidart** [comment]
Hi,

Can you run `php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider" --force`, and test again?

**Comment by mikemand** [comment]
Make sure you compare your config file against [the one for the release you are upgrading to](https://github.com/nWidart/laravel-modules/blob/5.1.0/config/config.php).

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
