### ISSUE TITLE
cant generate any file after creating module

### ISSUE THREAD

**Issue by MetaiR** [nWidart/laravel-modules#825]
this issue contains the same problem as #530 but in my case, I am using laravel 6.0 and module 5.1 and I did add ```"Modules\\": "Modules/"``` to my composer.json (in autoload section)

what is happening exactly:

1. I created a brand new laravel 6 project
2. modules version 5.1 has been installed
3.  ```"Modules\\": "Modules/"``` is added to my composer.json
4. created a new module named Custom
5. try to generate a new service provider by ```php artisan module:make-provider MyCustomServiceProvider Custom```
6. getting this error:
```
Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Modules\Custom\Providers\CustomServiceProvider' not found

  at F:\git\laravel-6\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:208
    204|      * @return \Illuminate\Support\ServiceProvider
    205|      */
    206|     public function createProvider($provider)
    207|     {
  > 208|         return new $provider($this->app);
    209|     }
    210| }
    211|

  Exception trace:

  1   Illuminate\Foundation\ProviderRepository::createProvider("Modules\Custom\Providers\CustomServiceProvider")
      F:\git\laravel-6\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:144

  2   Illuminate\Foundation\ProviderRepository::compileManifest()
      F:\git\laravel-6\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:61

  Please use the argument -v to see more details.
```

**Comment by nWidart** [comment]
that looks like you modules weren't loaded. Make sure they're loaded with composer. Run a dump autoload too.

**Comment by MetaiR** [comment]
yeah it worked after a dump-autoload but the funny thing is I tried to run dump-autoload and that time it didn't work and the command not executed properly and after closing and opening phpstorm the command is executing now

**Comment by nWidart** [comment]
Great to hear! 👍

**Comment by luisamerico32** [comment]
It worked for me just when I added manually on composer.json the psr-4 `"Modules\\": "Modules/"`. Then I could run the `composer dump-autoload`.
