### ISSUE TITLE
Master composer.json has Laravel 5.8 not 6.0

### ISSUE THREAD

**Issue by poseso** [nWidart/laravel-modules#828]
When I do: composer require nwidart/laravel-modules 

Carloss-iMac:laravel-6-boilerplate poseso$ composer require nwidart/laravel-modules
Using version ^5.1 for nwidart/laravel-modules
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing nwidart/laravel-modules (5.1.0): Downloading (100%)         
Writing lock file
Generating optimized autoload files

when i check the composer.json under require-dev is requiring     "laravel/framework": "5.8.*", instead of 6.0 as i can see on the master branch.

Do I need to do something else for bringing 6.0 compatibility ?

**Comment by poseso** [comment]
closing this:

added composer require nwidart/laravel-modules:dev-master

and now it works

**Comment by nWidart** [comment]
Hi, you need to require `6.0-dev` as indicated on the readme. 6.0 will be tagged this week.
