### ISSUE TITLE
[FEATURE REQUEST] nested modules

### ISSUE THREAD

**Issue by georgehristov** [nWidart/laravel-modules#829]
I have issued the command to generate module Utils/TestModule for instance and the files are generated correctly but the the generator exits with error
`Module [Utils/RecordBrowser] does not exist!`
It could be great if the module name can be resolved to Utils_TestModule for instance and modules can be nested in the folder structure with appropriate autoloading

**Comment by nWidart** [comment]
Hello,

I do not think having nested modules is a good idea hence why it's not supported.
