### ISSUE TITLE
same table name of different modules got conflict

### ISSUE THREAD

**Issue by badrul1329** [nWidart/laravel-modules#831]
When wants to create same table name like settings in different modules, it shows the error...

> Cannot declare class CreateSettingsTable, because the name is already in use

**Comment by nWidart** [comment]
Hi,

This is expected behaviour in laravel. Tables with the same name can't exist in any data source that I know of.

**Comment by badrul1329** [comment]
I have multiple database according to multiple module, and there may be
same table name like settings in multiple modular database hence the error
occurred when i create same settings migration file in different module and
tried to migrate, the error occurred but my same name table name is in
different module
