### ISSUE TITLE
Issue upgrading: Class name must be a valid object or a string in LaravelModulesServiceProvider.php

### ISSUE THREAD

**Issue by extricate** [nWidart/laravel-modules#833]
Hi there, I'm encountering the following issue whilst upgrading to Laravel v6/Laravel-modules v6.:

Upgraded the composer.json to include the latest "nwidart/laravel-modules": "^6.0".

Upon upgrading, after running the composer update I get the following error:
` Symfony\Component\Debug\Exception\FatalThrowableError  : Class name must be a valid object or a string

  at /vendor/nwidart/laravel-modules/src/LaravelModulesServiceProvider.php:59
    55|         $this->app->singleton(Contracts\ActivatorInterface::class, function ($app) {
    56|             $activator = $app['config']->get('modules.activator');
    57|             $class = $app['config']->get('modules.activators.' . $activator)['class'];
    58|
  > 59|             return new $class($app);
    60|         });
    61|         $this->app->alias(Contracts\RepositoryInterface::class, 'modules');
    62|     }
    63| }

  Exception trace:

  1   Nwidart\Modules\LaravelModulesServiceProvider::Nwidart\Modules\{closure}(Object(Illuminate\Foundation\Application), [])
      /vendor/laravel/framework/src/Illuminate/Container/Container.php:800

  2   Illuminate\Container\Container::build(Object(Closure))
      /vendor/laravel/framework/src/Illuminate/Container/Container.php:682`

Unfortunately, due to this error I'm unable to run the upgrade command. Anybody have any idea on how to successfully upgrade? Thanks in advance.

**Comment by nWidart** [comment]
Hi,

Did you republish the configuration? If not run the following:
```
php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"
```

**Comment by extricate** [comment]
Hiya nWidart,
Thanks for the swift reply. I've been desperately trying to forcefully republish the config -- however keep running into composer errors. No clue how to circumvent the composer-autoloader from being broken.

**Comment by nWidart** [comment]
I see, in that case you can compare the original: https://github.com/nWidart/laravel-modules/blob/master/config/config.php

You could copy the whole content and paste it in your config of laravel-modules.

**Comment by extricate** [comment]
Yea I'll just try that for now, thanks -- I'll keep you posted.

**Comment by extricate** [comment]
Manually resetting the config seems to have done the trick, merci!

**Comment by nWidart** [comment]
Awesome! 👌

**Comment by illyaAvdeuk** [comment]
Hi, I've got the same issue on laravel boilerplate app (https://github.com/rappasoft/laravel-boilerplate). Laravel 6.0, PHP 7.2.19 . Multiple extensions were installed before (guzzle, pretty routes etc).
Steps to reproduce:
`composer require nwidart/laravel-modules`
`php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"`
updated composer.json
`{
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Modules\\": "Modules/"
    }
  }
}`
than
`composer dump-autoload`
After trying to create module
`php artisan module:make Seo -v`
I'me getting:
` [stacktrace]
#0 /home/illya/laravel.loc/vendor/laravel/framework/src/Illuminate/Container/Container.php(800): Nwidart\\Modules\\LaravelModulesServiceProvider->Nwidart\\Modules\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#1 /home/illya/laravel.loc/vendor/laravel/framework/src/Illuminate/Container/Container.php(682): Illuminate\\Container\\Container->build(Object(Closure))
#2 /home/illya/laravel.loc/vendor/laravel/framework/src/Illuminate/Container/Container.php(630): Illuminate\\Container\\Container->resolve('Nwidart\\\\Modules...', Array)
#3 /home/illya/laravel.loc/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(768): Illuminate\\Container\\Container->make('Nwidart\\\\Modules...', Array)
#4 /home/illya/laravel.loc/vendor/laravel/framework/src/Illuminate/Container/Container.php(1246): Illuminate\\Foundation\\Application->make('Nwidart\\\\Modules...')
#5 /home/illya/laravel.loc/vendor/nwidart/laravel-modules/src/Commands/ModuleMakeCommand.php(39): Illuminate\\Container\\Container->offsetGet('Nwidart\\\\Modules...')
#6 [internal function]: Nwidart\\Modules\\Commands\\ModuleMakeCommand->handle()
#7 /home/illya/laravel.loc/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#8 /home/illya/laravel.loc/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /home/illya/laravel.loc/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#10 /home/illya/laravel.loc/vendor/laravel/framework/src/Illuminate/Container/Container.php(591): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#11 /home/illya/laravel.loc/vendor/laravel/framework/src/Illuminate/Console/Command.php(192): Illuminate\\Container\\Container->call(Array)
#12 /home/illya/laravel.loc/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#13 /home/illya/laravel.loc/vendor/laravel/framework/src/Illuminate/Console/Command.php(179): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 /home/illya/laravel.loc/vendor/symfony/console/Application.php(915): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /home/illya/laravel.loc/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(Nwidart\\Modules\\Commands\\ModuleMakeCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /home/illya/laravel.loc/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /home/illya/laravel.loc/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /home/illya/laravel.loc/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /home/illya/laravel.loc/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 {main}
"}
`

I tried to replace config/modules.php with https://github.com/nWidart/laravel-modules/blob/master/config/config.php - it didn't help. what could be causing the problem?

**Comment by nWidart** [comment]
Did you maybe cache the config?

**Comment by illyaAvdeuk** [comment]
Damn, you're right) shame on me and thanks) 
I'd recommend to add this and other issues to FAQ or to installation guide, I'm not the only messer who will face such problem.

**Comment by nWidart** [comment]
Cool 😄 
Yeah you're right, I'm thinking of improving the error message too.

**Comment by sampkme** [comment]
Facing same issue can help me on this?

**Comment by sampkme** [comment]
`   ErrorException 

  Trying to access array offset on value of type null

  at vendor/nwidart/laravel-modules/src/LaravelModulesServiceProvider.php:58
    54|             return new Laravel\LaravelFileRepository($app, $path);
    55|         });
    56|         $this->app->singleton(Contracts\ActivatorInterface::class, function ($app) {
    57|             $activator = $app['config']->get('modules.activator');
  > 58|             $class = $app['config']->get('modules.activators.' . $activator)['class'];
    59| 
    60|             if ($class === null) {
    61|                 throw InvalidActivatorClass::missingConfig();
    62|             }`

**Comment by nWidart** [comment]
The solution is explained in this ticket.

**Comment by sampkme** [comment]
I've compared the config.php but that's same as you provided in this ticket

**Comment by nWidart** [comment]
It can't since it's complaining about a missing key. Publish the configuration with `--force`, and flush your config cache.

**Comment by shubham-Xcube** [comment]
php artisan cache:clear
php artisan config:cache

worked for me :-)

**Comment by waleedmuaz2** [comment]
when I dump and die in the vendor file for debugging the code returning null I just replace the code of config https://github.com/nWidart/laravel-modules/blob/master/config/config.php in modules.php and run command 
`php artisan config:cache`  the error will resolve very quickly 

https://stackoverflow.com/users/11557508/waleed-muaz

**Comment by liam-milbel** [comment]
I was gradually upgrading an old Laravel 5.8 project up to current. Laravel 6 proved to be difficult due to this error. I had to actually cd into the `bootstrap/cache` directory and clear out cache manually as any artisan commands would throw the same error.
