### ISSUE TITLE
Module facade in scout config file

### ISSUE THREAD

**Issue by AurelienMendes** [nWidart/laravel-modules#834]
Hi @nWidart 
Hi everybody,

Since the framework is not fully booted when the configuration files are being read I'm can't use the Module facade (and the allEnabled() method) in my scout config file.

Do you see a way to have all the enabled Modules in my scout config file ?

Thanks

**Comment by nWidart** [comment]
Hi,

Hm, I wouldn't suggest using logic in configuration files.
You can create a service provider, that sets the configuration, and from there you can use the module facade.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
