### ISSUE TITLE
Incompatible signature on delete function

### ISSUE THREAD

**Issue by isecchin** [nWidart/laravel-modules#835]
Hi Nicolas,

I've just updated my projects to Laravel 6.0 and, consequently, have been updating all the third party packages that I was using as well, including yours (which is great, by the way, thank you very much).

Although I was scratching my head for a few hours since all my modules seemed like they just stopped working, I managed to reactivate them by running the `module:v6:migrate` command (I did not know I was supposed to do that and couldn't find any information about it, I just stumbled on this command and tried it and got it working, so maybe we should add something on the documentation/upgrade guides ? It could help others as well).

Anyhow, after I finished all the upgrades I needed and thought everything was working smoothly, I saw my worker.log file increasing its size and saw that there was an issue with the package that was causing an unwanted exception to be thrown.

Apparently, the commit d9d67d8c4fa8f82ce95b7bda5c7d3aad6f194534 added the signature of the `delete` method to the `RepositoryInterface`, but that signature differs from the one on the `FileRepository` class, causing the following exception:

`Declaration of Nwidart\Modules\FileRepository::delete($name): bool must be compatible with Nwidart\Modules\Contracts\RepositoryInterface::delete(string $module): bool`

**Comment by nWidart** [comment]
Hello,

Thank you for reporting the issue, I'll fix it now.
About the migrate command, it's mentioned in the changelog file: https://github.com/nWidart/laravel-modules/blob/master/CHANGELOG.md

Indeed it should also be mentioned in the docs so it's clear.

**Comment by isecchin** [comment]
Thanks for the quick response and fix, and sorry about the changelog, I really missed that on the update process !
