### ISSUE TITLE
Error routes in Laravel vapor

### ISSUE THREAD

**Issue by connectchurch** [nWidart/laravel-modules#836]
I deployed my application on the Laravel VAPOR. All modules are listed, but routes are not injected. Gives error 404 when request a route.

**Comment by nWidart** [comment]
Hi,

Sorry, I can't help you with vapor. I would assume it doesn't do anything with your routes.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by bhattraideb** [comment]
I am facing the same issue in ubuntu18.04/nginx. I am unable to see the routes defined for Admin Modules defined through **php artisan route:list** command.  I am getting this issue after deployed into DO. Everything is working fine in the local env. 

I am using fresh Laravel version 6.

**Comment by nWidart** [comment]
Could you make sure to commit the activator file? It's defined here: https://github.com/nWidart/laravel-modules/blob/master/config/config.php#L206

**Comment by bhattraideb** [comment]
Thanks @nWidart , This solved the issue.
