### ISSUE TITLE
Generator doesn't follow config when changing provider directory.

### ISSUE THREAD

**Issue by patrickcurl** [nWidart/laravel-modules#837]
Example: 

config: 
```php
[
    ...
    generator =>  [
        ...
        'provider' => ['path' => 'Base/Providers', 'generate' => true]
    ]
]
```

When I make the module it puts the files in the right place but module.json and composer.json point to App/ModuleName/Providers/ModuleProvider.php

Similarily a related issue is when RouteServiceProvider is in app/Blog/Base/Providers, it tries to point routes to ```__DIR__ . '/../Http/Routes/web.php'``` which should be 2 directories up now... I think it would be better to use ```(module_path('Account') . '/Http/Routes/web.php');```

The structure I'm going for is: 
```
|app
|--|Blog
|--|--|Base
|--|--|--|Events
|--|--|--|Notifications
|--|--|--|Providers
|--|--|--|Tests
|--|--|--|config.php
|--|--|Data
|--|--|--|Migrations
|--|--|--|Models
|--|--|--|Seeders
|--|--|Http
|--|--|--|Controllers
|--|--|--|Middleware
|--|--|--|Requests
|--|--|--|Routes
|--|composer.json
|--|module.json
```

**Comment by nWidart** [comment]
Hi,

Thank you for your patience.
Thank you for reporting this, I've fixed this here: https://github.com/nWidart/laravel-modules/commit/d2bbe192e105ff9030401e160e0c908e62f8206b

**Comment by nWidart** [comment]
And the second issue has been resolved here: https://github.com/nWidart/laravel-modules/commit/8b259fa847400140d4a459ba2640fc9970f93a2c

**Comment by nWidart** [comment]
Tagged as [6.2.0](https://github.com/nWidart/laravel-modules/releases/tag/6.2.0)
