### ISSUE TITLE
Extending native laravel commands

### ISSUE THREAD

**Issue by lexdewilligen** [nWidart/laravel-modules#842]
Why did you create your own commands instead of extending laravels default commands? As an example, your controller make command does not provide the --model, --resource, --invokable and --parent options. I've created a similar setup with modules but instead extended laravels commands to provide the same options laravel does. This is my resulting ModuleControllerMakeCommand:

```php
<?php

namespace App\Console\Commands;

use App\Traits\MakesForModules;
use Illuminate\Routing\Console\ControllerMakeCommand;

class ModuleControllerMakeCommand extends ControllerMakeCommand
{

	use MakesForModules;

    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'module:make:controller 
        {module : The name of the module} 
        {name : The name of the controller}
        {--m|model= : Generate a resource controller for the given model.}
        {--r|resource : Generate a resource controller class.}
        {--i|invokable : Generate a single method, invokable controller class.}
        {--p|parent : Generate a nested resource controller class.}
        {--api : Exclude the create and edit methods from the controller.}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a new module controller class';

	/**
	 * Get the stub file for the generator.
	 *
	 * @return string
	 */
	protected function getStub()
	{
		$stub = null;

		if ($this->option('parent')) {
			$stub = '/stubs/controller.nested.stub';
		} elseif ($this->option('model')) {
			$stub = '/stubs/controller.model.stub';
		} elseif ($this->option('invokable')) {
			$stub = '/stubs/controller.invokable.stub';
		} elseif ($this->option('resource')) {
			$stub = '/stubs/controller.stub';
		}

		if ($this->option('api') && is_null($stub)) {
			$stub = '/stubs/controller.api.stub';
		} elseif ($this->option('api') && ! is_null($stub) && ! $this->option('invokable')) {
			$stub = str_replace('.stub', '.api.stub', $stub);
		}

		$stub = $stub ?? '/stubs/controller.plain.stub';

		return __DIR__.$stub;
	}
}
```

Now, all I needed to change was the way some paths and namespaces were generated:

```php
<?php

namespace App\Traits;

use Illuminate\Support\Str;

trait MakesForModules
{
	/**
	 * Get the root namespace for the class.
	 *
	 * @return string
	 */
	protected function rootNamespace()
	{
		return config('modules.namespace') . '\\' . $this->argument('module') . '\\';
	}

	/**
	 * Get the root path for the class.
	 *
	 * @return string
	 */
	protected function rootPath()
	{
		return config('modules.paths.modules') . '/' . $this->argument('module');
	}

	/**
	 * Get the destination class path.
	 *
	 * @param  string  $name
	 * @param  string  $folder
	 * @return string
	 */
	protected function getPath($name, $folder = 'src')
	{
		$name = Str::replaceFirst($this->rootNamespace(), '', $name);

		return $this->rootPath() . '/' . $folder . '/' . str_replace('\\', '/', $name).'.php';
	}
}
```

Now, would you accept a PR implementing this? I could write it for you if you wish.

**Comment by nWidart** [comment]
Hi,

I like this idea. 👍 
I believe it wasn't done at the time, when laravel didn't expose this many options from the class.

If this can work for all commands similarly it'd be a nice improvement.

**Comment by lexdewilligen** [comment]
Ok, I'll submit the PR soon!

**Comment by lexdewilligen** [comment]
@nWidart, I've started refactoring the commands, starting with the ControllerMakeCommand of course. However, there will be some breaking changes since I'm following Laravel's standards. Could you check if this is fine by you? I've documented the changes nicely:

https://github.com/lexdewilligen/laravel-modules/commit/b1885de352ce242cd5f98777dd02ce0b8b545a05

Once I receive your confirmation, I'll go on refactoring the other commands.

**Comment by nWidart** [comment]
Thanks!
This looks like a lot more changes that mentioned above 😅 .

If there are breaking changes however we can't proceed with this, yet.

**Comment by lexdewilligen** [comment]
You could just release it as a major update right? I believe there should be some refactoring in the configuration too, for instance keeping `factories`, `Migrations` and `seeders` all lowercase (like laravel does). Also modules are very similar to packages of course, so maybe it should be a little more `src`-folder friendly. I'd be willing to help you of course, how do you think of these changes?

**Comment by nWidart** [comment]
They can be done yes, but I would prefer to wait until we're closer to the next major version of laravel.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
