### ISSUE TITLE
Class name must be a valid object or a string laravel 6

### ISSUE THREAD

**Issue by muhaned85** [nWidart/laravel-modules#843]
Symfony\Component\Debug\Exception\FatalThrowableError  : Class name must be a valid object or a string

  at C:\xampp\htdocs\blog\vendor\nwidart\laravel-modules\src\LaravelModulesServiceProvider.php:59
    55|         $this->app->singleton(Contracts\ActivatorInterface::class, function ($app) {
    56|             $activator = $app['config']->get('modules.activator');
    57|             $class = $app['config']->get('modules.activators.' . $activator)['class'];
    58|
  > 59|             return new $class($app);
    60|         });
    61|         $this->app->alias(Contracts\RepositoryInterface::class, 'modules');
    62|     }
    63| }

**Comment by nWidart** [comment]
When are you getting this error?

**Comment by muhaned85** [comment]
When create new module

**Comment by nWidart** [comment]
I can't reproduce this here. Which version of php are you using?

**Comment by muhaned85** [comment]
PHP Version 7.3.10

**Comment by efectn** [comment]
ı have this error .

**Comment by desyashasyi** [comment]
Anyone have solving the problem?

**Comment by nWidart** [comment]
A better error messages was added in [6.1](https://github.com/nWidart/laravel-modules/releases/tag/6.1.0)
