### ISSUE TITLE
Command Use module not working in docker container

### ISSUE THREAD

**Issue by skortabeast** [nWidart/laravel-modules#844]
Command Use module not working in docker container and all modules set disabled how I can set Enabled all modules with one command?
![image](https://user-images.githubusercontent.com/10978770/66140366-a5f6ff00-e60a-11e9-94ad-273d07dc4c54.png)
I try call command inside container but nothing

**Comment by nWidart** [comment]
Both of these features are depending on a disk, a file is written. 

I'm guessing something could be wrong with the setup of your docker container.


There's no command to set all modules to enabled built in. It's easy for you to create it however. Loop over all modules, and set them to enabled.

**Comment by skortabeast** [comment]
Command  module:use writes to modules_statuses.json in storrage / app?

**Comment by nWidart** [comment]
No that file is written by the activator.

Module used, writes in `storage/app/modules/module.used`

**Comment by skortabeast** [comment]
@nWidart strange, but I don't have this folder in my project 
![image](https://user-images.githubusercontent.com/10978770/66193498-57457580-e69b-11e9-82b9-5c8662a2dd1c.png)

**Comment by nWidart** [comment]
That's weird, I just used it again locally and the file was created.
