### ISSUE TITLE
Register Middleware Global

### ISSUE THREAD

**Issue by letuananh1873** [nWidart/laravel-modules#846]
Path: \Modules\Page\Http\Middleware\LanguageMiddleware::class in class I echo "Hello!"; die();

When I add this path via app\Http\kernel.php, it's working, show text "Hello!" -> https://gyazo.com/e59af775fd3f59f1fbf7f3147c6d01a4

But when I register via Modules/Page/Providers/PageServiceProvider.php
`
$router->aliasMiddleware('LanguageMiddleware', \Modules\Page\Http\Middleware\LanguageMiddleware::class)`;

It's not working, not show text "Hello!" -> https://gyazo.com/32df2073235f8a1e8cb7d53feea0459e

https://github.com/nWidart/laravel-modules/issues/175

Please help me.
Thank you so much!

**Comment by nWidart** [comment]
Hi,

I'm not sure you can register global middlewares anywhere.
You probably have to register in `app/http/kernel.php`, or define your own kernel.php.
