### ISSUE TITLE
migration in version 6 doesnt work

### ISSUE THREAD

**Issue by VeRJiL** [nWidart/laravel-modules#848]
Hi thanx for awesome package.
I was using the package v5 and it is perfect and working perfectly but yesterday i started a new project and I attempt to install the new version of the package which was v6 and after coping my modules from another project some of them has migrated perfectly but majority of them didn't.
I used "`php artisan migrate`" command and it did not migrate all of the migrations but then I used "`php artisan module:migrate ModuleName`" and It worked. but there is a problem, I am using config file for declaring table names and using that config address in the `Schema::create(config('ModuleName.tableNames.article), function() { ... }) `and the package does not recognize the config file in v6 while it is working fine in the v5.
the error message for migration the module with table names in config file says: cant create table ' '

**Comment by nWidart** [comment]
HI,

Did you run the migration command to migrate your modules to the v6 setup?
`php artisan module:v6:migrate`

**Comment by VeRJiL** [comment]
unfortunately I have a deadline to reach and I have forced to change the module version to v5. Don't close the issue, I will test it.
