### ISSUE TITLE
404 Errors

### ISSUE THREAD

**Issue by narwy** [nWidart/laravel-modules#849]
Hi,

v6 is throwing 404 errors on my production env, but localhost works fine.

Downgraded to v5.1 working again?

**Comment by nWidart** [comment]
Hi,

No idea why that would happen. You would have to debug it.

**Comment by kapil-gupta** [comment]
I was facing the same error. run  php artisan module:v6:migrate      after laravel upgrade

**Comment by narwy** [comment]
I ran the migrate command, made no difference.

**Comment by narwy** [comment]
Same docker environment, local and production, only difference is the I'm going through a proxy on AWS end. Any ideas @nWidart where to start the stack debug back to that?

**Comment by narwy** [comment]
#836 This could be related to this issue also, Vapor doesn't seem to be the issue.

This is just a standard docker containerised application also.

**Comment by ndhan93** [comment]
if you upgrade from 5.x, update your config also.
laravel-modules has new config for activator
I got same error before, update config and it's working

**Comment by 50shashwat** [comment]
The same issue happens even if i use laravel 5.8

**Comment by narwy** [comment]
Checked, nothing to do with the cache/configs. Clean install same issue.

**Comment by 50shashwat** [comment]
Somehow the new installation works fine but it only happens when it is used on another machine with git. Now the same issue keeps happening on all the Laravel versions > 5.6

**Comment by narwy** [comment]
@nWidart When a module is created is it cached against the url or anything like that?

**Comment by afanazmy** [comment]
You can check all module with `php artisan module:list`
If module disabled you can enable it with `php artisan module:enable {module_name}`

I think, in version 6 there is a bug when we clone our project because after running `composer install` all modules are disabled and we have to enable it first to use it.

**Comment by nWidart** [comment]
This isn't a bug, but a documented breaking change. You need to run `php artisan module:v6:migrate`

**Comment by vladamir** [comment]
Hi! I have the same issue, I have run `php artisan module:v6:migrate` many times, but anyway, with next deploy (composer install) I need to enable my modules again :(

**Comment by nWidart** [comment]
ah yes, you need to commit the file being generated: `storage/app/modules_statuses.json`, via the settings you can change its name and location if needed.

**Comment by vladamir** [comment]
wow, got it! Thank you!

**Comment by nWidart** [comment]
No problem 😄 
I'll try to document this as I understand it can be confusing.

**Comment by rmicheldev** [comment]
Hi
Same problem (Laravel 6 running on apache).
Locally it works but on my AWS it return 404.

Solution:

`php artisan module: list`
```
+ ------- + ---------- + ------- + ---------------------- ------- +
| Nome Status Ordem | Caminho
+ ------- + ---------- + ------- + ---------------------- ------- +
| Admin Desativado | 0 / var / www / dark / Módulos / Admin |
| Blog | Desativado | 0 / var / www / dark / Módulos / Blog |
| Usuário Desativado | 0 / var / www / dark / Módulos / Usuário |
+ ------- + ---------- + ------- + ---------------------- ------- +
```

An so, I run the command to enable the module again:

`php artisan module: enable administrador`

**Comment by narwy** [comment]
Is it better we remove the way this file is generated and look through the modules to check if they’re enabled instead? Most people are going to have issues with this as storage is on most people’s gitignore

**Comment by nWidart** [comment]
@narwy No, the whole point of this feature is to have this file generated.

**Comment by nWidart** [comment]
The activator file has been moved to the base path, giving it better visibility and not ignored by default in [6.1](https://github.com/nWidart/laravel-modules/releases/tag/6.1.0)

**Comment by narwy** [comment]
Thanks @nWidart
