### ISSUE TITLE
Catch Disabled Module?

### ISSUE THREAD

**Issue by SeoRoman** [nWidart/laravel-modules#85]
Maybe, I'm missing something, but I was wondering, if a module was "disabled" and the route was still attempted... is there anyway to catch that?

I noticed in the code in Repository.php that both register() and boot() only loaded from getOrdered() enabled() modules, so I would assume there would be no way to really catch that, but I was curious, if rather on the initial boot of the module instead of denying the route entirely, if it could check the module status when a route was being attempted and then have a "catch-all" to state that this module is disabled or w/e the user wanted to show?

Just a thought... Not really super important, but if I wanted to say make an "Auth" module, and then disable it for a time, there really isn't a way to show that I disabled that module to the users, without creating a whole new route and showing a custom page.

**Comment by nWidart** [comment]
There is no way to do this, out of the box that is. Since if the module is disabled no files inside it will be autoloaded.
