### ISSUE TITLE
Not run laravel modules

### ISSUE THREAD

**Issue by letuananh1873** [nWidart/laravel-modules#850]
Hi,

I created project laravel v6, install laravel-modules -> https://nwidart.com/laravel-modules/v6/installation-and-setup

And create Module Page (php artisan module:make Page), and visit http://my-project.com/page -> Show default template Hello World, 

I add router
`Route::get('/', 'PageController@index');`
https://gyazo.com/210fa03d536792b5a9ea1774c05af128

And visit http://my-project.com -> ít's' working, show default template of module "Hello World"

I commit this project on Gitlab,  and create a new domain -> http://my-project2.com and pull this project via my computer (XAMPP)

But module laravel-module not working, visit http://my-project2.com (xampp) -> show default laravel template, visit [http://my-project2.com/page] show 404.  But when I create new module Blog (php artisan module:make Blog) and visit [http://my-project2.com/blog] -> it working.

I try clear cache composer, clear cache laravel, remove vendor folder and composer install, composer update, composer dump-autoload, remove composer.lock,...but not working

Thank you!

**Comment by 50shashwat** [comment]
What did you do to make it work. I am having the same problem on my server. When I deploy using laravel deployer and gitlab to server, somehow all the routes of modules are not recognizable by laravel.

Even route:list doesn't return those routes in the module.

**Comment by 50shashwat** [comment]
The issue is similar to #849
