### ISSUE TITLE
Use Resources view for notifications?

### ISSUE THREAD

**Issue by skortabeast** [nWidart/laravel-modules#852]
how use custom views fro mail notify with modules, markdown/view  is not working with Module folder Resources.

**Comment by nWidart** [comment]
I would assume same as normal laravel.

**Comment by NickBourque** [comment]
Inside the build() function of a mailable, trying to reference a view that's inside of the module, even with the module's namespace, returns the following:

> View [viewname.blade.php] not found.

Code:

```
public function build()
    {
        return $this->subject($this->data['subject'])
            ->view('module::viewname');
    }

**Comment by bci24** [comment]
So is not possible to load the markup from the module ?

`
public function build(): static
{
        return $this->subject('test')
            ->markdown('Modules/Blog/Resources/views/emails/newPost');
 }
`

.... it throws an error: View not found.

I am using laravel/framework: 10 and nwidart/larevel-modules: 10
