### ISSUE TITLE
is it possible to use each module as a separate github repo?

### ISSUE THREAD

**Issue by mazraara** [nWidart/laravel-modules#853]
for example: If you consider these repo's nWidart/core, nWidart/contact, nWidart/notification

1. Can you plug and play **contact** and/or **notification** module with core module for different projects?
2. With this module package (nWidart/laravel-modules) is it possible to push updates to contact and notification modules when it is used by multiple projects and without crashing the existing functionality ? i.e like composer update
3. How do you develop and test the contact or notification module locally? should nWidart/contact and nWidart/notification be separate laravel application ?

**Comment by nWidart** [comment]
Yes you can, a module is just a package.

1. Don't know what you mean. But you can use modules anywhere.
2. Yes. Take a look at AsgardCMS
3. That's more complex, take a look at asgardcms.
