### ISSUE TITLE
Install Laravel Modules 6.0 in Fresh Laravel 6.0

### ISSUE THREAD

**Issue by desyashasyi** [nWidart/laravel-modules#854]
I got this error when install in Fresh Laravel 6.0

 Symfony\Component\Debug\Exception\FatalThrowableError  : Class name must be a valid object or a string

  at /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/nwidart/laravel-modules/src/LaravelModulesServiceProvider.php:59
    55|         $this->app->singleton(Contracts\ActivatorInterface::class, function ($app) {
    56|             $activator = $app['config']->get('modules.activator');
    57|             $class = $app['config']->get('modules.activators.' . $activator)['class'];
    58| 
  > 59|             return new $class($app);
    60|         });
    61|         $this->app->alias(Contracts\RepositoryInterface::class, 'modules');
    62|     }
    63| }

  Exception trace:

  1   Nwidart\Modules\LaravelModulesServiceProvider::Nwidart\Modules\{closure}(Object(Illuminate\Foundation\Application), [])
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/laravel/framework/src/Illuminate/Container/Container.php:800

  2   Illuminate\Container\Container::build(Object(Closure))
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/laravel/framework/src/Illuminate/Container/Container.php:682

  3   Illuminate\Container\Container::resolve("Nwidart\Modules\Contracts\ActivatorInterface", [])
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/laravel/framework/src/Illuminate/Container/Container.php:630

  4   Illuminate\Container\Container::make("Nwidart\Modules\Contracts\ActivatorInterface", [])
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:768

  5   Illuminate\Foundation\Application::make("Nwidart\Modules\Contracts\ActivatorInterface")
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/laravel/framework/src/Illuminate/Container/Container.php:1246

  6   Illuminate\Container\Container::offsetGet("Nwidart\Modules\Contracts\ActivatorInterface")
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/nwidart/laravel-modules/src/Commands/ModuleMakeCommand.php:39

  7   Nwidart\Modules\Commands\ModuleMakeCommand::handle()
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  8   call_user_func_array([])
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  9   Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/laravel/framework/src/Illuminate/Support/helpers.php:522

  10  value(Object(Closure))
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90

  11  Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34

  12  Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/laravel/framework/src/Illuminate/Container/Container.php:591

  13  Illuminate\Container\Container::call()
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/laravel/framework/src/Illuminate/Console/Command.php:202

  14  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/symfony/console/Command/Command.php:255

  15  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/laravel/framework/src/Illuminate/Console/Command.php:189

  16  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/symfony/console/Application.php:934

  17  Symfony\Component\Console\Application::doRunCommand(Object(Nwidart\Modules\Commands\ModuleMakeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/symfony/console/Application.php:273

  18  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/symfony/console/Application.php:149

  19  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/laravel/framework/src/Illuminate/Console/Application.php:90

  20  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:131

  21  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /Volumes/DATA 3/data important/WEB/FutureScientist6.0/artisan:37

How to solve the problem?

**Comment by nWidart** [comment]
I can't reproduce this.

**Comment by nWidart** [comment]
#843

**Comment by jtomek** [comment]
Same error here.

**Comment by nWidart** [comment]
Please update your configuration.
