### ISSUE TITLE
Use Resources of disable module

### ISSUE THREAD

**Issue by ojha007** [nWidart/laravel-modules#856]
i got a condition where i have to use the views of the ModuleA in moduleB  when  ModuleA is disable . i can use the controller and other class but cant use the resources .

**Comment by nWidart** [comment]
Don't use views cross modules.

Of course if the module is disabled, its resources wont be loaded/registered.

**Comment by ojha007** [comment]
isnot there any way to overwrite it .

**Comment by nWidart** [comment]
There probably is. Try to understand why it doesn't work now, and then you'll be able to make it work.
