### ISSUE TITLE
Form action gives error to different namespace

### ISSUE THREAD

**Issue by ntdorji** [nWidart/laravel-modules#858]
Hi, I have some issue with forms using laravel-form-builder. I have created 2 Modules: Home and Office. I started with Home, everything was working fine including the forms which i created using the form-builder.

But later when I created the module Office, the get/post actions from my forms in Home module redirects to Office controller. I am getting the error: 
Action Modules\Office\Http\Controllers\HomeController@index not defined.
I had used:    {!! Form::open(['method' => 'GET', 'action' => 'HomeController@index',  'class' => 'form-horizontal', 'autocomplete' => 'off']) !!}

I have gone through the other similar issues and tried the workarounds:

1. Using named routes:
   {!! Form::open(['method' => 'GET', 'action' => route('home.index'), 'class' => 'form-horizontal', 'autocomplete' => 'off']) !!}

 I get the following error:
ErrorException (E_ERROR)
Action Modules\Office\Http\Controllers\http://localhost/home not defined.

2. Using fully qualified namespace
 {!! Form::open(['method' => 'GET', 'action' => 'Modules\Home\Controllers\HomeController@index', 'class' => 'form-horizontal', 'autocomplete' => 'off']) !!}
Outputs the error:
Action Modules\Office\Http\Controllers\Modules\Home\Controllers\HomeController@index not defined. 

3. Using fully qualified namespace starting with '\'
 {!! Form::open(['method' => 'GET', 'action' => '\Modules\Home\Controllers\HomeController@index', 'class' => 'form-horizontal', 'autocomplete' => 'off']) !!}
Error:
Action Modules\Home\Controllers\HomeController@index not defined.

I have defined index method inside HomeController and my route file is as below:
Route::resource('home', 'HomeController');

I have been trying to fix this error for the entire day. Any help would be very appreciated.

**Comment by nWidart** [comment]
Hi,

I would suggest checking out the docs on the forms: https://laravel.com/docs/6.x/blade#forms

Example: you can use `action` and a route.
Instead use 
```
{!! Form::open(['method' => 'GET', 'route' =>'home.index', 'class' => 'form-horizontal', 'autocomplete' => 'off']) !!}
```

**Comment by ntdorji** [comment]
Thanks. Why didn't I do it that way. LOL. It works perfectly now. 

Is there any specific reason why 
{!! Form::open(['method' => 'GET', 'action' => 'HomeController@index', 'class' => 'form-horizontal', 'autocomplete' => 'off']) !!}
wouldn't work? 

Thanks a ton.
