### ISSUE TITLE
Module ServiceProviders not loaded within testing environment

### ISSUE THREAD

**Issue by SergejSi** [nWidart/laravel-modules#860]
I’m trying to use the laravel-modules package and everything runs as expected - except the tests. The problem is, that when running a test in the console, the specific module service providers seems not to be loaded within the testing environment. With the consequenz, that within tests i’m not able to use factories, seeders or routs defined in the specific module.

**Comment by SergejSi** [comment]
I Solve the problem for me by adding the following code to my base AppServiceProvider:

```
   if(app()->environment('testing')){
            $modules = array_slice(scandir(__DIR__."/../../Modules"),2);
            foreach ($modules as $module){
                            app()->register( "\Modules\\{$module}\\Providers\\{$module}ServiceProvider");

            }
        }
```

**Comment by RSpeekenbrink** [comment]
Make sure you add the Modules folder to your Composer.json autoloading section and make sure the folder is included in your phpunit.xml.

Composer.json:
```
 "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Modules\\": "modules/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
```

**Comment by SergejSi** [comment]
I added the module section to the composer.json. 
How do is adjust the phpunit.xml to load the factories/ seeds by default?

**Comment by nWidart** [comment]
Lets continue this in #870

**Comment by paul-crashley** [comment]
Was there an actual fix for this other than the PHPUnit exclusion?

I'm trying to run Dusk tests and no modules get registered
