### ISSUE TITLE
[Feature Request] Add StyleCI

### ISSUE THREAD

**Issue by RSpeekenbrink** [nWidart/laravel-modules#862]
Maybe an idea to add StyleCI with the Laravel preset to the repository to improve and standardize the codestyle?

https://styleci.io/

Possible StyleCI config:

.styleci.yml
```
preset: laravel
```

**Comment by nWidart** [comment]
Hi,

Thanks but we use php-cs-fixer using psr1/2 and not styleci using laravel's code style.

**Comment by RSpeekenbrink** [comment]
Is it possible to at least add PHPCS to the CI pipeline? So you will be notified in your PR if it does not meet any standards used by the package. This speeds up development quite a lot.

**Comment by RSpeekenbrink** [comment]
Nvm, I see it's in the pipeline now in the form of scrutinizer 👍
