### ISSUE TITLE
Module Migrate Issue

### ISSUE THREAD

**Issue by nasirkhan** [nWidart/laravel-modules#863]
I needed to use `module:v6:migrate` command for each new installation of my project. What changes i have to made, so that i do not have to run the same command each time?

**Comment by nWidart** [comment]
You need to commit the file it generates under the storage folder. You can also configure that file to be generated somewhere else.

**Comment by nasirkhan** [comment]
thanks for the update. Can you please let me know or refer to any doc so that i can change the generated file path and  commit with the project.

**Comment by nWidart** [comment]
here: https://github.com/nWidart/laravel-modules/blob/master/config/config.php#L204

**Comment by nasirkhan** [comment]
Thanks. 
I believe this file was not in the previous versions. Can we remain the same as before like not having the file?
Can you please mention why is it necessary to list the modules this way ?

**Comment by nWidart** [comment]
No we can't. This is a new feature from version 6, which is a major version.

The reason is because of this, we can easily change the storage, ie storing this in database too.

**Comment by nasirkhan** [comment]
I just checked the change log and found that this new feature has been added. 

I did not find that at the time of updating the package. 

I thing i just faced that i created a module and then deleted the whole module directory like i did previously. But the module_status file keeps it listed. It is alright? or what is the right way to delete  a module.

**Comment by nWidart** [comment]
you can delete the module folder and remove the line in the status file. 
We could provide a module:delete command to make it easier.
