### ISSUE TITLE
Existing migrations don't work.

### ISSUE THREAD

**Issue by djmirel** [nWidart/laravel-modules#868]
After update from 6.0.0 to 6.1.0, existing migrations don't work. 
I used php artisan migrate:fresh --seed for all the seeds and migrations.

**Comment by nWidart** [comment]
Hi,

Did you also force published the configuration?

**Comment by djmirel** [comment]
Do you mean "php artisan module:publish-config" ? If so, Yes.
Also, rechecked and the routes aren't working either.

**Comment by nWidart** [comment]
No I meant the package configuration.

Like did you run:
```
php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"
```
after the update to 6.1?

In any case, make sure [this option](https://github.com/nWidart/laravel-modules/blob/master/config/config.php#L206) points to the file you have.

**Comment by djmirel** [comment]
Unfortunately the above command didn't help.

Also, it seems that i don't have "modules_statuses.json" file anywhere. My config points to 
`'statuses-file' => storage_path('app/modules_statuses.json'),`
I searched for this file in my all the project.

I downgraded back to 6.0.0.

**Comment by nWidart** [comment]
I didn't ask you to run the command, but if you ran it.

You need to have this file somewhere, 6.0.0 has this file too.
if you upgraded from 5.x you need to run `php artisan module:v6:migrate`

**Comment by djmirel** [comment]
Ok, so i figured it out. 

After update, all my modules had disabled status (ran php artisan module:list command).  
After running `php artisan module:enable ModuleName` the file "modules_statuses.json" apeared in my project folder.
I made shure that all of the modules are in the json file, and now it works.

Note: i didn't migrate from 5.x, i started with 6.0.0. and "modules_statuses.json" didn't exist anywhere in my project.

Thank you for all your work!

**Comment by nWidart** [comment]
Hello,

I don't see how this is possible.
If you didn't upgrade from v5, it means you created modules on v6, which would have created this file.
