### ISSUE TITLE
How to use partials in a module

### ISSUE THREAD

**Issue by afarral** [nWidart/laravel-modules#869]
I have a master layout file in the main app, it contains some @include() statements,
i.e. @include('layouts.main-sidebar') within this i include a partial which contains the actual menu:@include('partials.menu') - may aim is that for each module the partial from that 'module' is used, is this possible?
Here an over view of my file structure to try to help explain:

app / Resources / views/ layouts / main-layout.blade.php
app / Resources / views/ layouts / partials main.blade.php

main-layout.blade contains @include('partials.menu')

moduleA / Resources / views/ index.blade (this extends main-layout.blade.php )
moduleA / Resources / views/ partials / menu.blade.php

I need the menu.blade.php to be used when viewing moduleA / Resources / views/ index.blade

**Comment by nWidart** [comment]
Hello,

These are namespaced by module, explained here: https://laravel.com/docs/6.x/packages#views

Meaning you can call the views by prefixing the module name.

**Comment by afarral** [comment]
Thanks for that, how would i put logic into a blade file: a long lines of:
if module i am using = Mod1 then load view parital Mod1::page
if module i am using = Mod2 then load view parital Mod2::page

Thanks
Adam

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
