### ISSUE TITLE
--database didn't use in migrate-xxxx(xxxx: rollback\reset\refresh)

### ISSUE THREAD

**Issue by HuNanZai** [nWidart/laravel-modules#87]
i look step by step into your code and i found this problem:

the problem is that you didn't use the '--database' option in your Migrations/Migrator.php's
`function table()` that will cause a lookup in the default db connection not the specific one i want.

as a advice, i think it's necessary add some method like `setConnection()` in the Migrator Class and use it in the command.

**Comment by nWidart** [comment]
Hello,

This is a duplicate of #49. Thanks for the tip though, feel free to submit a PR if you feel like it.

**Comment by nWidart** [comment]
This was fixed by pull request #88 
Let me know if it fixes your problem.

**Comment by HuNanZai** [comment]
haha~ it fixes my condition, hope it helps the other people!

**Comment by nWidart** [comment]
Fixed in 1.15.0
