### ISSUE TITLE
Undefined variable: factory

### ISSUE THREAD

**Issue by di1606** [nWidart/laravel-modules#870]
When I run my tests with this command `./vendor/bin/phpunit --coverage-text --colors=never` I have this error:
`Undefined variable: factory`.

I have checked that the `registerFactories()` method is called in my provider (`MyModuleServiceProvider`), it is well called.

I saw on the documentation that we need to add this piece of code in  `MyModuleServiceProvider`
```
$this->app->singleton(Factory::class, function () {
            $faker = $this->app->make(\Faker\Generator::class);
            return Factory::construct($faker, __DIR__ . '/../Database/factories');
});
```
it doesn't work ( same after I ran the command  `composer dumpautoload` )

Do you know how to fix the error ?

**Comment by nWidart** [comment]
Where is this variable factory undefined?

**Comment by di1606** [comment]
It's in my file test

```
class InstitutionControllerTest extends TestCase
{
    /**
     * @testdox Get the data of institutions
     * @covers \Modules\Institution\Http\Controllers\InstitutionController::index
     * */
    public function testIndex():void
    {
        $institutionCollection = new Collection(factory(Institution::class)->make()); // it's here factory 
        $mock = Mockery::mock(InstitutionRepository::class);
        $mock->shouldReceive('all')->andReturn($institutionCollection);
        $this->app->instance(InstitutionRepository::class, $mock);
        $response = $this->json('GET', 'api/institutions');
        $this->assertEquals(Response::HTTP_OK, $response->status());
        $this->assertEquals($institutionCollection, $response->getContent());
    }
}

```
the error appears when I execute the command `./vendor/bin/phpunit --coverage-text --colors=never` and not when i execute the command `./vendor/bin/phpunit`
<img width="694" alt="Capture d’écran 2019-11-06 à 09 05 10" src="https://user-images.githubusercontent.com/27860198/68279950-d3552380-0074-11ea-8578-d2039705c929.png">

**Comment by nWidart** [comment]
I just tried to reproduce this, creating a factory:

```php
<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */
use Faker\Generator as Faker;
use Modules\Blog\Entities\Post;

$factory->define(Post::class, function (Faker $faker) {
    return [
        'name' => $faker->name,
    ];
});
```

And in a migration creating it:

```php
factory(Post::class, 3)->create();
```

And it ran fine.

**Comment by di1606** [comment]
I use the make() function, but it's not the problem but the factory function which is not recognized when I run the tests with coverage.

**Comment by nWidart** [comment]
Hm not sure why it's not loaded for you. 
Did you check in your service provider if the factory is properly loaded for tests?

**Comment by di1606** [comment]
Here is my provide `InstitutionServiceProvider` 

```
class InstitutionServiceProvider extends ServiceProvider
{

    /**
     * Boot the application events.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerTranslations();
        $this->registerConfig();
        $this->registerViews();
        $this->registerFactories();
        $this->loadMigrationsFrom(__DIR__ . '/../Database/Migrations');
    }

    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->app->register(RouteServiceProvider::class);
        /*$this->app->singleton(Factory::class, function () {
            $faker = $this->app->make(\Faker\Generator::class);
            return Factory::construct($faker, __DIR__ . '/../Database/factories');
        });*/ // I put that in commentary. If I remove the comments it doesn't work.
    }
...
}
```

**Comment by nWidart** [comment]
What you commented is what loads the factories so you need that.

You could have something like this:

```php
    public function registerFactories()
    {
        if (! app()->environment('production') && $this->app->runningInConsole()) {
            app(Factory::class)->load(__DIR__ . '/../Database/factories');
        }
    }
```

**Comment by di1606** [comment]
the registerFactories() method is already called in the boot() method. I removed the comments but it doesn't work.


```
class InstitutionServiceProvider extends ServiceProvider
{
    public function boot()
    {
       ...
        $this->registerFactories();
       ...
    }
    public function register()
    {
        $this->app->register(RouteServiceProvider::class);
        $this->app->singleton(Factory::class, function () {
            $faker = $this->app->make(\Faker\Generator::class);
            return Factory::construct($faker, __DIR__ . '/../Database/factories');
        });
    }
...
    public function registerFactories()
    {
        if (! app()->environment('production') && $this->app->runningInConsole()) {
            app(Factory::class)->load(__DIR__ . '/../Database/factories');
        }
    }
....
}
```

**Comment by di1606** [comment]
I fix the error with phpunit, the solution is enable the module. But, I don't find the solution for the error with the command `./vendor/bin/phpunit --coverage-text --colors=never`

message error: 
```Undefined variable: factory ```

**Comment by di1606** [comment]
I found where the error comes from, it comes when I create a factory class. But I don't know solve this

factory class
```
<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use Faker\Generator as Faker;
use Modules\Institution\Entities\Institution;

$factory->define(Institution::class, function (Faker $faker) {
    return [
        'name' => $faker->company
    ];
});

```

**Comment by nWidart** [comment]
Is your module loaded in a test environment?

**Comment by di1606** [comment]
that is to say ?  setting up the .env.testing

**Comment by designvoid** [comment]
Running into this error today when running

```
php artisan event:list
```

Any suggestions?

**Comment by jeff1326** [comment]
I got the same problem with a package with Laravel 6.9.0 when using orchestra/testbench 3.9.2.
I did a test with this package with a test that can seed User and works well.
This sounds like a problem with how the setup of test are done.

**Comment by jeff1326** [comment]
I simply added an exclusion of my factories from file who is covered by Phpunit and this fixed my problem. I hope this will fix your problem too. 

> phpunit.xml
```
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./src</directory>
            <exclude>
                <directory>src/Database/Factories</directory>
            </exclude>
        </whitelist>
```

**Comment by ossycodes** [comment]
Still having this issue.
