### ISSUE TITLE
Controller not Found for additional Controllers inside module

### ISSUE THREAD

**Issue by stonedeft21** [nWidart/laravel-modules#872]
So I successfully created a Module with this command
`php artisan module:make Leads`

I also loaded the module in Composer using psr-4 and everything is working as expected. 

I created a new Controller inside the module with this command:  
`php artisan module:make-controller TesterController Leads`

It successfully created the controller within the Module .

I added this on the Module's Web Route:  
`Route::get('/tester','TesterController@index');`

I went to http://developmentsite.test/tester and I get this error: 
> Class Modules\Leads\Http\Controllers\TesterController does not exist

Am I missing something?

**Comment by nWidart** [comment]
Hi,

It looks like your configuration might be wrong. Look at the namespace, based on that you can fix the issue. It'll probably be in the `RouteServiceProvider` of your module

**Comment by mikemand** [comment]
Could also be that you need to [dump-autoload via Composer](https://getcomposer.org/doc/03-cli.md#dump-autoload-dumpautoload-): `composer dump-autoload -oa`

**Comment by nWidart** [comment]
I see you edited the issue, are you sure about the error message?

**Comment by stonedeft21** [comment]
Thanks for the very quick response. I checked the namespaces from my controllers and it is correctly defined in RouteServiceProvider

Running `composer dump-autoload -oa ` fixed the issue. Wow! thanks
