### ISSUE TITLE
Module::allEnabled returns empty array in laravel 6

### ISSUE THREAD

**Issue by soheil-ghs** [nWidart/laravel-modules#874]
when I call Module::allEnabled(), this returns empty array
what's the problem?

**Comment by nWidart** [comment]
Hi,

Did you just upgrade? If so, did you run the migrate command ?

```php
php artisan module:v6:migrate
```

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
