### ISSUE TITLE
Organising Module configs

### ISSUE THREAD

**Issue by dpetrovaliev** [nWidart/laravel-modules#875]
As I didn't find any issues and documentation related to this I'm opening a new issue.

What is the way to organize configs of different modules? Should I publish provider for each of my modules? If yes, do i need to write custom logic to load configs published by each of my modules?

Example. 
I have a module that should define a new 'alias' and I should use it inside the module.

What is the right way to do this without writing custom logic?

**Comment by nWidart** [comment]
There is no "right" way to do anything. 
You can choose what's best for you / your use-case. 

I would just use the configs as laravel has them.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
