### ISSUE TITLE
Auto publish modules

### ISSUE THREAD

**Issue by amitavadeb** [nWidart/laravel-modules#876]
Hi,

Anyway to auto publish modules? Everytime I work, I have to publish modules.

Thanks

**Comment by nWidart** [comment]
Hi,

You can yes, some of is explained here: https://nwidart.com/laravel-modules/v6/basic-usage/compiling-assets .
You can also look at [AsgardCMS](https://github.com/AsgardCms/Platform) where I set it up to auto publish the assets for each module on change.

**Comment by amitavadeb** [comment]
Thanks man but I am not using mix. I wrote a middleware instead.
