### ISSUE TITLE
Can't read config file values in the Module's web routes file

### ISSUE THREAD

**Issue by andersonpem** [nWidart/laravel-modules#877]
Hey nWidart!  First things first, thanks for this module. Its scaffolded structure is very helpful to start coding asap.
I'm currently developing a module. And in this module I want the user to be able to set the route group name by altering the config.php file inside the module. The module's config file is not published and I can read values from it in controllers with no problem.

I tried to include the config value in the route file like in the following example: 

```php
//  Modules/modulename/routes/web.php
Route::prefix(config('modulename.routename'))->group(function() {
//                         ^^^      ^^^ @returns null
.....
});
```
The default config file:
```php
//  Modules/modulename/Config/app.php
return [
    'name' => 'A Module Name',
    //Names the route given for handling the Module's requests
    'routename'=>'foo',
    ....
```
The problem is that when I try to read the config from the module it returns **null**. But I'm absolutely sure the value exists and I can read other values in Controllers.

I tested attempting to read a value in Laravel main project's config file (app.php) and it returned the value normally.

Is this related to the boot order and registration of the module and the one from the main app? How could I mitigate this without having to publish the config to the main app's config folder?

Once again, thanks man. This package rocks :+1:

**Comment by andersonpem** [comment]
I just came to the realization that the user is not supposed to poke around in the Module's folder. If he updates the module, all his changes will be lost in favor of a new version of the file. So the best practice would be, indeed, to request the user to publish the config files. Will do that :)
But still, what do you think that causes this behavior? :) It might be useful for someone to know.

**Comment by nWidart** [comment]
Indeed, the config file should be published.

About the null value, it could be that the config file is read, after the routes file which would explain this. You could try to load in the config file earlier.

**Comment by niridoy** [comment]
Config file of the main application is not working in the module action called.

**Comment by markpavia** [comment]
> Indeed, the config file should be published.
> 
> About the null value, it could be that the config file is read, after the routes file which would explain this. You could try to load in the config file earlier.

How can I load the config file earlier?
