### ISSUE TITLE
using vuejs seperately in each modules

### ISSUE THREAD

**Issue by hdshariati** [nWidart/laravel-modules#879]
I use laravel modules and create some components on vuejs. 
the main app.js in root inheritance in all modules and in some modules use that app.js as name of modue ex. module.js.
but some times nothing of vuejs loaded even in debugger. is there any way to resolve my problem?
when I try to update npm plugins all thing crash. so I use a node_modules repository and when I want add new plugin , add it customley.

**Comment by nWidart** [comment]
Hi,

I don't understand what you're saying.

It does look however like it's not a problem with this package, as laravel-modules doesn't do anything front-end related. 
So I'm guessing it's configuration related on your end.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
