### ISSUE TITLE
How use public folder on module

### ISSUE THREAD

**Issue by srayuth089** [nWidart/laravel-modules#880]
how config module for merge folder public on module?

**Comment by nWidart** [comment]
what do you mean?

**Comment by srayuth089** [comment]
@nWidart I want every module to have a public folder.

**Comment by srayuth089** [comment]
@nWidart Anybody, would you please help? how can I set /public on each /Modules?
for example
- /Modules/project-a/public
- /Modules/project-b/public

**Comment by nWidart** [comment]
You can't have public folders in modules, modules can publish in the public folder though. Look up the package documentation on the docs.

**Comment by srayuth089** [comment]
> You can't have public folders in modules, modules can publish in the public folder though. Look up the package documentation on the docs.

Thank you
