### ISSUE TITLE
How to enable laravel modules with multi-tenant

### ISSUE THREAD

**Issue by c1t1zen** [nWidart/laravel-modules#882]
Hello
i try use this package:
https://github.com/tenancy/multi-tenant

to enable Laravel modules and mutli tenant 
if system (app) has multi websites with multi databases
when i create new tenant it does not run migrations in other modules

thank you in advance

**Comment by nWidart** [comment]
hi,

I don't know what you mean by "run migrations in other modules".
There's only migrations in the application. If this package has migrations, they will run for the whole app.

**Comment by c1t1zen** [comment]
Hey, @nWidart 
thank you for reading my issue.
i did installed Laravel modules and i like it alot  i used to work with asgardCms .
my problem
i installed https://github.com/tenancy/multi-tenant
when i do create new tenant (new database) using
php artisan tenant:create foo "Billy Bob" billy@example.com
it does run all migrations under database/migrations/tenant for the new website(new database)
but it does not run any other migrations under any other modules like follwoing:
modules/User/Database/Migartions/*

i dont know how i run migrations in other modules when i create new tenant

Thank you in advance

**Comment by nWidart** [comment]
You would have to run the `module:migrate` command.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by asraf-bl04** [comment]
**### Its work**

```
function loadPaths()
    {
        $module = json_decode(file_get_contents(base_path('modules_statuses.json')), true);

        $paths = [];
        foreach (glob( base_path('Modules/*/Database/Migrations') ) as $filename) {
            foreach ($module as $key => $value) {
                if(Str::contains($filename, 'Modules/'. $key ) && $value == true ){
                    array_push($paths, $filename);
                }
                
            }
            
        }
        array_push($paths, database_path('migrations/tenant'));
        return $paths;
    }
```

**Comment by Vestibule** [comment]
You can manually specify the used by the `tenant:migrate` command in the tenancy config file. This artisan command is also called on tenant creation.

Here is what I did :
```php
/**
 * Parameters used by the tenants:migrate command.
 */
'migration_parameters' => [
    '--force' => true, // This needs to be true to run migrations in production.
    '--path' => [
        database_path('migrations/tenant'),
        module_path('Auth') . 'Database/Migrations/tenant',
        module_path('Tenancy') . 'Database/Migrations/tenant',
    ],
    '--realpath' => true,
],
```

Also a function could get all enabled modules and then push all the tenant related migrations paths to configuration but I think this would be relevant only with more than 10 modules.

**Comment by ctf0** [comment]
i came across the same issue and the easiest approach i found would be overriding the `Jobs\MigrateDatabase::class` in `App\TenancyServiceProvider` based on @ducor-io but with simpler logic ex.
```php
class TenancyMigrateDatabase extends MigrateDatabase
{
    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        $this->loadPaths();

        parent::handle();
    }

    public function loadPaths()
    {
        $paths   = [];
        $modules = array_filter(
            json_decode(
                file_get_contents(base_path('modules_statuses.json')),
                true
            )
        );

        foreach (array_keys($modules) as $module) {
            $paths[] = base_path("Modules/$module/Database/Migrations/tenant");
        }

        $config = 'tenancy.migration_parameters.--path';
        $paths  = array_unique(array_merge(config($config), $paths));

        return config([$config => $paths]);
    }
}
```

now when u run `php artisan migrate --seed` simply make sure the tenant seeder runs b4 any of the other seeders and all ur migrations `tenant / central` will run along with the seeders, all in one go.

**Comment by Surt** [comment]
@ctf0 how do you avoid migrating the tenant migrations on the central db?
do you use? ```  php artisan migrate --path database/migrations/ ```  as seen on https://github.com/nWidart/laravel-modules/issues/545 so central does not have all the tenant migrations?

**Comment by ctf0** [comment]
@Surt u just run `php artisan migrate --seed`

> Also, on your code the modules section should read:

by the time i was using the package, the `modules_statuses` was in the root.

**Comment by anburocky3** [comment]
@Surt 
![image](https://user-images.githubusercontent.com/15264938/205441151-9c712e9c-0fa8-4a0c-af93-d092828470e8.png)

I want to migrate this, while running `php artisan migrate --seed` it is migrating all central migration files and seeds them.

But i want to migrate only the tenant migration files located in each modules dir.

**Comment by legomannetje** [comment]
Does anyone have a working project with both packages that i can take a look at? I'm confused about how i can get it to work

**Comment by fgonga** [comment]
its work 
```PHP
<?php


namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Nwidart\Modules\Facades\Module;

class TenantMigrationServiceProvider extends ServiceProvider
{

    public function boot()
    {
        config([
            'tenancy.migration_parameters' => [
                '--force' => true,
                '--path' => $this->getTenantMigrationInModules(),
                '--realpath' => true,
            ],
        ]);
    }

    protected function getTenantMigrationInModules(): array
    {
        $modules = Module::all();

        $folders = [];
        $folders[] = database_path('migrations/tenant');
        foreach ($modules as $module) {
            $folders[] = $module->getPath() . "/database/migrations/tenant";
        }

        return $folders;
    }
   

}

```
