### ISSUE TITLE
Module ServiceProviders not loaded within production environment

### ISSUE THREAD

**Issue by NadaElnagar** [nWidart/laravel-modules#884]
I’m trying to use the laravel-modules package and everything runs on local envirnoment .  the specific module service providers seems not to be loaded within the production  environment. 
Error : no such file or directory 
try to write that in 
if(app()->environment('production')){
$modules = array_slice(scandir(__DIR__."/../Modules"),1);
foreach ($modules as $module){
app()->register( "\Modules\\{$module}\\Providers\\{$module}ServiceProvider");
}}
but still can't show  my custom modules

**Comment by nWidart** [comment]
are your modules enabled in production?

Do you have [this file](https://www.twitch.tv/yofamsteve) in prod?

**Comment by NadaElnagar** [comment]
ٍSorry the file you mention it link not open with me but am not doing anything in production
can explain or put link  how to enable modules in production

**Comment by nWidart** [comment]
Hi, sorry something went wrong with the link, this one: https://github.com/nWidart/laravel-modules/blob/master/config/config.php#L206

**Comment by NadaElnagar** [comment]
this config not exists 
you means am copy this file and put it on my config folder right ?

**Comment by nWidart** [comment]
No, you need to have `base_path('modules_statuses.json')`

**Comment by NadaElnagar** [comment]
i don't have this file in my project modules_statuses.json
am try to add it in moduls.php but still same error !

**Comment by nWidart** [comment]
You need that file, you probably have it locally. If you're on an old version of the package (6.0) it'll be in the storage folder.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
