### ISSUE TITLE
Should I register policies manually?

### ISSUE THREAD

**Issue by Daniyal-Javani** [nWidart/laravel-modules#885]
Policy Auto-Discovery not working:

> Specifically, the policies must be in a Policies directory below the directory that contains the models. So, for example, the models may be placed in the app directory while the policies may be placed in the app/Policies directory. In addition, the policy name must match the model name and have a Policy suffix. So, a User model would correspond to a UserPolicy class.

Is there any better way rather than registering manually in `app/Providers/AuthServiceProvider.php`?

**Comment by mikemand** [comment]
Depending on how you have your directories configured, you can create a `Policies` directory inside the `Entities` directory for your policies.

To handle that with this package, you should publish the config file (if it isn't already) and change this line: https://github.com/nWidart/laravel-modules/blob/4151f9f42887524783385dce0f5bf8735b6b73a3/config/config.php#L122

```diff
-'Policies'
+'Entities/Policies'
```

(replace `Entities` with whatever directory your models are generated into)

This works for vanilla Laravel, so it should work with this package also.
