### ISSUE TITLE
Database Connection refused on a fresh laravel installation

### ISSUE THREAD

**Issue by ppshobi** [nWidart/laravel-modules#886]
I have a fresh laravel 6 installation and laravel modules package, I have created a module according to the documentation and created a Model/Entity called `Category` and its migration, migration ran successfully but when I query the Model it throws following exception

> message: "SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `categories`)",…}
> exception: "Illuminate\Database\QueryException"
> file: "/Users/shobi/Projects/yahaal-inventory/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
> line: 669
> message: "SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `categories`)"

Following is my code on the controller which causes the above exception

` return response()->json(Category::all());`

when I dump the following `DB::connection()->getPdo();`I can see that the `DB_HOST` has been overridden to `127.0.0.1` instead of the ip address I have given.

**Comment by nWidart** [comment]
Hi,

This is not related to this package.
This looks like a configuration issue where laravel is unable to connect to the database.
Make sure the connection details are correct in your `.env` or `config/database` file.
