### ISSUE TITLE
Illuminate\Routing\RouteFileRegistrar::register(): Failed opening required

### ISSUE THREAD

**Issue by amitavadeb** [nWidart/laravel-modules#888]
Im getting this error which is related to one of the modules which I installed in one of my env.

`Illuminate\Routing\RouteFileRegistrar::register(): Failed opening required '/var/www/html/project/Modules/module-name' (include_path='.:/usr/share/pear7:/usr/share/php')`

In one of my env, its working fine but whenever I git pull to my other env, it shows the prev err msg.

Im unable to understand what this error is and unable to fix.

Thanks

**Comment by nWidart** [comment]
Hi,

Never seen this error before. It looks like some configuration wasn't loaded?

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by ripon52** [comment]
I am facing these issues right now. Still not fixed.

**Comment by asamarcos** [comment]
I may have more information on this as I was able to reproduce.

Steps:
Create a module using laravel 6 and laravel-modules version 6.*
Use this module on laravel 5.8 and laravel-modules version 5.*

As soon as the module is active, the error appears. To me it was:

` Illuminate\Routing\RouteFileRegistrar::register(): Failed opening required '/data/www/html/portal/Modules/MAIN' (include_path='.:/usr/share/pear:/usr/share/php') {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 64): Illuminate\\Routing\\RouteFileRegistrar::register(): Failed opening required '/data/www/html/portal/Modules/MAIN' (include_path='.:/usr/share/pear:/usr/share/php') at /data/www/html/portal/vendor/laravel/framework/src/Illuminate/Routing/RouteFileRegistrar.php:35)`
