### ISSUE TITLE
Modules being update to gitlab

### ISSUE THREAD

**Issue by ranrinc** [nWidart/laravel-modules#889]
After update my project to gitlab and then clone the project into production machine. We are unable to have it run and it shown 404. And I believe this have something to do with .gitignore not copying something or is there a procedure that I need to called after composer update?

Please help

**Comment by mgamal92** [comment]
please clarify that by providing some example in details

**Comment by nWidart** [comment]
You need to have the module file committed.  It's the one specified in the [module configuration here](https://github.com/nWidart/laravel-modules/blob/master/config/config.php#L206).

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
