### ISSUE TITLE
defer loading providers

### ISSUE THREAD

**Issue by eafshary** [nWidart/laravel-modules#89]
hi,
sorry for my eng
how to defer my module service providers, I know service providers registered at runtime but i have about 30 modules!!! it's very expensive to load my pages on server
your advise???

**Comment by adelowo** [comment]
Just set the `defer` property to true... https://laravel.com/docs/5.3/providers#deferred-providers

**Comment by eafshary** [comment]
I know, but providers instantiate in runtime and $defer=true ignored

**Comment by eafshary** [comment]
????????

**Comment by nWidart** [comment]
This is an issue I've looked at before and didn't find a proper solution to make this work, as laravel (as far as I'm aware) doesn't have an API to register a deferred provider.
