### ISSUE TITLE
Controller extends the wrong controller

### ISSUE THREAD

**Issue by VeRJiL** [nWidart/laravel-modules#891]
When creating a new controller in a module it is extending the wrong controller like so:

```
<?php

namespace Modules\Category\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller; // this is suppose to App\Http\Controllers\Controller;

class TestController extends Controller
{
}
```

**Comment by mgamal92** [comment]
No its a right controller , Because ```App\Http\Controllers\Controller``` extends from ```Illuminate\Routing\Controller```

**Comment by VeRJiL** [comment]
@mgamal92 No it is not because the App\Http\Controllers\Controller is using traits which helps us to validate or other actions in the controller which the App\Routing\Controller does not.

**Comment by nWidart** [comment]
That's up to you to decide. I would advise not to use anything from the default `App` namespace.

You could create your own base controller, or use the traits on a case by case basis.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by VeRJiL** [comment]
@nWidart Thank you and sorry for the late reply
