### ISSUE TITLE
Ordering routes from different modules

### ISSUE THREAD

**Issue by Kovbo** [nWidart/laravel-modules#892]
Working with default Laravel structure when you have only one route file you have to order your routes with the most specific first:
```
Route::get('posts/create', 'PostsController@create');
Route::post('posts/', 'PostsController@store');
Route::get('/posts/{post}', 'PostsController@show');
```
Laravel-modules offers separate route files for each module. This is really a great idea, but I'm facing a problem with the routes ordering (hierarchy).

I want to display posts without category nesting.
Just like `example.com/article-title`.

The route will be `Route::get('/{slug}', '\Modules\Posts\Http\Controllers\PostsController@show');`
But this route owerrides some other pages from other modules.

Is there any way to order routes files in the desired way?

**Comment by mikemand** [comment]
You could try the [fallback route](https://laravel.com/docs/6.x/routing#fallback-routes) feature? Please take note of the warning in the docs:

> The fallback route should always be the **last** route registered by your application.

**Comment by Kovbo** [comment]
> You could try the [fallback route](https://laravel.com/docs/6.x/routing#fallback-routes) feature? Please take note of the warning in the docs:
> 
> > The fallback route should always be the **last** route registered by your application.
> 
> Edit: A little more detail for you. You can use the `order` option (from `module.json` to tell Laravel Modules which order to load modules in, so setting a higher number will make your module load later - thus your routes for the Page module should load after all the others.

Thank you, ordering Modules registration solves the issue. I did not know there was the `order` parameter. It works fine now, thank you once again!

**Comment by mikemand** [comment]
> Thank you, ordering Modules registration solves the issue. I did not know there was the `order` parameter. It works fine now, thank you once again!

Yeah, I was trying to find in the docs where the `module.json` file was mentioned and didn't see it anywhere. It seems like an oversight; I'll see about getting it documented. 😃
