### ISSUE TITLE
translation its not working in web.php

### ISSUE THREAD

**Issue by soheilsam** [nWidart/laravel-modules#893]
I want to use translation in web.php in **modules** not web.php in laravel path
and its not working
for example 
`$pr = trans('moduleName::language.projects');` => everywhere in controller or blade its fine
`dd($pr)` => return 'projecten'
and in web.php **modules** path its not working
`$pr = trans('moduleName::language.projects');`
`dd($pr)` => return string _moduleName::language.projects_
`Route::get(trans($pr), ProjectController@index);` -> its not working and return string

**Comment by nWidart** [comment]
Hi,

It's possible the translations aren't loaded yet by laravel in your routes file.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
