### ISSUE TITLE
Tests with inactive modules?

### ISSUE THREAD

**Issue by NemanjaMilosevic** [nWidart/laravel-modules#894]
If i turn off certain module in my `module_statuses.json` how can i make it so that tests inside that module are not being run?

**Comment by nWidart** [comment]
Hi,

That status file isn't linked to phpunit, so it will keep running the tests. 
To ignore some tests, you need to remove the test doc blocks accordingly.

**Comment by NemanjaMilosevic** [comment]
So there is no way to due that dynamically based on module status?

**Comment by nWidart** [comment]
There might if phpunit has a programatic api for you to hook into.
I've not looked into this myself though.
