### ISSUE TITLE
In FileRepository.php line 164: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by eslam22695** [nWidart/laravel-modules#895]
when make composer update i get this error i don't know why

![image](https://user-images.githubusercontent.com/45387722/71824031-3f69fd00-30a1-11ea-8dcc-f5e1403c2798.png)

![image](https://user-images.githubusercontent.com/45387722/71824249-c15a2600-30a1-11ea-9bcb-0a0a846e0301.png)

**Comment by nWidart** [comment]
What updated in this composer update? What version did you have before etc?

**Comment by eslam22695** [comment]
Just adding passport to create APIs

![image](https://user-images.githubusercontent.com/45387722/71886537-0d11db80-3145-11ea-948b-e7d980c1d481.png)

**Comment by nWidart** [comment]
It's possible that upgraded laravel-modules, check which version is installed.

In any case version 3 is not supported anymore.

**Comment by eslam22695** [comment]
version of what ??
okay how to upgrade it ??

**Comment by nWidart** [comment]
The version of the package you're posting an issue on...

**Comment by eslam22695** [comment]
currently version is 3 as image above

**Comment by nWidart** [comment]
Yes, but as I mentioned it’s possible it got upgraded during your composer update. 
In any case, that version is not supported anymore.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
