### ISSUE TITLE
Accessing to Env file from a module

### ISSUE THREAD

**Issue by messi89** [nWidart/laravel-modules#896]
Hi;

I'm trying to read a value from laravel .env file on a vue file...as laravel mix docs says we need just to call :
process.env.MIX_VARNAME

when .env file contains 
VARNAME=test
MIX_VARNAME="${VARNAME}"

it's work on laravel main apps.js but if try it on a module folder it's not work (undefined)

I try to require dotenv but same problem

any idea ?

**Comment by nWidart** [comment]
I've had to do this too and works fine. Maybe you try to read it too soon in the initialisation.

**Comment by messi89** [comment]
> 
> 
> I've had to do this too and works fine. Maybe you try to read it too soon in the initialisation.

I had to add this line to the module webpack.mix file, otherwise it doesn't work for me (undefined var) :
`//fix for env mix var
require('dotenv').config({path: __dirname+'/./../../.env'});`

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
