### ISSUE TITLE
This module does something strange to a Laravel app

### ISSUE THREAD

**Issue by rabol** [nWidart/laravel-modules#897]
Hi

I do not know if it i's a bug or a feature

I'm using Laravel Homestead as dev environment.

from the command line:

1) laravel new myapp
2) change parameters in .env
3) composer require --dev laravel/ui
4) php artisan ui --auth vue
5) composer require nwidart/laravel-modules
6) composer dump-autoload
7) php artisan module:make Blog
8) composer dump-autoload

then I get the following error

```
Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Modules\Blog\Providers\BlogServiceProvider' not found
```

if I add the autoload like this:

```
{
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Modules\\": "Modules/"
    }
  }
}
```

But.... I do not want to use psr-4 autoloading, I want to control how the Modules are loaded in my own Service provider.

Any hint on why the error occur ?

**Comment by nWidart** [comment]
If you don't autoload via composer, you will have to handle that yourself indeed.

**Comment by rabol** [comment]
I'm sorry I do not understand your answer.

I would like to handle the loading of the modules my self, but I do not want the package (your) to break by app.

if I do not add the 
```
{
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Modules\\": "Modules/"
    }
  }
}
```  
then I get and error when executing this:
composer dump-autoload

in other words:
If I do this:
php artisan module:make Blog

and NOT add this to the main composer.json:
```
{
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Modules\\": "Modules/"
    }
  }
}
```

then I get the error and my app will not work

It looks like this command:

```
php artisan module:make Blog
```
Add something to the autogenerated composer file

**Comment by nWidart** [comment]
You need to add that piece of code for the app to work if you want modules to be loaded.

If you don't want to let composer handle that, you will have to handle autoloading yourself.

**Comment by rabol** [comment]
Yes, I know I should add a piece of code to my app  load the module, that is what I'm trying to say, but the command: "php artisan module:make Blog" adds a something and that something breaks my app, if I do not  add the "Modules\\": "Modules/" to the main composer.json file

If I do "php artisan module:delete Blog, then everything is back to normal

**Comment by rabol** [comment]
Sorry, it seems like you do not understand.

I do not want to auto load modules, so therefor I DO NOT have the psr-4 part in my main composer.json

But not having the psr-4 part in the main composer.json breaks my app due to the fact that your package adds something extra when I use the command: php artisan module:make Blog

Try to follow the steps in the first and you can see what I mean

**Comment by nWidart** [comment]
I do understand, and I've been telling you the same thing: you need to autoload the modules yourself if you don't want to use composer.

The package will try to load your module's service provider. If your module hasn't been loaded, this will error.
Autoload it yourself and the error will go away.

**Comment by rabol** [comment]
Aha, so you are saying that your service provider tries to load all Module's service providers, and i will get the error because all the modules classes / code is not 'loaded' before 

How can I prevent that ?

**Comment by nWidart** [comment]
Yes.

I already told you a few times.

**Comment by rabol** [comment]
ok, so I have to load hundreds of classes on each page load - that is not very good for performance

**Comment by nWidart** [comment]
You could report this finding to composer, which is the project doing the loading.

**Comment by rabol** [comment]
No, your package is doing the loading of all the modules service providers

/vendor/nwidart/laravel-modules/src/LaravelModulesServiceprovidor.

But, ok the package works for most people, I just need another solution

**Comment by nWidart** [comment]
I hope you're aware that's how everything works in php.
I also hope you're aware you can customise things like this. 

Feel free to actually do performance tests. I have, and no performance impact is present.

**Comment by rabol** [comment]
Well... Autoloading has nothing to do with PHP!

I'm fully aware that there is a 'trade-off' by using a framework.

It will make a difference if there is 1 or 10 modules, it might be small but there is a difference.

Look at this: https://github.com/mrabbani/laravel_module_manager

that package have a 'install' command, so that it only autoload modules that is 'installed'

**Comment by nWidart** [comment]
Autoloading has everything to do with [PHP](https://www.php.net/manual/en/function.spl-autoload-functions.php). It's a concept for PHP.

Of course it will make a difference, the exact same difference if you would have had to write that code outside modules.
I've done profiles with many more modules than 10, and no hit was found. Hence why I'm asking you do the same. I have a feeling you're making assumptions without proper research.

> that package have a 'install' command, so that it only autoload modules that is 'installed'
And this package has an active/inactive status. Inactive modules will not be loaded.

Please take time to do some research.

**Comment by rabol** [comment]
I have read the documentation: https://nwidart.com/laravel-modules/v6/introduction and I have not been able to find anything that indicate that it is possible to turn off autoloading of a single module.

I have not been able to find any module methods that give a status of a module (https://nwidart.com/laravel-modules/v6/advanced-tools/module-methods)
I have not seen any commands that can activate or deactivate a module

I have found this:

> module:use
Use a given module. This allows you to not specify the module name on other commands requiring the module name as an argument.

but the description is rather cryptic


This is from the documentation: (https://nwidart.com/laravel-modules/v6/installation-and-setup)

> By default the module classes are not loaded automatically. You can autoload your modules using psr-4. For example :

please note the "You can'" - this is actually not a option, you will get the error that I was trying to inform you about if you do not add this to your composer.json

**Comment by nWidart** [comment]
>I have not been able to find any module methods that give a status of a module (https://nwidart.com/laravel-modules/v6/advanced-tools/module-methods)
I have not seen any commands that can activate or deactivate a module

Did you read the page?
![image](https://user-images.githubusercontent.com/882397/72210055-01f8db80-34b6-11ea-8363-d1ef92fcaf32.png)

Look at this: https://github.com/nWidart/laravel-modules/blob/master/src/FileRepository.php#L318-L333
Now look up the `$this->getOrdered()` method. 

> please note the "You can'" - this is actually not a option, you will get the error that I was trying to inform you about if you do not add this to your composer.json
Seriously, why go in circles when the answer has been given.

You don't want to use composer, fine. Build it yourself.
