### ISSUE TITLE
method setActive returns wrong type

### ISSUE THREAD

**Issue by rabol** [nWidart/laravel-modules#898]
I'm using Laravel homestead:

1) laravel new test
2) modify .env
3) Install laravel-modules
4) php artisan module:make Blog
5) open /routes/web.php and modify like below

```
Route::get('/', function () {
    $module = Module::find('Blog');
    $module->setActive(true);
    return view('welcome');
});
´´´

This will cause an error:
Symfony\Component\Debug\Exception\FatalThrowableError
Return value of Nwidart\Modules\Module::setActive() must be of the type bool, null returned

**Comment by nWidart** [comment]
Thanks, this was fixed in this commit https://github.com/nWidart/laravel-modules/commit/eda71f595c66ea7443a592935fcff64e7936e650

You could also use the [activator class](https://github.com/nWidart/laravel-modules/blob/master/src/Activators/FileActivator.php) directly.
