### ISSUE TITLE
Cannot install on LV 5.1

### ISSUE THREAD

**Issue by sarfraznawaz2005** [nWidart/laravel-modules#9]
Hi,

Can not install this package for LV v5.1 with this command:

`omposer require nwidart/laravel-modules`

Because `composer.json` file requires v5.2 for laravel. 

Can you please modify it so it works with LV5.1 too as it is still widely used version.

Thanks

**Comment by nWidart** [comment]
Please see https://github.com/nWidart/laravel-modules/issues/3#issuecomment-233167161

**Comment by nWidart** [comment]
Support for 5.1 was pushed at tagged. 😄

**Comment by sarfraznawaz2005** [comment]
Awesome thanks :-)
