### ISSUE TITLE
elixir/gulp integration

### ISSUE THREAD

**Issue by peetersdiet** [nWidart/laravel-modules#90]
@nWidart Are there plans to support gulp/elixir to publish assets from modules to the public folder?

I found an npm package that could help: https://github.com/andywer/gulp-elixir-modules . The package is outdated and does not work with Laravel 5.3, due to changes in elixir, but maybe it's a good startingpoint.

**Comment by nWidart** [comment]
You already can publish those assets with elixir.

For instance on AsgardCMS I use the following:

```
var task = elixir.Task;
elixir.extend("stylistPublish", function() {
    new task("stylistPublish", function() {
        return gulp.src("").pipe(shell("php ../../artisan stylist:publish " + themeInfo.name));
    }).watch("**/*.less");
});
```

**Comment by nWidart** [comment]
Hello,

I'm not very advanced on the frontend side, so not sure what you want here.
Can't your gulpfile handle this logic ?

**Comment by peetersdiet** [comment]
No problem. Thx for the feedback.

We are developing an npm-module ourselves to automate the process of generating assets in the public-folder. I have to check if we can oepn-source this, but I'll let you know if we do. It could be handy for other developers using the same approach as us.

**Comment by nWidart** [comment]
Awesome. Feel free to post the link to it here if/when you can. 👍

**Comment by pedrosoares** [comment]
I don`t know if help, but with webpack.mix from Laravel 5.4 i can use the require to call another script in each module.
Main webpack:
```
require('./Modules/Admin/webpack.mix.js');
```
Admin Webpack:
```
const { mix } = require('laravel-mix');
mix.sass(__dirname+'/Assets/scss/app.scss', 'public/modules/Admin/css');
```

**Comment by balping** [comment]
I wrote this little artisan command that could automatise mix integration:

https://github.com/balping/asset-bundler

**Comment by nWidart** [comment]
This is really cool, well done! 👍
