### ISSUE TITLE
[Question] Middleware Groups

### ISSUE THREAD

**Issue by marcelogarbin** [nWidart/laravel-modules#902]
Hello, I'm using the [laravel-menu](https://github.com/lavary/laravel-menu) package, which uses middlewares for menu declaration.

I am currently declaring in the app / Http / Kernel.php file in the 'web' middleware.

Using your package would you have any way to declare middleware 'web' within a module without having to go through Kernel.php?

Thanks

**Comment by marcelogarbin** [comment]
another question that arose regarding middleware. 
Is it possible to generate a stub of it so that when a new module is created the middleware file is created together with the module? How can I do it?

@nWidart Would you help me? thanks

**Comment by nWidart** [comment]
Regarding your second question, yes you can. Up to you to choose how. You can look at Asgardcms (specifically the Workshop module) on how to do this.

And yes you can register middleware in modules. Example here https://github.com/AsgardCms/Platform/blob/3.0/Modules/Core/Providers/CoreServiceProvider.php#L40

**Comment by marcelogarbin** [comment]
> Regarding your second question, yes you can. Up to you to choose how. You can look at Asgardcms (specifically the Workshop module) on how to do this.
> 
> And yes you can register middleware in modules. Example here https://github.com/AsgardCms/Platform/blob/3.0/Modules/Core/Providers/CoreServiceProvider.php#L40

Thanks a lot for the help. It helped me a lot, I owe you a beer! :beers: hahaha

**Comment by marcelogarbin** [comment]
@nWidart Hello again, 

1. I would like to take a doubt, in the config/modules.php file there is the array of replacements. I have the middleware file in the stubs folder, made some modifications and put the 'LOWER_NAME', 'STUDLY_NAME' names to be replaced. But there is no such substitution, would there be any way to do that?

2. Another question that i didn't discover is about creating a new middleware file as soon as the module is created, i would like to create this file with the name of the module together. Example: PainelMenuMiddleware.php

Is it possible to do that?

sorry for the inconvenience and thank you
