### ISSUE TITLE
 Argument 2 passed to Nwidart\Modules\Migrations\Migrator::__construct() must be an instance of Illuminate\Contracts\Foundation\Application, instance of Laravel\Lumen\Application given

### ISSUE THREAD

**Issue by Jimmea** [nWidart/laravel-modules#906]

**Comment by Jimmea** [comment]
"laravel/lumen-framework": "^6.0"
"laravel/lumen-framework": "^6.0"

**Comment by nWidart** [comment]
Hi,

I don't support luman anymore, so you'd have to find out how to make it work on your own.

**Comment by khoatran** [comment]
I've created the PR: https://github.com/nWidart/laravel-modules/pull/911 to solve this issue. Could you help to review it?
