### ISSUE TITLE
Cannot Update to latest version

### ISSUE THREAD

**Issue by levonmanucharian** [nWidart/laravel-modules#907]
I had the version for Laravel 5.5 and now wanted to update to the latest one. However no matter what I do, I always get this error:
"You don't have a valid activator configuration class. This might be due to your config being out of date. Run php artisan vendor:publish - provider="Nwidart\Modules\LaravelModulesServiceProvider" --force to publish the up to date configuration"

Publishing the vendor does work because  this same message appears when I try to run any artisan command. Tried copying the config file manually, even after that getting the same message.
Tried with another project on Laravel where Laravel-modules was never installed - same message appears but this time it happens when I try to create a module, the initial vendor:publish works fine.

Any help is highly appreciated.

**Comment by nWidart** [comment]
you need to publish the configuration of this module. Run the following:

```
php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"
php artisan module:v6:migrate
```

**Comment by levonmanucharian** [comment]
@nWidart Thanks for the heads up. I have no idea what I did exactly that made it work now because previously none of the commands you mentioned were working. Anyway, works fine now so the issue can be closed, thanks again.

**Comment by nWidart** [comment]
Nice, I'm glad it worked out. 👍
