### ISSUE TITLE
how to install module (node js ) dependencies ? 

### ISSUE THREAD

**Issue by samerzaki** [nWidart/laravel-modules#909]
Hello,
I want to let each module install their dependencies for (node js) just as it does in php using (package.json file).
I can easily define all dependencies in module package.json file and run "npm install", but this install all packages in node_modules in the module directory.
I want all modules to install their dependencies in the node_modules in root directory.

**Comment by messi89** [comment]
Just put your dependencies in your Modules/{YOUR_MODULE}/package.json

than 
cd  Modules/{YOUR_MODULE}
npm i

**Comment by nWidart** [comment]
Hi,
For that you need to define the dependencies in the root package.json file.
I'm not aware of a `composer merge plugin` for npm.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by luizeduardocostaml** [comment]
Any solution for this ? I'm trying the following command: `npm install --prefix /Modules/Mymodule` but no success.

**Comment by Chomiciak** [comment]
Hello, a working solution is needed - was it found yet? What I mean by _working solution_, is one that is autoloading dependencies of modules
