### ISSUE TITLE
deleting module throwing exception module.json not found

### ISSUE THREAD

**Issue by chiragkanjariya** [nWidart/laravel-modules#910]
I've created a demo module user in my project. now I've deleted that module and my project throwing an exception as follows.
![image](https://user-images.githubusercontent.com/17644894/72704018-67675f00-3b7d-11ea-81da-31dbc8309496.png)

I tried to clear cache but it throws the same error.

![image](https://user-images.githubusercontent.com/17644894/72704168-00967580-3b7e-11ea-9041-930be2664cf3.png)

**Comment by nWidart** [comment]
How did you delete this module? Did you use the `module:delete` command?

If not, open the module-statuses file and remove the user module from it. You can find where this file is located from the config.

**Comment by chiragkanjariya** [comment]
I tried deleting modules by command but still, it throws the same error until I clear cache manually by deleting data folder from here "www/storage/framework/cache/data"

**Comment by nWidart** [comment]
Yeah that can happen if you cached configuration, views or routes for instance. Either way it's always good to clear the cache after deleting a module (and a composer dump autoload).

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
