### ISSUE TITLE
How to use the laravel-modules and laravel-menus libraries

### ISSUE THREAD

**Issue by Stenfrank** [nWidart/laravel-modules#912]
I am currently managing modules with laravel-modules, install laravel-menus but what I want is that the module that manages with laravel-modules adds the menu dynamically, validates the documentation and does not talk about how to integrate laravel-menus with laravel-modules.

Also validate the AsgardCms modules but always extend from "Modules\Core\Sidebar\AbstractAdminSidebar".

Could you give me an example.

Thank you.

**Comment by nWidart** [comment]
You can see an example in AsgardCms, modules add their items dynamically onto the menu.

**Comment by Stenfrank** [comment]
Thanks is already working
