### ISSUE TITLE
Question - Lock console delete for a module 

### ISSUE THREAD

**Issue by rajakhoury** [nWidart/laravel-modules#913]
Hi, this is more of a question maybe I missed something in the docs. 
Is there an option to disable the module delete command for certain modules? Maybe adding a flag in the module.json file? 
I accidentally deleted a module and it worries me what if that module was not just a test.. 

Thank you.

**Comment by nWidart** [comment]
Hey,

There is no such option. 
Such a flag could be added indeed, or maybe a confirmation message when deleting a module? 
Although you should have version control to revert the deletion anyway.

**Comment by rajakhoury** [comment]
Yes I agree. This was a silly question :) but a confirm message might be a good idea.
