### ISSUE TITLE
Use modules to another project

### ISSUE THREAD

**Issue by John-Dear** [nWidart/laravel-modules#914]
How can i use one of my previously developed module to my new laravel project? Basically, how to import and register modules in newly created projects?

**Comment by nWidart** [comment]
Hi, 

That's all up to you. 
In general though you can register the modules in composer, and require them on other projects just as you would with packages.
Look through the modules of [AsgardCMS](https://github.com/AsgardCms/Platform) if you need inspiration.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by sarmadmahar** [comment]
I have same question I have sample module git@github.com:sarmadmahar/module1.git how can I use it into my another project XYZ ?  `composer require sarmadmahar/module1` not working
