### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by AEK-BKF** [nWidart/laravel-modules#916]
Hi,
I'm using L5.6, please could you set us an example about how to use api routes for a module?
I tried to create api.php beside route.php but I didn't get it working !

Thanks.

**Comment by andersonpem** [comment]
Have you tried to list the endpoints available in your application? Do a php artisan route:list and see if you can find the API routes you have specified. It's probably something like /yourmodulename/api/endpoint

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
