### ISSUE TITLE
route globally modules

### ISSUE THREAD

**Issue by didiwijaya** [nWidart/laravel-modules#917]
How to add subdirectory/route globally in all modules (not in route of module)?
For example : domain.com/{subdirectory}/home

**Comment by nWidart** [comment]
Lots of ways to do this. One way I did in AsgardCMS: https://github.com/AsgardCms/Platform/blob/3.0/Modules/Core/Providers/RoutingServiceProvider.php#L91

Have a base provider that sets the prefixes for all modules.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
