### ISSUE TITLE
Ajax Validation Message

### ISSUE THREAD

**Issue by Nagasir** [nWidart/laravel-modules#918]
Thank you for this awesome package.

Lang module works with multiple locale using this 
`trans('yourmodule::file.key')` or `@lang('yourmodule::file.key')`

However lang validation translation from ajax 422 return message  always return lang from laravel root folder not from Modules folder itself.  

My app locale has been set successfully to `id` and I already add new lang for validation under `Modules/Backend/Resources/lang/id/validation.php`
and when I try to validate
`$request->validate([
            'email_to' => 'required|email',
            'email_message' => 'required'
        ]);`

it always returns error messages from `rootApp/resources/lang/en/validation.php`

**Comment by mikemand** [comment]
Hi, you need to tell Laravel to use your validation message using the [second parameter](https://laravel.com/docs/6.x/validation#custom-error-messages) of `$request->validate()` (third parameter if using the facade or the controller's helper method `$this->validate()`):

```php
$request->validate(
	[ 'email_to' => 'required|email', 'email_message' => 'required' ],
	['required' => trans('yourmodule::file.key')]
);
```

**Comment by Nagasir** [comment]
Thank you for your solution and it works, but it would be a lot of stuff todo to make it work by using second parameter for all translation key other than just having translation folder in each module.

If I put translation folder root laravel  like `rootApp/resources/lang/id/validation.php`
it works as expected without using second parameter.

Should this issue being considered as feature request or improvement?  It would be awesome, or it can't be implemented at all?

**Comment by mikemand** [comment]
I'm not sure if what you want is possible with Laravel. I know you can [tell Laravel about your translations](https://laravel.com/docs/6.x/packages#translations), but I don't think you can override the default validation messages with a package's (or in this case, a module's) without doing so for every validation.

You could try [Form Requests](https://laravel.com/docs/6.x/validation#customizing-the-error-messages) to limit the amount of repetitive validation, but this won't work if you have a lot of different validation to do.

**Comment by Nagasir** [comment]
Ok cool, for now I'll be using Laravel lang default folder for translation validation only. 

Thank you for your responses.
