### ISSUE TITLE
[FEATURES] Add in config params for generate .gitignore

### ISSUE THREAD

**Issue by livevasiliy** [nWidart/laravel-modules#919]
Hello @nWidart, I have idea add to config/modules.php param for generate base .gitignore file for each generate module like .gitkeep

**Comment by nWidart** [comment]
Hi,

Why not yeah. I wouldn't do this in this project directly, but you can easily extend the generation and add things you want custom to your likings. (I did this in AsgardCMS for instance).

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
