### ISSUE TITLE
Question: Drop in from Pingpong/Modules

### ISSUE THREAD

**Issue by jandayanan** [nWidart/laravel-modules#92]
Hi,

Is it possible to drop in the entire Modules/ folder of PingPong/Modules to the Modules folder generated by this? I want to migrate from the older PingPong modules to this one for maintainability and upgrade to Laravel 5.3

Thanks

**Comment by adelowo** [comment]
Yes.. The only changes would be namespace changes, I think.  You should check 

- generated class (for those generated with the `module` command in ping pong ) 
- The service provider in `config /app.php`
- Any other place you __manually_ referenced a class from ping pong.

**Comment by nWidart** [comment]
This is indeed possible. 👍  (What I did on asgardcms, was simply switch the package)
