### ISSUE TITLE
Cannot declare class Modules\Users\Providers\RouteServiceProvider, because the name is already in  use

### ISSUE THREAD

**Issue by carveybunt** [nWidart/laravel-modules#920]
- **when I run command of "php artisan module:make-model User User" or "php artisan module:make-controller UsersController User",I get the error of " Cannot declare class Modules\Users\Providers\RouteServiceProvider, because the name is already in
use"**

My module name is User,I wanna create a controller of user, and create a model of user.
Someone can give me a hand? How can I fix this error，please?

![image](https://user-images.githubusercontent.com/37894474/74162759-45cd3500-4c5c-11ea-8860-749173e8bcd3.png)

**Comment by nWidart** [comment]
Hi,

Hard to see, but it looks like there are multiple route service providers in the same module?

For sure you can have a `UsersControllers` and model `User`, I've done this many times.

**Comment by carveybunt** [comment]
Thanks, I will checking it again. But I'm sure i just only had a module User.

**Comment by vtscarlos** [comment]
The problem is that you cannot have two routes with the same name, it is a problem that I am having with the package, since I use modules to rewrite methods of my main laravel
