### ISSUE TITLE
Modules Routes Not listed

### ISSUE THREAD

**Issue by ahmedfathi1** [nWidart/laravel-modules#924]
After upgraded from 5.8 to 6.9 the home page giving me 404 page not found because it's in module route not in main web.php file 

All routes in `routes/web.php` are working fine
but any routes in in `Modules/<module-name>/routes/web.php` not working
the command `php artisan route:list` showing the list of routes in main web.php file only

**Comment by ahmedfathi1** [comment]
After running `php artisan module:v6:migrate` every thing working fine

**Comment by nWidart** [comment]
Great.

**Comment by popouille** [comment]
Hello,
Exactly same problem, but `php artisan module:v6:migrate` doesn't solve it.

**Comment by JunaidQadirB** [comment]
I'm on version 7.1 and I can't list the routes and opening the URL gives a 404. The module shows in the modules list. 

What am I doing wrong? Please help

**Comment by AmirHoseinBahrami** [comment]
just run php artisan route:cache
