### ISSUE TITLE
module:route-provider bug

### ISSUE THREAD

**Issue by tonamson** [nWidart/laravel-modules#925]
1. I create Module Company then i create then i try command **php artisan module:route-provider Company**, it's will show message error 

> File : path../Modules/Company/Providers/RouteServiceProvider.php already exists.

2. I try to remove RouteServiceProvider.php then run command again 

> Class 'Modules\Company\Providers\RouteServiceProvider' not found

Try to run composer dumpautoload it can't run command

**Comment by nWidart** [comment]
Hi,

Look in your module.json file, it probably has the new service provider added.

**Comment by tonamson** [comment]
Ok many thanks
