### ISSUE TITLE
Suggestion: Add extra infos for Module Object

### ISSUE THREAD

**Issue by AEK-BKF** [nWidart/laravel-modules#927]
Hi,
Thank you so much for this wonderful package !
I think it'll be useful to add extra infos for Module object, such as Icon, Description, Depends, ...
So when we call for example `Module::find('name');` :
we can find something like this :
```
Name
Description
Icon
Depends
Version
Active
Installed
... etc
```

Thanks :)

**Comment by nWidart** [comment]
Hi,

You could already do this now. Just add the keys, and use the [get method](https://github.com/nWidart/laravel-modules/blob/master/src/Json.php#L209) of the json class.

**Comment by AEK-BKF** [comment]
Thanks :)
