### ISSUE TITLE
Do not load standard module

### ISSUE THREAD

**Issue by demesiooliveira** [nWidart/laravel-modules#929]
I have an application developed in Laravel and I am thinking of changing the mudulos to laravel-modulos, however when performing a test I realized that when creating a module it overwrites all calls to that module. Is there any way to disable this?

`Action Modules\Colaborador\Http\Controllers\Auth\RegisterController@index not defined.`

the correct would be

`App\Http\Controllers\Auth\RegisterController@index`

**Comment by nWidart** [comment]
That's just how laravel route works. You can go around this by changing the order the routes are read.

**Comment by demesiooliveira** [comment]
@nWidart where can I make this change? In web.php?

**Comment by nWidart** [comment]
That would depend on your app. You'd have to change how the route providers are loaded from within the modules. Up to you to decide how you want to approach this. They're loaded by default in the module.json.

**Comment by demesiooliveira** [comment]
@nWidart I believe that I did not explain my doubt well.

I have a controller called `App\Http\Controller\TestController.php`, when I make a call
  inside the blade for example `TestController@index` it is automatically overwriting the namespace of` TestController@index` to `Modules\TestModule\Http\Controllers\TestController @ index`, ** TestModule ** being the module created.

My question is, how do I not overwrite the module's namespace automatically?

```
<div class="row">
    {!! Form::open(['action' => ('RegisterController@index'), "method" => 'GET']) !!}
    <div class="col-md-6">
        {!! Form::text('filtro_nome', isset($nome) ? $nome : null, ['class' => 'form-control', 'maxlength' => 255, 'placeholder' => 'Nome']) !!}
    </div>
    <div class="col-md-3">
        <button type="submit" class="btn btn-primary btn-flat btn_icon_filter"><span class="glyphicon glyphicon-filter" aria-hidden="true"></span>&nbsp; Filtrar</button>
        <a href="{{url('/user')}}" style="margin-left: 10px;" class="btn btn-primary btn-flat btn_icon_filter"><i class="fa fa-eraser"></i></a>
    </div>
    {!! Form::close() !!}
</div>
```

**Comment by nWidart** [comment]
I still have no idea what you're trying to do 😅

Controllers can't overwrite each other, that concept doesn't exist. Routes can though.
This is not related to this package but again how laravel works.

**Comment by demesiooliveira** [comment]
kkkk @nWidart you are right..

The problem is in the functions of UrlGenerator. for some reason it is defaulting on the namespace of the first module created.

@nWidart if you can reproduce the problem, follow the step by step.

1. Create one route in routes/web.php `Route::get('/', 'TestController@index');`
2. Create one controller in app/Http/Controllers  `TestController` and inside it an index function that returns a view
``` 
public function index()
{
    return view('test');
}
```
3. Creare one view with a function to generate a url for an action
```
@extends('layouts.default')

@section('content')
    {{ action('TestController@index'); }}
@endsection
```

**Comment by nWidart** [comment]
You shouldn't create routes in web.php ...

Just use the normal routes, set them up, don't create routes that can overwrite each other, and everything will work.
