### ISSUE TITLE
How to make helper in module

### ISSUE THREAD

**Issue by gzai** [nWidart/laravel-modules#93]
Hi,

How to make helper in module, so we can use global to other module?

**Comment by nWidart** [comment]
Hello,

What do you mean by helper ? If you mean a helper.php file with simple php functions, yes that's possible by adding that filename to the `module.json` `files` key.
Yes a module can use classes/functions from another module.

**Comment by rBrda** [comment]
Hello,

I have a very similar problem.
How can I register a function for all modules, where the function namespace is always the current module namespace?

I want to write a localization function, where I need to know which one is the current module, so I can load the appropriate localization file.
I can create a global function, but I cannot tell which module is the caller, that's the problem what I'm trying to solve. Localization files are modules based.

**Comment by armababy** [comment]
It seems to me that you are describing a Trait, that exists in Localization module. You can use many php functions to find out which class or namespace called this method.

Mainly maybe Reflections for `get_called_class()` and thereafter you can get anything that reflections offer.

**Comment by gzai** [comment]
@nWidart 
I create Module A with helper.php and Module B with helper.php
when I use helper.php in Module A can't call a function in helper.php in Module B
how to solve that?

**Comment by RahulGupta2312** [comment]
@nWidart I am trying to create a helper in a module. So the helper is ideally returning a Facade. The helper method is working fine in the the Controller and Provider. But it says undefined in the blade files.

So I was creating a Menu Facade and adding the menu in the boot() method. And I want to use that helper function in the blade file to get access to the menu items and render it.
