### ISSUE TITLE
Asking about performance when enable/disable module at runtime?

### ISSUE THREAD

**Issue by dexcell** [nWidart/laravel-modules#930]
Hi,
I want to ask questions about laravel modules.

Let's say i have 2 subdomain url accessing the same laravel app.
1st subdomain needs module A, and module B and module C.
2nd subdomain needs module B, and module D.

Therefore i had to enable / disable module dynamically based on subdomain on every http request,
I already did this, but is this performance wise?

Where does laravel modules save the enabled/disabled flag values? 
Because it looks like it's persisted, i tried to restart the server but laravel modules still persist the enable/disable value flag.
So i suspect laravel modules write the values to file?
Can i change it to memory?

Thank you

**Comment by nWidart** [comment]
Hi,

You can disable/enable dynamically yes, that's all up to you to architect your application. 
Look at the classes in the package, hint `Module` and you'll find it.

**Comment by dexcell** [comment]
Hi thanks for your response.
I dig up the source, looks like the value is written to `modules_statuses.json`, because we are using FileActivator.

To change this i had to write another activator, right?

Thank you

**Comment by nWidart** [comment]
Correct yeah. You can implement the database yeah, I think there's a PR for it somewhere

**Comment by dexcell** [comment]
Thank you! hopefully it will saves some dev time.

**Comment by sprklinginfo** [comment]
Hello @dexcell,
I want to achieve what you described here as I am trying to make a multi-tenancy setup. With each domain, I hope to enable/disable different modules dynamically. Could you share what you've done in order to achieve this? and you mentioned FileActivator, what is that for? Thank you for your guidance!
