### ISSUE TITLE
Moving Module Routes Before Main Routes 

### ISSUE THREAD

**Issue by virgiltu** [nWidart/laravel-modules#931]
I have a slight issue and I have been spinning my head around it. 

I have a route that will catch any slug structure. This is because my cms will need to have many sub pages. 

Here is my setup in the main Web Routes file of the Laravel app not the modules

```
Amin Routes ........
//Pages
 Route::get('/{slug}', 'HomeController@pages');
 Route::get('/{slug}/{sub_slug}', 'HomeController@sub_page')->where('sub_slug', '.*');
 Route::get('/', 'HomeController@index');
```

Now I can hit any admin route defined above the //Pages 
I can also hit any Slug page. 

My Web routes file from the module 

```
Route::prefix('articles')->group(function() {
    Route::get('/all/', 'ArticlesController@articles');
    Route::get('/{slug}', 'ArticlesController@article');
    
});
Route::resource('/admin/articles', 'ArticlesController')->middleware('auth');
```
So above I can hit the route /articles and /articles/all from the user side, but I can not hit the /admin/articles because the about /{slug}/{sub_slug} will catch it first. 

I am trying to put the /{slug}/{sub_slug} last. Is there any way to have laravel read the route from the modules and than the web ? 

web - laravel
web - module

**Comment by virgiltu** [comment]
Just an update if I include

`Route::get('/{slug}/{sub_slug}', 'HomeController@sub_page')->where('sub_slug', '.*');`

in my module after 
`Route::resource('/admin/articles', 'ArticlesController')->middleware('auth');`

it works fine but if I have more modules that will kind not make it ideal for modules distribution.

**Comment by mikemand** [comment]
You could try the [`fallback` route](https://laravel.com/docs/6.x/routing#fallback-routes), but it would only work for one of the two (either your `slug` route or the `sub_slug` route, but not both).

Other than that, you'll have to register your Modules in such a way that your routes that are meant to catch everything are registered after all the rest of the Modules have registered their routes.

**Comment by virgiltu** [comment]
Crap not sure how I missed that. Thank you the fall back worked perfectly.

**Comment by mikemand** [comment]
No worries. It's pretty new. Laravel 5.7? Maybe Laravel 5.8... I can't remember when it was added exactly.
