### ISSUE TITLE
REQUEST MODULE API

### ISSUE THREAD

**Issue by moises-devfametro** [nWidart/laravel-modules#932]
I created 2 module called API and WEB in a laravel project that I am developing. The API module has the LDAP authentication business rule that gives access to the system. In the WEB module, I developed the application frontend. When the user logs into the application, a POST http request is made to the API module's authentication endpoint, but the application is in a loop and nothing happens. How do I make requests for the API module correctly? 

1° How to make the request - result: cURL error 6: Could not resolve host: api

```
 public function store(Request $request, Client $client)
     {
         $credenciais = [
             "username" => $request->input("username"),
             "password" => $request->input("password")
         ];
         $result = $client->post('api/backoffice/login', $credenciais);
        dd($result->getBody());
    }
```

2° How to make the request - result: Loop
```
    public function store(Request $request, Client $client)
    {
        $credenciais = [
            "username" => $request->input("username"),
            "password" => $request->input("password")
        ];
        $result = $client->post('http://127.0.0.1:8000/api/backoffice/login', $credenciais);
        dd($result->getBody());
    }
```

**Comment by nWidart** [comment]
Hi,

Api calls work just like in laravel, there's nothing specific or different about this package.
You create your route(s), which are loaded via the RouteServiceProvider, nothing else.

Try to find where the request is received, and go from there I'd say.

**Comment by moises-devfametro** [comment]
> Oi,
> 
> As chamadas da API funcionam como no laravel, não há nada específico ou diferente neste pacote.
> Você cria suas rotas, que são carregadas pelo RouteServiceProvider, nada mais.
> 
> Tente descobrir onde a solicitação é recebida e vá de lá, eu diria.
> O Stackoverflow provavelmente seria um local melhor para fazer esta pergunta.

OK thank you
