### ISSUE TITLE
i cannot run this comman;php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"

### ISSUE THREAD

**Issue by Dave2424** [nWidart/laravel-modules#933]
Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Modules\Client\Providers\ClientServiceProvider' not found

  at /var/www/html/Laravelprojects/mgt/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:208

**Comment by djunehor** [comment]
Run `composer require nwidart/laravel-modules` again and ensure it complete successfully. Then try running `php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider"` again
