### ISSUE TITLE
module:migrate-refresh throws error when no option is provided.

### ISSUE THREAD

**Issue by logic-exception** [nWidart/laravel-modules#935]
From the docs:
**module:migrate-refresh**
Refresh the migration for the given module, or without a specified module refresh all modules migrations.

• When running the command without the module name it throws "TypeError: Argument 1 passed to Nwidart\Modules\FileRepository::find() must be of the type string, null given" when it should refresh all the modules.
• FileRepository::find(string $name) accepts string typed parameter, so we cannot pass null values and an error is thrown.
• Inside MigrateRefreshCommand::getModuleName() checking for null module before calling the FileRepository::find() or making FileRepository::find() accept Nullable parameter seems to solve the problem.

**Comment by nWidart** [comment]
Thank you for reporting the issue, I'll take a look at it.

**Comment by garbinmarcelo** [comment]
I got the same error here.

Laravel: v7.4.0
laravel-modules: 7.0.0

**Comment by ugurdnlr** [comment]
I'm having the same problem. Have there been any developments?
