### ISSUE TITLE
Theme with modules

### ISSUE THREAD

**Issue by nasirkhan** [nWidart/laravel-modules#937]
Is there any package or approach available when i can use themes for views. I found a number of packages, but got confused about those. Although there might be some other way out to use theme. Please advice.

**Comment by nWidart** [comment]
This is the one I use in AsgardCMS: https://github.com/floatingpointsoftware/stylist

**Comment by nasirkhan** [comment]
Thanks, It shows that the last commit on the package was  Aug 9, 2018. Do you think it is ok to use as it has not been updated for a long time?

**Comment by nWidart** [comment]
Try it out and see for yourself I'd say :D
