### ISSUE TITLE
Module Folder Structure

### ISSUE THREAD

**Issue by bryandeasis** [nWidart/laravel-modules#938]
Hi, I just want to ask, is there a way to separate the front end modules to backend modules like.

/Modules
/Modules/FrontEnd/<Module>
/Modules/BackEnd/<Module>
/Modules/Core/<Module>

Something like that.

Please let me know if it is possible.

**Comment by andersonpem** [comment]
Watching

**Comment by nWidart** [comment]
You could already do this now yes. I wouldn't advise it but you can.

**Comment by bryandeasis** [comment]
How can I do it? I'm actually just new at laravel. Thank you

**Comment by nWidart** [comment]
You can create these 2 modules. In one you would only do front-end stuff, in the other only ui stuff.
