### ISSUE TITLE
Route URL generator gives "Missing Required Parameters"

### ISSUE THREAD

**Issue by irvine48** [nWidart/laravel-modules#941]
Laravel 7.1.0
Laravel Module 7.0-dev

```
Route::domain('www.test.local')->name('backstage.')->group(function() {
    Route::get('/users', 'UserController@index')->name('user.index');

```

*php artisan route:list show route cached.

1. named route call in blade `route("backstage.user.index")` will triggered error.

2. this suppose to be non parameter's route, it keep showing missing parameters error.
tested on original route file web.php with named route (home) does't trigger any error.

if copy backstage controller in web.php (original)
```
Route::get('/users', '\Modules\Backstage\Http\Controllers\BackstageController@index')->name('backstage.user.index');
```
it work as usual.

*note that, if using URL directly like /user, it work as usual.

**Comment by nWidart** [comment]
Hm interesting, not really sure why this is happening. I don't see anything relevant in the upgrade guide.

**Comment by irvine48** [comment]
https://github.com/laravel/framework/issues/31744

this might be related? i not really sure is related. But similar error. I not using route:cache, not sure they are related or not.

**Comment by nWidart** [comment]
I tried to reproduce your issue and it's working fine for me.

I created a new route

```
Route::prefix('recipe')->group(function() {
    Route::get('/', 'RecipeController@index');
    Route::get('/users', 'RecipeController@show')->name('backstage.user.index');
});
```
in my index view, I have a link:
```
    <a href="{{route('backstage.user.index')}}">link 1</a>
```
Then I ran `php artisan route:cache` (I had to comment all default laravel routes... 🤦‍♂ )

Then I refreshed the page with the `route()` link, and it still worked.

**Comment by irvine48** [comment]
do i need to route:cache it to make it work?

**Comment by nWidart** [comment]
Ah then I misunderstood your error, I thought you had this with cached routes only.

Either way, I still can't reproduce the issue. Even before caching the routes, they still work.

**Comment by nWidart** [comment]
Just tested with this too, and works as well:
```php
Route::prefix('recipe')->name('backstage.')->group(function() {
    Route::get('/', 'RecipeController@index');
    Route::get('/users', 'RecipeController@show')->name('user.index');
});
```

**Comment by irvine48** [comment]
hmm... i guess i found the issue, might be the 

> domain('www.test.local')

i removed it and all work as usual.

anything related to this?

**Comment by nWidart** [comment]
I used it in modules too before and never had any issues with it so no idea.

**Comment by irvine48** [comment]
alright, i think may be issued on domain('{www}.test.local')

bracketed "www" parameter "missing" in this case.

**Comment by mikemand** [comment]
Yeah, your original post didn't show those brackets... If they were there, then yes anything within that group is going to require at least one parameter for the `$www` variable. If you remove the brackets, it will be fine.
