### ISSUE TITLE
I am getting the below error when I try to run "php artisan serve" to start the server.

### ISSUE THREAD

**Issue by daguah** [nWidart/laravel-modules#942]
` Exception trace:

  1   require()
      C:\XAMMP\htdocs\pizzahouse\vendor\laravel\framework\src\Illuminate\Routing\RouteFileRegistrar.php:35

  2   Illuminate\Routing\RouteFileRegistrar::register("C:\XAMMP\htdocs\pizzahouse\routes/web.php")
      C:\XAMMP\htdocs\pizzahouse\vendor\laravel\framework\src\Illuminate\Routing\Router.php:416

  Please use the argument -v to see more details.`

**Comment by nWidart** [comment]
Hi,

As you can see from the error message it's not from this package.
Make sure the file mentioned (`routes/web.php`) exists, or remove the reference to it.

**Comment by daguah** [comment]
Thanks for replying my message.

The file exists but the error is still there

**Comment by daguah** [comment]
I have got the problem and solved it, thanks.
