### ISSUE TITLE
[7.0-dev] package.json inside modules outdated.

### ISSUE THREAD

**Issue by irvine48** [nWidart/laravel-modules#944]
tried with original generated package.json `php artisan module:make`
1. `yarn install`
2. `npm run watch` failed.

original

>     "devDependencies": {
>         "cross-env": "^5.1.4",
>         "laravel-mix": "^4.0.7",
>         "laravel-mix-merge-manifest": "^0.1.2"
>     }

Modify package json dependency match to laravel 7.2.0 original version, it will compile `module.js` and `module.css` without error.

alter

>     "devDependencies": {
>         "cross-env": "^7.0",
>         "laravel-mix": "^5.0.1",
>         "laravel-mix-merge-manifest": "^0.1.2"
>     }

*I am wonder is that possible generate by copy these lines from original package.json (root) instead of generate from pre define template.

**Comment by nWidart** [comment]
You can send a pull request with the fix.

**Comment by nWidart** [comment]
Has been fixed in https://github.com/nWidart/laravel-modules/commit/c3c8997e397da3ceab9708f13338f9473d4d3362
