### ISSUE TITLE
Support Laravel 7

### ISSUE THREAD

**Issue by garbinmarcelo** [nWidart/laravel-modules#945]
Hi, I'm starting a new installation of Laravel 7, is this package already supported for this new version?

I ran the following command: `composer require nwidart/laravel-modules` in this case, version 6.2 was installed.

Is that correct? If not, how can I use it with the Laravel 7 version or is it currently not possible?

Thanks for this wonderful package =)

**Comment by nWidart** [comment]
Hi,

You can by using `7.0-dev` currently.

**Comment by garbinmarcelo** [comment]
Do I have to use it that way? 

composer.json
`"nwidart/laravel-modules": "^7.0"`

**Comment by ckissi** [comment]
"nwidart/laravel-modules": "^7.0-dev"

**Comment by garbinmarcelo** [comment]
Do you have any plans to release version 7 for production / master?

Thank you, I will close this issue.

**Comment by nWidart** [comment]
Yup, I just wanted to make sure everything was working fine before tagging. Since it has been available for a bit now, I'll do it asap.
