### ISSUE TITLE
[Discussion] Change config file to lowercase `modules`

### ISSUE THREAD

**Issue by bert-w** [nWidart/laravel-modules#946]
I noticed that the config file uses `Modules` as the directory name for all modules, whereas the default laravel setup (for all base directories) is lowercase.

See https://github.com/laravel/laravel for the default generated Laravel project that uses lowercase directories (except when entering the top level folders).

https://github.com/nWidart/laravel-modules/blob/master/config/config.php#L73
```php
        'modules' => base_path('Modules'),
```

Personally this caused me 30 mins of debugging because it wasn't immediately obvious to me why my modules wouldn't load. It gave me a "hintpath not found" error indicating that the view path was not being loaded, but that didn't point me in the right direction.

Now this is only an issue on UNIX systems where case sensitive directories are different.

So i suggest one of 3 solutions:
- Change the default config file to use `'modules'`
- Make a note somewhere in the docs
- Handle the situation manually in this package such that it throws an exception when the modules directory could not be found

Feedback appreciated.

**Comment by nWidart** [comment]
Hi,

This is fully configurable, no need to change the base configuration for this as it can be changed.
