### ISSUE TITLE
Define Controller type when creating the module

### ISSUE THREAD

**Issue by garbinmarcelo** [nWidart/laravel-modules#947]
Hello,
The package offers 3 types of controllers, web, api and plain.

Would it be possible when a new module is created to define the type of controller to be created? (I checked the documentation and has only the --plain)

Example, I use the package for creating api. In this case there would be a command like: 
`php artisan module:make User --api`

I believe that this would be a useful resource, you could consider that for v7... :smile:

**Comment by kkornwinkel** [comment]
Hi,
I agree with @garbinmarcelo
That would be a great feature for model-based automated API creation

**Comment by nWidart** [comment]
Hello,

Sorry for the late reply. I like this idea as well.

The default could stay as is, and then

- module:make User --web
- module:make User --api
- module:make User --plain

for example
