### ISSUE TITLE
Stub plural constants question

### ISSUE THREAD

**Issue by garbinmarcelo** [nWidart/laravel-modules#949]
Hello, 
generally when we want to define stubs we use constants such as: 
- `$STUDLY_NAME$`
- `$LOWER_NAME$`
- ...

I would like to know if there are any of these constants that the name of the module, example `$LOWER_NAME$` is written in the plural.

If so, what would be the constant? If not, how would you create this? How can I do it...

Thank you for your help

**Comment by nWidart** [comment]
hi,

I'm not sure what you're asking.
You can check each command for their values if you're looking for that.

**Comment by garbinmarcelo** [comment]
Okay, I'll give you an example to try to explain it better.

With his package it is possible to define custom stubs, and this is one of the most amazing things I think of him.

![image](https://user-images.githubusercontent.com/9335588/77678745-60d7d800-6f70-11ea-8049-f66ea41d9f0f.png)

Usually I place the stubs folder at the root of my project and customize some files, such as the controller.stub file

![image](https://user-images.githubusercontent.com/9335588/77678849-8bc22c00-6f70-11ea-9033-966c581f2b9b.png)

In this example I'm using the constants: `$STUDLY_NAME$` and `$LOWER_NAME$` (if that's what you call it).

In this example of commented code I am using the swagger for documentation of the apis, in which case we know that the standard endpoints are used in the plural.

After running the command to create the module: `php artisan module:make Teste`
![image](https://user-images.githubusercontent.com/9335588/77679182-f8d5c180-6f70-11ea-9680-ac92af0de8ce.png)

Where I want to go is, in addition to using the constants mentioned (STUDLY, LOWER), it would be possible to use / create for example a constant called `$PLURAL_NAME$`?


In that case in the place where you have commented `/teste` would be `/testes` after creating a new module, controller, model, etc..

**Comment by nWidart** [comment]
Ah, I see, thank you for the additional explanation. 😄 
These constants could be added but I'm wondering how much value these would bring.
You could also achieve this by wrapping the generation commands.

Maybe allow commands to be extended and adding new constants that way.

The easier solution would clearly be adding `_plural` on some constants, I'm only wondering if it's the best approach going forward.

**Comment by garbinmarcelo** [comment]
now it’s me who don’t know if i understand very well what you mean :sweat_smile:

What you mean is to define constants in a file (without being associated with this package) and use them within other files such as: controller, model, etc ... would that be?

If so, the problem is that I can't call variables or functions within comments, in the case of, for example, Swagger comments for documentation.

That's why I liked this approach of constants in your package, if you could propose at least one for this api URI issue it would be wonderful.

(In fact it would not be a problem, it would be an additional gain in development agility.)

what i think of idea would be to use $LOWER_NAME$ as $PLURAL_NAME$, which would use the module name to generate the name. 

Example: User, would be users.

It's an idea, I don't know if it would be possible.

**Comment by garbinmarcelo** [comment]
I currently use this helper in my config.php to call directly in my route files and it works normally, the problem is with comments.

![image](https://user-images.githubusercontent.com/9335588/77681858-bf9f5080-6f74-11ea-9509-29dd85642f2e.png)

**Comment by garbinmarcelo** [comment]
Taking advantage that we are talking about files of stubs, the one checked in this file. From what I saw, Laravel v7 no longer has this "extends Resource" (https://laravel.com/api/7.x/Illuminate/Http/Resources/Json.html). Now it would be JsonResource, I believe this is it.

https://github.com/nWidart/laravel-modules/blob/master/src/Commands/stubs/resource.stub

**Comment by garbinmarcelo** [comment]
I'm looking here that in the `migration/create.stub` file has the constant `$TABLE$`, this generates the plural name. Is it possible to use this constant inside a model.stub file? When I generate the model, do I rewrite it in the plural?

I tried here but it doesn't replace that constant after its generation, that's why I asked, I'm not sure. Thanks

**Comment by nWidart** [comment]
These constants could be added yes. But I'm not sure of the value it would add.

Maybe a pull request would make this make clear.

**Comment by solomon-ochepa** [comment]
> These constants could be added yes. But I'm not sure of the value it would add.
> 
> Maybe a pull request would make this make clear.

I've been looking for a way to archive the same goal.

There are many occasions where a pluralized name would be of great help.

Currently, I simply add 's' to form a plural of any word, but we all know that is not applicable to all words.

Its benefits and values can't be measured or justified by you alone (there are many features we would never use, but there are included in many products). The value is when we need the feature, and there is a provision for it.

### Examples
- index routes (I prefer - `example.com/users`, instead of `example.com/user`).
- index routes (I prefer - `example.com/faculties`, instead of `example.com/faculty`).
- controller permissions (I like using - `$this->middleware(['permission:users.index'])->only('index')`, instead of `$this->middleware(['permission:user.index'])->only('index')`), etc.

In the case where I want to pluralize a word like 'faculty', I'll end up having `facultys`, instead of `faculties`!

Again, you can equally make a provision to add new constants in the config file.

Thank you.

**Comment by kikky7** [comment]
I also have an "issue" with single and plural naming.

In the docs, when making modules, you name them in plural form, but this generates everything in plural (model, controller, seeder, factory, policy, etc.), but Laravel naming convention for those files is singular, so it would be Post, not Posts for model and PostController instead of PostsController, and so on.
But on the other hand, plural form is used for migrations (and probably some other files/classes I can't think of right now).

So the best solution would be to generate module in singural form, for example quote, instead of quotes or post instead of posts? But how to generate those names required in plural form?

**Comment by solomon-ochepa** [comment]
> I also have an "issue" with single and plural naming.
> 
> In the docs, when making modules, you name them in plural form, but this generates everything in plural (model, controller, seeder, factory, policy, etc.), but Laravel naming convention for those files is singular, so it would be Post, not Posts for model and PostController instead of PostsController, and so on. But on the other hand, plural form is used for migrations (and probably some other files/classes I can't think of right now).
> 
> So the best solution would be to generate module in singural form, for example quote, instead of quotes or post instead of posts? But how to generate those names required in plural form?

You are getting the whole idea wrong!

We usually call a module by its plural form, e.g., the "Users" module.

When creating a module, always use the singular name form, e.g., User, Post, Booking, Employee, etc. This will generate all the necessary structures for you, including those required in plural form, such as the migration you mentioned.

**Comment by solomon-ochepa** [comment]
However, if you want to use the plural name format for a specific purpose, you'll need to customize the name after finishing creating the module.

Nevertheless, I will be submitting a PR to include the plural name format for lowercase and uppercase.

**Comment by kikky7** [comment]
Ok, but I was referring to the docs, where modules are named in plural: https://laravelmodules.com/docs/v11/creating-a-module.

**Comment by kikky7** [comment]
> > I also have an "issue" with single and plural naming.
> > In the docs, when making modules, you name them in plural form, but this generates everything in plural (model, controller, seeder, factory, policy, etc.), but Laravel naming convention for those files is singular, so it would be Post, not Posts for model and PostController instead of PostsController, and so on. But on the other hand, plural form is used for migrations (and probably some other files/classes I can't think of right now).
> > So the best solution would be to generate module in singural form, for example quote, instead of quotes or post instead of posts? But how to generate those names required in plural form?
> 
> You are getting the whole idea wrong!
> 
> We usually call a module by its plural form, e.g., the "Users" module.
> 
> When creating a module, always use the singular name form, e.g., User, Post, Booking, Employee, etc. This will generate all the necessary structures for you, including those required in plural form, such as the migration you mentioned.

I followed this suggestion, but it still has issues.

You said "we usually call a module by its plural form", but when creating it to use singular - this produces module name in singular also, so there is requirement to manually update module name. Also this approach saves routes (path and name) as singular also, instead of plural, which is the default naming convention in Laravel.

So if I create module Post, module name will be Post, not Posts and generated resource routes will be post.index (/post), post.create (post/create), instead of posts.index.

That's why I asked initialy for constant for plural name. I could use $TABLE$ which (probably) generates plural name.

Someone mentioned in comments that wouldn't bring value, but it would, since that's the suggested naming convention in Laravel. I also didn't find in docs where to add custom constants.

**Comment by solomon-ochepa** [comment]
> > > I also have an "issue" with single and plural naming.
> > > In the docs, when making modules, you name them in plural form, but this generates everything in plural (model, controller, seeder, factory, policy, etc.), but Laravel naming convention for those files is singular, so it would be Post, not Posts for model and PostController instead of PostsController, and so on. But on the other hand, plural form is used for migrations (and probably some other files/classes I can't think of right now).
> > > So the best solution would be to generate module in singural form, for example quote, instead of quotes or post instead of posts? But how to generate those names required in plural form?
> > 
> > 
> > You are getting the whole idea wrong!
> > We usually call a module by its plural form, e.g., the "Users" module.
> > When creating a module, always use the singular name form, e.g., User, Post, Booking, Employee, etc. This will generate all the necessary structures for you, including those required in plural form, such as the migration you mentioned.
> 
> I followed this suggestion, but it still has issues.
> 
> You said "we usually call a module by its plural form", but when creating it to use singular - this produces module name in singular also, so there is requirement to manually update module name. Also this approach saves routes (path and name) as singular also, instead of plural, which is the default naming convention in Laravel.
> 
> So if I create module Post, module name will be Post, not Posts and generated resource routes will be post.index (/post), post.create (post/create), instead of posts.index.
> 
> That's why I asked initialy for constant for plural name. I could use `$TABLE$` which (probably) generates plural name.
> 
> Someone mentioned in comments that wouldn't bring value, but it would, since that's the suggested naming convention in Laravel. I also didn't find in the docs where to add custom constants.

Laravel has never stated/practiced any convention/standard for Route (https://laravel.com/docs/11.x/routing).

Nevertheless, it's more appropriate to have route paths in plural (I've been rewriting the route paths manually for years).

While I am certain about the route paths, I cannot say the same for the route names. Names should remain in singular as used by Laravel and in conformity with the module naming convention (`modules/User` Routes: `user.index`, `user.create`, `user.edit`, `user.update`, `user.delete`, etc.).

I'll propose a quick-fix (PR) for the plural route names ASAP.

**Comment by kikky7** [comment]
> > > > I also have an "issue" with single and plural naming.
> > > > In the docs, when making modules, you name them in plural form, but this generates everything in plural (model, controller, seeder, factory, policy, etc.), but Laravel naming convention for those files is singular, so it would be Post, not Posts for model and PostController instead of PostsController, and so on. But on the other hand, plural form is used for migrations (and probably some other files/classes I can't think of right now).
> > > > So the best solution would be to generate module in singural form, for example quote, instead of quotes or post instead of posts? But how to generate those names required in plural form?
> > > 
> > > 
> > > You are getting the whole idea wrong!
> > > We usually call a module by its plural form, e.g., the "Users" module.
> > > When creating a module, always use the singular name form, e.g., User, Post, Booking, Employee, etc. This will generate all the necessary structures for you, including those required in plural form, such as the migration you mentioned.
> > 
> > 
> > I followed this suggestion, but it still has issues.
> > You said "we usually call a module by its plural form", but when creating it to use singular - this produces module name in singular also, so there is requirement to manually update module name. Also this approach saves routes (path and name) as singular also, instead of plural, which is the default naming convention in Laravel.
> > So if I create module Post, module name will be Post, not Posts and generated resource routes will be post.index (/post), post.create (post/create), instead of posts.index.
> > That's why I asked initialy for constant for plural name. I could use `$TABLE$` which (probably) generates plural name.
> > Someone mentioned in comments that wouldn't bring value, but it would, since that's the suggested naming convention in Laravel. I also didn't find in the docs where to add custom constants.
> 
> Laravel has never stated/practiced any convention/standard for Route (https://laravel.com/docs/11.x/routing).
> 
> Nevertheless, it's more appropriate to have route paths in plural (I've been rewriting the route paths manually for years).
> 
> While I am certain about the route paths, I cannot say the same for the route names. Names should remain in singular as used by Laravel and in conformity with the module naming convention (`modules/User` Routes: `user.index`, `user.create`, `user.edit`, `user.update`, `user.delete`, etc.).
> 
> I'll propose a quick-fix (PR) for the plural route names ASAP.

Actually, in the docs it's always used plural when creating resource routes: https://laravel.com/docs/11.x/controllers#resource-controllers and it's like that since Laravel version 5 (as I recall).
And when you create resource routes `Route::resource('photos', PhotoController::class);`, the names are also auto-generated in plural.

Maybe it's not "mandatory", but it's the suggested (and default) naming convention for most resource routes.

Regarding all that, yeah, it's just easier to update those issues manually.

**Comment by solomon-ochepa** [comment]
> Actually, in the docs it's always used plural when creating resource routes: https://laravel.com/docs/11.x/controllers#resource-controllers and it's like that since Laravel version 5 (as I recall). And when you create resource routes `Route::resource('photos', PhotoController::class);`, the names are also auto-generated in plural.
> 
> Maybe it's not "mandatory", but it's the suggested (and default) naming convention for most resource routes.
> 
> Regarding all that, yeah, it's just easier to update those issues manually.

We'll go with whatever is provided by default using the `Route::resource('photos', PhotoController::class);`

And, you are correct. I've added it to the PR!

Thanks for your contributions, @kikky7.
![Screenshot 2024-07-25 151457](https://github.com/user-attachments/assets/ec9fcd2e-6ef4-4dfe-bdb4-ff43815a65e8)
