### ISSUE TITLE
Class 'Modules\Sun\Providers\SunServiceProvider' not found

### ISSUE THREAD

**Issue by nitrogenium** [nWidart/laravel-modules#950]
Make an empty Laravel 7 project.

laravel new test_project -> successful
composer require nwidart/laravel-modules -> successful
php artisan vendor:publish -> successful
php artisan module:make Sun ->Module [Sun] created successfully

**Then an error occurs at any action:**

```
  Class 'Modules\Sun\Providers\SunServiceProvider' not found

  at vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:208
    204|      * @return \Illuminate\Support\ServiceProvider
    205|      */
    206|     public function createProvider($provider)
    207|     {
  > 208|         return new $provider($this->app);
    209|     }
    210| }
    211|
```

**Comment by nWidart** [comment]
You forgot to autoload your modules. It's in the readme and documentation.
