### ISSUE TITLE
Class 'Faker\Factory' not found

### ISSUE THREAD

**Issue by jpswade** [nWidart/laravel-modules#951]
If you have installed package `nwidart/laravel-modules` and run `composer install --no-dev` when `APP_ENV=local` then you will get this error:

```
In DatabaseServiceProvider.php line 78:
         Class 'Faker\Factory' not found  
```

This has been an issue for quite some time...

https://github.com/laravel/framework/issues/19635

**Comment by nWidart** [comment]
What was the fix for laravel?

**Comment by jpswade** [comment]
Scrap that, it was our own code registering factories incorrectly.
