### ISSUE TITLE
Nested Modules 

### ISSUE THREAD

**Issue by husseinferas** [nWidart/laravel-modules#952]
Is your feature request related to a problem? Please describe.
when you building a module structure project or HMVC (Hierarchical model–view–controller)
sometimes you need to use nested modules (module inside the module)

**Comment by nWidart** [comment]
Hu?
It's not a feature of this package. It also won't be supported as in my opinion it points to an issue in architecture.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
