### ISSUE TITLE
Class RouteServiceProvider not found

### ISSUE THREAD

**Issue by ognistyi** [nWidart/laravel-modules#955]
Composer:
`"laravel/lumen-framework": "^6.0",
"nwidart/laravel-modules": "6.2.0",`

`> php artisan module:make TestModule`

Open in browser:
Class 'Illuminate\Foundation\Support\Providers\RouteServiceProvider' not found

How to setup on lumen 6.x ?

**Comment by nWidart** [comment]
You forgot to autoload your modules as mentioned in the readme and documentation.

**Comment by ognistyi** [comment]
> You forgot to autoload your modules as mentioned in the readme and documentation.
No, autoload is OK. Lumen 6+ doesn't has illuminate/foundation/*. But it used in module template.

**Comment by nWidart** [comment]
Ah ok. I'm not surehow lumenn does autoloading, this package isn't fully supported in Lumen. Support was added by a community member, but as I don't and never used lumen in the past I can't support that feature.

**Comment by BehroozBvk** [comment]
> Ah ok. I'm not surehow lumenn does autoloading, this package isn't fully supported in Lumen. Support was added by a community member, but as I don't and never used lumen in the past I can't support that feature.

I made the changes and the problem was apparently fixed. I think make the changes in the repository.
If there is a problem, we will solve it with the support of other programmers.

Thanks

**Comment by dharmendrasha** [comment]
Still facing this issue

**Comment by SubjectXXX** [comment]
I see 

> > Ah ok. I'm not surehow lumenn does autoloading, this package isn't fully supported in Lumen. Support was added by a community member, but as I don't and never used lumen in the past I can't support that feature.
> 
> I made the changes and the problem was apparently fixed. I think make the changes in the repository. If there is a problem, we will solve it with the support of other programmers.
> 
> Thanks @nWidart @Hodel1

I'm still facing same issue, even though I have implemented those 5 changes (3 new files and 2 files changed). Do I need to do anything else or is there a problem with new functionality because you were probably doing it on v6, now v8 is out?

Maybe [Hodel1](https://github.com/Hodel1) would know?
