### ISSUE TITLE
When I am trying to create a module, get this Error

### ISSUE THREAD

**Issue by mubasher95** [nWidart/laravel-modules#956]
ErrorException 

  Trying to access array offset on value of type null

  at E:\Online Booking Project\voyageplantravel\vendor\nwidart\laravel-modules\src\LaravelModulesServiceProvider.php:58
    54|             return new Laravel\LaravelFileRepository($app, $path);
    55|         });
    56|         $this->app->singleton(Contracts\ActivatorInterface::class, function ($app) {
    57|             $activator = $app['config']->get('modules.activator');
  > 58|             $class = $app['config']->get('modules.activators.' . $activator)['class'];
    59| 
    60|             if ($class === null) {
    61|                 throw InvalidActivatorClass::missingConfig();
    62|             }

  1   E:\Online Booking Project\voyageplantravel\vendor\nwidart\laravel-modules\src\LaravelModulesServiceProvider.php:58
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Trying to access array offset on value of type null", "E:\Online Booking Project\voyageplantravel\vendor\nwidart\laravel-modules\src\LaravelModulesServiceProvide
r.php", [Object(Illuminate\Foundation\Application)])

  2   E:\Online Booking Project\voyageplantravel\vendor\laravel\framework\src\Illuminate\Container\Container.php:803
      Nwidart\Modules\LaravelModulesServiceProvider::Nwidart\Modules\{closure}(Object(Illuminate\Foundation\Application), [])

E:\Online Booking Project\voyageplantravel>

**Comment by nWidart** [comment]
Publish your configuration file again (use `--force` for example). New options have been added.

**Comment by waleedfaridworkland** [comment]
For anyone stumbling upon this at a later date and facing the same issue with Lumen.
I was not able to publish my configuration file since that was also throwing the same error.
So I just copied the config file from the github repository of this package and pasted it under src/config.
That solved the issue for me.
