### ISSUE TITLE
Module enabled event

### ISSUE THREAD

**Issue by nicolassamat** [nWidart/laravel-modules#958]
Hi,

I'm trying to fire the 'modules.xxx.enabled' event but it doesn't work.

I think it’s due to the fact that the module isn't boot when enabled event is fired.

It's a bug ? Someone has a workaround ?

Thanks

**Comment by nWidart** [comment]
From what I can see the event is fired. You can see this happening here: https://github.com/nWidart/laravel-modules/blob/master/src/Module.php#L194

Maybe try to debug from there to understand what's happening.

**Comment by nicolassamat** [comment]
@nWidart, it works when i catch the enabled event since laravel app  but it doesn't work when i try to catch them since an module

**Comment by nWidart** [comment]
Ah ok, that means you didnt register your event in your module.

Example:

```php
        $this->app['events']->listen(
            BuildingSidebar::class,
            $this->getSidebarClassForModule('page', RegisterPageSidebar::class)
        );
```
