### ISSUE TITLE
Make exclude config for ConsoleServiceProvider

### ISSUE THREAD

**Issue by vladyslavstartsev** [nWidart/laravel-modules#959]
Hi! Thanks for the project.

I'm trying to use this package with https://github.com/laravel-doctrine/
BUT I get console commands that I don't want. I mean I have own migrations commands for doctrine right now, so I don't need `Nwidart\Modules\Commands\MigrateCommand`

What I want is to able to remove so of them during the registration.

My idea is to put exclude commands array somewhere in`config.php`

**Comment by nWidart** [comment]
Hi,

You don't need to exclude them, just don't use them and you're set.
