### ISSUE TITLE
php artisan module:migrate doesn't check time stambs 

### ISSUE THREAD

**Issue by ercanertan** [nWidart/laravel-modules#96]
I was trying to run **php artisan module:migrate** but there is a issue about migration.

I am assuming migration running by alphabetically. Is that right?

**Comment by armababy** [comment]
Migrations should be sorted [over here](https://github.com/nWidart/laravel-modules/blob/master/src/Migrations/Migrator.php#L103).
Can you give some filename examples, expected migration order and in what order actually they were run by laravel-modules.

**Comment by ercanertan** [comment]
Example here

2016_11_28_144737_create_services_table.php
2016_11_28_155717_create_services_translations_table.php

2016_11_28_104907_create_service_blocks_table.php
2016_11_28_105059_create_service_blocks_translations_table.php

My expectation was following
1.Migrate "service_blocks"
2.Migrate "services"

But migration was first creating "services" which is why I was having Foreign key error

**Comment by nWidart** [comment]
Look at your timestamps, they're not in order. That's why `2016_11_28_155717_create_services_translations_table` was sorted first.

**Comment by nWidart** [comment]
I cannot reproduce this as migrations have always been sorted before.

**Comment by armababy** [comment]
Can you give us environment on which this behaviour occurred? Mainly OS, if any virtualization (host, guest) etc.
Thanks.

**Comment by ercanertan** [comment]
Thanks for the quick respond, probably I will create migration files again.

**Comment by ercanertan** [comment]
I am using latest Mac OS X, Valet, Mysql 
thanks

**Comment by armababy** [comment]
So I did a little bit of testing and pretty much could not get sort wrong :(

So the command `module:migrate` actually does not call `getMigrations` method in laravel-modules `Migrator` class as I initially thought.

What actually happens is `Migrator` class only returns module migrations folder path and then the path is passed to Laravel's own `migrate` command. And the getting and sorting of files happen there.
And in this instance laravel-modules does no sorting whatsoever.

In my humble tests, i always got order right as you expected.

Internally laravel uses `sortBy` on a collection of files found and in turn `sortBy` uses (in this case) php function `asort` (low to high) sorting function.

It would be really great if you could try on some other system or setup. So we could pinpoint this problem that might be happening.

![migrations-test](https://cloud.githubusercontent.com/assets/219556/20734854/ea13e344-b6a4-11e6-805f-cae5c2fdad0c.png)

**Comment by ercanertan** [comment]
@armababy thank you for your time. I will do the test however

Could you pls try from different modules.

In my case I have 2 modules

**1.Module  ServiceBlock**
- 2016_11_28_104907_create_service_blocks_table.php
- 2016_11_28_105059_create_service_blocks_translations_table.php

**2.Module Service**
- 2016_11_28_144737_create_services_table.php
- 2016_11_28_155717_create_services_translations_table.php

**Comment by armababy** [comment]
@ercanertan Yes with this information, this is a behaviour of laravel-modules.
For multiple module migrations will resolve in alphabetical order or reverse alphabetical order if you specify `--direction="desc"` or `--d="desc"` option.

Apart from manually running migrations for modules in specific order, currently there is no way i can see to do this.

**Comment by ercanertan** [comment]
@armababy 
Did you run migration separately for each module on your test?

Because my issue is after following
`$ php artisan module:migrate`

I am expecting "multiple migration files" from separate module in order.Both modules has more then one migration files.

**Comment by armababy** [comment]
@ercanertan Yes I did run single `art module:migrate` my images are like that only because I do `dd`.
The test was to determine which module will be picked up first.

And with order 1 for `ServiceBlock` and order 0 for `Service` they did run like you wanted.

**Comment by ercanertan** [comment]
Wow I just tested and worked like a charm! 

Thank you very much for your time!

**Comment by armababy** [comment]
Great :)
I'll add that rollback thing to my improvements list if none will PR that I'll once I can.

**Comment by ercanertan** [comment]
oh yeah I just tested rollback and didn't work :) I come back to write actually.
But you already know.

Great feature 
Thanks again

**Comment by ercanertan** [comment]
How did rollback worked for you? because base on the order I am getting error!

**Comment by armababy** [comment]
I'll do PR hopefully today, with order respect for rest of migration commands - rollback, reset.

**Comment by ercanertan** [comment]
Thats great thank you!
