### ISSUE TITLE
Is it possible to introduce dependency packages separately in the module?

### ISSUE THREAD

**Issue by wilbur-oo** [nWidart/laravel-modules#960]
A specific dependency package is used in a module, so is it possible to compose composer.json in each module at runtime, and when the module is disabled, it also prevents composer from automatically loading dependencies under the module

**Comment by nWidart** [comment]
I doubt that's possible. Maybe if you make a custom composer plugin.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by Parables** [comment]
In my use case, I have 3 modules: USSD, API and Web.
I want to install `predis` and configure it as the cache for the USSD module.

How do I do that?
1.` cd Modules/USSD && composer require predis/predis`
2. install it in the main project root composer?

What if I want to use a different cache like MemCache for Web and Redis for USSD and API modules?
