### ISSUE TITLE
Add nwidart:stub-publish command

### ISSUE THREAD

**Issue by ntraykov** [nWidart/laravel-modules#964]
Similar to `php artisan stub:publish` command but that copies all stubs from `nwidart/laravel-modules/src/stubs`. I can create the command.

**Comment by nWidart** [comment]
What would be the difference on this one?

**Comment by ntraykov** [comment]
`php artisan stub:publish` publishes only Laravel's stubs, and specifficaly those that are allowed to be pusblished by Laravel. I want to customize many of the stubs offered by laravel-module. I needed to find them, and copy them by myself. Not a big deal but it would be really comfortable if I could just publish them, without even knowing where they are.

**Comment by nWidart** [comment]
Oh I see yeah. That sounds like a good idea. 👍

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by unionescreativas** [comment]
> Oh ya veo si. Eso suena como una buena idea.👍
Amigo en verdad si lo incluyes es genial , tu librería de modulo es lo mejor que e encontrado y estoy seguro que no soy el unico.

**Comment by madhurasri** [comment]
Is this command added?

**Comment by kodmanyagha** [comment]
Not added yet. But you can copy vendor/nwidart/laravel-modules/src/Commands/stubs folder to your accessible folder and then change `modules.stubs.path`  config value (config/modules.php, stubs.path array value).

**Comment by dcblogdev** [comment]
You can now publish the stubs using version 9.0.1:

```
php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider" --tag="stubs"
```

These publish the stubs to `stubs/nwidart-stubs`
