### ISSUE TITLE
Storage image/file

### ISSUE THREAD

**Issue by di1606** [nWidart/laravel-modules#965]
I want to save images in a module specific. In the documentation, I found this function `Module::getUsedStoragePath()` to get the path to the storage folder of the module, but I don't understand how to use it. 

When I display the return of the function I have `.../.../storage/app/modules/modules.used`, this file `modules.used` I do not understand its usefulness. In the documentation and on the internet I did not find answers to my question.

So I come to the official forum to clarify my questions.

So my question is:
- how can I use this function to record an image? 
- What is the purpose of the modules.used file?

**Comment by nWidart** [comment]
This method is not intended for external use, and only useful for the package itself.

You could have found out what it did by looking at the code, it's used to remember which module we're remembering in the CLI.

You can store assets however you like in your modules, and you can publish those assets into the public folder.

**Comment by di1606** [comment]
Okey

I've just created a function that allows me to save my storage folder but I can't retrieve my image (error 404)

```
class ThemeServiceProvider extends ServiceProvider
{

   public function boot()
   {
       ...
       $this->registerStorage();
   }

   protected function registerStorage()
   {
      $module= 'theme';
      Config::set('filesystems.disks.' . $module . '.public', [
            'driver' => 'local',
            'root' => storage_path('app/modules/' . $module . '/storage/public'),
            'url' => env('APP_URL').'/'.$module.'/storage',
            'visibility' => 'public',
        ]);
   }
...
}
```

my storage file has this structure 
`Modules/Theme/Storage > public > images`

<img width="107" alt="Capture d’écran 2020-04-18 à 16 53 45" src="https://user-images.githubusercontent.com/27860198/79641004-2dfeb980-8195-11ea-94ba-e51f01b1befd.png">

to access the file I created a symbolic link :` ln -s Modules/Theme/Storage/public public/theme`

The problem is that I can't get the image from the url : `asset('theme/images/image12.jpeg')`

**Comment by nWidart** [comment]
I haven't managed assets this way so couldn't really help you on this one.

**Comment by di1606** [comment]
I have solved my error, for those interested I leave my solution

I made a mistake in my symbolic link (a beginner's mistake) 

` ln -s /Users/.../.../Modules/Theme/Storage/public public/theme`

there must be an absolute link otherwise the link is broken.

**Comment by nWidart** [comment]
Ooh nice yeah, that's good to know! 👌

**Comment by nWidart** [comment]
I'll close this issue as you've found a solution 😄

**Comment by sarvjeetkushwaha2002** [comment]
sir can you help me. 
how to save image inside assets folder in modules?
