### ISSUE TITLE
Commands are not executed by my artisan scheduler

### ISSUE THREAD

**Issue by t-prod** [nWidart/laravel-modules#967]
Hi,

Commands are not executed by my artisan scheduler since I've made updates in composer.json. Eveyrhing worked fine bedore. Is the version 7.0 could be used with Laravel 6.1 ?
If I manually execute the command it's working.
 
![image](https://user-images.githubusercontent.com/1824638/79700772-84085580-8298-11ea-9487-46ba6f52d961.png)

Do you know the solution for this kind of problem ?

Thanks for your help

Regards

**Comment by nWidart** [comment]
As pointed in the readme file, 7.0 should not be used with laravel 6. Please use the correct version.

Besides that I don't see why your commands are not scheduled, it should work as expected. Maybe worth trying using version 6 of this package which corresponds to your laravel version.

**Comment by t-prod** [comment]
Everything is working by upgrading to Laravel 7 and Nwidart package version 7. I think it's on my side nothing wrong in your package. Sorry for that ;)
