### ISSUE TITLE
Running migrations

### ISSUE THREAD

**Issue by rbayley** [nWidart/laravel-modules#970]
Hi there!

I have a few modules, each of them have their own migrations.

If I ran

> php artisan module:migrate

Then all modules get migrated in alfabetical order, so:

1.  I noticed that the  getMigrations function sorts the migration files. Is this sort only within each module? If so, could they be sorted for all migration files?

2. If latter is not possible, is it possible to have command

> php artisan module:migrate Module1, Module4, Module3, Module2

with a comma separeted list of migrations to be executed in such order?

Any ideas about my issue?

**Warm regards and thanks for such great package**

**Comment by nWidart** [comment]
Hello,

It indeed sorts migration files, and also modules. You can set module order in its `module.json` file.

**Comment by rbayley** [comment]
Thanks!
