### ISSUE TITLE
Modules for API slowing down response times

### ISSUE THREAD

**Issue by kallekulp** [nWidart/laravel-modules#971]
I am using this package for my API so I could have my departments (medical) separated. After adding the package and separating everything into modules, I get extremely slow response times and I cannot figure out what that might be.

My database is properly indexed. I tried all the tips I found in this git including enabling cache etc. I also read people having 10+ modules with insanely fast times and I don't know what to do anymore.

For a simple API call to get all upcoming appointments takes almost 1.4-2 seconds while before it was 300ms-500ms. I am using a lot of repositories and interfaces and I think is this something that may be pulling the speed down??

[https://ibb.co/6rjrzCh](url)  is the image of the times what clockwork is showing me.

**Comment by nWidart** [comment]
Hi,

I have not experienced such drastic slowdowns. In fact none at all.
I have profiled bigger applications using blackfire.io to check this.
Maybe you can use this service too to try to see where the slow down is coming from?

**Comment by kallekulp** [comment]
@nWidart thank you for the response. I used the Blackfire logger, but I cannot make anything out of it as of yet. What I do see in clockwork is that it is registering all the modules which is good and I need that, but also boots them as well. I know this is how PHP and Laravel works. 

[https://ibb.co/mqszC93](url) Blackfire shows 10's of thousands of calls. Is this normal though?

**Comment by nWidart** [comment]
Yes, the number of calls is normal. You need to find "hot paths" in the graph, and see what is slowing down the execution.

I'm not sure I follow the clockwork graph, it says it needed 1331ms to register all the modules?
That seems excessively slow. 
Blackfire would should this is more detail, maybe something in the modules is slowing things down? But that would be every module has this same thing.
If you can share the backfire profile with me I can take a look if you want.

**Comment by kallekulp** [comment]
@nWidart I can share you the profile although I am not sure if this is helpful. 

I left the module providers the same, except binding interfaces with repositories. 

[https://blackfire.io/profiles/864c276c-cc2f-4493-b7b5-109ea8db77f1/graph](url)

**Comment by nWidart** [comment]
Thanks.
814ms with xdebug enabled doesn't look _that_ bad.

I see a bunch of things coming from Clockwork. Might be worth re-running the profiler without clockwork and xdebug enabled.

But besides that I don't see anything major, especially coming from the package.

**Comment by kallekulp** [comment]
Okay I disabled clockwork and things got a little bit better. What I tried was removing all the interface bindings from ServiceProviders and it got a little bit better but still. I feel like the boot time of the modules is triggering something but I might be wrong. 

I am using PHP v7.4.0, Apache v2.4.41 if that helps

**Comment by nWidart** [comment]
Do a new profile with everything disabled and look at that one. That will be more useful.

**Comment by kallekulp** [comment]
@nWidart here's new profile for you. Used blackfire straight from the terminal pinging my API.

[https://blackfire.io/profiles/dbc8cef3-12b5-4612-a60b-995d3b1d06ae/graph](url)

**Comment by nWidart** [comment]
Thanks. I see xdebug is still enabled so results will be off.

I can see each of you module service providers take ~10ms to startup. Make sure those don't do anything expensive in there.
Besides that I don't see anything out of the ordinary coming from the package at least.

You can use this profile data to pinpoint where the slowdown is coming from though.

**Comment by kallekulp** [comment]
Do you think binding about 5 interfaces inside providers is too extensive?

**Comment by nWidart** [comment]
I don't think so.

**Comment by kallekulp** [comment]
Okay! Thanks man, I will keep debugging it. Best wishes to you!

**Comment by kallekulp** [comment]
Just wanting to let you know I created a new blank laravel project, added all the modules again and ran artisan optimize with composer dump-autoload -o and somehow the loading times went back to normal.

**Comment by Alyka** [comment]
I have an issue similar to this. When working with about 10 - 15 modules, everything loads quite fast. But with about 30+ modules, it becomes terribly slow. I am working on a project that has about 100+ modules and the load speed become unbearable. I think performance degrades significantly with increasing number of modules.

**Comment by mewkhaleel** [comment]
https://github.com/nWidart/laravel-modules/issues/634#issuecomment-1865739105

In config/modules.php activate cache.

 'cache'=> ['enabled'  => true, 'key'=> 'laravel-modules', 'lifetime' => config('default.app.cache.ttl_seconds')],
