### ISSUE TITLE
[Support|Feature request] vendor:publish for module dependencies

### ISSUE THREAD

**Issue by renepardon** [nWidart/laravel-modules#972]
Hello,
I would like to install dependencies into my modules. Those dependencies have for example configuration or view files which can be published. Just normal behavior in a laravel application. But how can I publish such a config from a module dependency right into my modules Config folder? 
Is there an automated way to do so or do I have to copy the files manually and adjust my ServiceProvider to load them properly?

**Comment by nWidart** [comment]
Hi,

Module dependencies act as normal dependencies, so nothing to do there.
Module dependencies are in the vendor folder of your project.

Just call the commands from those dependencies you're using to publish there assets.

**Comment by renepardon** [comment]
I saw the `php artisan module:update` command, which installs the module dependencies in the root project. 
But I think it's a bit of overhead because I want to edit a dependency configuration within the module but not (again) within the main project. Imagine you develop a module and want to add this during runtime of the application. So you need to execute a bunch of commands and also adjust a dependency configuration but I don't want the enduser to change this kind of things. It should just work for him after he installed my module.

**Comment by nWidart** [comment]
Why would you add dependencies at runtime?

Either way I don't see the issue, laravel's publish command can do all this.

**Comment by renepardon** [comment]
My point is: I have an application based on the laravel-modules package and i want third party developers to develop independent packages for this project as well but the dependencies within those packages should not be installed within the root project and not during runtime. The new module should just work if i (for example) upload the module into proper folder.

**Comment by nWidart** [comment]
You could achieve this by building the architecture to support it.
