### ISSUE TITLE
Error when making new module

### ISSUE THREAD

**Issue by rebaz88** [nWidart/laravel-modules#974]
Hello,
There is an error when making module on fresh install of the package.
"php": "^7.4.4",
"laravel/framework": "^7.0",
"nwidart/laravel-modules": "^7.1"

 Return value of Nwidart\Modules\Activators\FileActivator::readJson() must be of the type array, null returned

at vendor/nwidart/laravel-modules/src/Activators/FileActivator.php:171
    167|         if (!$this->files->exists($this->statusesFile)) {
    168|             return [];
    169|         }
    170|
  _> 171|         return json_decode($this->files->get($this->statusesFile), true);_
    172|     }
    173|
    174|     /**
    175|      * Get modules statuses, either from the cache or from

\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

------------
adding empty brackets to module_stutuses.json fixed the error

**Comment by nWidart** [comment]
Thank for reporting this, I can't seem to be able to reproduce this.
Let's see if it's reported in the future 😄

**Comment by nessor** [comment]
I have the same problem.

php 7.4.2
laravel/framework 7.27.0
nwidart/laravel-modules"7.2.0

@rebaz88 Did you find a workaround?

**Comment by nessor** [comment]
Okay. Nvm. I found the problem. The modules_statusus.json was not valid.

**Comment by sehamsamy22** [comment]
> Okay. Nvm. I found the problem. The modules_statusus.json was not valid.

yes,that right solution.

**Comment by meeprakash25** [comment]
whats the solution?
