### ISSUE TITLE
Modules repository, Theme repository

### ISSUE THREAD

**Issue by quentingosset** [nWidart/laravel-modules#975]
Hi nWidart, great project that helps me code much cleaner! 
However I have a small question, currently I'm developing my FrontEnd as "FrontEnd Modules" but I would like to know if it's possible to create several "Module" directories. I explain myself
I wish I had the opportunity to have an architecture like this:

- Modules
  - Modules1
  - Modules2
- Themes
  - Theme1
  - Theme2

If this is possible how can I do it?

**Comment by emtiazzahid** [comment]
Not sure this info will help you or not 
You can add other directory like Modules with adding in your main composer.json file

```
"psr-4": {
        "App\\": "app/",
        "Modules\\": "Modules/",
        "Themes\\":"Themes/"
},
```

**Comment by quentingosset** [comment]
Thank you @emtiazzahid,
there's definitely an addition of repertoire in the composition. 
However I solved my problem, I reworked the nWidart module to have a separate one that manages the themes :)
