### ISSUE TITLE
could we composer require by defining local package?

### ISSUE THREAD

**Issue by njkd5** [nWidart/laravel-modules#976]
`"repositories": [
        {
            "type": "path",
            "url": "Modules/*"
        }
    ]`
we can define this in composer.json,then we can composer require vendor/package
is it ok?

**Comment by nWidart** [comment]
Hi, yes you can do this.
A module acts as a normal composer package, meaning you have access to all composer features.

**Comment by shahidkarimi** [comment]
Example?
