### ISSUE TITLE
Publish Assets 

### ISSUE THREAD

**Issue by prg-hussam** [nWidart/laravel-modules#979]
Hi there!

When i run (php artisan module:publish) the main.scss file (Modules/Admin/Resources/assets/sass/main.scss) compiled successfully in (Modules/Admin/Assets/css/admin.css)
But inside public/modules i found sass/main.scss not css/admin.css

can you help ?

Hope you have understood my problem
excuse my English 🙂

**Comment by nWidart** [comment]
Hi,

I don't understand the question. You can use the publish command to publish the compiled css.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
