### ISSUE TITLE
Method Nwidart\Modules\Laravel\LaravelFileRepository::enabled does not exist

### ISSUE THREAD

**Issue by ucanbehack** [nWidart/laravel-modules#981]
**Method Nwidart\Modules\Laravel\LaravelFileRepository::enabled does not exist**

I'm using `"laravel/framework": "^7.0",` and ` "nwidart/laravel-modules": "^7.0" `

I have also tried with` "nwidart/laravel-modules": "^6.0"` but getting the same error.

**Comment by nWidart** [comment]
This method has been renamed: https://github.com/nWidart/laravel-modules/releases/tag/6.0.0
