### ISSUE TITLE
BadMethodCallException Method Illuminate\Events\Dispatcher::fire does not exist.

### ISSUE THREAD

**Issue by iateadonut** [nWidart/laravel-modules#984]
installed bagisto and trying to build a module on top of it:

:/var/www/supremeSEA1/bagisto$ php7.3 artisan module:make poparser
Created : /var/www/supremeSEA1/bagisto/Modules/Poparser/module.json
Created : /var/www/supremeSEA1/bagisto/Modules/Poparser/start.php
Created : /var/www/supremeSEA1/bagisto/Modules/Poparser/Http/routes.php
Created : /var/www/supremeSEA1/bagisto/Modules/Poparser/Resources/views/index.blade.php
Created : /var/www/supremeSEA1/bagisto/Modules/Poparser/Resources/views/layouts/master.blade.php
Created : /var/www/supremeSEA1/bagisto/Modules/Poparser/Config/config.php
Created : /var/www/supremeSEA1/bagisto/Modules/Poparser/composer.json
Created : /var/www/supremeSEA1/bagisto/Modules/Poparser/Resources/assets/js/app.js
Created : /var/www/supremeSEA1/bagisto/Modules/Poparser/Resources/assets/sass/app.scss
Created : /var/www/supremeSEA1/bagisto/Modules/Poparser/webpack.mix.js
Created : /var/www/supremeSEA1/bagisto/Modules/Poparser/package.json
Created : /var/www/supremeSEA1/bagisto/Modules/Poparser/Database/Seeders/PoparserDatabaseSeeder.php
Created : /var/www/supremeSEA1/bagisto/Modules/Poparser/Providers/PoparserServiceProvider.php
Created : /var/www/supremeSEA1/bagisto/Modules/Poparser/Http/Controllers/PoparserController.php
Module [Poparser] created successfully.

$ php7.3 artisan clear-compiled

   BadMethodCallException  : Method Illuminate\Events\Dispatcher::fire does not exist.

  at /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:103

[2020-05-12 03:07:01] local.ERROR: Method Illuminate\Events\Dispatcher::fire does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Events\\Dispatcher::fire does not exist. at /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:103)
[stacktrace]
#0 /var/www/supremeSEA1/bagisto/vendor/nwidart/laravel-modules/src/Module.php(267): Illuminate\\Events\\Dispatcher->__call('fire', Array)
#1 /var/www/supremeSEA1/bagisto/vendor/nwidart/laravel-modules/src/Module.php(257): Nwidart\\Modules\\Module->fireEvent('register')
#2 /var/www/supremeSEA1/bagisto/vendor/nwidart/laravel-modules/src/FileRepository.php(299): Nwidart\\Modules\\Module->register()
#3 /var/www/supremeSEA1/bagisto/vendor/nwidart/laravel-modules/src/Providers/BootstrapServiceProvider.php(22): Nwidart\\Modules\\FileRepository->register()
#4 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(616): Nwidart\\Modules\\Providers\\BootstrapServiceProvider->register()
#5 /var/www/supremeSEA1/bagisto/vendor/nwidart/laravel-modules/src/ModulesServiceProvider.php(38): Illuminate\\Foundation\\Application->register(Object(Nwidart\\Modules\\Providers\\BootstrapServiceProvider))
#6 /var/www/supremeSEA1/bagisto/vendor/nwidart/laravel-modules/src/LaravelModulesServiceProvider.php(15): Nwidart\\Modules\\ModulesServiceProvider->registerModules()
#7 [internal function]: Nwidart\\Modules\\LaravelModulesServiceProvider->boot()
#8 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#9 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#11 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\\Container\\Container->call(Array)
#14 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(839): Illuminate\\Foundation\\Application->bootProvider(Object(Nwidart\\Modules\\LaravelModulesServiceProvider))
#15 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Nwidart\\Modules\\LaravelModulesServiceProvider), 43)
#16 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(840): array_walk(Array, Object(Closure))
#17 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#18 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(219): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#19 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(156): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#20 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#21 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#22 /var/www/supremeSEA1/bagisto/public/index.php(74): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#23 {main}
"}

**Comment by nWidart** [comment]
Hi, which version of laravel are you using?
The errors seems to be a versions mismatch, please refer to the versions table on the readme to use the appropriate laravel-modules version for you version of laravel.

**Comment by iateadonut** [comment]
thank you so much for the fast reply:

php7.3 artisan
Laravel Framework 6.18.1

grep -i module composer.json
        "nwidart/laravel-modules": "^3.2",

solution i tried:
$ composer require nwidart/laravel-modules:^6

$ php7.3 artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider" --force
Copied File [/vendor/nwidart/laravel-modules/config/config.php] To [/config/modules.php]
Publishing complete.


$ php7.3 artisan clear-compiled

$ php7.3 artisan module:make poparser

In InvalidActivatorClass.php line 9:
                                                                                                                    
  You don't have a valid activator configuration class. This might be due to your config being out of date.         
   Run php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider" --force to publish the up to date configuration
  e up to date configuration

**Comment by iateadonut** [comment]
here's the stack trace

[2020-05-12 07:45:44] local.ERROR: You don't have a valid activator configuration class. This might be due to your config being out of date. 
 Run php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider" --force to publish the up to date configuration {"exception":"[object] (Nwidart\\Modules\\Exceptions\\InvalidActivatorClass(code: 0): You don't have a valid activator configuration class. This might be due to your config being out of date. 
 Run php artisan vendor:publish --provider=\"Nwidart\\Modules\\LaravelModulesServiceProvider\" --force to publish the up to date configuration at /var/www/supremeSEA1/bagisto/vendor/nwidart/laravel-modules/src/Exceptions/InvalidActivatorClass.php:9)
[stacktrace]
#0 /var/www/supremeSEA1/bagisto/vendor/nwidart/laravel-modules/src/LaravelModulesServiceProvider.php(61): Nwidart\\Modules\\Exceptions\\InvalidActivatorClass::missingConfig()
#1 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Nwidart\\Modules\\LaravelModulesServiceProvider->Nwidart\\Modules\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#2 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build(Object(Closure))
#3 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve('Nwidart\\\\Modules...', Array, true)
#4 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve('Nwidart\\\\Modules...', Array)
#5 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make('Nwidart\\\\Modules...', Array)
#6 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Container/Container.php(1245): Illuminate\\Foundation\\Application->make('Nwidart\\\\Modules...')
#7 /var/www/supremeSEA1/bagisto/vendor/nwidart/laravel-modules/src/Commands/ModuleMakeCommand.php(39): Illuminate\\Container\\Container->offsetGet('Nwidart\\\\Modules...')
#8 [internal function]: Nwidart\\Modules\\Commands\\ModuleMakeCommand->handle()
#9 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#10 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#12 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#13 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#14 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#15 /var/www/supremeSEA1/bagisto/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#17 /var/www/supremeSEA1/bagisto/vendor/symfony/console/Application.php(1001): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /var/www/supremeSEA1/bagisto/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand(Object(Nwidart\\Modules\\Commands\\ModuleMakeCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/www/supremeSEA1/bagisto/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /var/www/supremeSEA1/bagisto/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /var/www/supremeSEA1/bagisto/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 {main}
"}

**Comment by iateadonut** [comment]
php7.3 artisan config:cache  worked.  (rather than php7.3 artisan config:clear)
