### ISSUE TITLE
change the api endpoint to modules

### ISSUE THREAD

**Issue by nusendra** [nWidart/laravel-modules#985]
Currently, we can set the api endpoint in the modules like this

```
Route::prefix('test')->middleware('someMiddleware')->group(function() {
  Route::get('products')->blabla....
  // here is the list of endpoints
});
```
Then we can access those routes using this endpoint
`http://localhost/api/test/products`

But, I want the endpoint like this
`http://localhost/test/api/products`

how to achieve this?

**Comment by nWidart** [comment]
Open your `RouterServiceProvider`, and change the `mapApiRoutes` method. This is the one adding the prefix. 
You have full control over everything in your module.

**Comment by nusendra** [comment]
Thanks @nWidart
