### ISSUE TITLE
TestCase not found

### ISSUE THREAD

**Issue by iateadonut** [nWidart/laravel-modules#986]
When creating a unit test through php artisan module:make-test, the created unit test uses Tests/TestCase, which is not found.

One possible fix is to "use PHPUnit\Framework\TestCase;" instead of "use Tests/TestCase;"

**Comment by nWidart** [comment]
Hm it's supposed to point to this one: https://github.com/laravel/laravel/blob/master/tests/TestCase.php

**Comment by iateadonut** [comment]
sorry about this.  i'm working with bagisto, and it looks like they've modified the base program a lot.

thank you for your reply.
