### ISSUE TITLE
Unable to Use FCM in Module Notification Class

### ISSUE THREAD

**Issue by abhiburk** [nWidart/laravel-modules#987]
Hey
I have implemented notification class in one of the module and in that I am using method from [https://github.com/benwilkins/laravel-fcm-notification](url) called toFcm but when I send notification through this class I get an error 
`Call to undefined method Modules\Blog\Notifications\NotifyBlogChannel::toFcm()`

When I use same toFcm method in Laravel Default channel (in app/notification) then that works perfectly.
It seem it doesn't work in Module Notifications

**Comment by nWidart** [comment]
Hi, 

This is not related to this package.
Make sure your class is imported correctly as the error shows.
