### ISSUE TITLE
module:seed sort not based on modules_statuses.json

### ISSUE THREAD

**Issue by quentingosset** [nWidart/laravel-modules#988]
Hey, I'm coming to you because I have a question that you might be able to help me with.

I am currently developing a series of modules for my app and when I seeded the modules, I found that the seed is based on the structure of the Module directory. It may be annoying if an example module starting with the letter Z should be seeded first so that the other modules can be seeded from module Z.

Is there an option to add to the command or is this not possible?
If it's not possible do you think it's interesting ? if you don't have time I can look to make a PR of this option (be careful this will be my first PR on an Open-Source project ;p )

**Comment by nWidart** [comment]
All database commands should use the order of each module, which you can find in the `module.json` file.

**Comment by 3NdR1m** [comment]
And how is this file configured?
