### ISSUE TITLE
Class 'Modules\Sprokets\Providers\SproketsServiceProvider' not found

### ISSUE THREAD

**Issue by hillelcoren** [nWidart/laravel-modules#99]
I'm trying to install a module through Packagist.

https://packagist.org/packages/invoiceninja/sprockets

When installing using `php artisan module:install invoiceninja/sprockets` I see the following:

    [Nwidart\Modules\Exceptions\ModuleNotFoundException]  
    Module [Sprockets] does not exist!  

By changing the command to `php artisan module:install invoiceninja/sprockets --type=github` the module installs but I still see an error:

    Cloning into '/Users/hillel/Dropbox/MacBook/ninja/Modules/Sprockets'...
    Already on 'master'
    Your branch is up-to-date with 'origin/master'.

    [Nwidart\Modules\Exceptions\ModuleNotFoundException]  
    Module [Sprockets] does not exist!     

From this point forward all requests result in the following error:

    [Symfony\Component\Debug\Exception\FatalThrowableError]               
    Class 'Modules\Sprokets\Providers\SproketsServiceProvider' not found  

'Modules' was added to the composer.json file. I've tried running `composer dump-autoload` and `php artisan optimize` but no luck. Any tips how on how to track this down would be very much appreciated.

**Comment by hillelcoren** [comment]
I've also tried `composer dump`

**Comment by nWidart** [comment]
Hello,

Might be something related to case sensitivity. Have you checked `modules` and `Modules`?

**Comment by hillelcoren** [comment]
Thanks for your quick reply!

This was caused by a typo in the module\class name.

**Comment by nWidart** [comment]
Ah cool ok. 👍

**Comment by lucassmacedo** [comment]
i have the same problem

**Comment by dothem1337** [comment]
same issue here, name's are correct
