### ISSUE TITLE
Unable to use mix

### ISSUE THREAD

**Issue by faadmin** [nWidart/laravel-modules#990]
Hi,

I have previously used it but without mix. Now, Im trying to use mix. But Im getting the below err:

Facade\Ignition\Exceptions\ViewException
Unable to locate Mix file: /js/admin.js. (View: C:\App\htdocs\App\Modules\Admin\Resources\views\layouts\master.blade.php) 

Im using Laravel 7.

**master.blade.php**
<script src="{{ mix('js/admin.js') }}"></script>

**webpack.mix.js**
```
const dotenvExpand = require('dotenv-expand');
dotenvExpand(require('dotenv').config({ path: '../../.env'/*, debug: true*/}));

const mix = require('laravel-mix');
require('laravel-mix-merge-manifest');

mix.setPublicPath('../../public').mergeManifest();

mix.js(__dirname + '/Resources/assets/js/app.js', 'js/admin.js')
    .sass( __dirname + '/Resources/assets/sass/app.scss', 'css/admin.css');

if (mix.inProduction()) {
    mix.version();
}

```
Im writing my js under "\Modules\Admin\Resources\assets\js\app.js"

app.js is getting created under "public/modules/admin/js" but why Im getting the above error.

What am I missing?

**Comment by nWidart** [comment]
Hi,

There's documentation about mix: https://nwidart.com/laravel-modules/v6/basic-usage/compiling-assets
