### ISSUE TITLE
Laravel 5.5 - file_get_contents web.stub failed to open stream

### ISSUE THREAD

**Issue by Jimmea** [nWidart/laravel-modules#991]

**Comment by Jimmea** [comment]
I'm using laravel 5.5
"nwidart/laravel-modules": "^2.0",

When i create a module. It have show a error ...
vendor/nwidart/laravel-modules/src/Support/../Commands/stubs/routes/web.stub): failed to open stream: No such  
   file or directory

**Comment by nWidart** [comment]
Sorry this vendor is not supported.
