### ISSUE TITLE
"Target is not instantiable while building" Upgrade laravel 7

### ISSUE THREAD

**Issue by neoplomero** [nWidart/laravel-modules#993]
Hi,

I'm upgrading to Laravel 7. I've many modules with their own RepositoryProviders. The app works fine but after upgrading laravel and nwidart/modules (laravel 7) is launching an error on composer dump-autoload.

Looks like is when trying to instantiate a repository from one module on another module

```
 @php artisan package:discover --ansi

   Illuminate\Contracts\Container\BindingResolutionException

  Target [Modules\Driver\Repositories\Interfaces\Driver] is not instantiable while building [Modules\Gdpr\Console\Anonymize, Modules\Gdpr\Services\GdprService].

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:1011
    1007|         } else {
    1008|             $message = "Target [$concrete] is not instantiable.";
    1009|         }
    1010|
  > 1011|         throw new BindingResolutionException($message);
    1012|     }
    1013|
    1014|     /**
    1015|      * Throw an exception for an unresolvable primitive.

      +23 vendor frames
  24  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

If I moved to previous laravel and nwidart/modules version everything is fine.

Any idea why this could be happening?

**Comment by nWidart** [comment]
Hi,

It could be that the module containing the repository you're trying to get isn't booted yet.

**Comment by neoplomero** [comment]
Hi, 

why the versions would affect this? Is there any way of setting the order this modules will be booted?

**Comment by nWidart** [comment]
Not sure why it changed no. 
The order can be set via the module.json file.

**Comment by neoplomero** [comment]
Well... the order worked!! Thanks a lot you're the best. 

<3<3<3

**Comment by neoplomero** [comment]
I thought the order had fixed this but no. Still giving the error during the composer dump-autoload

**Comment by PiotrSiemienik** [comment]
Hi,

it looks like the service providers in the modules are not autoloaded before the artisan commands are built. The autoloading works with `"nwidart/laravel-modules": "^5.0",`, but it fails with "nwidart/laravel-modules": "^6.0" and "nwidart/laravel-modules": "^7.0".

Are there any configuration options we should check?

**Comment by nWidart** [comment]
Hm yes: [this part has been added](https://github.com/nWidart/laravel-modules/blob/master/config/config.php#L194-L212), you can re-publish the config with `--force` or manually diff the 2 files.

**Comment by PiotrSiemienik** [comment]
Thanks. This one was one of 2 issues I had to fix.

1. Fixed `Modules\Gdpr\Console\Anonymize` command, so its constructor does not expect `Modules\Gdpr\Services\GdprService` service. Previously Laravel was attempting to inject the service without running providers inside modules whenever we use any Artisan command.
2. Updated the config as you recommended and generated `modules_statuses.json`

**Comment by nWidart** [comment]
Ah great!

For future users running into the same issue, there is a command to migrate to version 6: `php artisan module:v6:migrate`, this will generate this `module_statuses.json` file and populate it.

**Comment by HadaraWeb** [comment]
Check your Service Provider: and ensure the package is registered rightly according to the laravel version you are using
