### ISSUE TITLE
Changing the order value doesn't affect order of routes

### ISSUE THREAD

**Issue by oleaass** [nWidart/laravel-modules#994]
**Package Version:** 7.1.0

Not sure if this is a bug, or if it's me doing something wrong. But I cannot seem to get the routes to load in the order I want.

The `module:list` command show's that `Page` has order value 9999

```
> artisan module:list
+-------+---------+-------+---------------------+
| Name  | Status  | Order | Path                |
+-------+---------+-------+---------------------+
| Core  | Enabled | 0     | /****/Modules/Core  |
| File  | Enabled | 0     | /****/Modules/File  |
| Page  | Enabled | 9999  | /****/Modules/Page  |
| Place | Enabled | 0     | /****/Modules/Place |
+-------+---------+-------+---------------------+

```
but from the image below it's clear that the routes from `Page` is loaded before `Place`, which causes the catchall route in Page to override everything in Place

![](https://i.imgur.com/qkDlHMT.png)

I have also tried to change the order value for the `File` module to a number higher than `9999`, but no changes to route order.

When dumping the value from `FileRepository::getOrdered()` the modules are listed in the correct order.

**Comment by oleaass** [comment]
The more I look into this, the more confused I get..

I now added a `var_dump()` in each of the modules `register()` method

```
string(31) "CoreServiceProvider::register()"
string(31) "FileServiceProvider::register()"
string(31) "PageServiceProvider::register()"
string(32) "PlaceServiceProvider::register()"
```

So `Page` is triggered before `Place`. But when I add this

```
dd($this->getOrdered());
```

to `FileRepository::register()` I get this

```
array:4 [▼
  "Core" => Nwidart\Modules\Laravel\Module {#2782 ▶}
  "File" => Nwidart\Modules\Laravel\Module {#2794 ▶}
  "Place" => Nwidart\Modules\Laravel\Module {#2802 ▶}
  "Page" => Nwidart\Modules\Laravel\Module {#2798 ▶}
]
```

**Comment by nWidart** [comment]
Hm this is weird indeed, the modules should be booted using the ordered method as you mentioned.

**Comment by oleaass** [comment]
That's what I thought. Do you have any debugging tips that I can try? Not too familiar with the internals of this package, so now I'm just adding var_dumps spitting out name of class and method to see what's getting triggered

**Comment by nWidart** [comment]
If you have xdebug setup you can put breakpoints and go from there.
Otherwise var_dump's are another way.

**Comment by oleaass** [comment]
@nWidart I have found the issue. It's caused by Laravel's auto discover. Since the providers are listed in the composer.json, Laravel autodetects it and they are actually loaded in before even your package is triggered.

Solution to the issue, remove the provider from the module's composer.json and run `composer update`

**Comment by nWidart** [comment]
Ooh that's interesting. Very good to know, thanks!

**Comment by oleaass** [comment]
Glad I could help sort it out! Did a quick writeup of the issue - [Laravel modules order not being obeyed](https://medium.com/@aass.ole/laravel-modules-order-not-being-obeyed-eb1b4423c9f?sk=b729c555e0af059bb1876f4fd76bb2e3)

**Comment by nWidart** [comment]
Thanks! Very interesting.
I wonder if the modules shouldn't have that part in their composer file because of it.

**Comment by oleaass** [comment]
I don't think they should. This probably also means that you won't be able to disable modules.

**Comment by oleaass** [comment]
Closing this issue since it's solved by #996

**Comment by samerzaki** [comment]
@oleaass hello, I tried your way by deleting (serviceProvider) from each module composer.json but it didn't work. 
laravel still load modules instead of nWidart
the only solution that worked was writing the package name in main composer.json (dont-discover)
but that need to write all packages names
so, any solutions ?

**Comment by jhourlad** [comment]
This also goes when doing a `php artisan migrate:fresh`. Constraints cause errors when a dependent module executes first before the parent module.

`SQLSTATE[HY000]: General error: 1005 Can't create table `humanus_v1`.`payroll_templates` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `payroll_templates` add constraint `payroll_templates_company_id_foreign` foreign key (`company_id`) references `companies` (`id`))
`
