### ISSUE TITLE
Laravel 7 - Load components from the module directory

### ISSUE THREAD

**Issue by iamine** [nWidart/laravel-modules#997]
Hi,

It's possible to load components from the module directory?

because i want each module to have its own components, but it's still loading from 'resources/components' directory

**Comment by nWidart** [comment]
I haven't used laravel's component but I don't see why not. You might have to tell laravel where to find them though.

**Comment by iamine** [comment]
Components are like views, and Laravel 7 load them by default from 'resources/views/components' folder, they also provide like a Controller for components and Laravel load them from app/View folder it's new Feature on Laravel 7

I wich it this will be implemented on your package and load components for each Module from

Modules/Module/Resources/views/components for blade files
Modules/Module/View for components controllers

instead of loading all components from 'resources/views/components', and cannot separate each module if he has it's own components

**Comment by nWidart** [comment]
It's documented here https://laravel.com/docs/7.x/blade#components

**Comment by iamine** [comment]
Thank you @nWidart , That's what I'm using now, I'm registering them manually, i wish if they were loaded automatically for each module :)

**Comment by nWidart** [comment]
Well there might be a way. Look at how laravel loads those default spaces and maybe we can do the same for modules.
But that manual way works for now I suppose.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.

**Comment by BoraVivek** [comment]
Looking for the components to be implemented in Laravel modules, as components are quite handy and it must be implemented in the modules.

**Comment by nWidart** [comment]
Hi, you can already use these in modules.

**Comment by BoraVivek** [comment]
> Hi, you can already use these in modules.

So can i create a component folder inside each module and use it that way or do i have to use it through root components folder? 

As I don't see any artisan command available in modules for making components.

**Comment by nWidart** [comment]
As mentioned above, you need to see how laravel needs to load these components, and do the same here.
There is no command no.

**Comment by t-prod** [comment]
Hi,

If we have only the view in components directory how can we do to register it ?
It's not interpreted if we move on a module the Resources/Views/components

I try in the service provider with this but does not work :

`Blade::component('livewire::components.bootstrap.loading', 'livewire-loading');`

Any ideas ?

**Comment by uarefans** [comment]
```
Create a module example: One
Create a folder 'components' inside views
Create a file example: test.blade.php

How to call from others module
    @component('one::components.test')
    
    @endcomponent
```
