### ISSUE TITLE
Rename stub physical file name

### ISSUE THREAD

**Issue by yashiroiori** [nWidart/laravel-modules#998]
Hi.
I make an skeleton to create a module to use into my core system, run greats, but in some files need set the name using module name, it's posible to that??

Example:
Generate model using stub file named as 'Model.php', but I need rename manually name to the correct name i need, make module Customer and the model may say 'Customer.php' but in the config stubs the name are Model.php, I can change the name some way??

The same case are with request file, generate 2 files 'ModelStoreRequest' and 'ModelUpdateRequest' instance of 'Model' may say 'CustomerStoreRequest' and 'CustomerUpdateRequest'

Into the files namespace an class name are correct, only just need physical rename file name without make manually

![image](https://user-images.githubusercontent.com/17031855/83491683-c4eab100-a477-11ea-9ceb-fe015a760dcc.png)

**Comment by nWidart** [comment]
It's not possible to change the stub names no.
I don't see the use-case for naming the stubs, are they're changed anyway when generating the code.

**Comment by nWidart** [comment]
I'll close this as there hasn't been a reply in a while, feel free to comment if needed.
